INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chore', 'n.  家庭杂务； 困难的工作； 令人厌烦的工作', 2501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'semester', 'n.  学期', 2502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'until', 'prep&conj.  直到…时， 到…为止； 直到…', 2503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'strategy', 'n.  谋略， 战略， 策略', 2504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dull', 'adj.  乏味的， 单调的； 晦暗的； 愚钝的， 笨的； 钝的', 2505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'reason', 'v.  推断， 分析； 推论， 推理； 理喻， 劝告 n. 原因，理由；理性，理智', 2506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thought', 'n.  想法， 见解； 思考， 思维； 关心， 注意； 思想，', 2507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ring', 'n.  戒指； 环， 圆圈； 铃声； 电话； 团伙， 帮派； 拳击台， 摔跤台， 马戏场', 2508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'legend', 'n.  传说； 传奇人物', 2509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'taste', 'v.  有…味道； 品尝； 体验， 感受 n. 滋味；味觉，口味；鉴赏力；兴趣，爱好', 2510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ship', 'v.  用船运； 装运， 运送 n. 船，舰', 2511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'anywhere', 'adv.  在什么地方， 在任何地方； 随便什么地方', 2512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'professional', 'adj. 职业的；专业的 n.  专业人员； 自由职业者', 2513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cheese', 'n.  干酪， 奶酪', 2514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nineteenth', 'num. 第十九 n.  十九分之一', 2515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cake', 'n.  饼， 糕， 蛋糕', 2516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'neighbor', 'n.  邻居； 邻国', 2517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'gentle', 'adj.  温柔的， 慈祥的； 文雅的， 有礼貌的； 温和的， 暖和的', 2518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shoulder', 'v.  肩负， 承担 n. 肩', 2519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dance', 'v.  跳舞 n. 舞，舞蹈；舞曲，舞会', 2520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'boil', 'v. 沸腾，煮沸 n.  沸腾', 2521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'remain', 'v.  仍然是， 依旧是； 留下， 逗留； 剩余， 余留； 留待', 2522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eye', 'n.  眼， 眼睛； 虹膜； 眼状物', 2523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'himself', 'pron.  他自己； 他亲自， 他本人', 2524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'toilet', 'n.  厕所， 盥洗室', 2525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'envelope', 'n.  信封', 2526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dictionary', 'n.  词典， 字典', 2527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'slow', 'adv.  慢慢地 adj. 慢的；迟钝的，不灵巧的；不忙碌的 v. 慢下来，减速', 2528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'turkey', 'n.  火鸡； [T-] 土耳其', 2529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'letter', 'n.  信， 函件； 字母', 2530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tasty', 'adj. 美味的；引起食欲的 n.  好吃的东西； 吸引人的东西', 2531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'maybe', 'adv.  大概， 也许', 2532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'another', 'pron. 再一个，另一个 adj.  又一的， 再一个的； 另一的， 别的； 不同的', 2533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'enemy', 'n.  敌人， 仇敌', 2534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worth', 'adj. 相当于…价值的，值得…的 n.  价值， 财产', 2535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'new', 'adv.  新近 adj. 新的；新鲜的，新型的，流行的；更新的', 2536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'helicopter', 'n.  直升机', 2537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'are', 'v.  存在， 是', 2538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'advertisement', 'n.  广告， 公告； 广告活动， 宣传', 2539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'disabled', 'adj.  有残疾的', 2540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'watermelon', 'n.  西瓜', 2541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'arm', 'v.  以装备； 提供， 配备； n. 臂，前肢；臂状物，扶手；', 2542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'popular', 'adj.  流行的， 通俗的， 大众的； 受欢迎的', 2543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'art', 'n. 美术，艺术；技术，技艺；', 2544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'mom', 'n.  妈妈', 2545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'black', 'adj.  黑色的； 黑暗的； 黑人的； 不加奶的； 黯淡的， 毫无希望的', 2546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tour', 'n&v.  旅行， 旅游', 2547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'call', 'v.  把…叫做， 把…称为； 打电话给； 叫， 大声说出； 召唤， 传唤； 召开，', 2548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'calm', 'adj. 镇静的，镇定的；平静的，无风的 v.  平静； 镇静', 2549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'such', 'adv.  那么 adj. 这样的，这种的；那么的，如此程度的；上述的，该', 2550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kick', 'n&v.  踢', 2551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ask', 'v.  询问， 问； 要求', 2552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'describe', 'v.  描写， 描述； 说明', 2553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'through', 'adv.  从头到尾， 自 prep. 穿过，通过；在整个…期间，从头到尾；凭借，经由', 2554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'jazz', 'adj.  爵士乐的 n. 爵士乐', 2555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'run', 'v.  [run-run, running] 跑， 奔跑； 行驶， 驾驶； 蔓延， 伸展； 操作； 竞', 2556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'either', 'adv.  也 adj. 任一的，每一的', 2557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'view', 'v.  考虑， 认为； 观察， 看 n. 看法，观点；视野，眼界；景色，风景', 2558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ours', 'pron.  我们的', 2559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'white', 'adj. 白色的，白的；白种的 n.  白色； 蛋白； 眼白', 2560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'furniture', 'n.  家具', 2561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'huge', 'adj.  庞大的， 巨大的', 2562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yourself', 'pron.  你自己； 你亲自', 2563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'donate', 'v.  捐赠， 赠送', 2564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'helpful', 'adj.  有益的， 有用的； 给予帮助的， 肯帮忙的', 2565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'those', 'pron.  那些', 2566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worry', 'v. 担心，发愁；困扰，折磨 n.  担心， 发愁， 忧虑', 2567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'imagine', 'v.  想象， 设想； 料想， 猜想', 2568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'town', 'n.  镇， 市镇； 市区， 市中心', 2569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'might', 'modal verb. 可以〔用于礼貌地提出建议〕 n. 力量；威力；权力', 2570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'telephone', 'v.  打电话 n. 电话', 2571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'girl', 'n.  姑娘， 女孩； 女儿', 2572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'delicious', 'adj.  美味的； 芬芳的； 宜人的', 2573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worse', 'adj. 更坏的；更糟的；更差的 n. 更差[坏]的事物 adv. 更严重地；更厉害地', 2574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'whatever', 'pron.  无论什么， 不管什么； 任何…的事物， 凡是…的东西', 2575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'camp', 'v.  露营， 扎营 n. 营地，露营', 2576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'volunteer', 'v.  自愿 n. 志愿者，志愿兵', 2577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'museum', 'n.  博物馆', 2578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'everywhere', 'adv.  到处， 各处， 无论何处', 2579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worst', 'adv&adj.  最坏， 最差， 最糟', 2580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'clothing', 'n.  服装， 衣着', 2581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'aloud', 'adv.  出声地， 大声地', 2582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shop', 'n.  商店， 店铺； 工厂， 车间', 2583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Christmas', 'n.  圣诞节', 2584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'string', 'n.  弦， 线， 细绳； 一串， 一行', 2585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'September', 'n.  九月', 2586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'distance', 'n.  距离， 间距； 遥远， 远方； 冷淡， 疏远； 久远', 2587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'color', 'n. 颜色；颜料；肤色 vt.  给…着色', 2588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'truck', 'n.  卡车， 载重汽车； 敞篷货车', 2589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'book', 'v.  预订，　预约 n. 书，书籍；本子，簿册；', 2590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'show', 'v.  表明， 证明； 显示， 出示； 带领； 教， 告知； 演出， 放映； 显现，', 2591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nor', 'conj&adv.  也不， 也没有', 2592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Mars', 'n.  火星； 战神', 2593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'not', 'adv.  不， 没， 不是', 2594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'arrive', 'v.  到达， 到来； 来临； 达到， 达成', 2595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'street', 'n.  街道， 马路', 2596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'now', 'adv.  现在， 如今； 此刻', 2597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'statement', 'n.  陈述， 声明； 结算单， 报表', 2598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Tuesday', 'n.  星期二', 2599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shoe', 'n.  鞋', 2600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'race', 'n.  比赛， 赛跑； 竞争； 人种， 种族', 2601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'near', 'adv. 近，在近处 adj.  近的， 接近的； 亲近的 prep. 靠近，接近', 2602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'introduce', 'v.  介绍； 引进， 传入； 提出供讨论； 采用', 2603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'war', 'n.  战争； 斗争， 竞争', 2604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'way', 'n.  方法， 手段； 路， 路线； 方面； 方向； 习俗， 作风； 状况， 状态', 2605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'what', 'pron.  什么； 多么， 何等…的事物', 2606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'duty', 'n.  责任， 义务； 职责， 职务； 税， 关税', 2607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'risk', 'v.  冒…的危险， 使遭受危险 n. 危险，风险；引起危险的事物；冒险', 2608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'window', 'n.  窗户， 窗口', 2609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rise', 'v.  [rose-risen] 升起， 上升； 起立； 起床； 上涨， 增加； 反抗， 起义', 2610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'penny', 'n.  便士， 分', 2611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'play', 'v.  玩， 游戏； 演奏， 播放； 扮演， 演出； 参加， 打', 2612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yard', 'n.  院子， 场地； 码', 2613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'decide', 'v.  决定， 对…作出抉择； 使下决心', 2614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rent', 'v. 租借，租用；出租，出借 n.  租金； 出租； 裂缝， 分歧', 2615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'when', 'adv. 什么时候，何时；在…的时候 conj.  在…时， 当…时； 然后', 2616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fan', 'v.  煽动， 激起 n. 扇子；扇形物；狂热爱好者，迷', 2617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'anxious', 'adj.  焦虑的， 发愁的， 令人焦急的； 渴望的， 急', 2618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'slice', 'v. 切成片，削 n.  薄片， 切片； 一份， 部分', 2619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'far', 'adv. 远；久远；很大程度上，极 adj.  远的，　远方的；　久远的', 2620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fat', 'adj. 肥胖的；多脂肪的 n.  脂肪； 肥肉', 2621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'catch', 'v.  [caught-caught] 抓住， 接住； 偶然撞见； 染上， 感染； 赶上， 追上；', 2622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fax', 'v.  传真 n. 传真；传真电文', 2623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plan', 'n.  计划， 打算， 规划； 平面图， 示意图； 设计图', 2624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'case', 'n.  事例， 实例； 情况， 事实； 病例； 案件； 箱， 盒； 手提箱', 2625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'give', 'v.  [gave-given] 给予， 赠送； 供给， 提供； 做出， 发出', 2626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'double', 'adj.  双的， 双重的； 两倍的， 加倍的； 供两人用的， 双人的； 两面派的， 虚伪的', 2627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eighteen', 'num.  十八', 2628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'phone', 'v.  打电话 n. 电话，电话机', 2629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'comfortable', 'adj.  舒适的， 舒服的； 宽裕的， 小康的', 2630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'slide', 'v. （使）滑行，（使）滑动 n. 滑梯', 2631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'style', 'n.  风格， 文体； 式样， 类型； 流行式样， 时尚', 2632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'jungle', 'n.  丛林， 密林', 2633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'suit', 'n.  一套衣服； 套', 2634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'card', 'n.  卡， 卡片； 请帖； 贺卡； 纸牌', 2635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Yin', 'n.  阴', 2636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chocolate', 'n.  巧克力； 巧克力色', 2637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'care', 'v. 关心，关怀；担心；介意 n.  照顾， 护理； 小心， 注意； 忧虑； 挂念', 2638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'study', 'v. 学习；研究，调查；细察，仔细端详 n.  学习； 研究， 调查， 研究成果； 书房', 2639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'boss', 'n.  老板， 上司， 头儿', 2640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'direct', 'adv. 直接地 adj. 直接的；率直的，坦率的；顺行的 v.  把…对准， 针对； 管理；', 2641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'exercise', 'n.  锻炼， 运动； 练习， 习题； 运用， 行使； 操练， 演习', 2642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fever', 'n.  发热， 发烧； 狂热', 2643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'supermarket', 'n.  超市', 2644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'madam', 'n.  女士， 夫人', 2645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kilo', 'n.  千克', 2646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seldom', 'adv.  很少， 不常', 2647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'physics', 'n.  物理， 物理学', 2648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'protect', 'v.  保护， 保卫', 2649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'stress', 'v.  强调， 着重； 重读 n. 压力，紧张；强调，重要性；重音', 2650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'display', 'n&v.  陈列， 展览； 显示， 表现', 2651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wet', 'adj. 湿的，潮的；多雨的，雨天的 v.  把…弄湿， 使潮湿', 2652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'born', 'adj.  出生的， 产生的； 天生的', 2653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kill', 'v.  杀死， 扼杀； 终止， 否决； 使疼痛， 使非常痛苦； 消磨， 打发', 2654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wrong', 'adj. 错误的，不正确的；不道德的，不正当的，不合法的 n.  错误； 坏事； 不公', 2655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'porridge', 'n.  粥， 麦片粥', 2656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shirt', 'n.  衬衫', 2657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'criticize', 'v.  批评； 评论； 非难', 2658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'certain', 'adj.  某一， 某种； 肯定的， 确信的； 确实的， 无疑的', 2659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'board', 'n.  板， 牌子； 木板， 纸板； 委员会， 董事会， 理事会； 伙食', 2660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shut', 'v.  [shut-shut, shutting]　关闭， 关上； 打烊', 2661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'luck', 'n.  运气； 好运， 幸运', 2662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'simple', 'adj.  简单的； 朴素的； 单纯的， 直率的； 迟钝的， 头脑简单的', 2663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'autograph', 'v.  签名 n. 亲笔签名', 2664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eleventh', 'num.  第十一', 2665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'influence', 'v.  影响， 感化 n. 影响，影响力；产生影响力的人；势力，权势', 2666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cloud', 'v.  使模糊， 使阴暗； 遮盖， 笼罩 n. 云；一群，一团；阴影；天空', 2667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'whale', 'n.  鲸', 2668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'talent', 'n.  天资， 才能； 人才', 2669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'few', 'pron.  很少人；　有些，　一些 adj. 很少，几乎没有', 2670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rain', 'v.  下雨 n. 雨；雨天；雨季', 2671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'violin', 'n.  小提琴', 2672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'king', 'n.  君主， 国王； 巨子， 大王', 2673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kind', 'adj.  亲切的， 和蔼的， 仁慈的 n. 种类', 2674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'both', 'pron.  两者， 双方 adj. 两个…', 2675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'market', 'v.  销售， 出售 n. 市场；股市', 2676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'important', 'adj.  重要的， 重大的； 有势力的， 有地位的', 2677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'keen', 'adj.  热心的； 激烈的； 敏锐的', 2678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nine', 'num.  九， 九个', 2679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'phrase', 'v.  用语言表达， 叙述 n. 短语，词组，用语', 2680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'outside', 'adv. 在外面，向外面 adj.  外面的， 外部 prep. 在…外面，向…外面；除…以外', 2681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'daily', 'adv. 每日，天天 adj. 每日的；日常的 n.  日报', 2682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'keep', 'v.  [kept-kept] 使保持， 使继续； 阻止， 防止； 履行， 遵守； 保存， 保', 2683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yoghurt', 'n.  酸奶， 酵母乳', 2684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'elementary', 'adj.  基本的， 基础的； 初级的， 小学的', 2685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'topic', 'n.  题目， 话题； 主题', 2686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'skate', 'v.  溜冰， 滑冰 n. 冰鞋', 2687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'job', 'n.  职业， 职位； 工作， 活儿； 职责， 责任', 2688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sugar', 'v.  在…中加糖 n. 糖', 2689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'daughter', 'n.  女儿', 2690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'who', 'pron.  谁， 什么人； …的人； 他， 她， 他们', 2691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'game', 'n.  游戏， 娱乐； 运动， 比赛', 2692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'why', 'adv. 为什么；…的理由 int.  咳， 哎呀', 2693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'forbid', 'v.  [forbade-forbidden] 不许， 禁止； 妨碍， 阻止', 2694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'captain', 'n.  船长， 机长； 上尉； 队长， 领队', 2695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bowl', 'n.  碗， 钵', 2696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'alone', 'adj.  单独的， 孤独的； 单单， 仅； 独一无二的， 唯一的', 2697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'along', 'adv. 向前地；一道，一起 prep.  沿着， 循着', 2698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'joy', 'n.  欢乐， 喜悦； 乐事， 乐趣', 2699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dialogue', 'n.  对话', 2700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'America', 'n.  美国； 美洲', 2701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sad', 'adj.  悲哀的， 伤心的； 十分糟糕的， 令人伤心的', 2702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'diet', 'v.  进特种饮食， 节食 n. 日常饮食；特种饮食，规定饮食', 2703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'win', 'v. 〔在竞赛、游戏、选举等中〕获胜，赢 n. 〔尤指在体育比赛中的〕胜利，赢', 2704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sheep', 'n. 羊，绵羊', 2705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rest', 'v.  休息， 睡眠； n. 剩余部分，其余的人；休息；停止，静止；撑架，支座', 2706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'soccer', 'n.  足球', 2707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'butter', 'n.  黄油', 2708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'amount', 'v.  合计 n. 总额', 2709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'original', 'adj. 最初的，原始的；新颖的，有创意的；原创性的 n.  原件', 2710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'album', 'n.  粘贴簿； 集邮簿； 相册； 音乐专辑', 2711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'electric', 'adj.  电动的， 电的', 2712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'also', 'adv.  而且， 也， 此外； 同样', 2713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'say', 'v. 说 n. 决定权；发言权 interjection. 哎，我说〔用于表示惊讶或引起别人注意〕', 2714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sandwich', 'v.  把…做成三明治； 夹入， 挤进 n. 三明治，夹肉面包', 2715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'enough', 'adv. 足够地，充分地；相当，达到一定的程度 adj.  足够的', 2716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'increase', 'n.  增加， 增强； 增加， 增强', 2717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shine', 'v. 照耀；发光，发亮；干得出色 n.  光泽， 光', 2718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'spread', 'v. 展开，伸开；散布，蔓延；涂，敷 n.  传播， 蔓延； 幅度， 范围； 涂抹在食物上', 2719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'afternoon', 'n.  下午， 午后', 2720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'attention', 'n.  注意力， 专心； 关注； 关心； 立正姿势', 2721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shiny', 'adj.  光亮的， 有光泽的； 反光的', 2722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'visit', 'n&v.  参观， 访问', 2723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'headache', 'n.  头痛； 令人头痛的人', 2724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'front', 'adj.  前面的， 在前面的 n. 前面，正面；前线，战线', 2725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'oneself', 'pron.  自己， 自身； 亲自， 本人', 2726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plane', 'n.  飞机； 平面， 水平面', 2727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'parent', 'n.  父亲， 家长', 2728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'stupid', 'adj.  愚蠢的， 迟钝的； 无聊的； 恼人的', 2729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bad', 'adj.  坏的； 不利的； 差的， 有缺陷的； 邪恶的， 道德败坏的； 严重的， 厉害的；', 2730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bring', 'v.  [brought-brought] 带来， 拿来； 把…引来； 促使， 使发生', 2731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bag', 'v.  把…装进袋子 n. 袋；手提包，旅行袋', 2732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sauce', 'n.  沙司； 调味汁， 酱汁； 佐料', 2733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'awake', 'adj. 醒着的 v.  [awoke-awaken] 醒， 唤醒； 意识到， 醒悟', 2734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kiss', 'n&v.  吻', 2735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hamburger', 'n.  汉堡包', 2736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'offer', 'v. 给予，提供；表示愿意；提出，提议 n.  提供， 提议； 报价， 开价', 2737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fit', 'v. 可容纳，装进 adj. 〔尤因经常锻炼而〕健壮的，健康的 n. 〔感情的〕冲动，一阵发作 v. 〔疾病〕发作，突发', 2738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'robot', 'n.  机器人； 自动机械', 2739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fix', 'v.  修理； 固定； 安装； 安排， 确定； 整理， 收拾； 供给或准备', 2740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'need', 'v. 需要；必须 n.  需要， 必要； 缺乏； 迫切要求', 2741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'honest', 'adj.  诚实的， 正直的； 坦诚的， 直率的', 2742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rank', 'v.  排列， 使排成行； 将…分等级； 属于某等级， 居某地位 n. 等级；军衔，职衔', 2743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cinema', 'n.  电影院； 电影， 电影艺术', 2744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rubbish', 'n.  垃圾， 废物； 荒谬的念头； 废话', 2745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'surf', 'v.  冲浪； 冲浪， 浏览 n. 拍岸浪花；拍岸涛声；拍岸碎浪', 2746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sure', 'adv.  确实； 当然 adj. 肯定的，有把握的；一定的，必然的；可靠的，稳妥的', 2747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'angry', 'adj.  生气的， 发怒的， 愤怒的', 2748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'am', 'v.  是', 2749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'an', 'indefinite article. 一（个）〔用于以元音开头的单词前〕', 2750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fold', 'v.  折叠， 合拢 n. 褶痕，褶缝', 2751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'as', 'adv. 同样，一样地 prep.  当做， 作为； 像， 如同', 2752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plastic', 'adj. 塑料的；可塑的', 2753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'mysterious', 'adj.  神秘的， 难以理解的', 2754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plant', 'n.  植物； 作物； 工厂', 2755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'peace', 'n.  和平， 和睦； 平静， 安宁， 安静', 2756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drive', 'v. 驱赶，驱使，迫使…去〔某处〕 n. 驱车出行', 2757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Atlantic', 'adj. 大西洋的 n.  大西洋', 2758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'brother', 'n.  兄弟； 教友， 会友', 2759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hurt', 'v. 弄伤 adj. 痛的；受伤的 n. 〔对感情造成的〕伤害，痛苦', 2760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'strong', 'adj.  强壮的， 强有力的， 强大的； 牢固的； 坚强的， 坚定的； 强烈的， 浓的； 精', 2761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deal', 'v. 发放；给予；处理，对付 n.  交易； 协议； 大量， 很多', 2762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'prove', 'v.  证明， 证实； 结果是， 原来是', 2763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'be', 'v.  是， 就是； 在， 存在', 2764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'homeland', 'n.  祖国， 家乡', 2765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'maths', 'n.  数学', 2766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deaf', 'adj.  聋的； 不愿听的， 装聋的', 2767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dead', 'adv.  完全地； 绝对地 adj. 死的；无感觉的；呆板的 n. 死者', 2768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'mouth', 'n.  嘴， 口', 2769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'adj.', 'abbr. 调整（adjacent）', 2770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tomato', 'n. 番茄，西红柿', 2771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sea', 'n.  海， 海洋', 2772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sixth', 'num. 第六 n.  六分之一', 2773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'search', 'n&v.  搜索， 寻找； 搜查', 2774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'see', 'v.  [saw-seen] 看， 观看； 参见， 会晤； 领会， 理解； 想象； 把…看作； 发现； 体', 2775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'servant', 'n.  仆人；　公务员', 2776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fool', 'v. 欺骗，愚弄；干蠢事 adj.  愚蠢的 n. 蠢人，笨蛋', 2777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sudden', 'adj. 突然的，意外的 n.  突然发生的事', 2778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'popularity', 'n.  普及； 流行', 2779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'mountain', 'n. 山；', 2780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'by', 'prep.  被， 由； 凭借， 通过； 从…旁过去， 经由； 在…旁边， 靠近； 在…之前，', 2781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'whom', 'pron.  谁', 2782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wheat', 'n.  小麦； 淡黄色； 朴实的人', 2783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dear', 'adj. 亲爱的；昂贵的 int. 啊，哎呀 n.  亲爱的人', 2784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tooth', 'n. 牙，牙齿', 2785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'foot', 'n. 脚，足', 2786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sixty', 'num.  六十， 六十个', 2787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'set', 'v. 〔小心地〕放置，放下 n. 〔物品的〕一套，一副，一组 adj. 在…位置的，位于…的', 2788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'outstanding', 'adj.  杰出的； 明显的； 未解决的； 未偿付的', 2789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'escalator', 'n.  〈美〉自动扶梯', 2790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'medicine', 'n.  内服药； 医学； 内科学', 2791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flu', 'n.  流行性感冒', 2792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'food', 'n.  食物， 食品', 2793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fly', 'v. 乘飞机 v. 〔棒球中〕击腾空球，击高飞球 n. 蝇，苍蝇 adj. 时髦漂亮的', 2794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'partner', 'v.  做…的搭档 n. 配偶，搭档；伙伴，合伙人', 2795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Thursday', 'n.  星期四', 2796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kilometer', 'n.  千米', 2797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'river', 'n.  河流， 江， 川', 2798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'spider', 'n.  蜘蛛', 2799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kite', 'n.  风筝； 纸鸢', 2800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'interview', 'v.  面试； 会见， 采访 n. 接见，会见；面谈，面试', 2801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bed', 'n.  床； 床位； 床； 河床； 底', 2802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bee', 'n.  蜜蜂', 2803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beauty', 'n.  美， 美丽； 美人； 美的东西', 2804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'scarf', 'n.  围巾； 披巾； 薄头巾', 2805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'language', 'n.  语言； 措辞； 说法', 2806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'do', 'v.  [did-done] 做， 从事； 实行， 进行； 尽力； 可用； 制作； 算出， 解答', 2807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'humorous', 'adj.  幽默的， 诙谐的', 2808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Friday', 'n.  星期五', 2809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'scary', 'adj.  恐怖的， 吓人的', 2810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'which', 'pron.  哪一个， 哪一些； …的那个， …的那些； 那个， 那些', 2811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'disadvantage', 'n.  缺点， 不利条件', 2812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'complain', 'v.  抱怨， 诉苦； 投诉， 控告', 2813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fourteen', 'num.  十四', 2814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'she', 'pron.  她', 2815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'knife', 'n.  刀， 餐刀', 2816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'piece', 'n.  片， 块， 段； 断片， 碎块', 2817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'western', 'adj.  西方的， 西部的', 2818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'carry', 'v.  提， 挑， 背； 运送， 运载； 输送， 传送， 传播； 携带， 怀着； 支撑', 2819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'refrigerator', 'n.  电冰箱', 2820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'elephant', 'n.  象', 2821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'party', 'n.  社交聚会； 党， 政党； 一方， 当事人', 2822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'little', 'adj.  小的， 矮小的； 短的； 琐碎的， 微不足道的； 不多的， 少到', 2823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'however', 'adv. 然而，仍然；无论如何 conj.  不管怎样， 然而', 2824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deep', 'adj.  深的， 厚的； 深切的， 强烈的； 深沉的； 浓的； 深刻的， 深', 2825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shy', 'adj.  腼腆的， 害羞的； 胆怯的； 有戒心的， 畏缩的', 2826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'for', 'prep.  为， 为了； 给， 供； 代替， 代表； 因为， 由于； 就…而言； 往， 向', 2827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fox', 'n.  狐狸； 狡猾的人', 2828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'perhaps', 'adv.  或许， 大概， 可能', 2829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'aunt', 'n.  姑姑， 姨妈， 伯母， 婶婶， 舅妈', 2830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'skill', 'n.  技能， 技巧， 手艺； 熟练', 2831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'oak', 'n.  橡树； 橡木', 2832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'trouble', 'n.  麻烦， 苦恼， 困难； 疾病； 故障； 纠纷， 动乱', 2833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'divide', 'v. 分，分隔；分配，分享；除；使产生分歧 n.  分歧； 分开； 分界线， 分水岭', 2834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sir', 'n.  先生； [S-] 爵士', 2835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'class', 'n.  阶级， 社会等级； 班， 班级； 课； 种类， 门类； 等级， 级别', 2836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sit', 'v.  [sat-sat, sitting] 坐， 就座； 坐落， 被安放； 使坐， 使就座', 2837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'over', 'prep.  在…上方， 在…上面； 越过， 从一侧到另一侧； 高于， 超过； 在…期间；', 2838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'six', 'num.  六， 六个', 2839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'football', 'n.  足球； 橄榄球', 2840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dinner', 'n.  正餐， 主餐； 宴会', 2841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fork', 'n.  叉， 餐叉； 耙； 分叉， 岔口', 2842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'form', 'v.  形成， 构成 n. 形式，种类；外形，外貌；表格', 2843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'farmer', 'n.  农场主； 农民', 2844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'neither', 'adv.  也不 pron. 两者都不', 2845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'avoid', 'v.  避免； 避开， 躲开； 预防', 2846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'gate', 'n.  大门； 有大门的出入口； 观众人数， 门票收入', 2847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fresh', 'adj.  新的， 新到的； 新鲜的， 未经腌熏的', 2848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'he', 'pron.  他； 一个人', 2849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'very', 'adv. 很，非常；极其，完全地；正是 adj.  正是的， 恰好的； 完全的， 十足的', 2850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'big', 'adj.  大的， 巨大的； 重大的， 主要的； 年龄较大的， 长大了的', 2851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'practice', 'n.  实践； 实践行动； 练习； 惯例， 习俗', 2852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'crowd', 'v.  聚集， 群集； 挤， 推 n. 人群，群众；一群，一批', 2853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sick', 'adj.  有病的， 患病的； 恶心的， 想吐的； 厌恶的； 心烦意乱的， 恼火的', 2854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bit', 'n.  一点儿， 少许； 小片， 小块', 2855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'corner', 'n.  角， 角落； 街角； 遥远的地区， 偏僻处； 困境，', 2856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'else', 'adv.  其他， 另外', 2857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'four', 'num.  四', 2858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'easily', 'adv.  容易地， 不费力地', 2859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beside', 'prep.  在…旁边； 在…附近； 和…相比', 2860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'join', 'v.  参加， 加入； 连接， 接合', 2861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'if', 'conj.  如果， 假如； 是否； 即使， 虽然', 2862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'costume', 'n.  戏装； 成套服装', 2863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bathroom', 'n.  浴室； 盥洗室', 2864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sky', 'n.  天', 2865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sentence', 'v.  宣判， 判决 n. 句子；判决，宣判', 2866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hallway', 'n.  走廊， 回廊； 门厅， 过道', 2867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'large', 'adj.  大的； 多的， 众多的', 2868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'surface', 'v.  浮出水面； 浮现， 显露 n. 表面，面；外表，外观', 2869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'in', 'prep.  在…里， 在…内； 在…期间， 在…之内；', 2870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tomorrow', 'adv. 明天 n.  明天； 来日， 未来', 2871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'verb', 'n.  动词', 2872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'metal', 'n.  金属', 2873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'is', 'v.  存在， 是', 2874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'it', 'pron.  它； 他； ；', 2875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fry', 'v.  油煎， 油炸', 2876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drink', 'v. 喝，饮 n. 一杯[份]饮料；饮，喝', 2877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'announce', 'v.  宣布， 声称； 预告', 2878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'somebody', 'pron. 某人，有人 n.  重要人物', 2879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'India', 'n.  印度', 2880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'traditional', 'adj.  传统的， 惯例的； 口传的， 传说的', 2881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'operate', 'v.  动手术； 起作用； 经营， 管理', 2882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hello', 'int.  喂， 你好', 2883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'begin', 'v.  [began-begun, beginning] 开始', 2884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'parrot', 'n.  鹦鹉', 2885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'become', 'v.  [became-become] 变成， 成为； 开始变得', 2886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'alive', 'adj.  活着的， 在世的； 存在的， 在起作用的； 有活力的， 活跃的， 有生', 2887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weekend', 'adj.  周末的 n. 周末', 2888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'noodle', 'n.  面条', 2889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plate', 'n.  盘子； 金属牌； 感光底片', 2890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'world', 'adj.  世界的， 世界范围的 n. 世界，地球，天下；领域', 2891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'library', 'n.  图书馆， 藏书室； 藏书', 2892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ability', 'n.  能力， 本领； 才能， 才智', 2893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'everything', 'pron.  每件事， 一切； 最重要的东西', 2894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'camera', 'n.  照相机； 摄影机， 摄像机', 2895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'table', 'n.  桌子， 台子； 表格', 2896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bread', 'n.  面包； 生计， 谋生之道', 2897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'side', 'n.  面， 侧面， 旁边； 方面； 一方， 一边； 山坡， 坡， 岸', 2898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'break', 'v.  [broke-broken] 打破； 损坏， 弄坏； 破坏， 违反； 中止， 中断； 打破；', 2899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'restaurant', 'n.  餐馆， 饭店', 2900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'change', 'v. 改变；交换，互换；兑换；换衣，换车 n.  改变， 变化； 更改， 更换；', 2901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'draw', 'v.  [drew-drawn] 画， 描绘； 拖， 拉； 拔出， 抽出； 提取， 汲取； 引起； 吸引； 推', 2902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cupboard', 'n.  柜橱', 2903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'off', 'adv.  距， 离， 到； 离开； 出发， 起跑； 不发生， 取消； 断开， 不供', 2904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'joke', 'n.  笑话， 玩笑', 2905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'knee', 'n.  膝， 膝盖', 2906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hide', 'v. 把…藏起来，隐藏 n. 〔可观察鸟兽行动的〕隐匿处，埋伏处', 2907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'century', 'n.  世纪， 百年', 2908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'instruction', 'n.  命令， 指示； 教学， 教导', 2909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'discovery', 'n.  发现， 发觉； 被发现的事物', 2910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'candle', 'n.  蜡烛', 2911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'report', 'v.  报告， 汇报； 报道； 告发； 报到； 隶属， 对负责', 2912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'complete', 'adj. 十足的，彻底的；完成的 v.  完成， 结束', 2913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fun', 'adj. 有趣的，令人愉快的 n.  有趣的事； 乐趣， 娱乐', 2914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'theirs', 'pron.  他们的', 2915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sign', 'v.  签； 签署 n. 标志，符号；招牌；征兆，迹象', 2916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'several', 'adj.  几个， 若干', 2917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cotton', 'n.  棉， 棉花； 棉线， 棉纱', 2918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'office', 'n.  办公室， 办事处， 营业所； 处， 所， 局； 公职， 官职， 职责； 帮忙， 服务', 2919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'while', 'conj. 当…的时候，和…同时；而，然而；虽然，尽管 n.  一会儿， 时间', 2920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'northern', 'adj.  北方的， 北部的', 2921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'second', 'adj. 次等的，二等的 num. 第二 n.  秒， 瞬间', 2922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'that', 'determiner. 那，那个〔指已经提到或已经知道的人、事物、想法等〕 conjunction. 〔用于动词、名词或形容词后引导一个从句，表示某人所说或所想，或陈述一个事实或理由〕 adv. 那么〔大、多等〕〔尤指通过手势比画来表示大小、数量等〕', 2923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'high', 'adj.  高的， 高度的； 高级的， 重要的； 高兴的， 愉快的； 正盛', 2924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'edge', 'n.  边， 边缘； 刀口， 刃； 优势， 优越地位', 2925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'son', 'n.  儿子； 孩子', 2926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'skirt', 'n.  裙子； 边缘， 外围', 2927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'than', 'conj. 比 prep.  与…比较', 2928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'me', 'pron.  我', 2929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'level', 'adj.  平的， 水平的； 同高度的， 同程度 n. 水平面，水平线；高度；水平，等级', 2930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'author', 'n.  作家， 作者； 创始人， 发起者', 2931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Europe', 'n.  欧洲', 2932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'meter', 'n.  米， 公尺', 2933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'infinitive', 'n.  原形； 不定式', 2934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'establish', 'v.  建立， 设立； 确定， 证实', 2935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coat', 'v.  涂 n. 上衣，外套；表皮，皮毛；覆盖物，层', 2936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'license', 'n. 许可，执照 vt.  准许', 2937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dish', 'n.  碟， 盘； 菜肴， 一盘菜', 2938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dream', 'n. 梦 v. 梦想，希望', 2939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Wednesday', 'n.  星期三', 2940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'essay', 'n.  短文， 文章； 随笔， 散文', 2941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'prediction', 'n.  预言； 预料； 预报', 2942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coal', 'n.  煤， 煤块', 2943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'survey', 'v.  调查， 检视； 测量， 勘测； 全面审视， 概括论述； 俯瞰， 眺望； 调查， 检视； 测量， 勘测； 全面审视， 概括论述； 俯瞰， 眺望', 2944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tense', 'adj. 紧张的；拉紧的，绷紧的 v. 拉紧，绷紧 n.  时态', 2945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'birthday', 'n.  生日', 2946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'heat', 'v.  加热， 变热 n. 热，炎热；体温，热度；激动；激烈', 2947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'behind', 'prep.  在…的背后， 在…的后面； 落后于； 支持， 赞', 2948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tenth', 'num. 第十 n.  十分之一', 2949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'candy', 'n.  糖果', 2950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'student', 'n.  学生， 学者， 大学生； 研究生', 2951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'careful', 'adj.  小心的， 仔细的', 2952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'recipe', 'n.  烹饪法， 食谱； 方法； 秘诀， 诀窍', 2953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seal', 'v.  封， 密封 n. 封铅，封条；印，图章；海豹', 2954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'box', 'v.  把…装箱； (用拳或手 n. 箱，盒；包厢', 2955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bow', 'n&v.  鞠躬， 低头； 鞠躬， 低头', 2956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'boy', 'n.  男孩', 2957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'head', 'n.  头， 头部； 顶部， 前端； 领导， 首脑； 头数； 头脑， 智力', 2958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'month', 'n.  月， 一个月的时间', 2959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'total', 'adj. 总的，全部的；完全的，彻底的 v.  合计， 总计 n. 总数，总计', 2960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'oil', 'v.  给…加润滑油； 使涂满油 n. 油；润滑油；石油，燃料油；油画；油画颜料', 2961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'upstairs', 'adv. 在楼上，往楼上 adj. 楼上的 n.  楼上', 2962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'of', 'prep.  …的； 由…制成的； 含有…的， 装有…的', 2963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fight', 'v. 打（仗），与（…）作战，战斗 n. 打斗，打架', 2964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hear', 'v.  [heard-heard] 听见； 听到， 得知； 审讯， 听证； 收到…的信', 2965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'on', 'prep.  在…上； 向， 朝， 针对； 靠近…， 在…旁； 关于， 论及； 凭， 靠， 根据； 处', 2966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'zebra', 'n.  斑马', 2967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pretty', 'adv. 相当，很，颇 adj.  漂亮的， 俊俏的', 2968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'or', 'conj.  或， 或者， 还是； 即， 或者说； 否则， 要不然', 2969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chance', 'v.  碰巧， 偶然发生； 偶然看见 n. 可能性；机会，机遇；偶然的事', 2970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'social', 'adj.  社会的； 交际的， 社交的', 2971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wheel', 'v.  转动， 旋转 n. 轮，车轮', 2972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'homeless', 'adj.  无家的， 无家可归的', 2973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cross', 'v. 穿过，越过；交叉，相交；杂交 n.  十字架； 十字形记号', 2974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'control', 'v.  控制， 支配； n. 控制，支配；管理；调节；抑制，自制；控制器，调节器', 2975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cousin', 'n.  堂兄弟， 堂姐妹', 2976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'clerk', 'n.  〈美〉店员； 办事员， 职员', 2977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'earth', 'n.  地球； 陆地， 地面； 土， 泥', 2978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Paris', 'n.  巴黎', 2979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'elbow', 'v.  用肘推， 用肘挤 n. 肘部', 2980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'salad', 'n.  沙拉， 凉拌菜', 2981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rocket', 'v.  迅速上升； 猛涨 n. 火箭', 2982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'somewhere', 'adv.  在某处， 到某处； 大约， 大概', 2983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'scene', 'n.  一场， 一个镜头， 一节； (戏剧、 事件', 2984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'injure', 'v.  伤害， 损害， 损伤', 2985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Saturday', 'n.  星期六', 2986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'freeze', 'v. （使）结冰，（使）冻结 n. 〔价格、工资等的〕冻结', 2987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'province', 'n.  省； 领域； 范围', 2988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'clever', 'adj.  聪明的， 机灵的； 灵巧的， 精巧的', 2989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'friend', 'n.  朋友， 友人', 2990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bookcase', 'n.  书柜， 书架', 2991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'January', 'n.  一月', 2992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'recent', 'adj.  新近的， 近来的', 2993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'they', 'pron.  他们', 2994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'noise', 'n.  声音， 响声； 噪音', 2995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pleasure', 'n.  高兴， 愉快； 满足； 乐事， 快事', 2996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'old', 'adj.  老的， 年老的； 古老的， 陈旧的， 过时的； …岁的， …久的； 以前的， 过去', 2997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'them', 'pron.  他们', 2998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'then', 'adv.  当时， 在那时； 那么， 因而； 然后， 于是', 2999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ancient', 'adj.  古代的， 古老的； 年老的， 看上去很老的', 3000);
