INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'toss', 'v. 摇摆， 颠簸；向上扔；辗转反侧', 7001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mystery', 'n. 神秘； 神秘的事物 A；神秘小说， 侦探小说', 7002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deposit', 'vt. 沉淀； 付；存放； 储蓄 n. 存款； 保证金；沉积物', 7003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dissipate', 'v. 驱散；浪费； 挥霍 A', 7004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotten', 'adj. 腐烂的， 腐朽的', 7005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flash', 'vi. 闪光， 闪亮 n. 闪光， 闪现 A vt. 闪现', 7006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skillful', 'adj. 灵巧的， 娴熟的', 7007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disturbance', 'n. 动乱， 骚乱； 干扰 A <', 7008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simultaneous', 'adj. 同时的， 同时存在的 A', 7009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'guarantee', 'n. 保证； 保证书 A vt. 保证， 担保', 7010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recommend', 'vt. 推荐， 介绍；劝告， 建议', 7011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'default', 'vi. 不履行义务；拖欠 n. 违约， 拖欠；弃权', 7012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'helicopter', 'n. 直升机', 7013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tropic', 'n. 回归线', 7014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'waterfall', 'n. 瀑布', 7015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beverage', 'n. 饮料', 7016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attribute', 'n. 属性， 品质， 特征 vt. 把…归于； 认为…是…所为 A', 7017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mechanism', 'n. 机械装置； 机构 A；物理过程； 机理， 机制；机能', 7018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cemetery', 'n. 坟墓， 公墓', 7019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genetic', 'adj. 基因的， 遗传的', 7020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'triumph', 'vi. 得胜， 战胜 n. 胜利， 成功', 7021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horror', 'n. 恐怖； 战栗', 7022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poison', 'n. 毒物， 毒药 vt. 放毒； 〈喻〉毒害', 7023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gram', 'n. 克', 7024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arouse', 'vt. 唤醒， 唤起；激起， 引起', 7025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'riot', 'vi. 聚众闹事 n. 暴乱， 骚乱；极度丰富', 7026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'optimum', 'adj. 最好的；最有利的', 7027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nest', 'vi. 筑巢 n. 窝， 巢', 7028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consensus', 'n. 一致， 一致同意', 7029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'classic', 'adj. 第一流的， 不朽的；典型的 n. 杰作， 名著', 7030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metric', 'adj. 米制的， 公制的', 7031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absolute', 'adj. 绝对的， 完全的', 7032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gossip', 'vi. 传播流言蜚语； 说长道短 n. 流言蜚语；说长道短的人', 7033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'describe', 'v. 描述， 形容 A', 7034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grab', 'v. 抓； 夺  < n. 抓； 夺', 7035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suck', 'vt. 吸， 吮', 7036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slum', 'n. 贫民窟， 贫民区； 陋巷', 7037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wealthy', 'adj. 富裕的， 丰富的', 7038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'presently', 'adv. 一会儿， 不久；现在， 目前', 7039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foam', 'vi. 起泡沫 n. 泡沫', 7040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jazz', 'n. 爵士乐', 7041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'administration', 'n. 管理， 经营；行政； 政府', 7042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dwell', 'vi. 住， 居留', 7043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incorporate', 'adj. 合并的 vt. 合并， 纳入； 结合', 7044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'boast', 'v. 自夸， 夸耀 n. 自夸； 大话 A', 7045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'operator', 'n. 操作人员；接线员', 7046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'landlady', 'n. 女房东； 女地主', 7047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sophomore', 'n. 二年级学生', 7048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'counterpart', 'n. 对应的人', 7049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'segment', 'n. 段； 片； 节；部分', 7050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stripe', 'n. 条纹', 7051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pendulum', 'n. 【物】摆； 钟摆', 7052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sovereign', 'adj. 拥有最高统治权的， 至高无上的；独立自主的， 具有独立主权的  < n. 君主， 元首；统治', 7053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clothe', 'vt. 穿衣， 供给…衣服', 7054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imagine', 'vt. 想象； 设想， 料想', 7055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cater', 'vi. 迎合；提供饮食及服务', 7056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attractive', 'adj. 有吸引力的； 引起兴趣的； 动人的', 7057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superb', 'adj. 极好的， 高质量的', 7058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'duplicate', 'adj. 复制的； 二重的； 二倍的 n. 复制品， 副本 vt. 复写； 复制； 使加倍 <', 7059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'engineering', 'n. 工程； 工程学', 7060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decrease', 'v. 减少， 减小 n. 减少， 减小', 7061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ignorance', 'n. 无知， 愚昧； 不知道', 7062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trumpet', 'n. 喇叭， 小号', 7063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'installment', 'n. 分期付款， 分期交付；一集； 一期', 7064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trifle', 'n. 少量， 少许；小事， 琐事； 微不足道的东西 vt. 嬉耍  <', 7065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'migrate', 'vi. 迁移， 移居', 7066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Easter', 'n. 复活节', 7067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'submit', 'vi. 服从， 屈服 A vt. 呈送， 提交 A', 7068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'import', 'vt. 进口， 输入 n. 进口， 输入；进口商品， 进口物资；要旨， 含义；重要性', 7069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'string', 'n. 弦， 线， 细绳 A；一串， 一行 vt. 缚， 捆； 悬挂 <', 7070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occupy', 'vt. 占， 占用；占据， 占领；使忙碌， 使从事', 7071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affluent', 'adj. 丰富的； 富裕的', 7072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intrude', 'v. 侵入， 闯入， 打扰；把强加于', 7073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simplicity', 'n. 简单， 简易； 朴素；直率， 单纯 A', 7074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snatch', 'v. 攫取， 抢夺 n. 攫取， 抢夺', 7075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summit', 'n. 最高点， 峰顶， 极点；峰会', 7076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perfume', 'n. 香味， 芳香；香水； 香料 vt. 使散发香气； 洒香水于', 7077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnify', 'vt. 放大， 扩大 A', 7078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'redundant', 'adj. 累赘的， 冗长的；过剩的， 多余的', 7079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conclusion', 'n. 结束， 终结；结论， 推论', 7080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'typist', 'n. 打字员', 7081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'durable', 'adj. 持久的， 耐久的 n. 耐用物品', 7082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impose', 'vt. 征；处以；把…强加给', 7083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mammal', 'n. 哺乳动物', 7084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statement', 'n. 声明； 陈述', 7085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trademark', 'n. 商标', 7086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memorial', 'adj. 记忆的； 纪念的； 追悼的 n. 纪念物； 纪念碑； 纪念馆', 7087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'factor', 'n. 因素， 要素', 7088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delivery', 'n. 传递， 传送； 交付； 分娩', 7089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pinch', 'n. 撮， 微量；捏， 掐；紧缺， 短缺 vt. 捏， 掐， 拧， 挟', 7090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rack', 'n. 挂物架， 搁物架 vt. 使痛苦， 折磨', 7091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aural', 'adj. 听觉的 <', 7092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conquer', 'vt. 征服， 战胜； 占领；克服， 破除', 7093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sculpture', 'n. 雕刻， 雕塑 <；雕刻作品， 雕塑品', 7094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wax', 'n. 蜡， 蜂蜡 vt. 打蜡', 7095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sensation', 'n. 感觉， 知觉；激动； 轰动； 轰动一时的事情', 7096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'urban', 'adj. 城市的 <', 7097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furthermore', 'adv. 而且， 此外', 7098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'timely', 'adj. 及时的， 适时的', 7099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'risk', 'vt. 冒…的危险 n. 冒险；风险', 7100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flame', 'vi. 发火焰， 燃烧 A n. 火焰， 火苗；热情；光辉', 7101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discard', 'vt. 丢弃， 抛弃', 7102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subsidy', 'n. 津贴， 补助金', 7103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gage', 'n. 标准尺寸， 规格； 量规， 量表', 7104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'modest', 'adj. 谦虚的， 谦让的； 适度的', 7105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crush', 'n. 压碎， 压坏 vt. 压碎； 压坏；压服， 压垮', 7106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hatred', 'n. 憎恨， 憎恶， 怨恨', 7107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'electron', 'n. 电子', 7108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embed', 'vt. 把…嵌入', 7109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'promising', 'adj. 有希望的， 有前途的', 7110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'treason', 'n. 谋反， 通敌， 叛国', 7111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'counsel', 'vt. 劝告， 忠告 n. 劝告， 忠告；法律顾问； 辩护人', 7112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liver', 'n. 肝， 肝脏', 7113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'probability', 'n. 可能性， 概率', 7114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suicide', 'n. 自杀； 自取灭亡', 7115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'physiology', 'n. 生理学', 7116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lofty', 'adj. 高耸的；崇高的 A；高傲的', 7117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'explicit', 'adj. 详述的， 明确的；坦率的', 7118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'utilize', 'vt. 利用', 7119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prevail', 'vi. 取胜， 占优势；流行， 盛行', 7120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'browse', 'vi. 吃嫩叶或草 A；浏览 n. 嫩叶， 嫩芽；吃草， 放牧；浏览 A', 7121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'denial', 'n. 否认；拒绝； 拒绝给予', 7122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'implicit', 'adj. 不言明的， 含蓄的；固有的；无疑问的； 无保留的', 7123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portion', 'n. 一部分， 一份', 7124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'futile', 'adj. 无效的， 无用的， 无意义的；没出息的；琐碎的', 7125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'connexion', 'n. 联系， 连接', 7126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supermarket', 'n. 超级市场', 7127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hardship', 'n. 艰难， 困苦', 7128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confuse', 'vt. 使混乱， 混淆；使迷惑， 使糊涂', 7129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tragic', 'adj. 悲剧的， 悲惨的', 7130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'physician', 'n. 内科医生', 7131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dial', 'v. 拨号， 打电话 n. 钟面， 刻度盘， 拨号盘', 7132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grin', 'n. 露齿而笑， 咧嘴笑', 7133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grip', 'v. 紧握， 抓紧 n. 握， 抓紧', 7134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'explore', 'v. 勘探， 探究， 探索 A', 7135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strawberry', 'n. 草莓', 7136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'climate', 'n. 气候；风气， 社会思潮', 7137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tentative', 'adj. 尝试的， 试验的', 7138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crust', 'n. 外皮， 壳；地壳', 7139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criticize', 'v. 批评， 评论', 7140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'organization', 'n. 组织， 机构； 体制， 结构', 7141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'width', 'n. 宽度；宽阔， 广阔', 7142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rage', 'n. 愤怒； 精神错乱', 7143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preside', 'vi. 主持', 7144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'economic', 'adj. 经济的， 经济学的 <', 7145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statistics', 'n. 统计数据； 统计学', 7146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grim', 'adj. 讨厌的， 糟糕的；严厉的， 冷酷的', 7147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stuff', 'n. 原料， 材料； 东西 vt. 填满， 塞满', 7148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offspring', 'n. 子孙， 后代；结果， 产物', 7149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distinction', 'n. 差别， 区分', 7150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arrest', 'n. /', 7151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'widow', 'n. 寡妇', 7152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fee', 'n. 费；酬金', 7153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'section', 'n. 章节；部分；地区；部门， 科 A', 7154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'malignant', 'adj. 恶毒的； 恶性的；致命的 A', 7155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whip', 'n. 鞭子 A vt. 抽打， 鞭打；搅打， 打成泡沫', 7156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rumor', 'n. 传闻， 谣言', 7157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overflow', 'v. 外溢， 溢出 A', 7158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whale', 'n. 鲸', 7159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'provoke', 'vt. 挑衅， 激怒， 招惹', 7160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'threaten', 'vi. 有…危险， 预示凶兆 A vt. 恐吓， 威胁', 7161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enrich', 'vt. 使富足； 使肥沃 <；使充实、 丰富； 使更有意义 A', 7162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strain', 'vi. 尽力；用力推， 用力拉 n. 过度的疲劳， 紧张；张力， 拉力 vt. 扭伤， 拉伤；拉紧， 扯紧 <', 7163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'licence', 'n. 许可证， 执照 vt. 准许， 认可', 7164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hunt', 'v. 打猎； 猎取；搜索； 寻找 n. 打猎， 猎取；搜索； 寻找', 7165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cellar', 'n. 地窖， 地下室', 7166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'visible', 'adj. 看得见的， 可见的', 7167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intrigue', 'vi. 密谋， 施诡计 vt. 引起极大兴趣， 激起…的好奇心 ， 迷住 n. 阴谋， 诡计， 密谋', 7168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tangle', 'v. 缠结， 乱作一团 n. 乱糟糟的一堆；复杂的问题；困惑， 混乱', 7169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orient', 'vt. 定…的方位', 7170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handicap', 'vt. 妨碍， 使不利 n. 缺陷， 残疾 A；障碍， 不利条件', 7171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'survival', 'n. 幸存， 生存；幸存者； 残存物', 7172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rail', 'n. 栏杆， 围栏', 7173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plea', 'n. 恳求， 请求；抗辩， 答辩， 辩护；借口， 托辞', 7174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inner', 'adj. 内部的， 里面的；内心的', 7175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'keen', 'adj. 热心的， 渴望的；敏锐的； 头脑敏捷的；锋利的', 7176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nutrition', 'n. 营养', 7177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cereal', 'n. 谷物； 谷类食品', 7178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indifferent', 'adj. 冷漠的， 不关心的； 不积极的', 7179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overhaul', 'n. 彻底检修；改革A vt. 彻底检修；赶上， 超过', 7180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cruise', 'vi. 航游， 巡航；缓慢巡行 n. 航游； 游弋', 7181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eagle', 'n. 鹰', 7182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elementary', 'adj. 初等的；基本的', 7183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'topic', 'n. 话题， 主题， 题目', 7184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solemn', 'adj. 庄严的， 隆重的；严肃的', 7185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inhale', 'v. 吸入， 吸， 吸气', 7186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perceive', 'vt. 察觉， 感知；理解， 领悟', 7187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embarrass', 'vt. 使窘迫， 使为难', 7188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'option', 'n. 选择， 选择权；选择的事物；选课', 7189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'raid', 'n. 袭击； 侵袭', 7190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'politics', 'n. 政治， 政治学；政纲； 政见', 7191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acute', 'adj. 敏锐的， 尖锐的；急性的', 7192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kindergarten', 'n. 幼儿园 <', 7193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handbook', 'n. 手册， 指南', 7194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unexpected', 'adj. 想不到的， 意外的', 7195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crucial', 'adj. 至关重要的， 决定性的', 7196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contribute', 'v. 贡献； 捐助， 捐献；投稿；有助于', 7197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generator', 'n. 发电机， 发生器', 7198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remark', 'vi. 评论； 谈论 n. 评语， 议论， 意见 vt. 注意到， 察觉', 7199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'endurance', 'n. 忍耐； 持久， 耐久', 7200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'microscope', 'n. 显微镜', 7201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'candidate', 'n. 候选人， 申请人；报考者', 7202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strive', 'vi. 奋斗， 努力 <', 7203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intelligible', 'adj. 可理解的， 易领悟的；清楚的', 7204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parallel', 'adj. 平行的， 并联的 <；相同的， 类似的 n. 平行线； 平行面 A；类似， 对比； 相似物；纬线', 7205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cashier', 'n. 收银员， 出纳员 A <', 7206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hospitality', 'n. 好客， 殷勤； 款待', 7207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peanut', 'n. 花生', 7208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diet', 'n. 饮食， 食物', 7209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blunder', 'vi. 踉踉跄跄地走； 乱闯 <；犯错 n. 大错', 7210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breach', 'n. 裂缝， 缺口 A vt. 打破， 裂开；违背', 7211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wit', 'n. 智力， 才智', 7212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handful', 'n. 一把， 一小撮；少数', 7213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bewilder', 'vt. 使迷惑， 难住', 7214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terminal', 'n. 终点站；终端， 接线端； 计算机终端', 7215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'a.', 'n. 天主教徒', 7216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diminish', 'v. 缩小， 减少， 递减', 7217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surpass', 'vt. 超过， 胜过 <', 7218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reduction', 'n. 减少， 缩减', 7219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rake', 'n. 耙子， 耙机 vt. 耙；搜索； 探索', 7220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unfold', 'v. 展开， 打开；显露， 展现', 7221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extent', 'n. 广度， 宽度， 长度；程度， 限度', 7222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gaol', 'n. 监狱， 拘留所 vt. 监禁某人', 7223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversely', 'adv. 相反', 7224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sauce', 'n. 酱汁， 调味汁', 7225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hamburger', 'n. 汉堡包， 牛肉饼', 7226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'colonial', 'adj. 殖民的', 7227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'warfare', 'n. 战争； 斗争； 冲突', 7228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pension', 'n. 养老金， 年金', 7229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assumption', 'n. 假定， 设想；采取， 承担； 僭取', 7230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'giant', 'adj. 巨大的 n. 巨人； 巨物', 7231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rank', 'n. 军衔； 社会阶层；排， 横列 vt. 分等级， 把…分类； 排列 A', 7232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outlet', 'n. 出路； 出口； 渠道；发泄方法， 排遣', 7233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'waggon', 'n. 运货马车； 运货车；敞篷车厢', 7234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neglect', 'vt. 忽视； 疏忽， 忽略；漏做 n. 忽视； 疏忽， 漏做', 7235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'addition', 'n. 加； 加法；附加', 7236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cosmic', 'adj. 宇宙的', 7237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gang', 'n. 一帮， 一群， 一伙 A', 7238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carve', 'v. 刻', 7239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vein', 'n. 静脉， 血管；叶脉；纹理， 纹路；方式， 风格', 7240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shrink', 'v. 起皱； 收缩；退缩， 畏缩', 7241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'veil', 'v. 用面纱掩盖；掩饰 n. 面纱， 遮蔽物', 7242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hierarchy', 'n. 等级制度；统治集团； 领导者', 7243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ancestor', 'n. 祖宗， 祖先', 7244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'textile', 'adj. 纺织的 n. 纺织品', 7245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locality', 'n. 位置， 地点', 7246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peach', 'n. 桃； 桃树', 7247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proceeding', 'n. 行动； 进行；会议记录； 学报', 7248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'former', 'pron. 前者 adj. 以前的， 在前的', 7249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panic', 'n. 恐慌， 惊慌', 7250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extend', 'vt. 延长， 延伸；提供， 给予', 7251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hurl', 'vt. 猛投， 猛冲；大声叫骂', 7252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ax', 'n. 斧', 7253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'folk', 'adj. 民间的 n. 人们 <', 7254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intermediate', 'adj. 中间的， 居间的；中级的 n. 中间体， 媒介物', 7255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frank', 'adj. 坦白的， 直率的', 7256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consequently', 'adv. 因而， 所以', 7257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'virus', 'n. 病毒；有害影响', 7258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rape', 'vt. 强奸 n. 强奸', 7259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metaphor', 'n. 隐喻， 暗喻', 7260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sudden', 'adj. 突然的， 意外的 n. 突然发生的事', 7261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nickname', 'n. 绰号 vt. 给…起绰号', 7262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genre', 'n. 体载， 类型', 7263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scarcely', 'adv. 几乎不， 简直没有；刚刚 <', 7264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panel', 'n. 面， 板 A <；控制板， 仪表盘；专门小组', 7265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humanity', 'n. 人类； 人性， 人情；人文科学 A', 7266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'innovation', 'n. 创新， 革新， 改革 A', 7267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shutter', 'n. 百叶窗；快门', 7268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alternate', 'vi. 交替， 轮流 adj. 交替的， 轮流的', 7269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flu', 'n. 流行性感冒', 7270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tropical', 'adj. 热带的', 7271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plunge', 'v. 投入； 插进； 陷入；猛冲 n. 投入， 尝试', 7272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skeptical', 'adj. 怀疑的 A <', 7273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interview', 'vt. 采访； 面试 n. 接见， 会见； 采访； 面试', 7274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'naive', 'adj. 天真的； 幼稚的', 7275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'essential', 'adj. 必要的， 必不可少的；本质的， 基本的', 7276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expenditure', 'n. 花费；支出， 消耗', 7277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clarify', 'vt. 澄清； 阐明', 7278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnace', 'n. 炉子， 熔炉', 7279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scarf', 'n. 围巾； 头巾', 7280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ditch', 'n. 沟， 渠， 水沟', 7281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gasp', 'v. 喘息；气喘吁吁地说 < n. 喘息， 气喘 A', 7282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scare', 'v. 惊吓， 受惊 < n. 惊恐， 恐慌', 7283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thunder', 'vi. 打雷， 雷鸣 n. 雷； 轰隆声 vt. 大声说， 吼叫， 喊出', 7284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fore', 'adj. /', 7285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'observe', 'vt. 遵守， 奉行；观察， 注意到， 看到', 7286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnish', 'vt. 供应， 提供  <；装备， 布置', 7287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criticise', 'v. 批评， 评论', 7288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'garment', 'n. 衣服', 7289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rare', 'adj. 稀有的， 难得的， 珍奇的；稀薄的， 稀疏的', 7290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exclude', 'vt. 拒绝， 把…排除在外， 排斥', 7291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criticism', 'n. 批评， 评论', 7292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enlighten', 'vt. 启发， 启蒙； 教导', 7293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'utmost', 'adj. 最远的；极度的， 极端的 n. 极限， 极度； 最大可能', 7294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deduct', 'vt. 扣除；演绎', 7295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'image', 'n. 形象；肖像， 影像， 图像', 7296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fatigued', 'adj. 疲乏的', 7297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ribbon', 'n. 缎带， 丝带； 带， 带状物', 7298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portray', 'vt. 描写， 描绘；扮演， 饰演', 7299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mainland', 'n. 大陆， 本土', 7300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profound', 'adj. 深的， 深刻的， 意义深远的；渊博的， 造诣深的', 7301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'homogeneous', 'adj. 同种类的， 同性质的， 有相同特征的', 7302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affirm', 'vt. 断言， 肯定；证实， 宣誓说实话', 7303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marble', 'n. 大理石， 云石', 7304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necessity', 'n. 必需品；必要性， 需要', 7305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fog', 'n. 雾', 7306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frame', 'n. 框架； 骨架 vt. 装框子', 7307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'industrialize', 'vt. 使工业化', 7308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'origin', 'n. 起源， 由来；出身， 来历', 7309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocal', 'adj. 嗓音的， 发声的；直言不讳的 n. 声乐节目', 7310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clash', 'vi. 冲突， 碰撞 n. 冲突， 碰撞', 7311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overturn', 'vi. 翻倒， 倾覆 vt. 推翻 n. 翻倒， 倾覆', 7312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precaution', 'n. 预防； 谨慎； 警惕', 7313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'burden', 'n. 担子，负担，重担', 7314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clasp', 'v. 扣住， 钩住；紧握， 紧抱 n. 握手； 拥抱；扣子， 钩子', 7315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hover', 'vi. 翱翔， 盘旋 A；逗留在近旁； 徘徊； 彷徨， 犹豫', 7316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'random', 'adj. 随机的， 随意的 < n. 随机， 随意', 7317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dine', 'vi. 吃饭， 进餐 A', 7318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'personality', 'n. 人格， 个性；人物', 7319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alert', 'adj. 警惕的；机灵的', 7320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sanction', 'vt. 批准， 认可 n. 批准， 认可；约束因素， 约束力', 7321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rate', 'n. 速率， 比率；等级；价格， 费用 vt. 估价； 评级， 评价', 7322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plot', 'vi. 密谋， 策划 n. 秘密计划；小块土地；情节 vt. 标绘， 绘制', 7323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deduce', 'vt. 演绎， 推断', 7324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mosaic', 'n. 马赛克 <；镶嵌画', 7325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oak', 'adj. 橡木的 n. 栎树， 橡树， 橡木', 7326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosperity', 'n. 繁荣， 兴旺', 7327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contrary', 'adj. 相反的， 矛盾的， 对抗的 n. 矛盾， 反对；相反， 反面；对立物， 对立面', 7328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contend', 'vi. 竞争； 斗争 vt. 坚决主张', 7329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'digital', 'adj. 数字的 <', 7330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oar', 'n. 桨橹', 7331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rehearse', 'v. 排练；预演', 7332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gamble', 'vi. 赌博 n. 投机， 冒险； 赌博', 7333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specification', 'n. 详述； 说明书；规格， 规范 A', 7334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'counter', 'adv. 相反 adj. 相反的 v. 抵制， 反对； 反击 n. 柜台；计数器， 计算器', 7335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rhythm', 'n. 节奏， 韵律', 7336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layman', 'n. 普通信徒；门外汉， 外行', 7337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tease', 'v. 戏弄， 取笑；挑逗， 招惹 n. 戏弄他人者；戏弄， 挑逗', 7338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rash', 'adj. 鲁莽的， 轻率的 n. 疹， 皮疹；一连串令人不快的事物', 7339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'management', 'n. 经营， 管理；管理部门', 7340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'publish', 'vt. 出版， 刊印；公布， 发布', 7341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'correspondent', 'n. 记者； 通讯员', 7342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cylinder', 'n. 圆筒， 圆柱体；汽缸', 7343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'renew', 'v. 更新， 恢复， 重新开始， 继续 <', 7344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'withdraw', 'vt. 收回， 撤销 <；缩回， 退出 A；提取', 7345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assign', 'vt. 分配， 委派；指定', 7346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'straightforward', 'adv. 坦率地 adj. 正直的， 坦率的；简单的； 易懂的', 7347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decade', 'n. 十年', 7348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'congress', 'n. 大会；国会， 议会', 7349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divine', 'adj. 神的， 神圣的 A；非凡的， 超人的；神授的， 天赐的；极好的， 极美的 n. 牧师', 7350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'welfare', 'n. 福利 <；安宁， 幸福', 7351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foul', 'adj. 难闻的， 发臭的； 令人厌恶的， 糟透了的；下流的， 辱骂性的；恶劣的， 有暴风雨的 v. 对…犯规；弄脏， 弄污 n. 犯规', 7352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flourish', 'vi. 繁荣， 茂盛； 兴旺', 7353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intricate', 'adj. 错综复杂的， 复杂精细的', 7354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'astronaut', 'n. 宇航员', 7355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agony', 'n. 苦恼； 痛苦', 7356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vessel', 'n. 容器， 器皿；船， 舰；管； 血管', 7357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contemplate', 'vt. 盘算， 预期；思量， 对…周密考虑；注视， 凝视', 7358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drag', 'vt. 拖， 拖曳', 7359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zinc', 'n. 锌', 7360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'likely', 'adv. 大概， 多半 A adj. 很可能的； 有希望的', 7361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'issue', 'vi. 流出， 放出 vt. 发行， 发表； 颁布 < n. 发行， 期号；问题； 争论点， 争端', 7362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'literally', 'adv. 照字面意义； 逐字地；确实地， 真正地 A', 7363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lower', 'adj. 较低的， 下级的； 下游的 vt. 使降低； 放低', 7364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'index', 'n. 索引；标志 A；指数 vt. 附以索引， 编入索引', 7365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'doorway', 'n. 门口', 7366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fry', 'v. 油煎， 油炸', 7367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'odd', 'adj. 奇数的； 单的；奇怪的， 古怪的；临时的； 不固定的；带零头的， 余的', 7368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conservation', 'n. 保存； 保护； 保守 <；守恒， 不灭', 7369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supplement', 'n. 增补， 补充；增刊 vt. 增补， 补充', 7370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contrast', 'vi. 和…形成对照 vt. 使与…对比， 使与…对照 < n. 对照， 对比， 差异', 7371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brittle', 'adj. 易碎的； 脆的', 7372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occurrence', 'n. 发生， 出现；事件， 事故， 发生的事情', 7373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amplify', 'vt. 放大； 增强  <', 7374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inflation', 'n. 通货膨胀', 7375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disposal', 'n. 处理， 处置；布置， 安排', 7376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whirl', 'v. 旋转， 打转 n. 旋转， 急转 A <', 7377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'settlement', 'n. 解决； 决定； 调停；居留区， 住宅区 A', 7378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recede', 'vi. 退， 退去； 渐渐远去；向后倾斜， 缩 A', 7379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delegate', 'n. 代表 vt. 委派…为代表， 授权', 7380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'literature', 'n. 文学， 文学作品； 文献', 7381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sphere', 'n. 球； 球体；范围； 领域', 7382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tumour', 'n. 肿瘤， 肿块', 7383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'digest', 'vi. 消化 vt. 吸收， 领悟 n. 摘要， 文摘', 7384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dependence', 'n. 依靠， 依赖； 信任', 7385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ability', 'n. 能力， 智能；', 7386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'belief', 'n. 信仰， 信条 A；相信， 信念', 7387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'veto', 'n. 否决权 vt. 否决', 7388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vest', 'n. 背心， 马甲； 汗衫， 内衣', 7389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lantern', 'n. 提灯； 灯笼', 7390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disposition', 'n. 处理；天性； 气质；排列， 部署', 7391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slender', 'adj. 修长的， 苗条的； 细长的；微小的； 微薄的', 7392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oral', 'adj. 口头的', 7393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compensate', 'v. 补偿， 赔偿， 弥补', 7394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transaction', 'n. 办理， 处理；交易； 事务', 7395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conscious', 'adj. 意识到的， 自觉的； 有意识的', 7396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fur', 'n. 毛， 毛皮', 7397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pants', 'n. 长裤， 便裤；内裤', 7398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certify', 'vt. 证明； 保证；发证书给', 7399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'smog', 'n. 烟雾 <', 7400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solitary', 'adj. 单独的， 独自的；单个的， 唯一的；孤独的， 隐居的', 7401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locker', 'n. 储物柜， 有锁的橱柜', 7402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orchestra', 'n. 管弦乐队', 7403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sufficient', 'adj. 足够的， 充分的', 7404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'claim', 'v. 要求； 主张， 声称；索赔 n. 要求， 主张； 断言；索赔；权利， 要求权， 所有权', 7405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'widespread', 'adj. 分布广的； 普遍的', 7406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'antique', 'adj. 古时的， 古老的 n. 古物， 古董', 7407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'communication', 'n. 通讯； 传达； 传送； 交流', 7408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chronic', 'adj. 慢性的；积习难改的；严重的； 坏的', 7409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fasten', 'vt. 扎牢， 使固定', 7410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'porter', 'n. 搬运工人；门房', 7411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tolerance', 'n. 容忍， 宽容 A；公差', 7412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'toxic', 'adj. 有毒的；中毒的', 7413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turmoil', 'n. 混乱， 骚动', 7414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'author', 'n. 作者；创始人', 7415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'greenhouse', 'n. 温室', 7416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plus', 'adj. 正的， 加的 prep. 加上 n. 加号， 正号', 7417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wrench', 'vt. 猛拧， 猛拉；摆脱； 挣脱；使扭伤 n. 扳手；痛苦， 难受', 7418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expansion', 'n. 扩张； 膨胀；张开， 伸展', 7419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entry', 'n. 进入；入口； 通道；记载； 条目', 7420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'license', 'n. 许可证， 执照 vt. 准许， 认可', 7421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'puff', 'vi. 喘气； 喷气 n. 一口， 一阵', 7422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disk', 'n. 唱片； 圆盘， 盘状物', 7423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'headquarters', 'n. 司令部， 指挥部；总部， 总局', 7424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expand', 'v. 膨胀， 扩张 <；张开， 展开', 7425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fiscal', 'adj. 财政的， 国库的', 7426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gaze', 'n. /', 7427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'essay', 'n. 文章， 短文', 7428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magistrate', 'n. 地方法官， 治安官', 7429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'survey', 'vt. 俯瞰； 眺望 A；全面审视， 调查；测量， 勘定 n. 俯瞰； 眺望； 环视 A；全面审视， 调查；勘测； 测量图', 7430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retrieve', 'vt. 重新得到， 收回， 取回；挽回， 补救；检索', 7431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disc', 'n. 唱片； 圆盘， 盘状物', 7432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plug', 'n. 塞子， 插头 A vt. 堵塞； 嵌入， 插入', 7433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thermometer', 'n. 温度计', 7434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'postpone', 'vt. 推迟， 延期', 7435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bride', 'n. 新娘 A', 7436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'favourable', 'adj. 赞许的； 有利的， 顺利的', 7437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'code', 'n. 代码， 代号； 密码；法典， 法规； 规则， 规范', 7438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legacy', 'n. 遗产；遗留之物', 7439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hammer', 'v. 锤击， 敲打 n. 铁锤， 槌， 榔头', 7440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'displace', 'vt. 移置； 转移；取代； 置换', 7441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seal', 'n. 海豹；印， 图章 A；封铅， 封条 vt. 封， 密封', 7442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ideology', 'n. 思想体系； 思想意识， 意识形态', 7443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seam', 'n. 缝， 接缝', 7444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'investigate', 'vt. 调查， 调查研究', 7445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'storage', 'n. 贮藏， 保管， 存储；库房', 7446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illusion', 'n. 幻想中的事物； 错误的观念；错觉， 幻觉； 假象', 7447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'considerable', 'adj. 相当大的， 可观的；值得考虑的， 重要的', 7448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'productivity', 'n. 生产率', 7449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proposition', 'n. 主张， 建议；陈述， 命题', 7450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reserve', 'n. 保留地；储备； 储藏量； 储备金；缄默； 谨慎 vt. 保留， 储备；预订， 预约', 7451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heal', 'v. 治愈， 愈合<', 7452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'somehow', 'adv. 不知怎么地； 设法， 以某种方式', 7453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brick', 'n. 砖', 7454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dive', 'vi. 潜水；跳水； 俯冲 n. 潜水； 跳水； 俯冲', 7455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sympathy', 'n. 同情， 同情心；赞同', 7456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heap', 'v. 堆， 堆起 n. 堆， 大量， 许多', 7457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rescue', 'vt. 营救， 援救 < n. 营救， 援救', 7458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'roundabout', 'adj. 迂回的， 转弯抹角的 n. 环状交叉路', 7459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brief', 'adj. 简短的， 简洁的 n. 简报 vt. 简短介绍， 简要汇报', 7460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'keyboard', 'n. 键盘', 7461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embark', 'v. 上船', 7462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intelligent', 'adj. 聪明的， 明智的', 7463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confer', 'vi. 商谈， 商议 vt. 授予， 赋予', 7464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'friction', 'n. 摩擦； 摩擦力', 7465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equip', 'vt. 装备， 配备', 7466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'manuscript', 'n. 手稿， 原稿', 7467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Christian', 'adj. 基督教徒的 n. 基督教徒', 7468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'luxury', 'n. 奢侈， 华贵；奢侈品', 7469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spiritual', 'adj. 精神的， 心灵的', 7470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knit', 'v. 编织， 编结；接合， 黏合', 7471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'increasingly', 'adv. 不断增加地， 日益', 7472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salad', 'n. 色拉， 凉拌菜 <', 7473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'readily', 'adv. 容易地；乐意地， 欣然地', 7474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wholesome', 'adj. 卫生的； 健康的；有益于健康的； 有益的 <', 7475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convenience', 'n. 便利， 方便；便利设备', 7476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discipline', 'n. 纪律， 规定；学科；训练', 7477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'province', 'n. 省 A；领域， 范围', 7478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'estimate', 'vi. 估价， 估算 vt. 估计 n. 看法； 评价；判断', 7479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drip', 'vi. 滴下， 漏水 n. 滴， 水滴， 点滴', 7480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diploma', 'n. 文凭， 学位证书', 7481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brand', 'n. 商标， 标记， 牌子 vt. 使铭记；打火印， 打烙印', 7482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proposal', 'n. 提议， 建议；求婚', 7483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'choke', 'vi. 窒息， 噎住 < vt. 塞住， 堵塞， 阻塞', 7484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inevitable', 'adj. 不可避免的， 必然发生的', 7485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'edit', 'vt. 编辑， 校订', 7486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recreation', 'n. 娱乐， 消遣', 7487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'allowance', 'n. 津贴， 补助', 7488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skyscraper', 'n. 摩天大楼', 7489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portable', 'adj. 轻便的， 便携式的', 7490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ancient', 'adj. 古代的， 古老的', 7491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'squirrel', 'n. 松鼠', 7492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cognitive', 'adj. 认知的， 认识的， 有感知能力的', 7493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attorney', 'n. 律师', 7494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wander', 'vi. 漫步， 徘徊；迷路， 迷失方向；离题', 7495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adopt', 'vt. 采用， 采纳 <；通过；收养', 7496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expire', 'vi. 期满， 终止  A；断气， 死亡 vt. 呼气', 7497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oppose', 'vt. 反对， 反抗 <', 7498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'singular', 'adj. 非凡的， 卓越的；单数的； 唯一的', 7499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'device', 'n. 装置， 设备， 仪器；手段； 策略； 诡计', 7500);
