INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maneuver', 'n. [军] 机动；演习；策略；调遣 v. [军] 机动；演习；调遣；用计谋', 5001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mist', 'n. 薄雾；视线模糊不清；模糊不清之物 v. 下雾；变模糊', 5002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arch', 'n. 弓形，拱形；拱门 adj. 主要的 v. 使…弯成弓形；用拱连接', 5003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shipment', 'n. 装货；装载的货物', 5004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bleak', 'adj. 阴冷的；荒凉的，无遮蔽的；黯淡的，无希望的；冷酷的；单调的', 5005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oven', 'n. 炉，灶；烤炉，烤箱', 5006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hypocrisy', 'n. 虚伪；伪善', 5007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discharge', 'v. 解雇；卸下；放出；免除 n. 排放；卸货；解雇', 5008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trifle', 'n. 琐事；蛋糕；少量 v. 开玩笑；闲混；嘲弄', 5009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circumference', 'n. 圆周；周长；胸围', 5010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clone', 'n. 克隆；无性系；无性繁殖；靠营养生殖而由母体分离繁殖的植物 v. 无性繁殖，复制', 5011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graze', 'v. 放牧；擦伤 n. 放牧；轻擦', 5012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basement', 'n. 地下室；地窖', 5013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comparable', 'adj. 可比较的；比得上的', 5014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'february', 'n. 二月', 5015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'voltage', 'n. [电] 电压', 5016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instrumental', 'adj. 乐器的；有帮助的；仪器的，器械的 n. 器乐曲；工具字，工具格', 5017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fist', 'n. 拳，拳头；〈口〉笔迹；掌握；[印]指标参见号 vt. 紧握；握成拳；用拳打', 5018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carrot', 'n. 胡萝卜', 5019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'screw', 'v. 旋，拧；压榨；强迫 n. 螺旋；螺丝钉；吝啬鬼', 5020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thigh', 'n. 大腿，股', 5021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horrible', 'adj. 可怕的；极讨厌的', 5022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oil', 'n. 油；石油；油画颜料 v. 加油；涂油；使融化', 5023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'missile', 'n. 导弹；投射物 adj. 导弹的；可投掷的；用以发射导弹的', 5024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refund', 'v. 退还；偿还，归还 n. 退款；偿还，偿还额', 5025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wet', 'adj. [气象][物] 潮湿的；有雨的 n. 雨天；湿气 v. 弄湿', 5026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sane', 'adj. 健全的；理智的；[临床] 神志正常的 n. (Sane)人名；(日)实(姓)；(日)实(名)；(芬、塞、冈、几比、塞内)萨内', 5027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sand', 'n. 沙；沙地；沙洲；沙滩；沙子 v. 撒沙于；以沙掩盖；用砂纸等擦平或磨光某物；使撒沙似地布满；给…掺沙子', 5028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stair', 'n. 楼梯，阶梯；梯级', 5029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vapour', 'n. 蒸气（等于vapor）；水蒸气', 5030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unify', 'v. 统一；使相同，使一致', 5031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inland', 'n. 内地；内陆 adj. 内陆的；内地的；国内的 adv. 在内地；向内地；向内陆；在内陆', 5032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hydrogen', 'n. [化学] 氢', 5033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clever', 'adj. 聪明的；机灵的；熟练的', 5034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breed', 'v. 繁殖；饲养；产生 n. [生物] 品种；种类，类型', 5035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invariably', 'adv. 总是；不变地；一定地', 5036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lecture', 'n. 演讲；讲稿；教训 v. 演讲；训诫', 5037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stall', 'n. 货摊；畜栏；托辞 v. 停止，停转；拖延', 5038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snowstorm', 'n. 暴风雪；雪暴', 5039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'boundary', 'n. 边界；范围；分界线', 5040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'negro', 'n. 黑人 adj. 黑人的', 5041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pause', 'n. 暂停；间歇 v. 暂停，停顿，中止；踌躇', 5042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poll', 'n. 投票；民意测验；投票数；投票所 v. 投票；剪短；对…进行民意测验；获得选票 adj. 无角的；剪过毛的；修过枝的', 5043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pole', 'n. 杆；极点；电极 v. 用竿支撑', 5044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'troublesome', 'adj. 麻烦的；讨厌的；使人苦恼的', 5045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oval', 'adj. 椭圆的；卵形的 n. 椭圆形；卵形', 5046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sting', 'n. 刺痛；讽刺，刺激；刺毛 v. 刺；驱使；使…苦恼；使…疼痛', 5047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handicap', 'n. 障碍；不利条件，不利的因素 v. 妨碍，阻碍；使不利', 5048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apology', 'n. 道歉；谢罪；辩护；勉强的替代物', 5049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portrait', 'n. 肖像；描写；半身雕塑像', 5050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compress', 'v. 受压缩小', 5051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cough', 'n. 咳嗽，咳嗽声；咳嗽病 v. 咳出', 5052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recede', 'v. 后退；减弱', 5053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neat', 'adj. 灵巧的；整洁的；优雅的；齐整的；未搀水的；平滑的', 5054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stalk', 'n. （植物的）茎，秆；（支持叶子、果实和花的）梗，柄；追踪；高视阔步 v. 追踪，潜近；高视阔步', 5055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stale', 'adj. 陈腐的；不新鲜的 v. 变陈旧；撒尿；变得不新鲜 n. 尿', 5056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salt', 'n. 盐；风趣，刺激性 adj. 咸水的；含盐的，咸味的；盐腌的；猥亵的 v. 用盐腌；给…加盐；将盐撒在道路上使冰或雪融化', 5057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pound', 'n. 英镑；重击，重击声；兽栏；拘留所 v. 捣烂；敲打；监禁，拘留', 5058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neck', 'n. 脖子；衣领；海峡 v. 搂著脖子亲吻；变狭窄', 5059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'throw', 'v. 投；抛；掷 n. 投掷；冒险', 5060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pond', 'vt. 筑成池塘 vi. 筑成池塘 n. 池塘', 5061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stamp', 'n. 邮票；印记；标志；跺脚 v. 铭记；标出；盖章于…；贴邮票于…；用脚踩踏', 5062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fraction', 'n. 分数；部分；小部分；稍微', 5063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'objection', 'n. 异议，反对；缺陷，缺点；妨碍；拒绝的理由', 5064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'desolate', 'adj. 荒凉的；无人烟的 v. 使荒凉；使孤寂', 5065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'roast', 'v. 烤，焙；烘，烘烤；暴露于某种热力下以得温暖 adj. 烘烤的；烤过的 n. 烤肉；烘烤', 5066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'headquarters', 'n. 总部；指挥部；司令部', 5067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arrival', 'n. 到来；到达；到达者', 5068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handkerchief', 'n. 手帕；头巾，围巾', 5069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stomach', 'n. 胃；腹部；胃口 v. 忍受；吃下', 5070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radioactive', 'adj. [核] 放射性的；有辐射的', 5071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sorrow', 'n. 悲伤；懊悔；伤心事 v. 懊悔；遗憾；感到悲伤', 5072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tanker', 'n. 油轮；运油飞机；油槽车；坦克手', 5073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotate', 'v. 旋转；循环 adj. [植] 辐状的', 5074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curl', 'v. 使…卷曲；使卷起来 n. 卷曲；卷发；螺旋状物', 5075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'receipt', 'n. 收到；收据；收入 v. 收到', 5076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'integral', 'adj. 积分的；完整的，整体的；构成整体所必须的 n. 积分；部分；完整', 5077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bread', 'n. 面包；生计 v. 在…上洒面包屑', 5078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'import', 'n. 进口，进口货；输入；意思，含义；重要性 v. 输入，进口；含…的意思', 5079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'synthesis', 'n. 综合，[化学] 合成；综合体', 5080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cassette', 'n. 盒式磁带；暗盒；珠宝箱；片匣', 5081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knife', 'n. 刀；匕首 v. 用刀切；（口）伤害', 5082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'butterfly', 'n. 蝴蝶；蝶泳；举止轻浮的人；追求享乐的人', 5083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ring', 'v. 按铃；敲钟；回响；成环形 n. 戒指；铃声，钟声；拳击场；环形物', 5084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'welfare', 'n. 福利；幸福；福利事业；安宁 adj. 福利的；接受社会救济的', 5085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'destination', 'n. 目的地，终点', 5086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discount', 'n. 折扣；贴现率 v. 贴现；打折扣出售商品', 5087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gas', 'n. 气体；[矿业] 瓦斯；汽油；毒气 v. 加油；毒（死）', 5088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gay', 'adj. 快乐的；放荡的；艳丽的 n. 同性恋者', 5089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poster', 'n. 海报，广告；招贴', 5090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abundance', 'n. 充裕，丰富', 5091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mosquito', 'n. 蚊子', 5092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'riot', 'n. 暴乱；放纵；蔓延 v. 骚乱；放荡', 5093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'closet', 'n. 壁橱；议事室，密室；小房间 adj. 秘密的，私下的；空谈的 v. 把…关在私室中', 5094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recover', 'v. 恢复；弥补；重新获得 n. 还原至预备姿势', 5095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dizzy', 'adj. 晕眩的；使人头晕的；昏乱的；心不在焉的；愚蠢的 v. 使头晕眼花；使混乱；使茫然 n. (Dizzy)人名；(英)迪齐', 5096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oak', 'n. 橡树；橡木色；橡木家具 adj. 栎树的；栎木制的', 5097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consecutive', 'adj. 连贯的；连续不断的', 5098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotary', 'adj. 旋转的，转动的；轮流的 n. 旋转式机器；[动力] 转缸式发动机', 5099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oar', 'n. 桨；橹；桨手 vt. 划（船） vi. 划行', 5100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flight', 'n. 飞行；班机；逃走 v. 射击；使惊飞', 5101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kettle', 'n. 壶；[化工] 釜；罐；鼓', 5102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proposal', 'n. 提议，建议；求婚', 5103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ripe', 'adj. 熟的，成熟的；时机成熟的 vt. 搜查；调查 vi. 进行搜查 n. (Ripe)人名；(意、瑞典)里佩', 5104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resemblance', 'n. 相似；相似之处；相似物；肖像', 5105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uncover', 'v. 发现；揭开；揭露', 5106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illustration', 'n. 说明；插图；例证；图解', 5107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nursery', 'n. 苗圃；托儿所；温床', 5108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'niece', 'n. 外甥女，侄女', 5109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refuge', 'n. 避难；避难所；庇护 vt. 给予…庇护；接纳…避难 vi. 避难；逃避', 5110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'buffet', 'n. 自助餐；小卖部；打击；猛烈冲击 v. 与…搏斗；连续猛击 adj. 自助的；自助餐的', 5111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'squeeze', 'v. 挤；紧握；勒索 n. 压榨；紧握；拥挤；佣金', 5112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'envisage', 'v. 正视，面对；想像', 5113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torture', 'v. 折磨；拷问；歪曲 n. 折磨；拷问；歪曲', 5114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'champion', 'n. 冠军；拥护者；战士 v. 支持；拥护 adj. 优胜的；第一流的', 5115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'republic', 'n. 共和国；共和政体', 5116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fling', 'v. 掷，抛；嘲笑；使陷入；轻蔑地投射；猛动 n. 掷，抛；嘲弄；急冲', 5117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'musical', 'adj. 音乐的；悦耳的 n. 音乐片', 5118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dusk', 'n. 黄昏，薄暮；幽暗，昏暗 adj. 微暗的 v. 使变微暗', 5119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bulletin', 'n. 公告，公报 v. 公布，公告', 5120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stiff', 'adj. 呆板的；坚硬的；严厉的；拘谨的 adv. 僵硬地；彻底地 n. 死尸；令人讨厌者；流通票据；劳动者 v. 诈骗；失信', 5121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stack', 'n. 堆；堆叠 v. 使堆叠；把…堆积起来', 5122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cotton', 'n. 棉花；棉布；棉线 v. 一致；理解；和谐；亲近 adj. 棉的；棉制的', 5123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fixture', 'n. 设备；固定装置；固定于某处不大可能移动之物', 5124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frog', 'n. 青蛙；[铁路] 辙叉；饰扣 v. 捕蛙', 5125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'earnest', 'adj. 认真的，热心的；重要的 n. 认真；定金；诚挚', 5126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wax', 'n. 蜡；蜡状物 v. 给…上蜡 adj. 蜡制的；似蜡的', 5127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symphony', 'n. 交响乐；谐声，和声', 5128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loudspeaker', 'n. 喇叭，扬声器；扩音器', 5129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'naval', 'adj. 海军的；军舰的 n. (Naval)人名；(西、德、印)纳瓦尔', 5130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spacious', 'adj. 宽敞的，广阔的；无边无际的', 5131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mould', 'v. 发霉 n. 模具；霉', 5132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'linger', 'v. 徘徊；苟延残喘；磨蹭 n. (Linger)人名；(德、捷、瑞典)林格；(法)兰热', 5133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retention', 'n. 保留；扣留，滞留；记忆力；闭尿', 5134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heave', 'v. 举起；使起伏；投掷；恶心；发出（叹息等） n. 举起；起伏；投掷；一阵呕吐', 5135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sophomore', 'n. 大学二年级生；（美）有二年经验的人 adj. 二年级的；二年级学生的', 5136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'driver', 'n. 驾驶员；驱动程序；起子；传动器', 5137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'swarm', 'v. 挤满；成群浮游；云集 n. 蜂群；一大群', 5138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poem', 'n. 诗', 5139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'playground', 'n. 运动场，操场；游乐场', 5140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avert', 'v. 避免，防止；转移', 5141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hover', 'v. 盘旋，翱翔；徘徊 n. 徘徊；盘旋；犹豫', 5142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oath', 'n. 誓言，誓约；诅咒，咒骂', 5143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marxist', 'n. 马克思主义者 adj. 马克思主义的', 5144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evacuate', 'v. 疏散，撤退；排泄', 5145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bleed', 'v. 使出血；榨取', 5146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wood', 'n. 木材；木制品；树林 vi. 收集木材 vt. 植林于；给…添加木柴', 5147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arrow', 'n. 箭，箭头；箭状物；箭头记号 vt. 以箭头指示；箭一般地飞向', 5148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'installation', 'n. 安装，装置；就职', 5149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'classify', 'v. 分类；分等', 5150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slipper', 'n. 拖鞋 vt. 用拖鞋打', 5151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intercourse', 'n. 性交；交往；交流', 5152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anticipate', 'v. 预期，期望；占先，抢先；提前使用', 5153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'juice', 'n. （水果）汁，液；果汁', 5154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wool', 'n. 羊毛；毛线；绒线；毛织品；毛料衣物', 5155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'undermine', 'v. 破坏，渐渐破坏；挖掘地基', 5156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kitchen', 'n. 厨房；炊具；炊事人员', 5157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'astronomy', 'n. 天文学', 5158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'declare', 'v. 宣布，声明；断言，宣称', 5159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proceeding', 'n. 进行；程序；诉讼；事项 v. 开始；继续做；行进（proceed的ing形式）', 5160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prick', 'v. 刺，戳；刺伤，刺痛；竖起 n. 刺，扎；刺痛，刺伤；阴茎；锥 adj. 竖起的', 5161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supper', 'n. 晚餐，晚饭；夜宵', 5162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'owl', 'n. 猫头鹰；枭；惯于晚上活动的人', 5163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'warmth', 'n. 温暖；热情；激动', 5164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'latitude', 'n. 纬度；界限；活动范围', 5165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'multitude', 'n. 群众；多数', 5166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wheel', 'n. 车轮；方向盘；转动 v. 转动；使变换方向；给…装轮子', 5167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breakfast', 'n. 早餐；早饭 v. 吃早餐', 5168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bucket', 'n. 桶，水桶；铲斗；一桶的量 v. 倾盆而下；颠簸着行进', 5169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'explosive', 'adj. 爆炸的；爆炸性的；爆发性的 n. 炸药；爆炸物', 5170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'digital', 'adj. 数字的；手指的 n. 数字；键', 5171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'belly', 'n. 腹部；胃；食欲 v. 涨满；鼓起', 5172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prohibit', 'v. 阻止，禁止', 5173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lapse', 'n. (一时的) 走神，判断错误', 5174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'festival', 'n. 节日；庆祝，纪念活动；欢乐 adj. 节日的，喜庆的；快乐的', 5175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appliance', 'n. 器具；器械；装置', 5176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hail', 'n. 冰雹；致敬；招呼；一阵 v. 致敬；招呼；向欢呼；猛发；使像下雹样落下（过去式hailed，过去分词hailed，现在分词hailing，第三人称单数hails） int. 万岁；欢迎', 5177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'angle', 'v. 钓鱼；谋取 n. 角度，角，方面', 5178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vulgar', 'adj. 粗俗的；通俗的；本土的 n. 平民，百姓', 5179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passenger', 'n. 旅客；乘客；过路人；碍手碍脚的人', 5180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intervene', 'v. 干涉；调停；插入', 5181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locomotive', 'adj. 火车头的；运动的；移动的 n. 机车；火车头', 5182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reclaim', 'v. 开拓；回收再利用；改造某人，使某人悔改 n. 改造，感化；再生胶', 5183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irony', 'n. 讽刺；反语；具有讽刺意味的事 adj. 铁的；似铁的', 5184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prompt', 'adj. 敏捷的，迅速的；立刻的 v. 提示；促进；激起；（给演员）提白 n. 提示；付款期限；DOS命令：改变DOS系统提示符的风格 adv. 准时地', 5185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'queue', 'n. 队列；长队；辫子 v. 排队；排队等候', 5186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breadth', 'n. 宽度，幅度；宽宏', 5187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surrender', 'v. 使投降；放弃；交出；听任 n. 投降；放弃；交出；屈服', 5188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'earthquake', 'n. 地震；大动荡', 5189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'telegraph', 'n. [通信] 电报机，电报 v. 电汇；流露出；打电报给…', 5190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transistor', 'n. 晶体管（收音机）', 5191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hemisphere', 'n. 半球', 5192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'electricity', 'n. 电力；电流；强烈的紧张情绪', 5193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pamphlet', 'n. 小册子', 5194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excursion', 'n. 偏移；远足；短程旅行；离题；游览，游览团', 5195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overnight', 'adv. 通宵；突然；昨晚 adj. 晚上的；通宵的；前夜的 n. 头天晚上；一夜的逗留 vt. 连夜快递 vi. 过一夜', 5196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotten', 'adj. 腐烂的；堕落的；恶臭的；虚弱的；极坏的 adv. 非常 n. (Rotten)人名；(法、德)罗滕', 5197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certainty', 'n. 必然；确实；确实的事情', 5198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transient', 'adj. 短暂的；路过的 n. 瞬变现象；过往旅客；候鸟', 5199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coffee', 'n. 咖啡；咖啡豆；咖啡色', 5200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wreath', 'n. 花冠；圈状物 v. 环绕（等于wreathe）', 5201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poison', 'v. 污染；使中毒，放毒于；败坏；阻碍 n. 毒药，毒物；酒；有毒害的事物；[助剂] 抑制剂 adj. 有毒的', 5202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shiver', 'n. 颤抖，战栗；碎片 v. 颤抖；哆嗦；打碎', 5203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salesman', 'n. 推销员；售货员', 5204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'angel', 'n. 天使；守护神；善人 vt. 出钱支持', 5205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'christ', 'n. 基督；救世主 int. 天啊！', 5206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shutter', 'n. 快门；百叶窗；关闭物；遮板 v. 为…装百叶窗；以百叶窗遮闭', 5207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'raid', 'n. 袭击；突袭；搜捕；抢劫 v. 对…进行突然袭击', 5208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'weld', 'v. 焊接；使结合；使成整体 n. 焊接；焊接点', 5209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dump', 'v. 倾倒；倾卸；丢下，卸下；摆脱，扔弃；倾销 n. 垃圾场；仓库；无秩序地累积', 5210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tube', 'n. 管；电子管；隧道；电视机 v. 使成管状；把…装管；用管输送', 5211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compass', 'n. 指南针，罗盘；圆规 v. 包围', 5212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shopkeeper', 'n. 店主，老板', 5213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'facility', 'n. 设施；设备；容易；灵巧', 5214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'definite', 'adj. 一定的；确切的', 5215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dull', 'adj. 钝的；迟钝的；无趣的；呆滞的；阴暗的 v. 使迟钝；使阴暗；缓和 n. (Dull)人名；(罗、匈)杜尔；(柬)杜；(英)达尔', 5216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tuck', 'v. 卷起；挤进；用某物舒适地裹住；使有褶裥；收拢；大口吃；使隐藏 n. 食物；船尾突出部；缝摺；抱膝式跳水；活力；鼓声', 5217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whistle', 'n. 口哨；汽笛；呼啸声 v. 吹口哨；鸣汽笛', 5218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notebook', 'n. 笔记本，笔记簿；手册', 5219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wolf', 'n. 狼；色狼；残忍贪婪之人 v. 大吃；狼吞虎咽地吃', 5220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'timely', 'adj. 及时的；适时的 adv. 及时地；早', 5221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harvest', 'n. 收获；产量；结果 v. 收割；得到', 5222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fry', 'n. 鱼苗；油炸食物 v. 油炸；油煎', 5223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tension', 'n. 张力，拉力；紧张，不安；电压 vt. 使紧张；使拉紧', 5224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quarterly', 'adj. 季度的，按季度的；一年四次的 adv. 按季度，[农] 一季一次地；纵横四分地 n. 季刊', 5225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flash', 'v. 使闪光；反射 n. 闪光，闪现；一瞬间 adj. 闪光的，火速的', 5226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marble', 'n. 大理石；大理石制品；弹珠 adj. 大理石的；冷酷无情的', 5227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'angry', 'adj. 生气的；愤怒的；狂暴的；（伤口等）发炎的', 5228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distinct', 'adj. 明显的；独特的；清楚的；有区别的', 5229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uneasy', 'adj. 不舒服的；心神不安的；不稳定的', 5230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opt', 'v. 选择', 5231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'satire', 'n. 讽刺；讽刺文学，讽刺作品', 5232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glad', 'adj. 高兴的；乐意的；令人高兴的；灿烂美丽的 vt. 使高兴 n. (Glad)人名；(塞、瑞典)格拉德；(英)格莱德；(法、挪)格拉', 5233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grass', 'n. 草；草地，草坪 v. 放牧；使……长满草；使……吃草', 5234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locker', 'n. 柜，箱；上锁的人；有锁的橱柜；锁扣装置；有锁的存物柜', 5235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occasional', 'adj. 偶然的；临时的；特殊场合的', 5236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wholesome', 'adj. 健全的；有益健康的；合乎卫生的；审慎的', 5237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hunger', 'n. 饿，饥饿；渴望 v. 渴望；挨饿', 5238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violate', 'v. 违反；侵犯，妨碍；亵渎', 5239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recycle', 'v. 使再循环；使…重新利用 n. 再生；再循环；重复利用', 5240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'container', 'n. 集装箱；容器', 5241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cube', 'n. 立方；立方体；骰子 v. 使成立方形；使自乘二次；量…的体积', 5242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flare', 'v. 使闪耀；使张开；用发光信号发出；使外倾 n. 加剧，恶化；底部展开；（鼻孔）张开的意思；闪光，闪耀；耀斑；爆发；照明弹', 5243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ore', 'n. 矿；矿石', 5244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cargo', 'n. 货物，船货', 5245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'particle', 'n. 颗粒；[物] 质点；极小量；小品词', 5246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cloth', 'n. 布；织物；桌布 adj. 布制的', 5247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feudal', 'adj. 封建制度的；领地的；世仇的', 5248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'velocity', 'n. 【物】速度', 5249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simplify', 'v. 简化；使单纯；使简易', 5250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gigantic', 'adj. 巨大的，庞大的', 5251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'desert', 'v. 遗弃；放弃；逃跑 n. 沙漠；荒原；应得的赏罚 adj. 沙漠的；荒凉的；不毛的', 5252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'miracle', 'n. 奇迹，奇迹般的人或物；惊人的事例', 5253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'progressive', 'adj. 进步的；先进的 n. 改革论者；进步分子', 5254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crystal', 'n. 结晶，晶体；水晶；水晶饰品 adj. 水晶的；透明的，清澈的', 5255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'saint', 'n. 圣人；圣徒；道德崇高的人 adj. 神圣的 v. 成为圣徒', 5256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secretary', 'n. 秘书；书记；部长；大臣', 5257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snake', 'n. 蛇；阴险的人 v. 迂回前进', 5258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distract', 'v. 转移；分心', 5259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layman', 'n. 外行；门外汉；俗人；一般信徒', 5260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preclude', 'v. 排除；妨碍；阻止', 5261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rack', 'n. [机] 齿条；架子；拷问台 v. 变形；随风飘；小步跑', 5262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'twinkle', 'v. 闪烁；发亮 n. 闪烁', 5263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'silly', 'adj. 愚蠢的；不明事理的；没头脑的 n. 傻瓜', 5264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'misfortune', 'n. 不幸；灾祸，灾难', 5265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grand', 'adj. 宏伟的；豪华的；极重要的 n. 大钢琴；一千美元', 5266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'duck', 'n. 鸭子；鸭肉；（英）宝贝儿；零分 v. 闪避；没入水中', 5267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flu', 'n. 流感', 5268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cattle', 'n. 牛；牲畜（骂人的话）；家畜；无价值的人', 5269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tune', 'n. 曲调；和谐；心情 v. 调整；使一致；为…调音', 5270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'centimetre', 'n. 厘米；公分', 5271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clerk', 'n. 职员，办事员；店员；书记；记账员；<古>牧师，教士 v. 当销售员，当店员；当职员', 5272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stitch', 'n. 针脚，线迹；一针 v. 缝，缝合', 5273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zebra', 'n. [脊椎] 斑马 adj. 有斑纹的', 5274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'campus', 'n. （大学）校园；大学，大学生活；校园内的草地', 5275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clay', 'n. [土壤] 粘土；泥土；肉体；似黏土的东西 vt. 用黏土处理', 5276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ride', 'v. 骑马；乘车；依靠；漂浮 n. 骑；乘坐；交通工具；可供骑行的路；（乘坐汽车等的）旅行；乘骑；（乘车或骑车的）短途旅程；供乘骑的游乐设施', 5277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intention', 'n. 意图；目的；意向；愈合', 5278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alloy', 'v. 使成合金；使减低成色 n. 合金', 5279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paralyze', 'v. 使麻痹；使瘫痪', 5280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fix', 'v. 使固定；修理；安装；准备 n. 困境；方位；贿赂', 5281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notify', 'v. 通告，通知；公布', 5282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fine', 'adj. 好的；优良的；细小的，精美的；健康的；晴朗的 n. 罚款 v. 罚款；澄清 adv. 很好地；精巧地', 5283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passion', 'n. 激情；热情；酷爱；盛怒', 5284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wheat', 'n. 小麦；小麦色', 5285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rice', 'n. 稻；米饭 v. 把…捣成米糊状', 5286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'savage', 'adj. 野蛮的；残酷的；狂怒的；荒凉的 n. 未开化的人；粗鲁的人；残暴成性的人 v. 乱咬；粗暴的对待', 5287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cinema', 'n. 电影；电影院；电影业，电影制作术', 5288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'millimeter', 'n. [计量] 毫米', 5289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clap', 'v. 鼓掌，拍手；啪地关上 n. 鼓掌；拍手声', 5290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'claw', 'n. 爪；螯，钳；爪形器具 v. 用爪抓（或挖）', 5291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portray', 'v. 描绘；扮演', 5292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'librarian', 'n. 图书馆员；图书管理员', 5293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horn', 'n. 喇叭，号角；角 v. 装角于', 5294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incorporate', 'v. 包含，吸收；体现；把……合并 adj. 合并的；一体化的；组成公司的', 5295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hose', 'n. 软管；长筒袜；男性穿的紧身裤 v. 用软管浇水；痛打', 5296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barn', 'n. 谷仓；畜棚；车库；靶（核反应截面单位） vt. 把…贮存入仓', 5297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'auxiliary', 'n. 助动词；辅助者，辅助物；附属机构 adj. 辅助的；副的；附加的', 5298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spacecraft', 'n. [航] 宇宙飞船，航天器', 5299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bare', 'adj. 空的；赤裸的，无遮蔽的 v. 露出，使赤裸 n. (Bare)人名；(英)贝尔', 5300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'condense', 'v. 浓缩；凝结', 5301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thunder', 'n. 雷；轰隆声；恐吓 v. 打雷；怒喝', 5302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'microphone', 'n. 扩音器，麦克风', 5303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'duplicate', 'v. 复制；使加倍 n. 副本；复制品 adj. 复制的；二重的', 5304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maths', 'n. 数学（等于mathematics）', 5305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neutral', 'adj. 中立的，中性的；中立国的；非彩色的 n. 中立国；中立者；非彩色；齿轮的空档', 5306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'worship', 'n. 崇拜；礼拜；尊敬 v. 崇拜；尊敬；爱慕', 5307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stationery', 'n. 文具；信纸', 5308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divert', 'v. 转移；使…欢娱；使…转向 n. (Divert)人名；(法)迪韦尔', 5309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liner', 'n. 班轮，班机；衬垫；画线者', 5310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'linen', 'n. 亚麻布，亚麻线；亚麻制品 adj. 亚麻的；亚麻布制的', 5311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'queer', 'adj. 奇怪的；同性恋的；不舒服的；心智不平衡的 v. 搞糟；使陷于不利地位 n. 同性恋者；怪人；伪造的货币', 5312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'practise', 'v. 练习，实践；实施，实行；从事', 5313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'butcher', 'v. 屠杀 n. 屠夫', 5314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beware', 'v. 当心，小心', 5315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jargon', 'n. 行话，术语；黄锆石', 5316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bath', 'n. 沐浴；浴室；浴盆 v. 洗澡', 5317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trousers', 'n. 裤子，长裤', 5318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tilt', 'v. 倾斜；翘起；以言词或文字抨击 n. 倾斜', 5319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salvation', 'n. 拯救；救助', 5320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nerve', 'n. 神经；勇气；[植] 叶脉 v. 鼓起勇气', 5321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'edible', 'adj. 可食用的 n. 食品；食物', 5322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reproach', 'n. 责备；耻辱 v. 责备；申斥', 5323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tile', 'n. 瓷砖，瓦片 v. 铺以瓦；铺以瓷砖', 5324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aunt', 'n. 阿姨；姑妈；伯母；舅妈', 5325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gratitude', 'n. 感谢（的心情）；感激', 5326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'psychiatry', 'n. 精神病学；精神病治疗法', 5327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conviction', 'n. 定罪；确信；证明有罪；确信，坚定的信仰', 5328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ditch', 'v. 在…上掘沟；把…开入沟里；丢弃 n. 沟渠；壕沟', 5329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'qualify', 'v. 限制；使具有资格；证明…合格', 5330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bounce', 'n. 跳；弹力；活力 v. 弹跳；使弹起', 5331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cock', 'n. 公鸡；龙头；雄鸟；头目 v. 使竖起；使耸立；使朝上', 5332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kiss', 'v. 吻；（风等）轻拂 n. 吻；轻拂', 5333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'band', 'n. 带，环；[物] 波段；(演奏流行音乐的) 乐队 v. 用带绑扎；给镶边', 5334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terminal', 'n. 末端；终点；终端机；极限 adj. 末端的；终点的；晚期的', 5335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diversion', 'n. 转移；消遣；分散注意力', 5336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scramble', 'v. 攀登；使混杂，仓促凑成；扰乱 n. 抢夺，争夺；混乱，混乱的一团；爬行，攀登', 5337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specimen', 'n. 样品，样本；标本', 5338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'friendship', 'n. 友谊；友爱；友善', 5339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invasion', 'n. 入侵，侵略；侵袭；侵犯', 5340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parasite', 'n. 寄生虫；食客', 5341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bang', 'n. 刘海；重击；突然巨响 adv. 直接地；砰然地；突然巨响地 v. 重击；发巨响', 5342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seemingly', 'adv. 看来似乎；表面上看来', 5343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vital', 'adj. 至关重要的；生死攸关的；有活力的 n. (Vital)人名；(法、德、意、俄、葡)维塔尔；(西)比塔尔', 5344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'textbook', 'n. 教科书，课本', 5345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cream', 'n. 奶油，乳脂；精华；面霜；乳酪', 5346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orbit', 'n. 轨道；眼眶；势力范围；生活常规 v. 盘旋；绕轨道运行', 5347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tame', 'adj. 驯服的；平淡的；乏味的；顺从的 v. 驯养；使变得平淡；制服 n. (Tame)人名；(捷)塔梅', 5348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accustomed', 'adj. 习惯的；通常的；独有的 v. 使习惯于（accustom的过去分词）', 5349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'van', 'n. 先锋；厢式货车；增值网 vt. 用车搬运', 5350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concise', 'adj. 简明的，简洁的', 5351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emperor', 'n. 皇帝，君主', 5352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'powder', 'n. 粉；粉末；[化工][军] 火药；尘土 v. 使成粉末；撒粉；搽粉于', 5353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fare', 'v. 经营；进展；遭遇；过活 n. 票价；费用；旅客；食物', 5354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blaze', 'v. 在树皮上刻路标；公开宣布 n. 火焰，烈火；光辉；情感爆发', 5355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flock', 'n. 群；棉束（等于floc） v. 用棉束填满', 5356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lad', 'n. 少年，小伙子；家伙', 5357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shepherd', 'v. 牧羊；带领；指导；看管 n. 牧羊人；牧师；指导者', 5358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ally', 'n. 同盟国；伙伴；同盟者；助手 v. 使联盟；使联合', 5359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ache', 'v. 疼痛；渴望 n. 疼痛', 5360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tale', 'n. 故事；传说；叙述；流言蜚语', 5361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'predominant', 'adj. 主要的；卓越的；支配的；有力的；有影响的', 5362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lap', 'n. 一圈；膝盖；下摆；山坳 v. 使重叠；拍打；包围', 5363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offset', 'n. 抵消，补偿；平版印刷；支管 v. 抵消；弥补；用平版印刷术印刷', 5364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tall', 'adj. 高的；长的；过分的；夸大的 adv. 夸大地 n. (Tall)人名；(马里、阿拉伯)塔勒；(芬、罗、瑞典)塔尔；(英)托尔；(土)塔勒', 5365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coat', 'n. 外套 v. 覆盖…的表面', 5366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calendar', 'n. 日历；[天] 历法；日程表 v. 将…列入表中；将…排入日程表', 5367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dazzle', 'n. 耀眼的光；灿烂 v. 使……目眩；使……眼花', 5368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anniversary', 'n. 周年纪念日', 5369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cable', 'n. 缆绳；电缆；海底电报 v. 打电报', 5370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kite', 'n. 风筝 v. 使用空头支票；像风筝一样飞；轻快地移动', 5371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disrupt', 'v. 破坏；使瓦解；使分裂；使中断；使陷于混乱 adj. 分裂的，中断的；分散的', 5372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acid', 'n. 酸；<俚>迷幻药 adj. 酸的；讽刺的；刻薄的', 5373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retrieve', 'v. [计] 检索；恢复；重新得到 n. [计] 检索；恢复，取回', 5374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vitamin', 'n. [生化] 维生素；[生化] 维他命', 5375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fruitful', 'adj. 富有成效的；多产的；果实结得多的', 5376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peanut', 'n. 花生', 5377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thermal', 'adj. 热的；热量的；保热的 n. 上升的热气流', 5378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shuttle', 'n. 航天飞机；穿梭；梭子；穿梭班机、公共汽车等 v. 使穿梭般来回移动；短程穿梭般运送', 5379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cue', 'n. 提示，暗示；线索 v. 给…暗示', 5380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'historic', 'adj. 有历史意义的；历史上著名的', 5381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hatred', 'n. 憎恨；怨恨；敌意', 5382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stroke', 'n. （游泳或划船的）划；中风；（打、击等的）一下；冲程；（成功的）举动；尝试；轻抚 v. （用笔等）画；轻抚；轻挪；敲击；划尾桨；划掉；（打字时）击打键盘', 5383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torment', 'v. 折磨，使痛苦；纠缠，作弄 n. 痛苦，苦恼；痛苦的根源', 5384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'numerous', 'adj. 许多的，很多的', 5385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'burglar', 'n. 夜贼，窃贼', 5386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'privacy', 'n. 隐私；秘密；隐居；隐居处', 5387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strawberry', 'n. 草莓；草莓色', 5388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'antenna', 'n. [电讯] 天线；[动] 触角，[昆] 触须', 5389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recorder', 'n. 录音机；记录器；记录员；八孔直笛', 5390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creep', 'v. 爬行；蔓延；慢慢地移动；起鸡皮疙瘩 n. 爬行；毛骨悚然的感觉；谄媚者', 5391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inflation', 'n. 膨胀；通货膨胀；夸张；自命不凡', 5392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compartment', 'n. [建] 隔间；区划；卧车上的小客房 vt. 分隔；划分', 5393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incident', 'n. 事件，事变；插曲 adj. [光] 入射的；附带的；易发生的，伴随而来的', 5394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shore', 'v. 支撑，使稳住；用支柱撑住 n. 海滨；支柱', 5395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pardon', 'n. 原谅；赦免；宽恕 v. 原谅；赦免；宽恕', 5396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'empire', 'n. 帝国；帝王统治，君权', 5397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ministry', 'n. （政府的）部门', 5398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tape', 'n. 胶带；磁带；带子；卷尺 v. 录音；用带子捆扎；用胶布把…封住', 5399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'holy', 'adj. 圣洁的，神圣的；至善的 n. 神圣的东西', 5400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fiber', 'n. 纤维；光纤（等于fibre）', 5401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quiz', 'n. 考查；恶作剧；课堂测验 v. 挖苦；张望；对…进行测验', 5402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'melody', 'n. 旋律；歌曲；美妙的音乐', 5403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fertile', 'adj. 富饶的，肥沃的；能生育的', 5404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portion', 'n. 部分；一份；命运 v. 分配；给…嫁妆', 5405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'manuscript', 'n. [图情] 手稿；原稿 adj. 手写的', 5406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'green', 'adj. 绿色的；青春的 n. 绿色；青春 v. 使…变绿色', 5407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'greet', 'v. 欢迎，迎接；致敬，致意；映入眼帘 n. (Greet)人名；(英)格里特', 5408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'famine', 'n. 饥荒；饥饿，奇缺', 5409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hollow', 'adj. 空的；中空的，空腹的；凹的；虚伪的 n. 洞；山谷；窟窿 v. 使成为空洞 adv. 彻底地；无用地', 5410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'narrative', 'n. 叙述；故事；讲述 adj. 叙事的，叙述的；叙事体的', 5411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nylon', 'n. 尼龙，[纺] 聚酰胺纤维；尼龙袜', 5412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snap', 'v. 突然折断，拉断；猛咬；啪地关上 n. 猛咬；劈啪声；突然折断 adj. 突然的', 5413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'defect', 'n. 缺点，缺陷；不足之处 v. 变节；叛变', 5414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dragon', 'n. 龙；凶暴的人，凶恶的人；严厉而有警觉性的女人', 5415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acre', 'n. 土地，地产；英亩', 5416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'honest', 'adj. 诚实的，实在的；可靠的；坦率的', 5417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'postage', 'n. 邮资，邮费', 5418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revolt', 'v. 反抗；反叛；反感，厌恶 n. 反抗；叛乱；反感', 5419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preposition', 'n. 介词；前置词', 5420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flood', 'v. 淹没；充满；溢出 n. 洪水；泛滥；一大批', 5421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aircraft', 'n. 飞机，航空器', 5422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liver', 'n. 肝脏；生活者，居民', 5423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invade', 'v. 侵略；侵袭；侵扰；涌入', 5424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necklace', 'n. 项链', 5425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rabbit', 'n. 兔子，野兔 v. 让…见鬼去吧', 5426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commonwealth', 'n. 联邦；共和国；国民整体', 5427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'defeat', 'v. 击败，战胜；挫败；使…失败 n. 失败的事实；击败的行为', 5428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'giggle', 'v. 傻笑；咯咯地笑 n. 吃吃的笑', 5429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remnant', 'n. 剩余 adj. 剩余的', 5430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sparkle', 'n. 闪耀；火花；活力 v. 使闪耀；使发光', 5431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resolution', 'n. [物] 分辨率；决议；解决；决心', 5432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shove', 'v. 挤；强使；撞；猛推 n. 推；挤', 5433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reassure', 'v. 使…安心，使消除疑虑', 5434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seal', 'n. 密封；印章；海豹；封条；标志 v. 密封；盖章', 5435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seam', 'n. 缝；接缝 v. 缝合；接合；使留下伤痕', 5436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leaflet', 'n. 小叶；传单', 5437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocabulary', 'n. 词汇；词表；词汇量', 5438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'provision', 'n. 规定；条款；准备；[经] 供应品 v. 供给…食物及必需品', 5439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notwithstanding', 'adv. 尽管，仍然 prep. 尽管，虽然 conj. 虽然', 5440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motel', 'n. 汽车旅馆', 5441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convenient', 'adj. 方便的；[废语]适当的；[口语]近便的；实用的', 5442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wife', 'n. 妻子，已婚妇女；夫人', 5443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locality', 'n. 所在；位置；地点', 5444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'meditate', 'v. 考虑；计划；企图', 5445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blueprint', 'v. 计划；制成蓝图 n. 蓝图，设计图；计划', 5446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shout', 'v. 呼喊；喊叫；大声说 n. 呼喊；呼叫', 5447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dynasty', 'n. 王朝，朝代', 5448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horsepower', 'n. 马力（功率单位）', 5449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yellow', 'adj. 黄色的；黄皮肤的 n. 黄色；黄种人；黄色颜料 v. 使变黄或发黄', 5450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'garbage', 'n. 垃圾；废物', 5451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sunshine', 'n. 阳光；愉快；晴天；快活', 5452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fourteen', 'num. 十四；十四个；第十四 n. 十四的记号；十四岁；十四点钟；十五世纪', 5453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bureau', 'n. 局，处；衣柜；办公桌', 5454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certify', 'v. 证明；保证', 5455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'static', 'adj. 静态的；静电的；静力的 n. 静电；静电干扰', 5456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panda', 'n. 熊猫；猫熊', 5457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'log', 'v. 伐木 n. 记录；航行日志；原木', 5458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tangle', 'n. 纠纷；混乱状态 v. 使纠缠；处于混乱状态', 5459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnificent', 'adj. 高尚的；壮丽的；华丽的；宏伟的', 5460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marvelous', 'adj. 了不起的；非凡的；令人惊异的；不平常的', 5461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'swear', 'v. 发誓；咒骂 n. 宣誓；诅咒', 5462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blade', 'n. 叶片；刀片，刀锋；剑', 5463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnetic', 'adj. 地磁的；有磁性的；有吸引力的', 5464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sniff', 'v. 嗅；嗤之以鼻 n. 吸，闻；嗤之以鼻；气味；以鼻吸气；吸气声', 5465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sweat', 'v. 使出汗；流出；使干苦活；剥削；藉出汗减轻；焦急地期待 n. 汗；水珠；焦急；苦差使', 5466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ugly', 'adj. 丑陋的；邪恶的；令人厌恶的', 5467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graphic', 'adj. 形象的；图表的；绘画似的', 5468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'territory', 'n. 领土，领域；范围；地域；版图', 5469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drunk', 'v. 喝酒（drink的过去分词） adj. 喝醉了的', 5470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'captain', 'n. 队长，首领；船长；上尉；海军上校 v. 指挥；率领', 5471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vicinity', 'n. 邻近，附近；近处', 5472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'puppet', 'n. 木偶；傀儡；受他人操纵的人', 5473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offspring', 'n. 后代，子孙；产物', 5474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'landlord', 'n. 房东，老板；地主', 5475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stagger', 'v. 蹒跚；使交错；使犹豫 n. 蹒跚；交错安排 adj. 交错的；错开的', 5476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nineteen', 'num. 十九', 5477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seed', 'n. 种子；根据；精液；萌芽；子孙；原由 v. 播种；结实；成熟；去…籽', 5478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cosmic', 'adj. 宇宙的（等于cosmical）', 5479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plentiful', 'adj. 丰富的；许多的；丰饶的；众多的', 5480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comb', 'n. 梳子；蜂巢；鸡冠 v. 梳头发；梳毛', 5481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'singular', 'adj. 单数的；单一的；非凡的；异常的 n. 单数', 5482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handful', 'n. 少数；一把；棘手事', 5483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oxide', 'n. [化学] 氧化物', 5484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kindergarten', 'n. 幼儿园；幼稚园', 5485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'actress', 'n. 女演员', 5486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fisherman', 'n. 渔夫；渔人', 5487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adore', 'v. 崇拜；爱慕；喜爱；极喜欢 n. (Adore)人名；(法)阿多尔', 5488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turbine', 'n. [动力] 涡轮；[动力] 涡轮机', 5489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cop', 'v. 抓住 n. 巡警，警官', 5490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cow', 'n. 奶牛，母牛；母兽 v. 威胁，恐吓', 5491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'meantime', 'n. 其时，其间 adv. 同时；其间', 5492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frontier', 'n. 前沿；边界；国境 adj. 边界的；开拓的', 5493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cylinder', 'n. 圆筒；汽缸；[数] 柱面；圆柱状物', 5494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sweep', 'v. 扫除；猛拉；掸去 n. 打扫，扫除；范围；全胜', 5495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'december', 'n. 十二月', 5496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cosy', 'adj. 舒适的；惬意的 n. 保温罩', 5497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hound', 'v. 追猎；烦扰；激励 n. 猎犬；卑劣的人', 5498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hurricane', 'n. 飓风，暴风', 5499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corn', 'n. （美）玉米；（英）谷物；[皮肤] 鸡眼 v. 腌；使成颗粒', 5500);
