INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crisp', 'adj. 脆的,易碎的；（空气）清爽的', 1001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'democratic', 'adj. 民主的', 1002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'introduction', 'n. (to)介绍；传入,引进；导言,导论,绪论', 1003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'collective', 'n. 集体企业; 集体农庄 adj. 集体的,共同的', 1004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elevator', 'n. 电梯,升降机', 1005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'difficult', 'adj. 困难的,艰难的', 1006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dictation', 'n. 口述；听写', 1007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'name', 'n. 名字；名称；名声；名义 v. 给…取名', 1008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overtime', 'n. 超时工作，加班时间 adv. 加班', 1009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comparable', 'adj. 类似的，相当的；可相比的', 1010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'senator', 'n. 参议员', 1011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insult', 'v. 侮辱,凌辱 n. 侮辱,冒犯', 1012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intact', 'adj. 完整无缺的,未经触动的,未受损伤的', 1013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sufficient', 'adj. (for)足够的,充分的(比enough拘谨、正式)', 1014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creative', 'adj. 创造性的；有创造力的', 1015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'batch', 'n. 一批,一组,一群', 1016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consistent', 'adj. 一贯的，一致的', 1017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mirror', 'n. 镜子 v. 反映,反射', 1018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proof', 'n. 证据,证明；校样,样张', 1019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'domain', 'n. (活动,思想等)领域,范围；领地', 1020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invaluable', 'adj. 非常宝贵的,无价的', 1021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coincidence', 'n. 巧合；同时发生；符合，一致', 1022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sole', 'adj. 单独的,唯一的 n. 脚垫,鞋底；鞋底', 1023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'submerge', 'v. 沉没,淹没；潜入', 1024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illustrate', 'v. 举例说明,阐明；图解,加插图', 1025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'result', 'n. 结果；成绩，比分；〔选举的〕结果 v. 结果,致使,导致,由…而造成', 1026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gentle', 'adj. 和蔼的,文雅的,有礼貌的', 1027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'describe', 'v. 描述,形容', 1028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cargo', 'n. 船货,货物', 1029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commonwealth', 'n. 共和国,联邦,共同体', 1030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apologise', 'v. (to,for)道歉，认错', 1031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'debate', 'n. 争论,辩论 v. 讨论,辩论', 1032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agony', 'n. (精神或肉体的)极大痛苦，创伤', 1033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'celebrity', 'n. 名人，名流；著名，名声，名望', 1034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remarkable', 'adj. 值得注意的;显著的,异常的,非凡的', 1035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legitimate', 'adj. 合理的，合乎逻辑的；合法的 v. 使合法', 1036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grant', 'v. 同意,准予 n. 补助金，拨款', 1037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'collection', 'n. 收藏(品),收集(物)', 1038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avenue', 'n. 大街；林荫路；途径，渠道，方法', 1039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'respective', 'adj. 各自的,各个的', 1040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'controversy', 'n. 争论，辩论，争吵', 1041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'estimate', 'n. 估计；估价 v. 估计,估价', 1042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coordinate', 'v. 协作，协调', 1043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inspect', 'v. 检查,调查；视察,检阅', 1044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symptom', 'n. (疾病的)症状；(不好事情的)征兆,表征', 1045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appropriate', 'adj. 适当的 v. 挪用,盗用；拨给', 1046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'considerable', 'adj. 相当大(或多)的,可观的', 1047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delight', 'n. 快乐,高兴 v. (使)高兴,(使)欣喜', 1048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discriminate', 'v. 有差别地对待,歧视；区别,辨别', 1049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prepare', 'v. 筹备，（为…）做准备', 1050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'removal', 'n. 移动；除去', 1051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deficiency', 'n. 缺乏,不足；缺点,缺陷', 1052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assistance', 'n. 援助; 帮助', 1053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perpetual', 'adj. 永久的,永恒的,长期的', 1054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transport', 'v. 运输,运送,搬运 n. 运输系统,运载工具；运输,运送', 1055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deduce', 'v. (from)演绎,推断,推论', 1056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impossible', 'adj. 不可能的；难以忍受的，很难对付的', 1057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recur', 'v. (尤指不好的事)一再发生；重现', 1058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conform', 'v. (to)遵守；一致，符合', 1059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'description', 'n. 描写,形容', 1060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enclose', 'v. 包围; 装', 1061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'swallow', 'n. 燕子；吞咽 v. 吞,咽；咽口水；轻信', 1062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'porter', 'n. 守门人,门房；行李搬运工；服务员', 1063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'direction', 'n. 方向,方位；指令；说明', 1064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transaction', 'n. 交易,事务；办理,处理；(pl.)会报,学报', 1065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'atom', 'n. 原子', 1066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mere', 'adj. 仅仅,只不过', 1067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'signature', 'n. 签名,署名,签字', 1068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resident', 'n. 居民,常住者 adj. 居住的', 1069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'module', 'n. 单元；组件,模块,模件；(航天器的)舱', 1070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criterion', 'n. (pl.criteria或s)标准，尺度', 1071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specialize', 'v. (specialise)(in)专攻,专门研究,专业化', 1072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grace', 'n. 优美；文雅；恩惠,恩泽；感恩祷告', 1073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'especially', 'adv. 尤其；特别，格外；专门地，主要地', 1074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'similar', 'adj. (to)相似的,类似的', 1075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'difficulty', 'n. 困难；困境；难题', 1076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locomotive', 'n. 机车,火车头 adj. 运动的,移动的,运载的', 1077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curious', 'adj. 好奇的, 求知的；古怪的', 1078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'artist', 'n. 艺术家，美术家；(某方面的)能手', 1079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'log', 'n. 原木,圆木；航海日志', 1080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'principle', 'n. 原理,原则', 1081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shallow', 'adj. 浅的,浅薄的 n. 浅滩,浅处', 1082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'margin', 'n. 页边空白', 1083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moon', 'n. (加the)月球，月亮；卫星', 1084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cup', 'n. 杯子；奖杯，优胜杯；(一)杯，一杯的容量', 1085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'considerate', 'adj. 考虑周到的,体谅的', 1086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cart', 'n. (二轮货运)马车；手推车', 1087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opportunity', 'n. 机会', 1088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'successive', 'adj. 接连的,连续的', 1089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consolidate', 'v. 使加固，使加强；(把)联为一体，合并', 1090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'herb', 'n. 药草，(调味用的)香草，草本植物', 1091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'identify', 'v. 识别,鉴别', 1092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'officer', 'n. 官员,办事员;工作人员；军官', 1093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diversion', 'n. 转向,转移', 1094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basic', 'adj. 基本的,基础的', 1095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reduction', 'n. 减小,减少,缩小', 1096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apparatus', 'n. 器械，器具，仪器；机构，组织', 1097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diffuse', 'v. 扩散；传播 adj. (文章等)冗长的,漫无边际的', 1098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'midst', 'n. 中间,当中', 1099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comedy', 'n. 喜剧;喜剧性事件', 1100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grateful', 'adj. (to,for)感激的;感谢的', 1101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indignation', 'n. 愤怒,愤慨', 1102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sympathy', 'n. 同情，同情心；赞同', 1103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infinite', 'adj. 无限的,无穷的 n. 无限', 1104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lever', 'n. 杆,杠杆；手段,途径,工具', 1105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compete', 'v. 竞争；争夺，竞争', 1106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'active', 'adj. 活跃的，敏捷的；积极的；在活动中的', 1107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'caress', 'v. 爱抚，抚摸 n. 爱抚，抚摸', 1108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preposition', 'n. 介词', 1109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'technician', 'n. 技术员,技师,技工', 1110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equipment', 'n. 设备,器材,装置', 1111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prevalent', 'adj. 流行的,普遍的', 1112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'defect', 'n. 过失;缺点;不足', 1113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expensive', 'adj. 花费的,昂贵的', 1114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adventure', 'n. 冒险，冒险活动，奇遇 v. 大胆进行', 1115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'timely', 'adj. 及时的,适时的', 1116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ventilate', 'v. 使通风', 1117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'define', 'v. 确定，说明，界定；给…下定义，解释', 1118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'addict', 'n. 对…入迷的人', 1119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resistance', 'n. (to)抵抗,反抗;抵抗力,阻力;电阻', 1120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'senior', 'adj. 地位较高的；年长的 n. 〔中学或大学〕最高年级的学生，毕业班学生', 1121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'presently', 'adv. 一会儿,不久；现在,目前', 1122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illusion', 'n. 幻想，错误的观；错觉，幻觉，假象', 1123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gently', 'adv. 文雅地,有礼貌地;轻轻地', 1124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cry', 'v. 哭；叫，喊；(鸟兽)叫，啼，鸣，嗥 n. 叫，喊；哭；(鸟兽)叫，啼，鸣，嗥', 1125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remote', 'adj. 偏僻的；远的,遥远的；疏远的；渺茫的，微乎其微的', 1126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humid', 'adj. 湿的,湿气重的', 1127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extravagant', 'adj. 奢侈的', 1128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'repetition', 'n. 重复,反复', 1129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emerge', 'v. 显现,浮现；暴露', 1130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lecture', 'n. 演讲,讲课 v. 讲授，讲课，作讲座；演讲', 1131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advocate', 'n. 辩护者，拥护者，鼓吹者 v. 拥护，提倡', 1132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proceeding', 'n. 行动,进行；(pl.)会议录,学报', 1133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'object', 'n. 物体;客体,对象;目标;宾语 v. (to)反对', 1134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solar', 'adj. 太阳的,日光的', 1135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inside', 'adj. 里面的 adv&prep. 在里面 n. 内部', 1136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'introduce', 'v. 介绍；引进；提出(议案等)', 1137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revolutionary', 'adj. 革命的；革新的 n. 革命者', 1138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sportsman', 'n. 运动员；爱好运动的人', 1139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'volume', 'n. 音量；容积,体积；卷,册', 1140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rectify', 'v. 纠正,整顿', 1141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reproduce', 'v. 生殖，繁殖；复制；翻印', 1142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panorama', 'n. 全景；全景画', 1143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immune', 'adj. 免疫的,有免疫力的；不受影响的；豁免的', 1144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'march', 'v. (使)行军,(使)行进 n. 行军,行程', 1145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elegant', 'adj. 优雅的;端庄的;雅致的', 1146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'location', 'n. 地点,位置；定位,测位', 1147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cemetery', 'n. 坟墓，墓地，坟场', 1148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'submarine', 'n. 潜水艇 adj. 水底的,海底的', 1149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prior', 'adj. 先前的；优先的；(to)在…之前', 1150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convention', 'n. 大会,会议；公约,协定；惯例,常规', 1151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memorial', 'adj. 记忆的,纪念的 n. 纪念物,纪念碑,纪念馆', 1152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocabulary', 'n. 词汇,词汇量', 1153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'document', 'n. 公文,文献', 1154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'desperate', 'adj. 不顾一切的，绝望的；危急的', 1155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'speculate', 'v. 思索；推测；投机', 1156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expectation', 'n. 预期；期望,指望', 1157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layman', 'n. 外行', 1158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'count', 'v. 数,计算；算入；看作,认为 n. 计数,总数', 1159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suicide', 'n. 自杀', 1160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preside', 'v. (at,over)主持', 1161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monarch', 'n. 帝王，君主，最高统治者', 1162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elect', 'v. 选举,推选；选择,作出选择', 1163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'below', 'adv&prep. 在…下面，在…以下', 1164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consequence', 'n. 结果,后果,影响', 1165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bargain', 'n. 廉价货；交易,契约,合同 v. 议价', 1166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'partner', 'n. 配偶；合作者,合伙人,合股人；舞伴；伙伴', 1167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'visa', 'n. (护照等的)签证 v. 签证', 1168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'importance', 'n. 重要,重要性', 1169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excess', 'adj. 过量的,额外的 n. 过多，过量', 1170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enlighten', 'v. 启发,启蒙,教导', 1171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'actress', 'n. 女演员', 1172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dilemma', 'n. 困境；进退两难；', 1173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fin', 'n. 鱼鳍；鳍状物；尾翅', 1174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'island', 'n. 岛，岛屿', 1175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sanction', 'v. 批准,同意,支持,认可 n. 批准,同意,支持,认可；制裁；处罚', 1176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lightning', 'n. 闪电 adj. 闪电般的,快速的', 1177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carpenter', 'n. 木工,木匠', 1178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paradox', 'n. 悖论，似非而是的说法；自相矛盾（的情况）', 1179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pillow', 'n. 枕头', 1180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capital', 'n. 首都；资本；大写字母 adj. 主要的,大写字母的', 1181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infectious', 'adj. 传染的,传染性的；有感染力的', 1182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profit', 'n. 利润,收益 v. (by,from)得利,获益；有利于', 1183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'script', 'n. 剧本(原稿),手稿，原稿；笔迹，手迹', 1184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confusion', 'n. 困惑，糊涂；混淆；混乱，骚乱', 1185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sociology', 'n. 社会学', 1186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recipe', 'n. 烹饪法,食谱；诀窍,方法', 1187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cupboard', 'n. 碗柜,小橱', 1188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advice', 'n. 劝告，忠告，(医生等的)意见', 1189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seaside', 'n. 海滨,海边', 1190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'palace', 'n. 宫,宫殿', 1191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspicious', 'adj. 多疑的,疑心的；可疑的', 1192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'human', 'adj. 人的,人类的 n. 人', 1193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gender', 'n. (生理上的)性；(名词、代词等的)性', 1194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ornament', 'v. 装饰,美化 n. 装饰,装饰物', 1195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spectacle', 'n. 奇观,壮观；(pl.)眼镜', 1196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'principal', 'adj. 最重要的,主要的 n. 校长；负责人；资本,本金', 1197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'companion', 'n. 同伴,共事者,伴侣', 1198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attempt', 'v. 企图，试图 n. 努力，尝试，企图', 1199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metre', 'n. (meter)米，公尺；仪表，计量器', 1200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decide', 'v. 决定,下决心；解决,裁决', 1201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'promote', 'v. 促进,发扬；提升,提拔', 1202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genetic', 'adj. 遗传(学)的 n. [-s]遗传学', 1203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'private', 'adj. 私人的,个人的；秘密的,私下的', 1204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resist', 'v. 忍得住；抗拒，对抗；反抗，抵御', 1205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'depart', 'v. 离开,起程 adj. 过去的,逝世的', 1206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'platform', 'n. 站台,月台；平台,台；政纲,党纲', 1207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absence', 'n. 缺席，不在；缺乏，不存在', 1208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'temper', 'n. 脾气 v. 调和，使缓和；使回火', 1209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irrespective', 'adj. 不顾的,不考虑的,无关的', 1210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'second', 'adj. 第二；次等的,二等的 n. 秒 v. 赞成,附和', 1211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convenient', 'adj. (to)便利的,方便的', 1212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petition', 'n. 请愿书,申请书 v. (向…)请愿,正式请求', 1213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prime', 'adj. 首要的；最好的,第一流的 n. 青春,全盛期', 1214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Monday', 'n. 星期一', 1215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equator', 'n. 赤道', 1216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'visitor', 'n. 访问者,客人,来宾,参观者', 1217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'competitive', 'adj. 有竞争力的；竞争的，竞争性的', 1218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aspect', 'n. (问题等的)方面；样子, 外表, 面貌', 1219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revive', 'v. 复兴；恢复；（使）复苏', 1220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grammar', 'n. 语法；语法书', 1221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pan', 'n. 平底锅', 1222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'husband', 'n. 丈夫', 1223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curb', 'n. 路边；控制，约束 v. 制止，抑制', 1224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harmony', 'n. 融洽；协调,和谐', 1225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invasion', 'n. 入侵,侵略,侵犯', 1226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vacation', 'n. 休假,假期', 1227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consensus', 'n. (意见等的)一致，一致同意，共识', 1228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'priest', 'n. 神父；教士', 1229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'executive', 'n. 总经理,董事,行政负责人 adj. 执行的,实施的', 1230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vision', 'n. 视力,视觉;远见;洞察力;幻想,幻影;想象力', 1231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resent', 'v. 对…表示忿恨,怨恨', 1232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locality', 'n. 地区', 1233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'call', 'v. 叫，喊；打电话；把…叫作；叫，喊 n. 叫声；号召', 1234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'provided', 'conj. 倘若,只要,假如', 1235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concession', 'n. 让步，妥协；特许(权)', 1236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnace', 'n. 炉子,熔炉', 1237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subordinate', 'adj. (to)次要的,从属的；下级的', 1238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remove', 'v. 移动；脱掉；免职', 1239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'participant', 'n. 参加者,参与者 adj. 有份的,参与的', 1240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refuse', 'v. 拒绝,谢绝 n. 废物,垃圾', 1241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abstract', 'adj. 抽象的 n. 摘要，梗概 v. 提取,摘录要点', 1242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'following', 'adj. 其次的，接着的；下列的，下述的', 1243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monument', 'n. 纪念碑,纪念馆；遗迹', 1244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illuminate', 'v. 照亮，照明；说明，阐释', 1245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sense', 'n. 感官；感觉；理解力；判断力；意义 v. 觉得,意识到', 1246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intelligent', 'adj. 聪明的,明智的', 1247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'increase', 'v. 增加,增长,增进 n. 增加,增长,增进', 1248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'catch', 'v. 捕捉,捕获；赶上；感染；听到', 1249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dominant', 'adj. 支配的,统治的,占优势的', 1250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proposal', 'n. 提议,建议；求婚', 1251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'category', 'n. 种类，部属，类目,范畴，类型', 1252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concede', 'v. 承认；(比赛结束前)认输,退让', 1253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statesman', 'n. 政治家,国务活动家', 1254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resolve', 'v. 决心；(使)分解,溶解；决议 n. 决心', 1255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marry', 'v. 结婚,嫁,娶', 1256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cater', 'v. (for)提供饮食及服务；(for/to)满足,迎合', 1257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precious', 'adj. 珍贵的；贵重的', 1258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curriculum', 'n. 课程,(学校等的)全部课程', 1259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summer', 'n. 夏天，夏季 adj. 夏季的', 1260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'celebrate', 'v. 庆祝；颂扬，赞美', 1261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fireman', 'n. 消防队员', 1262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recognize', 'v. (recognise)认出；承认；赏识,表扬', 1263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recovery', 'n. 痊愈,复元；重获,恢复', 1264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recognition', 'n. 认出,辨认；承认', 1265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'congratulate', 'v. (on)祝贺,向…致贺词', 1266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'devise', 'v. 设计;发明;图谋;作出(计划);想出(办法)', 1267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evacuate', 'v. 撤离，疏散；排泄', 1268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dialog', 'n. (dialogue)对话,对白', 1269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'banquet', 'n. (正式的)宴会 v. 参加宴会，宴请', 1270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'move', 'v. 移动；迁移；感动 n. 行动；移动,活动', 1271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contradict', 'v. 反驳；同…矛盾,同…抵触', 1272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corporation', 'n. 公司，企业；法人', 1273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prisoner', 'n. 囚犯', 1274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accommodation', 'n. 住宿，膳宿供应', 1275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embassy', 'n. 大使馆;大使及其随员', 1276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'respect', 'n. 尊敬,尊重；敬意,问候 v. 尊敬,尊重', 1277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fragile', 'adj. 易碎的，脆的，易损坏的', 1278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deficit', 'n. 赤字,逆差;亏损,亏空;不足,缺乏', 1279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grandmother', 'n. 祖母,外祖母', 1280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compensate', 'v. (for)补偿；赔偿', 1281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paralyze', 'v. (paralyse)使瘫痪(麻痹)；使不能正常运作，使陷入瘫痪', 1282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evaluate', 'v. 估价,评价', 1283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excessive', 'adj. 过多的;过分的', 1284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orderly', 'adj. 整齐的,有条理的；有秩序的 n. 勤务兵', 1285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salesman', 'n. 售货员,推销员', 1286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curiosity', 'n. 好奇心；古董,古玩', 1287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discipline', 'n. 纪律；学科', 1288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equal', 'adj. 相等的；胜任的 n. 同等的人 v. 等于', 1289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soldier', 'n. 士兵,军人', 1290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barely', 'adv. 勉强才能；几乎不', 1291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'final', 'adj. 最终的；决定性的 n. 决赛；期末考试', 1292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confine', 'v. 限制；使不外出，禁闭 n. [pl.]界限，范围', 1293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creature', 'n. 动物;生物', 1294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'communism', 'n. 共产主义', 1295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deceive', 'v. 欺骗,蒙蔽', 1296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'characterize', 'v. 描述…特性', 1297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basis', 'n. 基础,根据', 1298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'species', 'n. (物)种,种类', 1299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'part', 'n. 部分,角色,一方,零件,地区,部,篇 v. 使分开', 1300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summarize', 'v. (summarise)概括,总结', 1301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'signal', 'n. 信号,暗号 v. 发信号,用信号通知', 1302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circulate', 'v. (使)循环,(使)流通', 1303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'religious', 'adj. 宗教的；信教的,虔诚的', 1304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'massacre', 'v. 残杀,集体屠杀 n. 残杀,大屠杀', 1305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decrease', 'n. 减少,减小;减少量 v. 减少,变少,降低', 1306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'countryside', 'n. 乡下,农村', 1307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'improvement', 'n. 改进,进步,增进', 1308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precision', 'n. 精确,精确度', 1309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suppose', 'v. 料想,猜想;假定', 1310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accident', 'n. 意外遭遇,事故', 1311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comprise', 'v. 包含，包括，由...组成；构成，组成', 1312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'penny', 'n. 便士', 1313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compare', 'v. 比较；与…相比', 1314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'character', 'n. 性格,品质,特性；人物,角色;；字符,(汉)字', 1315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genius', 'n. 天才', 1316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dedicate', 'v. 奉献;献身于', 1317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expose', 'v. (to)使暴露,受到；揭露，揭发', 1318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formal', 'adj. 官方的；正式的', 1319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'same', 'adj. 相同的 pron. 同样 adv. 同样地', 1320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inevitable', 'adj. 不可避免的,必然发生的', 1321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspect', 'v. 猜想；怀疑 adj. 可疑的 n. 嫌疑犯', 1322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capitalism', 'n. 资本主义', 1323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perform', 'v. 表演,演出；履行,执行', 1324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medieval', 'adj. 中世纪的,中古(时代)的；老式的,原始的', 1325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cartoon', 'n. 动画片；漫画,幽默画', 1326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limited', 'adj. 有限的,被限制的', 1327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possible', 'adj. 可能的,做得到的；合理的', 1328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extract', 'v. 拔出,抽出；摘录 n. 节录；选段；抽取物', 1329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'container', 'n. 容器；集装箱', 1330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'menace', 'n. 有危险性的人(或物)；威胁，威吓 v. 威胁，威吓', 1331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adhere', 'v. (to)粘着；坚持，遵守', 1332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'besides', 'adv. 此外；并且 prep. 于…之外；除…以外', 1333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analogue', 'n. 类似物；相似体；模拟', 1334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversation', 'n. 会话,谈话', 1335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pride', 'n. 自豪（感），骄傲 v. 使自豪', 1336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'significant', 'adj. 重要的，重大的，影响深远的', 1337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reciprocal', 'adj. 相互的,往复的,互利的', 1338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'to', 'prep. (表示方向)到；向；(表示间接关系)给', 1339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perfection', 'n. 尽善尽美,完美', 1340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possession', 'n. 持有,拥有；所有物；财产,财物', 1341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paragraph', 'n. 段落；短评；段落符号 v. 将…分段', 1342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'influence', 'n. 影响；势力；感化；有影响的人或事 v. 影响；改变', 1343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intellectual', 'adj. 智力的；聪明的；理智的 n. 知识分子；凭理智做事者', 1344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'political', 'adj. 政治的；党派的', 1345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'science', 'n. 科学；技术；学科；理科', 1346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'economic', 'adj. 经济的，经济上的；经济学的', 1347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'century', 'n. 世纪，百年；（板球）一百分', 1348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'increase', 'n. 增加，增长；提高 v. 增加，增大；繁殖', 1349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stress', 'n. 压力；强调；紧张；重要性；重读 v. 强调；使紧张；加压力于；用重音读', 1350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'power', 'n. 力量，能力；电力，功率；政权，势力；[数] 幂 v. 激励；供以动力；使…有力量 adj. 借影响有权势人物以操纵权力的', 1351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'national', 'adj. 国家的；国民的；民族的；国立的 n. 国民', 1352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consider', 'v. 考虑；认为；考虑到；细想', 1353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'process', 'v. 处理；加工 n. 过程，进行；方法，步骤；作用；程序；推移 adj. 经过特殊加工（或处理）的', 1354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'create', 'v. 创造，创作；造成', 1355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drug', 'n. 药；毒品；麻醉药；滞销货 v. 使服麻醉药；使服毒品；掺麻醉药于', 1356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'care', 'n. 关怀；照料；谨慎；忧虑 v. 照顾；关心；喜爱；顾虑', 1357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'group', 'n. 组；团体 adj. 群的；团体的 v. 聚合', 1358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discovery', 'n. 发现，发觉；被发现的事物', 1359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'include', 'v. 包含，包括', 1360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'price', 'n. 价格；价值；代价 v. 给……定价；问……的价格', 1361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sector', 'n. 部门；扇形，扇区；象限仪；函数尺 vt. 把…分成扇形', 1362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'service', 'n. 服务，服侍；服役；仪式 adj. 服务性的；耐用的；服现役的 v. 维修，检修；保养', 1363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'search', 'v. 搜寻；调查；探求 n. 搜寻；探究，查究', 1364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'experience', 'n. 经验；经历；体验 v. 经验；经历；体验', 1365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'require', 'v. 需要；要求；命令', 1366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'individual', 'adj. 个人的；个别的；独特的 n. 个人，个体', 1367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scientific', 'adj. 科学的，系统的', 1368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attention', 'n. 注意力；关心；立正！（口令）', 1369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'influential', 'adj. 有影响的；有势力的 n. 有影响力的人物', 1370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'court', 'n. 法院；球场；朝廷；奉承 v. 招致（失败、危险等）；向…献殷勤；设法获得', 1371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'law', 'n. 法律；规律；法治；法学；诉讼；司法界 vi. 起诉；控告 vt. 控告；对…起诉', 1372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'federal', 'adj. 联邦的；同盟的；联邦政府的； 联邦制的 adv. 联邦政府地 n. (Federal)人名；(英)费德勒尔', 1373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'past', 'n. 过去；往事 adj. 过去的；结束的 prep. 越过；晚于 adv. 过；经过', 1374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deal', 'v. 处理；给予；分配；发牌 n. 交易；（美）政策；待遇；份量', 1375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rise', 'v. 上升；增强；起立；高耸 n. 上升；高地；增加；出现', 1376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limit', 'n. 限制；限度；界线 v. 限制；限定', 1377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peer', 'n. 贵族；同等的人；同龄人 v. 凝视，盯着看；窥视', 1378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scientist', 'n. 科学家', 1379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'financial', 'adj. 金融的；财政的，财务的', 1380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'report', 'n. 报告；报道；成绩单 v. 报告；报导；使报到', 1381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'issue', 'n. 问题；流出；期号；发行物 v. 发行，发布；发给；放出，排出', 1382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'risk', 'n. 风险；危险；冒险 v. 冒…的危险', 1383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'method', 'n. 方法；条理；类函数 adj. 使用体验派表演方法的', 1384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'publish', 'v. 出版；发表；公布', 1385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'practice', 'n. 实践；练习；惯例 v. 练习；实习；实行', 1386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'future', 'n. 未来；前途；期货；将来时 adj. 将来的，未来的', 1387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'function', 'n. 功能；[数] 函数；职责；盛大的集会 v. 运行；活动；行使职责', 1388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evidence', 'n. 证据，证明；迹象；明显 v. 证明', 1389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pressure', 'n. 压力；压迫，[物] 压强 v. 迫使；密封；使……增压', 1390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turn', 'v. 转动，使旋转；转弯；翻过来；兑换 n. 转弯；变化；(损害或有益于别人的)行为，举动，举止', 1391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'argue', 'v. 争论，辩论；提出理由 n. (Argue)人名；(英、法)阿格', 1392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'support', 'v. 支持，支撑，支援；扶持，帮助；赡养，供养 n. 支持，维持；支援，供养；支持者，支撑物', 1393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offer', 'v. 提供；出价；试图 n. 提议；出价；意图；录取通知书', 1394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'understand', 'v. 理解；懂；获悉；推断；省略', 1395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'history', 'n. 历史，历史学；历史记录；来历', 1396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bring', 'v. 带来；促使；引起；使某人处于某种情况或境地 n. (Bring)人名；(英、瑞典)布林', 1397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knowledge', 'n. 知识，学问；知道，认识；学科', 1398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medical', 'adj. 医学的；药的；内科的 n. 医生；体格检查', 1399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rate', 'n. 比率，率；速度；价格；等级 v. 认为；估价；责骂', 1400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continue', 'v. 继续，延续；仍旧，连续', 1401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monkey', 'n. 猴子；顽童 v. 胡闹；捣蛋', 1402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'student', 'n. 学生；学者', 1403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'smell', 'v. 嗅，闻；有…气味 n. 气味，嗅觉；臭味', 1404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'single', 'adj. 单一的；单身的；单程的 n. 一个；单打；单程票 v. 选出', 1405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'average', 'n. 平均；平均数；海损 adj. 平均的；普通的；通常的 v. 算出…的平均数；将…平均分配；使…平衡', 1406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loss', 'n. 减少；亏损；失败；遗失', 1407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legal', 'adj. 法律的；合法的；法定的；依照法律的 n. (Legal)人名；(法)勒加尔', 1408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'effect', 'n. 影响；效果；作用 v. 产生；达到目的', 1409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feeling', 'n. 感觉，触觉；感情，情绪；同情 adj. 有感觉的；有同情心的；富于感情的 v. 感觉；认为（feel的现在分词）；触摸', 1410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gamble', 'v. 赌博；孤注一掷；投机；打赌 n. 赌博；冒险；打赌', 1411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'writing', 'n. 书写；作品；著作；[法] 笔迹 v. 书写（write的ing形式）', 1412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'share', 'v. 分享，分担；分配 n. 份额；股份', 1413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'earn', 'v. 赚，赚得；获得，挣得；使得到；博得 n. (Earn)人名；(泰)炎', 1414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'message', 'n. 消息；差使；启示；预言；广告词 v. 报信，报告；[通信] 报文', 1415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'standard', 'n. 标准；水准；旗；度量衡标准 adj. 标准的；合规格的；公认为优秀的', 1416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quit', 'v. 离开；放弃；停止；使…解除 n. 离开；[计] 退出 adj. 摆脱了…的；已经了结的', 1417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'railroad', 'v. 由铁道运输；铺设铁路；以捏造不实之罪使入狱 n. 铁路；铁路公司', 1418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certain', 'adj. 某一；必然的；确信；无疑的；有把握的 pron. 某些；某几个 n. (Certain)人名；(葡)塞尔塔因；(法)塞尔坦', 1419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decision', 'n. 决定，决心；决议', 1420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'performance', 'n. 性能；绩效；表演；执行；表现', 1421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concept', 'n. 观念，概念', 1422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'class', 'n. 阶级；班级；种类；班；等级 v. 分类；把…分等级；把…归入某等级，把…看作（或分类、归类）；把…编入某一班级 adj. 极好的；很好的，优秀的，出色的', 1423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'difference', 'n. 差异；不同；争执', 1424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genetic', 'adj. 遗传的；基因的；起源的', 1425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'journal', 'n. 日报，杂志；日记；分类账', 1426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slave', 'n. 奴隶；从动装置 v. 苦干；拼命工作', 1427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brain', 'n. 头脑，智力；脑袋 v. 猛击…的头部', 1428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'response', 'n. 响应；反应；回答', 1429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'potential', 'n. 潜能；可能性；[电] 电势 adj. 潜在的；可能的；势的', 1430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'site', 'n. 地点；位置；场所 v. 设置；为…选址', 1431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'produce', 'v. 生产；引起；创作；生育，繁殖 n. 农产品，产品', 1432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spread', 'v. 传播；伸展 n. 传播；伸展 adj. 伸展的', 1433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attitude', 'n. 态度；看法；意见；姿势', 1434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'living', 'adj. 活的；现存的；活跃的；逼真的 n. 生活；生存；生计 v. 生活；居住（live的ing形式）；度过', 1435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'union', 'n. 联盟，协会；工会；联合', 1436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'born', 'v. 出世（bear的过去分词） adj. 天生的 n. (Born)人名；(柬)邦；(英、西、俄、捷、德、瑞典、匈)博恩', 1437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'define', 'v. 定义；使明确；规定 n. (Define)人名；(英)德法恩；(葡)德菲内', 1438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'critic', 'n. 批评家，评论家；爱挑剔的人', 1439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'institution', 'n. 制度；建立；（社会或宗教等）公共机构；习俗', 1440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'experiment', 'v. 尝试；进行实验 n. 实验，试验；尝试', 1441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adult', 'adj. 成年的；成熟的 n. 成年人', 1442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'review', 'n. 回顾；复习；评论；检讨；检阅 v. 回顾；检查；复审', 1443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generation', 'n. 一代；产生；一代人；生殖', 1444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quality', 'n. 质量，[统计] 品质；特性；才能 adj. 优质的；高品质的；<英俚>棒极了', 1445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criticism', 'n. 批评；考证；苛求', 1446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remain', 'v. 保持；依然；留下；剩余；逗留；残存 n. 遗迹；剩余物，残骸', 1447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'product', 'n. 产品；结果；[数] 乘积；作品', 1448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nation', 'n. 国家；民族；国民', 1449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infer', 'v. 推断；推论', 1450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'community', 'n. 社区；[生态] 群落；共同体；团体', 1451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'happy', 'adj. 幸福的；高兴的；巧妙的 n. (Happy)人名；(英、瑞典、喀)哈皮', 1452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cover', 'v. 包括；采访，报导；涉及 n. 封面，封皮；盖子；掩蔽物;幌子，借口', 1453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'publication', 'n. 出版；出版物；发表', 1454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'segment', 'v. 分割 n. 段；部分', 1455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seek', 'v. 寻求；寻找；探索；搜索', 1456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'condition', 'n. 条件；情况；环境；身份 v. 决定；使适应；使健康；以…为条件', 1457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'internet', 'n. 因特网', 1458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'success', 'n. 成功，成就；胜利；大获成功的人或事物', 1459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fund', 'n. 基金；资金；存款 v. 投资；资助', 1460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'structure', 'n. 结构；构造；建筑物 v. 组织；构成；建造', 1461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sense', 'n. 感觉，功能；观念；道理；理智 v. 感觉到；检测', 1462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'newspaper', 'n. 报纸', 1463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'customer', 'n. 顾客；家伙', 1464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'learned', 'adj. 博学的；有学问的；学术上的 n. (Learned)人名；(英)勒尼德', 1465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'board', 'n. 董事会；木板；甲板；膳食 v. 上（飞机、车、船等）；用板盖上；给提供膳宿', 1466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'president', 'n. 总统；董事长；校长；主席', 1467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remove', 'v. 移动，迁移；开除；调动 n. 移动；距离；搬家', 1468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'series', 'n. 系列，连续；[电] 串联；级数；丛书', 1469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'record', 'v. 记录，记载；标明；将录音 n. 档案，履历；唱片；最高纪录 adj. 创纪录的', 1470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moral', 'adj. 道德的；精神上的；品性端正的 n. 道德；寓意', 1471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'production', 'n. 成果；产品；生产；作品', 1472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'population', 'n. 人口；[生物] 种群，[生物] 群体；全体居民', 1473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underline', 'v. 强调；在…下面划线；预告 n. 下划线；下期节目预告', 1474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humanity', 'n. 人类；人道；仁慈；人文学科', 1475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'position', 'n. 位置，方位；职位，工作；姿态；站位 v. 安置；把……放在适当位置', 1476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'particular', 'adj. 特别的；详细的；独有的；挑剔的 n. 详细说明；个别项目', 1477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immigrant', 'adj. 移民的；迁入的 n. 移民，侨民', 1478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opportunity', 'n. 时机，机会', 1479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'access', 'v. 使用；存取；接近 n. 进入；使用权；通路', 1480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'observe', 'v. 庆祝', 1481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stay', 'v. 停留；坚持；暂住；停下 n. 逗留；停止；支柱', 1482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commercial', 'adj. 商业的；营利的；靠广告收入的 n. 商业广告', 1483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reveal', 'v. 显示；透露；揭露；泄露 n. 揭露；暴露；门侧，窗侧', 1484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'effort', 'n. 努力；成就', 1485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reduce', 'v. 减少；降低；使处于；把…分解', 1486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'term', 'n. 术语；学期；期限；条款；(代数式等的)项 v. 把…叫做', 1487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'action', 'n. 行动；活动；功能；战斗；情节', 1488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decade', 'n. 十年，十年期；十', 1489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'productivity', 'n. 生产力；生产率；生产能力', 1490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sentence', 'n. [语][计] 句子，命题；宣判，判决 v. 判决，宣判', 1491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'celebrity', 'n. 名人；名声', 1492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'teacher', 'n. 教师；导师', 1493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concern', 'v. 涉及，关系到；使担心 n. 关系；关心；关心的事；忧虑', 1494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'score', 'n. 分数；二十；配乐；刻痕 v. 获得；评价；划线，刻划；把…记下', 1495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'variety', 'n. 多样；种类；杂耍；变化，多样化', 1496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unique', 'adj. 独特的，稀罕的；[数] 唯一的，独一无二的 n. 独一无二的人或物', 1497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'depend', 'v. 依赖，依靠；取决于；相信，信赖', 1498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nuclear', 'adj. 原子能的；[细胞] 细胞核的；中心的；原子核的', 1499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'involve', 'v. 包含；牵涉；使陷于；潜心于', 1500);
