INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obituary', 'n.  讣闻， 讣告', 10501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bureau', 'n.  局， 署； 办公室； 机构', 10502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moist', 'adj.  潮湿的； 多雨的', 10503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cable', 'v.  给…发电报， 用电报传送 n. 缆绳，钢索；电缆；电报', 10504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intense', 'adj.  强烈的； 热切的； 激烈的', 10505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thrifty', 'adj.  节省的， 节俭的', 10506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yelp', 'v. 尖叫 n.  短而尖的叫声', 10507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'estate', 'n.  地产； 庄园； 个人财产， 遗产', 10508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acoustic', 'adj.  非电声乐器的， 原声的； 听觉的， 声音的', 10509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'articulate', 'adj.  善于表达的； 发音清晰的， 口齿清楚的 v.  明确表达， 清楚说明； 清晰地吐， 清晰地发； 用关节连接', 10510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brass', 'n.  铜管乐器； 黄铜', 10511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dignify', 'vt.  使有尊严， 使高贵； 美化', 10512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bluster', 'v.  虚张声势地恫吓； 猛刮', 10513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'traverse', 'v.  横穿， 横渡', 10514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impending', 'adj.  即将发生的， 迫近的', 10515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigorous', 'adj.  缜密的， 谨慎的； 严格的， 严厉的', 10516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amino', 'adj.  氨基的', 10517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secular', 'adj.  现世的； 世俗的； 非宗教的', 10518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'activate', 'vt.  刺激， 使活动', 10519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strenuous', 'adj.  费劲的， 费力的， 艰苦的； 精力充沛的； 奋力的', 10520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lethargy', 'n.  死气沉沉； 无精打采， 倦怠', 10521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amusement', 'n.  可笑； 娱乐， 消遣', 10522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boundary', 'n.  分界线； 边界', 10523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shame', 'n. 羞耻，羞愧，耻辱；可耻的人 vt.  使羞愧； 玷辱', 10524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endow', 'vt.  使天生具有， 赋予； 资助， 捐赠', 10525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precipitate', 'v. 使…突然降临；加速；降水；使突然陷入； adj.  仓促的， 鲁莽的', 10526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'centric', 'adj.  以…为中心的', 10527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mandate', 'v.  强制执行； 授权 n. 授权；委托书，授权令；任期', 10528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slog', 'v.  艰难行进； 埋头苦干； 猛击', 10529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'financial', 'adj.  财政的， 财务的， 金融的', 10530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respective', 'adj.  分别的， 各自的', 10531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inactivate', 'vt.  使不活动， 使不活跃', 10532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'media', 'n.  媒介， 媒体', 10533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plaudit', 'n. 喝彩；赞美', 10534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exalt', 'vt.  高度赞扬， 褒扬； 提升， 提拔', 10535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reversible', 'adj.  可逆的， 可翻转的； 正反两用的； 可恢复原状的', 10536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'define', 'vt.  定义， 解释； 限定', 10537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dictate', 'v. 规定；决定；口述；支配 n.  命令， 规定', 10538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flick', 'v. 轻拍；移动 n.  轻拍； 浏览', 10539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'memorize', 'vt.  记住， 记忆， 熟记', 10540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'render', 'vt.  给予， 提供； 致使； 递交， 呈献； 表达； 翻译', 10541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haven', 'n.  港口； 庇护所， 避难所； 栖息处', 10542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neon', 'n.  氖； 霓虹灯', 10543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manifest', 'adj.  明显的 vt. 表明，显示 n. 货物清单', 10544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relieve', 'vt.  缓解， 减轻； 使轻松， 使宽慰； 调剂； 接替， 换班', 10545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buffalo', 'n.  水牛； 野牛', 10546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endeavor', 'vi&n.  努力， 尽力', 10547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quartz', 'n.  石英', 10548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prelude', 'n.  前奏曲， 序幕', 10549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adjacent', 'adj.  邻近的， 毗连的', 10550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transport', 'n.  运输； 运输系统， 运载工具 vt.  运输； 传播', 10551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grump', 'vi. 发脾气，发牢骚 n.  脾气不好的人', 10552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specific', 'adj.  明确的， 具体的； 特定的， 特有的', 10553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sprain', 'n&vt.  扭伤', 10554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prioritize', 'v.  划分优先顺序； 优先处理', 10555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engage', 'v.  从事于， 忙于； 吸引； 订婚； 聘用', 10556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adroit', 'adj.  精明的， 干练的； 熟练的， 灵巧的', 10557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appetite', 'n.  胃口， 食欲； 欲望', 10558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frivolity', 'n.  轻浮； 愚蠢的行为', 10559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strategy', 'n.  战略， 策略', 10560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remainder', 'n.  剩余物， 残余； 其他的人； 差数， 余数', 10561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clumsy', 'adj.  笨拙的； 不得体的， 冒犯人的； 复杂难懂的， 难处理的', 10562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'territory', 'n.  领土， 版图； 领域， 地盘', 10563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'summon', 'v.  传唤， 传讯； 召集， 召开； 鼓起， 振作', 10564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grovel', 'vi.  摇尾乞怜， 奴颜婢膝', 10565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maintain', 'vt.  维持， 保持； 维修， 保养； 主张， 坚持； 赡养， 负担', 10566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shift', 'v. 转移；改变 n.  转移； 改变； 轮班', 10567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implore', 'v.  哀求， 恳求', 10568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rehabilitate', 'vt.  使恢复原状， 修复； 改造， 使恢复正常生活； 恢复…的名誉', 10569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expertise', 'n.  专门知识， 专长', 10570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bargain', 'vi.  讨价还价 n. 特价商品，廉价货；协议；交易', 10571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elective', 'adj.  选举的； 可选择的； 选修的', 10572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pivot', 'v.  在枢轴上旋转 n. 枢轴；中心点；核心', 10573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissuade', 'vt.  劝阻， 阻止', 10574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sneaker', 'n.  鬼鬼祟祟的人， 卑鄙者； 运动鞋', 10575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conclusive', 'adj.  确定的， 确凿的， 不容置疑的； 结论性的', 10576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encompass', 'vt.  包含； 环绕', 10577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sustenance', 'n.  食物； 生计； 维持', 10578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allergy', 'n.  过敏性反应', 10579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disinterested', 'adj.  客观的， 无私的， 公正的； 无兴趣的， 不关心的', 10580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'envelope', 'n.  信封', 10581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deposit', 'v. 沉淀；堆积；储蓄；', 10582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissipate', 'v.  消散， 消失； 挥霍， 浪费', 10583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recount', 'v.  讲述， 描述； 重新清点， 重计', 10584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flask', 'n.  细颈瓶； 烧瓶', 10585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluctuation', 'n.  波动， 起伏', 10586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pliable', 'adj.  易弯曲的， 柔韧的； 易受影响的； 顺从的', 10587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flash', 'vi.  闪光； 反射 n. 闪光；闪现', 10588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continent', 'n.  大陆， 陆地； 洲', 10589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disturbance', 'n.  打扰； 骚动； 心神不安， 烦恼', 10590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confidant', 'n.  知己， 密友', 10591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simultaneous', 'adj.  同时的， 同步的', 10592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guarantee', 'v. 保证；担保 n.  保证， 担保； 保证书', 10593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'improvise', 'v.  即兴创作； 临时准备', 10594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predation', 'n.  掠夺； 掠食', 10595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recommend', 'vt.  推荐； 建议', 10596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demobilize', 'vt.  遣散； 使复员', 10597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leach', 'v. 过滤；溶解 n.  过滤器； 过滤剂', 10598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prodigious', 'adj.  巨大的', 10599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lost-and-found', 'n.  失物招领', 10600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knack', 'n.  诀窍； 技能， 本领； 习惯， 癖好', 10601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'default', 'vi.  不履行义务， 违约 n. 违约；弃权；缺省', 10602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indolent', 'adj.  懒惰的， 懒散的； 不活跃的', 10603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tropic', 'adj.  热带的 n. 回归线；热带地区', 10604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beverage', 'n.  饮料', 10605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diction', 'n.  措辞， 用语', 10606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ripe', 'adj.  熟的； 成熟的', 10607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attribute', 'n.  属性， 特征 vt.  把…归于', 10608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genetic', 'adj.  基因的， 遗传的', 10609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'triumph', 'v.  获胜， 成功 n. 狂喜；胜利，成功', 10610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slumber', 'vi.  睡眠， 安睡', 10611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arouse', 'vt.  唤醒， 唤起； 激起， 引起', 10612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nest', 'v. 做窝，筑巢 n.  巢， 窝', 10613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tout', 'v.  吹捧； 兜售', 10614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expropriate', 'vt.  征用， 没收', 10615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consensus', 'n.  共识， 一致同意； 舆论', 10616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classic', 'adj. 经典的；典型的 n. 经典作品；', 10617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embellish', 'vt.  装饰； 对…添枝加叶， 渲染', 10618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metric', 'adj.  米制的； 公制的', 10619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absolute', 'adj.  完全的， 绝对的； 地道的； 无疑的， 确凿的； 不受限制的， 不受约束的', 10620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retract', 'v.  收回， 撤销； 缩回', 10621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gossip', 'vi.  传播流言飞语， 说长道短 n. 闲话，流言飞语；爱说长道短的人', 10622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'technological', 'adj.  技术的， 工艺的', 10623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grab', 'v.  拿， 抓， 夺', 10624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silversmith', 'n.  银匠； 银器商人', 10625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antecedent', 'adj.  先行的 n. 祖先，先辈', 10626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remains', 'n.  剩余物， 残留物； 古代遗物， 遗迹， 遗址； 遗骸', 10627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'granular', 'adj.  粒状的； 含颗粒的', 10628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incorporate', 'vt.  纳入， 合并； 包含； 吸收； 注册成立', 10629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graphite', 'n.  石墨', 10630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boast', 'v&n.  自我夸耀', 10631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reiterate', 'vt.  反复说， 重申', 10632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flank', 'n. 肋腹；侧面；侧翼 vt.  位于…的侧面', 10633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counterpart', 'n.  相对物； 职位相当的人； 副本', 10634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'segment', 'n.  音段； 段， 部分', 10635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stripe', 'n.  条纹， 斑纹', 10636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sovereign', 'adj. 君主的；至高无上的；独立自主的 n.  君主， 元首， 最高统治者', 10637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gourd', 'n.  葫芦； 葫芦制成的容器', 10638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attractive', 'adj.  吸引人的， 有魅力的； 引起注意的', 10639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cater', 'v.  迎合； 提供饮食', 10640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superb', 'adj.  极好的， 高质量的， 上乘的； 华丽的', 10641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engineering', 'n.  工程； 工程学', 10642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duplicate', 'adj. 完全相同的；副本的 n.  复制品； 副本 vt.  复写； 复制； 使加倍', 10643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affable', 'adj.  和蔼可亲的， 易于交谈的， 友善的', 10644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decrease', 'v.  减少 n.  减少', 10645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surmise', 'v.  推测， 猜测 n.  推测， 猜测', 10646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eradicate', 'vt.  根除， 灭绝', 10647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'germinate', 'v.  发芽， 萌芽； 发展', 10648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trumpet', 'v. 鼓吹，宣扬 n.  小号， 喇叭', 10649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conservationist', 'n.  自然环境保护论者', 10650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'despondent', 'adj.  垂头丧气的， 沮丧的', 10651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trifle', 'vi.  不认真对待， 怠慢 n. 少许；琐事，小事；无价值的东西', 10652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'migrate', 'v.  迁徙； 移居', 10653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Easter', 'n.  复活节', 10654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'string', 'v.  用线串； 悬挂 n. 细绳，带子；一串；一系列；弦', 10655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submit', 'v.  提交， 呈递； 屈从； 主张， 建议', 10656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occupy', 'vt.  占用； 占据， 占领； 使忙于', 10657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'import', 'n.  进口， 输入； 意义， 要旨， 重要性 vt.  进口， 输入', 10658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affluent', 'adj.  丰富的； 富裕的', 10659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indigestion', 'n.  消化不良', 10660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrude', 'vi.  侵入， 闯入； 打扰， 侵扰', 10661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simplicity', 'n.  简单， 容易； 朴素， 质朴', 10662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blink', 'v. 眨眼睛；闪亮，闪烁 n.  眨眼睛', 10663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'summit', 'n.  最高点， 峰顶， 极点； 峰会', 10664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perfume', 'n. 香味；香水 vt.  使充满香气； 洒香水于', 10665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnify', 'vt.  放大， 扩大； 夸大', 10666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'redundant', 'adj.  多余的； 累赘的', 10667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'durable', 'adj.  持久的， 耐用的', 10668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impose', 'v.  把…强加于； 征； 处以', 10669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mammal', 'n.  哺乳动物', 10670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preliterate', 'adj.  文字出现以前的， 没有文字的', 10671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'factor', 'n.  要素， 因素； 因数； 系数', 10672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rite', 'n.  仪式， 典礼', 10673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pinch', 'v. 捏，掐；夹痛；偷窃；逮捕 n.  捏， 掐； 一撮， 微量', 10674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mischievous', 'adj.  恶作剧的， 顽皮的， 淘气的； 恶意的', 10675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conquer', 'vt.  战胜， 征服； 克服', 10676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wan', 'adj.  苍白的， 无血色的； 憔悴的', 10677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuity', 'n.  连贯性， 连续性', 10678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sculpture', 'n.  雕像， 雕塑品； 雕刻术', 10679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'realization', 'n.  实现； 意识', 10680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wax', 'v. 给…打蜡；渐满 n.  蜡； 蜡状物', 10681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contamination', 'n.  污染； 玷污', 10682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arable', 'adj. 可耕作的，适于耕作的 n.  可耕地', 10683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gist', 'n.  主旨， 要点， 大意', 10684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urban', 'adj.  城市的， 市内的', 10685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refer', 'v.  提到， 谈及； 查阅， 参考', 10686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stellar', 'adj.  星的， 恒星的， 星球的； 精彩的； 优秀的', 10687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flame', 'v.  燃烧； 闪耀 n. 火舌，火焰；光芒，光辉；强烈的感情', 10688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discard', 'vt.  丢弃', 10689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsidy', 'n.  补助金， 津贴', 10690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'criteria', 'n.  [criterion的复数形式]标准， 准则', 10691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obscene', 'adj.  淫秽的， 下流的； 骇人听闻的； 可憎的， 可恶的', 10692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'raft', 'v.  用筏运送； 乘筏渡河 n. 筏，木排；充气船', 10693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attentive', 'adj.  注意的， 专心的； 关心的', 10694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prohibitive', 'adj.  禁止的， 抑制的； 高得令人难以承受的', 10695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flair', 'n.  才能， 本领； 天资', 10696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modest', 'adj.  谦虚的； 适度的', 10697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crush', 'vt.  碾碎； 使变形； 镇压', 10698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electron', 'n.  电子', 10699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embed', 'vt.  把…嵌入； 使深留脑中', 10700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'citadel', 'n.  堡垒， 要塞', 10701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'promising', 'adj.  有希望的； 有前途的', 10702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambivalent', 'adj.  对立的， 感情矛盾的', 10703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'practicable', 'adj.  能实行的， 可行的， 适用的', 10704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physiology', 'n.  生理学； 生理机能', 10705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lofty', 'adj.  高耸的； 崇高的； 高傲的', 10706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explicit', 'adj.  清楚的； 直率的', 10707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utilize', 'vt.  利用', 10708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevail', 'vi.  盛行， 流行； 战胜， 压倒； 劝说', 10709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flake', 'v. 使成薄片；雪片般落下 n.  薄片', 10710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'browse', 'v. 吃嫩叶或草；浏览 n.  嫩叶； 浏览', 10711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implicit', 'adj.  含蓄的； 绝对的； 内含的', 10712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purity', 'n.  纯度； 纯洁， 纯净， 纯粹', 10713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portion', 'n. 部分；一份 vt.  划分， 分配', 10714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'futile', 'adj.  无效的， 无用的， 无意义的； 琐细的； 没出息的', 10715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pensive', 'adj.  沉思的； 忧虑的', 10716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliever', 'n.  救济者； 缓解物', 10717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acumen', 'n.  敏锐， 聪明', 10718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abate', 'v.  减少， 减轻', 10719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tragic', 'adj.  悲惨的； 悲剧的', 10720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eschew', 'vt.  避开， 戒除， 回避', 10721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physician', 'n.  内科医生', 10722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stardom', 'n.  明星的身份', 10723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amass', 'vt.  积聚', 10724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'venturesome', 'adj.  敢于冒险的； 有危险的', 10725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'souvenir', 'n.  纪念品， 纪念物', 10726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quaint', 'adj.  古色古香的； 离奇有趣的', 10727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grip', 'v. 控制；紧握；吸引住…的注意 n.  控制， 影响力； 紧握； 理解', 10728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tornado', 'n.  飓风， 龙卷风', 10729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explore', 'v.  探索， 勘探； 探险； 探究', 10730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acronym', 'n.  首字母缩写词', 10731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noteworthy', 'adj.  显著的， 值得注目的', 10732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shirk', 'v.  逃避， 规避', 10733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electricity', 'n.  电； 电流', 10734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tentative', 'adj.  试验性的； 不确定的， 暂定的； 犹豫的', 10735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cosmos', 'n.  宇宙', 10736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'climate', 'n.  气候； 气候区， 地带； 风气， 氛围； 思潮', 10737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staggering', 'adj.  巨大的； 势不可挡的； 惊人的， 令人吃惊的', 10738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crust', 'n.  地壳； 外壳； 硬的表面； 面包片', 10739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'criticize', 'v.  批评； 吹毛求疵， 非难； 评论', 10740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incredulous', 'adj.  怀疑的， 不轻信的', 10741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'condole', 'vi.  向…吊唁； 慰问', 10742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grid', 'n.  格子， 栅格； 地图上的坐标方格， 网格； 输电网， 煤气输送网', 10743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circumference', 'n.  周围， 周边； 圆周； 周长', 10744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rage', 'v. 猛烈地继续，激烈进行；发怒，怒斥；迅速蔓延，猖獗 n.  风靡一时的事物， 时尚； 狂怒', 10745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finalize', 'vt.  使完成； 把…最后定下来； 定稿', 10746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hull', 'n. 外壳；船身，船体 vt.  给…去外壳', 10747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preside', 'vi.  担任主席； 主持； 掌管', 10748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'board', 'v.  登机， 上船； 搭伙， 寄宿 n. 膳食费用；委员会，董事会；板，木板', 10749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'economic', 'adj.  经济的； 经济上的； 经济学的； 合算的', 10750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stuff', 'n. 原料，材料 vt.  填满， 塞满； 让…吃饱', 10751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offspring', 'n.  子孙， 后代； 崽', 10752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whim', 'n.  一时的兴致， 冲动； 怪念头， 奇想', 10753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arrest', 'n&vt.  逮捕， 拘留； 停止， 阻止； 吸引', 10754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assortment', 'n.  分类； 各种各样', 10755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'section', 'n.  部分； 地区； 部门； 段落， 章节； 截面， 剖面', 10756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rumor', 'n.  传闻， 谣言', 10757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overflow', 'v.  泛滥， 溢出 n.  溢出； 容纳不下的物', 10758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'provoke', 'vt.  挑动， 激怒， 挑衅； 引发， 引起', 10759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enrich', 'vt.  使充实； 使肥沃； 使富裕， 使富有', 10760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strain', 'n. 拉力，压力，张力；', 10761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'otherwise', 'adv. 另样，用别的方法；在其他方面 conj.  要不然， 否则', 10762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marked', 'adj.  显著的； 有记号的； 被监视的', 10763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pathological', 'adj.  病态的； 病理学的； 不理智的， 无道理的', 10764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recital', 'n.  音乐演奏会； 诗歌朗诵会； 赘述', 10765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'visible', 'adj.  看得见的， 明显的', 10766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrigue', 'v.  密谋； 迷住 n.  阴谋， 诡计', 10767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tangle', 'v.  缠结， 纠结 n. 混乱；纠纷，不和', 10768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orient', 'n. [O-]东方 vt.  使适应； 确定方向， 定位', 10769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recurring', 'adj.  往复的， 反复的， 再次发生的', 10770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tranquil', 'adj.  安静的， 平静的', 10771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pleasing', 'adj.  令人高兴的， 愉快的', 10772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inner', 'adj. 内部的；内心的 n.  内部； 内心', 10773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'voyage', 'n.  旅行； 航程', 10774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'keen', 'adj.  灵敏的， 敏锐的； 热心的， 渴望的； 激烈的； 锋利的', 10775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutrition', 'n.  营养； 营养学', 10776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absenteeism', 'n.  旷课； 旷工', 10777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cereal', 'n.  谷物； 谷类食物', 10778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gait', 'n.  步法， 步态', 10779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overhaul', 'n.  仔细检查； 彻底检修 vt.  仔细检查； 彻底检修', 10780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elementary', 'adj.  初级的， 基础的； 基本的； 简单的', 10781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solemn', 'adj.  庄严的， 严肃的； 隆重的', 10782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perceive', 'vt.  感知， 察觉； 理解', 10783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embarrass', 'vt.  使尴尬， 使困窘； 使困惑', 10784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'politics', 'n.  政治； 政纲， 政见； 政治事务； 权术； 政治学', 10785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acute', 'adj.  严重的； 极度的， 激烈的； 敏锐的', 10786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stigma', 'n.  污点， 耻辱； 烙印； 特征', 10787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pathology', 'n.  反常， 变态； 病理学； 病状', 10788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silica', 'n.  硅石， 硅土； 二氧化硅', 10789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crucial', 'adj.  至关重要的， 决定性的', 10790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contribute', 'v.  贡献， 捐赠； 有助于； 投稿', 10791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remark', 'v. 评论；谈论；察觉 n.  评论， 评语； 注释', 10792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microscope', 'n.  显微镜', 10793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissenter', 'n.  不同意者， 反对者', 10794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strive', 'vi.  奋斗， 努力； 力求', 10795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'candidate', 'n.  候选人； 投考者', 10796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fungus', 'n. 真菌', 10797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intelligible', 'adj.  聪明的， 理智的； 易懂的， 易理解的', 10798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'along', 'adv. 向前；一起 prep.  沿着', 10799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parallel', 'adj. 平行的；相似的 n. 相似处；', 10800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cashier', 'n.  收银员， 出纳员', 10801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inert', 'adj.  无活动的， 惰性的； 不活泼的， 迟钝的', 10802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diet', 'vi.  节食 n. 饮食，食物；规定饮食', 10803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissimulate', 'v.  掩盖， 掩饰， 假装', 10804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enzyme', 'n.  酶， 酵素', 10805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soccer', 'n.  足球', 10806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breach', 'n. 违背；破裂；缺口 vt.  打破； 违反', 10807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'butter', 'n. 黄油 vt.  涂黄油于', 10808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wit', 'n.  智力， 才智； 风趣； 机智幽默的人', 10809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respire', 'v.  呼吸', 10810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'selective', 'adj.  选择的， 选择性的； 精挑细选的', 10811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handful', 'n.  一把； 少数人', 10812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebate', 'n.  回扣， 折扣； 退还款', 10813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stimulus', 'n. 刺激（物）；促进因素', 10814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'systematize', 'vt.  使系统化， 使条理化， 使成体系', 10815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barter', 'n&v.  实物交易， 以物易物', 10816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bewilder', 'vt.  使迷惑， 使不知所措', 10817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regiment', 'n. 团；', 10818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terminal', 'adj.  末端的 n. 终点站；终点；航站楼', 10819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kerosene', 'n.  煤油， 火油', 10820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diminish', 'v.  降低， 贬低； 减少， 减弱', 10821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surpass', 'vt.  超过， 超越， 胜过', 10822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linguist', 'n.  语言学家； 通晓数国语言的人', 10823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oyster', 'n.  牡蛎， 蚝', 10824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aloof', 'adj.  远离的； 冷淡的， 冷漠的', 10825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idealize', 'vt.  将…理想化', 10826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gouge', 'vt. 挖出；敲竹杠 n.  凿子', 10827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attention', 'n.  注意， 留心； 立正', 10828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'succumb', 'vi.  屈服， 屈从； 死亡', 10829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disproportionate', 'adj.  不成比例的', 10830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extent', 'n.  程度， 范围', 10831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'translucent', 'adj.  半透明的', 10832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magma', 'n.  岩浆', 10833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fin', 'n.  鳍； 鳍状物； 翼', 10834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sauce', 'n.  调味汁， 佐料', 10835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'husk', 'n. 外壳，外皮 vt.  去壳， 削皮', 10836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fix', 'v. 修理；使固定，安装；安排；找到，确定 n.  解决方法； 困境， 窘境', 10837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonial', 'adj.  殖民的； 殖民国家的', 10838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rank', 'v.  属于某等级， 归类 n. 等级；头衔', 10839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'giant', 'adj. 巨大的；超群的 n.  巨大的动物； 才智超群的人', 10840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perch', 'v. 栖息，停留；把…置于较高处；坐于 n.  栖息处， 栖木； 高处， 较高的位置； 鲈鱼', 10841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ablaze', 'adj.  着火的， 燃烧的； 闪耀的； 情绪激动的', 10842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grouse', 'v. 发牢骚，抱怨 n.  松鸡； 怨言', 10843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'addition', 'n.  加， 加法； 添加， 增加', 10844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overcharge', 'v. 讨价过高，索价过高；过量装填；渲染，夸张 n.  过高的要价； 超载', 10845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saucy', 'adj.  无礼的； 俏皮的； 漂亮的', 10846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neglect', 'vt&n.  忽略， 忽视； 疏忽', 10847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cosmic', 'adj.  宇宙的； 无限的', 10848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gang', 'vi.  合伙 n. 一帮，一伙；帮派', 10849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vein', 'n.  静脉； 叶脉； 纹理， 纹路； 方式， 风格', 10850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carve', 'v.  雕刻； 切', 10851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrink', 'v.  收缩， 缩小； 退缩， 畏缩', 10852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'veil', 'n. 面纱；遮蔽物 vt.  以面纱掩盖； 掩饰', 10853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ancestor', 'n.  祖先， 祖宗； 原种； 原型', 10854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hierarchy', 'n.  统治集团； 等级制度； 阶层', 10855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'league', 'n.  联盟， 同盟； 等级， 级别', 10856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'textile', 'n.  纺织品', 10857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locality', 'n.  地点； 位置', 10858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncanny', 'adj.  神秘的； 易乎寻常的', 10859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'former', 'adj. 从前的 n.  前者', 10860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'panic', 'n&v.  惊慌', 10861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extend', 'v.  延长， 延伸； 扩大…的范围； 舒展', 10862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fold', 'n. 褶，褶层；褶皱；褶痕，褶缝；羊栏，', 10863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canyon', 'n.  峡谷', 10864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impenetrable', 'adj.  不能穿透的； 不可理解的， 高深莫测的', 10865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hurl', 'v.  猛投； 大声斥责', 10866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intermediate', 'adj. 中间的；中级的 n.  中间体， 媒介', 10867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consideration', 'n.  考虑， 思考； 体谅， 照顾； 考虑因素， 理由； 报酬', 10868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frank', 'adj.  坦白的， 直率的', 10869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inscribe', 'v.  写、 题、 铭刻； 铭记', 10870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admire', 'vt.  钦佩， 仰慕； 欣赏', 10871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virus', 'n.  病毒； 病毒性疾病', 10872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rape', 'vt&n.  强奸； 肆意破坏', 10873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metaphor', 'n.  隐喻， 暗喻', 10874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genre', 'n.  类型； 流派', 10875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permanence', 'n.  永久， 持久', 10876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'panel', 'n. 面板，镶板；仪表盘；专门小组 vt.  镶板', 10877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanity', 'n.  人类； 人性； 人道， 仁慈', 10878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outstanding', 'adj.  优秀的， 杰出的， 出色的； 未解决的； 未偿付的', 10879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adobe', 'n.  泥砖， 土坯', 10880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alternate', 'v.  轮流， 交替 adj.  交替的， 轮流的； 间隔的', 10881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unbridgeable', 'adj.  不能架桥的； 不能逾越的', 10882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infuriate', 'vt.  激怒', 10883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flu', 'n.  流行性感冒', 10884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plunge', 'v. 掉入；暴跌，突降 n.  跳水； 猛跌， 骤降； 卷入', 10885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skeptical', 'adj.  怀疑的', 10886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decipher', 'vt.  破译', 10887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burgeon', 'vi.  迅速成长， 发展', 10888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'naive', 'adj.  天真的， 率真的， 质朴的； 幼稚的， 无知的， 轻信的； 稚拙派的', 10889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sewage', 'n.  污水， 污物', 10890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'essential', 'adj. 基本的，本质的；极其重要的，必不可少的 n.  要素， 实质； 必需品', 10891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expenditure', 'n.  花费， 支出', 10892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vent', 'n. 通风口；出口 vt.  表达， 发泄', 10893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clarify', 'vt.  澄清， 阐明', 10894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furnace', 'n.  火炉， 熔炉； 锅炉', 10895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haunt', 'vt. 出没于；萦绕在心头；长期缠扰 n.  常去的地方', 10896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scarf', 'n.  围巾， 披巾， 头巾', 10897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congenial', 'adj.  情投意合的； 相宜的， 适宜的； 适当的， 合适的', 10898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graphics', 'n.  图形， 图像； 制图法， 制图学', 10899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'observe', 'v.  遵守， 奉行； 观察； 察觉， 看到； 评说， 评论', 10900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meaningful', 'adj.  意味深长的； 有目的的， 有用意的； 有意义的', 10901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furnish', 'vt.  提供， 供应； 布置， 为…配备家具', 10902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'larynx', 'n.  喉', 10903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excavation', 'n.  挖掘， 发掘； 出土文物； 挖掘现场', 10904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rare', 'adj.  稀有的， 罕见的； 半熟的', 10905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exclude', 'vt.  把…排除在外', 10906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amalgamation', 'n.  融合， 合并； 联合， 结合', 10907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creativity', 'n.  创造力， 创造性', 10908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enlighten', 'vt.  启发， 启迪； 开导； 阐明', 10909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'needy', 'adj.  贫穷的， 贫困的', 10910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utmost', 'adj. 最大限度的 n.  最大限度； 最大量', 10911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deduct', 'vt.  扣除， 减去； 推论， 演绎', 10912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'image', 'n.  形象， 印象； 画像； 影像， 映像； 意象， 比喻', 10913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'voracious', 'adj.  狼吞虎咽的， 贪婪的； 求知欲强的', 10914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unpredictable', 'adj.  不可预知的； 无法预言的', 10915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'topography', 'n.  地形学； 地形， 地貌', 10916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ribbon', 'n.  带状物； 丝带， 缎带； 绶带； 色带', 10917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portray', 'vt.  描绘； 扮演， 饰演', 10918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trance', 'n.  恍惚； 昏睡状态', 10919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scrub', 'v. 擦洗；取消 n.  灌木丛； 丛林地带', 10920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'profound', 'adj.  巨大的， 深远的； 知识渊博的； 深奥的', 10921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affirm', 'v.  断言， 坚持声称； 证实， 确认', 10922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homogeneous', 'adj.  同类的， 相似的， 同质的', 10923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marble', 'n.  大理石； 子弹', 10924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waggle', 'v&n.  摆动', 10925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'garb', 'n. 服装，装束 vt.  穿着， 装扮', 10926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'necessity', 'n.  必需品； 必要， 需要； 必然性', 10927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frame', 'n. 框架；总的思想，体系 vt.  设计， 构成； 给…镶框； 表达', 10928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salon', 'n.  营业性的厅； 沙龙； 客厅， 会客厅', 10929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vocal', 'adj. 声音的，嗓音的，发声的；直言不讳的', 10930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'origin', 'n. 起源，由来；', 10931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plow', 'v.  耕田， 犁田， 耕作 n. 犁', 10932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clasp', 'n. 搭扣，扣环；紧抱；紧握 vt.  握紧； 抱紧； 扣住， 扣牢', 10933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hover', 'vi.  徘徊， 彷徨； 翱翔， 盘旋', 10934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'random', 'adj. 随机的，任意的 n.  随机， 随意', 10935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personality', 'n.  个性； 性格； 名人', 10936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terminology', 'n.  专门用语， 术语； 术语学', 10937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alert', 'adj. 警觉的，警惕的 vt. 警告，提醒 n.  警戒； 警报', 10938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rate', 'v.  估价； 评级， 评价； 把…列为 n. 率，比率；速度；价格；等级', 10939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plot', 'n. 情节；阴谋，密谋；', 10940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sanction', 'vt. 同意，许可；惩罚，实施制裁 n.  同意， 许可； 约束； 制裁', 10941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mosaic', 'n.  马赛克； 镶嵌工艺', 10942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oak', 'n.  橡树， 橡木', 10943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prosperity', 'n.  繁荣， 兴旺', 10944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proprietor', 'n.  所有者， 业主', 10945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contrary', 'adj. 相反的，逆的 n.  相反， 反面', 10946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rehearse', 'v.  预演， 排练； 默诵； 照搬， 重复', 10947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thwart', 'vt.  阻碍； 使…受挫', 10948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gamble', 'n&v.  投机， 冒险； 赌博， 打赌', 10949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pesticide', 'n.  杀虫剂， 农药', 10950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deport', 'vt.  驱逐出境', 10951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'syrup', 'n.  糖浆', 10952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counter', 'adv. 相反地 adj. 相反的 n. 柜台；', 10953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conserve', 'vt.  保存， 保藏', 10954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Gothic', 'adj. 哥特式的，哥特风格的 n.  哥特式建筑', 10955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhythm', 'n.  节奏， 韵律', 10956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rash', 'adj. 鲁莽的，轻率的 n.  疹， 皮疹； 一连串令人不快的事物', 10957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pottery', 'n.  陶器； 陶器厂， 制陶作坊； 制陶工艺， 陶器制造术', 10958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cylinder', 'n.  圆筒， 圆柱体； 气缸', 10959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'starch', 'n. 淀粉；', 10960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depose', 'vt.  革除， 罢免， 废黜', 10961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'correspondent', 'n.  报道者， 记者； 通信者', 10962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fort', 'n.  要塞， 堡垒； 营地', 10963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renew', 'vt.  使…续期； 重新开始； 重申； 修复', 10964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assign', 'vt.  指派； 指定； 分配； 布置', 10965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'withdraw', 'v.  取消； 撤销； 提取； 撤退， 撤离', 10966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decade', 'n.  十年， 十年期', 10967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'languish', 'vi.  憔悴； 凋谢， 枯萎； 受煎熬', 10968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melodic', 'adj.  旋律的， 曲调的； 音调优美的', 10969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congress', 'n.  [C-] 议会， 国会； 大会', 10970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'welfare', 'n.  福利； 安宁， 幸福', 10971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'divine', 'adj. 神的，神圣的；非凡的，超人的；极好的，', 10972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abhor', 'vt.  憎恨， 厌恶', 10973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legislative', 'adj.  立法的， 有立法权的； 根据法规执行的 n. 立法机关', 10974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flourish', 'vi.  繁荣， 茂盛； 挥舞， 挥动', 10975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transcribe', 'vt.  记录， 抄录； 转录； 改编', 10976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foul', 'adj.  污秽的， 肮脏的； 充满脏话的， 辱骂性的； 邪恶的', 10977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intricate', 'adj.  错综复杂的', 10978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contemplate', 'v.  思量， 考虑， 思忖； 注视， 凝视； 打算', 10979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rodent', 'adj.  啮齿目的； 咬的 n. 啮齿目动物', 10980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'context', 'n.  上下文； 背景； 环境', 10981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drag', 'v. 拖动；缓慢而费力地移动；拖沓地进行，拖延 n.  累赘， 障碍； 一吸， 一抽， 一饮', 10982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'zinc', 'n.  锌', 10983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advisory', 'adj. 顾问的，咨询的；劝告的 n.  警报', 10984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'issue', 'n. 问题，争论点；发行；', 10985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maturity', 'n.  成熟； 完备', 10986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsistence', 'n.  生存， 生计', 10987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lower', 'v. 降低 adj.  较低的； 下级的， 下等的', 10988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frail', 'adj.  体弱的， 虚弱的； 易碎的', 10989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'odd', 'adj.  单数的； 奇数的； 奇异的， 古怪的； 偶尔发生的', 10990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'announce', 'vt.  宣布； 通知； 声称， 宣称； 广播， 播音', 10991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mechanize', 'vt.  使机械化', 10992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'additive', 'n. 〔食品的〕添加剂，添加物', 10993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decree', 'v.  判决； 颁布 n. 政令，法令；裁定，判决', 10994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'traditional', 'adj.  传统的， 惯例的； 口传的， 传说的', 10995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conservation', 'n.  守恒； 保存； 保护', 10996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'malleable', 'adj.  有延展性的， 易成型的； 易受影响的， 可塑的', 10997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplement', 'n.  补充， 增补； 增刊； 补遗， 附录 vt.  补充， 增补', 10998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'well-heeled', 'adj.  富有的， 有钱的', 10999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contrast', 'v.  对比， 对照 n.  对比， 对照', 11000);
