INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'back', 'adv. 回原处 n. 背,后面 adj. 后面的 v. 后退', 1);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'significant', 'adj. 重要的,意义重大的', 2);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skill', 'n. 技能,技巧', 3);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'public', 'adj. 公共的,公开的 n. 公众', 4);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'go', 'v. 去,离开,进行', 5);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fish', 'n. 鱼 v. 钓鱼', 6);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'set', 'n. (一)套 v. 放置,设定', 7);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'once', 'adv. 一次,曾经 conj. 一旦…(就…)', 8);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'table', 'n. 桌子,表格', 9);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demand', 'n&v. 要求,需要', 10);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'day', 'n. 天,一昼夜,时期', 11);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'south', 'n. 南部 adj. 南方的 adv. 在南方', 12);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'almost', 'adv. 几乎,差不多', 13);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'local', 'adj. 当地的,局部的 n. 当地人', 14);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'open', 'adj. 开的,开放的 v. 开', 15);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cover', 'v. (掩)盖,包括,报道 n. 盖子,封面', 16);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purpose', 'n. 目的,意图', 17);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reach', 'v. 到达,伸出,达成 n. 范围', 18);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'various', 'adj. 不同的,多样的,多方面的', 19);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'late', 'adj. 晚的,最近的 adv. 迟,晚', 20);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sometime', 'adv. 将来(或过去)某个时候 adj. 以前的', 21);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'function', 'n. 功能,职务 v. 运行,起作用', 22);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'able', 'adj. 能够…的,得以…的', 23);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allow', 'v. 允许(…进入),同意给,承认', 24);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'middle', 'n. 中部,中间 adj. 中部的,中间的', 25);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'home', 'n. 家(乡)', 26);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'European', 'adj. 欧洲的 n. 欧洲人', 27);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reason', 'n. 原因v分析,推理', 28);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rise', 'n&v. 上升,升起', 29);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'member', 'n. 成员,会员', 30);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toward', 'prep. 向,朝,接近', 31);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'house', 'n. 房屋 v. 给…房子住', 32);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'characteristic', 'n. 特性,特征 adj. 特有的,典型的', 33);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'last', 'adj. 刚过去的,最后的 adv. 最后 v. 持续', 34);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'location', 'n. 位置,地点', 35);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'today', 'n. 今天,现今', 36);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'culture', 'n. 文化,文明', 37);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infant', 'n. 婴儿', 38);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'left', 'adj. 左边的 adv. 向左 n. 左边', 39);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recent', 'adj. 近来的,新近的', 40);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Europe', 'n. 欧洲', 41);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'family', 'n. 家,家庭', 42);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'site', 'n. 位置,地点 v. 使位于,设置', 43);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incorrect', 'adj. 不正确的,错误的', 44);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agricultural', 'adj. 农业的', 45);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generally', 'adv. 通常,普遍地', 46);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'property', 'n. 财产,所有物', 47);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atmosphere', 'n. 大气,空气,气氛', 48);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'themselves', 'pron. 他(她、它)们自己', 49);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'though', 'conj. 尽管,虽然 adv. 可是', 50);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strong', 'adj. 强烈的,坚强的,强壮的', 51);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clear', 'a&ad. 清晰的(地) v. 清除 v. 变清澈', 52);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reduce', 'v. 减少,缩小', 53);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deposit', 'v. 沉淀,存放,堆积 n. 存款,堆积物', 54);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'west', 'n. 西(方,部) adj. 西方(部)的 adv. 向西方', 55);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thus', 'adv. 如此,因此', 56);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cannot', 'conj. 不能', 57);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statement', 'n. 陈述,声明', 58);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'settle', 'v. 解决,定居,安顿', 59);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melt', 'v. (使)融化,(使)消散,(使)逐渐消失', 60);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Pacific', 'n. 太平洋', 61);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'available', 'adj. 可利用的,可得到的,有空的', 62);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'direct', 'a&ad. 直接的 v. 对准,指导', 63);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industry', 'n. 工业,产业', 64);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'language', 'n. 语言', 65);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vary', 'v. 改变,变化,使多样化', 66);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glass', 'n. 玻璃,玻璃杯,[pl]眼镜', 67);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'range', 'n. 范围,山脉 v. 变动,排列', 68);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subject', 'n. 主题,学科 v. 使服从', 69);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deep', 'adj. 深的 adv. 深深地', 70);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'green', 'adj. 绿色的,生的 v. 使…变绿', 71);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charge', 'v. 指控,收费,充电', 72);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'travel', 'n&v. 旅行,移动,传播', 73);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dry', 'adj. 干的,干燥的 v. (使)变干', 74);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'role', 'n. 作用,角色', 75);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'establish', 'v. 建立,确立,创办', 76);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'right', 'a&ad. 对(的),右(的) n. 权利 v. 扶直,纠正', 77);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lower', 'adj. 较低的,下面的 v. 降下,放低', 78);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'center', 'n&a. 中心(的) v. 居中,使集中', 79);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roman', 'a&n. 罗马(的),罗马人(的)', 80);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tend', 'v. 易于,趋向 v. 照料', 81);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'longer', 'ad&a. 比较久(的)', 82);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'just', 'adv. 正好,仅仅,刚才 adj. 公平的', 83);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lack', 'v&n. 缺乏,不足', 84);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compare', 'v. 比较,对比,比喻 n. 比较', 85);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'away', 'adv. 在远处,离去', 86);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insect', 'n. 昆虫,虫', 87);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'experience', 'n&vt. 经历,经验', 88);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'measure', 'n. 措施,量度,尺寸 v. 测量', 89);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'replace', 'v. 取代,替换,放回原处', 90);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attract', 'v. 吸引', 91);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snow', 'n. 雪 v. 下雪', 92);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salt', 'n. 盐 v. 腌,盐渍', 93);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hunt', 'n&v. 狩猎,追捕,搜寻', 94);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clay', 'n. 黏土,泥土', 95);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turn', 'v. 转动,扭转,(使)变成', 96);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feature', 'n. 特征 v. 以为特色,起作用', 97);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marine', 'n. 船舶,水兵 adj. 海(洋)的,海军(事)的', 98);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weather', 'n. 天气,气象 v. 风化,经受风雨(侵蚀)', 99);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'popular', 'adj. 流行的,通俗的,受欢迎的', 100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consider', 'v. 考虑,认为', 101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'necessary', 'adj. 必要的,必然的 n. 必需品', 102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'researcher', 'n. 研究者,调查者', 103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upper', 'adj. 上面的,上部的', 104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wide', 'adj. 宽阔的,广泛的', 105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forest', 'n. 森林 v. 种植于', 106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'current', 'adj. 当前的 n. 趋势', 107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'learn', 'v. 学会,学习,得知', 108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'select', 'v. 选择,挑选 adj. 精选的', 109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'improve', 'v. 改善,改进', 110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'western', 'adj. 西方的,西部的 n. 西方人', 111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lake', 'n. 湖', 112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'value', 'n. 价值 v. 评估,重视', 113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'factory', 'n. 工厂,制造厂', 114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'school', 'n. 学校,学院 v. 教育', 115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warm', 'a&ad. 温暖的 v. 变暖,使暖和', 116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scientific', 'adj. 科学的', 117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'raise', 'n. 上升,增高 v. 升起,举起,提出', 118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'political', 'adj. 政治的,政党的', 119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maintain', 'v. 维持,保持', 120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ant', 'n. 蚂蚁', 121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affect', 'v. 影响,作用', 122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fit', 'v. 适合,适应,安装', 123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'periodic', 'adj. 周期的,定期的', 124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metal', 'n. 金属 v. (以金属)覆盖、装配', 125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'importance', 'n. 重要(性)', 126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'native', 'adj. 本国的,本土的,当地的 n. 本地人', 127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identify', 'v. 识别,鉴定', 128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'valley', 'n. 山谷', 129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specific', 'adj. 特定的,具体的', 130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'short', 'adj. 短的,矮的', 131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foot', 'n. 足,脚', 132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'style', 'n. 风格,式样', 133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hard', 'adj. 硬的,困难的 adv. 努力地,强烈地', 134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'origin', 'n. 起源,来源', 135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grain', 'n. 谷物,颗粒 v. 形成(颗粒),(用谷物)喂养', 136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'national', 'adj. 国家的,民族的', 137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'near', 'adv. 在近处 v&prep. 靠(接)近 adj. 接近的', 138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'person', 'n. 人', 139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primary', 'adj. 首要的,主要的,最初的 n. 居首位的事物', 140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mammal', 'n. 哺乳动物', 141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formation', 'n. 形成,构成,编队', 142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deer', 'n. 鹿', 143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complex', 'adj. 复杂的,复合的', 144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'past', 'adj. 以前的 prep&ad. 经过,过 n. 过去', 145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'say', 'v. 说,表明', 146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flow', 'n&v. 流动,淹没', 147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'break', 'n. 休息 v. 打破,弄坏', 148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'low', 'a&ad. 低(的),低下(的)', 149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seed', 'n. 种子 v. 播种', 150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perhaps', 'adv. 也许,可能', 151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steam', 'n. 蒸汽v蒸,蒸发', 152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'picture', 'n. 画,照片 v. 描绘,构想', 153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'east', 'n. 东(方，部)a东方(部)的 adv. 向东方', 154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agriculture', 'n. 农业,农学', 155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'particle', 'n. 微粒,极小量', 156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aspect', 'n. 方面,外观', 157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industrial', 'adj. 工业的,产业的', 158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'field', 'n. 田地,领域', 159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'experiment', 'n. 试验 v. 尝试,做实验', 160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'itself', 'pron. 它自己', 161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relate', 'v. 叙述,使有联系,有关联', 162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yet', 'adv. 还,已经 conj. 然而', 163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instrument', 'n. 仪器,工具', 164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speed', 'n. 速度 v. 加速,急行', 165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thousand', 'n. 一千(个),许许多多,成千上万', 166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'print', 'v. 印刷,冲洗(照片)', 167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'therefore', 'adv. 因此,所以', 168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tradition', 'n. 传统,惯例', 169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'goods', 'n. 货物,商品', 170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'represent', 'v. 代表,表现,描绘', 171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'iceberg', 'n. 冰山,冷若冰霜的人', 172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'our', 'pron. 我们的', 173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'man', 'n. 男人,人(类)', 174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'store', 'v. 储存,贮藏 n. 商店', 175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depend', 'v. 依靠,取决于', 176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heavy', 'a&ad. 重的,大量的', 177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'general', 'adj. 普遍的,概括的', 178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'story', 'n. 故事,小说', 179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'technology', 'n. 工艺,技术', 180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rain', 'n. 雨 v. 下雨', 181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contrast', 'v&n. 对比,对照', 182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predator', 'n. 掠夺者,食肉动物', 183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'against', 'prep. 反对,逆,防御', 184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'survive', 'v. 活着,幸存', 185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biological', 'adj. 生物(学)的', 186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nature', 'n. 自然(界),本性', 187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expression', 'n. 措辞,表达', 188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solar', 'adj. 太阳(能)的', 189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'teacher', 'n. 教师', 190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'off', 'adv. 掉(下),离开,停止', 191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'town', 'n. 城市,城镇', 192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'architecture', 'n. 建筑,建筑学', 193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'train', 'v. 训练,培训', 194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contribute', 'v. 捐助,贡献', 195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'least', 'ad&a. 最小的,最少的', 196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pass', 'v. 通过,经过', 197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'always', 'adv. 总是,一直,始终,', 198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'normal', 'adj. 正常的,正规的', 199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mineral', 'n. 矿物,矿石', 200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primarily', 'adv. 主要地,起初地', 201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knowledge', 'n. 知识,学问', 202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ask', 'v. 询问,请求,邀请', 203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'observe', 'v. 注意到,观察,监视', 204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simple', 'adj. 简单的,朴素的', 205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slow', 'adj. 慢的 v. 放慢,减速', 206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canal', 'n. 运河,沟渠', 207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'craft', 'n. 工艺,手艺', 208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'name', 'n. 名字 v. 命名', 209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reflect', 'v. 反映,反射', 210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'addition', 'n. 加,增加,附加物', 211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'argue', 'v. 说服,争论,辩论', 212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'draw', 'v. 画,拖,移动', 213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theater', 'n. 戏院,剧场', 214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'above', 'prep. 在…上方,多(大,高)于 adv. 在上面', 215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'especially', 'adv. 特别,尤其', 216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'central', 'adj. 中心的,主要的,重要的', 217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apply', 'v. 申请,应用', 218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quickly', 'adv. 快速地', 219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'every', 'adj. 每个,一切的,每隔', 220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'successful', 'adj. 成功的,圆满的', 221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frequent', 'adj. 频繁的,经常的', 222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surround', 'v. 包围,环绕', 223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'practice', 'n&v. 练习', 224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'introduce', 'v. 介绍,引进', 225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggressive', 'adj. 侵略的,进攻性的', 226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'act', 'v. 行动,表演 n. 行为', 227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Canada', 'n. 加拿大', 228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extreme', 'adj. 极度的,极端的 n. 极端,过分', 229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'test', 'n&vt. 试验,测试', 230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glacial', 'adj. 冰川(期)的,非常冷的', 231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sense', 'v. 感觉,意识到', 232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eat', 'v. 吃', 233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'single', 'adj. 单一的,单个的,独身的', 234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quality', 'n. 质量,品质,性质', 235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'teach', 'v. 讲授,教授', 236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continent', 'n. 大陆,洲', 237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cycle', 'n. 循环,周期 v. 骑自行(摩托)车,循环', 238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'previous', 'adj. 以前的,先于,在之前', 239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'northern', 'adj. 北方的,北部的', 240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'separate', 'v. 分开,隔开', 241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cost', 'n. 价格,成本 v. 花费,使付出', 242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advantage', 'n. 优势,有利条件 v. 有利于', 243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transportation', 'n. 运输(工具、系统)', 244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discovery', 'n. 发现,发现物', 245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stream', 'n. 小河,溪流 v. 涌流(出)', 246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obtain', 'v. 获得,得到', 247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recognize', 'v. 认出,确认,意识到', 248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parent', 'n. 父母亲', 249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypothesis', 'n. 假设', 250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'England', 'n. 英格兰', 251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rural', 'adj. 农村的', 252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concern', 'v. 有关于,使担心,', 253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'get', 'v. 获得,得到', 254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substance', 'n. 物质,实质,主旨', 255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'original', 'adj. 原始的,最初的', 256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'easily', 'adv. 容易地', 257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'channel', 'n. [常pl]通道,渠道', 258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'belong', 'v. 属于', 259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'construction', 'n. 建造,结构', 260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swim', 'n&v. 游泳', 261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'southern', 'adj. 南的,南方的', 262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'worth', 'prep. 相当于…价值的,值得…的 n. 价值', 263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'run', 'v. 跑,运转,经营', 264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imply', 'v. 暗示, 意味', 265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'basic', 'adj. 基本的,基础的', 266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'internal', 'adj. 内在的,国内的', 267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crystal', 'n. 水晶', 268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explanation', 'n. 解释,说明', 269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evolve', 'v. 演变,进化,发展', 270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hundred', 'n. 百,[pl]数以百计', 271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'start', 'v. 开始,出发', 272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beg', 'v. 请求,乞求', 273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rapid', 'adj. 快的,迅速的', 274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quantity', 'n. 量,数量', 275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illustrate', 'v. 说明,阐明', 276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locate', 'v. 定位,把…设置在', 277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remove', 'v. 移开,去除', 278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'across', 'prep. 穿过,在对面', 279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whose', 'pron. 谁的,那(些)人的', 280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'typical', 'adj. 典型的,有代表性的', 281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'matter', 'n. 事情,情况 v. 要紧', 282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resource', 'n. 资源', 283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eastern', 'adj. 东方的,东部的', 284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'half', 'n&a. 一半,半个的', 285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'migration', 'n. 移居,迁移', 286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'course', 'n. 过程,课程', 287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'date', 'n. 日期,时期 v. 追溯到', 288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'merchant', 'n. 商人', 289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'face', 'n. 脸 v. 面向,面对', 290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coast', 'n. 海岸,海滨', 291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'machine', 'n. 机器,机械', 292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'claim', 'n&v. 声称,要求', 293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'religious', 'adj. 宗教的', 294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twentieth', 'num. 第二十,二十分之一', 295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'throughout', 'prep. 遍及,贯穿 adv. 始终', 296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'special', 'adj. 特别的,特殊的', 297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plate', 'n. 盘子,碟', 298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mark', 'n. 痕迹,记号 v. 做标记', 299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atomic', 'adj. 原子的,原子能的', 300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rapidly', 'adv. 迅速地', 301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wood', 'n. 木头,木材', 302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leader', 'n. 领导者', 303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fire', 'n. 火 v. 开火,解雇,点燃', 304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entire', 'adj. 全部的,整个的', 305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plain', 'n. 平原,草原 adj. 清晰的,简单的', 306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extend', 'v. 延伸,扩展', 307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'difficulty', 'n. 困难,难点', 308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'core', 'n. 核心,要点', 309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'easy', 'adj. 容易的,轻松的', 310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constant', 'adj. 不变的,持续的', 311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adult', 'n. 成年人', 312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consist', 'v. 由组成,在于', 313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'figure', 'n. 图形,外形 v. 计算,认为', 314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cold', 'adj. (寒)冷的 n. (寒)冷,感冒', 315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'education', 'n. 教育', 316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'railroad', 'n. 铁路 v. 由铁道运输 v. 在铁路公司工作', 317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'law', 'n. 法律', 318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unlike', 'adj. 不同的 prep. 不象…', 319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expand', 'v. 扩大,扩展,膨胀', 320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brain', 'n. 脑,头脑', 321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carbon', 'n. 碳', 322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'return', 'v. 返回,恢复,归还', 323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cell', 'n. 单元,细胞', 324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'either', 'adv. [否]也 a&pron. 任一的', 325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'company', 'n. 公司', 326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grass', 'n. 草', 327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engine', 'n. 发动机,引擎', 328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stimulus', 'n. 促进(因素),刺激(物)', 329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hour', 'n. 小时,钟点', 330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'program', 'n. 节目,计划,程序 v. 编程', 331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevent', 'v. 防止,预防', 332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'per', 'prep. 每,每一', 333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sell', 'v. 出售,卖', 334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'damage', 'v&n. 损害,毁坏', 335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unusual', 'adj. 异常的,独特的', 336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lie', 'v. 躺,说谎', 337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wall', 'n. 墙 v. 围住,隔开', 338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landscape', 'n. 风景,全景 v. 美化', 339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brief', 'n. 摘要,大纲 adj. 简短的', 340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'associate', 'v. 联合,结交 n. 伙伴 adj. 副的', 341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rare', 'adj. 稀有的,珍奇的', 342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minor', 'adj. 较小的,次要的', 343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artisan', 'n. 工匠,技工', 344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorite', 'n. 陨石, 流星', 345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'define', 'v. 定义,详细说明', 346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cool', 'v. 冷却,(使)冷静', 347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oxygen', 'n. 氧', 348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'daily', 'adj. 每日的,日常的', 349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Africa', 'n. 非洲', 350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erosion', 'n. 腐蚀,侵蚀', 351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'want', 'v. 想要', 352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'response', 'n. 回答,响应,反应', 353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'third', 'num. 第三,三分之一', 354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decade', 'n. 十年,十', 355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emphasize', 'v. 强调,着重', 356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'baby', 'n. 婴孩', 357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volcanic', 'adj. 火山的,猛烈的', 358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organization', 'n. 组织,机构,团体', 359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonial', 'adj. 殖民地的', 360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preserve', 'v. 保护,保存', 361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detail', 'n. 细节,详情 v. 详述', 362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bone', 'n. 骨,骨骼', 363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'position', 'n. 位置,职务,立场 v. 安置', 364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protect', 'v. 保护', 365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'labor', 'n. 工人 v. 劳动', 366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'degree', 'n. 学位,程度,度数', 367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revolution', 'n. 革命', 368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'read', 'v. 读,理解', 369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'positive', 'adj. 积极的,肯定的', 370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receive', 'v. 接到,收到,接待', 371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'route', 'n. 路线,途径', 372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statue', 'n. 塑像,雕像', 373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meter', 'n. 米,公尺', 374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jupiter', 'n. 木星', 375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organic', 'adj. 有机(体)的,有机物的', 376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apparent', 'adj. 明显的,表面上的', 377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motion', 'n. 运动,动作', 378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'you', 'pron. 你,你们', 379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'composition', 'n. 成分,作品,合成物', 380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stage', 'n. 舞台,阶段', 381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cut', 'v. 切,割,剪', 382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vegetation', 'n. 植物,草木', 383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'winter', 'n. 冬季 v. 过冬', 384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eventually', 'adv. 最后,终于', 385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expose', 'v. 暴露,显露', 386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dinosaur', 'n. 恐龙', 387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literature', 'n. 文学,文献', 388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'project', 'n. 计划,工程v设计,计划', 389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meet', 'v. 遇见,见面', 390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'benefit', 'n. 利益 v. 有益于,得益', 391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whether', 'conj. 是否,不管,无论', 392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slowly', 'adv. 慢慢地,迟缓地', 393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thing', 'n. 东西,事情', 394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facial', 'adj. 脸部的,面部的', 395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liquid', 'n. 液体 adj. 液体的', 396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cultural', 'adj. 文化的,教养的', 397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'differ', 'v. 不同,有区别 n. 区别', 398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'never', 'adv. 决不,从未', 399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'science', 'n. 科学', 400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spread', 'v. 传播,展开,散布', 401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whig', 'n. 辉格党', 402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encourage', 'v. 鼓励,促进,支持', 403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newspaper', 'n. 报纸', 404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'party', 'n. 政党,聚会', 405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'data', 'n. 数据,资料', 406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coal', 'n. 煤', 407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'combine', 'v. 联合,使结合', 408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'happen', 'v. 发生,碰巧,出现', 409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'five', 'num. 五,五个', 410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cretaceous', 'n&a. 白垩纪(的)', 411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'book', 'n. 书', 412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quite', 'adv. 相当,完全,十分', 413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'already', 'adv. 已经', 414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nearly', 'adv. 几乎,差不多', 415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collect', 'v. 收集', 416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sand', 'n. 沙,沙子', 417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hot', 'adj. 热的,辣的,强烈的', 418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrestrial', 'adj. 陆地的', 419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leaf', 'n. 叶子', 420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sequence', 'n. 次序,顺序', 421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'star', 'n. 星,明星 v. 以星状物装饰,变成演员', 422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'estimate', 'n&v. 估计,估价', 423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drill', 'n. 钻子 v. 练习,钻孔', 424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transport', 'n&v. 运输', 425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'groundwater', 'n. 地下水', 426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'international', 'adj. 国际的,世界的', 427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'serve', 'v. 服务,担任', 428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'favor', 'n. 好感 v. 偏爱,支持', 429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'root', 'n. 根 v. 生根,扎根', 430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'huge', 'adj. 巨大的,庞大的', 431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'put', 'v. 放,安置', 432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whale', 'n. 鲸 v. 捕鲸', 433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exchange', 'v&n. 交换,兑换', 434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ecosystem', 'n. 生态系统', 435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distance', 'n. 距离,路程', 436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assume', 'v. 假定,设想', 437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'egg', 'n. 蛋', 438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opinion', 'n. 意见,看法', 439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'principle', 'n. 原理,原则', 440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'global', 'adj. 全球性的,总的', 441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cause', 'v. 引起,使发生 n. 原因', 442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eye', 'n. 眼睛', 443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'introductory', 'adj. 引导的,介绍的', 444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weight', 'n. 重量,负担 v. 加重量于', 445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variation', 'n. 变化,变动', 446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sculpture', 'n. 雕塑,雕刻', 447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'student', 'n. 学生', 448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bacteria', 'n. 细菌', 449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'presence', 'n. 出席,存在', 450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accept', 'v. 接受,承认,同意', 451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accumulate', 'v. 积聚,堆积', 452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colony', 'n. 殖民地', 453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gradual', 'adj. 逐渐的,逐步的', 454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'piece', 'n. 片,块 v. 拼合(凑)', 455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solid', 'n. 固体', 456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'action', 'n. 行动,行为,作用', 457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'service', 'n. 公共设施,服务 v. 服务', 458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destroy', 'v. 破坏,毁灭,消灭', 459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relative', 'adj. 相对的,相关的 n. 亲属', 460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'military', 'adj. 军事的 n. 军队', 461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'memory', 'n. 记忆(力),回忆', 462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potential', 'adj. 潜在的 n. 潜能', 463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sign', 'n. 标记,符号 v. 做标记', 464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electricity', 'n. 电流,电', 465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dioxide', 'n. 二氧化物', 466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perform', 'v. 执行,履行,表演', 467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'situation', 'n. 情形,境遇', 468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evolution', 'n. 进化,发展,演变', 469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soon', 'adv. 不久,很快', 470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fill', 'v. 装满', 471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fort', 'n. 堡垒,要塞', 472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'content', 'n. 内容 v. 使满足,使安心', 473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'success', 'n. 成功,成就', 474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signal', 'n. 信号,标志 v. 发信号,标志着', 475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generation', 'n. 一代人(或产品),产生,发生', 476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vast', 'adj. 巨大的,辽阔的,大量的', 477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manufacture', 'vt&n. 制造,制造业[pl]产品', 478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compete', 'v. 竞争,比赛', 479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'link', 'v. 连接,联系 n. 联系', 480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blood', 'n. 血 v. 流血', 481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commercial', 'adj. 商业的,贸易的', 482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approach', 'v. 靠近,接近 n. 途径,方法', 483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predict', 'v. 预知,预言', 484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'step', 'n. (脚)步,步骤,台阶 v. 行走,踏上', 485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stand', 'v. 站,坐落,处于', 486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'release', 'vt&n. 释放,解脱', 487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plan', 'n. 计划 v. 计划,设计', 488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sample', 'n. 样品,样本 v. 采样,取样', 489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expansion', 'n. 膨胀,扩展,扩充', 490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extensive', 'adj. 广泛的,广阔的', 491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reveal', 'v. 揭露,显示', 492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helium', 'n. 氦', 493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regular', 'adj. 规则的,定期的', 494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'effort', 'n. 努力,成就', 495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mile', 'n. 英里', 496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irrigation', 'n. 灌溉', 497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'next', 'n&a. 下一个的 prep. 靠近', 498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'actual', 'adj. 实际的,真实的', 499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'egyptian', 'n&a. 埃及人(的)', 500);
