INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creep', 'vi.  缓慢行进； 爬行； 悄悄地移动', 12001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deciduous', 'adj.  落叶的； 非永久的， 短暂的', 12002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scholar', 'n.  学者； 奖学金获得者', 12003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contradictory', 'adj. 对立的，矛盾的；反驳的 n.  对立物； 矛盾因素', 12004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accompany', 'vt.  为…伴奏； 陪伴， 陪同； 伴随， 和…一起发生', 12005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immediate', 'adj.  即刻的； 当前的； 最接近的； 紧接的， 紧靠的', 12006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perspicuous', 'adj.  明白易懂的； 明了的', 12007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beneficial', 'adj.  有益的， 有利的', 12008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blame', 'vt. 谴责，责备 n.  过失， 责备； 责任', 12009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confusion', 'n.  困惑； 混乱， 混淆', 12010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'platitude', 'n.  陈词滥调， 老生常谈', 12011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auditorium', 'n.  礼堂； 观众席', 12012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'session', 'n.  会议； 开庭； 开庭期； 一节', 12013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tactile', 'adj.  触觉的； 有触觉的； 可感触的', 12014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extrinsic', 'adj.  外来的， 外在的， 非本质的', 12015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bland', 'adj.  平淡的， 乏味的； 清淡的； 沉稳的', 12016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microbe', 'n.  微生物， 细菌', 12017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reception', 'n.  招待会； 反响； 接纳， 接待； 接收', 12018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sole', 'adj. 单独的；唯一的 n.  鞋底， 脚底', 12019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lumber', 'v. 笨拙地移动；迫使担负 n.  木材， 木料； 杂物', 12020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sledding', 'n.  进展', 12021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solo', 'adv. 独自，单独地 adj. 单独的；独唱的，独奏的 n.  独唱， 独奏， 独舞', 12022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monitor', 'vt. 监控；调节 n.  显示器； 监视器； 班长', 12023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tuition', 'n.  学费； 教学， 讲授', 12024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Fahrenheit', 'adj.  华氏温度的 n. 华氏温度计', 12025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tangible', 'adj.  可触摸的， 可感知的； 明确的， 确凿的； 有形的， 实际的', 12026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congest', 'v.  充满， 拥塞； 充血', 12027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postage', 'n.  邮资， 邮费', 12028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tame', 'adj. 驯服的；沉闷的，乏味的 vt.  驯化； 控制并利用', 12029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cavern', 'n.  大洞穴， 大山洞', 12030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'material', 'adj.  物质的， 身体上的； 重要的； 实质性的， 客观存在的 n. 材料，原料；素材，资料', 12031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adjoin', 'v.  贴近， 紧挨， 毗连', 12032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spectacular', 'adj. 壮观的，引人注目的 n.  壮观的场面； 壮观的演出', 12033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peculiar', 'adj.  独特的； 罕见的； 奇怪的， 古怪的', 12034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hue', 'n.  颜色； 色度， 色调； 信仰， 观点； 形式， 样子', 12035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idiom', 'n.  习惯用语； 术语； 风格， 特色', 12036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diplomat', 'n.  外交官； 有手腕的人', 12037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landmass', 'n.  大片陆地', 12038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'president', 'n.  总统， 校长， 主席', 12039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'muscular', 'adj.  肌肉的； 肌肉发达的； 强健的， 强壮的', 12040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staple', 'n. 主要产品；原材料；主食；订书钉', 12041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'memo', 'n.  备忘录', 12042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artifice', 'n.  诡计， 奸计； 策略', 12043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaborate', 'v.  协作， 合作； 勾结， 通敌', 12044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaborator', 'n.  合作者， 协作者； 通敌者', 12045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superficial', 'adj.  肤浅的， 浅薄的； 表面的， 外表的， 外层的', 12046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'executive', 'adj.  执行的， 实施的； 行政的 n. 执行者；管理人员；行政负责人', 12047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melt', 'v.  融化， 熔化； 溶化； 消散', 12048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hook', 'v. 连接到无线电设备；勾住 n.  钩， 吊钩； 钩状物', 12049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stadium', 'n.  竞走场； 运动场', 12050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refrigerate', 'vt.  冷冻， 冷藏； 使冷却， 使变冷', 12051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'casualty', 'n.  伤亡事故； 伤亡', 12052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spatial', 'adj.  空间的', 12053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gauge', 'n. 标准，规格；测量仪表，计量器 vt.  测量， 度量', 12054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'belt', 'n.  地带， 地区； 腰带， 皮带； 带状物', 12055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ridicule', 'vt. 嘲笑，奚落 n.  嘲笑， 奚落', 12056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protest', 'v.  抗议， 反对 n.  抗议， 反对', 12057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensitive', 'adj.  敏感的； 灵敏的', 12058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacant', 'adj.  空的； 闲置的； 茫然的， 空虚的', 12059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hoof', 'n.  蹄', 12060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afford', 'v.  买得起， 担负得起； 冒险做； 提供， 给予', 12061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'underground', 'adv.  在地下， 往地下； 秘密地， 不公开地 adj.  地下的； 秘密的， 不公开的 记 组合词： under + ground → 地下的', 12062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sieve', 'n. 筛子；漏勺 vt.  筛， 滤', 12063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appease', 'vt.  平息； 安抚， 抚慰； 绥靖', 12064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reddish', 'adj.  微红的', 12065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impede', 'vt.  妨碍， 阻碍， 阻止', 12066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acting', 'adj. 代理的 n.  演戏， 表演', 12067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'machinery', 'n.  〈总称〉机器， 机械； 机构', 12068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shield', 'n. 防护物；盾 vt.  保护', 12069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anatomy', 'n.  解剖； 解剖构造； 剖析', 12070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deliver', 'v.  传送， 传递； 发表， 宣布； 履行诺言； 移交， 交出； 接生', 12071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instantaneous', 'adj.  瞬间的， 即刻的， 立即的', 12072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phenomenon', 'n.  现象， 迹象； 非凡的人', 12073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quarterly', 'adv. 按季度，一季一次 adj.  季度的， 每季一次的 n. 季刊', 12074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notify', 'vt.  通报', 12075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smirk', 'vi.  假笑， 得意地笑', 12076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barbecue', 'v.  在烤架上烧烤 n. 烧烤野餐；金属烤架', 12077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abbey', 'n.  修道院； 大教堂', 12078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alienable', 'adj.  可转让的', 12079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buoyant', 'adj.  有浮力的， 漂浮的； 轻快的， 快乐的； 繁荣的； 看涨的', 12080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrepid', 'adj.  勇敢的， 无畏的', 12081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generalize', 'v.  概括， 归纳； 推广', 12082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accredit', 'vt.  委任， 授权； 把…归于； 正式认可', 12083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nourish', 'vt.  滋养； 养育', 12084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faucet', 'n.  龙头， 旋塞', 12085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lengthen', 'v.  延长， 变长', 12086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unconsolidated', 'adj.  松散的， 疏松的', 12087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strike', 'v. 碰，撞，撞击；侵袭；突然想到；给…以深刻印象；罢工；敲响 n.  罢工； 袭击', 12088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subdue', 'vt.  制服， 征服； 抑制， 克制', 12089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allege', 'vt.  断言， 宣称', 12090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'positive', 'adj.  肯定的； 积极的； 确凿的； 自信的， 乐观的； 正电的', 12091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trigger', 'vt. 引发，导致 n.  扳机', 12092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'segregate', 'vt.  隔离， 使分开', 12093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maize', 'n.  玉米', 12094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meticulous', 'adj.  细心的， 小心翼翼的', 12095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rental', 'adj. 租用的；出租的 n.  租金额； 租赁， 出租', 12096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prospect', 'v.  勘探， 勘察 n. 前景，前途；可能性；景象；期望', 12097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radar', 'n.  雷达', 12098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'withhold', 'vt.  拒绝给， 不给； 抑制； 忍住', 12099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinetic', 'adj.  运动的， 运动引起的； 动力学的', 12100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specialize', 'v.  专攻； 专用于', 12101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rotate', 'v.  转动， 旋转； 轮流', 12102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instance', 'n.  例子， 事例', 12103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consonant', 'adj. 和谐的，协调的，符合的 n.  辅音', 12104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engulf', 'vt.  吞没', 12105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inheritance', 'n.  遗产， 继承物； 继承； 遗传', 12106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reptile', 'n.  爬行动物， 爬虫类； 卑鄙的人', 12107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cassette', 'n.  盒式录音带', 12108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receptive', 'adj.  接受得快的； 善于接受的， 能接纳的', 12109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blade', 'n.  刀刃， 刀片； 叶片； 草叶； 桨叶', 12110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solution', 'n.  溶液； 解答， 解决', 12111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foreshorten', 'vt.  用透视法缩小； 缩短， 节略', 12112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diverge', 'vi.  分开， 叉开； 分歧； 偏离', 12113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opponent', 'adj.  对立的， 反对的， 对抗的 n. 敌手，对手，反对者', 12114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accelerate', 'v.  加快， 加速', 12115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emblem', 'n.  徽章； 标记， 象征', 12116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regardless', 'adv.  不顾， 不管', 12117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confiscate', 'vt.  没收， 充公， 征用', 12118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'filial', 'adj.  子女的； 子孙后代的', 12119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barge', 'v. 冲撞，乱闯 n.  驳船', 12120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turtle', 'n.  龟， 海龟', 12121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorology', 'n.  气象学', 12122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occur', 'vi.  发生， 出现； 存在于', 12123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illustrate', 'vt.  说明， 解释； 加插图于； 显示…存在', 12124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scuba', 'n.  水中呼吸器， 水肺', 12125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'definitive', 'adj. 确定的，最后的，决定性的；', 12126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breeze', 'vi.  飘然移动 n. 微风，和风', 12127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trash', 'n. 无价值之物，废物；拙劣的文学作品；没用的人 vt.  捣毁， 破坏', 12128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'horn', 'n.  角； 号角， 喇叭', 12129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'troupe', 'n.  剧团； 马戏团； 芭蕾舞团', 12130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transit', 'n.  运输， 运送； 中转； 转变； 交通运输系统', 12131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sore', 'adj. 疼痛的；恼火的 n.  疮口， 痛处', 12132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'position', 'vt. 安置 n.  位置； 职位； 立场； 姿势， 姿态； 见解', 12133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curtail', 'vt.  缩短， 缩减， 削减', 12134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glow', 'vi. 发光；发红，发热；洋溢 n.  暗淡的光； 容光焕发； 喜悦', 12135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patent', 'adj.  有专利的； 显而易见的 vt. 取得专利权 n.  专利权', 12136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sheath', 'n.  鞘， 外壳； 套； 护皮； 紧身连衣裙', 12137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollen', 'n.  花粉', 12138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remodel', 'vt.  重新塑造， 改造； 改编； 改变', 12139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'groove', 'n.  沟； 槽； 唱片上的纹路', 12140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'certificate', 'n.  证书， 证明书； 文凭， 结业证书', 12141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dispersal', 'n.  疏散； 散布， 散开', 12142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quantum', 'n. 量子', 12143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'racket', 'n.  球拍； 喧嚷， 吵闹； 勒索， 诈骗', 12144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mess', 'n. 肮脏，杂乱；混乱，困境 vt.  弄脏， 弄乱； 搞糟', 12145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sour', 'v. 变酸；变馊；变坏，恶化 adj.  酸的； 馊的； 乖戾的， 尖酸刻薄的； 酸痛的', 12146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transform', 'vt.  使变形； 改造， 改革； 转换', 12147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnitude', 'n.  巨大； 重要性； 星等， 星球的亮度', 12148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genuine', 'adj.  真的， 非人造的； 真诚的， 诚实的', 12149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agitate', 'v.  鼓动， 煽动； 激怒， 使激动， 使不安； 搅动', 12150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microwave', 'n.  微波； 微波炉', 12151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gorilla', 'n.  大猩猩', 12152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immune', 'adj.  免疫的， 有免疫力的； 不受影响的； 免除的， 豁免的', 12153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brochure', 'n.  小册子， 说明书', 12154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'downside', 'n.  缺点， 负面； 底侧； 下降趋势', 12155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equation', 'n.  等式， 方程式； 等同， 相等； 均衡', 12156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impressive', 'adj.  给人深刻印象的； 感人的', 12157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prospector', 'n.  勘探者， 采矿者', 12158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compound', 'n. 化合物， vt.  使恶化， 使加重； 混合', 12159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discredit', 'vt. 使丧失声誉；使怀疑 n.  名誉丧失', 12160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extraordinary', 'adj.  特别的； 非凡的', 12161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spawn', 'v. 产卵；产生，促成 n.  卵', 12162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensory', 'adj.  感觉的， 感官的', 12163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puzzle', 'n. 难题，谜 vt.  迷惑， 使困惑', 12164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mere', 'adj.  仅仅的， 纯粹的', 12165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suburb', 'n.  市郊， 郊区', 12166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taut', 'adj.  绷紧的； 肌肉结实的； 结构严谨的， 紧凑的', 12167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simplify', 'vt.  简化， 使简单， 使单纯', 12168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lubricant', 'n.  润滑剂', 12169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glue', 'vt. 胶合，黏合；紧附于 n.  胶， 胶水', 12170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orbital', 'adj.  轨道的', 12171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solder', 'vt. 焊接 n.  焊料， 焊锡', 12172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'envelop', 'vt.  包围', 12173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firm', 'adj.  结实的； 坚定的， 坚决的 n. 公司', 12174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reflect', 'v.  反射， 映现； 显示， 表明； 仔细考虑， 深思', 12175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adventitious', 'adj.  偶然的， 偶发的', 12176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ongoing', 'adj. 正在进行的；不间断的；继续存在的 n.  前进， 发展', 12177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outfit', 'n.  全套装备； 全套服装', 12178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ignorant', 'adj.  无知的， 愚昧的； 无知觉的', 12179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extort', 'vt.  勒索， 敲诈， 强夺', 12180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trample', 'v.  踩碎； 践踏， 摧残', 12181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negligible', 'adj.  可以忽略的， 微不足道的； 无关紧要的', 12182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'setback', 'n.  挫折， 阻碍； 倒退', 12183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spray', 'n. 浪花；飞沫；', 12184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distinguish', 'v.  区别， 辨别； 使有别于， 成为…的特征； 看清， 听出； 使杰出， 使著名', 12185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primordial', 'adj.  原始的， 最初的； 基本的', 12186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'husbandry', 'n.  耕种， 务农， 农牧业', 12187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haircut', 'n.  理发', 12188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decorative', 'adj.  装饰性的， 做装饰用的', 12189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pointed', 'adj.  尖的， 尖角的； 尖锐的， 尖刻的', 12190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enthusiastic', 'adj.  热情的， 热心的', 12191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elongate', 'v.  延长， 伸长', 12192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symptom', 'n.  症状； 征兆', 12193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fray', 'vi. 磨损，磨破；烦躁，恼火 n.  争斗', 12194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thereby', 'adv.  因此， 从而', 12195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wield', 'vt.  支配， 掌权， 行使', 12196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disastrous', 'adj.  灾难性的', 12197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impulse', 'n.  冲动， 一时的念头； 刺激， 推动力； 脉冲', 12198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crystallize', 'v.  结晶； 明确', 12199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subspecies', 'n.  亚种', 12200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shower', 'v.  淋浴； 下阵雨； 洒落， 纷纷降落； 抛撒 n. 阵雨，暴雨；淋浴；一阵，一大批', 12201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infectious', 'adj.  传染性的， 传染病的； 有感染力的', 12202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concur', 'v.  同时发生； 意见一致', 12203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nevertheless', 'adv.  然而， 不过', 12204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prominent', 'adj.  卓著的， 杰出的； 突起的， 凸出的', 12205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insulin', 'n.  胰岛素', 12206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ironic', 'adj.  说反话的， 讽刺的； 出乎意料的', 12207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fundamental', 'adj. 基础的，基本的，根本的 n.  基本原则； 基础', 12208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hieratic', 'adj. 僧侣的；', 12209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entitle', 'vt.  使…有权； 给题名', 12210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monotony', 'n.  单调， 千篇一律', 12211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outline', 'n.  轮廓； 概要， 大纲 vt.  描绘； 略述', 12212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counselor', 'n.  顾问； 律师', 12213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fade', 'v.  褪色； 凋谢； 逐渐消失', 12214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overdue', 'adj.  过期未付的， 逾期的； 过度的， 过火的； 迟到的， 延误的', 12215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nominal', 'adj.  名义上的； 微不足道的', 12216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excess', 'adj.  过量的； 额外的 n.  过度， 超过', 12217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perspective', 'n.  展望； 观点， 看法； 远景； 透视图， 透视法； 前途', 12218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'galaxy', 'n.  星系； [G-]银河系， 银河； 群英', 12219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invade', 'v.  侵入， 侵略； 侵扰', 12220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intervening', 'adj.  介于中间的， 发生于期间的', 12221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clump', 'v.  聚集， 成群； 以沉重的脚步行走 n. 丛，簇，束；块，团；群，组', 12222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thorough', 'adj.  彻底的； 详尽的； 一丝不苟的', 12223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'democracy', 'n.  民主政体， 民主制度； 民主国家； 民主精神', 12224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peninsula', 'n.  半岛', 12225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evolve', 'v.  发展； 进化', 12226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congratulation', 'n.  祝贺， 道喜', 12227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abandon', 'vt. 离弃，放弃 n.  放纵， 放任', 12228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extol', 'vt.  赞美， 颂扬', 12229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'household', 'adj. 家庭的，家用的；家喻户晓的 n.  家庭', 12230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adverse', 'adj.  负面的； 不利的； 逆的', 12231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bulletin', 'n.  新闻简报； 公告， 布告； 简报', 12232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ratio', 'n.  比， 比率', 12233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'junction', 'n.  交叉点， 汇合处； 连接， 接合', 12234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electrolysis', 'n.  电解作用； 电解术', 12235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bandanna', 'n.  色彩鲜艳的围巾', 12236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instinct', 'n.  本能， 直觉； 生性， 天性', 12237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gourmet', 'adj. 美味的 n.  美食家', 12238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reputation', 'n.  名声， 声望， 名誉', 12239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spike', 'n.  长钉， 大钉； 猛增， 急升', 12240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrub', 'n.  灌木', 12241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'presentation', 'n.  提供， 显示； 介绍， 陈述； 赠送； 表演', 12242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genesis', 'n.  起源， 开端', 12243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subliminal', 'adj.  下意识的， 潜意识的', 12244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engrave', 'vt.  雕刻； 铭刻', 12245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tavern', 'n.  小旅馆， 客栈； 小酒店', 12246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glimmer', 'vi.  发微光； 隐约出现 n. 闪烁的微光；隐约的迹象；一丝，一线', 12247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awkward', 'adj.  别扭的； 笨拙的； 难处理的， 棘手的； 难操纵的', 12248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adhesive', 'adj.  带黏性的 n. 胶合剂', 12249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monumental', 'adj.  纪念碑的； 不朽的', 12250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ruin', 'vt. 破坏，毁灭；使破产 n. 毁灭，毁坏；', 12251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spill', 'v. 溢出，溅出；蜂拥而出 n.  溢出， 泄漏', 12252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'celebrate', 'v.  赞美； 庆祝', 12253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cradle', 'n.  摇篮； 发源地', 12254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abut', 'v.  邻接， 毗邻', 12255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'folkway', 'n.  社会风俗', 12256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mountainous', 'adj.  多山的； 巨大的', 12257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laboratory', 'n.  实验室， 研究室', 12258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geometric', 'adj.  几何的， 几何学的', 12259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Latin', 'adj. 拉丁的；拉丁语的 n.  拉丁语', 12260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inspect', 'vt.  检查， 视察', 12261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'campaign', 'vi. 竞选；参加战斗 n.  竞选活动； 活动； 战役', 12262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vital', 'adj.  生死攸关的； 至关重要的； 精力充沛的， 有活力的', 12263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conflict', 'vi.  冲突； 不一致； 争论 n.  冲突； 争论', 12264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engraving', 'n.  雕刻术， 刻版术； 版画', 12265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rough', 'adj. 粗糙不平的；粗暴的；艰难的 n.  高低不平的地面', 12266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lawsuit', 'n.  诉讼', 12267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sequential', 'adj.  序列的； 连续的； 随之而来的', 12268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detect', 'vt.  发现， 察觉； 探测； 查明', 12269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'derivative', 'adj. 派生的，引出的；无创意的 n.  派生词， 衍生词； 派生物', 12270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amateur', 'adj.  业余爱好的； 业余的 n. 业余爱好者；外行', 12271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rodeo', 'n.  牛仔竞技表演', 12272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assistance', 'n.  帮助， 援助', 12273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commerce', 'n.  贸易， 商业； 交往， 交流', 12274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canvass', 'v.  游说， 拉选票； 细查', 12275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gulf', 'n.  海湾； 分歧， 隔阂， 鸿沟', 12276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'causal', 'adj.  原因的， 因果关系的', 12277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tectonics', 'n.  构造地质学', 12278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wonder', 'v. 诧异；纳闷，想知道 n.  惊奇， 惊异； 奇迹， 奇事', 12279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mansion', 'n.  公寓， 府邸； 大厦', 12280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gull', 'n.  鸥， 海鸥', 12281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'summary', 'adj.  概括的， 概要的； 即刻的， 立即的 n. 摘要，概要', 12282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illusory', 'adj.  虚幻的， 幻觉的', 12283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nickel', 'n.  镍； 五分镍币', 12284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accustom', 'vt.  使习惯于', 12285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entail', 'vt.  牵涉； 使必要， 需要', 12286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inferior', 'adj. 劣等的，较差的；次要的；级别低的 n.  下级， 下属， 晚辈', 12287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dramatic', 'adj.  戏剧的； 引人注目的； 突然的， 巨大的； 戏剧性的', 12288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spinet', 'n.  小型立式钢琴', 12289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mosquito', 'n.  蚊子', 12290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parasite', 'n.  寄生物； 食客', 12291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artificial', 'adj.  人工的， 人造的， 假的； 矫揉造作的， 假装', 12292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deficiency', 'n.  不足， 缺乏', 12293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imaginary', 'adj.  想象中的， 虚构的， 假想的', 12294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'removal', 'n.  除去； 移动， 搬迁', 12295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comment', 'v&n.  评论； 注释', 12296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vaporize', 'v.  蒸发， 汽化', 12297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transcend', 'vt.  超越', 12298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spiny', 'adj.  长满刺的， 多刺的， 带刺的； 棘手的', 12299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronological', 'adj.  按年代顺序排列的， 年代学的', 12300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanitarian', 'adj. 人道主义的，慈善的 n.  人道主义者， 博爱者， 慈善家', 12301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'employ', 'vt. 用，使用；雇用 n.  受雇， 雇用', 12302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surcharge', 'n. 额外费用，增收费，附加费 vt.  收取额外费用', 12303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sturdy', 'adj.  健壮的， 结实的； 稳固的； 顽强的', 12304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fable', 'n.  寓言； 谎言', 12305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balcony', 'n.  阳台； 楼厅， 楼座', 12306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instill', 'vt.  慢慢灌输； 逐渐培养', 12307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consist', 'vi.  在于， 存在于； 由…组成， 由…构成', 12308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'palatable', 'adj.  美味的， 可口的； 合意的， 认可的', 12309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compatible', 'adj.  协调的， 一致的； 兼容的； 能和睦相处的', 12310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'critic', 'n.  评论家， 批评家； 吹毛求疵者', 12311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenement', 'n.  廉租公寓', 12312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photosynthesis', 'n.  光合作用', 12313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sidebar', 'n.  补充报道', 12314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crest', 'v.  达到顶点 n. 顶峰，顶点；浪尖；羽冠', 12315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'profession', 'n.  职业； 同行； 专业； 宣称', 12316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deplore', 'vt.  悲叹， 哀叹， 公开谴责', 12317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compress', 'v.  压缩； 缩短； 浓缩', 12318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grimly', 'adv.  冷酷地； 严肃地； 坚定地', 12319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cherish', 'vt.  爱护， 珍爱； 怀有， 抱有', 12320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outlive', 'vt.  比…长命， 比…耐久', 12321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patronize', 'v.  以高人一等的态度对待； 光顾； 赞助， 资助', 12322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eminent', 'adj.  显著的， 杰出的', 12323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'underneath', 'adv.  在下面 prep. 在…下面', 12324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spectrum', 'n.  谱， 光谱， 频谱； 范围， 幅度', 12325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prolong', 'vt.  拉长， 延长', 12326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refund', 'n.  偿还额； 退款 vt.  退还， 偿付', 12327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distress', 'n. 痛苦，忧伤；贫困，窘迫；遇难 vt.  使痛苦， 使悲伤， 使忧虑', 12328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remnant', 'n.  残余物； 布头； 遗迹', 12329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'broadcast', 'v. 广播，播放 n.  广播， 广播节目', 12330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compressible', 'adj.  可压缩的', 12331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steep', 'adj. 陡的，陡峭的；急剧的；过高的 v.  浸泡； 沉浸', 12332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classical', 'adj.  经典的， 古典的', 12333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immunity', 'n.  免疫力； 保护； 免除， 豁免', 12334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'privilege', 'vt. 给予特权，特别优待 n.  特权， 特殊待遇； 特殊利益， 优惠； 荣耀， 荣幸', 12335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shroud', 'vt. 隐藏，遮蔽 n.  裹尸布， 寿衣； 遮蔽物', 12336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substitute', 'v.  代替 n. 代替者，代替品', 12337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'criss-cross', 'v. 构成十字形图案；交叉往来 adj.  纵横交错的', 12338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uniform', 'adj.  统一的； 均匀的 n. 制服', 12339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choppy', 'adj.  波浪起伏的， 不平静的； 不连贯的， 支离破碎的', 12340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blaze', 'vi.  燃烧， 着火； 发光， 放光彩； 怒视 n. 火焰；光辉，强烈的光；迸发', 12341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bountiful', 'adj.  慷慨的； 大量的， 充足的', 12342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meager', 'adj.  不足的， 贫乏的； 消瘦的', 12343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scatter', 'v.  使分散， 驱散， 散开； 撒播', 12344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'violate', 'vt.  违反， 违背； 亵渎； 侵犯， 干扰', 12345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'methanol', 'n.  甲醇', 12346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steer', 'v. 驾驶，为…操舵；引导 n.  食用公牛', 12347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pheromone', 'n.  信息素', 12348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collective', 'adj. 集体的，共同的 n.  集体， 共同体', 12349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buddy', 'n.  密友； 搭档， 伙伴', 12350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undergo', 'vt.  经历； 遭受', 12351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outlying', 'adj.  边远的， 偏僻的； 无关的， 题外的', 12352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delineate', 'vt.  描绘， 描述； 解释', 12353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agency', 'n.  代理处， 经销机构； 专门机构', 12354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coupon', 'n.  礼券， 优惠券； 配给券， 票证', 12355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multitude', 'n.  大量， 众多； 群众， 民众； 人群', 12356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inhabit', 'vt.  居住于， 栖居于', 12357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'innate', 'adj.  天生的， 固有的； 内在的， 直觉的', 12358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'siege', 'n.  包围， 围困； 封锁', 12359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gratify', 'vt.  使满意， 使高兴； 满足', 12360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fascinating', 'adj.  迷人的， 醉人的', 12361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abstract', 'adj. 抽象的；抽象派的 n.  摘要， 梗概 vt.  做…的摘要； 提取', 12362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agenda', 'n.  议程， 议程表', 12363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liquid', 'adj. 液体的，液态的，流体的；清澈的；流畅的 n.  液体； 液态', 12364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quasar', 'n.  类星体', 12365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anonymous', 'adj.  匿名的， 不具名的； 无特色的， 无个性特征的', 12366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fake', 'v.  伪造； 伪装', 12367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'span', 'n. 跨度；持续时间 vt.  跨越； 持续， 贯穿； 包括', 12368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'desegregate', 'v.  废除种族隔离', 12369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'girder', 'n.  主梁， 大梁', 12370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bizarre', 'adj.  奇形怪状的， 古怪可笑的， 怪诞的', 12371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perfect', 'adj.  完美的， 理想的； 完全的， 十足的 vt.  使完美， 使熟练', 12372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prefer', 'v.  更喜欢， 宁愿', 12373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'astronomical', 'adj.  天文学的； 极大的， 庞大的', 12374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ascribe', 'vt.  把…归于； 归咎于', 12375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pole', 'n.  地极； 磁极， 电极； 柱， 杆， 杖； 极端', 12376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minority', 'n.  少数； 少数民族', 12377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allure', 'n&v.  诱惑， 吸引', 12378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reference', 'n.  提到， 论及， 涉及； 引文， 参考； 介绍', 12379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conspiracy', 'n.  密谋； 阴谋', 12380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chamber', 'n.  会议厅； 议院； 洞穴； 腔， 室； 房间', 12381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arrange', 'v.  布置； 安排， 筹备', 12382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aristocratic', 'adj.  贵族的， 有贵族气派的', 12383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trivialize', 'vt.  使显得琐碎； 轻视', 12384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depart', 'vi.  离开； 背离', 12385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exponent', 'n.  解释者； 倡导者， 拥护者； 指数， 幂', 12386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accordion', 'n.  手风琴', 12387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incongruity', 'n.  不一致， 不和谐', 12388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solicit', 'v.  恳请； 乞求； 征求； 勾引； 招揽', 12389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhyme', 'v. 押韵；和…同韵 n.  押韵； 同韵词， 押韵词', 12390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fossil', 'adj. 化石的；陈腐的 n.  化石； 老顽固', 12391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disciple', 'n.  门徒， 弟子， 追随者', 12392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collision', 'n.  碰撞； 冲突， 抵触', 12393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manufacture', 'vt. 大量制造，成批生产；捏造 n. 大量制造；', 12394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arthritis', 'n.  关节炎', 12395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'focal', 'adj.  焦点的； 很重要的', 12396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spinning', 'adj. 旋转的 n.  纺纱', 12397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squid', 'n.  鱿鱼， 枪乌贼', 12398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slogan', 'n.  标语， 口号； 广告语', 12399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bosom', 'n.  胸部， 乳房； 胸怀， 内心', 12400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tract', 'n.  地域； 领域； 传单， 小册子； 大片', 12401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mercury', 'n.  [M-]水星； 水银， 汞', 12402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interact', 'vi.  相互作用； 互相配合', 12403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'powder', 'n.  粉， 粉末； 散剂； 火药， 炸药', 12404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bestow', 'vt.  赠与， 授予， 献给', 12405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggregate', 'n.  聚集物； 总计 vt.  聚集； 总计', 12406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'differential', 'adj. 差别的，有区别的；微分的 n.  差别， 差异； 微分', 12407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forsake', 'vt.  遗弃， 放弃， 抛弃', 12408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rust', 'v. 生锈 n.  锈， 铁锈； 锈病', 12409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trace', 'vt. 查出，找到；追溯；探索；描摹；追述 n.  痕迹； 微量， 少许； 扫描线', 12410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stylized', 'adj.  非写实的； 程式化的', 12411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'array', 'n. 一系列；阵列 vt.  布置， 排列； 部署', 12412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrorism', 'n.  恐怖主义', 12413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nominee', 'n.  被提名者， 被任命者', 12414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discriminate', 'v.  区别； 歧视', 12415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'camouflage', 'n&vt.  掩饰， 伪装', 12416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'track', 'v.  跟踪， 追踪 n. 跑道；小路；轨迹；足迹', 12417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'annex', 'vt.  兼并； 附加', 12418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enslave', 'vt.  奴役', 12419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'centennial', 'n.  百年纪念', 12420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monetary', 'adj.  金钱的， 货币的', 12421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rush', 'v. 冲，突进；奔，急速流动；仓促从事；突袭 n. 冲，急速行进；匆忙；', 12422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demolish', 'vt.  拆除； 破坏； 驳倒， 推翻', 12423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shellfish', 'n.  贝类， 有壳的水生动物', 12424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trade', 'v.  交易， 买卖； 互相交换 n. 贸易，商业；交易；职业，行业', 12425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gush', 'v. 滔滔不绝地说；喷涌 n.  喷出， 涌出； 迸发， 发作', 12426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'derivation', 'n.  起源， 发源； 派生', 12427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spew', 'v. 喷涌；射出；呕吐，呕出 n.  喷出物', 12428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comic', 'adj. 可笑的，滑稽的；喜剧的 n.  喜剧演员', 12429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weave', 'v. 迂回行进；编织；编造，编纂 n.  编法， 织法', 12430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'normally', 'adv.  通常地； 正常地', 12431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vague', 'adj.  模糊的； 不明确的', 12432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fare', 'vi. 进展 n.  费用', 12433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'juridical', 'adj.  法律的， 司法的', 12434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ephemeral', 'adj.  短暂的， 转瞬即逝的', 12435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accuracy', 'n.  准确， 精确', 12436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curtsy', 'vi.  行屈膝礼 n. 屈膝礼', 12437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'setting', 'n.  环境； 背景； 布景； 曲； 底座， 底板', 12438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'score', 'v. 评分；划；获胜，成功 n.  得分， 分数； 乐谱； 抓痕， 划痕； 二十', 12439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quote', 'v. 引用；', 12440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unanimous', 'adj.  全体一致的， 一致同意的', 12441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quota', 'n.  配额， 限额， 定额', 12442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scorn', 'v.  轻蔑， 鄙视； 不屑于 n. 轻蔑，鄙视', 12443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thermal', 'adj. 热的，热量的；保暖的，防寒的 n.  上升的热气流', 12444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'percussion', 'n.  打击乐器', 12445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nationalism', 'n.  国家主义； 民族主义， 民族优越感', 12446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sulfur', 'n.  硫； 硫黄', 12447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrain', 'n.  地势， 地形； 地带', 12448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'navigate', 'v.  航行， 横渡； 导航； 设法完成', 12449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'culpable', 'adj.  有罪的； 该谴责的， 难辞其咎的', 12450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'raw', 'adj.  生的， 未烹制的； 自然状态的， 未经加工的； 生疏的， 无经验的； 粗犷的； 原始的， 未经处理的', 12451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sprinkle', 'v. 撒，洒，喷 n.  少量', 12452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'backlighting', 'n.  逆光', 12453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'municipal', 'adj.  市政的； 内政的； 地方性的', 12454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'institute', 'vt. 设立；制定；开创 n.  研究所， 学院', 12455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endure', 'vt.  忍受， 忍耐； 持久， 持续', 12456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feign', 'vt.  装作， 假装； 伪造', 12457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poster', 'n.  海报， 招贴画； 发布消息的人', 12458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shortly', 'adv.  不久； 简要地； 不耐烦地', 12459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'criterion', 'n. 〔判断、决定的〕标准，准则', 12460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'essence', 'n.  本质， 精髓', 12461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pore', 'vi. 仔细阅读，审阅；审视 n.  气孔， 小孔', 12462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambient', 'adj.  周围的， 周围环境的； 产生轻松氛围的', 12463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insistence', 'n.  坚持， 坚决主张', 12464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manual', 'adj. 手工的；体力的 n.  手册， 指南', 12465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ornamental', 'adj. 装饰性的，装饰用的 n.  装饰物', 12466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sentimental', 'adj.  情感的； 伤感的， 多愁善感的', 12467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maneuver', 'v. 操纵，控制；耍花招 n.  策略； 花招', 12468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dual', 'adj.  双的， 二重的', 12469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retire', 'v.  退休， 引退， 退役； 退出； 撤退； 就寝', 12470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dexterous', 'adj.  惯用右手的； 灵巧的， 熟练的', 12471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aspect', 'n.  方面； 朝向， 方向； 外表， 外观', 12472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vegetarian', 'adj.  素食者的 n. 素食者', 12473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggressive', 'adj.  侵略的， 挑衅的； 强有力的； 敢作敢为的， 有进取心的', 12474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resilience', 'n.  弹力， 弹性； 复原力； 适应力', 12475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corona', 'n.  日冕， 日华； 光环', 12476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midterm', 'adj. 中间的，期中的 n.  期中考试； 中期； 期中', 12477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signify', 'v.  意味； 表示， 预示； 要紧， 有重要性', 12478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suction', 'n.  吸， 抽吸； 吸力', 12479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'holistic', 'adj.  整体的， 全面的； 功能整体性的', 12480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stratum', 'n. 岩层；地层', 12481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swing', 'v. 摆动，摇荡；突然转向，突然转身 n.  摆动， 摇摆； 秋千', 12482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turbulent', 'adj.  动乱的； 狂暴的， 汹涌的', 12483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overt', 'adj.  公开的， 非秘密的', 12484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invasion', 'n.  侵入， 侵略， 侵犯', 12485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forefront', 'n.  最前沿， 最前线； 中心', 12486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spin', 'v. 快速旋转；纺纱；吐丝；甩干衣服 n.  旋转', 12487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grocery', 'n.  杂货店； 杂货', 12488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shallow', 'adj. 浅的；', 12489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scout', 'v. 侦察；寻找；搜索 n.  侦察员； 侦察机； 童子军', 12490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edifice', 'n.  大厦， 宏伟的建筑物', 12491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'register', 'v&n.  登记， 注册', 12492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'persuasive', 'adj.  有说服力的， 让人信服的', 12493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'couple', 'n. 对，双；夫妇，情侣；几个人，几件事 vt.  连接， 结合', 12494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'communicate', 'v.  交流， 沟通； 传达， 传播； 通信', 12495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saddle', 'n. 马鞍；车座 vt.  给…备鞍', 12496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rural', 'adj.  乡村的， 农村的； 田园的', 12497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acclaim', 'n&vt.  喝彩， 称赞', 12498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concord', 'n.  和睦； 公约', 12499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acid', 'adj.  酸的， 酸味的； 尖刻的， 刻薄的 n. 酸，酸性物质', 12500);
