INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shock', 'v. 感到震惊', 1001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'disservice', 'n. 伤害，帮倒忙', 1002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ambitious', 'adj. 有雄心的，野心勃勃的', 1003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fancy', 'adj. 华丽的；别致的', 1004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accumulate', 'v. 积累，增加', 1005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fuss', 'n. 大惊小怪', 1006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ultimately', 'adv. 最后，最终', 1007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'showmanship', 'n. 主持演出的技巧', 1008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cancel', 'v. 取消', 1009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'regulate', 'v. 管理', 1010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'peer', 'n. 同龄人', 1011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'calculate', 'v. 计算', 1012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'virtually', 'adv. 几乎，差不多', 1013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accustom', 'v. 使习惯', 1014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'retailer', 'n. 零售商', 1015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'programmer', 'n. 程序设计员', 1016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'advice', 'n. 建议', 1017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'admiration', 'n. 钦佩，称赞', 1018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'courageous', 'adj. 有勇气的', 1019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'respectful', 'adj. 有礼貌的，尊重的', 1020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'makeup', 'n. 化妆品', 1021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reservation', 'n. 预定', 1022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apply', 'v. 申请；应用', 1023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'demonstrate', 'v. 证明；展示', 1024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'generation', 'n. 一代人；产生', 1025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chat', 'v. 聊天', 1026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ancient', 'adj. 古代的', 1027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evil', 'n. 邪恶，罪恶', 1028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'indifferent', 'adj. 冷漠的', 1029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'namely', 'adv. 即，也就是', 1030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'effect', 'n. 影响', 1031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'devote', 'v. 奉献，致力于', 1032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appointment', 'n. 约会', 1033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appoint', 'v. 任命，委派；约定，确定，指定', 1034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'resemble', 'v. 像，相似', 1035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assemble', 'v. 集合；组装；集合', 1036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expressiveness', 'n. 表达', 1037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'visibility', 'n. 能见度', 1038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distracted', 'adj. 分心的', 1039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'debt', 'n. 债务', 1040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'substitute', 'n. 代替者 v. 代替', 1041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'insecure', 'adj. 不安全的', 1042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chap', 'n. 小伙子，小家伙，家伙', 1043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'selective', 'adj. 选择的,精选的', 1044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compensation', 'n. 弥补，补偿', 1045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dilemma', 'n. 困境', 1046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'foreseeable', 'adj. 可以预见的', 1047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inadequacy', 'n. 不足', 1048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'guarantee', 'v. 担保 n. 保证，担保', 1049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discrimination', 'n. 歧视', 1050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intense', 'adj. 强烈的', 1051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'facilitate', 'v. 使便利，促进', 1052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mislead', 'v. 误导', 1053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reassess', 'v. 重新评估', 1054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'response', 'n. 反应', 1055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'essay', 'n. 散文，文章', 1056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stimulate', 'v. 刺激', 1057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dessert', 'n. 甜点', 1058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'peaceful', 'adj. 平静的；和平的', 1059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'regularly', 'adv. 定期地，有规律地', 1060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fascinate', 'v. 强烈地吸引，迷住', 1061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'durability', 'n. 持久', 1062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discover', 'v. 发现', 1063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'constitute', 'v. 组成', 1064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'administrative', 'adj. 管理的', 1065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tremble', 'v. 颤抖', 1066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ignorant', 'adj. 无知的', 1067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'decorate', 'v. 装饰', 1068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'acquire', 'v. 获得', 1069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'annual', 'adj. 每年的', 1070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'due', 'adj. 到期的', 1071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'situation', 'n. 情况', 1072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'archive', 'n. 档案馆，档案室；档案', 1073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'incomparable', 'adj. 无比的，无可匹敌的', 1074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'perspective', 'n. 视角，观点；远景', 1075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compete', 'v. 竞争', 1076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'joint', 'adj. 联合的', 1077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'overload', 'n. 负担太重', 1078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mechanic', 'n. 机械师', 1079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distinguish', 'v. 区别，区分', 1080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vote', 'v. 投票，选举', 1081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'everlasting', 'adj. 永恒的', 1082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'construction', 'n. 建筑', 1083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'aggressive', 'adj. 挑衅的，好斗的；有上进心的', 1084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'classification', 'n. 分类，级别', 1085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'melt', 'v. 融化', 1086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'detect', 'v. 觉察；检测', 1087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discourage', 'v. 阻止；使气馁', 1088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'combination', 'n. 联合，结合', 1089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grave', 'n. 坟墓', 1090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'malfunction', 'n. 失灵，故障', 1091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reduce', 'v. 减少', 1092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'respectively', 'adv. 各自地', 1093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'forefinger', 'n. 食指', 1094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wise', 'adj. 聪明的，有智慧的', 1095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'background', 'n. 背景', 1096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'symbol', 'n. 象征，标志', 1097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'quality', 'n. 品质', 1098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'repave', 'v. 再铺，重新铺砌', 1099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'downfall', 'n. （雨等的）大下特下', 1100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ring', 'n. 拳击台', 1101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'planet', 'n. 行星', 1102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pension', 'n. 养老金', 1103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'perception', 'n. 感知', 1104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'facility', 'n. 设施', 1105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'proportion', 'n. 比例，部分', 1106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'involve', 'v. 卷入，包含', 1107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'attempt', 'n. 尝试，试图 v. 尝试，试图', 1108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conventional', 'adj. 传统的', 1109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'detailed', 'adj. 细节的，详细的', 1110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interpretation', 'n. 阐释，说明', 1111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'guilt', 'n. 有罪，犯罪行为', 1112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'connectivity', 'n. 连接，联系', 1113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'behave', 'v. 表现', 1114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'instruct', 'v. 指导；教授；通知；命令；', 1115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'infinite', 'adj. 无限的', 1116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hazard', 'n. 危险', 1117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'undervalue', 'v. 低估', 1118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'specific', 'adj. 特定的，具体的', 1119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appealing', 'adj. 吸引人的', 1120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fitness', 'n. 健康', 1121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conclusion', 'n. 结论', 1122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'absent', 'adj. 缺席的', 1123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'antique', 'n. 古玩，古董', 1124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'myth', 'n. 神话', 1125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intervention', 'n. 干涉', 1126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'trace', 'n. 痕迹', 1127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'protest', 'v. 抗议', 1128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'refuel', 'v. （给）加油，加燃料', 1129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tackle', 'v. 处理', 1130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'finance', 'n. 财政 v. 资助', 1131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fine', 'v. 罚款', 1132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'indicate', 'v. 表明', 1133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dissatisfy', 'v. 不满意', 1134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expand', 'v. 扩大', 1135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spontaneous', 'adj. 自发的', 1136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'offense', 'n. 犯罪；冒犯', 1137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'abruptly', 'adv. 突然地', 1138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recycle', 'v. 循环，再利用', 1139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rude', 'adj. 粗鲁的', 1140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contribute', 'v. 捐款，贡献', 1141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'embarrass', 'v. 尴尬', 1142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'weaken', 'v. 减少，减弱', 1143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mineral', 'n. 矿物', 1144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sticky', 'adj. 粘的', 1145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'challenge', 'n. 挑战 . v. 质疑', 1146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'excess', 'n. 过量，过度', 1147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recruit', 'v. 招募，吸收 n. 新兵，新成员', 1148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'overstate', 'v. 夸张，夸大', 1149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'generalization', 'n. 概括', 1150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hub', 'n. 中心', 1151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conservative', 'adj. 保守的，传统的', 1152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'restock', 'v. 重新进货，再储存', 1153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'convict', 'v. 证明…有罪', 1154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'deepen', 'v. 使加深，加剧', 1155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tank', 'n. 油箱，水箱', 1156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'negative', 'adj. 消积的；否定的', 1157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accelerate', 'v. 加速', 1158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'territory', 'n. 领土，领域', 1159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impact', 'n. 影响', 1160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distraction', 'n. 分心；消遣', 1161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'resolve', 'v. 解决；下决心', 1162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'refuse', 'v. 拒绝', 1163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'soluble', 'adj. 可溶的；可以解决的', 1164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brave', 'adj. 勇敢的；极好的', 1165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hat', 'n. 帽子（一般指有边的）', 1166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beach', 'n. 海滩，湖滩，河滩', 1167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'authority', 'n. 当局，官方；权力', 1168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'roast', 'v. 烤，炙；烘', 1169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'amplify', 'v. 放大，扩大；增强', 1170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bulk', 'n. 大部分；体积，块头', 1171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'put', 'v. 放，摆；使处于', 1172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stable', 'adj. 稳定的，不变的', 1173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'certificate', 'n. 证书，证件，执照；（毕业）文凭，合格证书', 1174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dragon', 'n. 龙', 1175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'capable', 'adj. 有能力的；有才能的', 1176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'criticism', 'n. 批评；批判；评论', 1177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accommodation', 'n. 住处；工作场所', 1178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'imply', 'v. 暗示，意指', 1179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'December', 'n. 十二月', 1180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'president', 'n. 总统；（某组织的）最高权力人', 1181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lately', 'adv. 最近，不久前', 1182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'down', 'adv. 向下；在下面', 1183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'matter', 'n. 事情；物质 v. 要紧', 1184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lake', 'n. 湖', 1185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nor', 'conj. 既不…也不…；也不', 1186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bench', 'n. 长凳，条凳', 1187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rug', 'n. 小地毯；毛毯', 1188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mirror', 'n. 镜子 v. 与〔另一事物〕相似；反映', 1189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'draw', 'v. 画，划', 1190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'net', 'n. 网，网状物；互联网', 1191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scale', 'n. 天平，磅秤，秤', 1192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'outline', 'n. 轮廓；略图；大纲', 1193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'quiet', 'adj. 安静的；寂静的', 1194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'water', 'n. 水 v. 使湿，灌溉', 1195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nervous', 'adj. 神经的；易激动的', 1196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nevertheless', 'conj. 然而 adv. 仍然', 1197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assembly', 'n. 集合；集会；装配', 1198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fight', 'v. 打（仗）；斗争', 1199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'missing', 'adj. 失去的；缺掉的', 1200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lift', 'v. 提起，提高 n. 电梯', 1201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'refrigerator', 'n. 冰箱，冷藏库', 1202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dirty', 'adj. 脏的；下流的', 1203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rent', 'n. 租金 v. 出租', 1204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'convince', 'v. 使确信，使信服', 1205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'abroad', 'adv. （在）国外', 1206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'offend', 'v. 冒犯 v. 犯罪，违法', 1207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'belong', 'v. 属于', 1208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'arouse', 'v. 引起，唤起；唤醒', 1209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'admission', 'n. 承认；允许进入', 1210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'modify', 'v. 更改，修改', 1211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'express', 'v. 表示 n. 快车；快递', 1212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'imagine', 'v. 想象，设想', 1213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'infinite', 'adj. 无限的；无数的', 1214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'barrier', 'n. 障碍；栅栏；屏障', 1215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lane', 'n. （乡间）小路；跑道', 1216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'notebook', 'n. 笔记本，期票簿', 1217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'realm', 'n. 领域；王国，国土', 1218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lever', 'n. 控制杆；杆，杠杆', 1219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'midst', 'n. 中部，中间，当中', 1220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pilot', 'n. 飞行员；领航员', 1221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'direct', 'adj. 直接的；直率的', 1222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prejudice', 'n. 偏见，成见', 1223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tour', 'n. 旅行，旅游 v. 旅游，游历', 1224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tolerance', 'n. 忍受，容忍', 1225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discourage', 'v. 使泄气，使灰心', 1226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'get', 'v. 获得，得到；到达；变成，成为', 1227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'advertisement', 'n. 广告', 1228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ribbon', 'n. 缎带，丝带；带', 1229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'partner', 'n. 配偶；伙伴；搭挡', 1230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hamburger', 'n. 汉堡包，牛肉饼', 1231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'climb', 'v. 攀登，爬', 1232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'differ', 'v. 不同，相异', 1233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exhibition', 'n. 展览会；展览，陈列', 1234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mineral', 'n. 矿物 adj. 矿物的', 1235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'public', 'adj. 公众的 n. 公众', 1236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'palace', 'n. 宫，宫殿', 1237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pulse', 'n. 脉搏；脉动；脉冲', 1238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'immediately', 'adv. 立即；（immediately involved）直接地', 1239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cow', 'n. 母牛，奶牛；母兽', 1240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'private', 'adj. 私人的；私下的', 1241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'toast', 'n. 烤面包 v. 烘，烤', 1242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scenery', 'n. 风景；舞台布景', 1243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fun', 'n. 乐趣，娱乐；玩笑', 1244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'living', 'adj. 活的 n. 生活，生计', 1245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'Mediterranean', 'n. 地中海 adj. 地中海的', 1246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'worth', 'adj. 值…的 n. 价值', 1247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conquer', 'v. 征服；战胜', 1248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'absorb', 'v. 吸收；中文释义；使专心', 1249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'enthusiasm', 'n. 热情，热心，热忱', 1250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brood', 'n. 同窝幼鸟 v. 孵（蛋）', 1251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tip', 'v. 轻击；给小费', 1252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accompany', 'v. 陪伴，陪同；伴随', 1253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'execute', 'v. 将…处死；实施', 1254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conceal', 'v. 把…隐藏起来', 1255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'certain', 'adj. 肯定的；确实的', 1256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apparent', 'adj. 明显的；表面上的', 1257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'messenger', 'n. 送信者，信使', 1258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'merit', 'n. 长处，优点', 1259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'youth', 'n. 青春；青年们；青年', 1260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'naval', 'adj. 海军的，军舰的', 1261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'downward', 'adj. 向下的 adv. 向下地', 1262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fact', 'n. 事实；实际，实情', 1263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hut', 'n. 小屋，棚屋', 1264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'namely', 'adv. 即，也就是', 1265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'monument', 'n. 纪念碑；纪念馆', 1266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cool', 'adj. 凉的；冷静的', 1267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'governor', 'n. 州长；主管人员', 1268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'program', 'n. 程序；节目单', 1269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'illness', 'n. 病，疾病', 1270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'normal', 'adj. 正常的，普通的', 1271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'population', 'n. 人口；全体居民', 1272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'frontier', 'n. 边境；边疆；新领域', 1273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'quantity', 'n. 量，数量，分量', 1274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'order', 'n. 次序；整齐 v. 命令', 1275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'learning', 'n. 学问，知识；学习', 1276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'everywhere', 'adv. 到处，处处', 1277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stage', 'n. 阶段；舞台', 1278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'everyone', 'pron. 每人，人人', 1279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sting', 'v. 刺；刺痛 n. 刺', 1280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hatch', 'v. （蛋）孵化；孵出', 1281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'honey', 'n. 蜜，蜂蜜', 1282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nest', 'n. 巢；窝，穴', 1283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'degree', 'n. 度；学位', 1284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'equivalent', 'adj. 相等的；等量的', 1285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'calendar', 'n. 日历，历书；历法', 1286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'manual', 'adj. 体力的 n. 手册', 1287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cabinet', 'n. 内阁；橱，柜', 1288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'steady', 'adj. 稳固的 v. 使稳定', 1289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'more', 'adj. 更多的 adv. 更', 1290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apple', 'n. 苹果', 1291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'never', 'adv. 永不，决不；不', 1292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'instruction', 'n. 命令；教学；教训', 1293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'laughter', 'n. 笑，笑声', 1294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appeal', 'n. 呼吁；申述 v. 呼吁；申述', 1295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'idiom', 'n. 习语，成语', 1296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impressive', 'adj. 给人印象深刻的', 1297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fourteen', 'num. 十四', 1298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'on', 'prep. 在…上', 1299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stack', 'n. 堆，垛 v. 堆积', 1300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'imitate', 'v. 模仿；仿效；仿制', 1301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cast', 'v. 投，扔，抛；浇铸', 1302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pump', 'n. 泵 v. 用抽机抽', 1303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'animal', 'n. 动物，兽 adj. 兽欲/动物本能等（animal urges/instincts）', 1304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mend', 'v. 修补，缝补；修理', 1305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dozen', 'n. 一打，十二个', 1306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bathe', 'v. 给…洗澡', 1307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'means', 'n. 方法，手段，工具', 1308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emphasis', 'n. 强调，重点，重要性', 1309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shortage', 'n. 不足，缺少，不足额', 1310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contrary', 'adj. 相反的 n. 相反', 1311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tunnel', 'n. 隧道，坑道，地道', 1312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'visible', 'adj. 可见的，看得见的', 1313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'minimum', 'n. 最小量 adj. 最小的', 1314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hedge', 'n. 篱笆，树篱', 1315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bundle', 'n. 捆，包，束；包袱', 1316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stretch', 'v. 伸展；伸 n. 伸展', 1317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'electrical', 'adj. 电的，电气科学的', 1318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'artificial', 'adj. 人工的；娇揉造作的', 1319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grateful', 'adj. 感激的', 1320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'classmate', 'n. 同班同学', 1321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assess', 'v. 对（财产等）估价', 1322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'personal', 'adj. 个人的；本人的', 1323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'qualify', 'v. 使具有资格', 1324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shift', 'v. 替换，转移 n. 转换', 1325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'preceding', 'adj. 在前的；在先的', 1326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'board', 'n. 板 v. 上（船、车等）', 1327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'custom', 'n. 习惯，风俗；海关', 1328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'patch', 'n. 补丁；〔与周围部分不同的〕斑，小块 v. 修补，缝补', 1329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'jar', 'n. 罐子，坛子，广口瓶', 1330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'defeat', 'v. 战胜，击败；挫败', 1331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'child', 'n. 小孩，儿童；儿子/女儿', 1332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'education', 'n. 教育；训导', 1333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stair', 'n. 楼梯', 1334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ornament', 'n. 装饰物；装饰', 1335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'downstairs', 'adv. 在楼下 adj. 楼下的', 1336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hare', 'n. 野兔', 1337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brook', 'n. 小河，溪流', 1338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'procedure', 'n. 程序；手续；过程', 1339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'employ', 'v. 雇用；用；使忙于', 1340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'may', 'modal verb. 可能；可以；祝', 1341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'province', 'n. 省；领域，部门', 1342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'freeze', 'v. 冻；结冻', 1343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'artistic', 'adj. 艺术的；艺术家的', 1344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'combination', 'n. 结合，联合；混合', 1345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adapt', 'v. 使适应；改编', 1346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ambulance', 'n. 救护车', 1347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'burden', 'n. 担子，重担', 1348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'innocent', 'adj. 清白的；幼稚的', 1349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'option', 'n. 选择；选择权', 1350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fee', 'n. 费，酬金；赏金', 1351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'greeting', 'n. 问候，招呼，致敬', 1352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sincere', 'adj. 真诚的；真挚的', 1353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'steel', 'n. 钢，钢铁', 1354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'guard', 'v. 守卫；看守 n. 卫兵', 1355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'worthy', 'adj. 值得尊敬的；值得的', 1356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'breakfast', 'n. 早饭，早餐', 1357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sympathize', 'v. 同情；同感，共鸣', 1358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gallery', 'n. 美术馆，画廊；长廊；走廊', 1359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'notice', 'v. 注意 n. 注意；通知', 1360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'percentage', 'n. 百分比，百分率', 1361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'money', 'n. 货币；金钱；财富', 1362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'best', 'adj. 最好的；最大的', 1363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'meet', 'v. 遇见', 1364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crown', 'n. 王冠，冕；花冠', 1365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beginning', 'n. 开始，开端；起源', 1366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mathematical', 'adj. 数学的，数学上的', 1367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'juice', 'n. （水果等）汁，液', 1368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'meadow', 'n. 草地，牧草地', 1369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'district', 'n. 地区，区域；区', 1370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fish', 'n. 鱼；鱼肉 v. 钓鱼', 1371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'incorrect', 'adj. 不正确的，错误的', 1372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lose', 'v. 失去；迷失；输掉', 1373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'man', 'n. 男人；人；人类', 1374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mere', 'adj. 仅仅的；纯粹的', 1375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bell', 'n. 钟，铃，门铃；钟声', 1376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mean', 'v. 作…解释；意指', 1377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'surrender', 'v. 交出；投降', 1378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'complicate', 'v. 使复杂；使陷入', 1379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'English', 'n. 英语 adj. 英国人的', 1380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gardener', 'n. 园丁，花匠', 1381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'call', 'v. 把…叫做；叫，喊', 1382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pleasant', 'adj. 令人愉快的，舒适的', 1383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conversion', 'n. 转变，转化；改变', 1384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adopt', 'v. 收养；采用；采取', 1385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'master', 'n. 能手；主人；硕士', 1386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pipe', 'n. 管子，导管；烟斗', 1387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recover', 'v. 重新获得；挽回', 1388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'communicate', 'v. 通讯；传达', 1389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bike', 'n. 自行车 v. 骑自行车', 1390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'classify', 'v. 把…分类', 1391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'trumpet', 'n. 喇叭，小号', 1392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'canoe', 'n. 独木舟，皮艇，划子', 1393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'entertain', 'v. 使欢乐；招待', 1394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'campaign', 'n. 运动；战役', 1395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'abandon', 'v. 丢弃；放弃，抛弃', 1396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lorry', 'n. 运货汽车，卡车', 1397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'congress', 'n. 大会；国会，议会', 1398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'double', 'adj. 双的；两倍的', 1399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confident', 'adj. 确信的；自信的', 1400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'extreme', 'adj. 极度的；尽头的', 1401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'frequency', 'n. 屡次；次数；频率', 1402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confess', 'v. 供认，承认；坦白', 1403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lodge', 'v. 暂住，借宿，投宿', 1404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apartment', 'n. 一套公寓房间', 1405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'elevator', 'n. 电梯；升降机', 1406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'kilogram', 'n. 千克，公斤', 1407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'industrial', 'adj. 工业的；产业的', 1408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'explosive', 'n. 炸药 adj. 会爆炸的', 1409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'challenge', 'n. 挑战', 1410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'swear', 'v. 宣（誓）；诅咒', 1411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'departure', 'n. 离开，出发，起程', 1412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'elastic', 'n. 松紧带 adj. 有弹性的', 1413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'break', 'v. 打破；损坏；破坏', 1414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'capital', 'n. 首都；资本，资金', 1415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adequate', 'adj. 足够的；可以胜任的', 1416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'progress', 'n. 前进；进展；进步', 1417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'paste', 'n. 糊；酱；糨糊', 1418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relevant', 'adj. 有关的，贴切的', 1419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exam', 'n. 考试；检查，细查', 1420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conservative', 'adj. 保守的 n. 保守的人', 1421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inhabit', 'v. 居住于，栖息于', 1422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ministry', 'n. （政府的）部', 1423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stem', 'n. 茎，（树）干 v. 起源', 1424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'margin', 'n. 页边的空白；边缘；边缘', 1425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'core', 'n. 果实的心；核心', 1426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'correspondent', 'n. 通讯员；通信者', 1427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'possibly', 'adv. 可能地；也许', 1428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'roll', 'v. 滚动；转动', 1429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'repair', 'v. 修理，修补 n. 修理，修补', 1430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'moral', 'adj. 道德的；合乎道德的', 1431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'broken', 'adj. 被打碎的；骨折的', 1432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'steer', 'v. 驾驶', 1433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wax', 'n. 蜡，蜂蜡', 1434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'centimetre', 'n. 公分，厘米', 1435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gaseous', 'adj. 气体的，气态的', 1436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'equal', 'adj. 相等的；平等的', 1437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lecture', 'n. 演讲，讲课 v. 演讲，讲课', 1438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recommendation', 'n. 推荐，介绍；劝告', 1439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bleed', 'v. 出血，流血', 1440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'kid', 'n. 小孩，儿童；少年', 1441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'become', 'v. 变得；变成；成为', 1442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rid', 'v. 使摆脱，使去掉', 1443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'land', 'n. 土地；陆地 v. 上岸', 1444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bold', 'adj. 大胆的；冒失的', 1445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prison', 'n. 监狱；监禁', 1446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'modest', 'adj. 谦虚的；不太大的；不很贵的', 1447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leather', 'n. 皮革；皮革制品', 1448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'length', 'n. 长，长度；一段', 1449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'academic', 'adj. 学院的；学术的', 1450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prosperous', 'adj. 繁荣的，昌盛的', 1451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grammatical', 'adj. 语法上的', 1452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'physics', 'n. 物理学', 1453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'turbine', 'n. 叶轮机，汽轮机', 1454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contempt', 'n. 轻蔑；藐视；受辱', 1455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'settlement', 'n. 解决；殖民，殖民地', 1456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'label', 'n. 标签；标记，符号', 1457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dew', 'n. 露，露水', 1458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'professor', 'n. 教授', 1459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nothing', 'n. 没有东西 adv. 毫不', 1460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'palm', 'n. 手掌，手心', 1461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'limit', 'n. 限度；限制；范围', 1462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crude', 'adj. 简陋的；天然的', 1463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cold', 'adj. 冷的；冷淡的 n. 冷', 1464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'frank', 'adj. 坦白的，直率的', 1465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'forget', 'v. 忘记，遗忘', 1466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bean', 'n. 豆，蚕豆', 1467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appear', 'v. 似乎；出现；来到', 1468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'price', 'n. 价格，价钱；代价', 1469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emotion', 'n. 情感，感情；激动', 1470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'worst', 'adj. 最坏的 adv. 最坏地', 1471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'moan', 'n. 呻吟声 v. 呻吟', 1472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'terrible', 'adj. 可怕的；极度的', 1473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dollar', 'n. 元〔美国、加拿大、澳大利亚等国的货币单位〕', 1474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'answer', 'v. 回答；响应', 1475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'barn', 'n. 谷仓；牲口棚', 1476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conclusion', 'n. 结论，推论；结尾', 1477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'demand', 'v. 要求；询问；需要', 1478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'learn', 'v. 学，学习', 1479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rival', 'n. 竞争者 adj. 竞争的', 1480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'industry', 'n. 工业，产业；勤劳', 1481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'concern', 'n. 关心，挂念；重要的事', 1482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'friendly', 'adj. 友好的；友谊的', 1483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pale', 'adj. 苍白的；浅的', 1484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dramatic', 'adj. 戏剧的；引人注目的', 1485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rhythm', 'n. 韵律，格律；节奏', 1486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'local', 'adj. 地方的；局部的', 1487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nuclear', 'adj. 原子核的', 1488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gentleman', 'n. 绅士；有教养的人', 1489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exactly', 'adv. 确切地；恰恰正是', 1490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shield', 'n. 盾；防护物 v. 保护', 1491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hawk', 'n. 鹰，隼', 1492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'network', 'n. 网状物；网络', 1493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'disease', 'n. 病，疾病；病害', 1494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'French', 'adj. 法国的 n. 法国人', 1495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'indicate', 'v. 标示，表示；表明', 1496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'aural', 'adj. 耳的，听觉的', 1497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'basket', 'n. 篮，篓，筐', 1498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interpreter', 'n. 译员，口译者', 1499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mountain', 'n. 山，山岳；山脉', 1500);
