INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breed', 'v. 教养,抚养 n. 品种', 1501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'partner', 'n. 合伙人', 1502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'argument', 'n. 争论', 1503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solve', 'v. 解决,解答', 1504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cage', 'n. 笼', 1505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shale', 'n. 页岩,泥板岩', 1506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'productivity', 'n. 生产力', 1507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furniture', 'n. 家具,设备', 1508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'systematic', 'adj. 系统的,体系的', 1509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attribute', 'n. 属性,品质,特征', 1510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maker', 'n. 制造者', 1511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variable', 'adj. 多变的,可变的 n. 变量', 1512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preservation', 'n. 保存', 1513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'initiate', 'v. 开始,发起', 1514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breakfast', 'n. 早餐 vi进早餐', 1515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perceive', 'v. 察觉,感知', 1516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convince', 'v. 使确信, 使信服', 1517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'competitive', 'adj. 竞争的', 1518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clue', 'n. 线索', 1519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nervous', 'adj. 紧张的,不安的', 1520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'count', 'v. 数,计算', 1521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adjust', 'v. 调整,校准', 1522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'challenge', 'n&v. 挑战', 1523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hyper', 'adj. 亢奋的,高度紧张的', 1524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eliminate', 'v. 排除,除去', 1525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warren', 'n. 养兔场,大杂院', 1526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resident', 'n. 居民', 1527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vent', 'n. 出口 v. 排出,发泄', 1528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pole', 'n. 柱,地极', 1529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storage', 'n. 贮藏(量),存储', 1530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'investor', 'n. 投资者', 1531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loose', 'n. 解放,放任 v. 弄松, 释放', 1532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'miss', 'n. 过错 v. 错过,遗漏', 1533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upward', 'adj. 向上的 adv. 以上', 1534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linguistic', 'adj. 语言(学)上的', 1535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primitive', 'adj. 原始的,远古的', 1536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uniform', 'n. 制服 v. 使统一', 1537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vision', 'n. 幻想,视觉', 1538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graze', 'v. 放牧,掠过', 1539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cucumber', 'n. 黄瓜', 1540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exception', 'n. 除外,例外', 1541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elaborate', 'adj. 详尽的,复杂的 v. 详述', 1542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'failure', 'n. 失败', 1543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secure', 'adj. 安全的,可靠的 v. 保护', 1544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pool', 'n. 池', 1545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mystery', 'n. 神秘,神秘的事物', 1546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coat', 'n. 外套 v. 涂上,包上', 1547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mature', 'adj. 成熟的 v. 使成熟', 1548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sustain', 'v. 支撑,维持', 1549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'latitude', 'n. 纬度,范围', 1550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clothe', 'v. 给穿衣,覆盖', 1551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coin', 'n. 硬币 v. 铸造(硬币)', 1552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'news', 'n. 新闻,消息', 1553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organ', 'n. 器官,机构', 1554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'earthenware', 'n. 土器,陶器', 1555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refuse', 'v. 拒绝', 1556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hill', 'n. 小山,丘陵', 1557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wagon', 'n. 四轮马车,货车', 1558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rite', 'n. 仪式,典礼', 1559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'achievement', 'n. 成就,功绩', 1560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inhabit', 'v. 居住于,栖息', 1561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locust', 'n. 蝗虫', 1562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'federal', 'adj. 联邦的,联合的', 1563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'govern', 'v. 统治,支配,管理', 1564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'philosophy', 'n. 哲学', 1565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endure', 'v. 耐久,忍耐', 1566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offspring', 'n. 儿女,子孙', 1567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Hawaii', 'n. 夏威夷', 1568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brick', 'n. 砖块', 1569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convert', 'v. 使转变,转换', 1570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pigeon', 'n. 鸽子', 1571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'celebrity', 'n. 名声,名人', 1572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devise', 'v. 设计,发明', 1573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'your', 'pron. 你的,你们的', 1574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'territory', 'n. 领土,地域', 1575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interact', 'v. 互相作用,互相影响', 1576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gulf', 'n. 海湾,深渊', 1577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bond', 'n. 结合,协定 v. 使结合,粘合', 1578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cluster', 'n. 串,丛', 1579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calcium', 'n. 钙', 1580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vital', 'adj. 重大的,至关重要的', 1581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poetry', 'n. 诗', 1582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notice', 'n. 通知 v. 注意到', 1583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inland', 'adj. 内陆的,国内的', 1584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'voice', 'n. 嗓音,意见 v. 说(话)', 1585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'double', 'n&a. 两倍(的) v. 使加倍', 1586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entrance', 'n. 入口', 1587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chemistry', 'n. 化学', 1588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oppose', 'v. 反对,对抗', 1589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portrait', 'n. 肖像,人像', 1590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agent', 'n. 代理(商)', 1591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weave', 'v. 织,编', 1592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scatter', 'v. 撒(播),分散', 1593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empty', 'adj. 空的 v. (使)空,倒出', 1594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'islander', 'n. 岛上居民', 1595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recognition', 'n. 识别,确认', 1596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tile', 'n. 瓦片,瓷砖', 1597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indication', 'n. 指示,表示,迹象', 1598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implement', 'v. 履行,实施 n. 工(器,用)具', 1599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limitation', 'n. 限制,局限性', 1600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'piano', 'n. 钢琴', 1601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proxy', 'n. 代理人', 1602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neolithic', 'adj. 新石器时代的', 1603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'voyage', 'n&v. 航海', 1604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inspire', 'v. 鼓舞,激起,给…以灵感', 1605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spore', 'n. 孢子', 1606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Texas', 'n. 德克萨斯州(美国州名)', 1607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strain', 'n&v. 拉紧,紧张,劳累', 1608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imitate', 'v. 模仿,仿制', 1609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'timber', 'n. 木材,木料', 1610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rank', 'n. 等级,阶层 v. 排列', 1611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concentrate', 'v. 专心,集中,浓缩', 1612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'container', 'n. 容器', 1613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'article', 'n. 文章,论文', 1614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sink', 'v. 下沉', 1615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ecology', 'n. 生态学', 1616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drink', 'v. 喝酒', 1617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'runoff', 'n. 径流量,流出', 1618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watercolor', 'n. 水彩颜料,水彩画(法)', 1619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'streamline', 'adj. 流线型的', 1620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'self', 'n. 自己,自我', 1621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reward', 'n. 报酬 v. 酬劳', 1622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mantle', 'n. 斗蓬 v. 披风,覆盖', 1623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telescope', 'n. 望远镜', 1624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsequent', 'adj. 后来的,并发的', 1625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hungry', 'adj. 饥饿的,渴望的', 1626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'episode', 'n. 一段情节', 1627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crossbill', 'n. 交喙鸟', 1628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emergence', 'n. 浮现,露出', 1629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cheap', 'adj. 便宜的,不值钱的', 1630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sort', 'n. 种类v分类,拣选', 1631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industrialize', 'v. 使工业化', 1632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burial', 'n. 埋葬', 1633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hominid', 'n. 原始人类', 1634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laboratory', 'n. 实验室', 1635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cinema', 'n. 电影院,电影', 1636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compass', 'n. 罗盘,指南针', 1637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kittiwake', 'n. 三趾鸥', 1638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mode', 'n. 方式,模式', 1639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entertainment', 'n. 款待,娱乐', 1640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'everything', 'pron. 每件事物', 1641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purchase', 'v. 购买', 1642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sanctuary', 'n. 避难所', 1643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bus', 'n. 公共汽车', 1644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theatrical', 'adj. 戏剧性的', 1645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'profession', 'n. 职业,专业', 1646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theme', 'n. 主题', 1647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravel', 'n. 砂砾(层)', 1648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laborer', 'n. 劳动者', 1649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proton', 'n. 质子', 1650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commerce', 'n. 商业', 1651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decide', 'v. 决定,判决', 1652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fireplace', 'n. 壁炉', 1653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aluminum', 'n. 铝', 1654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firm', 'n. 公司', 1655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collide', 'v. 碰撞,抵触', 1656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fight', 'n&v. 战斗,打架,斗争', 1657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puzzle', 'n. 难题 v. (使)迷惑', 1658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'performer', 'n. 表演者', 1659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twist', 'v. 缠绕,拧,扭曲', 1660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dramatically', 'adv. 戏剧地,引人注目地', 1661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'listen', 'v. 听', 1662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dependence', 'n. 依靠,信任', 1663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'struggle', 'v. 努力,奋斗,挣扎', 1664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'German', 'n. 德国人 adj. 德国的', 1665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irregular', 'adj. 不规则的,无规律的', 1666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'centimeter', 'n. 厘米', 1667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonization', 'n. 殖民地化,殖民', 1668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fund', 'n. 资金 v. 支助,投资', 1669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'historian', 'n. 历史学家', 1670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'female', 'n. 女性', 1671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emit', 'v. 发出,放射', 1672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retreat', 'v. 撤退,退却', 1673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deficiency', 'n. 缺乏,不足', 1674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rotate', 'v. (使)旋转', 1675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invertebrate', 'a&n. 无脊椎的,无骨气的人', 1676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbiotic', 'adj. 共生的', 1677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alternative', 'adj. 选择性的,二中择一的', 1678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bridge', 'n. 桥 v. 架桥,渡过', 1679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vertical', 'adj. 垂直的,直立的', 1680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circle', 'n. 圆(圈) v. 围着,盘旋', 1681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quarter', 'n. 四分之一,一刻钟', 1682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fix', 'v. 修理,安装,整理', 1683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doubt', 'n&v. 怀疑,怀疑', 1684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Tennessee', 'n. 田纳西州', 1685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eruption', 'n. 爆发,火山灰', 1686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'treat', 'vt&n. 对待,款待', 1687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'politician', 'n. 政治家,政客', 1688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'politics', 'n. 政治,政治学', 1689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mail', 'n. 邮件,邮政', 1690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beauty', 'n. 美,美景', 1691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'format', 'n. 设计,格式', 1692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Spanish', 'a&n. 西班牙(的),西班牙人(的)', 1693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confirm', 'v. 确定,确认', 1694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bubble', 'n. 泡 v. 冒泡,起泡', 1695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engraving', 'n. 雕刻术,雕版', 1696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specimen', 'n. 范例,标本,样品', 1697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tide', 'n. 潮,潮汐', 1698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ray', 'n. 光线,射线', 1699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weigh', 'v. 称重量', 1700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encounter', 'v&n. 遭遇,遇到', 1701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'costume', 'n. 装束,服装', 1702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plane', 'n. 平面,飞机', 1703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nouveau', 'adj. 新近到达的,最近产生的', 1704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gland', 'n. 腺', 1705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emission', 'n. 散发,发行,排放', 1706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'log', 'n. 原木,航海日志 v. 正式记录', 1707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glaze', 'v. 变呆滞 v. 上釉 n. 釉(料)', 1708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'martian', 'n&a. 火星人(的)', 1709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bee', 'n. 蜜蜂', 1710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'latter', 'adj. 后者的,后面的', 1711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occurrence', 'n. 发生,出现', 1712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anything', 'pron. 任何事', 1713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevail', 'v. 流行,获胜', 1714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliance', 'n. 信任,信心,依靠', 1715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roof', 'n. 屋顶', 1716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mercantile', 'adj. 贸易的,商业的', 1717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overall', 'adj. 全部的,全面的', 1718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fossilize', 'v. 成化石,陈腐', 1719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chain', 'n. 链(条),一连串,一系列', 1720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pose', 'n. 姿势,姿态 v. 摆姿势', 1721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cylinder', 'n. 圆筒,圆柱体', 1722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'countercurrent', 'n. 逆流,反向电流', 1723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'score', 'n. 得分', 1724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potter', 'n. 陶工,制陶工人', 1725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aesthetic', 'adj. 美学的,审美的', 1726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neighborhood', 'n. 附近,邻近', 1727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hemisphere', 'n. 半球', 1728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excavate', 'v. 挖掘,开凿', 1729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reclamation', 'n. 开垦,改造', 1730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admire', 'v. 赞美,钦佩,羡慕', 1731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ensure', 'v. 确保,保证', 1732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weak', 'adj. 虚弱的,淡的', 1733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excite', 'v. 使兴奋,激动', 1734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orbit', 'n. 轨道 v. (绕…)作轨道运行', 1735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sale', 'n. 出售,卖出', 1736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blow', 'v. 风吹,吹气于', 1737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pair', 'n. 一对,一双', 1738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grind', 'v. 磨(碎),折磨', 1739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cease', 'v. 停止,终了', 1740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incorporate', 'v. 合并,组成公司', 1741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classroom', 'n. 教室', 1742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'box', 'n. 盒子,箱', 1743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biologist', 'n. 生物学家', 1744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aboriginal', 'adj. 土著的,原来的', 1745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'automatically', 'adv. 自动地,机械地', 1746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crude', 'adj. 天然的,未加工的,粗鲁的', 1747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'version', 'n. 译文,译本', 1748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drawing', 'n. 图画,制图', 1749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capture', 'n&v. 捕获,俘获,夺取', 1750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hang', 'v. 悬挂,附着', 1751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'income', 'n. 收入,收益,', 1752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freedom', 'n. 自由', 1753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Mississippi', 'n. 密西西比河,密西西比州(美国州名)', 1754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cartoon', 'n. 漫画,卡通画', 1755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'separation', 'n. 分离,分开', 1756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recharge', 'v. 再充电,再进攻,恢复精力', 1757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motivation', 'n. 动机', 1758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gene', 'n. [遗传]因子,[遗传]基因', 1759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penetrate', 'v. 穿透,渗透,看穿', 1760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collective', 'adj. 集体的,共同的', 1761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nerve', 'n. 神经,胆量', 1762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engrave', 'v. 雕刻,使铭记', 1763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strait', 'n. 地峡', 1764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flake', 'n. 薄片 v. 使成薄片,剥落', 1765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disadvantage', 'n. 不利,缺点,劣势', 1766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constitute', 'v. 构成,组成,建立', 1767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graham', 'adj. 全麦(面粉)的', 1768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reference', 'n. 提及,涉及,参考', 1769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eight', 'num. 八,八个,第八', 1770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turnpike', 'n. 收费公路', 1771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'load', 'n. 负荷,装载量 v. 装(载),使负担', 1772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trigger', 'v. 引发,引起 n. 板机', 1773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mixture', 'n. 混合(物)', 1774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geology', 'n. 地质学,地质概况', 1775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spin', 'v. 旋转,纺纱', 1776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expressive', 'adj. 表达的,意味深长的', 1777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'row', 'n. 排,行v划(船)', 1778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secrete', 'v. 隐藏,隐匿', 1779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discourage', 'v. 使气馁,阻碍', 1780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tremendous', 'adj. 巨大的,惊人的', 1781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crab', 'n. 蟹', 1782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'garden', 'n. (菜、花)园', 1783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'astronomer', 'n. 天文学家', 1784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bare', 'adj. 赤裸的,无遮蔽的', 1785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Erie', 'n. 伊利(人)', 1786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inhibit', 'v. 阻止妨碍抑制', 1787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Yucatan', 'n. 尤卡坦半岛', 1788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alkali', 'n. 碱 adj. 碱性的', 1789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complexity', 'n. 复杂(性),复杂的事物', 1790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sedimentary', 'adj. 沉积的,沉淀性的', 1791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accelerate', 'v. 加速,促进', 1792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Spain', 'n. 西班牙(欧洲南部国家)', 1793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'window', 'n. 窗,窗口', 1794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'text', 'n. 正文,课文', 1795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sing', 'v. 唱,演唱', 1796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assist', 'v. 援助,帮助', 1797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'representation', 'n. 表示法,表现,陈述', 1798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regulation', 'n. 规则', 1799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enclose', 'v. 放入封套,围绕', 1800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluctuate', 'v. 变动,波动', 1801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furnace', 'n. 炉子,熔炉', 1802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reptile', 'n. 爬虫动物', 1803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'popularity', 'n. 普及,流行', 1804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whom', 'pron. 谁', 1805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bake', 'v. 烘焙,烤', 1806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ash', 'n. 灰(烬),[植]岑树', 1807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'institution', 'n. 公共机构,协会,制度', 1808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbolic', 'adj. 象征的,符号的', 1809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'religion', 'n. 宗教,信仰', 1810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conserve', 'v. 保存,保藏', 1811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pit', 'n. 深坑,陷阱v窖藏,使凹下', 1812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'traffic', 'n. 交通,运输', 1813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Harvard', 'n. 哈佛大学(美国)', 1814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Himalaya', 'n. 喜马拉雅山', 1815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'digest', 'v. 消化,融会贯通', 1816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'application', 'n. 请求,申请,应用', 1817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravity', 'n. 地心引力,重力', 1818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explorer', 'n. 探险者', 1819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'educate', 'v. 教育,培养', 1820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sudden', 'adj. 突然的,意外的', 1821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precipitation', 'n. 仓促', 1822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sheep', 'n. 羊,绵羊', 1823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mercy', 'n. 仁慈,宽恕,怜悯', 1824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lewis', 'n. [机] 吊楔,起重爪', 1825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oceanic', 'adj. 海洋的', 1826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'award', 'n. 奖,奖品 v. 授予,判给', 1827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comfortable', 'adj. 舒适的,充裕的', 1828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sail', 'v. 航行(于),启航', 1829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recall', 'v. 回忆,记起 n. 召回', 1830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'publisher', 'n. 出版者,发行人', 1831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seat', 'n. 座位 v. 使坐下', 1832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'usual', 'adj. 平常的,通常的', 1833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'touch', 'v. 接触,达到', 1834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boom', 'n. 繁荣 v. 发隆隆声,兴隆', 1835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'administration', 'n. 管理,经营', 1836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outflow', 'n. 流出(物)', 1837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'durable', 'adj. 持久的,耐用的', 1838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undertake', 'v. 承担,采取', 1839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finance', 'n. 财政 v. 供给经费,筹措资金', 1840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seal', 'n. 封铅 vt封, 密封', 1841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assumption', 'n. 假定, 设想', 1842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Ohio', 'n. 俄亥俄州(美国州名)', 1843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guide', 'n. 领路人,指南 vt指导, 支配', 1844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exceed', 'v. 超越, 胜过', 1845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reform', 'vt&n. 改革, 革新', 1846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'switch', 'n. 开关 vt转换, 转变', 1847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'southwestern', 'adj. 西南的, 来自西南的', 1848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infantile', 'adj. 幼稚的，幼儿的', 1849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brother', 'n. 兄弟', 1850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crucial', 'adj. 至关紧要的', 1851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amnesia', 'n. 健忘症', 1852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toy', 'n. 玩具', 1853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silent', 'adj. 寂静的, 沉默的', 1854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutritional', 'adj. 营养的,滋养的', 1855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taste', 'v. 品尝, 体验', 1856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contradict', 'v. 同矛盾, 同抵触', 1857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verbal', 'adj. 口头的', 1858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attach', 'v. 缚上, 配属,隶属于', 1859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplement', 'n. 补充, 附录', 1860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delivery', 'n. 递送,交付,传输', 1861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'span', 'n. 跨度v横越', 1862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comparable', 'adj. 可比较的, 比得上的', 1863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satisfy', 'v. 满足,使满意', 1864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'panel', 'n. 面，板,专门小组', 1865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'react', 'v. 起反应, 起作用', 1866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freshwater', 'n. 淡水', 1867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'successive', 'adj. 连续的, 接连的', 1868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'official', 'n. 官员 adj. 官方的,正式的', 1869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'save', 'v. 解救, 保存', 1870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appreciate', 'v. 赏识, 感激', 1871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'friend', 'n. 朋友, 赞助者, 助手', 1872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outline', 'n. 大纲 v. 描画轮廓,略述', 1873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crustal', 'adj. 地壳的', 1874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'threat', 'n. 恐吓, 凶兆, 威胁', 1875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carbohydrate', 'n. 碳水化合物,醣类', 1876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'periodical', 'adj. 周期的, 定期的 n期刊, 杂志', 1877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nine', 'num. 九,九个', 1878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strengthen', 'v. 加强, 巩固', 1879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quartz', 'n. 石英', 1880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sociologist', 'n. 社会学家', 1881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classic', 'adj. 最优秀的,标准的 n杰作', 1882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sum', 'n. 总数,总和 v. 共计,概括', 1883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delicate', 'adj. 精巧的, 精致的', 1884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leadership', 'n. 领导能力,领导阶层', 1885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'king', 'n. 国王', 1886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colleague', 'n. 同事, 同僚', 1887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seafloor', 'n. 海底', 1888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bronze', 'n. 青铜', 1889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'medium', 'n. 媒体,方法 adj. 中间的', 1890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dome', 'n. 圆屋顶', 1891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'script', 'n. 手稿, 手迹', 1892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hotel', 'n. 旅馆, 客栈,', 1893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'found', 'v. 建立, 创办', 1894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twice', 'adv. 两次, 两倍', 1895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instruction', 'n. 命令,指示,用法说明', 1896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thrive', 'v. 兴旺,繁荣', 1897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fiction', 'n. 虚构,小说', 1898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motor', 'n. 发动机', 1899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'partially', 'adv. 部分地', 1900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Germany', 'n. 德国', 1901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beautiful', 'adj. 美丽的', 1902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vehicle', 'n. 交通工具, 车辆', 1903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marsh', 'n. 湿地,沼泽', 1904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freight', 'n. 货物 v. 运送', 1905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trust', 'v. 信任, 信赖', 1906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrigue', 'v. 激起兴趣,耍阴谋 n. 阴谋，密谋', 1907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artwork', 'n. 艺术品,美术品', 1908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hatch', 'n. 孵化 vt孵出, 策划', 1909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shore', 'n. 岸, 海滨', 1910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utilize', 'v. 利用', 1911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classification', 'n. 分类, 分级', 1912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tube', 'n. 管子', 1913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kiln', 'n. 窑,炉', 1914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implication', 'n. 含意, 暗示', 1915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expert', 'n. 专家, 行家', 1916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awareness', 'n. 知道, 晓得', 1917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drag', 'v. 拖, 拖曳', 1918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indium', 'n. [化]铟', 1919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precious', 'adj. 宝贵的,珍爱的', 1920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'velocity', 'n. 速度, 速率', 1921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burst', 'v. 爆裂, 炸破', 1922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'academy', 'n. 学院,学会,专科学校', 1923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'path', 'n. 小路, 路线', 1924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refine', 'v. 精炼, 精制', 1925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imprint', 'v. 留下烙印', 1926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intellectual', 'adj. 智力的, 有智力的', 1927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impression', 'n. 印象, 感想', 1928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Pennsylvania', 'n. 宾夕法尼亚州（美国州名）', 1929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'iridium', 'n. [化]铱', 1930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pick', 'v. 挑选,采摘', 1931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cent', 'n. (货币单位)分, 分币', 1932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mobility', 'n. 活动性, 灵活性', 1933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inference', 'n. 推论', 1934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'integrate', 'v. 使成整体, 结合', 1935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rush', 'n&v. 冲,匆忙,突袭', 1936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spray', 'n. 喷雾 vt喷射', 1937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strongly', 'adv. 强烈地；强有力地', 1938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lay', 'v. 放置,铺设', 1939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bite', 'n&v. 咬, 刺痛', 1940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harm', 'v. 伤害, 损害', 1941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'footprint', 'n. 足迹', 1942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herself', 'pron. 她自己', 1943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sponsor', 'n. 发起人 v发起, 主办, 赞助', 1944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calorie', 'n. 卡路里', 1945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unpredictable', 'adj. 不可预知的', 1946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'automobile', 'n. 汽车', 1947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collector', 'n. 收藏家, 征收者', 1948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cooperation', 'n. 合作, 协作', 1949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enzyme', 'n. [生化]酶', 1950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'employee', 'n. 职工, 雇员', 1951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irrigate', 'v. 灌溉', 1952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dozen', 'n. 一打, 十二个', 1953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrieve', 'v. 恢复,挽回,取回', 1954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'printer', 'n. 印刷工,打印机', 1955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silt', 'n. 淤泥 v. (使)淤塞', 1956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roll', 'v. (使)滚动,卷', 1957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surveyor', 'n. 测量员, 检查员', 1958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'worldwide', 'adj. 全世界的', 1959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acre', 'n. 英亩, 地产', 1960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nuclear', 'adj. 核子的, 原子能的', 1961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutrition', 'n. 营养, 营养学', 1962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'larva', 'n. 幼虫', 1963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exposition', 'n. 展览会, 说明', 1964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sharp', 'adj. 锐利的,明显的,急剧的', 1965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peasant', 'n. 农夫', 1966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plastic', 'n. 塑料(制品) adj. 塑胶的', 1967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genetic', 'adj. 遗传的, 起源的', 1968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'page', 'n. 页,记录', 1969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accumulator', 'n. 蓄电池,积聚者', 1970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chief', 'n. 首领 adj. 主要的, 首要的', 1971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imitation', 'n. 模仿, 效法', 1972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beneficial', 'adj. 有利的, 有益的', 1973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lip', 'n. 嘴唇', 1974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fertilizer', 'n. 肥料', 1975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rainwater', 'n. 雨水', 1976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satire', 'n. 讽刺(文学)', 1977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epoch', 'n. 新纪元, 时代', 1978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impressive', 'adj. 给人深刻印象的, 感人的', 1979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brush', 'n. 刷子, 毛刷, 画笔 vt刷, 掸, 拂', 1980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Massachusetts', 'n. 马萨诸塞(美国州名)', 1981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'realism', 'n. 现实主义', 1982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watch', 'v. 看,注视,照顾', 1983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foundation', 'n. 基础, 根本', 1984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evident', 'adj. 明显的, 显然的', 1985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marry', 'v. 娶, 嫁,和结婚', 1986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'race', 'n. 种族 v赛跑', 1987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orient', 'v. 使适应,使朝向 n东方', 1988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barren', 'adj. 不生育的,贫瘠的 n. 荒地', 1989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prosperity', 'n. 繁荣', 1990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lava', 'n. 熔岩, 火山岩', 1991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pace', 'n. 步调 v踱步', 1992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empire', 'n. 帝国', 1993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contract', 'n. 合同 v缩小,订合同', 1994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deco', 'n. 装饰派艺术', 1995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'descriptive', 'adj. 描述的, 叙述的', 1996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ruminant', 'n&a. 反刍动物(的), 沉思的', 1997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stoneware', 'n. 瓷器', 1998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mirror', 'n. 镜子 v. 反映,映出', 1999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barb', 'n. 鱼钩 v. 装倒钩于', 2000);
