INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slave', 'n. 奴隶', 4501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pinniped', 'adj. 鳍足类的', 4502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'companionship', 'n. 友谊', 4503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaeocyte', 'n. 原始(生殖)细胞', 4504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protective', 'adj. 给予保护的, 保护的', 4505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incidental', 'adj. 偶然的；附带的', 4506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intruder', 'n. 入侵者', 4507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conjunction', 'n. 联合, 关联', 4508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ornate', 'adj. 华丽的, 装饰的', 4509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intentionally', 'adv. 有意地,故意地', 4510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impractical', 'adj. 不切实际的,不实用的', 4511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steal', 'v. 偷, 窃取', 4512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhetoric', 'n. 雄辩言辞,修辞学', 4513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clump', 'n. (树，草)丛 v. 使成一丛', 4514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immaturity', 'n. 不成熟', 4515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'understandable', 'adj. 可理解的,能够懂的', 4516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'register', 'n& vt. 登记(表)，注册', 4517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offset', 'v. 补偿，抵消', 4518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faculty', 'n. 能力，院系，全体教员', 4519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'divorce', 'n&v. 离婚, 脱离', 4520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'daytime', 'n. 白天, 日间', 4521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dare', 'v. 敢, 挑战', 4522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overcrowd', 'v. 过度拥挤', 4523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marvelous', 'adj. 令人惊异的, 非凡的', 4524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foolish', 'adj. 愚蠢的，荒谬的', 4525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opportunistic', 'adj. 机会主义的, 投机取巧的', 4526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brine', 'n. 盐水', 4527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'naive', 'adj. 天真的', 4528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'merchandise', 'n. 商品, 货物', 4529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jade', 'n. 玉，翡翠', 4530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lapis', 'n. [化]天青石(常用于化学中的矿物命名)', 4531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breakthrough', 'n. 突破', 4532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manager', 'n. 经理, 管理人员', 4533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compositional', 'adj. 合成的,组成的', 4534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'youngster', 'n. 年青人,  少年', 4535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ideologically', 'adv. 意识形态上地, 思想上地', 4536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interpersonal', 'adj. 人与人之间的, 人际关系的', 4537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Afghanistan', 'n. 阿富汗(西南亚国家)', 4538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lazuli', 'n. 天青石', 4539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electronically', 'adv. 电子地, 通过电子手段', 4540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sewage', 'n. 污水, 污物', 4541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authorize', 'v. 批准', 4542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'municipal', 'adj. 市政的', 4543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imagery', 'n. 意象, 肖像', 4544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refreeze', 'vt. 再结冰, 重新冻结', 4545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydrologic', 'adj. 水文的', 4546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dietary', 'adj. 饮食的 n. 规定的食物', 4547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydropower', 'n. 水力发出的电力', 4548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'granule', 'n. 小粒，微粒', 4549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'further', 'a&ad. 更远的,更进一步地', 4550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recreational', 'adj. 娱乐的, 消遣的', 4551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insecure', 'adj. 不安全的,不稳固的', 4552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dealing', 'n. 行为, 交易', 4553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circumvent', 'v. 绕行,设法避开', 4554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chunk', 'n. 大块,相当大的部分（数量）', 4555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staff', 'n. 全体职工，全体人员', 4556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'achondrite', 'n. 不含球粒陨石', 4557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asset', 'n. 资产', 4558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'navigable', 'adj. 可航行的,可操纵的', 4559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flutter', 'v. 振翼；飘动', 4560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pitch', 'n. 球场,强度v扔,猛然倒下', 4561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multiplicity', 'n. 多样性', 4562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'figuratively', 'adv. 比喻地', 4563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crime', 'n. 犯罪', 4564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speaker', 'n. 说话者, 演讲人', 4565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undermine', 'v. 破坏', 4566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'greener', 'n. 生手', 4567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entrepreneurial', 'adj. 企业家的,  企业性质的', 4568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foliage', 'n. 树叶,植物', 4569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vice', 'n. 缺点, 恶习', 4570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supreme', 'adj. 最高的, 至上的', 4571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maximize', 'v. 取最大值, 最佳化', 4572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bushman', 'n. 丛林居民', 4573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grade', 'n. 等级 v. 评分,分等级', 4574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marshy', 'adj. 沼泽般的,湿软的', 4575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anxiety', 'n. 忧虑, 焦急', 4576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retirement', 'n. 退休', 4577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sympathetic', 'adj. 同情的', 4578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manifestation', 'n. 显示, 表现', 4579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excitement', 'n. 刺激, 兴奋', 4580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'porcupine', 'n. [动]豪猪', 4581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amaze', 'v. 使吃惊', 4582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barge', 'n. 驳船 vi猛撞', 4583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'keyboard', 'n. 键盘', 4584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hook', 'n. 钩 v. 钩住', 4585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'experimentation', 'n. 实验', 4586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'percussion', 'n. 碰撞, 打击乐器', 4587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plausible', 'adj. 似真实合理的', 4588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crisscross', 'v. 交叉, 来回移动 n. 十字形', 4589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blink', 'v&n. 眨眼, 闪烁', 4590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rift', 'n. 裂口 v. 裂开', 4591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiator', 'n. 暖气片，散热器', 4592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'myriad', 'adj. 无数的 n无数', 4593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clavichord', 'n. 翼琴(钢琴的前身)', 4594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trilobite', 'n. [古生]三叶虫', 4595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'converter', 'n. 转炉', 4596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'layout', 'n. 布局，安排', 4597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'claw', 'n. (脚)爪', 4598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repel', 'v. 排斥,击退', 4599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sierra', 'n. [地]齿状山脊, [鱼]马鲛', 4600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legitimate', 'adj. 合法的', 4601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plus', 'prep. 加上 a正的', 4602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'octopus', 'n. 章鱼', 4603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temporal', 'adj. 现世的, 暂时的', 4604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unpredictability', 'n. 不可预测性', 4605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minimalist', 'n. 最低限要求者', 4606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magical', 'adj. 魔术的, 神奇的', 4607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storefront', 'n. 店头, 店面', 4608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'makeshift', 'adj. 临时的 n. 临时替代物', 4609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plight', 'n. 困境', 4610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cactus', 'n. [植]仙人掌', 4611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solemn', 'adj. 庄严的,严肃的', 4612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reap', 'v. 收割, 收获', 4613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'improvise', 'v. 即兴创作', 4614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ascend', 'v. 攀登, 上升', 4615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'showman', 'n. 戏剧制作人, 玩杂耍的', 4616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'summit', 'n. 顶点, 最高阶层', 4617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appointment', 'n. 约会, 指定', 4618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lawyer', 'n. 律师', 4619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Alaskan', 'n. 阿拉斯加人 a阿拉斯加的', 4620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constrain', 'v. 强迫, 限制', 4621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exploitation', 'n. 开发, 开采', 4622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doctrine', 'n. 教条, 学说', 4623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immeasurably', 'adv. 无法计量地, 无限地', 4624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambition', 'n. 野心, 雄心', 4625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perpetuate', 'v. 使永存, 使不朽', 4626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afterlife', 'n. 来世, 后来的岁月', 4627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bask', 'v. 晒太阳', 4628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanitarian', 'n&a. 人道主义者(的)', 4629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shoemaker', 'n. 鞋匠', 4630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prairies', 'n. 大草原', 4631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handicraft', 'n. 手工艺(品)', 4632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'logically', 'adv. 符合逻辑地, 逻辑上地', 4633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'airstream', 'n. 气流', 4634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whoever', 'pron. 任何人, 无论谁', 4635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsafe', 'adj. 不安全的', 4636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flashbulb', 'n. [摄]闪光灯泡', 4637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bovine', 'adj. (似)牛的，迟钝的', 4638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thoughtful', 'adj. 深思的', 4639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ignite', 'v. 点火', 4640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'icicle', 'n. 冰柱', 4641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unbroken', 'adj. 不间断的', 4642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'funnel', 'n. 漏斗,烟囱', 4643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fastidious', 'adj. 过分讲究的, 挑剔的', 4644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overshadow', 'v. 遮蔽, 使失色', 4645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hare', 'n. 野兔', 4646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consult', 'v. 商量, 商议', 4647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inhospitable', 'adj. 不好客的,不适于居住的', 4648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artistically', 'adv. 艺术地, 在艺术上', 4649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pigmentation', 'n. 染色', 4650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quincy', 'n. 昆西(美国伊利诺斯州西部一城市)', 4651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afternoon', 'n. 午后', 4652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rumen', 'n. 瘤胃(反刍动物的第一胃)', 4653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aristocracy', 'n. 贵族（政治）', 4654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advise', 'v. 劝告, 忠告, 警告, 建议', 4655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impair', 'v. 损害,削弱', 4656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'greedy', 'adj. 贪婪的', 4657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'broadleaf', 'n. 阔叶烟草,阔叶树', 4658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pierce', 'v. 刺穿', 4659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bluish', 'adj. 带蓝色的', 4660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autobiographical', 'adj. 自传的', 4661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Parisian', 'n&a. 巴黎(人)(的)', 4662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'halfway', 'adj. 中途的ad半路地', 4663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instability', 'n. 不稳定(性)', 4664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fabricate', 'v. 编造, 虚构', 4665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ring', 'n. 环 v. 包围', 4666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embrace', 'v. 拥抱', 4667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corruption', 'n. 腐化；贪污', 4668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postwar', 'adj. 战后的', 4669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orange', 'n. 橘子', 4670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'license', 'n. 许可证 vt许可', 4671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heel', 'n. 脚后跟', 4672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whichever', 'pron. 无论那一个, 任何一个', 4673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brant', 'n. 黑雁', 4674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obsession', 'n. 迷住, 困扰', 4675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scurry', 'v. 疾行', 4676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subtropical', 'adj. 亚热带的', 4677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comfort', 'n. /v安慰', 4678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'banana', 'n. 香蕉', 4679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Vancouver', 'n. 温哥华（城市名)', 4680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thorn', 'n. [植]刺', 4681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'megawatt', 'n. 兆瓦特', 4682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cellar', 'n. 地窖, 地下室', 4683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pain', 'n. 痛苦 v. 使痛苦', 4684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arboreal', 'adj. 树木的', 4685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multicellular', 'adj. 多细胞的', 4686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hail', 'n. 雹 v. 下雹,高呼', 4687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slop', 'v. 溢出, 溅溢', 4688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spontaneously', 'adv. 自发地', 4689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limner', 'n. 素描者', 4690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elective', 'adj. 选举的,随意选择的', 4691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devour', 'v. 吞食,吞没', 4692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repertoire', 'n. 全部节目', 4693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swimmer', 'n. 游泳者', 4694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physically', 'adv. 身体上地', 4695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eagerly', 'adv. 热心地,急切地', 4696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protectionist', 'n. 保护贸易论(者)', 4697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'husbandry', 'n. 管理', 4698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barely', 'adv. 仅仅, 几乎不能', 4699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortification', 'n. 防御工事', 4700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ill', 'adj. 有病的,坏的', 4701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vascular', 'adj. 血管的,  脉管的', 4702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glassy', 'adj. 象玻璃的', 4703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trunk', 'n. 树干, 行李箱', 4704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenth', 'num. 第十, 十分之一', 4705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unavailable', 'adj. 难以获得的', 4706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sulfuric', 'adj. [化] 硫磺的,含硫的', 4707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'latest', 'adj. 最近的', 4708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'redefine', 'v. 重新定义', 4709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'greenhouse', 'n. 温室, 花房', 4710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instinctively', 'adv. 本能地', 4711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universally', 'adv. 普遍地', 4712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guard', 'n. 警戒 v. 守卫', 4713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clearer', 'adj. 更清楚的', 4714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'matrix', 'n. 矩阵', 4715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complaint', 'n. 诉苦, 抱怨', 4716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graduation', 'n. 毕业典礼', 4717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'huddle', 'n&v. 拥挤,挤作一团', 4718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bloom', 'v. (使)开花,(使)繁盛', 4719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epitome', 'n. 摘要', 4720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subspecies', 'n. [生]亚种', 4721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scrap', 'n. 碎片 v. 废弃', 4722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'celebration', 'n. 庆祝, 庆典', 4723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mist', 'n. 薄雾', 4724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'joy', 'n. 欢乐, 喜悦', 4725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'propel', 'v. 推进, 驱使', 4726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chalk', 'n. 粉笔', 4727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weaver', 'n. 织布者', 4728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dropstone', 'n. 滴石', 4729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unlimited', 'adj. 无限的；过渡的', 4730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respondent', 'n. 应答者, 被告', 4731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portrayal', 'n. 描画, 描写', 4732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'declare', 'v. 宣布，声明', 4733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curtain', 'n. 窗帘', 4734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hexagon', 'n. 六角形, 六边形', 4735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poetic', 'adj. 诗歌的', 4736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undisturbed', 'adj. 未受干扰的', 4737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ascent', 'n. 上升,提高', 4738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Talbot', 'n. [动]塔尔博特提猎狗', 4739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'query', 'n&v. 质问,疑问', 4740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evoke', 'v. 唤起, 引起', 4741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amass', 'v. 积累，积聚', 4742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poll', 'n. 民意测验, 投票', 4743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'causal', 'adj. 原因的', 4744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glide', 'v&n. 滑行', 4745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metalworker', 'n. 金工工人', 4746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sinuous', 'adj. 蜿蜒的', 4747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'floral', 'adj. 花的,像花的', 4748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grasp', 'v. 抓住,领会', 4749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incongruous', 'adj. 不协调的,不一致的', 4750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overlook', 'v&n. 俯瞰,忽视', 4751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adventurer', 'n. 冒险家', 4752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personalize', 'v. 个人化, 私人化', 4753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenant', 'n. 承租人, 房客', 4754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herbaceous', 'adj. 草本植物的', 4755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sap', 'n. 树液  vt耗尽', 4756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respective', 'adj. 分别的, 各自的', 4757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primordial', 'adj. 原始的,最初的', 4758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oversee', 'v. 监督，监管', 4759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deity', 'n. 神, 神性', 4760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phosphorus', 'n. 磷', 4761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unearned', 'adj. 不劳而获的', 4762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burrow', 'n. 洞穴 v. 挖地洞', 4763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infrequent', 'adj. 不频发的,不常见的', 4764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acclaim', 'n&v. 喝采, 欢呼', 4765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peg', 'n. 小钉 v. 钉，固定', 4766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'translation', 'n. 翻译, 译文', 4767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yarn', 'n. 纱线 v. 讲故事', 4768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plasma', 'n. 血浆', 4769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'London', 'n. 伦敦', 4770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'originality', 'n. 独创性', 4771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ford', 'n. 浅滩 v徒涉', 4772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mortise', 'n. 榫眼  v用榫接合', 4773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wander', 'v. 漫步, 徘徊', 4774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mate', 'n. 配偶, 对手', 4775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microbial', 'adj. 微生物的,  由细菌引起的', 4776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intervene', 'v. 干涉，干预', 4777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ironwork', 'n. 铁制品', 4778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unearth', 'v. 掘出', 4779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microbiologist', 'n. 微生物学家', 4780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'situate', 'v. 位于，坐落在', 4781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mallet', 'n. 槌棒', 4782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alcohol', 'n. 酒精,酒', 4783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guncotton', 'n. [军]强棉药', 4784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approval', 'n. 赞同,批准, 认可', 4785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fathom', 'n. 长度单位(6英尺)', 4786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accidental', 'adj. 意外的，偶然(发生)的', 4787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disastrous', 'adj. 灾难性的, 极糟的', 4788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'execute', 'v. 执行, 处决', 4789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supersonic', 'n&a. 超声波(的)', 4790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exemplify', 'v. 例证, 例示', 4791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sixth', 'num. 第六, 六分之一', 4792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sex', 'n. 性别,性', 4793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pantomime', 'n. 哑剧', 4794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alligator', 'n. 产于美洲的鳄鱼', 4795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuum', 'n. 连续统一体', 4796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transparent', 'adj. 透明的, 显然的', 4797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conscious', 'adj. 意识到的，自觉的', 4798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spherical', 'adj. 球(面、状)的', 4799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retail', 'n. ／v／ad零售', 4800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Japan', 'n. 日本', 4801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microwave', 'n. 微波(波长为1毫米至30厘米的高频电磁波)', 4802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adversely', 'adv. 不利地,逆向地', 4803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indirectly', 'adv. 间接地', 4804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domesticate', 'v. 驯养, 教化', 4805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'philosophical', 'adj. 哲学的, 达观的', 4806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deceive', 'v. 欺骗, 行骗', 4807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aesthetically', 'adv. 有审美能力地', 4808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anthropology', 'n. 人类学', 4809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'functionalism', 'n. 功能主义, 机能心理学', 4810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'talent', 'n. 天才,才能', 4811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuation', 'n. 继续(部分)；续篇', 4812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detach', 'v. 拆卸,使分开', 4813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydrodynamic', 'adj. 水力的', 4814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shoreline', 'n. 海岸线', 4815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sedge', 'n. [植]莎草', 4816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disproportionate', 'adj. 不成比例的', 4817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tanker', 'n. 油轮', 4818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lament', 'n. 悲伤v哀悼', 4819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'systematically', 'adv. 有系统地, 有条理地', 4820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curiosity', 'n. 好奇心', 4821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ancestral', 'adj. 祖先的', 4822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resume', 'v. (中断后)继续 n摘要；简历', 4823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eligible', 'adj. 有资格的, 合适的', 4824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absolutely', 'adv. 完全地, 绝对地', 4825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'senator', 'n. 参议员', 4826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pig', 'n. 猪', 4827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marvel', 'n. 令人惊奇的事物(或人物)', 4828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afraid', 'adj. 害怕的', 4829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'estuary', 'n. 河口, 江口', 4830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seismic', 'adj. [地]地震的', 4831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radius', 'n. 半径（范围）', 4832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'withdrawal', 'n. 收回, 撤退', 4833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ember', 'n. 灰烬, 余烬', 4834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'launch', 'vt&n. 发射', 4835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sorghum', 'n. [植]高粱属的植物', 4836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paleoecologist', 'n. 古生态学家', 4837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primal', 'adj. 最初的', 4838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regulatory', 'adj. 管理的, 控制的', 4839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'isotopic', 'adj. 同位素的,合痕的', 4840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'captain', 'n. 首领, 船长', 4841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extension', 'n. 延长, 扩充', 4842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ultimate', 'adj. 最后的, 最终的n终极(限)', 4843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'omit', 'v. 省略,遗漏', 4844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'applicable', 'adj. 合适的, 适用的,', 4845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snowstorm', 'n. 暴风雪', 4846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'macdonald', 'n. 麦当劳快餐店', 4847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locomotion', 'n. 运动, 移动', 4848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'persuasively', 'adv. 有说服力的', 4849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'livable', 'adj. 适于居住的', 4850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretty', 'adj. 漂亮的, 可爱的', 4851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dime', 'n. <美> 一角硬币', 4852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'testify', 'v. 证明, 证实', 4853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outlying', 'adj. 远离中心的，偏僻的', 4854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dollar', 'n. 元, 美元', 4855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lid', 'n. 盖子,vt给盖盖子', 4856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'privilege', 'n. 特权，优惠', 4857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ethological', 'n. 行为性的,  行为学的', 4858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disruption', 'n. 分裂', 4859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsistence', 'n. 生存, 生活, 留存', 4860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notwithstanding', 'prep. ／ ad尽管', 4861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autumn', 'n. 秋天', 4862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clip', 'n. 夹子 vt夹住', 4863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impetus', 'n. 推动力, 促进', 4864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grower', 'n. 种植者，栽培者', 4865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sophistication', 'n. 老练, 精明', 4866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instructive', 'adj. 有益的, 教育性的', 4867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manual', 'adj. 手工的 n手册,指南', 4868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mundane', 'adj. 平凡的, 世俗的', 4869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'raindrop', 'n. 雨滴, 雨点', 4870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appoint', 'v. 任命, 委派', 4871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inflation', 'n. 通货膨胀, 膨胀', 4872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sunflower', 'n. [植]向日葵', 4873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doorway', 'n. 门口', 4874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'injure', 'v. 伤害，损害', 4875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instigate', 'v. 鼓动', 4876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spill', 'v. (使)溢出 n溢出', 4877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'January', 'n. 一月(略作Jan)', 4878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gateway', 'n. 入口；通道', 4879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigorously', 'adv. 严格地', 4880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roam', 'v. 漫游, 闲逛', 4881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onrushing', 'adj. 猛冲的', 4882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tricycle', 'n. 三轮车', 4883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydrological', 'adj. 水文学的', 4884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foresee', 'v. 预见, 预知', 4885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ignorance', 'n. 无知', 4886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constitutional', 'adj. 法治的；体质的', 4887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orogeny', 'n. [地] 山岳之形成', 4888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accuse', 'v. 控告, 谴责', 4889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'administrator', 'n. 管理人,行政官', 4890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trainer', 'n. 训练者', 4891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temporarily', 'adv. 临时', 4892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'befit', 'v. 适合', 4893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compost', 'n. 混合肥料', 4894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaborator', 'n. 合作者', 4895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lodge', 'v. (让)暂住 n乡间小屋，旅舍', 4896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endow', 'v. 捐赠, 赋予', 4897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patience', 'n. 耐性, 忍耐', 4898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'residency', 'n. 居住, 住所', 4899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cosmopolitan', 'adj. 全球的,四海为家的 n世界主义者', 4900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shower', 'n. 阵雨, 淋浴', 4901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaborative', 'adj. 合作的, 协作的', 4902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'westerner', 'n. 美国之西部的人', 4903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refrigerate', 'v. 使冷冻, 使冷藏', 4904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clergy', 'n. 圣职者, 牧师', 4905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brewster', 'n. 酿造者', 4906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rage', 'n. 愤怒', 4907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'execution', 'n. 处决, 执行', 4908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tough', 'adj. 坚韧的，强硬的，困难的', 4909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skirt', 'n. 裙子', 4910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lithograph', 'n. 石版画, 平版印刷', 4911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cling', 'v. 紧贴, 附着', 4912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yew', 'n. 紫杉, 紫杉木', 4913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wholesale', 'n. 批发 adj. 大规模的', 4914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cart', 'n. 大车，手推车', 4915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adrift', 'a&ad. 漂流的,漫无目的', 4916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mystical', 'adj. 神秘的', 4917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coerce', 'v. 强制', 4918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crash', 'v. 碰撞，撞击', 4919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eccentricity', 'n. 反常，怪癖', 4920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distasteful', 'adj. 味道差的,反感的', 4921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tragedy', 'n. 悲剧, 惨案', 4922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lantern', 'n. 灯笼，提灯', 4923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diagram', 'n. 图表', 4924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spell', 'v. 拼写', 4925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'durability', 'n. 经久, 耐久力', 4926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stark', 'adj. 荒凉的；严酷的 adv. 完全', 4927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'code', 'n. 代码 vt把…编码', 4928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revere', 'v. 尊敬,敬畏', 4929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crush', 'vt&n. 压碎', 4930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'goose', 'n. 鹅', 4931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tabulate', 'v. 把制成表格', 4932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'please', 'adv. 请 v使高兴', 4933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uniquely', 'adv. adv独特地, 唯一地', 4934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'birch', 'n. 桦树, 白桦', 4935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adaptability', 'n. 适应性', 4936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caledonian', 'n&a. 苏格兰人(的)', 4937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strive', 'v. 努力, 奋斗', 4938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'qualitative', 'adj. 性质上的, 定性的', 4939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gram', 'n. 克', 4940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prohibitive', 'adj. 禁止的, 抑制的', 4941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prospector', 'n. 探勘者, 采矿者', 4942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contradiction', 'n. 反驳, 矛盾', 4943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auditorium', 'n. 听众席,观众席,', 4944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remark', 'n. 备注,评论 vt评论', 4945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rote', 'n. 死记硬背', 4946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'battleship', 'n. 战舰', 4947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regime', 'n. 政权制度,政权', 4948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skepticism', 'n. 怀疑论', 4949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'economist', 'n. 经济学者', 4950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commandment', 'n. 戒律', 4951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glimpse', 'n. 一瞥v瞥见', 4952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preferable', 'adj. 更好的,更合意的', 4953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delineate', 'v. 描绘', 4954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rugged', 'adj. 高低不平的, 崎岖的', 4955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'referent', 'n. 指示物', 4956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inadequacy', 'n. 不充分', 4957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Gypsy', 'n&a. 吉普赛人(的),吉普赛语（的）', 4958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outwash', 'n. [地质]冰水沉积', 4959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crumble', 'v. 弄碎,崩溃', 4960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissatisfaction', 'n. 不满', 4961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knap', 'v. 敲击', 4962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'basaltic', 'adj. 玄武岩的', 4963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plateau', 'n. 高地, 高原', 4964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carbonic', 'adj. (含)碳的', 4965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lengthy', 'adj. 冗长的', 4966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intersect', 'v. 贯穿, 交叉', 4967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'masterpiece', 'n. 杰作, 名著', 4968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Yale', 'n. 耶鲁', 4969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'redwood', 'n. [植]红杉', 4970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'connoisseur', 'n. 鉴赏家', 4971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accessory', 'n. 附件 adj. 辅助的', 4972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seriousness', 'n. 严肃, 认真', 4973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finely', 'adv. 细微地,美好地', 4974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preferentially', 'adj. 优先的, 优待的', 4975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquisition', 'n. 获得(物)', 4976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'march', 'n&v. 行军', 4977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lane', 'n. 小路, 小巷', 4978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sterile', 'adj. 贫脊的,不结果的', 4979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seaweed', 'n. 海草, 海藻', 4980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preschool', 'adj. 未满学龄的n幼儿园', 4981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smelt', 'v. 熔解，熔炼', 4982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'streambed', 'n. 河床', 4983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hint', 'n. 暗示,  线索', 4984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rally', 'n. 集会 v集合', 4985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'luckily', 'adv. 幸运地', 4986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drawback', 'n. 缺点,障碍', 4987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'successional', 'adj. 接连著的, 连续性的', 4988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drake', 'n. 公鸭, 蜉蝣类', 4989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salinization', 'n. 盐渍化', 4990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrinkage', 'n. 收缩', 4991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detachment', 'n. 冷漠, 脱离', 4992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oblige', 'v. 迫使；施恩于', 4993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gully', 'n. 小峡谷, 排水沟', 4994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inconclusive', 'adj. 非决定性的,不确定的', 4995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'innovator', 'n. 改革者, 革新者', 4996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pulverization', 'n. 弄成粉, 粉碎', 4997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homemaking', 'n. 家政', 4998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebuild', 'v. 重建, 改造', 4999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intestine', 'adj. 内部的,国内的', 5000);
