INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surplus', 'adj. 过剩的， 剩余的 < n. 过剩， 剩余', 8001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dynamical', 'adj. 动力的， 电动的；有生气的', 8002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'correspondence', 'n. 通信， 信件；符合， 一致；相当， 相似', 8003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refresh', 'vt. 精神振作， 精力恢复', 8004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inhibit', 'vt. 阻止， 妨碍， 抑制', 8005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intimate', 'adj. 亲密的； 密切的', 8006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'theft', 'n. 偷窃； 盗窃行为', 8007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disclose', 'vt. 揭示； 泄露', 8008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'declaration', 'n. 宣言， 宣布， 声明 <', 8009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'religion', 'n. 宗教， 信仰；信念， 信条', 8010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diagram', 'n. 图解， 图表', 8011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tragedy', 'n. 悲剧； 惨事， 灾难', 8012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'charm', 'n. 吸引力， 魅力 vt. 迷人， 使陶醉；施魔法于', 8013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oxide', 'n. 【化】 氧化物', 8014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'miniature', 'adj. 微型的， 缩小的 n. 缩小的模型， 缩图', 8015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosperous', 'adj. 繁荣的， 兴旺的', 8016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chart', 'n. 图， 图表', 8017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evoke', 'vt. 唤起， 引起', 8018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preface', 'n. 序言， 引言， 前言', 8019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fridge', 'n. 电冰箱', 8020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embryo', 'n. 胚， 胚胎 <；事物的萌芽期', 8021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tilt', 'v. 倾斜， 倾侧 n. 倾斜， 倾侧', 8022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secure', 'adj. 安全的； 可靠的； 放心的 vt. 得到某物， 获得；防护， 保卫', 8023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neutron', 'n. 【核】 中子 <', 8024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locomotive', 'adj. 运动的， 移动的， 运载的 n. 机车， 火车头', 8025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tile', 'n. 瓦片， 瓷砖', 8026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immense', 'adj. 广大的， 巨大的', 8027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avenue', 'n. 林荫道； 大街；途径， 手段', 8028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inherent', 'adj. 固有的， 内在的， 天生的', 8029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hay', 'n. 干草', 8030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perish', 'vi. 凋谢；丧生； 毁灭， 消亡', 8031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marathon', 'adj. 马拉松式的 n. 马拉松赛跑；马拉松式的活动', 8032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'definite', 'adj. 明确的； 肯定的； 限定的', 8033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pastime', 'n. 消遣， 娱乐', 8034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adapt', 'v. 适应， 适合 A；改编， 改写', 8035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'batch', 'n. 一批， 一组， 一群', 8036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intrinsic', 'adj. 内在的， 本质的， 固有的', 8037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'guilty', 'adj. 有罪的； 内疚的', 8038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outskirts', 'n. 郊区', 8039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lash', 'v. 将系牢；鞭打， 抽打； 猛烈打击；抨击， 斥责 n. 鞭打；眼睫毛 A <；鞭子， 鞭梢', 8040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'receipt', 'n. 收据， 收条；收到， 接到', 8041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basement', 'n. 建筑物的底部， 地下室， 地窖', 8042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capsule', 'n. 胶囊；太空舱', 8043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plural', 'adj. 复数的 n. 复数', 8044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'video', 'adj. 电视的； 视频的；录像的 n. 电视； 视频；录像', 8045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surroundings', 'n. 周围的事物， 环境', 8046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ozone', 'n. 臭氧；〈口〉新鲜空气', 8047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ecology', 'n. 生态学', 8048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prudent', 'adj. 谨慎的， 深谋远虑的', 8049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vote', 'v. 投票， 表决 n. 投票， 表决；选票， 选票数', 8050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'steady', 'adj. 稳定的， 不变的 <；坚定的， 扎实的 v. 稳固， 稳定', 8051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enclose', 'vt. 围住， 圈起， 封入 <', 8052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disease', 'n. 疾病， 弊病 A', 8053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notwithstanding', 'adv. 尽管 conj. 尽管 < prep. 尽管 <', 8054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'technician', 'n. 技术员， 技师， 技工', 8055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'endorse', 'vt. 赞同， 认可；代言；背书； 在背面签名<', 8056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marital', 'adj. 婚姻的； 夫妻的', 8057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alike', 'adv. 也； 同样地 adj. 相同的， 相像的', 8058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genius', 'n. 天才； 创造力 A', 8059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clarity', 'n. 清晰， 明晰', 8060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infrastructure', 'n. 基础结构； 基础设施 <', 8061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'typical', 'adj. 典型的， 有代表性的', 8062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'watt', 'n. 瓦， 瓦特', 8063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'buzz', 'vi. 发出嗡嗡声；充满兴奋 n. 嗡嗡声；嘈杂的谈话声', 8064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tray', 'n. 盘， 碟， 托盘', 8065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notorious', 'adj. 臭名昭著的， 声名狼藉的； 众所周知的', 8066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hydrogen', 'n. 氢', 8067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infant', 'n. 婴儿， 幼儿 <', 8068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'millimeter', 'n. 毫米', 8069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carbon', 'n. 碳', 8070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unload', 'v. 卸， 卸下', 8071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circus', 'n. 马戏团， 杂技团', 8072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dinosaur', 'n. 恐龙；过时的人或事物', 8073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tram', 'n. 有轨电车 <', 8074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'odour', 'n. 气味； 名声', 8075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deprive', 'vt. 夺去， 使丧失', 8076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resultant', 'adj. 作为结果而发生的；合成的', 8077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pest', 'n. 害虫； 有害物', 8078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pedal', 'n. 踏板 vt. 踩踏板， 骑自行车', 8079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heritage', 'n. 遗产； 继承物；传统', 8080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supreme', 'adj. 极度的； 最重要的；至高的， 最高的 <', 8081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ambulance', 'n. 救护车', 8082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slope', 'v. 倾斜 n. 斜坡， 斜面；倾斜， 斜度', 8083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'philosophy', 'n. 哲学', 8084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'junior', 'adj. 年少的， 年幼的；低年级的；后进的， 下级的；三年级的 n. 年少者， 低班生；下级， 晚辈；三年级学生', 8085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lapse', 'vi. 终止， 失效；陷入…状态 A n. 失误， 疏忽；行为失检， 失足；流逝； 间隔', 8086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'latent', 'adj. 潜在的， 潜伏的， 不易察觉的 <', 8087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terrific', 'adj. 极好的；非常的， 极度的', 8088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'standpoint', 'n. 立场， 观点', 8089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'worship', 'v. 崇拜， 敬仰， 尊敬；做礼拜 A n. 礼拜， 礼拜仪式；崇拜， 敬仰', 8090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lawn', 'n. 草地， 草坪', 8091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pirate', 'n. 海盗；盗版 vt. 盗版', 8092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stubborn', 'adj. 顽固的， 倔强的；难对付的， 难以克服的', 8093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formulate', 'vt. 构想， 形成；系统地阐述', 8094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emigrate', 'vi. 自本国移居他国', 8095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alien', 'adj. 外国的 <；相异的；不相容的 n. 外侨；外星人', 8096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layer', 'n. 层', 8097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'triangle', 'n. 三角', 8098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'linguistic', 'adj. 语言的， 语言学的', 8099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elite', 'n. 上层人士； 掌权人物； 实力集团； 精英', 8100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ornament', 'v. 装饰， 美化 n. 装饰， 装饰物', 8101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'helmet', 'n. 头盔， 钢盔', 8102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ivory', 'n. 象牙；象牙色， 乳白色', 8103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'theme', 'n. 题目， 主题', 8104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'smash', 'v. 打碎， 粉碎 n. 打碎， 粉碎', 8105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'henceforth', 'adv. 今后 <', 8106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'editor', 'n. 编辑， 编者', 8107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barrel', 'n. 桶；枪管， 炮管', 8108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'efficient', 'adj. 有效的， 效率高的；有能力的， 能胜任的', 8109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'murmur', 'v. 小声说；小声抱怨； 咕哝 n. 小声说； 小声抱怨； 咕哝', 8110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unify', 'v. 联合， 统一；相同； 一致', 8111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unfortunately', 'adv. 不幸地； 可惜地', 8112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consistent', 'adj. 前后一致的， 始终如一的', 8113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disgrace', 'n. 失宠；耻辱 vt. 使失宠；玷污， 使蒙羞', 8114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reverse', 'adj. 相反的； 倒转的 v. 颠倒， 倒转； 倒退 n. 相反， 反转， 颠倒；背面， 后面', 8115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barren', 'adj. 贫瘠的， 荒芜的；不结果实的； 不育的；无益的；没有结果的， 没有意义的', 8116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sword', 'n. 剑， 刀', 8117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'permanent', 'adj. 永久的， 持久的', 8118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foster', 'adj. 收养的； 收养孤儿的 A vt. 培养， 培育；鼓励； 促进；领养', 8119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chap', 'n. 小伙子， 家伙', 8120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summarize', 'v. 概括， 总结', 8121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'facility', 'n. 才能， 天赋', 8122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incidence', 'n. 发生', 8123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beam', 'vi. 微笑；发光 n. 梁， 桁条；束； 柱 A', 8124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'civilization', 'n. 文明， 文化', 8125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fiction', 'n. 虚构， 编造；小说', 8126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cucumber', 'n. 黄瓜', 8127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'replace', 'vt. 替换； 取代；放回； 归还', 8128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aviation', 'n. 航空， 飞行', 8129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appointment', 'n. 任命， 委任；约定， 指定', 8130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hip', 'n. 臀部， 髋部', 8131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pessimistic', 'adj. 悲观的', 8132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emphasis', 'n. 强调； 重点', 8133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interrupt', 'v. 中断， 遮断， 阻碍 A；打断， 打扰', 8134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'worldwide', 'adv. 遍及全世界 adj. 全世界的， 世界范围的', 8135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feasible', 'adj. 可行的', 8136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prescribe', 'vt. 指示， 规定；开处方， 开', 8137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flatter', 'vt. 奉承； 使高兴 <', 8138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'potential', 'adj. 潜在的， 可能的；【物】势的， 位的 n. 潜能， 潜力', 8139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bean', 'n. 豆， 菜豆， 蚕豆', 8140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hostess', 'n. 女主人； 女主持人 A', 8141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turbine', 'n. 汽轮机， 透平机， 涡轮机', 8142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lounge', 'vi. 斜倚， 躺卧； 闲逛 n. 休息室； 起居室， 客厅', 8143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gross', 'adj. 总的， 毛的 <；显而易见的； 粗鲁的 n. 总额', 8144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'workshop', 'n. 车间， 工场；专题讨论会', 8145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'porch', 'n. 门廊', 8146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resist', 'v. 抵抗， 反抗；抗， 忍得住， 抵制', 8147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stimulate', 'vt. 刺激， 使兴奋 <；激励， 鼓舞', 8148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eclipse', 'n. 食', 8149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soak', 'v. 吸收；浸泡， 浸湿 A', 8150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soar', 'vi. 猛增， 剧增；高飞， 翱翔 A；高涨 A；高耸， 屹立', 8151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interference', 'n. 干涉， 干预；妨碍， 打扰', 8152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fibre', 'n. 纤维， 纤维质', 8153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commute', 'vi. 乘公交车上下班， 经常乘车往返于两地； 通勤 n. 在两地之间坐车往返； 通勤', 8154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sustain', 'vt. 支撑， 承受住；维持， 持续；遭受； 忍耐 <', 8155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'classify', 'vt. 分类； 分等 <', 8156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'altitude', 'n. 高度， 海拔', 8157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'colony', 'n. 殖民地', 8158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'credentials', 'n. 证明书； 证件；资格', 8159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wagon', 'n. 运货马车； 运货车；敞篷车厢', 8160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shepherd', 'n. 牧民， 牧羊人', 8161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'debut', 'n. 初次登台；处女作 vt. 面世， 首次推出', 8162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uphold', 'vt. 支持， 维护； 维持， 确认 <', 8163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dimension', 'n. 尺寸； 尺度；维； 度； 元', 8164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deserve', 'vt. 应受， 值得', 8165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'process', 'n. 过程， 进程；工序， 制作法； 工艺 vt. 加工； 处理', 8166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'philosopher', 'n. 哲学家， 哲人', 8167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'restore', 'vt. 恢复； 使复原；归还， 交还；修复， 重建', 8168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sprout', 'vi. 抽条， 发芽 n. 芽， 幼苗', 8169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nostalgic', 'adj. 怀旧的', 8170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chef', 'n. 厨师长， 厨师', 8171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alternative', 'adj. 供选择的 n. 替换物， 选择对象', 8172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'banner', 'n. 旗', 8173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'encounter', 'n. 遇到， 遭遇 vt. 遇到， 遭遇 <', 8174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soda', 'n. 苏打水， 汽水', 8175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'approve', 'vi. 赞成， 同意； 满意 vt. 批准， 审定， 通过 <', 8176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chew', 'v. 咀嚼 <；思量', 8177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pedestrian', 'adj. 徒步的；缺乏想象的 n. 行人', 8178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'account', 'vi. 说明， 解释；占；导致， 引起 n. 账目； 账户；叙述， 说明', 8179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uneasy', 'adj. 不安的， 焦虑的；不稳定的； 紧张的', 8180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sometime', 'adv. 曾经； 在某一时刻； 有一天', 8181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mostly', 'adv. 主要地， 大部分， 通常', 8182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radioactive', 'adj. 放射性的， 放射引起的', 8183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appall', 'vt. 使惊骇， 使恐怖', 8184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'innocent', 'adj. 清白的， 无罪的；无害的； 没有恶意的；天真的， 单纯的； 无知的', 8185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alphabet', 'n. 字母表', 8186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stride', 'vi. 大步走， 迈进； 跨过 n. 迈步， 阔步', 8187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tramp', 'v. 步行； 跋涉 n. 流浪者；步行； 跋涉', 8188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'traitor', 'n. 叛徒， 卖国贼', 8189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appreciate', 'vt. 感谢， 感激；正确评价； 欣赏， 赏识 A', 8190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trim', 'adj. 整齐的， 整洁的 < vt. 整理， 修整 <；装饰 n. 整理， 修整； 装饰', 8191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'qualitative', 'adj. 性质上的， 定性的', 8192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dental', 'adj. 牙齿的， 牙科的', 8193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diverse', 'adj. 多种多样的， 不同的', 8194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rally', 'v. 集合， 团结；恢复， 重新振作 n. 集会；公路汽车赛', 8195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prime', 'adj. 首要的， 主要的；最好的， 第一流的 n. 青春， 青壮年时期； 全盛时期', 8196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sofa', 'n. 沙发', 8197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'festival', 'n. 节日； 欢宴；音乐节， 戏剧节', 8198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loyal', 'adj. 忠诚的， 忠贞的', 8199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preference', 'n. 偏爱， 喜爱 A；优惠， 优先选择', 8200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'court', 'n. 法院， 法庭；宫廷， 朝廷；院子；球场 A', 8201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distort', 'vt. 歪曲， 扭曲 <', 8202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'venture', 'vi. 敢于； 大胆表示 vt. 冒险； 大胆行事 n. 冒险；冒险行动；投机活动； 商业冒险； 企业', 8203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discern', 'vt. 认出， 发现；辨别， 识别', 8204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'route', 'n. 路线， 路程', 8205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enthusiasm', 'n. 热情， 热心', 8206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flexible', 'adj. 柔韧的， 易弯曲的； 灵活的， 可变通的', 8207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'organ', 'n. 器官；机构；风琴', 8208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mirror', 'n. 镜子；反映， 反射 vt. 反映， 反射', 8209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obstruction', 'n. 【律】阻碍；妨碍；障碍', 8210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'depict', 'vt. 描绘； 描写， 描述', 8211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shiver', 'n. /', 8212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hop', 'vi. 单足跳跃， 单足跳行；齐足跳跃， 齐足跳行 n. 蹦跳；短程航行', 8213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liquor', 'n. 酒， 烈性酒', 8214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'honourable', 'adj. 可敬的；荣誉的， 光荣的', 8215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vanity', 'n. 虚荣心， 浮华', 8216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'characteristic', 'adj. 特有的， 独特的 n. 特征， 特性', 8217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interior', 'adj. 内部的， 里面的 < n. 内部， 内地', 8218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rouse', 'vt. 惊起；唤起， 唤醒', 8219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spark', 'v. 导致， 产生；冒火花， 飞火星 n. 火花， 火星 A', 8220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'integral', 'adj. 构成整体所必需的；完整的 <', 8221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lubricate', 'vt. 润滑； 加润滑油于', 8222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comet', 'n. 彗星', 8223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assembly', 'n. 集合， 集会， 会议；装配', 8224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hearing', 'n. 听， 倾听 A；听力；审讯', 8225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bully', 'n. 恃强凌弱者 vt. 恐吓， 欺负', 8226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chip', 'n. 碎片；薄片；芯片', 8227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chin', 'n. 下巴， 颏', 8228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'piston', 'n. 活塞', 8229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pistol', 'n. 手枪', 8230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assemble', 'v. 集合， 集会；装配， 组装', 8231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blast', 'v. 爆炸， 爆破 n. 一阵， 一股；爆炸冲击波；管乐器或汽笛声', 8232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mutter', 'v. 咕哝； 抱怨', 8233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'repel', 'vt. 击退；抵制， 拒绝 <；排斥； 讨厌', 8234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'series', 'n. 一系列， 连续；丛书', 8235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'junk', 'n. 废旧杂物； 垃圾 < vt. 丢弃， 废弃', 8236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cultivate', 'vt. 耕作， 栽培； 养殖；培养， 教养； 磨炼', 8237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thrive', 'vi. 兴旺， 繁荣 A', 8238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imaginative', 'adj. 富有想象力的； 爱想象的', 8239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analytic', 'adj. 分析的； 分解的', 8240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'purse', 'n. 钱包', 8241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'represent', 'vt. 描述； 表示；代表， 代理；阐明， 说明', 8242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'celebrity', 'n. 名望， 著名， 名声；知名人士', 8243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dispatch', 'vt. 派遣， 调遣； 发送 n. 急件， 快信；新闻报道', 8244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accountant', 'n. 会计人员， 会计师', 8245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sympathise', 'vi. 同情， 体谅； 共鸣， 同感', 8246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trail', 'n. 踪迹， 痕迹；小道 vt. 追踪， 跟踪', 8247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cyberspace', 'n. 计算机世界， 网络空间', 8248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absurd', 'adj. 荒唐的', 8249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prior', 'adv. 优先， 在…之前 < adj. 优先的， 在前的', 8250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'burglar', 'n. 窃贼， 破门盗窃者', 8251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trait', 'n. 特征， 特点， 特性', 8252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vanish', 'v. 消失， 消散', 8253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sightseeing', 'n. 观光， 游览', 8254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'planet', 'n. 行星', 8255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generalise', 'v. 归纳， 概括；推广， 普及', 8256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ashore', 'adv. 在岸上； 上岸', 8257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creep', 'vi. 爬， 爬行；蔓延', 8258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scholar', 'n. 学者', 8259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vision', 'n. 视觉， 视力；眼光， 洞察力', 8260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accompany', 'vt. 陪同， 伴随；为…伴奏', 8261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thereof', 'adv. 由此， 因此', 8262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beneficial', 'adj. 有利的， 有益的', 8263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reckon', 'vi. 指望； 想要 vt. 认为， 估计；计算， 测算', 8264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excerpt', 'n. 摘录， 选录， 节录', 8265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confusion', 'n. 混乱， 混淆', 8266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'auditorium', 'n. 礼堂；观众席', 8267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hinge', 'n. 合页， 铰链', 8268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blank', 'adj. 空白的， 空着的；失色的， 无表情的 n. 空白；表格', 8269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'landlord', 'n. 房东； 地主', 8270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analytical', 'adj. 分析的； 分解的', 8271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'session', 'n. 会议， 一届会议', 8272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'additional', 'adj. 附加的， 额外的 <', 8273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reception', 'n. 接待； 招待会；接收， 接受； 接收效果', 8274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tank', 'n. 坦克 A；罐， 槽， 箱', 8275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outward', 'adv. 向外， 在外 adj. 向外的； 外面的； 外表的', 8276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bloody', 'adj. 流血的； 血腥的', 8277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sole', 'adj. 单独的， 唯一的；专有的， 独用的 < n. 脚垫， 鞋底', 8278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vapour', 'n. 蒸汽', 8279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jury', 'n. 陪审团', 8280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lumber', 'n. 木材， 木料', 8281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'holy', 'adj. 神圣的， 圣洁的', 8282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'idiot', 'n. 白痴， 傻子', 8283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solo', 'adj. 单独的， 单独进行的 n. 独奏 ， 独唱 ， 独舞', 8284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tuition', 'n. 学费 <', 8285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'postage', 'n. 邮费， 邮资', 8286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tame', 'adj. 驯服的， 温顺的 <；沉闷的， 乏味的 vt. 驯服， 制服', 8287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adjoin', 'v. 毗连， 靠近', 8288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spectacular', 'adj. 壮观的； 引人注目的 n. 壮观的演出', 8289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peculiar', 'adj. 古怪的， 异常的 A <；特殊的， 特有的 <', 8290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'idiom', 'n. 习语', 8291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hug', 'n. /', 8292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'muscular', 'adj. 肌肉的；肌肉发达的；强健的', 8293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hum', 'v. 哼曲子；发嗡嗡声；忙碌； 活跃， 充满活力 n. 嗡嗡声， 营营声， 嘈杂声', 8294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sparkle', 'v. 发火花， 闪耀', 8295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'envy', 'n. /', 8296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'staple', 'adj. 主要的；经常需要的 n. 订书钉，；主食；主要产品 vt. 用订书钉订， 把…订起来', 8297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hut', 'n. 小屋， 棚屋', 8298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memo', 'n. 备忘录 <', 8299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'royalty', 'n. 王家， 王族 A', 8300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'collaborate', 'vi. 协作， 合作', 8301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superficial', 'adj. 表面的 <；肤浅的， 浅薄的 <', 8302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'executive', 'adj. 执行的， 实施的 n. 总经理； 董事； 行政负责人', 8303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tablet', 'n. 药片；碑， 匾； 平板', 8304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hook', 'v. 钩； 钓 n. 钩； 吊钩； 钩状物', 8305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'melt', 'v. 融化， 熔化', 8306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'action', 'n. 行动， 行为；动作， 活动；作用', 8307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stadium', 'n. 体育场', 8308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highland', 'n. 高地， 高原', 8309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'displacement', 'n. 移置， 转移； 取代', 8310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'casualty', 'n. 伤亡人员； 受害人', 8311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gauge', 'n. 标准尺寸， 规格； 量规， 量表', 8312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chop', 'vt. 砍， 劈， 斩 n. 排骨； 肉块', 8313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sensitive', 'adj. 敏感的， 灵敏的；易受伤害的', 8314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'protest', 'v. 抗议， 反对 n. 抗议， 反对', 8315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vacant', 'adj. 未占用的， 空着的', 8316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'culprit', 'n. 罪犯', 8317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underground', 'adv. 在地下； 秘密地 adj. 地下的， 地面下的；秘密的 n. 地铁', 8318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impression', 'n. 印象； 感想；盖印， 压痕', 8319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'machinery', 'n. 机器， 机械； 机制', 8320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shield', 'n. 防护物， 护罩；盾， 盾状物 A vt. 保护， 防护', 8321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inference', 'n. 推理， 推论， 推断；推断结果， 结论', 8322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deliver', 'v. 交付， 递送； 释放；发表； 表达；接生', 8323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instantaneous', 'adj. 瞬间的， 即刻的', 8324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'phenomenon', 'n. 现象', 8325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obsession', 'n. 牵挂， 惦念；迷住， 入迷； 困扰；萦绕于心的事物或人；固执的念头 <', 8326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notify', 'vt. 通知， 告知； 报告', 8327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barbecue', 'n. 金属烤架；烧烤野餐 vt. 在烤架上烧烤', 8328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'file', 'n. 锉刀；文件， 档案 vt. 锉', 8329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bibliography', 'n. 书目； 参考书目', 8330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generalize', 'v. 归纳， 概括；推广， 普及', 8331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heave', 'vt. 举起， 提起；扔 n. 举起； 升降', 8332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nourish', 'vt. 提供养分， 养育', 8333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grease', 'n. 动物脂， 油脂； 润滑油 vt. 抹油； 润滑', 8334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'allege', 'vt. 断言， 宣称', 8335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torch', 'n. 手电筒；火炬， 火把', 8336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'positive', 'adj. 积极的； 肯定的 <；确实的， 明确的；〈美〉正电的； 【化】阳性的；十足的， 完全的 n. 正片', 8337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trigger', 'n. 扳机 vt. 引发， 导致 <', 8338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'favourite', 'adj. 特别喜欢的， 中意的 n. 最喜欢的人或物', 8339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'segregate', 'vt. 隔离， 分开', 8340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prospect', 'n. 景色；前景， 前途， 展望', 8341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radar', 'n. 雷达', 8342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'withhold', 'vt. 拒给， 不给；使停止； 阻挡', 8343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refugee', 'n. 难民， 流亡者', 8344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specialize', 'vi. 专攻； 专用于； 专业化', 8345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotate', 'v. 旋转', 8346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instance', 'n. 例子， 事例， 例证', 8347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conscience', 'n. 良心， 良知 A', 8348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'banquet', 'n. 宴会， 盛宴', 8349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thrill', 'n. 令人激动的事 vt. 使激动， 使兴奋；使毛骨悚然', 8350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reptile', 'n. 爬行动物', 8351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cassette', 'n. 盒子；盒式磁带', 8352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blade', 'n. 刃， 刀片；叶片', 8353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solution', 'n. 解答， 解决办法；溶解， 溶液', 8354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opponent', 'adj. 对立的， 对抗的 n. 对手， 反对者， 敌手', 8355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'host', 'n. 主人； 旅店老板；节目主持人；一大群， 许多 vt. 主持； 作为主人招待', 8356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accelerate', 'vt. 加速； 促进', 8357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'backward', 'adv. 向后， 朝反方向 < adj. 向后的； 落后的； 倒行的；迟钝的', 8358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'regardless', 'adj. 不留心的， 不注意的；不管', 8359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jolly', 'adv. 非常 adj. 欢乐的， 高兴的', 8360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'upward', 'adv. 向上， 往上， …以上 adj. 向上的， 上升的', 8361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illustrate', 'vt. 举例说明， 阐明；图解， 加插图', 8362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specialise', 'vi. 专攻； 专用于； 专业化', 8363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hose', 'n. 水龙带， 软管 vt. 用软管', 8364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breeze', 'n. 微风， 和风 A', 8365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dentist', 'n. 牙医', 8366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trash', 'n. 垃圾， 废物；拙劣的文学作品；没用的人， 社会渣滓 vt. 捣毁， 破坏', 8367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'millimetre', 'n. 毫米', 8368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horn', 'n. 角， 触角；号， 喇叭；角状物； 角制品 A', 8369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infer', 'vt. 推论， 推断', 8370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specialist', 'n. 专家', 8371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transit', 'n. 运输， 载运 vt. 通过， 经过', 8372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tactics', 'n. 策略， 战术', 8373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adolescent', 'adj. 青春期的， 青少年的 n. 青少年 A', 8374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sore', 'adj. 疼痛的； 痛心的 n. 痛处， 疮口', 8375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petty', 'adj. 小的； 琐碎的；气量小的', 8376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glow', 'vi. 发热， 发光， 发红 n. 光亮； 光辉', 8377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'laughter', 'n. 笑， 笑声', 8378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sentiment', 'n. 思想感情； 情绪； 情操', 8379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strife', 'n. 冲突， 斗争， 纷争； 竞争', 8380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'patent', 'adj. 专利的， 特许的 n. 专利； 专利品； 专利权 vt. 批准专利， 获得专利', 8381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certificate', 'n. 证书； 执照', 8382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'racket', 'n. 球拍', 8383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mess', 'n. 混乱， 混杂； 脏乱 vt. 弄脏， 弄乱， 搞糟', 8384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sour', 'adj. 酸的； 发酸的； 酸痛的；脾气坏的； 刻薄的', 8385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delete', 'vt. 删除', 8386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'speciality', 'n. 特产； 特色菜；专业； 专长', 8387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transform', 'vt. 改变， 变换； 使改观；变压； 转化 A；改造， 改革', 8388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plumber', 'n. 管子工， 铅管工， 水暖工', 8389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leadership', 'n. 领导', 8390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnitude', 'n. 大小， 数量；巨大， 广大；重要性， 重要程度', 8391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genuine', 'adj. 真正的， 名副其实的 <', 8392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agitate', 'vi. 鼓动 vt. 使激动， 使不安；搅动， 搅拌 A', 8393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immune', 'adj. 免疫的， 有免疫力的 A；不受影响的；免除的， 豁免的', 8394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brochure', 'n. 小册子', 8395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spokesman', 'n. 发言人', 8396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equation', 'n. 等式， 方程式；相等； 均衡', 8397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impressive', 'adj. 给人深刻印象的；威严的； 使人敬畏的', 8398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stern', 'adj. 严厉的； 苛刻的； 难以忍受的；坚决的， 坚定的 n. 船尾， 舟尾', 8399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rotary', 'adj. 旋转的', 8400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compound', 'adj. 混合的； 化合的； 复合的 n. 混合物， 化合物', 8401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'master', 'adj. 主要的 n. 男主人； 雇主；师傅； 大师， 名家；硕士 vt. 精通， 掌握', 8402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ruby', 'n. 红宝石', 8403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underlie', 'vt. 位于…之下；构成…的基础', 8404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extraordinary', 'adj. 非常的， 格外的', 8405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'regulation', 'n. 规则， 规章；调节， 校准， 调整', 8406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complicate', 'v. 变复杂', 8407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'puzzle', 'n. 难题； 谜； 迷惑 vt. 使迷惑， 使为难', 8408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hypocrisy', 'n. 伪善， 虚伪', 8409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evident', 'adj. 明显的， 明白的', 8410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accommodation', 'n. 住宿， 留宿', 8411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mere', 'adj. 纯粹的 A；仅仅， 只不过', 8412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suburb', 'n. 市郊， 郊区', 8413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simplify', 'vt. 简化； 使单纯', 8414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'annoy', 'vt. 使恼怒， 使生气；打搅', 8415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glue', 'n. 胶， 胶水 vt. 胶合， 粘贴', 8416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reflect', 'vi. 反省， 细想； 考虑 vt. 反映； 表现', 8417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contribution', 'n. 贡献；捐献， 捐款 A', 8418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'procession', 'n. 队伍， 行列', 8419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outfit', 'n. 全套装备； 全套工具', 8420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Marxist', 'adj. 马克思主义的 n. 马克思主义者', 8421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'massacre', 'vt. 大规模屠杀， 残杀；彻底击败 n. 大屠杀， 残杀；惨败', 8422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ignorant', 'adj. 无知的， 愚昧的； 不知道的', 8423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'negligible', 'adj. 可以忽略的， 微不足道的', 8424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'setback', 'n. 挫折； 倒退； 失败', 8425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spray', 'n. 喷雾， 飞沫；浪花， 水花 < vt. 喷洒， 喷射', 8426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distinguish', 'vt. 区别， 辨别； 辨认出；使杰出； 使著名', 8427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'howl', 'vi. 嗥叫， 呼啸 vt. 吼叫， 哀号 n. 嗥叫； 呼啸；吼叫； 哀号', 8428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vitamin', 'n. 维生素 <', 8429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intention', 'n. 意图， 意向， 目的', 8430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rude', 'adj. 粗鲁的， 无礼的；猛烈的， 残暴的；粗糙的， 粗陋的', 8431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enthusiastic', 'adj. 热情的， 热心的', 8432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symptom', 'n. 症状；征候， 征兆', 8433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thereby', 'adv. 因此， 从而', 8434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disastrous', 'adj. 灾难性的', 8435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'funeral', 'n. 丧葬， 葬礼', 8436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impulse', 'n. 推动；冲动； 刺激', 8437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infectious', 'adj. 传染的， 传染性的； 有感染力的', 8438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'religious', 'adj. 宗教的； 信教的； 虔诚的', 8439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nevertheless', 'adv. 仍然， 不过 conj. 然而， 不过', 8440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prominent', 'adj. 突起的， 凸出的；杰出的， 著名的', 8441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superiority', 'n. 优越性， 优势 <', 8442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jewel', 'n. 宝石， 宝石饰物', 8443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fundamental', 'adj. 基础的， 基本的', 8444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'global', 'adj. 全球的， 世界的', 8445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entitle', 'vt. 给以权利；给…以称号； 给…题名', 8446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outline', 'n. 轮廓， 略图；大纲， 梗概 vt. 概述， 略述', 8447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fade', 'v. 褪色；衰减， 消失', 8448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nominal', 'adj. 名义上的；微不足道的', 8449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excess', 'adj. 过量的， 额外的 n. 过量， 过剩', 8450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thrift', 'n. 节约， 节俭', 8451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perspective', 'n. 透视画法； 透视图；远景， 前途；观点， 看法', 8452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'galaxy', 'n. 星系； 银河 A <；一群 A <', 8453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equality', 'n. 同等， 平等', 8454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dictation', 'n. 听写， 口述； 命令', 8455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rebellion', 'n. 叛乱， 反抗， 起义', 8456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invade', 'v. 侵入， 侵略， 侵害', 8457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accordance', 'n. 一致， 符合', 8458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'weary', 'adj. 疲倦的；令人厌烦的 vt. 使疲倦， 使厌倦', 8459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thorough', 'adj. 彻底的， 完全的；细心的； 认真的； 周到的', 8460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'democracy', 'n. 民主； 民主制； 民主国家', 8461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peninsula', 'n. 半岛', 8462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evolve', 'v. 发展， 进化', 8463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abandon', 'vt. 放弃， 抛弃', 8464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'congratulation', 'n. 祝贺；祝贺词', 8465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marvelous', 'adj. 令人惊奇的； 奇迹般的； 〈口〉妙极的', 8466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'household', 'adj. 家庭的 n. 户， 家庭； 全家人', 8467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adverse', 'adj. 不利的， 有害的', 8468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bulletin', 'n. 公报， 公告， 告示', 8469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ratio', 'n. 比， 比率', 8470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'junction', 'n. 连接， 接合；交叉点， 接合处， 枢纽站', 8471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instinct', 'n. 本能， 天性； 直觉', 8472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cannon', 'n. 加农炮， 大炮', 8473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'afterward', 'adv. 后来， 以后', 8474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reputation', 'n. 名声， 声望', 8475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shrug', 'v. 耸肩 n. 耸肩', 8476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'independence', 'n. 独立， 自主', 8477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'restrain', 'vt. 抑制， 制止', 8478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'awkward', 'adj. 笨拙的， 不灵活的；棘手的； 尴尬的；使用不便的', 8479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ruin', 'v. 毁灭， 毁坏； 破产； 堕落 n. 毁灭， 崩溃', 8480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mutton', 'n. 羊肉', 8481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impatient', 'adj. 不耐烦的， 急躁的', 8482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spill', 'v. 溢出， 溅出 n. 摔下， 跌下', 8483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cradle', 'n. 摇篮 A；发源地', 8484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'collection', 'n. 收藏， 收集', 8485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'finding', 'n. 发现， 发现物', 8486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'laboratory', 'n. 实验室， 研究室', 8487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Latin', 'adj. 拉丁的； 拉丁文的 n. 拉丁语', 8488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inspect', 'vt. 检查， 调查， 视察', 8489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'campaign', 'n. 战役；活动； 竞选运动', 8490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vital', 'adj. 生死攸关的， 重大的；生命的， 生机的', 8491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conflict', 'vi. 抵触， 冲突 A n. 战斗， 斗争；矛盾， 冲突', 8492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'update', 'vt. 更新； 使现代化', 8493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detect', 'vt. 察觉， 发觉；侦察， 探测', 8494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amateur', 'adj. 业余的 n. 业余活动者', 8495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'condemn', 'vt. 谴责， 指责 A；判刑， 宣告有罪', 8496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commerce', 'n. 商业， 贸易', 8497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assistance', 'n. 帮助， 援助', 8498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gulf', 'n. 海湾', 8499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'definition', 'n. 定义， 解释', 8500);
