INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shortage', 'n.  不足， 缺乏', 12501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blush', 'vi. 脸红；羞愧 n.  脸上泛起的红晕', 12502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overgraze', 'v.  过度放牧', 12503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dubious', 'adj.  怀疑的， 拿不准的； 可疑的， 靠不住的', 12504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clipper', 'n.  快速帆船； 剪刀', 12505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swift', 'adj. 敏捷的，速度快的 n.  雨燕', 12506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ductile', 'adj.  有延性的， 韧性的； 易引导的， 易受影响的', 12507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conciliate', 'vt.  安抚， 抚慰； 调和', 12508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utensil', 'n.  用具； 器皿', 12509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accede', 'vi.  即位， 就任； 同意', 12510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ratify', 'vt.  正式批准， 使正式生效', 12511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vivify', 'vt.  赋予生气； 使生动， 使活跃', 12512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pose', 'vt. 摆姿势；造成；提出 n.  姿势', 12513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amend', 'vt.  修正， 修订', 12514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erupt', 'v.  突然发生， 爆发； 喷出', 12515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'benevolent', 'adj.  慈善的； 善心的', 12516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consent', 'vi&n.  同意， 赞成， 准许', 12517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respect', 'vt. 尊重，尊敬；遵守 n.  尊敬， 尊重； 重视； 方面', 12518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retreat', 'vi. 退却，撤退；退缩 n.  退却， 撤退； 隐退处', 12519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fusion', 'n.  熔化， 熔解； 熔合； 核聚变； 联合， 合并', 12520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parachute', 'v.  跳伞； 空投 n. 降落伞', 12521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'behaviorism', 'n.  行为主义', 12522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mutual', 'adj.  相互的； 共有的', 12523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shell', 'n. 壳，外壳；壳状物；骨架，框架；外表；炮弹 vt.  给…去壳； 炮击', 12524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carnivore', 'n.  食肉动物', 12525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pharmacy', 'n.  药店； 药剂学', 12526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'therefore', 'adv. 因此，从而 conj.  因此', 12527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exchange', 'vt. 兑换；交易；调换，交换；交流 n.  交易； 兑换； 交换； 交流', 12528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crooked', 'adj.  不诚实的； 欺诈的； 弯曲的', 12529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contiguous', 'adj.  接壤的， 毗邻的； 不间断的', 12530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nourishment', 'n.  营养， 营养品', 12531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'connote', 'v.  意味着； 暗示', 12532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puddle', 'n.  水坑， 水洼', 12533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primal', 'adj.  最初的； 主要的， 首要的', 12534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paste', 'v. 粘贴；拼贴 n.  面团； 糨糊', 12535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'directory', 'n.  人名地址录， 电话号码簿； 目录', 12536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jeans', 'n.  牛仔裤', 12537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monarch', 'n.  君主， 帝王', 12538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overnight', 'adv.  整夜； 一夜之间 adj.  通宵的， 一整夜的； 一夜之间的', 12539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'behave', 'v.  行为， 表现； 表现得体， 有礼貌； 作出反应', 12540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laser', 'n.  激光； 激光器', 12541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scope', 'n.  范围， 界限； 眼界， 见识； 余地， 机会', 12542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notate', 'vt.  以符号表示， 把…写成记号', 12543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaeology', 'n.  考古学', 12544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'molecular', 'adj.  分子的； 摩尔的； 由分子组成的', 12545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morale', 'n.  士气， 斗志', 12546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'periphery', 'n.  外围， 边缘', 12547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fresco', 'v.  绘湿壁画于 n. 湿壁画；湿壁画技法', 12548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identify', 'v.  识别； 鉴定； 找到， 发现', 12549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embrace', 'v. 拥抱；包含；欣然接受 n.  拥抱', 12550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nitrogen', 'n.  氮', 12551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artesian', 'adj.  自流水的， 喷水的', 12552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'label', 'vt. 标记 n.  标签； 称号', 12553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aquarium', 'n.  养鱼缸； 水族馆', 12554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modify', 'vt.  修改， 更改； 缓和； 【语】修饰', 12555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soprano', 'n.  女高音', 12556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mortify', 'vt.  使蒙受屈辱， 使难堪', 12557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cram', 'v.  填塞， 塞满； 匆忙准备， 临时死记硬背', 12558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clone', 'n. 克隆动物，无性繁殖动物；复制品，翻版 vt.  克隆， 以无性繁殖技术复制', 12559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detest', 'v.  憎恶', 12560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enunciate', 'v.  清晰地发音； 表达， 阐明', 12561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reservoir', 'n.  水库， 蓄水池； 储备， 储藏', 12562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exempt', 'adj. 被免除的，被豁免的 vt.  免除， 豁免', 12563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'degenerative', 'adj.  衰退的， 堕落的； 变性的', 12564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crab', 'n.  蟹， 螃蟹', 12565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feminist', 'n.  女权主义者', 12566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aesthetic', 'adj.  审美的， 美学的； 美的， 艺术的', 12567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'backup', 'n. 后援，增援；', 12568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arithmetic', 'n.  算术', 12569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardy', 'adj.  强壮的； 耐寒的； 能吃苦耐劳的', 12570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caption', 'n. 说明文字；标题；字幕 vt.  给加说明文字', 12571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mismanage', 'vt.  对…管理不当， 处理不当', 12572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carbohydrate', 'n.  碳水化合物', 12573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subconscious', 'adj.  下意识的， 潜意识的 n. 下意识，潜意识', 12574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eject', 'v.  逐出， 驱赶； 喷出， 喷射； 弹出', 12575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorologist', 'n.  气象学者', 12576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defect', 'vi.  变节， 叛变 n.  瑕疵， 缺陷； 过失', 12577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obedience', 'n.  服从， 顺从', 12578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reinforce', 'vt.  加固， 加强； 增援', 12579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'casual', 'adj.  非正式的， 随便的； 漫不经心的； 漠不关心的， 冷淡的； 偶然的， 碰巧的； 临时的', 12580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rim', 'n. 边，轮缘；边界 vt.  给…镶边', 12581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decline', 'n&v.  下降； 衰退； 拒绝， 谢绝', 12582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rip', 'v. 扯破，撕坏 n.  裂口， 裂缝', 12583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'property', 'n.  财产， 所有物； 所有权； 房产， 地产； 特性', 12584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'debris', 'n.  岩屑； 残骸； 碎屑', 12585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scuffle', 'n&vi.  扭打， 混战', 12586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'luster', 'n.  光亮， 光泽； 荣耀', 12587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handle', 'v. 处理；对待；操纵；触，摸 n.  柄， 把手， 拉手', 12588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urbanization', 'n.  都市化', 12589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tough', 'adj.  坚韧的； 棘手的， 困难的； 强健的， 吃苦耐劳的； 粗暴的； 严格的； 老的', 12590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yeast', 'n.  酵母， 发酵粉', 12591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'script', 'n. 剧本，脚本，广播稿；笔迹；字母表 vt.  为电影写剧本', 12592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melody', 'n.  旋律， 曲调； 乐曲， 歌曲', 12593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trilogy', 'n.  三部剧， 三部曲', 12594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spot', 'v. 认出，发现 n.  地点； 斑点； 少量', 12595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sterile', 'adj.  不育的； 贫瘠的； 无菌的； 无结果的， 没有实际价值的； 刻板的', 12596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watercourse', 'n.  水道， 河道', 12597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catholic', 'adj. 广泛的，包罗万象的；[C-]天主教的 n.  [C-]天主教', 12598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mighty', 'adj.  强有力的； 巨大的', 12599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'partial', 'adj.  部分的， 不完全的； 偏爱的， 癖好的； 偏袒的', 12600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pictorial', 'adj. 图示的，有图片的；绘画的，图画的 n.  画报， 画刊', 12601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slough', 'vt.  使脱落 n.  泥坑， 沼泽； 绝境', 12602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drench', 'vt.  使湿透', 12603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retain', 'vt.  保持， 保留', 12604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drastic', 'adj.  剧烈的， 猛烈的， 激烈的', 12605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epoch', 'n.  新纪元， 时代', 12606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retail', 'adv.  以零售方式 v. 零售；以…价格销售 n. 零售', 12607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crew', 'n.  全体船员； 全体工作人员', 12608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spear', 'v. 刺，戳 n.  矛， 枪； 嫩叶', 12609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'innovate', 'v.  革新， 创新', 12610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extravagant', 'adj.  放肆的， 过分的； 奢侈的， 铺张的', 12611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accommodate', 'v.  提供； 容纳； 适应， 顺应', 12612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bubble', 'n. 泡；', 12613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yield', 'v. 生产，出产；屈服，顺从；让出，放弃；变形，弯曲 n.  产量； 收益', 12614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protagonist', 'n.  主角， 主人公； 领导者， 倡导者', 12615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacation', 'vi. 度假 n.  假期', 12616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sacred', 'adj.  宗教的； 上帝的， 神圣的', 12617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outcome', 'n.  结果， 成果', 12618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polar', 'adj.  极的， 极地的； 磁极的； 正好相反的， 截然对立的', 12619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tender', 'adj. 嫩的；脆弱的；温柔的，亲切的 v. 提出；投标 n.  投标', 12620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vapor', 'n.  蒸气， 潮气', 12621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curriculum', 'n. 课程', 12622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meditate', 'v.  沉思， 冥想； 考虑； 谋划', 12623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prototype', 'n.  原型， 雏形', 12624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meantime', 'n&ad.  其时， 同时', 12625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dehydrate', 'v.  脱水', 12626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cite', 'vt.  引用， 引证； 传唤， 传讯； 表彰， 嘉奖', 12627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blurt', 'vt.  脱口而出', 12628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atom', 'n.  原子； 微粒， 微量', 12629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'internship', 'n.  实习期', 12630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pertain', 'vi.  存在； 适用', 12631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shed', 'vt. 抛弃；摆脱；流出；散发；发出；脱落 n.  小屋', 12632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spun', 'adj.  拉成丝的', 12633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tolerable', 'adj.  可忍受的， 可容忍的； 尚好的， 过得去的', 12634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bicameral', 'adj.  两院制的， 有两个议院的', 12635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'correspond', 'vi.  相一致， 符合； 相当于； 通信', 12636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spur', 'n. 刺激；激励；马刺 vt.  激励， 鼓舞； 刺激， 促进', 12637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mode', 'n.  方式， 形式； 风格； 时尚', 12638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rear', 'adj.  后部的， 后面的 vt. 养育，抚养，培养；饲养 n. 后部，后方；臀部', 12639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elapse', 'vi.  消逝， 流逝', 12640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symmetry', 'n.  对称； 相似， 相仿', 12641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insect', 'n.  昆虫， 虫', 12642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complement', 'vt.  补充， 补足， 使完善； 与…相配 n.  补充物， 补足物； 足数， 足额； 补足语', 12643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'qualify', 'v.  具有资格， 合格； 有权； 限定， 修饰', 12644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bode', 'vi.  预示', 12645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'already', 'adv.  已， 已经', 12646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Pueblo', 'n.  普韦布洛印第安人村落； 普韦布洛人', 12647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'applicable', 'adj.  可应用的， 可实施的； 适当的， 合适的', 12648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admission', 'n.  准许进入； 入场费； 承认', 12649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adhere', 'vi.  黏附， 附着； 坚持； 遵守', 12650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sediment', 'n.  沉淀物， 沉积物', 12651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tremulous', 'adj.  发抖的， 颤抖的； 害怕的', 12652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hybrid', 'adj. 杂交产生的；混合的，合成的 n.  杂交植物； 混合物， 合成物', 12653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'panorama', 'n.  全景， 全貌； 概观， 综述', 12654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adaptable', 'adj.  能适应的； 可改编的', 12655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contemporary', 'adj. 当代的；', 12656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mock', 'v. 嘲笑，嘲弄；模仿；蔑视， n.  模拟考试', 12657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credence', 'n.  可信性， 真实性； 信任； 信念', 12658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gear', 'n. 齿轮，传动装置；挡；设备 vt.  调节， 使适应', 12659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facilitate', 'vt.  推动， 促进', 12660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rob', 'vt.  抢夺， 抢掠； 剥夺， 使失去', 12661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rod', 'n.  杆， 棒', 12662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roe', 'n.  鱼卵', 12663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quiver', 'vi.  颤动， 抖动 n. 颤抖；箭筒', 12664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encase', 'vt.  包住', 12665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telegraph', 'v.  打电报， 发电报 n. 电报；电报机', 12666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disappoint', 'v.  失望， 扫兴', 12667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebellious', 'adj.  反叛的， 叛逆的； 叛乱的', 12668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gloss', 'v.  有光泽 n. 光泽，色泽；亮光漆；注解', 12669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ration', 'n. 配给量，定量；给养，口粮 vt.  配给， 定量供应', 12670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'construction', 'n.  构造， 结构； 建筑物', 12671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predict', 'v.  预言， 预测', 12672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dump', 'vt. 丢弃，倾倒；抛弃；推卸；倾销 n.  垃圾场', 12673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universal', 'adj.  普遍的， 全体的； 通用的， 万能的； 宇宙的， 全世界的', 12674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subjective', 'adj.  主观的， 个人的', 12675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blossom', 'vi.  开花； 长成 n. 花', 12676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radical', 'adj. 根本的；激进的，极端的；全新的，不同凡响的 n.  激进分子； 游离基， 自由基', 12677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blunt', 'adj. 钝的；不敏感的；直率的 vt.  使迟钝； 使减弱', 12678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irresistible', 'adj.  无法抗拒的， 诱人的； 不能自已的', 12679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doodle', 'vi.  乱涂， 胡画', 12680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intuitive', 'adj.  直觉的', 12681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minute', 'adj.  细微的， 极小的； 细致入微的， 详细的 n.  分， 分钟； 一会儿， 片刻； 时刻', 12682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'analogy', 'n.  类比， 类推', 12683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transcendent', 'adj.  卓越的， 出众的', 12684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swirl', 'v.  打旋， 旋转 n. 漩涡；螺旋形', 12685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'application', 'n.  请求， 申请； 应用， 运用； 敷用', 12686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'productive', 'adj.  生产的； 能产的， 多产的； 富有成效的', 12687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hummingbird', 'n.  蜂鸟', 12688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'semester', 'n.  学期', 12689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypothesis', 'n.  假设， 假说； 前提', 12690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collapse', 'v&n.  崩溃， 倒塌； 虚脱', 12691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dull', 'adj.  乏味的， 单调的； 迟钝的； 无光泽的； 萧条的； 阴沉的， 昏暗的', 12692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ferment', 'v.  发酵； 骚动 n.  发酵； 动乱， 骚动', 12693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprehend', 'v.  理解， 领会； 包括， 由…组成', 12694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potency', 'n.  影响力， 支配力； 效力', 12695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accurate', 'adj.  正确无误的， 精确的', 12696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'octopus', 'n.  章鱼', 12697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prostitution', 'n.  卖淫； 出卖灵魂， 堕落； 滥用', 12698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legend', 'n.  传奇故事， 传说； 传奇文学', 12699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paraphrase', 'v.  解释； 改写 n. 释义', 12700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erect', 'adj. 直立的 vt.  建立； 竖立', 12701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exalted', 'adj.  崇高的， 高贵的， 显赫的', 12702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identification', 'n.  身份证明； 辨认， 鉴定', 12703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protein', 'n.  蛋白质', 12704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'annual', 'adj. 每年的，一年一度的 n.  年报， 年刊， 年鉴； 一年生植物', 12705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exclusive', 'adj. 独占的；除外的，排他的；奢华的 n.  独家新闻', 12706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jar', 'v. 震动；冲突，抵触；感到不快 n.  坛子； 广口瓶', 12707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poverty', 'n.  贫穷， 贫困', 12708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repertoire', 'n.  常备剧目， 保留剧目； 可表演节目； 全部才能', 12709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resort', 'vi. 求助 n.  度假胜地； 手段', 12710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dwindle', 'v.  减少； 缩小', 12711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lightning', 'adj.  闪电般的， 快速的 n. 闪电', 12712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jaw', 'n. 颌，颚；', 12713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reef', 'n.  礁， 暗礁', 12714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'margin', 'n.  边缘； 页边空白； 差数， 差额； 余地， 余裕', 12715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nail', 'n. 指甲，爪；钉 vt.  将…钉牢， 钉住', 12716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tarnish', 'v. 失去光泽；玷污，败坏 n.  污点； 瑕疵', 12717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sunlit', 'adj.  阳光照射的', 12718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refine', 'vt.  精炼， 精制； 使完善； 净化， 提纯', 12719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mount', 'v. 增加；登上，攀登；骑上，乘上；发起，组织，开展 n.  山， 山峰； 支架， 底座', 12720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coexist', 'vi.  共存', 12721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquiesce', 'vi.  默许， 默认', 12722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pathetic', 'adj.  可怜的， 引起怜悯的， 令人怜惜的', 12723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turkey', 'n.  火鸡； 失败', 12724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atomic', 'adj.  原子的； 原子能的', 12725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overtime', 'adv. 加班 adj.  超时的， 加班的', 12726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scorch', 'v. 烧焦；枯萎，枯黄 n.  焦痕', 12727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telescope', 'n.  望远镜', 12728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mound', 'n.  土墩， 土丘； 堆， 垛', 12729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gentility', 'n.  有教养， 文雅', 12730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accuse', 'vt.  谴责； 指责， 归咎； 指控， 控告', 12731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'algebra', 'n.  代数', 12732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'espouse', 'vt.  支持， 拥护， 赞成', 12733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predecessor', 'n.  前辈； 前任； 原有事物', 12734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquire', 'vt.  获得， 取得', 12735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tactic', 'n. 手段，策略；', 12736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'worth', 'adj. 值…的，价值…的，值得…的 n.  价值； 财产', 12737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'automobile', 'n.  汽车， 机动车', 12738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fertile', 'adj.  肥沃的， 富饶的； 能结果的， 能繁殖的； 想象力丰富的', 12739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diversity', 'n.  多样性', 12740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notion', 'n.  概念， 观念； 想法', 12741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'captive', 'adj. 被监禁的，被困住的；受控制的 n.  俘虏， 战俘', 12742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dividend', 'n.  红利， 股息； 回报， 效益； 被除数', 12743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'popular', 'adj.  通俗的； 受欢迎的； 流行的', 12744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vice', 'n.  恶行， 恶习； 副， 代理', 12745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'esteem', 'n&vt.  尊重， 敬重', 12746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outweigh', 'vt.  超过', 12747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shear', 'v.  剪； 切断， 剪切', 12748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wedge-shaped', 'adj.  楔形的', 12749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alga', 'n. 水藻', 12750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dupe', 'n. 上当者 vt.  欺骗， 愚弄', 12751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteor', 'n.  流星', 12752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empower', 'v.  授权， 准许； 使控制局势', 12753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suppress', 'vt.  抑制， 阻止； 镇压， 压制； 禁止发表， 查禁； 阻止…的生长', 12754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crater', 'n.  火山口； 坑', 12755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravitational', 'adj.  重力的， 万有引力的', 12756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wrinkle', 'v.  起皱纹 n. 皱纹', 12757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calm', 'adj. 平静的；镇静的，沉着的 vt.  使平静， 使镇定， 平息', 12758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supervise', 'vt.  监督； 指导', 12759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fabulous', 'adj.  寓言式的； 难以置信的； 极好的', 12760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dilemma', 'n.  困境， 进退两难的局面', 12761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rub', 'n&v.  擦， 摩擦', 12762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'through', 'adv. 从头到尾，自始至终；直达，径直；彻底，完全 adj.  完成的， 结束的； 直达的， 直通的 prep. 穿过，通过；从头到尾，自始至终；经由，以；因为，由于', 12763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rug', 'n.  地毯； 围毯', 12764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hieroglyph', 'n.  象形文字， 象形符号', 12765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'towering', 'adj.  高耸的； 杰出的', 12766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occasional', 'adj.  偶然的， 不经常的； 临时的', 12767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enact', 'v.  制定法律， 颁布； 扮演', 12768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deviant', 'adj. 不正常的，越出常规的 n.  不正常的人', 12769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pharaoh', 'n.  法老', 12770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scrutinize', 'v.  仔细检查， 细察', 12771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'realtor', 'n.  房地产经纪人', 12772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'debate', 'v&n.  辩论； 讨论， 争论', 12773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spacecraft', 'n.  航天器， 宇宙飞船', 12774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extinguish', 'vt.  熄灭， 扑灭； 消灭， 毁灭， 使破灭', 12775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vulnerable', 'adj.  易受攻击的， 易受伤的', 12776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preach', 'v.  布道， 讲道； 竭力鼓吹， 宣讲， 宣传； 说教', 12777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fibrous', 'adj.  含纤维的； 纤维状的', 12778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recollection', 'n.  记忆力； 回忆， 记忆； 回想起来的事', 12779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subjugate', 'vt.  征服， 制伏， 使服从', 12780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'donate', 'vt.  捐赠； 赠送', 12781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deplete', 'vt.  使枯竭， 耗尽', 12782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bonanza', 'n.  富矿带； 带来好运的事； 兴盛， 繁荣', 12783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statistic', 'n. 统计数字，统计资料；', 12784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nicotine', 'n.  尼古丁', 12785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taboo', 'adj.  忌讳的 n. 禁忌，忌讳；禁止，避讳', 12786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mold', 'n. 霉菌；模型 vt.  塑造', 12787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bold', 'adj.  大胆的； 冒失的； 粗体的； 醒目的', 12788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'significant', 'adj.  有重大意义的， 重要的， 显著的； 意味深长的', 12789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tentacle', 'n.  触角， 触须， 触手', 12790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overlap', 'v.  交叠， 部分重叠 n.  重叠； 重叠的部分', 12791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volunteer', 'v. 自愿做 adj.  志愿的， 义务的 n. 志愿者；志愿军', 12792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'senate', 'n.  参议院； 上院', 12793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assassinate', 'vt.  暗杀， 行刺； 诋毁', 12794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crow', 'v.  啼叫， 打鸣； 得意洋洋 n. 乌鸦', 12795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bolt', 'v. 逃跑；闩上 n.  插销， 门闩； 闪电', 12796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congressional', 'adj.  立法机构的； 代表大会的； 国会的', 12797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boon', 'n.  恩惠， 恩赐； 益处', 12798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'novelty', 'n.  新奇， 新颖； 新奇的事物', 12799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boom', 'vi. 迅速发展，激增；发出低沉有力的声音 n.  激增， 繁荣； 繁荣昌盛期', 12800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abolish', 'vt.  废止， 废除', 12801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absence', 'n.  缺席； 缺乏', 12802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attract', 'vt.  吸引', 12803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'critique', 'n. 批评，评论 vt.  写评论', 12804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cautious', 'adj.  小心的， 谨慎的', 12805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recession', 'n.  衰退， 衰退时期， 萧条时期； 撤回， 退回', 12806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'situated', 'adj.  坐落在…的； 处于…境地的', 12807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'malicious', 'adj.  怀有恶意的， 恶毒的', 12808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vigilance', 'n.  警戒， 警惕', 12809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ally', 'v.  结盟 n.  同盟国； 结盟者， 支持者', 12810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concentric', 'adj.  同心的', 12811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mantle', 'n.  覆盖物； 披风， 斗篷； 纱罩； 【地】地幔', 12812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outrageous', 'adj.  残暴的； 骇人的； 反常的， 过度的', 12813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abbreviate', 'vt.  缩略， 缩写', 12814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lavish', 'adj.  大方的， 慷慨的； 大量的； 浪费的 vt. 慷慨给予，滥用；浪费，挥霍', 12815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substance', 'n.  物质； 主旨， 实质； 根据； 重要性', 12816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'varnish', 'vt. 上清漆 n.  清漆', 12817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tribal', 'adj.  部落的， 宗族的； 种族的', 12818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bond', 'v.  黏合， 结合 n. 联结，黏结；债券；黏合剂；契约，合同', 12819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'momentum', 'n.  动量； 动力， 冲力； 势头', 12820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'target', 'n. 目标，对象；靶子 vt.  把…作为目标', 12821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discourse', 'vi.  讲述， 论述 n.  演讲； 论文； 话语', 12822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obstruct', 'vt.  妨碍， 阻挠； 阻塞', 12823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grind', 'v. 打磨；磨，碾 n.  磨碎， 碾碎； 苦差事', 12824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bony', 'adj.  瘦骨嶙峋的； 似骨的； 多骨的', 12825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'labyrinth', 'n.  迷宫； 错综复杂的事件', 12826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aquatic', 'adj.  水生的； 水上的', 12827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cape', 'n.  海角， 岬； 斗篷， 披肩', 12828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microprocessor', 'n.  微处理器', 12829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delicate', 'adj.  易损的； 微妙的； 精巧的； 娇弱的， 纤细的', 12830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebel', 'vi.  造反， 起义， 反抗 n.  叛逆者， 起义者', 12831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modeling', 'n.  立体感； 建模， 造型', 12832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bounce', 'v. 弹起，反弹 n.  弹跳； 反弹力', 12833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ammonia', 'n.  氨， 氨水', 12834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crustal', 'adj.  外壳的， 地壳的', 12835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tissue', 'n. 纸巾，面巾纸', 12836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'experimental', 'adj.  实验的， 用于实验的', 12837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cart', 'n. 运货马车；手推车 vt.  用车装运', 12838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cast', 'vt. 浇铸；投掷；投射；蜕 n.  铸件； 演员表， 全体演员； 投， 抛', 12839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anxious', 'adj.  渴望的； 担忧的； 令人焦虑的', 12840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slice', 'n. 薄片；部分，份额 vt.  把…切成片', 12841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auditory', 'adj.  耳的； 听觉的', 12842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frost', 'v. 结霜，蒙上霜 n.  霜； 霜冻； 严寒', 12843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'larva', 'n. 〔昆虫的〕幼虫，幼体', 12844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burrow', 'v. 挖掘，挖地洞；寻找，', 12845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incline', 'v.  倾斜； 倾向于 n.  斜坡， 斜面', 12846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'olfactory', 'adj.  嗅觉的', 12847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elevate', 'vt.  举起， 抬高； 提升职位； 使情绪高昂， 使兴高采烈', 12848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'designate', 'adj.  已任命但尚未就职的 vt. 命名；任命；指明，标示', 12849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slick', 'adj.  光滑的； 熟练的； 圆滑的， 口齿伶俐的； 精巧的， 巧妙的', 12850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oppressive', 'adj.  压迫的， 压制的； 令人焦虑的', 12851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'item', 'n.  项目， 条款； 一件商品； 一条， 一则', 12852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canvas', 'n.  画布； 油画； 帆布', 12853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superintendent', 'n.  主管， 负责人； 指挥者， 管理者； 警长', 12854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invasive', 'adj.  侵入的， 侵略的； 开刀的', 12855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calculable', 'adj.  可计算的； 能预测的； 可信的', 12856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hollow', 'adj. 空心的，中空的；凹陷的；空洞的，虚伪的；沉闷的， vt.  挖空， 凿空', 12857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shipwright', 'n.  造船者， 造船工人； 修船工', 12858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epic', 'adj.  史诗般的； 艰苦卓绝的； 壮丽的， 宏大的 n. 史诗；史诗般的电影；壮举', 12859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'downtown', 'adv.  在市中心； 往市中心 adj. 市中心的', 12860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rely', 'vi.  依赖， 依靠； 信赖， 信任', 12861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moor', 'v.  停泊， 系泊 n. 沼泽；旷野，荒野', 12862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slide', 'v. 滑动 n.  滑动； 滑坡， 滑道； 幻灯片', 12863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydrothermal', 'adj.  热液的', 12864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sticky', 'adj.  黏的， 黏性的； 闷热的； 棘手的', 12865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grill', 'vt. 烧烤；拷问，盘问 n.  烤架', 12866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'care', 'v.  关心， 关怀； 介意； 担忧 n. 小心，谨慎；照看，照料；忧虑，焦虑', 12867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pattern', 'n. 模式，方式；样式，图案；样品，样本 vt.  仿制； 使形成， 促成', 12868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'settle', 'v.  安定， 安顿， 定居； 结束， 解决； 决定， 确定； 平静下来； 支付， 结算； 飞落， 停留', 12869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'increment', 'n.  增加； 增量； 定期的加薪', 12870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harsh', 'adj.  恶劣的， 严酷的； 刺耳的； 粗糙的， 毛糙的', 12871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smother', 'vt.  使窒息而死； 厚厚地覆盖； 抑制， 扼杀； 把闷熄', 12872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cramped', 'adj.  狭小的， 狭窄的； 受限制的； 密小难认的', 12873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vehicle', 'n.  交通工具， 车辆； 工具， 手段', 12874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scrape', 'v. 刮掉，擦掉；发出刺耳的刮擦声；', 12875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kiln', 'n.  窑， 炉', 12876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bleak', 'adj.  阴冷的； 无望的， 令人沮丧的； 乏味的； 荒凉的', 12877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorological', 'adj.  气象学的； 气象的', 12878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cushion', 'vt. 起缓冲作用 n.  垫子', 12879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glorious', 'adj.  壮丽的， 辉煌的； 光荣的； 令人愉快的， 极好的', 12880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bilateral', 'adj.  有两边的； 双边的', 12881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plateau', 'vi.  保持稳定水平 n. 高原；稳定期，停滞期', 12882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aptitude', 'n.  适合， 恰当； 天资， 才能， 资质', 12883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'daisy', 'n.  雏菊； 一流的人物', 12884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stress', 'v.  强调； 重读； 焦虑不安 n. 压力；强调；精神压力，紧张；重音，重读', 12885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliance', 'n.  依靠， 依赖； 信任', 12886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'display', 'vt&n.  陈列； 展示； 显示', 12887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gnaw', 'v.  啃， 咬', 12888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disorder', 'n.  混乱， 凌乱； 动乱， 骚乱； 失调， 紊乱', 12889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggravate', 'vt.  恶化， 加重； 激怒', 12890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disquiet', 'v. 不安，忧虑 n.  不安， 忧虑', 12891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'addictive', 'adj.  使人上瘾的； 使人沉醉的， 醉心的', 12892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yarn', 'n.  纱， 纱线； 故事', 12893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spurn', 'vt&n.  拒绝； 摈弃', 12894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orchid', 'n.  兰， 兰花', 12895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dairy', 'adj.  乳品的 n. 牛奶场；乳品店；奶制品', 12896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plaque', 'n.  匾额； 牙斑', 12897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'membrane', 'n.  薄膜； 细胞膜', 12898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mature', 'adj. 成熟的；', 12899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scavenger', 'n.  捡破烂的人， 拾荒者； 食腐动物', 12900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alleviate', 'vt.  减轻， 缓解， 缓和', 12901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'talent', 'n.  天赋； 才干； 人才', 12902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scoff', 'vi.  嘲笑， 讥笑', 12903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sacrificial', 'adj.  供奉的， 献祭的， 牺牲的', 12904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'factual', 'adj.  实际的， 真实的， 事实的', 12905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negotiate', 'v.  谈判， 商议； 商定， 达成； 通过， 越过', 12906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moth', 'n.  蛾', 12907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'germ', 'n.  微生物， 细菌； 萌芽', 12908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shatter', 'v.  粉碎， 破碎； 破灭； 散开， 吹散； 给予极大打击', 12909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credentialism', 'n.  文凭主义', 12910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glimpse', 'n. 一看，一瞥 vt.  瞥见', 12911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moss', 'n.  苔藓', 12912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detective', 'adj.  侦探的 n. 侦探，私人侦探', 12913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transfer', 'v. 转移；转学；转让；换乘 n.  转移； 转学； 转让； 换乘', 12914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resin', 'n.  树脂', 12915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affection', 'n. 喜爱，钟爱；', 12916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diversion', 'n.  消遣， 娱乐； 转移， 转换', 12917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'omit', 'vt.  省略， 删去； 遗漏， 忽略', 12918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'courteous', 'adj.  谦恭的， 有礼貌的', 12919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limitation', 'n.  限制； 局限性', 12920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sponsor', 'vt. 主办；赞助 n.  发起者； 赞助者', 12921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jog', 'vi.  慢跑； 轻轻触碰', 12922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ascertain', 'vt.  弄清， 查明', 12923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insert', 'vt.  插入', 12924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jot', 'vt.  草草记下， 匆匆记下', 12925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Neolithic', 'adj.  新石器时代的', 12926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'highlight', 'vt. 强调，突出；以强烈光线照射 n.  最精彩部分', 12927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'database', 'n.  数据库', 12928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sac', 'n.  囊， 液囊', 12929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patient', 'adj. 有耐心的，能忍耐的 n.  病人， 患者', 12930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reject', 'vt.  拒绝， 抵制； 抛弃， 摈弃， ， 丢弃； 拒收， 不录用； 排斥 n.  被拒货品， 不合格产品', 12931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sheer', 'adv. 垂直地，陡峭地 vi.  急转， 偏离 adj. 陡峭的；完全的，十足的，全然的；绝对的；极薄的', 12932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imitation', 'n.  模仿， 仿效； 仿制； 仿造品', 12933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compliment', 'vt.  赞美， 称赞 n.  赞美；', 12934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'miracle', 'n.  奇事， 奇迹', 12935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rinse', 'vt. 冲洗，漂洗，冲刷 n.  漂洗， 冲洗， 洗涤； 染发剂', 12936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amount', 'vi. 总计 n.  总额', 12937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comply', 'vi.  服从； 遵守', 12938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sap', 'vt. 使衰竭；削弱，逐渐破坏 n.  液， 汁； 精力； 笨蛋', 12939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spellbind', 'vt.  用妖术迷惑； 迷住， 使入迷', 12940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nectar', 'n.  花蜜； 甘美的饮料， 琼浆玉液', 12941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feudal', 'adj.  封建的', 12942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kingdom', 'n.  王国； 领域， 界', 12943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spread', 'v. 展开；蔓延，扩散；散布；涂，敷 n.  传播， 蔓延； 涉及幅度， 活动范围', 12944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puppet', 'n.  木偶； 玩偶； 傀儡， 受人操纵的人', 12945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'educated', 'adj.  受过教育的， 有教养的', 12946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'favor', 'n.  帮助； 赞同， 支持； 偏爱', 12947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'latter', 'adj. 后面的，后半期的；后者的 n.  后者', 12948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clinic', 'n.  门诊部， 诊所', 12949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affiliate', 'vt.  使隶属于 n.  分公司', 12950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simply', 'adv.  简单地， 简明地； 简直； 仅仅， 只； 朴素地， 简朴地', 12951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recessive', 'adj.  隐性的', 12952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equivalent', 'adj.  相同的； 相当的 n. 对等物；等价物', 12953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'momentary', 'adj.  片刻的， 瞬间的， 暂时的', 12954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypocritical', 'adj.  伪善的， 虚伪的', 12955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constricted', 'adj.  狭窄的； 收缩的； 抑制的， 约束的', 12956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensational', 'adj.  轰动性的， 引起哗然的， 耸人听闻的； 〈口〉极好的， 绝妙的', 12957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canoe', 'vi. 乘独木舟，划独木舟 n.  独木舟', 12958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wedge', 'n. 楔子；楔形物 vt.  ■入， 塞入', 12959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alienate', 'vt.  使疏远， 使不友好； 转让， 让渡', 12960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awake', 'v. 唤醒；醒；觉醒，醒悟 adj.  醒着的； 警觉的', 12961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plague', 'vt. 困扰，使苦恼；纠缠 n.  鼠疫； 传染病； 祸患， 灾害', 12962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perpetual', 'adj.  连续不断的； 永久的， 长期的', 12963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrospect', 'n.  回顾， 反顾', 12964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fascinate', 'v.  深深吸引， 迷住', 12965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offer', 'v. 提供；自愿给予；提出，提议 n.  提议； 报价， 出价； 特价', 12966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diplomatic', 'adj.  外交的， 从事外交的； 有策略的， 有手腕的， 老练的', 12967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'projector', 'n.  放映机， 幻灯机， 投影仪', 12968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'draft', 'adj.  供役使的 n. 草图，草稿；汇票；气流 vt. 起草；征募，选派', 12969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loath', 'adj.  不情愿的， 勉强的', 12970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complex', 'adj.  合成的， 综合的； 复杂的， 错综的， 难以理解的 n.  建筑群； 综合体， 集合体； 情结', 12971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humidity', 'n.  湿度； 潮湿', 12972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluid', 'adj.  液体的； 流动的 n. 液体，流体', 12973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pamphlet', 'n.  小册子', 12974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'healthful', 'adj.  有益健康的', 12975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'posit', 'vt.  安排； 假定', 12976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ornate', 'adj.  华丽的， 豪华的', 12977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metropolis', 'n.  首府； 大都市', 12978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'documentation', 'n.  文件； 归档， 文献记录', 12979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proliferate', 'vi.  激增， 迅速繁殖', 12980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personal', 'adj.  个人的， 私人的； 亲自的', 12981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plastic', 'adj.  塑料的； 可塑的； 做作的， 虚伪的 n. 塑料', 12982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delay', 'v. 耽搁，延迟 n.  耽搁， 延迟', 12983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onslaught', 'n.  冲击； 攻击， 猛攻', 12984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transient', 'adj.  短暂的， 转瞬即逝的； 临时的', 12985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disrepute', 'n.  坏名声， 不光彩', 12986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plank', 'n.  木板； 政策要点， 政纲的核心', 12987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heyday', 'n.  全盛期', 12988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sponge', 'v.  用海绵擦， 揩 n. 海绵；寄生虫', 12989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deal', 'v.  处理， 对付； 给予； 做买卖， 经营 n. 交易，买卖；协议', 12990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spaghetti', 'n.  意大利式细面条', 12991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insulate', 'vt.  使隔离， 使隔绝', 12992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scheme', 'v.  密谋， 秘密策划， 图谋 n. 计划，方案；阴谋；体系，体制', 12993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affect', 'vt.  影响； 感染', 12994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drain', 'v. 流走，流出；使耗尽 n.  下水道， 排水沟； 排放； 消耗', 12995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smoothly', 'adv.  顺利地； 平稳地； 平静地', 12996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'isolate', 'vt.  使隔离， 使孤立', 12997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'civil', 'adj.  市民的， 公民的， 平民的； 民事的； 国家的， 政府的； 文明的， 有教养的', 12998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsequent', 'adj.  随后的； 并发的', 12999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indicate', 'v.  表明， 显示； 指出， 指示； 象征， 预示； 暗示， 间接提及', 13000);
