INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fat', 'n.  脂肪', 6001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electron', 'n.  电子', 6002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'citadel', 'n.  根据地， 大本营', 6003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'panegyric', 'n.  颂词； 颂文', 6004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brooch', 'n.  胸针， 领针', 6005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambivalent', 'adj.  矛盾的', 6006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'practicable', 'adj.  能实行的， 行得通的， 可以实行的', 6007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'esoteric', 'adj.  深奥的； 隐秘的', 6008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probability', 'n.  概率', 6009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'browbeat', 'vt.  恫吓， 吓唬', 6010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'explicit', 'adj.  清晰的， 明确的， 清楚的； 直率的， 不含糊的', 6011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propriety', 'n.  适当， 正当， 得体； 礼节， 礼仪', 6012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abash', 'vt.  使局促不安， 使困窘', 6013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mastermind', 'n.  具有极高才智的人， 出谋划策的人， 设计者', 6014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'imbue', 'v.  浸透', 6015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abase', 'vt.  降低自己， 使卑下', 6016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aerostat', 'n.  航空器', 6017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utilize', 'v.  利用', 6018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'idealist', 'n.  理想主义者', 6019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subside', 'v.  下沉； 沉淀； 平息； 减退', 6020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antilogy', 'n.   前后矛盾', 6021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epistolary', 'adj.  书信的； 书信体的', 6022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elated', 'adj.  兴高采烈的； 得意洋洋的', 6023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'purity', 'n.  纯度', 6024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portion', 'n.  一部分', 6025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'futile', 'adj.  无效的， 无用的， 无希望的， 无意义的； 琐细的', 6026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'algae', 'n.  海藻； 藻类', 6027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pensive', 'adj.  沉思的； 悲伤的', 6028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'isotope', 'n.  同位素', 6029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clothier', 'n.  衣商', 6030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'engross', 'v.  吸引， 使全神贯注； 独占', 6031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acumen', 'n.  敏锐， 聪明', 6032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abate', 'v.  减少； 减轻', 6033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wee', 'adj.  很少的， 微小的', 6034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wistful', 'adj.  伤感的， 徒然神往的', 6035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'risible', 'adj.  可笑的, 滑稽的', 6036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eschew', 'v.  避开， 回避', 6037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'melee', 'n.  混战， 搏斗， 格斗', 6038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amass', 'vt.  收集， 积聚', 6039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'souvenir', 'n.  纪念品', 6040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seminary', 'n.  神学院', 6041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quaint', 'adj.  离奇有趣的； 奇怪的； 做得很精巧的', 6042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comical', 'adj.  好笑的， 滑稽的', 6043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grip', 'n. 紧握，紧抓；握力 v. 紧握，紧抓', 6044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adjutant', 'adj. 辅助的 n.  副官', 6045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bronchitis', 'n.  【医】 支气管炎', 6046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'biennial', 'adj.  两年生的； 两年一次的', 6047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tentative', 'adj.  试验性的， 试探的', 6048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'egoism', 'n.  自我主义； 利己主义', 6049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'criticize', 'v.  批评， 评论', 6050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wanton', 'adj.  荒唐的， 嬉戏的； 恣意的', 6051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incredulous', 'adj.  怀疑的， 不轻信的', 6052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'whet', 'v.  磨， 磨快； 兴奋', 6053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumference', 'n.  圆周， 周长； 周围', 6054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crystallization', 'n.  结晶', 6055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'behold', 'v.  目睹， 看见', 6056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dominance', 'n.  优势； 统治', 6057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indebted', 'adj.  负债的； 感恩的', 6058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'economic', 'adj.  经济  的， 经济学的', 6059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indicator', 'n.  指示剂', 6060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'whim', 'n.  一时的兴致； 幻想', 6061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thrall', 'n.  奴隶； 束缚； 奴役', 6062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distinction', 'n.  区别， 差别', 6063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrace', 'v.  折回； 退回', 6064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heretofore', 'adv.  迄今', 6065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abnegate', 'v.  放弃', 6066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'section', 'n.  断面； 一部分', 6067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ruinous', 'adj.  破坏性的， 灾难性的， 毁灭性的； 已成废墟的', 6068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malignant', 'adj.  恶性的， 致命的； 恶意的， 恶毒的', 6069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precedence', 'n.  优先， 居先', 6070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undercharge', 'v.  索价低于常价', 6071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'protocol', 'n.  草案； 协议', 6072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overflow', 'v.   泛滥，  溢出，  充溢 n. 溢出', 6073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'provoke', 'v.  挑动； 激发； 招惹', 6074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foil', 'v.  挫败 n. 箔，金属薄片', 6075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'respite', 'v.  暂缓', 6076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remonstrate', 'v.  抗议', 6077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gruesome', 'adj.  可怕的， 可憎的， 令人厌恶的', 6078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foolhardy', 'adj.  鲁莽的， 有勇无谋的', 6079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapprochement', 'n.  友好关系的恢复， 和解， 亲善', 6080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salutatory', 'n.  大学毕业典礼的贺词', 6081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repugnant', 'adj.  令人讨厌的； 冲突的； 不一致的', 6082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rail', 'v.  责骂， 抱怨', 6083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tranquil', 'adj.  安静的， 安详的', 6084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plea', 'n.  恳求， 请求； 抗辩， 答辩， 辩护； 借口， 托辞', 6085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boatswain', 'n.  水手长', 6086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'strait', 'n. 海峡；〔狭窄的〕水道', 6087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'choleric', 'adj.  易怒的', 6088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denominator', 'n.  标准； 分母', 6089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fastidious', 'adj.  难取悦的； 挑剔的； 苛求的', 6090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nutrition', 'n.  营养', 6091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cereal', 'n.  谷类食品； 谷类', 6092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invigorate', 'v.  鼓舞', 6093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indifferent', 'adj.  不关心的， 冷淡的， 不感兴趣的； 无偏袒的， 中立的， 公平的', 6094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undersize d', 'adj.  较一般为小的， 不够大的', 6095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unfavorable', 'adj.  相反的； 不适宜的， 不顺利的； 令人不快的', 6096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'producer', 'n.  生产者', 6097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solemn', 'adj.  庄严的， 隆重的； 严肃的', 6098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dictatorial', 'adj.  独裁的； 傲慢的， 专横的', 6099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perceive', 'vt.  察觉， 感知； 理解， 领悟', 6100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sugar', 'n.  糖类', 6101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electrolyte', 'n.  电解质', 6102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embarrass', 'v.  使窘迫， 使为难', 6103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'option', 'n.  选择， 选择权；  选择的事物 ； 选课', 6104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acute', 'adj.  敏锐的， 尖锐的；  急性的', 6105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stigma', 'n.  污名， 耻辱', 6106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unveil', 'v.  除去面纱； 使暴露； 展示， 介绍', 6107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generator', 'n.  发电机', 6108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sonar', 'n.  声纳', 6109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endurance', 'n.  忍耐， 持久， 耐久', 6110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'microscope', 'n.  显微镜', 6111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'farcical', 'adj.  滑稽的， 引人发笑的', 6112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'candidate', 'n.  候选人； 候补者； 报考者', 6113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cognizant', 'adj.  认知的', 6114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intelligible', 'adj.  可理解的， 明白易懂的， 易领悟的， 清楚的', 6115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parallel', 'adj. 平行的；相同的；类似的 n.  平行线， 平行面； 类似， 相似物', 6116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wearisome', 'adj.  使疲倦的， 使厌倦的， 乏味的', 6117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prattle', 'v.  说孩子气的话； 闲聊', 6118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inert', 'adj.  无活动的； 惰性的； 迟钝的', 6119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blunder', 'vi.  跌跌撞撞地走； 犯大错， 做错 n. 大错', 6120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pertinacious', 'adj.  固执的', 6121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enzyme', 'n.  酶', 6122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'breach', 'n. 违背；破坏；破裂，裂口 vt.  打破； 突破', 6123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'granule', 'n.  细粒', 6124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'selective', 'adj.  选择的， 选择性的； 精挑细选的', 6125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stimulus', 'n. 刺激（物）；促进因素', 6126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agglomerate', 'adj.  成块的， 凝聚的 v.  使成团， 使成块， 使凝聚 n. 大团，大块', 6127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bewilder', 'vt.  使迷惑； 使不知所措； 使昏乱', 6128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regiment', 'n.  团', 6129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'curmudgeon', 'n.  脾气坏的人', 6130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gall', 'n.  胆汁； 恶毒； 怨恨； 愚勇', 6131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terminal', 'n.  终点站； 终端， 接线端； 计算机终端', 6132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'egalitarian', 'adj.  平等主义的', 6133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'linguist', 'n.  语言学家', 6134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'surpass', 'v.  超过， 超越； 胜过', 6135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aloof', 'adv.  远离地； 冷漠超然地 adj. 孤零的，冷淡的', 6136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'idealize', 'v.  使理想化， 使合乎理想', 6137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stagnate', 'vt.   停滞，  变萧条', 6138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fainthearted', 'adj.  懦弱的， 胆小的', 6139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'succumb', 'v.  屈服， 屈从； 死', 6140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amatory', 'adj.  恋爱的； 情人的', 6141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rant', 'v.  怒气冲冲地叫嚷； 夸夸其谈', 6142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'translucent', 'adj.   透明的', 6143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conciliatory', 'adj.  抚慰的， 调和的', 6144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arbitrate', 'v.  做出公断', 6145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brine', 'n.  盐水', 6146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aversion', 'n.  厌恶； 讨厌的事和人', 6147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dipper', 'n.  药勺', 6148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pension', 'n.  养老金， 年金', 6149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preparatory', 'adj.  预备的', 6150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vein', 'n.  静脉', 6151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'veil', 'v.  用面纱掩盖； 掩饰 n. 面纱，遮蔽物', 6152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hierarchy', 'n.  等级制度； 统治集团', 6153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'licentious', 'adj.  放肆的', 6154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'posterior', 'adj.  较晚的', 6155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amphitheater', 'n.  古罗马的圆形剧场， 竞技场， 似圆形剧场的场所', 6156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'panic', 'n.  恐慌， 惊慌', 6157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proxy', 'n.  代理人', 6158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fold', 'v.  对折', 6159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'patter', 'v.  喋喋不休', 6160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boiling', 'n.  沸腾', 6161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impervious', 'adj.  不可渗透的； 不可破坏的', 6162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intermediate', 'adj. 中间的，居间的；中级的 n.  中间体， 媒介物', 6163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'simultaneously', 'adv.  同时地', 6164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'competitive', 'adj.  竞争的', 6165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compression', 'n.  浓缩， 压缩， 压榨；  压缩', 6166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambrosial', 'adj.  芳香的， 特别美味的', 6167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sentient', 'adj.  有感觉力的', 6168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frank', 'adj.  坦白的， 直率的', 6169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exacerbate', 'v.  使恶化， 使加剧； 使发怒', 6170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapt', 'adj.  全神贯注的', 6171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heterodox', 'adj.  异端的； 非正统的', 6172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virus', 'n.  病毒', 6173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aerate', 'v.  使充满气体', 6174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anterior', 'adj.  前面的； 逻辑上在前的', 6175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blaspheme', 'v.  亵渎； 咒骂， 辱骂', 6176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recourse', 'n.  求援， 求助', 6177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virtu', 'n.  古董类', 6178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revocation', 'n.  撤回', 6179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extinction', 'n.  灭绝', 6180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cadaver', 'n.  死尸， 尸体', 6181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contestant', 'n.  竞争者； 参赛者', 6182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nickname', 'n. 诨号，绰号 vt.  给…起绰号', 6183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'genre', 'n.  类型； 流派', 6184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trickery', 'n.  欺骗', 6185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'relinquish', 'v.  放弃', 6186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ignition', 'n.  灼烧', 6187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'humanity', 'n.  人类， 人性， 人情； 人文科学', 6188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radiance', 'n.  光辉； 闪烁', 6189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'charge', 'n. 费用，价钱 v. 控告，指控', 6190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appendage', 'n.  附属肢体', 6191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alternate', 'v. 交替，轮流 adj.  交替的， 轮流的', 6192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infuriate', 'adj.  狂怒的 v.  激怒', 6193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cacophonous', 'adj.  发音不和谐的', 6194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recreate', 'v.   得到休养，  得到娱乐', 6195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assuage', 'vt.  缓和， 减轻； 镇定', 6196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tropical', 'adj.  热带的', 6197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repulsion', 'n.  斥力', 6198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forgery', 'n.  伪造', 6199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'renascent', 'adj.  新生的， 复活的， 复兴的', 6200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enchant', 'v.  对…施行妖法， 用妖术迷惑； 使心醉， 使销魂， 使迷住', 6201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'burgeon', 'vi.  萌芽； 快速成长', 6202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'naive', 'adj.  天真的； 幼稚的', 6203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clarify', 'v.  澄清， 阐明', 6204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'duplicity', 'n.  奸诈， 狡猾', 6205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'residual', 'n.  残留', 6206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'congenial', 'adj.  性格相似的， 意气相投的', 6207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generosity', 'n.  慷慨， 宽大', 6208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acclimate', 'v.  使适应新环境', 6209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exclude', 'v.  把…排除在外， 排斥', 6210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enlighten', 'v.  启发， 启蒙， 教导， 启迪， 开导', 6211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utmost', 'adj. 极度的，极端的 n.  极限， 极度， 最大可能', 6212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perturb', 'v.  使感到不安', 6213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'needy', 'adj.  贫困的， 非常贫穷的', 6214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oxidize', 'v.  氧化', 6215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buffoonery', 'n.  打诨； 滑稽', 6216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deduct', 'v.  扣除， 减去', 6217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'specious', 'adj.  华而不实的， 徒有其表的； 似是而非的', 6218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'voracious', 'adj.  狼吞虎咽的； 贪婪的', 6219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'image', 'n.  像', 6220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caricature', 'n. 讽刺画，漫画；讽刺描述法；歪曲的模仿 vt.  画成漫画讽刺', 6221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terse', 'adj.  简洁的， 扼要的', 6222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pallid', 'adj.  苍白的； 暗淡的', 6223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'topography', 'n.  地形， 地形学', 6224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quorum', 'n.  法定人数； 选出的团体', 6225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portray', 'v.  画 ， 画  ； 描绘， 描写， 描述', 6226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inexplicable', 'adj.  无法说明的； 难以理解的', 6227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blight', 'vt.  毁灭', 6228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ruddy', 'adj.  红色的； 红润的', 6229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pontiff', 'n.  罗马教皇； 主教', 6230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'confrontation', 'n.  对抗', 6231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comestible', 'adj. 可吃的 n.  食物', 6232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'profound', 'adj.  深刻的， 意义深远的； 渊博的， 造诣深的', 6233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homogeneous', 'adj.  同种类的， 同性质的， 有相同特征的', 6234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penumbra', 'n.  半影', 6235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'usurp', 'v.  篡夺； 篡位； 侵占', 6236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aggress', 'v.  攻击； 侵犯', 6237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'condone', 'v.  宽恕， 赦免', 6238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electroscope', 'n.  验电器', 6239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aspiration', 'n.  强烈的愿望； 志向， 抱负', 6240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'usury', 'n.  高利贷； 高利', 6241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'necessity', 'n.  必要性，  需要； 必需品', 6242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foible', 'n.  小缺点； 弱点', 6243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abeyance', 'n.  暂时无效； 中止', 6244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recreant', 'n.  懦夫', 6245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compelling', 'adj.  强制的； 引人注目的', 6246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'halcyon', 'adj.  平静的', 6247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'origin', 'n.  起源， 由来； 出身， 来历； 原点', 6248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocal', 'adj.  嗓音的， 声音的， 有声的', 6249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precaution', 'n.  预防， 警惕， 谨慎， 小心； 预防措施', 6250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'personality', 'n.  人格， 个性； 人物', 6251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subterfuge', 'n.  托辞； 借口', 6252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rate', 'n.  率， 比率； 速度， 速率', 6253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sanction', 'v.  同意， 许可， 准许', 6254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deduce', 'v.  推论， 演绎出', 6255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obsolescent', 'adj.  逐渐被废弃的； 即将过时的', 6256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extemporaneous', 'adj.  无准备的， 即席的', 6257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oak', 'n.  橡树', 6258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proverb', 'n.  谚语', 6259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tangential', 'adj.  切线的', 6260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prosperity', 'n.  繁荣， 兴旺', 6261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divide', 'v.  除', 6262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adulatory', 'adj.  奉承的', 6263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contend', 'v.  斗争， 竞争； 主张', 6264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'covert', 'adj.  隐蔽的， 偷偷摸摸的', 6265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'potion', 'n.  一服， 一剂', 6266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thwart', 'v.  反对， 阻碍； 横过', 6267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'armory', 'n.  兵工厂， 军械库', 6268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gamble', 'v. 赌博 n. 冒险，碰运气', 6269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gaucherie', 'n.  笨拙', 6270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deport', 'v.  举止； 驱逐', 6271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'luminescent', 'adj.  发冷光的', 6272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'counter', 'n.  计数器', 6273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crestfallen', 'adj.  垂头丧气的', 6274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coagulate', 'v.  凝结', 6275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cylinder', 'n.  圆柱体', 6276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affray', 'v.   吵架， 打架', 6277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'starch', 'n.  淀粉', 6278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sedate', 'adj.  安静的； 稳重的', 6279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'withdraw', 'v.  取回， 收回； 撤销', 6280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'promotion', 'n.  提升， 晋级；  宣传， 推销', 6281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'colloquialism', 'n.  口语体； 口语用法', 6282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wry', 'adj.  扭歪的； 挖苦的， 揶揄的', 6283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'straightforward', 'adj.  直截了当的， 简单明了的； 正直的， 诚实的， 坦率的', 6284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transcription', 'n.  转录', 6285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exhilarate', 'v.  使高兴； 使振奋', 6286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'languish', 'v.  憔悴； 凋萎', 6287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tabulate', 'v.  把…制成表格', 6288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capricious', 'adj.  任性的； 反复无常的', 6289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legislative', 'adj.  立法的， 立法机关的', 6290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transcribe', 'v.  转录', 6291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lunatic', 'adj.  精神错乱的， 疯狂的； 极端愚蠢的', 6292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intricate', 'adj.  错综复杂的， 难以理解的', 6293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capacious', 'adj.  容积大的； 宽敞的； 广阔的', 6294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ciliate', 'adj. 有纤毛的；有睫毛的；纤毛虫的 n.  纤毛虫', 6295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'context', 'n.  上下文， 文章前后关系', 6296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abidance', 'n.  居住； 遵守', 6297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'augur', 'v.  占卜， 预言 n. 占兆官；占卜师，预言者', 6298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'advisory', 'adj.  咨询的； 劝告的', 6299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'issue', 'v. 流出，放出；发行，发表，颁布 n.  发行 ，  期号； 问题， 争论点， 争端', 6300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pundit', 'n.  博学者', 6301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lingual', 'adj.  语言的', 6302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subsistence', 'n.  生存； 生活', 6303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dejected', 'adj.  沮丧的， 灰心的', 6304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'metal', 'n.  金属', 6305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'audacity', 'n.  大胆， 厚颜', 6306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autarchy', 'n.  独裁； 专制', 6307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'germination', 'n.  发芽', 6308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'habitable', 'adj.  可居住的', 6309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malign', 'v. 诽谤 adj.  恶毒的', 6310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plaintive', 'adj.  悲哀的， 哀伤的', 6311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lively', 'adj.  活泼的， 活跃的', 6312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malleable', 'adj.  有延展性的， 可锻的； 易受影响的， 能根据环境的变化而调整的， 适应的', 6313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supplement', 'n.  补角， 指两角之和为180度', 6314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alteration', 'n.  变更， 改造', 6315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brittle', 'adj.  易碎的； 脆弱的', 6316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affinity', 'n.  构造相似； 特点相近； 密切关系', 6317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gypsy', 'n.  吉普赛人', 6318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedestal', 'n.   基座， 台座， 柱脚', 6319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pertinacity', 'n.  顽固', 6320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'semblance', 'n.  外表； 伪装', 6321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solicitude', 'n.  关怀', 6322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'admonish', 'vt.  劝告， 训诫， 警告', 6323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indefinitely', 'adv.  无限定地', 6324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gibberish', 'n.  快速而含混不清的言语， 胡言乱语', 6325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'occurrence', 'n.  发生， 出现； 事件， 事故， 发生的事情', 6326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bauble', 'n.  小玩意', 6327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recede', 'vi.  退， 退去， 渐渐远去； 向后倾斜； 缩进', 6328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'delegate', 'n.  代表， 代表团成员 vt.  委派  …为代表； 授 ， 把…委托给', 6329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'literature', 'n.  文学； 文学作品； 文献', 6330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sphere', 'n.  球体', 6331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'digest', 'v.  消化 n. 摘要，文摘', 6332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'melodious', 'adj.  旋律优美的', 6333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irreparable', 'adj.  不能挽回的', 6334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abyss', 'n.  深渊', 6335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belief', 'n.  信仰， 信条； 相信， 信念', 6336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'veto', 'v. 否决〔尤指他人或其他组织已赞同之事〕 n. 否决(权)', 6337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'centipede', 'n.  蜈蚣', 6338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encore', 'n.  要求再演； 加演', 6339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exuberant', 'adj.  繁茂的； 丰富的； 兴高采烈的， 热情洋溢的', 6340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proficient', 'adj.  精通的， 熟练的', 6341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remembrance', 'n.  回想， 记忆', 6342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'halve', 'v.  把…平分为二； 将…减半', 6343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obnoxious', 'adj.  不愉快的； 讨厌的', 6344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penitent', 'adj.  忏悔的； 悔过的', 6345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impromptu', 'n.  即席演出， 即兴之作', 6346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verbose', 'adj.  冗长的； 嗦的', 6347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'photon', 'n.  光子', 6348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slender', 'adj.  修长的， 苗条的； 微小的， 微薄的', 6349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terminus', 'n.  终点', 6350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compensate', 'v.  偿还， 补偿， 付报酬', 6351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'attache', 'n.  随员； 大使馆馆员', 6352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conscious', 'adj.  意识到的， 自觉的； 有意识的， 神志清醒的', 6353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dilatory', 'adj.  拖拉的', 6354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malodorous', 'adj.  有恶臭的', 6355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'animadversion', 'n.  批评， 非难', 6356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prodigal', 'adj. 浪费的 n.  挥霍者', 6357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outcast', 'n.  被驱逐者， 流浪者', 6358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'placid', 'adj.  平静的', 6359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coax', 'v.  劝诱； 诱骗', 6360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contentment', 'n.  满足， 满意', 6361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beatify', 'v.  使享福；  为  行宣福礼', 6362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laudable', 'adj.  值得赞美的， 值得称赞的', 6363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'edge', 'n.  立体的边或棱', 6364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brotherhood', 'n.  手足情谊， 兄弟关系', 6365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'skirt', 'n.  边缘', 6366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'orchestra', 'n.  管弦乐队', 6367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'widespread', 'adj.  分布广泛的， 普遍的', 6368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antique', 'adj.  古时的， 古老的 n. 古物，古玩，古董', 6369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'asexual', 'adj.  无性的； 无性生殖的', 6370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'morose', 'adj.  郁闷的； 乖僻的', 6371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'toxic', 'adj.  有毒的， 因中毒引起的', 6372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coalescence', 'n.  合并， 接合； 联合', 6373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contest', 'v.  争论， 争辩， 竞赛， 争夺 n.  竞争， 竞赛， 比赛', 6374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'turmoil', 'n.  骚动； 混乱', 6375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'organelle', 'n.  细胞器', 6376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overleap', 'v.  越过', 6377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diagnosis', 'n.  诊断', 6378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'doctrinaire', 'n.  空谈家； 教条主义者', 6379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plus', 'adj.  表示加的； 正的 prep. 加，加上', 6380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'raze', 'v.  夷为平地', 6381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'license', 'n.  许可  ； 执照', 6382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'expand', 'v.   膨胀，  扩张； 张开， 展开', 6383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dismissal', 'n.  免职， 解雇', 6384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ohm', 'n.  欧姆', 6385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'squander', 'v.  浪费', 6386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perimeter', 'n.  周长', 6387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suggestive', 'adj.  提示的， 暗示的', 6388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrieve', 'v.  重新得到； 恢复', 6389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cantata', 'n.  清唱剧； 康塔塔； 大合唱', 6390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malice', 'n.  恶意， 怨恨', 6391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thermometer', 'n.  温度计', 6392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'athwart', 'adv. 横跨着，斜穿过；逆，相反 prep.  横过， 反对， 逆', 6393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heat', 'n.  热', 6394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discrepant', 'adj.  差异的', 6395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'furrow', 'n.  分裂沟', 6396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'code', 'n.  密码； 代码， 代号， 编码', 6397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legacy', 'n.  遗赠的财物， 遗产', 6398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'displace', 'v.  移置， 转移； 取代， 置换', 6399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nutriment', 'n.  营养品', 6400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'swindle', 'v.  诈骗', 6401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'veritable', 'adj.  真正的', 6402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hemoglobin', 'n.  血红蛋白', 6403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inestimable', 'adj.  无价的， 无法估计的', 6404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'illusion', 'n.  错觉， 幻觉； 假象', 6405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'whine', 'v.  哭诉， 发牢骚， 发呜呜声', 6406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'considerable', 'adj.  相当大  的， 可观的； 值得考虑的， 重要的', 6407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'toxin', 'n.  毒素', 6408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subsist', 'v.  生存， 生活； 供养', 6409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brief', 'adj.  简短的； 短暂的 n. 摘要，大纲 vt. 简短介绍；简要汇报', 6410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recover', 'v.  重新获得； 痊愈， 复原', 6411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'influx', 'n.  流入', 6412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'devastate', 'v.  毁坏', 6413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prodigy', 'n.  天才  ； 奇观， 奇事', 6414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exonerate', 'v.  免罪； 免除', 6415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'surfeit', 'v.  使饮食过度', 6416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disavow', 'v.  不承认， 否认； 否定， 抵赖', 6417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maple', 'n.  枫树', 6418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compliant', 'adj.  顺从的； 适应的', 6419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obsequies', 'n. 葬礼，丧礼', 6420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diagonal', 'adj. 对角的，对角线的', 6421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prophetic', 'adj.  预言的', 6422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aroma', 'n.  芳香， 香气， 香味', 6423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transmute', 'v.  改变', 6424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'readily', 'adv.  容易地； 乐意地， 欣然地', 6425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'projector lens', '放映机镜头', 6426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oratory', 'n.  讲演术', 6427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wrest', 'n.  夺取， 强夺； 歪曲', 6428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'determination', 'n.  决心， 果断', 6429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discipline', 'v.  训练； 锻炼 n. 纪律；学科；规定；训练', 6430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'burnish', 'vi.  磨光； 擦亮', 6431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'calculus', 'n.  微积分学； 结石', 6432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ensconce', 'v.  使隐藏； 安置', 6433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proclamation', 'n.  宣布', 6434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valediction', 'n.  告别； 告别词', 6435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suspension', 'n.  吊； 悬浮； 悬浮液； 暂停， 中止； 悬而未决， 延迟', 6436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inevitable', 'adj.  不可避免的， 必然发生的', 6437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'relapse', 'v.  旧病复发', 6438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antecede', 'v.  先前， 先行', 6439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insensible', 'adj.  失去知觉的； 麻木不仁的； 无感觉的', 6440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vaccinate', 'v.  进行预防接种', 6441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cognitive', 'adj.  认知的， 认识的， 有感知的', 6442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sear', 'v.  烤焦， 使枯萎', 6443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disingenuous', 'adj.  不真诚的， 无诚意的', 6444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'placenta', 'n.  胎盘', 6445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bridge', 'n. 桥 vt.  架桥； 渡过', 6446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evaporation', 'n.  蒸发', 6447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commentary', 'n.  注释， 解说词', 6448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impeccable', 'adj.  完美的； 无懈可击的', 6449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minus', 'adj.  表示减  的， 负的； 阴性的 prep. 减，除', 6450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mistrust', 'n.  不信任， 猜疑', 6451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conservative', 'adj.  保守的； 谨慎的 n. 保守主义者', 6452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serenity', 'n.  平静', 6453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seed', 'n.  种子', 6454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lifelong', 'adj.  终身的， 毕生的', 6455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anaerobic respiration', '[植] 无氧呼吸；[微] 厌氧呼吸', 6456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'torque', 'n.  扭矩', 6457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dais', 'n.  台， 讲台', 6458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'workmanlike', 'adj.  精巧的， 技巧熟练的', 6459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belle', 'n.  美女， 美人', 6460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chromatic', 'adj.  彩色的； 半音的', 6461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disturb', 'v.  扰乱； 打乱； 打扰， 使不安； 使烦恼', 6462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lecherous', 'adj.  淫荡的； 好色的', 6463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vector', 'n.  矢量', 6464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'armful', 'n.  一抱之量', 6465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensual', 'adj.  感觉的', 6466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'righteous', 'adj.  正直的， 正当的； 公正的， 正义的', 6467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abominable', 'adj.  讨厌的， 令人憎恶的', 6468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'speculate', 'v.  推测， 思索； 做投机买卖', 6469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recrudescent', 'adj.  复发的', 6470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adorn', 'vt.  装饰', 6471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dismantle', 'v.  拆掉…覆盖物； 拆卸  ； 摧毁， 粉碎', 6472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bedaub', 'v.  涂污； 过分地装饰', 6473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cantonment', 'n.  宿营地，  军营， 兵营', 6474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquaint', 'v.  使认识， 使了解', 6475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'censorship', 'n.  审查； 审查制度', 6476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquiescence', 'n.  默许', 6477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vacuity', 'n.  空虚', 6478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temperate forest', '温带森林（等于temperate woodland）', 6479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'joint', 'adj. 联合的，共同的，共有的 n. 关节 v. 把〔肉〕切成大块', 6480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'saline', 'adj.  盐的； 含盐的', 6481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'separate', 'adj. 分开的 v.  分开', 6482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'urine', 'n.  尿', 6483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reasonable', 'adj.  合理的， 有道理的； 适度的； 通情达理的', 6484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'innumerable', 'adj.  无数的， 数不清的', 6485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stultify', 'v.  使显得愚笨； 使变无效， 使成为徒劳', 6486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fatalism', 'n.  宿命论', 6487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elicit', 'vt.  得出， 引出， 抽出， 引起', 6488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'relegate', 'v.  驱逐， 放逐； 丢弃； 委托； 移交', 6489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'qualm', 'n.  疑虑', 6490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trivial', 'adj.  琐碎的； 无足轻重的', 6491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misadventure', 'n.  遭遇', 6492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'longevity', 'n.  长寿； 寿命； 耐久性', 6493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reluctant', 'adj.  不情愿的， 勉强的', 6494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scuttle', 'v.  凿洞沉船', 6495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conscientious', 'adj.  认真的， 谨慎的', 6496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forgo', 'v.  抛弃， 放弃', 6497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coil', 'n.  线圈', 6498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ensure', 'v.  确保， 保证', 6499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prescience', 'n.  预知； 先见', 6500);
