INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brittle', 'adj.  易碎的； 脆弱的； 尖利的', 11001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affinity', 'n.  密切关系； 吸引力； 喜爱', 11002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mediate', 'v.  调解， 调停， 斡旋', 11003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amplify', 'vt.  放大； 增强； 详述， 充实', 11004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inflation', 'n.  通货膨胀， 物价上涨； 膨胀', 11005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disposal', 'n.  清除， 外理， 处置； 变卖', 11006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'matrimony', 'n.  婚姻， 婚配', 11007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recede', 'vi.  退， 后退； 渐渐远去； 逐渐减弱', 11008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delegate', 'n.  代表 vt.  委派…为代表， 授权', 11009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literature', 'n.  文学； 文学作品； 文献', 11010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suffragist', 'n.  妇女政权论者', 11011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sphere', 'n.  球； 范围， 领域； 阶层', 11012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'digest', 'v.  消化， 吸收； 领悟 n.  摘要， 概要', 11013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melodious', 'adj.  旋律优美的， 悦耳的', 11014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ethnology', 'n.  民族学， 文化人类学', 11015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ability', 'n.  能力， 才干', 11016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'veto', 'n. 否决权；禁止 vt.  否决； 禁止', 11017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delight', 'v. 愉快，高兴 n.  快乐， 高兴； 令人高兴的事， 乐趣', 11018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proficient', 'adj.  熟练的， 精通的', 11019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuum', 'n.  统一体', 11020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'draw', 'v. 吸引，招引；画，描绘；拖，拉；引起，激起；拨出，抽出；提取，支取；推断出；打成平局 n.  平局， 和局； 抽签', 11021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contender', 'n.  竞争者， 争夺者， 对手', 11022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slender', 'adj.  细长的； 苗条的， 纤细的； 微薄的， 不足的', 11023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terminus', 'n.  终点站', 11024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oral', 'adj.  口头的， 口述的； 口腔的', 11025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compensate', 'v.  赔偿， 弥补', 11026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conscious', 'adj.  自觉的， 意识到的； 有知觉的， 有意识的； 有意的， 刻意的', 11027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transaction', 'n.  交易， 业务； 办理， 处理', 11028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accomplishment', 'n.  成就； 完成； 才艺， 技艺', 11029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pants', 'n.  内裤， 短裤； 裤子', 11030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'placid', 'adj.  平静的， 安静的； 温和的， 文静的', 11031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solitary', 'adj.  孤独的； 单独的， 独自的； 单个的； 唯一的， 仅有的', 11032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'second', 'adj. 第二的；次等的，二等的 v. 赞成，附和 num.  第二 n. 秒；瞬间，片刻', 11033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laudable', 'adj.  值得赞美的， 值得称赞的', 11034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edge', 'v.  徐徐移动； 略为增加； 给…加边 n. 边，边缘；刀口，刃；优势', 11035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orchestra', 'n.  管弦乐队', 11036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sufficient', 'adj.  足够的， 充分的', 11037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glaze', 'v.  上釉； 给…装玻璃 n. 釉料；糖浆', 11038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'claim', 'v&n.  声称， 断言； 要求； 索赔', 11039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'widespread', 'adj.  分布广泛的， 普遍的', 11040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antique', 'n. 古物，', 11041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thaw', 'v. 融化，解冻；化冻；变暖；变得友善 n.  解冻时期； 缓和', 11042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fasten', 'v.  使固定； 系牢， 扎牢； 握住， 抓牢', 11043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toxic', 'adj.  有毒的； 中毒的', 11044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contest', 'vt.  竞争； 争辩， 就…提出异议 n.  竞赛； 辩论； 争夺', 11045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asymmetrical', 'adj.  不均匀的， 不对称的', 11046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turmoil', 'n.  骚动， 混乱； 焦虑', 11047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clench', 'v&n.  握紧， 抓牢； 咬紧', 11048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modernity', 'n.  现代性', 11049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'schematic', 'adj.  图解的； 纲要的； 严谨的', 11050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rekindle', 'vt.  重新点燃； 使振作', 11051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expansion', 'n.  扩张； 膨胀', 11052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wrench', 'v. 扭伤；猛拉，猛扭；使痛苦 n.  扭伤； 痛苦， 难受； 扳手', 11053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'license', 'n. 许可证，执照 vt.  批准， 许可', 11054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puff', 'v. 喘气，喘息；喷出 n.  吸； 一缕； 喘息', 11055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expand', 'v.  扩张； 膨胀； 伸展， 伸开', 11056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squander', 'vt.  浪费， 挥霍', 11057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synchronizer', 'n.  同步装置', 11058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perimeter', 'n.  周长； 外缘， 边缘', 11059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'essay', 'n.  散文， 随笔； 短文； 评论', 11060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrieve', 'vt.  取回， 索回； 挽回， 扭转颓势； 检索', 11061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'survey', 'v.  调查； 概述 n.  调查； 概述', 11062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'malice', 'n.  恶意， 怨恨', 11063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postpone', 'v.  延期， 推迟', 11064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'codify', 'vt.  把…编成法典， 使法律成文化； 整理， 系统化', 11065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dorsal', 'adj.  背部的， 背脊的', 11066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'code', 'vt. 编纂；把…编码 n.  法典， 法规； 密码， 代码', 11067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potassium', 'n.  钾', 11068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'displace', 'vt.  取代； 撤职； 迫使…离开家园', 11069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hammer', 'v. 锤打 n.  锤， 槌； 锤子', 11070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ideology', 'n.  思想体系； 意识形态', 11071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seal', 'vt. 密封；确定，使成定局 n.  海豹； 封铅， 封条； 印， 图章', 11072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'investigate', 'v.  研究， 调查', 11073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storage', 'n.  库房； 贮藏； 存储', 11074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'troposphere', 'n.  对流层', 11075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swindle', 'vt&n.  诈骗， 骗取', 11076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illusion', 'n.  幻觉， 错觉； 幻想中的事物', 11077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'productivity', 'n.  生产力， 生产率', 11078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reserve', 'n. 储备；自然保护区；谨慎；替补队员；后备部队 vt.  保留； 预订', 11079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsist', 'vi.  存活， 生存', 11080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invertebrate', 'adj.  无脊椎的 n. 无脊椎动物', 11081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dive', 'vi&n.  跳水； 潜水', 11082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sympathy', 'n.  同情， 同情心； 赞同， 支持', 11083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rescue', 'vt&n.  营救， 搭救', 11084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brief', 'adj. 简短的，短暂的；简洁的', 11085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recover', 'v.  复原， 恢复； 重新获得； 收回', 11086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'influx', 'n.  注入， 涌入', 11087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'determine', 'v.  查明， 确定； 决心， 决定； 支配， 影响', 11088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devastate', 'vt.  破坏， 毁坏； 令人震惊， 使难以承受', 11089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embark', 'v.  上船', 11090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cousin', 'n.  堂兄弟， 堂姐妹', 11091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intelligent', 'adj.  有才智的， 聪明的', 11092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confer', 'v.  授予； 协商， 商讨', 11093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'friction', 'n.  摩擦； 摩擦力； 矛盾， 冲突', 11094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'walnut', 'n.  胡桃； 胡桃木', 11095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incessantly', 'adv.  不断地', 11096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imagist', 'adj. 意象派的 n.  意象派诗人', 11097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiation', 'n.  放射； 辐射； 放射物， 放射线； 辐射的热', 11098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'luxury', 'adj. 奢华的 n.  奢侈， 奢华； 奢侈品', 11099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diagonal', 'adj. 斜线的，', 11100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knit', 'v.  编结， 编织； 紧密结合， 使紧凑； 愈合； 皱紧， 皱', 11101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aroma', 'n.  芳香， 香味； 气氛， 氛围', 11102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subversive', 'adj. 颠覆性的，破坏性的 n.  颠覆分子', 11103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strategic', 'adj.  对全局有重要意义的， 关键的； 战略性的', 11104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wholesome', 'adj.  健康的， 有利健康的； 有道德的', 11105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'readily', 'adv.  欣然地； 容易地', 11106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convenience', 'n.  便利； 便利设施', 11107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discipline', 'vt. 训练；惩罚 n.  纪律； 学科', 11108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calculus', 'n.  微积分； 结石', 11109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expedient', 'adj.  得当的， 可取的 n. 权宜之计，应急办法，临时手段', 11110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emission', 'n.  散发物， 排放物； 发射， 排放', 11111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ensconce', 'vt.  使安顿， 安置， 使安坐', 11112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freeze', 'v.  结冰， 凝固', 11113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inevitably', 'adv.  不可避免地， 必然地', 11114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'estimate', 'v.  评估， 估计； 估价 n.  估计； 估价； 评价， 看法', 11115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brand', 'vt. 铭刻；打烙印于；丑化，败坏名声 n.  商标， 品牌； 类型； 烙印', 11116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspension', 'n.  暂停； 暂缓， 推迟， 延期； 悬架； 悬浮液', 11117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proposal', 'n.  提议， 建议； 求婚', 11118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vibrant', 'adj.  振动的； 活泼的， 充满生气的', 11119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insanity', 'n.  精神错乱， 疯狂', 11120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recreation', 'n.  娱乐， 消遣', 11121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skyscraper', 'n.  摩天楼', 11122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portable', 'adj.  轻便的， 便携的， 手提式的', 11123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ancient', 'adj.  古代的； 古老的', 11124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antecede', 'vt.  居先； 高于', 11125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squirrel', 'n.  松鼠', 11126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cognitive', 'adj.  认识的； 认知的， 有感知的', 11127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attorney', 'n.  辩护律师； 代理人', 11128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adopt', 'v.  采用； 收养， 领养； 正式通过， 批准', 11129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expire', 'vi.  到期， 期满， 失效； 断气， 去世', 11130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'viral', 'adj.  病毒的， 病毒引起的', 11131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oppose', 'v.  反对， 对抗', 11132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'singular', 'adj.  单数的； 突出的， 卓越的； 异常的', 11133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'device', 'n.  装置， 设备； 手法， 策略', 11134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evaporation', 'n.  蒸发； 消失， 不存在', 11135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commentary', 'n.  评论， 注释； 实况报道， 现场解说', 11136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homosexuality', 'n.  同性恋； 同性恋行为', 11137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minus', 'adj. 减的，负的 prep.  减 n. 负数；减号；不足', 11138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conservative', 'adj. 保守的，守旧的；不时新的，传统的 n.  保守派', 11139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skeletal', 'adj.  骨骼的， 骸骨的； 梗概的； 轮廓的', 11140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seep', 'v.  漏出， 渗漏', 11141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsubstantiated', 'adj.  未经证实的， 无事实根据的', 11142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cabin', 'n.  小屋； 机舱， 船舱', 11143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seem', 'v.  好像， 似乎', 11144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apprenticeship', 'n.  学徒的身份； 学徒的年限', 11145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disturb', 'vt.  打扰； 搅乱， 弄乱； 使烦恼， 使不安', 11146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'persist', 'vi.  坚持； 持续', 11147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pump', 'n. 泵 vt.  抽', 11148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pierce', 'v.  刺穿， 刺破； 穿孔， 打眼', 11149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calendar', 'n.  日历， 挂历， 月历； 日程表', 11150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patriarch', 'n.  家长， 族长', 11151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intern', 'n.  实习生 vt.  拘禁， 软禁', 11152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensual', 'adj.  感觉的， 感官的； 肉欲的； 耽于感官享受的', 11153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'righteous', 'adj.  正直的， 公正的； 正义的， 正当的', 11154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speculate', 'v.  推测； 深思， 沉思； 投机， 做投机买卖', 11155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'closet', 'adj.  隐蔽的； 私下的， 秘密的 vt. 把…关在房间里 n. 橱，壁橱', 11156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heed', 'n&v.  注意， 留心', 11157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adorn', 'vt.  装饰， 装扮', 11158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monster', 'adj.  巨大的， 庞大的 n. 怪物；庞然大物；恶魔', 11159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cement', 'n. 水泥；胶合剂 vt.  巩固； 使团结', 11160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subway', 'n.  地铁', 11161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scourge', 'vt. 鞭笞；使受苦，折磨 n.  鞭子； 祸害； 鞭笞', 11162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquaint', 'vt.  使认识； 使熟悉', 11163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atrophy', 'n.  萎缩', 11164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pulp', 'vt. 使成浆状 n.  纸浆； 浆状物', 11165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undergraduate', 'n.  大学肄业生； 大学本科生', 11166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antibiotic', 'adj.  抗菌的', 11167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'joint', 'adj.  连接的； 共同的， 共有的， 联合的 n. 关节，骨节；接头，接合处', 11168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'separate', 'v.  分离； 划分； 区别； 分居 adj.  分离的； 个别的', 11169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reasonable', 'adj.  合理的， 适当的； 通情达理的； 公道的', 11170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endangered', 'adj.  濒危的， 将要灭绝的', 11171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haphazard', 'adj.  偶然的， 任意的； 无计划的， 无秩序的', 11172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wick', 'n.  蜡烛芯； 灯芯', 11173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biannual', 'adj.  一年两次的', 11174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elicit', 'vt.  得出， 引出； 诱出', 11175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relegate', 'vt.  使贬职， 使降级； 放逐， 贬谪', 11176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambiguity', 'n.  模棱两可的话； 歧义', 11177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trivial', 'adj.  琐碎的， 微不足道的', 11178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awareness', 'n.  知道， 意识， 察觉', 11179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postcard', 'n.  明信片', 11180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'longevity', 'n.  长寿； 寿命', 11181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'military', 'adj. 军事的 n.  [the ～]军队， 军方', 11182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reluctant', 'adj.  不情愿的， 勉强的', 11183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conscientious', 'adj.  凭良心的； 认真谨慎的， 一丝不苟的', 11184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coil', 'v. 盘绕，卷 n.  卷； 线圈', 11185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authoritative', 'adj.  官方的； 权威性的， 可信的； 专断的， 命令式的', 11186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ensure', 'vt.  确保， 担保， 保证', 11187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organism', 'n.  生物， 有机物； 有机体', 11188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epidemic', 'adj.  流行性的， 传染性的 n. 流行；流行病', 11189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suppose', 'v.  假设， 推测； 认为， 料想； 要不', 11190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scruple', 'n&vi.  踌躇， 顾忌， 顾虑', 11191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remarkable', 'adj.  显著的， 值得注意的； 非凡的', 11192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flavor', 'n. 风味，滋味；调味品 vt.  给…调味', 11193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recess', 'n. 休会期；休庭；暂停；凹室，', 11194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extract', 'vt.  取出； 提取， 榨取 n.  提出物； 摘录， 选段； 精， 汁', 11195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outspoken', 'adj.  直言不讳的， 坦率的', 11196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obscure', 'adj. 暗的，模糊的，朦胧的；费解的，晦涩的；不著名的，不重要的 vt.  使变模糊； 使费解', 11197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noxious', 'adj.  有害的； 有毒的', 11198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bolster', 'vt. 支持；改善 n.  垫子， 枕垫', 11199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'region', 'n.  层； 地区， 区域； 范围', 11200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deceive', 'v.  欺骗', 11201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ingenious', 'adj.  巧妙的； 聪明的， 机敏的； 善于创造发明的； 设计独特的， 别致的', 11202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'questionnaire', 'n.  问卷， 调查表', 11203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breakthrough', 'n.  突破， 重大进展', 11204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snack', 'n.  快餐， 小吃， 点心', 11205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amphibious', 'adj.  两栖的； 水陆两用的', 11206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imprint', 'vt.  使铭记， 使牢记； 压印 n.  印记， 印痕； 持久的影响', 11207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destination', 'n.  目的地， 终点', 11208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yoke', 'n. 裤腰；牛轭；奴役，束缚 vt.  使结合， 连接', 11209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vertical', 'adj. 垂直的，竖直的 n.  垂直线', 11210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reciprocal', 'adj. 相互的；互惠的；相应的；', 11211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perpetuate', 'vt.  使永存， 使持续', 11212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pure', 'adj.  纯洁的； 纯净的； 完全的； 纯理论的， 抽象的', 11213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'damp', 'adj. 潮湿的 n. 潮湿；湿气 vt.  弄湿； 减弱， 抑制', 11214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emphasize', 'vt.  强调， 着重', 11215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brighten', 'v.  更明亮； 快活起来； 有希望', 11216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ore', 'n.  矿； 矿物， 矿石', 11217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slight', 'adj. 轻微的，微小的 v. 侮慢；轻视，冷落', 11218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'previous', 'adj.  先前的， 在前的', 11219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'argue', 'v.  争论， 辩论； 主张， 论证； 说服， 劝说', 11220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concomitant', 'adj. 伴随的 n.  伴随物', 11221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cumbersome', 'adj.  笨重的； 麻烦的； 累赘的， 冗长的', 11222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'belie', 'vt.  给人以错觉； 掩饰； 证明…不正确', 11223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'premature', 'adj. 早熟的；过早的；不成熟的，仓促的 n.  早产儿', 11224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superior', 'adj. 较高的；更好的；有优越感的，高傲的；超群的 n.  上级， 长官', 11225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choir', 'vi.  合唱 n. 唱诗班，合唱队', 11226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compensation', 'n.  补偿， 赔偿； 赔偿金', 11227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accessory', 'adj.  辅助的 n. 附件，零件；配饰；从犯，同谋', 11228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ecosystem', 'n.  生态系统', 11229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seminar', 'n.  研讨会； 研讨班', 11230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pupil', 'n.  小学生； 瞳孔', 11231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'naturalist', 'n.  自然主义者； 博物学家', 11232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'venom', 'n.  毒液； 恶意， 怨恨', 11233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hazard', 'n. 危险；风险 vt.  尝试着做； 冒…风险， 使处于危险', 11234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melodrama', 'n.  情节剧， 通俗剧； 戏剧性的事件', 11235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vegetative', 'adj.  植物的； 有生长力的', 11236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proof', 'adj.  耐…的， 防…的 n. 证据，证明；证词；检验，证实；校样', 11237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'militant', 'adj. 好战的，好暴力的 n.  激进分子', 11238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phase', 'n. 相位，月相；阶段，时期 vt.  分阶段实行， 逐步做', 11239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dilute', 'adj. 冲淡的，稀释的 vt.  冲淡， 稀释； 淡化， 削弱', 11240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'method', 'n.  方法， 办法， 措施； 秩序', 11241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contract', 'v.  订合同； 收缩； 感染， 染上 n.  合同， 契约', 11242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scroll', 'n.  卷轴； 纸卷， 画卷； 名册', 11243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sluggish', 'adj.  行动迟缓的； 不活泼的； 无精打采的， 怠惰的', 11244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yolk', 'n.  蛋黄， 卵黄', 11245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vascular', 'adj.  血管的， 脉管的', 11246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'susceptible', 'adj.  易受感染的； 易受影响的； 过敏的； 感情丰富的； 能经受…的， 容许…的', 11247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'innovative', 'adj.  革新的， 创新的； 富有革新精神的', 11248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insight', 'n.  洞察力； 领悟', 11249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quiescent', 'adj.  静止的， 寂静的； 静态的', 11250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assail', 'vt.  抨击， 指责； 猛攻； 困扰', 11251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fabric', 'n.  布料， 织品； 构造， 结构', 11252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exact', 'adj. 精确的，准确的；严谨的，严格的；', 11253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'centigrade', 'adj.  百分度的； 摄氏温度的', 11254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cerebral', 'adj.  大脑的； 理智的', 11255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mural', 'adj.  墙壁的； 在墙上的 n. 壁画，壁饰', 11256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'periodic', 'adj.  周期的， 定期的', 11257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seismology', 'n.  地震学', 11258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slander', 'n. 诽谤，中伤，诋毁 vt.  诽谤， 诋毁', 11259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gem', 'n.  宝石， 珍品； 美丽绝伦的事物', 11260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sedentary', 'adj.  久坐的， 固定不动的； 土生的， 不迁徙的； 沉积的', 11261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capacity', 'n.  能力； 容量； 职责， 职位； 生产力', 11262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hemp', 'n.  大麻； 由大麻制成的麻醉药', 11263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saturate', 'vt.  使湿透； 使饱和', 11264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counterfeit', 'adj. 伪造的，假冒的 n. 赝品 vt.  伪造， 仿造', 11265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'course', 'n.  课程， 教程； 过程， 进程； 路线； 一道菜', 11266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barber', 'v.  为…理发； 当理发师 n. 理发师', 11267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precise', 'adj.  准确的， 精确的； 严谨的', 11268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensible', 'adj.  可察觉的， 可感知的； 明智的； 切合实际的； 意识到的', 11269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precious', 'adj.  贵重的； 珍爱的', 11270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspect', 'v.  怀疑， 猜想 adj. 可疑的；不信任的 n.  嫌疑犯， 可疑分子', 11271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apologize', 'vi.  道歉， 认错； 辩解', 11272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mingle', 'v.  混合； 交往', 11273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'braid', 'n. 穗带，饰带；发辫 vt.  编织； 编成辫子', 11274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unravel', 'v.  澄清； 解体， 瓦解； 解开', 11275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edible', 'adj.  可食用的', 11276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chorus', 'n. 合唱曲；合唱队；副歌，叠句；齐声，', 11277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prone', 'adj.  平卧的， 俯卧的； 易于做…的， 倾向于…的', 11278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asset', 'n.  资产， 财产； 有价值的人； 长处， 优点', 11279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exposition', 'n.  展览会， 博览会； 阐释', 11280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minimum', 'adj. 最小的，最低的 n.  最小值， 最低限度', 11281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'date', 'n. 日期，日子；时期，年代；约会；', 11282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reveal', 'vt.  暴露， 揭露； 展现', 11283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depot', 'n.  库房， 仓库； 公共汽车站， 火车站', 11284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theoretical', 'adj.  不切实际的； 理论的', 11285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'owl', 'n.  猫头鹰', 11286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sound', 'adj. 可靠的；健康的，完好无损的；合理的 v.  似乎； 测量…的深度', 11287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harbor', 'vt. 窝藏；藏有 n.  港口', 11288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vibrate', 'v.  颤动， 振动', 11289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hospitable', 'adj.  宜人的； 好客的， 殷勤的； 开通的', 11290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multiplicative', 'adj.  倍增的； 乘法的', 11291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impetus', 'n.  促进， 推动； 刺激； 推动力', 11292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'healing', 'adj. 有治疗功用的 n.  康复， 治疗； 复原', 11293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'realistic', 'adj.  现实的； 逼真的', 11294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revitalize', 'vt.  使恢复生机， 使再生； 使更强壮', 11295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barrier', 'n.  屏障， 障碍物； 检票口； 障碍， 阻力； 隔阂', 11296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caribou', 'n.  北美驯鹿', 11297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simmer', 'vi. 充满；煨，炖 n.  煨， 炖', 11298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eviscerate', 'vt.  取出内脏； 除去主要部分', 11299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resource', 'n. 资源〔指土地、矿产等〕 v. 向…提供资源', 11300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brace', 'vt. 绷紧肌肉；使顶住；使防备；加强，加固 n.  支架， 托架', 11301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brisk', 'adj.  清新的； 敏捷的， 活泼的', 11302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nightmare', 'n.  噩梦； 无法摆脱的恐惧； 可怕的事', 11303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prolonged', 'adj.  长期的， 持久的', 11304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prestige', 'n.  威望； 声望', 11305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spontaneity', 'n.  自发性； 自发行为', 11306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'core', 'n. 地核；果心，核心；要点，精髓 vt.  去掉…的中心部分', 11307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'famish', 'v.  饥饿', 11308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fraud', 'n.  骗子， 冒名顶替者； 冒牌货； 欺骗', 11309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'council', 'n.  委员会； 地方议会', 11310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'igneous', 'adj.  火的， 似火的； 火成的， 火成岩的', 11311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dazzling', 'adj.  令人眼花缭乱的， 耀眼的', 11312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rectangle', 'n.  长方形， 矩形', 11313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rotational', 'adj.  旋转的； 轮流的', 11314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quash', 'vt.  撤销， 废止； 镇压； 平息', 11315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sprawl', 'vi. 伸开四肢坐；扩展，蔓延 n.  扩展， 蔓延； 蔓延物', 11316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concrete', 'adj. 混凝土制的；具体的；确凿的 n.  混凝土', 11317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rustproof', 'adj.  不锈的', 11318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrimp', 'n.  小虾', 11319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abridge', 'vt.  缩短， 删节， 节略， 精简', 11320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penalty', 'n.  处罚， 惩罚； 罚金； 犯规的处罚', 11321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scale', 'n. 鳞；规模；比例；刻度；【音】音阶；等级，级别 vt.  攀登', 11322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vegetation', 'n.  植物； 植被', 11323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gin', 'n. 杜松子酒；弹棉机，', 11324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engaging', 'adj.  迷人的', 11325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contributor', 'n.  投稿者； 贡献者， 捐助者； 促成物', 11326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subdivide', 'v.  再分， 细分', 11327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nosy', 'adj.  爱管闲事的， 好打听的', 11328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salient', 'adj.  显著的， 突出的', 11329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buck', 'v. 猛然弓背跃起；猛然震荡；抵制，反抗 n.  美元； 雄鹿', 11330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'iceberg', 'n.  冰山； 冷冰冰的人', 11331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'station', 'n. 所；站；台；岗位；身份，地位 vt.  安置； 派驻， 驻扎', 11332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feeble', 'adj.  虚弱的， 衰弱的， 无力的', 11333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herb', 'n.  药草， 香草； 草本植物', 11334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herd', 'v.  放牧； 成群， 聚集 n. 牧群，兽群；人群，芸芸众生', 11335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limb', 'n.  肢， 臂； 主枝', 11336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prose', 'n.  散文', 11337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inverse', 'adj. 相反的，反向的 n.  反面； 倒数', 11338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cognition', 'n.  感知， 认知， 认识', 11339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confidence', 'n.  信任； 信心', 11340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cuisine', 'n.  烹饪； 烹调法， 烹调风格', 11341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arbitrary', 'adj.  任意的； 专制的， 专断的', 11342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intent', 'adj.  专心的， 专注的； 急切的 n. 意图，目的', 11343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'readability', 'n.  可读性', 11344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interrogate', 'vt.  审问， 讯问， 盘问', 11345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'astute', 'adj.  机敏的， 精明的', 11346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'challenge', 'n. 挑战；艰巨任务，难题；质疑，质问 vt.  向…挑战； 公然反抗； 对…质疑', 11347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dignity', 'n.  尊严， 庄严； 高贵， 尊贵； 自尊， 自重', 11348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unearth', 'vt.  掘出， 发掘； 揭露', 11349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emit', 'vt.  发出； 放射； 排放', 11350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snap', 'v. 猛咬；折断，断裂；打开，关上；呵斥，厉声说；拍照 adj.  仓促的， 匆忙的 n. 啪嗒声；照片', 11351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sleigh', 'n.  雪橇', 11352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'govern', 'v.  统治， 治理， 管理； 决定， 支配； 控制， 影响', 11353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'numerous', 'adj.  许多的； 无数的', 11354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seismic', 'adj.  地震的， 地震引起的； 影响深远的， 重大的', 11355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resemble', 'vt.  与…相似， 像', 11356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remote', 'adj.  偏僻的， 偏远的； 久远的； 远程的； 关系远的； 微乎其微的； 冷漠的', 11357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cafeteria', 'n.  自助餐厅， 自助食堂', 11358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rupture', 'v.  破裂； 决裂， 断绝', 11359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afflict', 'vt.  使苦恼， 折磨', 11360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluctuate', 'v.  波动； 变化', 11361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calculate', 'v.  计算， 核算； 估计， 推测； 计划， 打算', 11362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rancorous', 'adj.  怨恨的， 满怀恶意的', 11363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'persistent', 'adj.  坚持的， 百折不挠的； 持续的', 11364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authorize', 'vt.  授权； 批准， 许可', 11365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trauma', 'n.  精神创伤； 外伤； 痛苦经历', 11366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'groom', 'v. 刷洗；梳理毛发；培养，', 11367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'audience', 'n.  听众； 观众； 读者', 11368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'possess', 'vt.  具有， 拥有', 11369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dedication', 'n.  献身， 奉献； 献词； 奉献仪式', 11370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neutral', 'adj.  中性的； 中立的', 11371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optional', 'adj.  可以任选的， 非强制的', 11372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'analysis', 'n.  分析； 分析报告； 分解', 11373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devise', 'vt.  设计； 发明； 想出； 策划， 图谋', 11374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apparent', 'adj.  显然的， 明显的； 表面上的， 貌似的', 11375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'journalism', 'n.  新闻业， 新闻工作', 11376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronical', 'adj.  慢性的， 延续很长的', 11377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exposure', 'n.  暴露， 显露； 揭露； 曝光； 面临， 遭受', 11378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evacuate', 'v.  疏散， 撤离； 排空', 11379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clutch', 'v.  企图抓住， 抓紧 n. 一次所孵的卵；离合器；掌握，控制；把握，抓紧', 11380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dawn', 'n.  破晓， 黎明； 开始， 发端', 11381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humble', 'adj. 谦卑的；卑贱的；简陋的，低劣的 vt.  降低， 贬抑', 11382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commodity', 'n.  商品； 日用品', 11383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'independent', 'adj.  独立的， 自主的； 自立的； 不相干的， 不受影响的； 无偏见的， 中立的； 私立的； 有主见的； 无党派的', 11384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glossy', 'adj.  光滑的； 光彩夺目的； 浮华的', 11385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blur', 'v. 变模糊，难以区分；玷污 n.  模糊形状； 模糊的记忆； 污点', 11386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plausible', 'adj.  似有道理的， 似乎正确的', 11387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cider', 'n.  苹果酒； 苹果汁', 11388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hearsay', 'n.  谣言， 传闻， 道听途说', 11389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mundane', 'adj.  世俗的； 平凡的', 11390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alkali', 'n.  碱', 11391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonization', 'n.  殖民地化', 11392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortuitous', 'adj.  偶然的， 意外的', 11393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equator', 'n.  赤道', 11394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sexism', 'n.  性别歧视', 11395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incapacitate', 'vt.  使无资格； 使失去能力； 使不胜任', 11396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deceitful', 'adj.  欺诈的， 惯于欺骗的， 不诚实的', 11397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'audition', 'n.  旁听； 试演', 11398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'editorial', 'adj.  社论的； 编辑的 n. 社论，重要评论', 11399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sharpen', 'v.  削尖， 磨快； 使敏锐； 变得清晰', 11400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sedimentary', 'adj.  沉积的， 沉淀性的', 11401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'committee', 'n.  委员会', 11402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kernel', 'n.  仁； 粒； 核心， 要点', 11403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stingy', 'adj.  吝啬的， 小气的', 11404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excavate', 'vt.  挖掘； 掘出', 11405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wipe', 'v&n.  擦， 揩， 抹', 11406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subtle', 'adj.  细微的， 微妙的； 精巧的， 巧妙的； 狡猾的； 敏锐的', 11407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foliage', 'n.  叶', 11408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photograph', 'v.  拍照 n. 照片', 11409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'component', 'adj.  组成的， 构成的 n. 成分，组成部分', 11410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suite', 'n.  套， 组； 套房', 11411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overwhelm', 'vt.  淹没， 漫过； 压倒， 击败， 制服； 使难以忍受； 使应接不暇', 11412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morgue', 'n.  停尸房， 太平间', 11413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unprecedented', 'adj.  空前的', 11414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pocketbook', 'n.  钱袋， 皮夹； 财政状况， 财力', 11415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charcoal', 'n.  木炭', 11416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disguise', 'vt&n.  掩饰； 伪装， 假装', 11417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imperial', 'adj.  帝国的， 帝王的； 至尊的； 专横的', 11418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wrap', 'vt. 包，裹 n.  披肩， 围巾； 包装材料', 11419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prehistoric', 'adj.  史前的； 陈旧的', 11420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facet', 'n.  小平面； 方面', 11421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'novel', 'adj. 新颖的 n.  小说', 11422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tedium', 'n.  单调， 乏味', 11423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liberal', 'adj.  自由的， 开明的； 慷慨的； 不严格的； 人文的', 11424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'standard', 'adj.  标准的 n. 标准，准则', 11425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harmony', 'n.  和声； 和谐， 融洽， 协调； 相符， 一致', 11426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genial', 'adj.  亲切的， 和蔼的； 温和的， 温暖的', 11427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epitome', 'n.  摘要， 梗概； 典型， 典范', 11428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sharply', 'adv.  急剧地； 猛烈地； 尖刻地； 鲜明地', 11429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afoul', 'adv.  相抵触， 有冲突', 11430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chill', 'adj. 寒冷的 v.  变冷， 冷却 n. 寒冷，寒意', 11431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dominate', 'v.  支配， 统治； 控制； 盛行', 11432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imitate', 'vt.  模仿， 效仿； 仿制， 仿造', 11433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compute', 'v.  计算， 估算', 11434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pastel', 'adj. 彩色蜡笔的；柔和的 n.  彩色蜡笔', 11435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homestead', 'n.  家宅， 农庄； 宅地', 11436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'middleman', 'n.  中间人， 调解人； 经纪人', 11437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exceed', 'v.  超过， 超出', 11438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'avert', 'vt.  避免， 规避； 转移', 11439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conversation', 'n.  交谈， 会话', 11440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monarchy', 'n.  君主制； 君主国', 11441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manifestation', 'n. 显示，表明；', 11442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vicious', 'adj.  危险的， 罪恶的； 残酷的， 凶残的； 恶性的', 11443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lace', 'v.  用带子束紧 n. 蕾丝；缎带；鞋带，系带', 11444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invitation', 'n.  邀请； 请柬； 吸引， 诱惑', 11445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lithosphere', 'n.  岩石圈', 11446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enormous', 'adj.  巨大的， 极大的', 11447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revival', 'n.  复兴， 再流行； 复苏； 苏醒， 复活； 重演', 11448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moisture', 'n.  潮湿， 湿气', 11449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sloth', 'n.  树懒； 懒散， 怠惰', 11450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lack', 'n&vt.  缺乏， 不足', 11451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'external', 'adj.  外部的， 外面的； 外来的； 对外的', 11452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circumstance', 'n.  环境， 条件； 境况， 经济状况', 11453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revise', 'vt.  修订， 修改； 复习', 11454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authority', 'n. 权力，管辖权；', 11455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paramount', 'adj.  至为重要的； 最高权力的， 至尊的', 11456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emerald', 'n.  祖母绿， 绿宝石； 翡翠绿', 11457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legislature', 'n.  立法机关， 立法团体', 11458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sociable', 'adj.  好交际的， 合群的； 友善的， 友好的', 11459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhilarating', 'adj.  令人高兴的， 使人兴奋的', 11460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Saturn', 'n.  土星', 11461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'avenge', 'vt.  复仇， 报仇； 向…报仇', 11462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obsolete', 'adj.  过时的； 废弃的', 11463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instrument', 'n.  仪器， 器械， 工具； 乐器', 11464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'medium', 'adj. 〔大小、水平或数量〕中等的；中号的 n. 传播媒介〔如报纸、电视等〕 n. 灵媒，巫师，通灵的人', 11465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gasoline', 'n.  汽油', 11466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interface', 'n.  界面， 分界面； 接口', 11467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sculpt', 'vt.  雕刻', 11468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lipid', 'n.  脂质， 类脂', 11469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fatal', 'adj.  致命的； 毁灭性的； 命中注定的', 11470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hormone', 'n.  激素， 荷尔蒙', 11471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'psychology', 'n.  心理学； 心理， 心理特征', 11472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outgas', 'vt.  除去气', 11473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ridge', 'n.  脊； 山脊， 山脉； 高压脊； 隆起物', 11474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypothesize', 'v.  假定， 假设', 11475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puritanical', 'adj.  极守道德的', 11476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twine', 'v.  缠绕， 盘绕， 围绕 n. 细绳', 11477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mobile', 'adj.  可移动的； 多变的 n. 动的雕塑', 11478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perform', 'v.  做， 履行， 完成； 表演， 演出； 执行', 11479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrospective', 'adj.  回顾的， 追想的； 有追溯效力的', 11480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peak', 'adj. 最高的，高峰的 n.  最高点， 顶峰', 11481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evolution', 'n.  发展； 演变， 进化， 进化论', 11482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lucrative', 'adj.  赚钱的， 获利的， 有利可图的', 11483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portrait', 'n.  肖像， 画像； 描写， 描绘', 11484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inanity', 'n.  空虚， 空洞； 无意义的事物', 11485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acidity', 'n.  酸度； 酸性', 11486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complaint', 'n.  诉苦， 抱怨； 投诉； 控告', 11487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pinnacle', 'n.  山顶， 顶峰； 鼎盛时期； 小尖塔', 11488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inject', 'vt.  注射； 注入， 灌输； 投入', 11489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cannibalism', 'n.  嗜食同类', 11490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indifference', 'n.  冷漠， 不关心', 11491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'copious', 'adj.  丰富的， 富饶的', 11492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inception', 'n.  开端， 开始', 11493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'channel', 'n.  频道； 渠道， 途径； 通道； 海峡； 水道， 航道', 11494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'focus', 'v.  集中； 聚焦 n. 焦点，焦距；中心', 11495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hamper', 'vt. 妨碍，阻挠 n.  大篮子', 11496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approach', 'v. 接近；', 11497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'usher', 'v.  引领， 引导 n. 领座员，招待员', 11498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decisive', 'adj.  决定性的； 果断的', 11499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollinate', 'vt.  给…授粉', 11500);
