INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'predict', 'v. 预言,预测,预告', 501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'waterproof', 'adj. 防水的,耐水的', 502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'productivity', 'n. 生产率', 503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'finally', 'adv. 最后,最终', 504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subtract', 'v. (from)减(去)', 505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'direct', 'a&ad. 径直地 adj. 径直的 v. 管理,指导；(at,to)指向', 506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monetary', 'adj. 金融的,货币的', 507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'approve', 'v. 批准，通过；(of)赞成，赞许，同意', 508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'economical', 'adj. 节约的,经济的', 509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bankrupt', 'adj. 破产的 v. 使破产 n. 破产者', 510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'objection', 'n. 异议,反对的理由；反对,不喜欢', 511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pale', 'adj. 苍白的,灰白的；浅的,暗淡的', 512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'format', 'n. (出版物的)开本,版式,格式 v. 设计;安排', 513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'voice', 'n. 声音;嗓音；意见,发言权;语态', 514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abdomen', 'n. 腹，下腹', 515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spicy', 'adj. 加很多香料的；(口味)浓郁的', 516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specify', 'v. 指定,详细说明', 517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'modern', 'adj. 现代的,近代的；新式的', 518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prestige', 'n. 声望,威望,威信', 519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clothe', 'v. (给…)穿衣,供给…衣服', 520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lawyer', 'n. 律师', 521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enclosure', 'n. 围地，围场', 522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motor', 'n. 发动机,电动机', 523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'addition', 'n. 增添，添加；附加部分，增加(物)；加法', 524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'project', 'n. 方案,工程,项目 v. 投射,放映；设计,规划', 525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'silver', 'n. 银;银器;银币 v. 镀银', 526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incorporate', 'v. 合并,纳入,结合 adj. 合并的', 527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evade', 'v. 逃避，回避；避开，躲避；回避', 528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sensitive', 'adj. 敏感的，容易生气的', 529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conventional', 'adj. 惯例的,常规的', 530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cut', 'v. 削减，删节；切，割，削 n. 切口，伤口', 531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intimate', 'adj. 亲密的,密切的 n. 熟友,熟人', 532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affect', 'v. 影响；(疾病)侵袭；感动', 533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chairman', 'n. 主席,议长,会长,董事长', 534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'important', 'adj. 重要的,重大的；有地位的,有权力的', 535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mob', 'n. 暴民，乱民 v. 围攻', 536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'demonstrate', 'v. 论证,证实；演示,说明', 537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basin', 'n. 盆,脸盆；盆地', 538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'price', 'n. 价格,价钱；代价 v. 给…定价钱', 539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marginal', 'adj. 记在页边的,旁注的', 540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'position', 'n. 姿势,姿态；位置；职位；处境,形势', 541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solid', 'adj. 固体的；结实的,稳固的；可靠的 n. 固体', 542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mobile', 'adj. 可动的,活动的,运动的', 543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'identification', 'n. 身份证明(文件)；识别,鉴别', 544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convenience', 'n. 便利,方便', 545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'logic', 'n. 逻辑,逻辑学', 546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immediate', 'adj. 立即的,即时的；最接近的；紧接的', 547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'autonomy', 'n. 自治，自治权；', 548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crystal', 'n. 水晶,水晶饰品；结晶 adj. 水晶的,透明的', 549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'local', 'adj. 地方的,当地的；局部的', 550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'process', 'n. 过程,进程；工序,制作法,工艺 v. 加工；处理', 551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'great', 'adj. 大量的；很好的；伟大的', 552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revolution', 'n. 革命', 553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ban', 'v. 取缔,查禁,禁止 n. 禁止,禁令', 554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'competition', 'n. 竞争；比赛，竞赛', 555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marine', 'adj. 海洋的,海生的,海产的；船舶的；海军的', 556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'significance', 'n. 重要性; 意义', 557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panic', 'n. 恐慌,惊慌 v. 使惊慌,使害怕', 558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'satisfactory', 'adj. 令人满意的,圆满的,良好的,符合要求的', 559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'factor', 'n. 因素,要素', 560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perspective', 'n. 观点,看法；透视画法,透视图因素,要素', 561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impetus', 'n. 推动(力),促进', 562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'announce', 'v. 正式宣布,发表', 563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contract', 'n. 合同/契约 v. 订合同/契约；使缩小', 564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entertainment', 'n. 文娱节目；娱乐活动；招待,款待', 565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detective', 'n. 侦探', 566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radioactive', 'adj. 放射性的,放射引起的', 567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'follow', 'v. 跟随；接着', 568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'database', 'n. 数据库', 569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vigorous', 'adj. 朝气蓬勃的,精力旺盛的', 570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metropolitan', 'adj. 大城市的，大都会的', 571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'include', 'v. 包括,包含', 572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'herself', 'pron. [反身代词]她自己；她亲自，她本人', 573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summon', 'v. 召唤；传讯,传唤；鼓起(勇气),振作(精神)', 574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'activate', 'v. 启动，激活；驱动，驱使；使开始起作用', 575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pyramid', 'n. 金字塔', 576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contain', 'v. 包含，容纳', 577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lure', 'n. 吸引力,魅力,诱惑物 v. 引诱，吸引', 578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cure', 'v. (of)治愈,医治 n. 治愈，治疗', 579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lower', 'adj. 下面的，下方的 v. 降下,放低', 580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detain', 'v. 耽搁；扣押,拘留', 581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'modify', 'v. 更改,修改', 582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'encounter', 'v. 遇到,遭遇 n. 遭遇；经历', 583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conceive', 'v. (of)设想,构思,想象；怀胎', 584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emergency', 'n. 紧急情况,突然事件,非常时刻', 585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'successor', 'n. 接替的人或事物，继任者', 586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retrospect', 'n. 回顾，回想，追溯', 587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'performance', 'n. 表演,演出；表现；履行,执行', 588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'essential', 'adj. 本质的,基本的 n. 要素', 589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disclose', 'v. 揭示,泄露', 590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nominate', 'v. 提名；任命', 591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crisis', 'n. (pl.crises)危机,紧要关头', 592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indication', 'n. 指出,指示;表明,显示', 593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heritage', 'n. 遗产,继承物;传统', 594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scale', 'n. 规模;刻度;天平,磅秤;比例尺;音阶;鱼鳞', 595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sympathetic', 'adj. 有同情心的；赞同的，支持的', 596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversion', 'n. 转变，转换；信仰的改变；', 597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'psychology', 'n. 心理,心理学,心理状态', 598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tomato', 'n. 西红柿', 599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mark', 'n. 痕迹；记号；分数 v. 标记；打分；使有特色', 600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rectangle', 'n. [数]矩形, 长方形', 601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solo', 'n. 独奏 adj. 单独的；独唱的 adv. 单独地；独唱地', 602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'permanent', 'adj. 永久的；持久的', 603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'former', 'adj. 以前的,在前的', 604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barbecue', 'n. 烧烤野餐 v. 炙烤(肉等)', 605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'receive', 'v. 收到,接到；遭受,受到；接待,接见', 606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'university', 'n. (综合)大学', 607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merge', 'v. (使)结合，(使)合并，(使)合为一体', 608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agency', 'n. 代理(处)，代办处；[美](政府的)机关，厅', 609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'greet', 'v. 致敬,问候,迎接;扑(鼻),入(耳),触(目)', 610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subsequent', 'adj. 随后的,后来的', 611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'benefit', 'n. 利益,好处,恩惠 v. 有益于;(from,by)受益', 612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embarrass', 'v. 使困窘,使局促不安；阻碍,麻烦', 613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marvelous', 'adj. (marvellous)惊人的,奇迹般的,妙极的', 614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'office', 'n. 办公室,办事处；职务,公职；部,局,处', 615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indicative', 'adj. (of)指示的,暗示的', 616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proportion', 'n. 部分；比例；均衡,相称', 617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'definite', 'adj. 明确的;一定的', 618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'van', 'n. 有篷汽车；有篷货运车厢', 619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assist', 'v. 协助，帮助，促进', 620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medical', 'adj. 医学的，医疗的，医药的', 621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subjective', 'adj. 主观(上)的，个人的', 622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocal', 'adj. 声音的;有声的;歌唱的 n. 元音;声乐作品', 623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'luxury', 'n. 奢侈,华贵；奢侈品 adj. 奢华的,豪华的', 624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'among', 'prep. 在一群(组)之中；在…之中，于…之间', 625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secret', 'adj. 秘密的,机密的 n. 秘密', 626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inspiration', 'n. 灵感；鼓舞,激励', 627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curl', 'v. (使)卷曲,蜷缩 n. 卷发;卷曲状；卷曲物', 628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deposit', 'v. 存放；使沉淀 n. 存款；沉积物', 629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crime', 'n. 罪行,犯罪', 630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abandon', 'v. 离弃，丢弃；遗弃，抛弃；放弃', 631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memory', 'n. 记忆力；记忆,回忆；存储(器)', 632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'projector', 'n. 放映机,幻灯机,投影仪', 633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trumpet', 'n. 喇叭,小号', 634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transparent', 'adj. 透明的，透光的；易理解的', 635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profitable', 'adj. 有利可图的,有益的', 636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grade', 'n. 等级,级别；分数 v. 分等,分级', 637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bicycle', 'n. (bike)自行车 v. 骑自行车', 638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disposition', 'n. 性格；排列,部署；倾向,意向', 639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disorder', 'n. 失调,疾病；混乱,杂乱；骚乱', 640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equality', 'n. 同等;平等;相等;等式;等同性', 641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'export', 'v. 出口 n. 出口；出口商品', 642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subject', 'n. 主题；学科 adj. 隶属的；易遭..的 v. 使隶属', 643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnish', 'v. 供应,提供；装备,布置', 644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possibility', 'n. 可能,可能性', 645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prayer', 'n. 祷告,祷文；祈祷', 646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'production', 'n. 生产,产品,作品,(研究)成果,总产量', 647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continual', 'adj. 不断的,连续的；频繁的', 648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parent', 'n. 父母,母亲；母体', 649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'survive', 'v. 幸免于,幸存；比…长命', 650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alongside', 'adv&prep. 在旁边', 651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'involve', 'v. 包含,含有；涉及', 652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solidarity', 'n. 团结', 653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embark', 'v. (使)上船(或飞机,汽车等)；着手,从事', 654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intimidate', 'v. 胁迫，威胁(某人做某事)', 655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carriage', 'n. (四轮)马车；(火车)客车厢', 656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remark', 'n. 评语,意见 v. 评论', 657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detach', 'v. 分开, 分离, 分遣, 派遣(军队)', 658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immerse', 'v. 使浸没；使沉浸在', 659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'partial', 'adj. 部分的,不完全的；偏袒的,不公平的,偏爱的', 660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recreation', 'n. 娱乐,消遣', 661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attract', 'v. 吸引；引起的注意(或兴趣等)', 662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formation', 'n. 形成;构成;组织;构造;编制;塑造', 663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'speciality', 'n. (specialty) 特色食品; 特产；专业；专门研究；专长', 664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motion', 'n. 运动,动；提议,动议 v. 提议,动议', 665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'privacy', 'n. (不受干扰的)独处，自由；隐私', 666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosper', 'v. 成功,兴隆,昌盛,使成功,使昌隆,繁荣', 667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'articulate', 'adj. 善于表达的 v. 清楚地讲话', 668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'car', 'n. 汽车，车辆，车；(火车)车厢', 669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gratitude', 'n. 感激,感谢', 670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resemble', 'v. 像,类似', 671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'synthetic', 'adj. 合成的,人造的', 672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pessimistic', 'adj. 悲观(主义)的', 673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insist', 'v. 坚称，坚决认为', 674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certificate', 'n. 证(明)书,执照', 675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'technology', 'n. 科技；工艺', 676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'testimony', 'n. 证词', 677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invention', 'n. 发明,创造,发明物', 678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resemblance', 'n. 相似,相似性[点,物]', 679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'admire', 'v. 钦佩，赞美，羡慕', 680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'succession', 'n. 继任,继承', 681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'counter', 'n. 柜台；计数器 adj&adv. 相反(的) v. 反对,反击', 682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hers', 'pron. [she的物主代词]她的(所有物)', 683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'primitive', 'adj. 原始的,远古的,早期的；简陋的; 旧式的', 684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'politics', 'n. 政治；政治学；政纲,政见', 685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parliament', 'n. 国会,议会', 686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'predecessor', 'n. 前辈，前任', 687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'college', 'n. 高等专科学校；大学；学院', 688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summary', 'n. 摘要,概要 adj. 概括的,简略的', 689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interact', 'v. 互相作用,互相影响', 690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'import', 'v. 进口,输入 n. 进口,输入', 691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adverse', 'adj. 逆的，相反的；敌对的；不利的；有害的', 692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'technique', 'n. 技巧，手艺，工艺；技能，技术', 693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circle', 'n. 圆,圆周；集团；周期,循环 v. 环绕,旋转', 694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medium', 'n. 媒体；方法；媒介,介质 adj. 中等的', 695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'official', 'n. 官员,行政官员 adj. 官方的,官方的,正式的', 696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divert', 'v. 使转向，使改道；转移(注意力)；使娱乐', 697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agitate', 'v. 煽动，鼓动；宣传', 698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maneuver', 'n. (manoeuvre)移动;运用,操作; v. 移动', 699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'allowance', 'n. 补贴，津贴；允许量；零用钱', 700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nickname', 'n. 绰号，浑名 v. 给…起绰号', 701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adverb', 'n. 副词 adj. 副词的', 702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spiritual', 'adj. 精神(上)的,心灵的', 703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'artery', 'n. 动脉；干线，要道', 704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merit', 'n. 优点，成绩 v. 值得', 705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bacterium', 'n. 细菌', 706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'current', 'n. 水流；气流；电流；潮流,趋势 adj. 当前的;现行的', 707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bottom', 'n. 底(部),基础,根基；海底,湖底,河床', 708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verify', 'v. 证实,查证；证明', 709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'security', 'n. 安全(感)；防御(物),保证(人)；(pl.)证券', 710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'induce', 'v. 引诱,劝使；引起,导致', 711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosperous', 'adj. 繁荣的,兴旺的,茂盛的,顺利的', 712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cohesive', 'adj. 团结的，有凝聚力的', 713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merchandise', 'n. 商品,货物', 714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resign', 'v. 辞去,辞职；使听从(于),使顺从', 715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'battery', 'n. 电池(组)；(器具等的)一组，一套；炮兵连', 716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motivate', 'v. 作为…的动机；促动，激励，鼓励', 717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alleviate', 'v. 减轻，缓和，缓解(痛苦等)', 718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'senate', 'n. 参议院,上院', 719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portray', 'v. 描写，描绘', 720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commercial', 'adj. 商业的；商务的；可获利的 n. 广告节目', 721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generator', 'n. 发电机,发生器', 722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cape', 'n. 披肩，短披风；海角，岬', 723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intervene', 'v. (in)干涉,干预;插入,介入', 724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mercy', 'n. 仁慈,怜悯,宽恕', 725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prevent', 'v. (from)预防,防止,阻止,制止,妨碍', 726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capable', 'adj. 有本领的,有能力的;(of)可以…的,能…的', 727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tractor', 'n. 拖拉机,牵引车', 728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'visual', 'adj. 视觉的，视力的', 729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simulate', 'v. 模仿,模拟；假装,冒充', 730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'valuable', 'adj. 贵重的,有价值的 n. (pl.)贵重物品,财宝', 731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'productive', 'adj. 能产的,多产的；生产(性)的', 732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detect', 'v. 察觉,发觉,侦察,探测', 733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fracture', 'n. 裂缝(痕);骨折 v. (使)断裂,(使)折断', 734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sensation', 'n. 感觉,知觉；激动,轰动,轰动一时的事情', 735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'improve', 'v. 改善，改进；变得更好', 736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recall', 'v. 回忆,回想；撤消,收回', 737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affection', 'n. 喜爱，钟爱；慈爱', 738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formulate', 'v. 规划；制定；准备；仔细思考并明确表达', 739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversely', 'adv. 相反地', 740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graceful', 'adj. 优美的,文雅的,大方的', 741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monkey', 'n. 猴子', 742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'positive', 'adj. 肯定的,积极的', 743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'access', 'n. 进入；接入；到达；享用权；入口 v. 存取', 744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'panel', 'n. 专门小组；面板，控制板，仪表盘', 745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'erect', 'v. 建立；树立,使竖立 adj. 直立的,垂直的', 746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oppose', 'v. 反对,使对立,使对抗,使相对', 747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'void', 'adj. 无效的；毫无…的，缺乏…的', 748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consumption', 'n. 消费(量),消耗', 749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ambassador', 'n. 大使；特使，(派驻国际组织的)代表', 750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'versatile', 'adj. 多才多艺的；有多种用途的，多功能的，万用的', 751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vital', 'adj. 生死攸关的,重大的；生命的,生机的', 752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evoke', 'v. 唤起(回忆、感情等)；引起', 753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dominate', 'v. 支配,统治,控制', 754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'desolate', 'adj. 荒凉的;孤独的 v. 使荒芜', 755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accept', 'v. 接受；认可，同意', 756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secondary', 'adj. 次要的,二级的；(教育) 中等的', 757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'physiological', 'adj. 生理学的, 生理学上的', 758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pronunciation', 'n. 发音,发音方法', 759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commerce', 'n. 买卖，贸易；商务；商业', 760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commodity', 'n. 商品', 761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'video', 'n. 录影，录像 adj. 电视的,视频的;录像的', 762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'selection', 'n. 选择,挑选；挑选出来的东西', 763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'procession', 'n. 队伍,行列', 764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bath', 'n. 沐浴,洗澡；浴缸，澡盆 v. (给…)洗澡', 765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furious', 'adj. 狂怒的,狂暴的,猛烈的', 766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conspiracy', 'n. 阴谋，密谋，共谋', 767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intellectual', 'n. 知识分子 adj. 智力的，理智的，有理解力的', 768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calcium', 'n. 钙(化学符号Ca)', 769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sentiment', 'n. 意见，观点，感想；多愁善感；感情因素', 770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'provision', 'n. 提供，供给；预备', 771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anticipate', 'v. 预料；期望；预先考虑；抢先；提前使用', 772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'progressive', 'adj. 进步的,先进的;前进的', 773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'documentary', 'adj. 文献的 n. 记录片', 774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inclusive', 'adj. 包括的,包含的；范围广的', 775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'isle', 'n. 小岛(用于诗歌中)', 776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disposal', 'n. 丢弃，处理', 777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grand', 'adj. 宏伟的，壮丽的，隆重的', 778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bar', 'n. 条,杆,闩;酒吧;栅,障碍(物) v. 阻挡，阻拦', 779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prospective', 'adj. 预期的', 780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'romance', 'n. 爱情；恋爱', 781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supervise', 'v. 管理,监督', 782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medicine', 'n. 内服药,医药；医术;医学', 783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verse', 'n. 〔歌曲、诗歌、《圣经》等的〕一节；韵文,诗;诗节,诗句', 784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'effect', 'n. 效应；影响；结果 v. 引起；使发生', 785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aggressive', 'adj. 侵略的，好斗的；有进取心的', 786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'art', 'n. 美术，艺术；技术，技艺；文科，人文科学', 787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'month', 'n. 月,月份', 788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diverse', 'adj. 多种多样的,不同的', 789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curtain', 'n. 窗帘,门帘；幕(布) v. 用帘子隔开', 790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recover', 'v. 重新获得；(from)恢复,痊愈', 791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possibly', 'adv. 可能，也许，或许', 792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'middle', 'n. 中间,当中 adj. 中间的,当中的', 793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illustration', 'n. 插图，图解；说明；例证', 794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equip', 'v. (with)装备,配备；训练', 795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'market', 'n. 集市,市场；销路,需求(量) v. 销售', 796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sister', 'n. 姐，妹；护士长；修女，女教士', 797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generous', 'adj. 慷慨的；宽宏大量的', 798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'democracy', 'n. 民主,民主制；民主国家', 799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sometime', 'adv. 将来(或过去)某个时候 adj. 以前的', 800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consist', 'v. (in)在于；(of)由…组成,由…构成', 801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'temporary', 'adj. 暂时的,临时的', 802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incidentally', 'adv. 附带地,顺便提及', 803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'architect', 'n. 建筑师；设计师；缔造者；创造者', 804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'movement', 'n. 运动；活动；移动,迁移', 805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'municipal', 'adj. 市政府的，市的，市办的', 806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Catholic', 'adj. 天主教的 n. 天主教徒', 807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generate', 'v. 产生,发生', 808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simplicity', 'n. 简单,简易;朴素;直率,单纯', 809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absent', 'adj. 缺席的；缺乏的，不在场的；心不在焉的', 810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'except', 'prep. 除…之外 v. 除外', 811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'privilege', 'n. 特权,优惠,特许 v. 给予优惠,给予特权', 812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vacant', 'adj. 空的,未占用的;空缺的;神情茫然的；空缺的；神情茫然的', 813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'account', 'n. 叙述，说明；账目，账户 v. 说明，解释', 814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clothes', 'n. 衣服(虽为复数，亦不可数)', 815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evidence', 'n. 证据，证明；证据，证词', 816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'community', 'n. 社区；团体', 817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cloth', 'n. 织物,衣料；(一块)布', 818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eventually', 'adv. 终于,最后', 819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appal', 'v. 使惊骇，使恐怖', 820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'classify', 'v. 分类；分等(级)', 821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'division', 'n. 分,分割；除法；部门', 822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mankind', 'n. 人类', 823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solitary', 'adj. 单一的，唯一的；单独的，无伴的；喜欢独处的，不喜与人接触的', 824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'method', 'n. 方法,办法', 825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anniversary', 'n. 周年，周年纪念日', 826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occur', 'v. 发生；出现', 827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'support', 'v. 支撑；支持；赡养；维持 n. 支持；拥护；赞同', 828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expense', 'n. 花费,消费,消耗', 829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'approximate', 'adj. 近似的 v. (to)接近', 830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beneficial', 'adj. (to)有利的,有益的', 831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disgrace', 'n. 丢脸，耻辱 v. 使失宠;玷辱,使蒙羞', 832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocation', 'n. 职业;召唤;天命;天职;才能', 833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'certainly', 'adv. 一定,必定,无疑；当然,行', 834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'general', 'adj. 总的,大体的；一般的,普通的 n. 将军', 835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basket', 'n. 筐，篮，篓', 836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accustomed', 'adj. 习惯的，适应的(一般作表语)；惯常的', 837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'composite', 'adj. 混合成的，综合成的 n. 合成物，复合材料', 838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oblige', 'v. 强迫,迫使', 839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diameter', 'n. 直径', 840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acceptance', 'n. 正式接受；接纳；接受，赞同，赞成，认可', 841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'artificial', 'adj. 人工的，人造的；人为的；虚伪的，做作的', 842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cattle', 'n. 牛〔指菜牛或奶牛〕', 843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'protect', 'v. (from)保护,保卫', 844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'banner', 'n. 旗(帜)', 845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divide', 'v. 分；隔开；(by)除', 846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pet', 'n. 宠物 adj. 钟爱的 (理论、项目、学科等)', 847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'systematic', 'adj. (al)系统的,有组织的', 848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capture', 'v. 俘虏；夺得,攻占；捕获 n. 捕获,俘虏；夺得,攻占', 849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loyal', 'adj. (to)忠诚的,忠贞的', 850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tiny', 'adj. 极小的,微小的', 851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'system', 'n. 系统，体系；制度；一套办法', 852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dispose', 'v. (for)布置,安排；(of)处理,处置', 853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commonplace', 'adj. 常见的，屡见不鲜的 n. 寻常的事物；平庸的东西', 854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'manner', 'n. 方式;举止;(pl.)风度,礼貌;规矩;风俗', 855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fierce', 'adj. 凶猛的,残忍的；狂热的,强烈的', 856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invitation', 'n. 邀请,招待；请柬', 857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'policeman', 'n. 警察', 858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'product', 'n. 产品；产物', 859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reject', 'v. 拒绝,抵制,丢弃,排斥,退掉 n. 落选者', 860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legal', 'adj. 法律的,法定的;合法的,正当的', 861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cap', 'n. 便帽,军帽；盖,罩,套 v. 覆盖于…顶端', 862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monitor', 'n. 监视器；显示器；班长 v. 监控,监测', 863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'form', 'n. 形状；形状；表格 v. 组成,构成；形成', 864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absolute', 'adj. 完全的；绝对的；确实的，肯定的', 865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'country', 'n. 国家；农村,乡下', 866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'movie', 'n. 电影；电影院', 867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cripple', 'n. 跛子,残疾人 v. 使跛,使残疾', 868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'procedure', 'n. 程序,手续,步骤', 869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terminate', 'v. (使)结束，(使)停止', 870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curve', 'n. 曲线,弯曲(物) v. 弄弯,成曲形', 871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'religion', 'n. 宗教,信仰', 872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invalid', 'n. 病人,伤残人 adj. 无效的', 873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'effective', 'adj. 有效的；有生效的', 874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'predominant', 'adj. (over)占优势的;主要的,突出的', 875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'geometry', 'n. 几何(学)', 876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'syndrome', 'n. 综合病征', 877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'temperature', 'n. 温度；体温', 878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appraisal', 'n. 对...作出的评价；评价，鉴定，评估', 879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invent', 'v. 发明,创造；捏造,虚构', 880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monopoly', 'n. 垄断；独占；专营', 881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occurrence', 'n. 事件,事故,发生的事情；发生,出现', 882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attain', 'v. 完成；获得；达到', 883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legacy', 'n. 遗产，遗赠；先人(或过去)留下的东西', 884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'semiconductor', 'n. 半导体', 885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prize', 'n. 奖赏,奖金,奖品 v. 珍视,珍惜', 886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inherit', 'v. 继承(金钱等)；经遗传而得(性格、特征)', 887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'term', 'n. 学期;期限,期间;(pl.)条件,条款;术语', 888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humanity', 'n. 人类；人性,人情；(pl.)人文科学', 889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tactic', 'n. (s)策略,战术', 890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kilometre', 'n. (kilometer) 公里，千米(略作km)', 891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'special', 'adj. 特殊的，特别的', 892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resolution', 'n. 决定,决议；坚决,决心', 893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'man', 'n. (pl.men)人；；人类；男人', 894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circular', 'adj. 圆(形)的,环形的；循环的；环行的 n. 传单,通报', 895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'baseball', 'n. 棒球', 896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limitation', 'n. 限制，制约', 897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simplify', 'v. 简化,使单纯', 898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'collect', 'v. 收集,搜集；领取,接走；收(税等)；聚集,堆积', 899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bank', 'n. 银行；岸,堤；', 900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highlight', 'v. 使显著,使突出;强调 n. 最精彩的部分', 901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formidable', 'adj. 强大的;令人敬畏的;可怕的;艰难的', 902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verbal', 'adj. 口头的；用言辞的,用文字的；动词的', 903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'menu', 'n. 菜单', 904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accessory', 'n. 附件,附属品；装饰物，小配件', 905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legend', 'n. 传说,传奇', 906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assumption', 'n. 假定，设想；采取；承担', 907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pronounce', 'v. 发…的音；宣布,宣判', 908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continue', 'v. 继续,连续；延伸', 909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perceive', 'v. 理解,领悟；察觉,感知', 910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proposition', 'n. 主张，观点，见解；提议，建议', 911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'susceptible', 'adj. 易得病的；易受影响的；〔人〕易受影响的', 912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obsolete', 'adj. 已废弃的,过时的', 913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invisible', 'adj. 看不见的；无形的', 914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'daylight', 'n. 日光；白昼,黎明', 915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'create', 'v. 创造,引起；创作', 916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cathedral', 'n. 大教堂', 917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'centigrade', 'adj. 摄氏温度计的;摄氏的 n. 摄氏温度计;摄氏', 918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'levy', 'n. 税款，税额 v. 征收,征集,征用', 919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'catalog', 'n. （ue）目录(册) v. 编目(录)', 920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'married', 'adj. 已婚的,夫妇的;(to)与…结婚的', 921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'political', 'adj. 政治的', 922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'band', 'n. 条,带;乐队;波段;一群,一伙', 923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ascertain', 'v. 确定，查明，弄清', 924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accuracy', 'n. 正确，准确；准确性；精确度', 925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inform', 'v. (of,about)通知,告诉,报告', 926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opposite', 'adj. 对面的,相对的；相反的 n. 相反的人[事物]，对立物', 927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preceding', 'adj. 在前的,在先的', 928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hero', 'n. 英雄，勇士；男主角，男主人公', 929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'postman', 'n. 邮递员', 930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proficiency', 'n. (in)熟练,精通', 931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exception', 'n. 例外,除外', 932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avert', 'v. 防止，避免；转移(目光、注意力等)', 933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exclusive', 'adj. 独占的;排他的;孤高的;唯一的;高级的', 934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspicion', 'n. 怀疑，猜疑；一点儿，少量', 935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surprise', 'v. 使诧异,使惊异,使感到意外 n. 诧异,惊异', 936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revise', 'v. 修正,修改；修订,校订', 937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uniform', 'n. 制服,军服 adj. 相同的,一律的', 938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'communication', 'n. 通讯,沟通;(pl.)通讯系统', 939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paradigm', 'n. 典范; 范例; 示例', 940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symphony', 'n. 交响乐,交响曲', 941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subscribe', 'v. (to)订阅，订购', 942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incident', 'n. 事件,事变', 943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decisive', 'adj. 决定性的', 944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convict', 'v. (经审讯)证明…有罪,宣判…有罪 n. 囚犯', 945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commemorate', 'v. 纪念，庆祝', 946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'characteristic', 'adj. 特有的,独特的 n. 特征,特性', 947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motel', 'n. (附有停车场的)汽车旅馆', 948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reduce', 'v. 缩小；减少；降低', 949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analogy', 'n. 类似，相似，类比，类推', 950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carve', 'v. (雕)刻', 951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moderate', 'adj. 有节制的；中等的,适度的；温和的,稳健的', 952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assign', 'v. 派给，分配；选定，指定(时间、地点等)', 953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conclude', 'v. 结束,终止；断定,下结论', 954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quarrel', 'v. 争吵,争论 n. 争吵，吵架，争执', 955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spectator', 'n. 观众,旁观者', 956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'finish', 'n. 光洁（度） v. 完成；结束；（被）吃光，（被）喝光', 957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attractive', 'adj. 吸引人的，引人注意的；漂亮的，迷人的', 958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soluble', 'adj. 可溶的', 959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petty', 'adj. 小(器、规模)的,不重要的,细微的', 960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agenda', 'n. 议事日程，记事册', 961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vague', 'adj. 不明确的,含糊的,暧昧的', 962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'universal', 'adj. 全体的,宇宙的,世界的；普遍的，通用的', 963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'primary', 'adj. 首要的,主要的,基本的；初级的；最初的', 964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'educate', 'v. 教育,培养,训练', 965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secure', 'adj. (from,against)安全的 v. 得到；使安全，保护', 966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verb', 'n. 动词', 967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advertise', 'v. 为...做广告；公告，公布', 968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vanity', 'n. 虚荣心,浮华', 969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calendar', 'n. 日历,月历', 970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solemn', 'adj. 严肃的，庄重的；庄严的,隆重的', 971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conviction', 'n. 深信,确信；定罪，判罪', 972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'envisage', 'v. 想象，设想，展望，', 973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'career', 'n. (个人的)事业，职业；生涯', 974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ordinary', 'adj. 普通的,平凡的,平常的；平庸的', 975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invert', 'v. 倒置,倒转,颠倒', 976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inventory', 'n. 详细目录,清单；存货', 977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gracious', 'adj. 亲切的,客气的;宽厚的,仁慈的', 978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'survival', 'n. 继续生存；幸存', 979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circumference', 'n. 圆周,周围', 980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calculate', 'v. 计算,推算；预测，估计', 981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'order', 'n. 命令;次序;整齐;定货单;等级 v. 定制,订购', 982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outside', 'adv&adj&prep. 在外面(的),在…外(的) n. 外部', 983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'allocate', 'v. 分配，分派；拨给', 984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aspire', 'v. (to，after)渴望，追求，有志于', 985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merely', 'adv. 仅仅，只不过', 986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trademark', 'n. 商标；特征', 987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exposure', 'n. 暴露；揭露；朝向', 988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'law', 'n. 法律,法规,法学,规律,定律', 989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metropolis', 'n. 大都市；首府；重要中心', 990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'representative', 'n. 代表,代理人 adj. (of)典型的,有代表性的', 991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inherent', 'adj. 固有的,内在的,天生的', 992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dialect', 'n. 方言', 993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ideology', 'n. 意识形态，(政治或社会的)思想意识', 994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'denounce', 'v. 公开指责,公然抨击;谴责', 995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specific', 'adj. 明确的；具体的,特定的,特有的', 996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'essence', 'n. 本质,实质', 997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heroine', 'n. 女英雄；女主角', 998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'customer', 'n. 顾客,主顾', 999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'here', 'adv. 在(到，向)这里；这时；在这一点上', 1000);
