INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tear', 'v.   扯破， 撕开 n.  眼泪', 4001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'excuse', 'n.  借口， 理由 vt.  原谅， 宽恕', 4002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attack', 'v&n.  攻击， 袭击', 4003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spoonful', 'n.  一匙', 4004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'humour', 'n.  幽默， 幽默感', 4005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'divorce', 'n. 离婚 vt.  使离婚', 4006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'currency', 'n.  货币', 4007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'distribute', 'v.  分布； 分配', 4008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worried', 'adj.  担心的； 烦恼的', 4009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attach', 'vt.  系上， 贴上', 4010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'canal', 'n.  运河； 水道', 4011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shout', 'v.  呼喊， 呼叫 n. [C]喊，高声呼喊', 4012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'escape', 'v&n.  逃跑， 逃脱； 避开', 4013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flashlight', 'n.  手电筒； 闪光信号', 4014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ankle', 'n.  脚踝', 4015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'situation', 'n.  形势， 情况', 4016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'think', 'v.   想， 思索； 认为', 4017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'receive', 'v.  收到， 得到', 4018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thirst', 'n.  渴， 口渴', 4019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'participate', 'vi.  参加， 参与', 4020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'surplus', 'n.  剩余， 过剩', 4021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'refresh', 'v.   精神振作； 更新', 4022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'librarian', 'n.  图书管理员， 图书馆馆长', 4023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'theft', 'n.  盗窃案', 4024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'religion', 'n.  宗教', 4025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diagram', 'n.  图表， 图样', 4026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'claw', 'n.  爪', 4027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prayer', 'n.  祈祷', 4028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'speech', 'n.  演讲', 4029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'watch', 'v.  观察， 观看 n. 手表', 4030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clap', 'v.   拍手， 鼓掌', 4031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'quit', 'v.   离开； 停止', 4032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'polish', 'v.  擦亮， 磨光； 润色', 4033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chart', 'n.  图表； 航海图', 4034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'insurance', 'n.  保险', 4035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'medical', 'adj.  医学的， 医疗的', 4036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'principle', 'n.  原则； 原理', 4037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'till', 'conj&prep.  直到， 直到…为止', 4038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attend', 'v.  出席， 参加； 专心， 考虑； 看护， 照料', 4039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'goods', 'n.  商品， 货物', 4040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lie', 'vi. 躺，卧，平放；位于 n. 谎言 vt.   说谎', 4041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'secure', 'adj.  安全的， 可靠的； 放心的， 无虑的', 4042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'smell', 'n. 气味 v. 闻出，闻到，嗅到', 4043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'used to', 'v.  过去常常', 4044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unable', 'adj.  不能的， 不能胜任的', 4045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'glare', 'v. 瞪眼，怒目而视；闪耀 n.  强光', 4046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disappointed', 'adj.  失望的', 4047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'irrigation', 'n.  灌溉', 4048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'late', 'adv.  晚， 迟 adj. 晚的，迟的', 4049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'continue', 'v.  延伸； 继续', 4050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shoot', 'vt. 射击，射中；摄影 n.  嫩枝， 苗， 芽', 4051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'realize', 'vt.  认识到； 实现', 4052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'budget', 'n.  预算', 4053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'actual', 'adj.  实际的， 现实的', 4054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tension', 'n.  紧张， 不安； 拉紧， 绷紧； 压力， 张力', 4055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chest', 'n.  箱子； 胸部', 4056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eastern', 'adj.  东方的， 东部的', 4057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'marathon', 'n.  马拉松', 4058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'last', 'determiner. 最近的，最近一段时间的，最近一次的 adv. 最近，上次 v. (使)持续 n. 鞋楦', 4059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adapt', 'v.  适应； 改编', 4060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wash', 'v. 洗涤，冲刷 n.  洗； 洗的衣服', 4061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'weight', 'n.  重量', 4062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'doubt', 'n&v.  怀疑， 疑惑', 4063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cheerful', 'adj.  兴高采烈的， 快活的', 4064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'uncomfortable', 'adj.  不舒服的， 不安的', 4065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'develop', 'v.   发展；  发育； 开发； 冲洗', 4066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'misunderstand', 'vt.   误会， 不理解', 4067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'warn', 'vt.  警告； 预告', 4068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'measure', 'v. 测量；权衡 n.  方法， 措施', 4069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'guilty', 'adj.  有罪的， 犯法的； 内疚的', 4070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'crossroads', 'n.  十字路口', 4071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'district', 'n.  区， 地区', 4072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'receipt', 'n.  收据； 收到， 接收', 4073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'assume', 'vt.  假定， 设想； 承担', 4074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'swim', 'vi.  游泳； 游', 4075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'full', 'adv.  完整地， 十分地 adj. 满的，充满的，完全的', 4076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'basement', 'n.  地下室', 4077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pepper', 'n.  胡椒粉', 4078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chant', 'v. 唱；歌颂 n.  圣歌， 赞美诗', 4079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'capsule', 'n.  胶囊； 太空舱', 4080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'away', 'adv.  离开， 远离', 4081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'memory', 'n.  回忆， 记忆', 4082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'concept', 'n.  概念， 观念', 4083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'motivation', 'n.  动机', 4084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'impossible', 'adj.  不可能的， 办不到的', 4085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'effort', 'n.  努力， 艰难的尝试', 4086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wave', 'v. 挥手；摇动 n.  波， 波浪', 4087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disaster', 'n.  灾难， 祸患', 4088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anything', 'pron.  某事  ； 任何事', 4089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'agriculture', 'n.  农业， 农学', 4090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grocer', 'n.  零售商人； 食品店', 4091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ecology', 'n.  生态学', 4092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stare', 'v.  盯着看， 凝视', 4093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'painful', 'adj.  痛苦的； 疼痛的', 4094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'steady', 'adj.  稳固的； 平稳的', 4095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'vote', 'v.  选举， 投票', 4096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'early', 'adv.  早， 在早期 adj. 早的，早期的', 4097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harvest', 'n&v.  收割； 收获', 4098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pain', 'n. 疼痛；', 4099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disease', 'n.  病， 疾病', 4100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'start', 'n&v.  开始， 着手； 出发', 4101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'purchase', 'n&vt.  购买', 4102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'yet', 'adv.  到目前为止； 还； 仍然', 4103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'engineer', 'n.  工程师； 技师', 4104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pair', 'n.  一双， 一对', 4105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'manage', 'vi.  应付过去 vt. 管理；达成', 4106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'equal', 'adj. 平等的，相等的 vt.  等于， 比得上', 4107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alike', 'adv.  类似于， 以同样的方式 adj. 相同的，相似的', 4108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gravity', 'n.  地心引力， 重力', 4109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'typical', 'adj.  典型的； 象征性的', 4110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bravery', 'n.  勇敢， 勇气', 4111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'finance', 'n.  财政， 金融', 4112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'parking', 'n.  停车', 4113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shadow', 'n.  [C] 影子， 阴影', 4114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hydrogen', 'n.  氢', 4115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'put', 'vt.   放， 摆', 4116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'climb', 'v.  爬， 攀登', 4117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'offence', 'n.  犯罪； 过错； 冒犯； 攻击', 4118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'carbon', 'n.  碳', 4119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circus', 'n.  马戏团', 4120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'controversial', 'adj.  争论的， 争议的', 4121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dinosaur', 'n.  恐龙', 4122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'enter', 'v.  进入', 4123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attain', 'vt.  获得； 达到', 4124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'trap', 'vt. 使陷入困境 n.  陷阱， 圈套', 4125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lonely', 'adj.  孤独的， 寂寞的', 4126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tram', 'n.  有轨电车', 4127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pale', 'adj.  苍白的， 灰白的', 4128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'struggle', 'n&v.  努力， 斗争， 挣扎', 4129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gallery', 'n.  画廊， 美术品陈列室', 4130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pest', 'n.  害虫', 4131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'warmth', 'n.  温暖， 暖和； 热烈， 热情， 热心', 4132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lesson', 'n.  课； 功课； 教训', 4133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'destroy', 'v.  破坏， 毁坏', 4134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'supreme', 'adj.  极度的； 极大的， 最高的', 4135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ambulance', 'n.  救护车', 4136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'junior', 'adj.  初级的； 年少的', 4137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coast', 'n.  海岸， 海滨', 4138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shuttle', 'n.   车辆、 飞机等', 4139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'provide', 'v.  提供', 4140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'allocate', 'vt.  分配； 配给； 拨出', 4141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'light', 'vi. 点，变亮 adj.  明亮的； 轻的； 浅色的 n. 光，灯，灯光', 4142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'valuable', 'adj.  值钱的， 贵重的', 4143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'primary', 'adj.  初级的； 首要的', 4144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stubborn', 'adj.  顽固的， 固执的； 难应付的', 4145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'enterprise', 'n.  企业， 事业', 4146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'paperwork', 'n.  文书工作', 4147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'solar', 'adj.  太阳的', 4148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consume', 'vt.  消耗； 消费', 4149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'triangle', 'adj.  三角形的 n. 三角形', 4150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'competence', 'n.  能力', 4151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'helmet', 'n.  头盔', 4152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'theme', 'n.  主题', 4153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consult', 'v.  请教， 商议； 查询', 4154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'merely', 'adv.  仅仅， 只不过', 4155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wealth', 'n.  财富', 4156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'editor', 'n.  编辑', 4157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'means', 'n.  方法， 手段', 4158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chain', 'n.  链， 链条', 4159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'desire', 'n&v.  渴望， 期望', 4160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'survive', 'vi. 幸存，生还 vt.  比…活得长', 4161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'initial', 'adj.  开始的， 最初的', 4162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'muddy', 'adj.  泥泞的，多泥的', 4163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consistent', 'adj.  一致的， 连贯的', 4164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sword', 'n.  剑， 刀', 4165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fingernail', 'n.  手指甲', 4166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'permanent', 'adj.  永久的， 持久的', 4167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chat', 'vi.  聊天， 闲谈 n. 聊天，闲谈', 4168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fetch', 'v.  去取来， 去请来', 4169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fellow', 'n.  同伴， 伙伴', 4170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'choice', 'n.  选择， 抉择', 4171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'travel', 'n&vi.  旅行', 4172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'civilization', 'n.  文明， 文化', 4173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'before', 'adv. 以前 conj.  在…之前 prep. 在…以前，在…前面', 4174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fiction', 'n.  小说； 虚构， 杜撰', 4175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'friendly', 'adj.  友好的', 4176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'possession', 'n.  所有， 拥有； 财产， 所有物', 4177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tell', 'v.   告诉， 吩咐； 辨别， 知道', 4178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'replace', 'vt.  取代， 代替； 把…放回原处', 4179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appointment', 'n.  约会', 4180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stomach', 'n.  [C] 胃， 胃部', 4181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'experience', 'vt. 经历，体验 n.  经验； 经历', 4182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'listen', 'vi.  听， 仔细听， 留神听', 4183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hit', 'n&v.   打， 撞； 击中', 4184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'major', 'adj. 主要的；成年的 n.  主修专业', 4185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interrupt', 'v.  打扰， 打断', 4186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'beat', 'v. 打赢；跳动；敲打 n.   节拍', 4187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worldwide', 'adj.  遍及全球的， 世界各地的', 4188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bear', 'v. 承担；忍受 n.  熊', 4189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'affair', 'n.  事， 事情', 4190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consider', 'vt.  考虑； 认为', 4191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'housework', 'n.  家务劳动', 4192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'potential', 'adj. 潜在的，可能的 n.  潜力', 4193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accustomed', 'adj.  通常的， 习惯的', 4194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'group', 'n.  组， 群', 4195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jewelry', 'n.  〈总称〉 珠宝， 首饰', 4196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'obtain', 'vt.  获得， 得到', 4197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lounge', 'n.  休息厅， 休息室', 4198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rugby', 'n.  英式橄榄球', 4199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'resist', 'vt.  抵抗； 挡开', 4200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'format', 'n.  版式， 格式', 4201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sacrifice', 'n&v.  牺牲， 奉献', 4202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'particular', 'adj. 特殊的；个别的', 4203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'illegal', 'adj.  违法的， 不合规定的', 4204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pause', 'n&vi.  暂停， 停止', 4205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'congratulate', 'vt.  祝贺， 恭贺', 4206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'careless', 'adj.  粗心的； 漫不经心的', 4207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'square', 'adj.  平方的； 方形的 n. 广场；正方形', 4208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rainbow', 'n.  彩虹； 幻想', 4209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'twice', 'adv.  两次； 两倍', 4210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ample', 'adj.  充足的， 丰富的', 4211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'altitude', 'n.  高度； 高处', 4212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'request', 'n&vt.  要求， 请求', 4213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'classify', 'vt.  分类', 4214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'part', 'v.  分离， 分别 n. 部分；角色', 4215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'percent', 'n.  百分之…', 4216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'point', 'v. 指，指向 n.  点； 要点， 观点； 分数', 4217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'paddle', 'v.  划桨； 戏水 n. 桨状物；蹼', 4218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'general', 'adj.  大体的， 总的； 一般的； 普遍的', 4219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tend', 'vi.  趋向， 往往是 vt. 照管，护理', 4220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'frighten', 'vt.  使惊恐， 吓唬', 4221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relief', 'n.  缓解； 轻松', 4222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'boycott', 'n&vt.  联合抵制', 4223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dimension', 'n.  尺寸， 尺度', 4224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'park', 'n. 公园；停车场 vt.  停放', 4225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unbelievable', 'adj.  难以置信的', 4226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'process', 'vt. 加工，处理 n.  程序； 方法', 4227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deserve', 'vt.  应受， 值得', 4228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'subscribe', 'v.  捐赠； 订阅', 4229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clear', 'adj.  清晰的； 明亮的； 清楚的', 4230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chef', 'n.  厨师', 4231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alternative', 'adj.  选择性的， 二者择一的', 4232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'zoom', 'v.  突然扩大， 使猛增', 4233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'colleague', 'n.  同事', 4234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diamond', 'n.  钻石， 金刚石； 菱形', 4235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'someone', 'pron.  某人； 重要人物', 4236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'build', 'v. 建造 n.  构造', 4237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mean', 'v.   意味着， 意思是', 4238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'approve', 'vi.  赞成； 满意 vt. 批准，通过', 4239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'neither', 'determiner. 两者都不（的），两者中无一（的） adv. 也不', 4240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'earn', 'vt.  挣得， 赚得', 4241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'glad', 'adj.  高兴的， 乐意的', 4242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chew', 'v.  咀嚼', 4243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pedestrian', 'n.  步行者， 行人', 4244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hurry', 'v. 赶快；急忙 n.  匆忙， 仓促', 4245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'account', 'v.  总计有； 认为 n. 账目；描述', 4246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tolerate', 'vt.  忍受， 容忍', 4247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'radioactive', 'adj.  放射性的', 4248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'underline', 'vt.  在…下面划线； 强调', 4249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'innocent', 'adj.  清白的， 无罪的； 纯真的', 4250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chopsticks', 'n.  筷子', 4251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alphabet', 'n.  字母表', 4252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ambiguous', 'adj.  暧昧的； 不明确的', 4253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'advance', 'v&n.  推进， 前进', 4254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'trip', 'n.  [C] 旅行， 旅程', 4255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'botanical', 'adj.  植物学的， 植物的', 4256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appreciate', 'vt.  欣赏； 感激', 4257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'record', 'v.  录制， 记录 n.  记录； 唱片', 4258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diverse', 'adj.  不同的， 多种多样的', 4259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cube', 'n.  立方体， 立方', 4260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'strict', 'adj.  严格的， 严密的', 4261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jump', 'v.  跳跃； 惊起； 猛扑 n. [C]跳跃', 4262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'knowledge', 'n.  知识， 学问', 4263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'happen', 'v.   发生， 碰巧', 4264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pass', 'v.  传递； 经过', 4265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'past', 'adj. 过去的，最近的 prep.  经过； 晚于 n. 过去，往事', 4266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'festival', 'n.  节日', 4267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shock', 'vt. 使震惊 n.  震动， 冲击', 4268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'delighted', 'adj.  高兴的， 快乐的', 4269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pancake', 'n.  薄煎饼', 4270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'active', 'adj.  积极的， 主动的', 4271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bill', 'n.  钞票； 账单； 法案， 议案', 4272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'whichever', 'pron.  不论哪个', 4273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'court', 'n.  法庭， 法院； 球场', 4274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'whose', 'pron&conj.  谁的', 4275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bucket', 'n.  桶； 铲斗', 4276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'senior', 'adj. 年长的，资深的；高年级的 n.  上级， 长辈； 高年级学生', 4277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flexible', 'adj.  柔软的， 灵活的', 4278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relative', 'adj.  相对的； 比较的 n. 亲属，亲戚', 4279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attitude', 'n.  态度； 看法', 4280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'organ', 'n.  器官', 4281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'average', 'adj. 平均的；普通的 n.  平均数', 4282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'compare', 'vt.  比较， 对照', 4283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sceptical', 'adj.  怀疑的， 怀疑论的', 4284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unwilling', 'adj.  不愿意， 勉强的', 4285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thriller', 'n.  使人激动的人； 惊险、 恐怖、 刺激的小说、 戏剧或电影', 4286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'transparent', 'adj.  显然的； 透明的', 4287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'characteristic', 'adj.  特有的， 独特的， 典型的', 4288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'how', 'adv.  怎样， 如何； 多少； 多么', 4289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grasp', 'vt.  抓住， 紧握； 领会', 4290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Buddhism', 'n.  佛教', 4291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'receptionist', 'n.  接待员', 4292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'composition', 'n.  作文； 作曲', 4293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unlike', 'prep.  不像， 和…不同', 4294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hearing', 'n.  听力', 4295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'term', 'n.  学期； 术语； 条款； 项', 4296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'volcano', 'n.  火山', 4297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wedding', 'n.  婚礼， 结婚', 4298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'acquisition', 'n.  获得； 获得物', 4299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rigid', 'adj.  刚硬的， 刚性的； 严格的', 4300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deadline', 'n.  最后期限， 截止日期', 4301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spare', 'adj. 空闲的；多余的，剩余的 vt.  提供； 匀出， 分出', 4302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mine', 'pron.  我的 v. 开采，挖掘 n. 矿藏', 4303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mind', 'v.  介意 n. 思想', 4304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grateful', 'adj.  感激的， 感谢的', 4305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'business', 'n.  商业， 生意； 职业， 事业', 4306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bungalow', 'n.  平房', 4307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'staff', 'n.  全体职员', 4308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'possible', 'adj.  可能的', 4309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'partly', 'adv.  部分地， 在一定程度上', 4310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'breathless', 'adj.  喘不过气来的', 4311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'meet', 'v. 遇见，会面；满足 n.  集会', 4312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'answer', 'v.  回答， 应答； 接电话 n. 答案', 4313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'borrow', 'v.  借用； 借', 4314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'maximum', 'n&adj.  最大量 ， 最大限度', 4315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'under', 'adv. 在下 prep.  在…下面， 向…下面', 4316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'desert', 'v.  舍弃， 遗弃 n.  沙漠', 4317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'represent', 'vt.  代表； 表现', 4318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'compete', 'vi.  比赛， 竞赛', 4319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'die', 'v.   死亡； 消失； 熄灭', 4320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'radium', 'n.  镭', 4321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fragrant', 'adj.  香的， 芬芳的', 4322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dig', 'v.   挖  ， 掘', 4323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accountant', 'n.  会计， 会计师', 4324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stocking', 'n.  长筒袜', 4325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sometimes', 'adv.  有时', 4326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'emergency', 'n.  紧急情况或状态', 4327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'promise', 'v. 答应，允诺；预示 n.  答应， 允诺； 希望， 前景', 4328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dip', 'v.   浸， 蘸', 4329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hold', 'v.   拿， 握住； 举行', 4330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'habit', 'n.  习惯， 习性', 4331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'passport', 'n.  护照', 4332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'absurd', 'adj.  不合理的； 荒谬的', 4333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'burglar', 'n.  盗贼， 窃贼', 4334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'considerate', 'adj.  体贴的， 考虑周到的； 替人着想的', 4335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rubber', 'n.  橡皮； 橡胶； 合成橡胶', 4336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'legal', 'adj.  法律的， 法定的', 4337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'underwear', 'n.  内衣', 4338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'talk', 'v. 谈话，议论 n.  谈话， 会谈； 演讲', 4339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reply', 'n&vi.   回答， 答复', 4340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'train', 'v. 培训，训练 n.  火车', 4341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'parcel', 'n.  包裹', 4342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'test', 'n&vt.  测试， 考查， 试验', 4343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'journey', 'n.  旅行， 路程', 4344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'count', 'v.  数； 计算； 有价值', 4345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'graph', 'n.  图表， 曲线图', 4346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'upwards', 'adv.  向上， 往上', 4347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'feast', 'n.  盛宴； 节日； 令人愉悦的事情', 4348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'contradictory', 'adj.  相互矛盾的；不一致的', 4349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'take', 'v.   拿走； 接受， 接纳', 4350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accompany', 'vt.  陪伴， 伴随； 伴奏', 4351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'petrol', 'n.  汽油', 4352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'beneficial', 'adj.  有益的， 受益的', 4353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blame', 'n&vt.  责备， 责怪', 4354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'final', 'adj. 最后的 n.  决赛； 期末考试', 4355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'some', 'pron.  若干， 一些 adj. 一些，若干；有些；某一', 4356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'squeeze', 'v.  压榨， 挤 n. 紧握，捏', 4357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blank', 'adj. 空的；茫然的 n.  空格， 空白， 空白处', 4358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rather', 'adv.  相当， 宁可', 4359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'importance', 'n.  重要性', 4360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'session', 'n.  会议； 开庭', 4361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'back', 'adv. 回；向后 adj. 后面的 n.  背后， 后部； 背', 4362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worthy', 'adj.  值得的； 相称的', 4363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'endless', 'adj.  无止境的； 没完没了的', 4364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'training', 'n.  培训', 4365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'expectation', 'n.  预料； 期望', 4366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mist', 'n.  雾', 4367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'miss', 'v.  错过； 想念', 4368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pound', 'n.  磅； 英镑', 4369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'load', 'n.  担子， 货物', 4370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bite', 'v. 咬，叮 n.  咬； 一口', 4371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ferry', 'n.  渡船', 4372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disgusting', 'adj.  令人讨厌的', 4373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ignore', 'vt.  不理睬； 忽视', 4374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'loaf', 'n.  一条', 4375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reception', 'n.  接待', 4376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'applaud', 'v.  鼓掌， 喝彩', 4377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'just', 'adv. 刚才，恰好；只是，仅 adj.  公正的', 4378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'outward', 'adv. 向外，在外 adj.  向外的， 外出的', 4379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'notice', 'v.  注意到 n. 通告，注意', 4380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'yummy', 'adj.  美味的', 4381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'holy', 'adj.  神圣的', 4382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relax', 'v.   放松， 轻松', 4383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relay', 'n. 接力；', 4384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'custom', 'n.  习惯， 习俗', 4385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'length', 'n.  长， 长度', 4386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'permission', 'n.  允许， 许可， 同意', 4387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grand', 'adj.  宏伟的， 盛大的', 4388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'schedule', 'n. 时刻表 vt.  安排， 排定', 4389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eastwards', 'adv.  向东', 4390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'print', 'v.  印刷', 4391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rewind', 'v.  重绕； 回转', 4392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'although', 'conj.  虽然， 尽管', 4393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'material', 'n.  材料， 原料； 物质', 4394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'approximately', 'adv.  近似地， 大约', 4395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'encouragement', 'n.  鼓励， 支持， 促进； 起激励作用的事物', 4396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'universe', 'n.  宇宙', 4397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'biochemistry', 'n.  生物化学', 4398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'iron', 'v.  熨烫 n. 铁；熨斗', 4399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'idiom', 'n.  习语， 成语', 4400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blanket', 'n.  毛毯， 毯子', 4401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hug', 'v. 紧抱，拥抱 n.  拥抱', 4402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'explain', 'vt.  解释， 说明', 4403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'envy', 'n&v.  嫉妒， 羡慕', 4404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'discount', 'n.  折扣', 4405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'construct', 'vt.  构筑； 建造', 4406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hope', 'n&v.  希望', 4407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attempt', 'vt&n.  试图， 尝试', 4408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'soon', 'adv.  不久， 很快， 一会儿', 4409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'division', 'n.  除， 除法； 分开， 分割； 分界线', 4410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tablet', 'n.  药片', 4411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hook', 'n. 钩子 vt.  钩住， 用钩子挂', 4412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'balance', 'v.  使平衡； 权衡 n. 平衡', 4413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bend', 'v.   弯曲； 弯腰， 屈身', 4414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'action', 'n.  行动', 4415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lock', 'n. 锁 vt.  锁， 锁上', 4416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stadium', 'n.   体育场', 4417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fear', 'n&v.  害怕， 恐惧， 担忧', 4418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appreciation', 'n.  欣赏； 评论； 感激', 4419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'electrical', 'adj.  与电有关的， 电气的', 4420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'statue', 'n.  雕像', 4421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sense', 'n.  感觉， 意识', 4422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cream', 'n.  奶油； 乳脂', 4423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sensitive', 'adj.  敏感的； 灵敏的； 易被惹恼的', 4424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'being', 'n.  生物， 人； 存在', 4425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'vacant', 'adj.  空的， 空白的', 4426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'afford', 'vt.  买得起； 有时间做； 承担得起； 提供', 4427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'birthplace', 'n.  出生地， 故乡', 4428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dustbin', 'n.  垃圾箱', 4429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'impression', 'n.  印象， 感觉', 4430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interval', 'n.  间歇， 间隔； 幕间休息', 4431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'evaluate', 'vt.  评价； 估计', 4432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'status', 'n.  身份， 地位', 4433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'upset', 'adj. 心烦的，苦恼的 vt.   使苦恼', 4434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dot', 'n.  点， 圆点', 4435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deliver', 'vt.  投递  ； 交付， 给', 4436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tailor', 'v.  定做 n. 裁缝', 4437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stamp', 'n.  [C] 邮票', 4438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'skip', 'vi.   跳过； 跳读', 4439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'phenomenon', 'n.   现象', 4440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mention', 'vt. 提到，说起 n.  提及', 4441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mad', 'adj.  发疯的； 生气的', 4442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'barbecue', 'n.  烤肉野餐', 4443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'file', 'n.  文件， 档案', 4444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'laundry', 'n.  洗衣店； 要洗的衣服', 4445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'member', 'n.  成员， 会员', 4446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'brewery', 'n.  啤酒厂， 酿酒厂', 4447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accumulate', 'vt.  堆积， 积累', 4448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'crime', 'n.   罪， 罪行', 4449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stand', 'vi. 站立 vt. 承担，忍受 n.  站； 台', 4450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'surround', 'vt.  围绕， 包围', 4451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'together', 'adv.  一起， 共同', 4452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pavement', 'n.  人行道', 4453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cigarette', 'n.  香烟', 4454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'may', 'modal verb. 可能，也许 n. 山楂花', 4455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'could', 'modal verb. 能，会，可以〔can 的过去式〕', 4456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'forward', 'adv.  向前， 前进 adj. 早的；前进的', 4457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bent', 'n. 爱好，嗜好 adj. 弯曲的；决心的', 4458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'strike', 'vt. 罢工；侵袭；敲；', 4459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'health', 'n.  健康， 卫生', 4460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'positive', 'adj.  积极的； 肯定的', 4461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'favourite', 'adj. 特别喜爱的 n.  特别喜爱的人', 4462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bless', 'vt.  保佑， 降福', 4463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'menu', 'n.  菜单', 4464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Pacific', 'adj.  太平洋的', 4465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'able', 'adj.  有能力的； 有才干的， 有本事的', 4466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mend', 'v.  修理， 修补', 4467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'return', 'v. 归还，返回 n.  返回， 来回', 4468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mail', 'n. 邮政，邮递 vt.  〈美〉 邮寄', 4469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'conscience', 'n.  道德心， 良心', 4470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'subject', 'n.  题目， 主题； 学科； 主语； 主体', 4471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'use', 'n.  利用； 应用', 4472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bonus', 'n.  奖金， 红利', 4473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'feel', 'vi. 摸索，寻找 v.  觉得； 摸起来 vt. 感觉；触摸；认为', 4474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'main', 'adj.  主要的', 4475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thrill', 'n. 激动，兴奋；刺激 vt.  使激动； 使胆战心惊', 4476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'serve', 'vt.  服务， 招待； 服役', 4477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cassette', 'n.  [C]卡式盒； 暗盒', 4478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'smile', 'n&v.  微笑', 4479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fine', 'adj. 好的；晴朗的；健康的 vt.  处…以罚金', 4480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'find', 'vt.   找到， 发现； 感到', 4481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'host', 'n. 主人；节目主持人 vt.  招待； 主持', 4482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accelerate', 'vt.  加速， 促进', 4483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grain', 'n.  谷物， 谷类', 4484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'international', 'adj.  国际的', 4485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'maid', 'n.  女仆； 少女', 4486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'credit', 'n.  信用； 信赖； 贷方', 4487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'oxygen', 'n.  氧； 氧气', 4488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'regardless', 'adv.  不管， 不顾； 不加理会', 4489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'terrible', 'adj.  可怕的； 糟糕的', 4490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'combine', 'v.  联合， 结合', 4491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'upward', 'adv.  向上， 往上', 4492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'waste', 'vt. 浪费 n.  废弃物； 粪便', 4493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'citizen', 'n.  公民， 市民', 4494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'occur', 'vi.  发生， 出现', 4495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'comedy', 'n.  喜剧', 4496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pleasant', 'adj.  令人愉快的， 舒适的', 4497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'difficult', 'adj.  难的； 艰难的； 不易相处的', 4498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pressure', 'n.  压； 压力； 压强', 4499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sort', 'v. 分类，拣选 n.  种类， 类别', 4500);
