INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'due', 'adj.  到期的； 预期的； 应得的； 恰当的， 适当的； 应支付的', 10001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ripen', 'v.  成熟', 10002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conform', 'vi.  遵守， 服从； 符合； 适应', 10003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bake', 'v.  烘， 烤， 焙', 10004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authentic', 'adj.  真正的， 真实的； 逼真的； 可靠的', 10005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opal', 'n.  蛋白石', 10006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lodge', 'v.  正式提出； 租住， 借宿； 为…提供住宿； 寄存 n. 巢穴；旅社；乡间小屋', 10007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'threat', 'n.  恐吓， 威胁； 坏兆头， 危险迹象', 10008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rayon', 'n.  人造丝， 人造纤维', 10009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devoid', 'adj.  全无的', 10010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mercy', 'n.  宽恕； 仁慈； 恩惠， 幸运', 10011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curl', 'v. 卷曲，蜷缩 n.  卷发； 卷曲状； 卷曲物', 10012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inform', 'vt.  通知， 通告； 了解， 熟悉； 告发， 检举， 告密', 10013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depend', 'v.  依靠， 依赖； 取决于', 10014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dearth', 'n.  缺乏， 短缺', 10015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commit', 'vt.  承诺； 犯错； 犯罪； 忠于', 10016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patch', 'vt. 修补，打补丁 n.  小片， 小块； 补丁； 小块土地', 10017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'presidency', 'n.  职位； 任期', 10018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scurry', 'vi&n.  急跑， 疾行', 10019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scornful', 'adj.  轻蔑的， 鄙视的', 10020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cholesterol', 'n.  胆固醇', 10021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnetic', 'adj.  磁的， 磁石的； 有磁性的； 有吸引力的', 10022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stick', 'v. 刺，戳，插；粘住，粘贴；放置；卡住 n.  棍， 棒； 手杖', 10023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orbit', 'v.  作轨道运行 n. 轨道；势力范围', 10024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'band', 'vi. 联合，集合 n.  乐队； 群， 伙； 带； 波段， 频带', 10025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beneficent', 'adj.  有益的； 行善的， 慈善的', 10026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprise', 'vt.  包含； 由…组成', 10027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moderate', 'adj.  适度的； 温和的； 普通的 v. 缓和，使适中 n.  持温和意见的人', 10028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resident', 'adj. 常驻的；居住的 n.  居民； 住宿者， 旅客； 住院实习医生', 10029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upheaval', 'n.  剧变， 动乱， 大变动', 10030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receiver', 'n.  接收器； 听筒； 接收者； 官方接管人', 10031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gilding', 'n.  镀金； 贴金层， 镀金层； 金色涂层', 10032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'execute', 'vt.  执行， 履行， 实施； 将…处死， 处决； 完成', 10033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substantial', 'adj.  实质的； 坚固的； 可观的， 大量的', 10034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balm', 'n.  香脂油， 药膏； 镇痛剂， 安慰剂', 10035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Paleolithic', 'adj. 旧石器时代的 n.  旧石器时代', 10036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'benefit', 'v.  受益； 得益于 n. 益处，好处；恩惠；津贴', 10037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quality', 'adj.  优良的， 优质的 n. 质，质量；品德，品质；性质，特性', 10038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unique', 'adj.  唯一的； 独特的， 罕见的； 特有的', 10039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boost', 'vt. 提高，推进；替…做广告，宣扬 n.  增加， 帮助', 10040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sober', 'adj. 清醒的，未醉的；持重的，冷静的；素净的 v.  清醒； 变得冷静', 10041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'male', 'adj. 雄的，公的；', 10042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maternal', 'adj.  母亲的， 母系的', 10043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prolific', 'adj.  多产的； 富有创造力的', 10044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expel', 'vt.  开除； 驱逐； 排出', 10045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shelter', 'n. 掩蔽处，庇护所；居所，住所；掩蔽，保护 vt.  保护， 掩蔽； 躲避', 10046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'externality', 'n.  外部性， 外界效应', 10047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'latitude', 'n. 纬度；', 10048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vigor', 'n.  活力， 精力', 10049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scan', 'vt. 细察，审视；扫描；粗略地看，浏览 n.  扫描检查； 浏览', 10050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industry', 'n.  勤劳， 勤奋； 工业， 行业', 10051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eliminate', 'vt.  消除； 淘汰', 10052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'augment', 'vt.  增加， 提高', 10053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tangent', 'adj.  切线的， 相切的 n. 切线；正切', 10054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'benign', 'adj.  良性的； 有利的； 善良的， 和蔼的', 10055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destruction', 'n.  毁坏， 毁灭', 10056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquit', 'vt.  宣告无罪； 表现', 10057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stiff', 'adv.  极其， 非常； 僵硬地 adj. 硬的，僵直的；呆板的；拘谨的；艰难的，费劲的；强烈的', 10058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prosper', 'vi.  繁荣， 兴旺； 成功', 10059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blizzard', 'n.  暴风雪， 大风雪', 10060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appeal', 'vi. 上诉，起诉；呼吁，恳求；吸引 n.  上诉， 申诉； 呼吁， 恳求； 感染力， 吸引力', 10061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swamp', 'n. 沼泽地，湿地 vt.  使陷入， 淹没； 使应接不暇， 使疲于应对', 10062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entrepreneur', 'n.  企业家； 承包人', 10063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transportation', 'n.  运输； 运输系统， 运输工具', 10064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dedicate', 'vt.  致力于， 奉献给； 题献词于上', 10065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dye', 'v.  染色 n. 颜料，染料', 10066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extensive', 'adj.  广大的， 广阔的； 广泛的， 大量的', 10067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monotonous', 'adj.  单调的， 无聊的', 10068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negate', 'vt.  取消； 否定', 10069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impart', 'vt.  传授； 传达； 给予', 10070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inspire', 'vt.  鼓舞， 激励； 给…以灵感', 10071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bureaucracy', 'n.  官僚主义， 官僚作风； 政府机构， 官僚机构', 10072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geometry', 'n.  几何， 几何学', 10073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devote', 'vt.  为…付出； 献身于', 10074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delectable', 'adj.  美味可口的； 有吸引力的； 令人喜爱的， 赏心悦目的', 10075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barb', 'n.  鱼钩， 倒钩； 挖苦的话', 10076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alumnus', 'n. 校友，毕业生', 10077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'far-fetched', 'adj.  牵强的', 10078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approximate', 'adj.  大约的， 近似的 vt.  接近， 近似', 10079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'craftsman', 'n.  能工巧匠， 手艺人， 工艺师', 10080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'project', 'v.  放映； 规划； 预测， 推想 n.  方案； 课题， 项目； 工程', 10081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aberrant', 'adj.  越轨的； 异常的', 10082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lope', 'vi. 轻松地大步跑 n.  轻快的步伐', 10083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lateral', 'adj.  侧面的， 旁边的； 横向的', 10084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hinterland', 'n.  内地， 腹地； 内地贸易区', 10085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nominate', 'vt.  任命， 指定； 提名， 推荐', 10086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tread', 'v. 踏，践踏；行走 n.  轮胎面； 脚步声； 步法', 10087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diameter', 'n.  直径', 10088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stationary', 'adj.  静止的； 固定的， 稳定的， 不变的', 10089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barn', 'n.  谷仓； 牲口棚', 10090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bark', 'v.  吠叫； 厉声质问 n. 树皮；犬吠声', 10091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kennel', 'n.  狗窝； 养狗场', 10092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ellipse', 'n.  椭圆， 椭圆形', 10093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bare', 'adj. 赤裸的；光秃的，无遮盖的；最基本的 vt.  脱掉； 显露', 10094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sidewalk', 'n.  人行道', 10095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formidable', 'adj.  难对付的； 强大的； 令人敬畏的', 10096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abound', 'vi.  富于； 大量存在； 充满', 10097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suitcase', 'n.  手提箱， 衣箱', 10098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invert', 'vt.  使倒转， 使倒置， 使颠倒', 10099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discrete', 'adj.  分离的， 个别的； 离散的', 10100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temperate', 'adj.  气候温和的， 温带的； 温和的， 自我克制的', 10101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immutable', 'adj.  不可改变的， 永恒不变的', 10102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disrupt', 'vt.  使中断； 扰乱； 使分裂， 使瓦解', 10103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scar', 'vt. 给…留下疤痕；给…留下精神创伤；损害…的外观 n.  疤痕； 创伤', 10104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abort', 'v.  夭折， 中止； 使流产', 10105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypothetical', 'adj.  假设的', 10106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coefficient', 'n.  系数', 10107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'converse', 'vi. 交谈，会话 adj. 逆向的，相反的 n.  相反的事物； 反面', 10108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gospel', 'n.  准则， 信条； 绝对真理； [G-]福音； 福音音乐； 训示', 10109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eccentric', 'adj.  古怪的， 反常的 n. 古怪的人', 10110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appliance', 'n.  用具， 器具； 装置', 10111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alloy', 'n.  合金 vt.  使成合金', 10112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defer', 'v.  推迟， 延期', 10113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drowsy', 'adj.  昏昏欲睡的； 催眠的', 10114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lore', 'n.  学问， 学识； 传说， 传统', 10115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mast', 'n.  船桅； 旗杆； 天线塔', 10116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mass', 'adj.  大量的 n. 质量；块，团；众多；群众，平民百姓', 10117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'muggy', 'adj.  闷热的', 10118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revoke', 'vt.  撤销， 撤回； 取消， 废除', 10119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proper', 'adj.  正确的； 合乎体统的， 适当的； 固有的， 特有的', 10120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renaissance', 'n.  [the R-] 文艺复兴， 文艺复兴时期； 复兴， 再生', 10121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poisonous', 'adj.  有毒的， 有害的； 恶毒的', 10122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auction', 'n&v.  拍卖', 10123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allot', 'vt.  分配， 配给， 拨给', 10124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'propel', 'vt.  推进， 驱使； 激励', 10125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admit', 'v.  承认； 准许…进入， 接纳', 10126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rampant', 'adj.  猖獗的， 肆虐的； 蔓生的', 10127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interest', 'n. 兴趣，关注；业余爱好；利息；利害关系 vt.  使感兴趣， 引起…关注', 10128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uneven', 'adj.  不平均的； 不平坦的； 不规则的； 不势均力敌的； 不公平的', 10129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twig', 'n.  嫩枝， 小枝', 10130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immature', 'adj.  未成熟的， 未充分发展的', 10131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organic', 'adj.  有机的； 器官的； 有机体的', 10132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chaste', 'adj.  贞洁的； 简朴的， 朴实的', 10133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mask', 'n. 面具；面罩；假面具，', 10134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evacuation', 'n.  撤离', 10135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patron', 'n.  资助人， 赞助人； 老主顾， 顾客', 10136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apply', 'v.  申请， 请求； 适用； 应用， 运用； 涂， 敷， 施', 10137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stew', 'v.  炖， 煨； 思考； 不安， 担忧 n. 炖菜；不安，担忧', 10138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overlook', 'vt.  俯瞰， 眺望； 忽略； 对…不予考虑', 10139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incredible', 'adj.  惊人的， 难以置信的', 10140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'layout', 'n.  编排， 版面设计； 规划， 布局', 10141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landing', 'n.  登陆； 着陆， 降落', 10142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formula', 'n.  公式， 方程式； 分子式； 配方', 10143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'avalanche', 'n&v.  雪崩； 山崩', 10144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revolt', 'v. 反叛，反抗；违抗；厌恶，反感 n.  起义， 叛乱， 反抗', 10145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disgust', 'vt.  厌恶， 嫌恶', 10146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tribute', 'n.  贡品； 颂词， 称赞； 悼念， 致哀； 礼物', 10147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endanger', 'vt.  危及， 危害', 10148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'base', 'adj.  卑鄙的， 不道德的 vt. 把设在；', 10149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stem', 'vt. 阻止，遏制；起源 n.  茎， 干', 10150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subordinate', 'adj. 次要的；下级的 vt.  使处于次要地位， 使从属于 n.  部属， 下属', 10151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trend', 'n.  趋势， 倾向', 10152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mechanic', 'n.  技工， 机修工', 10153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revolution', 'n.  革命； 巨变； 旋转', 10154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliable', 'adj.  可靠的， 可信赖的', 10155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incentive', 'n.  刺激； 动机', 10156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relate', 'v.  叙述， 讲述； 有关联', 10157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preliminary', 'adj. 预备的，初步的 n.  初步做法， 起始行为', 10158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obstacle', 'n.  障碍， 妨害物', 10159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leftover', 'adj.  剩余的', 10160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaborative', 'adj.  合作的， 协作的', 10161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constitute', 'v.  组成； 设立； 制定', 10162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indict', 'vt.  控诉， 起诉， 控告', 10163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'courier', 'n.  送急件的人， 信使； 旅游服务员', 10164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convince', 'vt.  使确信， 说服', 10165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mate', 'v.  交配 n. 配偶；朋友，伙伴；同事；大副', 10166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stampede', 'v. 狂奔，涌向；使仓促行事 n.  逃窜， 狂奔； 热潮， 风尚', 10167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gorge', 'v. 狼吞虎咽 n.  山峡， 峡谷', 10168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terminate', 'v.  停止， 结束', 10169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mannerism', 'n.  怪癖， 癖性； 过分的独特风格', 10170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theory', 'n.  理论， 原理； 学说； 见解， 看法', 10171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confederacy', 'n.  联盟， 同盟， 联邦； 私党', 10172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flock', 'vi. 聚结，成群 n.  群； 一群； 大量', 10173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extension', 'n.  延长； 延伸； 电话分机， 分机号码', 10174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'internal', 'adj.  内在的， 内部的； 国内的， 内政的； 内心的', 10175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gender', 'n.  性别； 性', 10176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literary', 'adj.  文学的； 文人的， 书卷气的', 10177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'architect', 'n.  建筑师； 设计师， 缔造者', 10178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excise', 'vt.  切除； 删去', 10179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'punch', 'vt. 拳打；打孔；按，压 n.  重拳击打； 冲床， 打孔机', 10180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'across', 'adv. 横过；到对面，向对面 prep.  穿过， 越过； 在对面', 10181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flexibility', 'n.  灵活性； 弹性， 韧性； 适应性', 10182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mortgage', 'n. 抵押贷款，按揭；抵押证书 vt.  用…作抵押', 10183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identity', 'n.  身份； 特征， 特性； 同一性', 10184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'federal', 'adj.  联邦的； 联邦制的； 联邦政府的', 10185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verify', 'v.  检验， 核实', 10186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excursion', 'n.  远足， 短途旅游', 10187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inaugurate', 'vt.  为…举行就职典礼； 为…举行开幕式； 开始， 开创', 10188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cramp', 'n. 痉挛，抽筋； vt.  阻碍， 阻止', 10189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'academy', 'n.  学会， 研究院； 专科院校', 10190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solitude', 'n.  孤独， 单独； 独处， 独居； 隐居处', 10191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reward', 'n. 报答，奖赏，报酬 vt.  奖赏， 奖励， 给以报酬', 10192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hockey', 'n.  曲棍球', 10193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graze', 'v. 吃草；放牧；擦伤 n.  擦伤', 10194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swallow', 'v. 吞，咽；吞没，侵吞；轻信，轻易接受；默默忍受；使不流露，抑制 n.  燕子； 吞， 咽', 10195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perquisite', 'n.  津贴， 利益； 特权', 10196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hominid', 'adj.  灵长目的 n. 原始人类；人科动物', 10197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nucleus', 'n. (原子)核', 10198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sting', 'v. 刺，蜇；感觉刺痛 n.  尾刺； 刺痛', 10199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'juice', 'vt. 榨出汁液 n.  汁， 液', 10200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haste', 'v.  赶快， 匆忙 n. 急忙，急速，匆忙', 10201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nurture', 'vt. 养育，养护，培养；扶植，支持；滋长，助长 n.  养育， 培养', 10202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buckle', 'v.  扣紧； 变形， 弯曲 n. 皮带扣环', 10203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'degenerate', 'vi.  退化， 衰退 adj.  堕落的； 退化的', 10204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destructive', 'adj.  破坏性的， 毁灭性的', 10205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monastery', 'n.  男修道院， 寺院', 10206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devout', 'adj.  虔敬的； 诚恳的', 10207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'censor', 'n. 审查员 vt.  审查， 检查', 10208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devour', 'vt.  狼吞虎咽地吃， 吞食； 吞没， 吞噬； 如饥似渴地读', 10209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stir', 'v. 搅拌；煽动；激发，打动；行动，活动 n.  搅拌， 搅动； 激动， 震动', 10210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insult', 'vt.  侮辱， 凌辱 n.  侮辱， 凌辱', 10211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'existence', 'n.  存在， 实在； 生存， 生活', 10212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'craft', 'v.  手工制作 n. 手艺，工艺', 10213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'axis', 'n.  轴； 轴线， 中心线', 10214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maze', 'n. 迷宫；复杂难懂的细节；困惑，迷惘 vt.  使混乱； 使困惑， 迷惑', 10215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'float', 'v.  漂浮， 浮动； 飘动', 10216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gaseous', 'adj.  气体的， 气态的', 10217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negligent', 'adj.  忽略的； 疏忽的； 粗心大意的', 10218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expressive', 'adj.  有表现力的， 富有表情的； 表示…的， 表现…的', 10219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conductivity', 'n.  传导性； 传导率', 10220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'desolate', 'adj.  荒凉的， 无人烟的； 不幸的， 忧伤的 vt.  使感到悲惨， 使感到凄凉； 使荒芜', 10221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coarse', 'adj.  粗糙的； 粗俗的', 10222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evade', 'v.  逃避， 回避； 躲开， 避开', 10223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'associative', 'adj.  联想的； 结合的； 关联的', 10224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exaggerate', 'v.  夸张， 夸大', 10225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cortex', 'n.  皮层， 皮质', 10226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imply', 'vt.  意味着， 暗示； 说明， 表明； 使有必要', 10227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offset', 'n. 分支；补偿；抵消 vt.  补偿； 抵消', 10228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'backhand', 'n.  反手击球', 10229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cascade', 'vi. 倾泻，流注 n.  小瀑布； 倾泻', 10230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cavity', 'n.  腔； 洞， 穴， 窟窿； 龋洞', 10231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sequence', 'n. 一系列，一连串；顺序，次序，序列 vt.  按顺序排列', 10232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'provision', 'n.  供应， 供应品； 条款； 准备， 预备', 10233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recruit', 'v. 招募，征募 n.  新兵； 新成员', 10234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thrust', 'v. 挤；插；戳，刺 n.  戳， 刺； 要旨； 驱动力', 10235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abolition', 'n.  废除， 废止； 废奴运动', 10236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sporadic', 'adj.  偶发的， 间或出现的， 零星的', 10237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turnout', 'n.  出席人数； 产量， 产额', 10238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'configuration', 'n.  布局， 格局； 结构， 构造， 形状； 配置', 10239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scientific', 'adj.  科学的； 细致严谨的', 10240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spherical', 'adj.  球形的， 球状的', 10241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chunk', 'n.  厚片， 大块； 相当大的部分； 矮胖的人', 10242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asteroid', 'n.  小行星', 10243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commonplace', 'adj.  普通的， 平凡的 n. 平凡的事；老生常谈', 10244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'libel', 'vt. 诽谤 n.  诽谤； 诽谤性文字', 10245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parameter', 'n.  参量， 参数； 界限， 范围', 10246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extinct', 'adj.  灭绝的， 不存在的； 不再活跃的', 10247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forerunner', 'n.  先驱者， 开路人； 先兆， 预兆', 10248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cubism', 'n.  立体派； 立体主义', 10249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agonize', 'vi.  苦苦思索； 焦虑不已', 10250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'percolate', 'v. 过滤；渗入，渗透；逐渐流传，传开 n.  滤液', 10251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opaque', 'adj.  不透明的， 不透光的； 难懂的， 晦涩的', 10252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advantage', 'n. 优点；优势，有利条件 vt.  有益于', 10253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assistant', 'adj. 辅助的，助理的；副的 n.  助手， 助教', 10254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humid', 'adj.  湿的， 潮湿的； 湿润的', 10255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instead', 'adv.  代替， 顶替； 反而， 却', 10256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'controversy', 'n.  争论， 辩论', 10257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'command', 'n&v.  命令； 指挥， 统率', 10258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compulsory', 'adj.  必须做的， 义务的； 强制性的； 必修的', 10259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abortive', 'adj.  落空的， 失败的', 10260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swarm', 'vi. 云集 v.  密集， 云集； 成群地飞行 n. 群，一大群', 10261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anticipate', 'v.  预见， 预期； 先于…行动', 10262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variable', 'adj. 易变的；', 10263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temple', 'n.  寺庙， 教堂； 太阳穴', 10264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slash', 'v. 砍；大幅削减 n.  砍痕， 伤痕； 斜线号', 10265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fabricate', 'vt.  编造； 制造', 10266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uproot', 'v.  根除； 离开家园', 10267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tally', 'v.  吻合 n. 记录；账', 10268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landscape', 'n. 风景，景色；地貌，地形；风景画 vt.  美化…的环境', 10269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exception', 'n.  除外， 例外', 10270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevailing', 'adj.  普遍的； 流行的； 一地常刮的， 盛行的', 10271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temporary', 'adj.  暂时的， 临时的', 10272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'habitat', 'n.  自然环境， 栖息地', 10273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optimal', 'adj.  最佳的， 最理想的', 10274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'desperate', 'adj.  绝望的； 不顾死活的， 拼命的； 极度渴望的', 10275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awful', 'adj.  不舒服的； 糟糕的； 可怕的； 非常的', 10276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urge', 'v. 促进，力劝；驱赶，驱策 n.  强烈的欲望， 冲动', 10277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handy', 'adj.  可用的； 易使用的， 便利的； 手巧的', 10278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anguish', 'v.  极度痛苦 n. 极度痛苦', 10279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refraction', 'n.  折射', 10280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'visual', 'adj.  视觉的', 10281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sanctuary', 'n.  禁猎区， 动物保护区； 庇护所， 避难所； 圣所， 圣殿', 10282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aerobics', 'n.  有氧运动', 10283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inviting', 'adj.  动人的， 诱人的； 引人注目的', 10284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instruct', 'vt.  指示； 教授', 10285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agreeable', 'adj.  使人愉快的； 欣然同意的', 10286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'merchant', 'n.  商人', 10287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'community', 'n.  社会； 社团； 群落； 共同体', 10288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ailment', 'n.  小病', 10289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'version', 'n.  译文， 译本； 版本', 10290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charismatic', 'adj.  蒙受神恩的； 有超凡魅力的', 10291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overload', 'vt.  使超载， 使过载； 使超负荷； 给…增加负担 n.  超载； 超负荷', 10292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bronze', 'adj.  青铜色的 n. 青铜；青铜色；青铜制品；铜牌', 10293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staunch', 'adj.  坚定的， 忠诚的', 10294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'selection', 'n.  选择， 挑选； 精选； 被挑选出来的人， 精选品； 可供选择的事物', 10295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adolescence', 'n.  青春', 10296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notch', 'n. 等级，档次；', 10297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subculture', 'n.  亚文化行为观念， 次文化', 10298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhale', 'v.  呼出； 散发', 10299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appropriate', 'adj.  适当的 vt.  拨款； 占用， 挪用', 10300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'least', 'adv.  最小； 最少； 微不足道 adj. 最小的；最少的；最不重要的', 10301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utility', 'n.  功用， 效用； 公用事业', 10302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abrasion', 'n.  表面磨损', 10303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symphony', 'n.  交响乐， 交响曲； 和谐， 协调', 10304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eloquent', 'adj.  雄辩的 ； 动人的', 10305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'observatory', 'n.  天文台， 天文观测站', 10306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optimistic', 'adj.  乐观的', 10307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proponent', 'n.  支持者； 倡导者', 10308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insolvent', 'adj.  财力不足的， 破产的', 10309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submarine', 'adj.  水下的， 海底的 n. 潜水艇', 10310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empiricism', 'n.  经验论， 经验主义', 10311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sleek', 'adj. 光滑而有光泽的；线条流畅的；时髦的 vt.  使平整光亮', 10312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'particle', 'n.  微粒， 颗粒； 【语】小品词', 10313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'musician', 'n.  音乐家， 乐师', 10314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'typify', 'vt.  是…的典范； 成为…的特征', 10315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stagnant', 'adj.  不景气的； 停滞的； 迟钝的； 因不流动而污浊的', 10316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perceptive', 'adj.  感知的， 知觉的； 有洞察力的， 理解力强的', 10317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'annotation', 'n.  注释， 注解', 10318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minimize', 'vt.  将…减到最少， 使最小化； 降低， 贬低', 10319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sweep', 'v. 打扫；席卷，横扫；挥动，舞动；迅速传播；', 10320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'descend', 'v.  遗传； 下降； 起源； 降临， 来临', 10321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mechanics', 'n.  机械学， 力学； 技巧， 方法', 10322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toed', 'adj.  有趾的', 10323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maglev', 'n.  磁力悬浮火车', 10324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'logical', 'adj.  逻辑的； 符合逻辑的， 合理的； 有逻辑头脑的', 10325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'characterize', 'vt.  以…为特征； 刻画； 描述', 10326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'descent', 'n.  血统， 世系； 下降', 10327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stunt', 'vt. 阻碍生长；遏制 n.  特技表演； 噱头； 愚蠢行为', 10328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weird', 'adj.  怪异的， 神秘的', 10329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'farce', 'n.  笑剧， 滑稽剧； 闹剧', 10330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ridiculous', 'adj.  荒唐的， 可笑的', 10331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrusion', 'n.  侵扰， 干扰； 侵犯； 侵入， 闯入', 10332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refute', 'vt.  反驳， 驳斥', 10333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'severe', 'adj.  严重的； 严厉的； 剧烈的； 严峻的， 艰巨的； 朴素的， 不加装饰的', 10334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exemplify', 'vt.  是…的典型； 例示， 举例证明', 10335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emerge', 'vi.  显露， 暴露； 出来， 现出', 10336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lease', 'n. 租约；租期 vt.  出租', 10337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exploit', 'vt.  开发； 利用； 剥削 n.  英勇行为， 业绩， 功绩', 10338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eager', 'adj.  渴望的， 热切的', 10339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evidence', 'vt. 证明 n.  证据； 迹象； 根据', 10340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'republic', 'n.  共和国； 共和政体', 10341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'errand', 'n.  差事， 差使', 10342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flamboyant', 'adj.  艳丽的， 绚丽夺目的； 炫耀的', 10343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lethal', 'adj.  致命的； 破坏性极大的， 极其有害的', 10344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stun', 'vt.  使昏迷； 使震惊； 使…目瞪口呆， 给以深刻印象', 10345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repetition', 'n.  重复， 反复； 重复的事', 10346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sled', 'v.  乘雪橇， 用雪橇运 n. 雪橇；摘棉机', 10347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polygamous', 'adj.  一夫多妻的， 一妻多夫的', 10348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspense', 'n.  担心， 焦虑； 悬念， 不确定', 10349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gemstone', 'n.  经雕琢的宝石', 10350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrate', 'v.  讲述， 叙述', 10351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spring', 'v. 跳跃；涌现，突然出现；突然提出 n.  泉； 弹簧， 发条； 春天； 跳， 跃', 10352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autonomy', 'n.  自治， 自治权； 自主， 自主权', 10353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gibe', 'n&v.   嘲弄， 讥笑', 10354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fitness', 'n.  健康， 健壮； 适合', 10355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shred', 'n. 碎片，细条；些许，少量 vt.  切碎， 撕碎', 10356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kindle', 'v.  点燃， 开始燃烧； 激起', 10357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surrender', 'v. 投降；放弃，交出 n.  投降； 屈服， 屈从； 放弃', 10358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faint', 'vi. 昏厥，晕倒 adj. 模糊的，不清楚的；无力的，虚弱的；眩晕的 n.  昏厥', 10359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elm', 'n.  榆树', 10360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shade', 'n. 阴凉处，遮光物；阴暗；色度；差别 vt.  遮蔽， 遮光', 10361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collide', 'vi.  碰撞， 互撞； 冲突， 抵触', 10362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cardinal', 'adj. 主要的，最重要的 n.  红衣凤头鸟', 10363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insist', 'v.  坚持要求； 坚决主张', 10364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evergreen', 'adj. 常绿的 n.  常绿树， 常青树', 10365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staggered', 'adj.  交错的， 错开的； 震惊的', 10366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volume', 'n.  体积， 容积， 容量； 音量； 卷， 册； 书', 10367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transact', 'v.  交易； 执行， 处理', 10368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catalyst', 'n.  催化剂， 触媒； 促使变化的人', 10369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guideline', 'n. 指导方针，指导原则', 10370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loose', 'adj.  松散的， 宽松的； 不精确的， 不严密的； 不牢固的； 自由的， 散漫的', 10371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loathsome', 'adj.  令人厌恶的， 讨厌的', 10372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flint', 'n.  燧石， 打火石', 10373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preeminent', 'adj.  卓越的， 杰出的', 10374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indignant', 'adj.  愤慨的， 恼怒的', 10375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decimal', 'adj. 十进位的，小数的 n.  小数', 10376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardly', 'adv.  几乎不， 简直不； 刚刚， 仅仅', 10377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lasting', 'adj.  持久的， 永久的', 10378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cynical', 'adj.  愤世嫉俗的， 冷嘲热讽的', 10379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'technical', 'adj.  技术的， 工艺的； 专业的', 10380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outermost', 'adj.  最外面的， 离中心最远的', 10381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'companion', 'n.  同伴， 共事者', 10382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'culminate', 'vi.  达到顶点； 告终； 【天】到中天', 10383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tortuous', 'adj.  折磨人的， 令人痛苦的； 曲折的， 蜿蜒的； 含混不清的， 拐弯抹角的', 10384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paucity', 'n.  极小量， 少量', 10385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stretch', 'v.  延伸， 拉长 n. 一段路程；延伸', 10386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strand', 'n. 股，缕；部分，方面 vt.  使滞留； 使搁浅', 10387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accomplish', 'vt.  达到； 完成； 实现', 10388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constituent', 'adj.  有宪法制定或修改权的； 组成的， 构成的 n. 选民；要素，成分', 10389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intentionally', 'adv.  有意地， 故意地', 10390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irritate', 'vt.  激怒， 使烦躁； 刺激', 10391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'havoc', 'n.  混乱， 大破坏', 10392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'responsible', 'adj.  有责任感的， 负责的； 需负责任的； 责任重大的， 重要的', 10393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vagrant', 'adj.  漂泊的 n. 无业游民，流浪者', 10394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'medal', 'n.  奖牌， 奖章', 10395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linen', 'n.  亚麻织品； 亚麻布', 10396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satellite', 'n.  卫星； 人造卫星', 10397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'packed', 'adj.  拥挤的； 压紧的', 10398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illuminate', 'vt.  照亮； 启发， 启迪； 阐明， 说明', 10399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lizard', 'n.  蜥蜴', 10400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delirium', 'n.  精神错乱， 神志失常', 10401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preoccupation', 'n.  主要考虑因素； 全神贯注', 10402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vow', 'v. 发誓 n.  誓约', 10403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cipher', 'n.  密码， 暗号', 10404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protrude', 'v.  突出， 伸出', 10405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'residue', 'n.  剩余物， 残余物', 10406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noted', 'adj.  著名的', 10407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frenzy', 'n.  狂暴， 狂热， 疯狂', 10408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forum', 'n.  论坛； 讨论会', 10409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contempt', 'n.  轻视， 鄙视， 轻蔑', 10410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'horizon', 'n. 地平线；', 10411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undertaking', 'n.  任务， 项目； 事业， 企业； 承诺， 保证', 10412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'figurative', 'adj.  比喻的， 借喻的， 象征的； 形象的', 10413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sweat', 'v.  出汗 n. 汗；一身汗', 10414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'progressive', 'adj.  进步的； 逐步的， 渐进的； 【语】进行时的', 10415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'betray', 'vt.  出卖， 泄露； 辜负， 对…不忠； 流露情感', 10416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aloft', 'adv.  在高处； 在空中', 10417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contributory', 'adj.  贡献的； 捐助的； 促进的', 10418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deliberate', 'adj.  故意的， 蓄意的； 审慎的， 深思熟虑的 v.  深思熟虑', 10419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swear', 'v.  诅咒； 宣誓， 发誓', 10420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atmosphere', 'n.  大气， 大气层； 空气； 气氛， 氛围', 10421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decorate', 'v.  装饰， 布置', 10422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'career', 'n.  生涯， 经历； 职业', 10423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slacken', 'v.  松弛， 放松； 减缓， 放慢', 10424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'release', 'n&vt.  释放； 发布， 公开； 发泄', 10425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charter', 'vt. 特许设立，给予特权；包租 n.  纲领， 宣言； 宪章； 特许状', 10426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abiding', 'adj.  持久的， 永久的', 10427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liberate', 'vt.  解放； 释放', 10428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moral', 'adj. 道德的，道义上的；有道德的，品行端正的；精神的', 10429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diminution', 'n.  减少， 缩减', 10430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aspire', 'v.  有志于； 热望， 向往', 10431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explode', 'v.  爆炸； 激增； 冲动， 发怒', 10432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outbreak', 'n.  发作； 爆发', 10433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nap', 'n.  小睡， 打盹', 10434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manipulate', 'vt.  操作， 处理； 利用， 操纵', 10435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'similar', 'adj.  相似的， 类似的', 10436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ecological', 'adj.  生态的', 10437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contradict', 'v.  反驳； 同…矛盾， 相抵触', 10438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'digitize', 'vt.  数字化', 10439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'partnership', 'n.  合伙； 伙伴关系； 合伙人身份', 10440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shape', 'n. 形状，外形，样子；体形，身材；形式；幻象；情况，状况 vt.  使成为…形状， 塑造； 决定…的形成', 10441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verbalize', 'v.  用言语表达', 10442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'momentous', 'adj.  重大的， 重要的', 10443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specify', 'vt.  使具体化； 明确规定， 详细说明', 10444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allegiance', 'n.  忠诚， 效忠， 拥戴', 10445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wanna', 'v.  想要', 10446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crossing', 'n.  十字路口， 人行横道； 过境处； 交叉点； 穿越， 横渡', 10447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relevance', 'n.  有关， 相关； 中肯， 适当； 重大关系， 意义； 实用性', 10448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quarry', 'v.  采石； 采集 n. 采石场，石矿；猎物，追捕的对象', 10449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravel', 'n.  沙砾， 砾石', 10450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'malnutrition', 'n.  营养不良', 10451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submerge', 'v.  浸没， 淹没', 10452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'converge', 'vi.  汇聚， 聚集， 聚合； 相交， 会合； 趋于一致', 10453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pertinent', 'adj.  相关的； 恰当的， 贴切的', 10454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compose', 'v.  创作； 组成； 使安定', 10455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'giraffe', 'n.  长颈鹿', 10456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supersonic', 'adj. 超音速的，超声波的 n.  超音速， 超声波', 10457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cell', 'n.  细胞； 基层组织； 单人房间； 电池', 10458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swell', 'v. 增加，扩大；膨胀，肿胀 n.  波浪的涌动； 隆起； 增强， 增加', 10459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remind', 'vt.  提醒； 使想起； 使发生联想', 10460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crude', 'adj.  天然的， 未提炼的； 粗糙的； 粗俗的', 10461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'valid', 'adj.  有根据的， 合理的； 有效的', 10462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'withstand', 'vt.  经受住， 耐； 抵挡', 10463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inertia', 'n.  惯性； 惰性', 10464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'epitomize', 'vt.  成为…的缩影； 摘要， 概括， 缩写', 10465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wintry', 'adj.  冬天的； 寒冷的； 冷淡的', 10466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encourage', 'v.  鼓励， 激励； 促进， 激发', 10467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacuum', 'n. 真空；真空状态，空白，', 10468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'era', 'n.  纪元， 年代， 时代； 代', 10469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'administer', 'vt.  管理； 执行； 给予， 提供', 10470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transplant', 'vt.  移植； 使迁移， 使移居； 移栽， 移种 n.  移植', 10471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deficit', 'n.  不足额； 赤字， 逆差', 10472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elegant', 'adj.  优美的， 高雅的； 雅致的， 精美的； 简练的， 简洁的', 10473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cohere', 'vi.  连贯， 一致； 黏合； 齐心协力， 团结一致', 10474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snowflake', 'n.  雪花， 雪片', 10475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linger', 'vi.  徘徊， 流连； 继续存留； 缓慢消失', 10476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grasshopper', 'n.  蚂蚱， 蝗虫', 10477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dispel', 'vt.  驱散， 驱逐； 消除', 10478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cascara', 'n.  缓泻剂', 10479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slip', 'v. 滑倒，失足；滑落；悄悄疾行，溜；摆脱；下降，跌落；陷入 n.  差错， 纰漏； 滑倒； 纸片', 10480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'species', 'n.  种类， 类群', 10481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anchor', 'v. 抛锚；使固定；扎根，基于；主持 n.  锚； 给人安全感的物， 精神支柱', 10482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manifesto', 'n.  宣言， 声明', 10483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quench', 'vt.  扑灭， 熄灭； 解', 10484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spice', 'n. 香料，调味品；趣味，情趣 vt.  加香料于； 给…增添趣味', 10485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pedagogy', 'n.  教育学， 教学法', 10486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'screen', 'vt. 掩蔽；审查；筛选 n.  屏幕', 10487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autonomous', 'adj.  自治的； 独立自主的', 10488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'naked', 'adj.  裸露的， 无遮盖的； 直白的， 露骨的， 不加掩饰的', 10489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vibration', 'n.  振动， 颤动', 10490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aerial', 'adj. 空中的，地表以上的；从飞行器上的 n.  天线', 10491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trial', 'n.  审讯； 试验， 试用； 令人伤脑筋的人', 10492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perception', 'n.  感知， 感觉； 认识， 观念； 洞察力', 10493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saturation', 'n.  饱和； 饱和度', 10494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stylistic', 'adj.  风格上的， 文体上的', 10495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undertake', 'v.  承担； 进行， 从事', 10496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optimize', 'vt.  使最优化； 充分利用', 10497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indigenous', 'adj.  本地的， 本土的； 土产的； 土著的', 10498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'visualize', 'v.  想象， 使形象化； 构思', 10499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rejuvenate', 'vt.  使年轻； 使恢复活力', 10500);
