INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'individualistic', 'adj. 个人主义的', 3501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stylistic', 'adj. 风格上的,文体上', 3502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eka', 'n. 准(第一)', 3503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'check', 'v. 检查 n. 核对,支票', 3504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cabin', 'n. 小屋, 船舱', 3505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convenient', 'adj. 便利的,方便的', 3506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geography', 'n. 地理(学)', 3507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bottle', 'n. 瓶子 vt用瓶装', 3508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exaggeration', 'n. 夸张', 3509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hamper', 'v. 妨碍, 牵制', 3510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unpleasant', 'adj. 不愉快的；不合意的', 3511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'softwood', 'n. 软木材', 3512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arsenic', 'n. [化]砷, 砒霜', 3513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bean', 'n. 豆, 豆形果实', 3514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slate', 'n. 板岩,石板', 3515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reptilian', 'n. 爬行类动物', 3516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overirrigation', 'n. 过量灌溉', 3517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bold', 'adj. 大胆的, 无礼的', 3518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conclusive', 'adj. 决定性的,结论性的', 3519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'file', 'n. 文档 vt登记备案 ,提出', 3520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'honeybee', 'n. 蜜蜂', 3521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satiric', 'adj. 讽刺的,挖苦的', 3522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refresh', 'v. (使)精神振作,(使)恢复活力', 3523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'starvation', 'n. 饥饿, 饿死', 3524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personally', 'adv. 亲自；就个人来说', 3525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spruce', 'n. 云杉', 3526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprehend', 'v. 理解，领会', 3527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diffusion', 'n. 传播，散布', 3528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'differentiate', 'v. 区分 ,区别', 3529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radical', 'adj. 根本的；激进的 n激进分子', 3530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whenever', 'conj. 无论何时，随时', 3531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stiffen', 'v. 弄硬；加强', 3532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simulate', 'v. 模拟, 模仿', 3533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fetus', 'n. 胎儿', 3534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feeder', 'n. 饲养员', 3535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reminder', 'n. 提醒物；暗示', 3536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foodstuff', 'n. 食品, 粮食', 3537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shepherd', 'n. 牧羊人 v. 带领，引导', 3538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pine', 'n. 松(树) vi消瘦', 3539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'informant', 'n. 通知者, 告密者', 3540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allocate', 'v. 分派, 分配', 3541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cedar', 'n. 雪松', 3542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vanish', 'v. 消失', 3543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slab', 'n. 厚板，平板', 3544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coexist', 'v. 共存', 3545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marble', 'n. 大理石', 3546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moose', 'n. [动] 驼鹿', 3547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cod', 'abbr. 货到付款 (Cash on Delivery) n鳕鱼', 3548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'migrant', 'n. 移居者, 候鸟', 3549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aviation', 'n. 航空,飞机制造业', 3550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frontal', 'n. 前沿', 3551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hexagonal', 'adj. 六角形的,六边的', 3552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'journal', 'n. 定期刊物, 杂志', 3553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assure', 'v. 使确信, 确保', 3554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sizable', 'adj. 相当大的', 3555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decompose', 'v. (使)腐烂', 3556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scout', 'n. 侦察员 vi侦察', 3557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mineralization', 'n. 矿化作用,成矿作用', 3558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'krypton', 'n. [化] 氪', 3559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diminish', 'v. (使)减少, (使)变小', 3560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'residual', 'adj. 剩余的, 残留的', 3561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chlorophyll', 'n. [生化]叶绿素', 3562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'xenon', 'n. 氙(惰性气体的一种,元素符号Xe)', 3563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coil', 'v. 盘绕, 卷', 3564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penicillin', 'n. [微]青霉素（一种抗菌素，音译名为盘尼西林）', 3565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homestead', 'n. 家宅，宅基', 3566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prestigious', 'adj. 享有声望的', 3567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frustration', 'n. 挫败, 挫折', 3568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'servant', 'n. 仆人', 3569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imitative', 'adj. 仿制的,模仿的', 3570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lesson', 'n. 功课', 3571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incubate', 'v. 孵卵', 3572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hectare', 'n. 公顷（等于1万平方米）', 3573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alert', 'adj. 警觉的n戒备', 3574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'committee', 'n. 委员会', 3575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chocolate', 'n. 巧克力', 3576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loosely', 'adv. 松散地', 3577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creator', 'n. 创建者, 创作者', 3578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dirt', 'n. 污垢, 泥土', 3579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Asian', 'n&a. 亚洲(的), 亚洲人(的)', 3580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enthusiastic', 'adj. 热心的, 热情的', 3581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proof', 'n. 证据，证明', 3582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infrastructure', 'n. 下部构造,基础下部组织', 3583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'novelist', 'n. (长篇)小说家', 3584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peruvian', 'n&a. 秘鲁人(的)', 3585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'static', 'adj. 静态的, 静止的', 3586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'osprey', 'n. 白色的羽毛, 鱼鹰', 3587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Scotland', 'n. 苏格兰(英国的一部分,在不列颠北部)', 3588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'underneath', 'adv. 在下面 prep在的下面', 3589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pillar', 'n. 柱子, 栋梁', 3590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affection', 'n. 影响, 感情', 3591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'someone', 'pron. 有人, 某人', 3592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kneel', 'v. 跪下', 3593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evaluation', 'n. 估价, 评价', 3594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'huckleberry', 'n. 越橘类', 3595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elk', 'n. 麋鹿', 3596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'darken', 'v. (使)变暗', 3597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suffer', 'v. 遭受, 经历', 3598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jaw', 'n. 颚,下巴', 3599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardship', 'n. 困苦, 艰难', 3600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'historically', 'adv. 历史上地', 3601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disorient', 'v. 使失去方向感, 使迷惑', 3602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anthocyanin', 'n. [植]花青素, [化]花色醣苔', 3603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acidic', 'adj. 酸的,酸性的', 3604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elder', 'n. 年长者, 老人', 3605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modification', 'n. 更改, 修改', 3606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anyone', 'pron. 任何一个', 3607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fingerboard', 'n. 键盘', 3608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watercraft', 'n. 船只', 3609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buildup', 'n. 集结, 增长', 3610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'varnish', 'n. 清漆；光泽 v. 涂清漆，使光亮', 3611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warfare', 'n. 战争, 作战, 冲突, 竞争', 3612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cop', 'n. 警官, 巡警', 3613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbiosis', 'n. [生]共生(现象),合作关系', 3614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'presidential', 'adj. 总统的', 3615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sponge', 'n. 海绵 vt擦', 3616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gut', 'n. 内脏', 3617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Russia', 'n. 俄罗斯', 3618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'powder', 'n. 粉(末) v搽粉,撒粉', 3619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organizational', 'adj. 组织的', 3620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abruptly', 'adv. 突然地；粗鲁地', 3621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'administrative', 'adj. 管理的，行政的', 3622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypothetical', 'adj. 假说的，臆说的', 3623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pastoral', 'adj. 田园生活的，宁静的', 3624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overtime', 'n. 超时', 3625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interglacial', 'adj. 间冰期的', 3626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bias', 'n. 偏见vt使存偏见', 3627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ahead', 'a&ad. 在前, 向前', 3628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lamp', 'n. 灯', 3629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conform', 'v. 使一致, 遵从', 3630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detractor', 'n. 诽谤者', 3631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'timescale', 'n. 时标, 时间量程', 3632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stove', 'n. 炉', 3633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sailfish', 'n. 旗鱼', 3634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marlin', 'n. 枪鱼', 3635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swordfish', 'n. 旗鱼', 3636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commit', 'v. 犯罪, 承诺, 委托', 3637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renewal', 'n. 更新, 恢复', 3638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'false', 'adj. 错误的；假的', 3639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Eurasian', 'adj. 欧亚的, 欧亚人的', 3640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tolerant', 'adj. 宽容的, 容忍的', 3641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dull', 'adj. 乏味的；阴沉的', 3642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depress', 'v. 使沮丧, 使消沉', 3643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortunate', 'adj. 幸运的, 侥幸的', 3644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buoyant', 'adj. 有浮力的, 轻快的', 3645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slick', 'adj. 圆滑的；精巧的', 3646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shine', 'v. 照耀,发光 n光泽', 3647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinship', 'n. 血族关系', 3648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helpful', 'adj. 有益的；给予帮助的', 3649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domestication', 'n. 驯养, 教化', 3650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blur', 'v. 弄脏 n. 污点, 模糊', 3651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'replenish', 'v. 补充', 3652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fellowship', 'n. 伙伴关系', 3653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tutelage', 'n. 监护', 3654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freudian', 'n. n&a,佛洛伊德学说(的)', 3655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'controversy', 'n. 论争, 辩论', 3656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blubber', 'n. 鲸脂,哭号v哭号', 3657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'basalt', 'n. 玄武岩', 3658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predation', 'n. 掠食', 3659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'qualification', 'n. 资格, 条件', 3660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perish', 'v. 丧生，消亡', 3661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photographer', 'n. 摄影师', 3662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boule', 'n. 人造宝石，议会', 3663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Berlin', 'n. 柏林[德国]', 3664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trance', 'n&v. 恍惚；出神', 3665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opaque', 'adj. 不透明的,难懂的', 3666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vigorously', 'adv. 精力旺盛地；健壮地', 3667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lease', 'n. 租赁vt出租,租得', 3668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brightly', 'adv. 明亮地', 3669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'underlies', 'v. 位于之下, 成为的基础', 3670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telecommunication', 'n. 电信，远程通信', 3671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recur', 'v. 再发生，重现', 3672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reset', 'v. 重新安排', 3673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constructive', 'adj. 建设性的,构造上的', 3674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'habituation', 'n. 适应', 3675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generalization', 'n. 一般化, 归纳, 概括', 3676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shock', 'n&v. 震动；震惊', 3677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permanence', 'n. 永久, 持久', 3678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tine', 'n. (尖)齿, 叉', 3679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacation', 'n. 假期,休假', 3680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'briefly', 'adv. 简短地；简略地', 3681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precipitate', 'v. 促成；使沉淀 n沉淀物', 3682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Scottish', 'n. 苏格兰人(的), 苏格兰语（的）', 3683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Norwegian', 'adj. 挪威的 n挪威人, 挪威语', 3684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lime', 'n. 酸橙,石灰', 3685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ball', 'n. 球, 球状物', 3686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'joiner', 'n. 工匠', 3687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bulk', 'n. (大)块,主体 vt使更大', 3688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repetition', 'n. 重复，反复', 3689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patronage', 'n. 赞助；光顾(买东西)', 3690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bacterium', 'n. 细菌', 3691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carman', 'n. 车夫,司机', 3692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incise', 'v. 切入, 切割', 3693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shaft', 'n. 柄，杆', 3694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leak', 'v. (使)漏；泄露 n漏洞', 3695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'energetic', 'adj. 精力充沛的,积极的', 3696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restore', 'v. 恢复,重建', 3697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Mexican', 'n&a. 墨西哥(的)， 墨西哥人(的)', 3698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cat', 'n. 猫', 3699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bit', 'n. 一点儿，少许；小片', 3700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doctor', 'n. 医生；博士', 3701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crumple', 'v. (使)皱，扭曲；(使)崩溃', 3702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equality', 'n. 等同性, 平等', 3703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'developmental', 'adj. 发展的, 进化的', 3704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'await', 'v. 等候', 3705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saline', 'adj. 含盐的；咸的', 3706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minimal', 'adj. 最小的, 最小限度的', 3707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warmth', 'n. 暖和, 温暖', 3708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newborn', 'n. 婴儿', 3709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opposition', 'n. 反对,相反', 3710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shadow', 'n. 阴影；影子', 3711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magic', 'n. 魔术；魔力 a有魔力的', 3712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meal', 'n. 餐, 一顿饭', 3713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mechanical', 'adj. 机械的, 机械制的', 3714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alien', 'adj. 外国(人)的 n. 外国(星)人', 3715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chapbook', 'n. 畅销故事书', 3716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shoe', 'n. 鞋', 3717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Manhattan', 'n. 曼哈顿岛(美国纽约一区)', 3718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distract', 'v. 转移,分散', 3719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satisfactory', 'adj. 令人满意的', 3720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devastate', 'v. 毁坏', 3721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Holland', 'n. 荷兰', 3722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glue', 'n. 胶(水) vt胶合', 3723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prospect', 'n. 前景, 景象', 3724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arcade', 'n. 拱廊', 3725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'navigational', 'adj. 导航的, 航行的', 3726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deterioration', 'n. 变坏, 退化', 3727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pursuit', 'n. 追求,追逐', 3728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soak', 'n&v. 浸泡, 渗透', 3729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metallurgy', 'n. 冶金, 冶金术', 3730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taxes', 'n. 赋税,  税收', 3731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solidify', 'v. (使)凝固,团结', 3732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'belt', 'n. 带子, 地带', 3733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cape', 'n. 海角,斗篷', 3734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spoil', 'v. 损坏；溺爱 vi变质', 3735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meticulously', 'adv. 仔细地,谨慎地', 3736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'configuration', 'n. 构造, 结构', 3737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unaided', 'adj. 未受协助的, 独立的', 3738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perplex', 'v. 使困惑，使费解', 3739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unnecessary', 'adj. 不必要的,多余的', 3740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concave', 'adj. 凹的 n凹(面)', 3741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beak', 'n. 鸟嘴, 喙', 3742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'descent', 'n. 下降,下倾', 3743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outermost', 'adj. 最外方的,离中心最远的', 3744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duck', 'n. 鸭，鸭肉', 3745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duty', 'n. 义务, 责任', 3746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yard', 'n. 院子，场地', 3747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legendary', 'adj. 闻名的；传说的', 3748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haul', 'vt& n. (用力)拖，拉', 3749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congressional', 'adj. 会议的；国(议)会的', 3750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abstraction', 'n. 提取', 3751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eel', 'n. 鳗鱼', 3752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hazard', 'n. 危险 vt冒…风险', 3753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'December', 'n. 十二月(略作Dec)', 3754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overlap', 'v. 重叠, 重复', 3755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'width', 'n. 宽度, 广度', 3756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pet', 'n. 宠物', 3757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'camouflage', 'v&n. 伪装', 3758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adverse', 'adj. 不利的，有害的', 3759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postage', 'n. 邮费', 3760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prairie', 'n. 大草原,牧场,', 3761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'triumph', 'n. 胜利 v. 获胜', 3762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cylindrical', 'adj. 圆柱形的', 3763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reinforce', 'v. 增强，加强', 3764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bent', 'n. 倾向, 爱好', 3765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'son', 'n. 儿子', 3766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stimulation', 'n. 激励,刺激', 3767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hibernate', 'v. 冬眠', 3768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auxiliary', 'adj. 辅助的, 补助的', 3769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'athlete', 'n. 运动员', 3770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kettle', 'n. 壶, 罐, 釜, 鼓', 3771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shut', 'v. 关上, 关闭', 3772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'priority', 'n. 优先(权)', 3773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salary', 'n. 薪水', 3774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collaboration', 'n. 合作，协作', 3775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waterpower', 'n. 水力(水力发电)', 3776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollen', 'n. 花粉', 3777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dealer', 'n. 经销商, 商人', 3778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firmly', 'adv. 坚固地，稳定地', 3779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relieve', 'v. 减轻, 解除', 3780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defensive', 'n&a. 防御(的)', 3781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equilibrium', 'n. 平衡', 3782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbolize', 'v. 象征', 3783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concrete', 'adj. 实在的，具体的 n混凝土', 3784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brea', 'n. 布雷亚(美国加州地名)', 3785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upset', 'v. 搅乱,使心烦 n不安', 3786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exocrine', 'adj. [医]外分泌的', 3787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'definite', 'adj. 明确的,一定的', 3788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formerly', 'adv. 从前, 以前', 3789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'camp', 'n. 营地 v. 宿营', 3790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cosmos', 'n. 宇宙', 3791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overlie', 'v. 躺在上面', 3792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shorten', 'v. 缩短, (使)变短', 3793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aboard', 'prep&ad. 在(船、飞机、车)上，上船', 3794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blend', 'v. (使)混和n混合物', 3795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'participation', 'n. 参加，参与', 3796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brass', 'n. 黄铜(制品)', 3797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detectable', 'adj. 可发现的,可察觉的', 3798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adhere', 'v. 粘附,遵守', 3799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accommodate', 'v. 容纳,提供(住处),适应', 3800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toolmaker', 'n. 精密工具制造者', 3801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'printmaking', 'n. 版画复制(术)', 3802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'populous', 'adj. 人口稠密的', 3803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wallpaper', 'n. 墙纸', 3804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reputation', 'n. 名誉, 名声', 3805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gasoline', 'n. 汽油', 3806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invite', 'v. 邀请；征求', 3807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tap', 'n&v. 塞子，龙头；轻叩(拍)', 3808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'igloo', 'n. 圆顶建筑', 3809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endless', 'adj. 无止境的,无穷的', 3810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formalize', 'v. 使正式, 形式化', 3811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edition', 'n. 版,版本', 3812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sew', 'v. 缝合, 缝纫', 3813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inefficient', 'adj. 效率低的,效率差的', 3814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geographer', 'n. 地理学者', 3815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laser', 'n. 激光', 3816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foul', 'adj. 邪恶的,下流的 n犯规 v弄脏', 3817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'willow', 'n. 柳(树)', 3818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuity', 'n. 连续性, 连贯性', 3819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteoric', 'adj. 流星的,大气的', 3820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explode', 'v. 爆炸；爆发', 3821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recipient', 'n. 接受者，接收者', 3822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Michigan', 'n. 密歇根州(美国州名)', 3823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'favorite', 'adj. 喜爱的 n特别喜爱的人(或物)', 3824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anxious', 'adj. 渴望的, 忧虑的', 3825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harness', 'n. 马具 v. 治理，束以马具', 3826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adoption', 'n. 采用, 收养', 3827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vie', 'v. 竞争', 3828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instruct', 'v. 教导, 指示', 3829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carol', 'n. 颂歌, 欢乐的歌', 3830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'god', 'n. 神, 上帝', 3831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'girl', 'n. 女孩', 3832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comedy', 'n. 喜剧', 3833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'provision', 'n. 供应,预备', 3834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exceptionally', 'adv. 格外地, 特别地', 3835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fieldstone', 'n. 散石,大卵石', 3836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ranch', 'v. 经营牧场n牧场', 3837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imperial', 'adj. 帝国的，帝王的', 3838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defenseless', 'adj. 无防备的', 3839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furnish', 'v. 布置, 装备, 提供', 3840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lag', 'v. 落后 n滞后', 3841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lumiere', 'n. 彩色照相术', 3842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accompaniment', 'n. 陪伴物, 伴奏', 3843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretend', 'v. 假装，装作', 3844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thresh', 'v. 打谷, 脱粒, 反复得做', 3845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repetitive', 'adj. 重复的,反复的', 3846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mule', 'n. 骡子,十分固执的人', 3847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prone', 'adj. 易于…的，很可能…的', 3848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wipe', 'v. 擦, 揩', 3849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'individualism', 'n. 个人主义, 利己主义', 3850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Russian', 'a& n. 俄罗斯(语)(的)', 3851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formulate', 'v. 构想出，规划', 3852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'krill', 'n. [动]磷虾(单复同)', 3853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forty', 'num. 四十', 3854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coastline', 'n. 海岸线', 3855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unevenly', 'adv. 不平坦地, 不均衡地', 3856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assess', 'v. 估定,评定', 3857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sick', 'adj. 有病的；恶心的', 3858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drapery', 'n. 布业，布匹', 3859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nick', 'n. 小伤口，刻痕', 3860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Ute', 'n. 犹特人(美洲印第安人的一种), 犹特语', 3861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ordinarily', 'adv. 平常地；普通地', 3862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'headquarter', 'v. 将之总部设在', 3863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peach', 'n. 桃(树)', 3864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiocarbon', 'n. 放射性炭', 3865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afield', 'adv. 远离着(家乡), 去远处', 3866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relocate', 'v. 重新部署', 3867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enormously', 'adv. 极度,大量', 3868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saltwater', 'adj. 盐水的, 海产的', 3869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pipe', 'n. 管子', 3870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mute', 'adj. 哑的,不发音的 vt消除(声音)', 3871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deglaciation', 'n. 冰消作用', 3872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glen', 'n. 峡谷, 溪谷', 3873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poison', 'n. 毒药vt 下毒', 3874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wax', 'n. 蜡, 蜡状物', 3875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neglect', 'vt&n. 忽视，忽略', 3876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pangaea', 'n. 泛古陆,  泛大陆', 3877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fahrenheit', 'n. 华氏温度计', 3878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lys', 'n. [化]赖氨酸', 3879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Sac', 'n. 〈生〉囊,液囊', 3880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midcontinent', 'n. 大陆中部', 3881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emperor', 'n. 皇帝, 君主', 3882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mainstay', 'n. 支柱;骨干', 3883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'connecticut', 'n. (美国）康涅狄格', 3884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wholly', 'adv. 整个,全部', 3885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brilliance', 'n. 光辉，辉煌', 3886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Oklahoma', 'n. 俄克拉荷马州', 3887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhinoceros', 'n. [动]犀牛', 3888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'externally', 'adv. 外部地, 外面地', 3889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'successor', 'n. 接班人, 继任人', 3890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tax', 'n. 税,税款', 3891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plumb', 'v. （用铅垂）测量,探测', 3892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lessen', 'v. 减少,缩小', 3893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trout', 'n. 鲑鱼', 3894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permian', 'n&a. [地]二叠纪(的)', 3895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superintendent', 'n. 主管人，监管人', 3896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'friendly', 'adj. 友好的, 友谊的', 3897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wasteful', 'adj. 浪费的，挥霍的', 3898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foraminifera', 'n. 有孔虫类', 3899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peace', 'n. 和平, 安静', 3900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domain', 'n. 领地,范围', 3901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agitate', 'v. 搅动,煽动', 3902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'farce', 'n. 闹剧；荒唐可笑', 3903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aborigine', 'n. 土著居民', 3904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attest', 'v. 证明', 3905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggressiveness', 'n. 进取精神, 侵犯', 3906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'privately', 'adv. 秘密，一个人', 3907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vague', 'adj. 不明确的,模糊的', 3908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lawlike', 'adj. 似法律的', 3909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oppositely', 'adv. 相反地, 相对地', 3910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anecdotal', 'adj. 轶事的,趣闻的', 3911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ounce', 'n. 盎司', 3912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disorder', 'n. 混乱 vt扰乱', 3913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defeat', 'vt&n. 击败,战败', 3914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synchronization', 'n. 同步化', 3915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dress', 'n. 连衣裙,女装 v打扮', 3916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biographer', 'n. 传记作者', 3917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creativity', 'n. 创造(力)', 3918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illness', 'n. 疾病, 生病', 3919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curriculum', 'n. 课程', 3920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Anglo', 'n. 盎格鲁, 英裔美国人', 3921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revival', 'n. 复兴, 复活', 3922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Hampshire', 'n. 汉普郡(英国南部之一郡)', 3923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'worthwhile', 'adj. 值得做的', 3924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spy', 'n. 间谍, 侦探 v侦察', 3925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instinctive', 'adj. 本能的,直觉的', 3926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signaler', 'n. 信号员', 3927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retire', 'v. 退休', 3928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turbulence', 'n. 骚乱, 动荡', 3929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paradigm', 'n. 范例', 3930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insight', 'n. 洞察力, 见识', 3931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penchant', 'n. 喜好(倾向)', 3932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sinkhole', 'n. 污水池', 3933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neptune', 'n. [天]海王星', 3934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cyanide', 'n. [化]氰化物', 3935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gin', 'n. 杜松烧酒  v开始', 3936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flax', 'n. 亚麻', 3937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revolve', 'v. 旋转', 3938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'withdraw', 'v. 收回,撤消', 3939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purple', 'adj. 紫色的', 3940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprise', 'v. 包含, 由组成', 3941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'timer', 'n. 计时员, 定时器', 3942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplant', 'v. 排挤，取代', 3943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harpsichord', 'n. 大键琴', 3944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peaceful', 'adj. a 和平的, 平静的', 3945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reign', 'n. 君主统治 v. 统治, 支配', 3946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appreciation', 'n. 感谢, 感激', 3947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tempt', 'v. 吸引,诱惑', 3948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boast', 'v&n. 自夸', 3949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revitalize', 'v. 新生', 3950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spiritual', 'adj. 精神上的', 3951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clan', 'n. 氏族,部落', 3952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fictional', 'adj. 虚构的,小说的', 3953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heterogeneous', 'adj. 异种的, 异质的', 3954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diversion', 'n. 转向, 转移', 3955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protrude', 'v. 突出', 3956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recrystallize', 'v. ( 使) 再结晶', 3957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warp', 'v. 弯曲,歪曲', 3958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Nevada', 'n. 内华达州(美国西部内陆州)', 3959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amusement', 'n. 娱乐, 消遣', 3960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monetary', 'adj. 货币的, 金融的', 3961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reed', 'n. 芦苇', 3962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legislature', 'n. 立法机关', 3963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'baboon', 'n. [动]狒狒', 3964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wedge', 'n. 楔 vt楔入, 楔进', 3965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overgraze', 'vt. 使过度放牧', 3966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embed', 'v. 使插入, 嵌入', 3967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blowhole', 'n. 喷水孔, 通风孔', 3968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imagist', 'n&a. 意像派者(的)', 3969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antenna', 'n. 天线', 3970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receptor', 'n. 接受器', 3971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magenta', 'n&a. 红紫色(的)', 3972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'valse', 'v. 轻轻地走 n. 华尔兹', 3973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebellion', 'n. 反叛，反抗', 3974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discoverer', 'n. 发现者', 3975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charcoal', 'n. 木炭', 3976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conifer', 'n. [植]松类, 针叶树', 3977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'botanist', 'n. 植物学家', 3978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrator', 'n. 讲述者', 3979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'critically', 'adv. 批评性地, 危急地', 3980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Inca', 'n. 印加人(古代秘鲁土著人)', 3981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'woolen', 'adj. 毛线的 n. 毛制品', 3982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dialogue', 'n. 对话', 3983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'void', 'adj. 无效的', 3984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variously', 'adv. 不同地, 各种各样地', 3985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dictate', 'v. 口授；命令', 3986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incursion', 'n. 侵犯，入侵', 3987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sweet', 'adj. 甜的', 3988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decode', 'v. 解码, 译解', 3989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advantageous', 'adj. 有利的', 3990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legend', 'n. 传说', 3991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toll', 'n. 过路(桥)费', 3992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deliberate', 'adj. 故意的,深思熟虑的', 3993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'milk', 'n. 乳, 牛奶', 3994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subside', 'v. 下沉,平静', 3995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'socially', 'adv. 社交上；社会上', 3996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inventory', 'n. 详细目录, 存货(清单)', 3997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twin', 'n. 双胞胎中一人 v. 使成对', 3998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drastic', 'adj. 激烈的, 极端的', 3999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chapel', 'n. 小教堂', 4000);
