INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mechanical', 'adj. 机械的， 机械制造的； 机械学的， 力学的； 呆板的', 7001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recommendation', 'n. 推荐， 推荐信； 建议； 优点， 可取之处', 7002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'welfare', 'n. 幸福； 福利， 福利救济', 7003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'flourish', 'vi. 繁荣，茂盛，兴旺 vt. 挥动', 7004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'output', 'n. 产量；输出；输出功率 vt. 输出', 7005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fatigue', 'v. 疲劳 n. 疲劳，劳累', 7006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'striking', 'adj. 显著的， 突出的； 惹人注目的， 容貌出众的', 7007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vessel', 'n. 容器； 船； 飞船； 管', 7008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'majority', 'n. 多数， 大多数', 7009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'drag', 'v. 拖，拉；迫使，硬拉；拖着脚步走 n. 累赘； 一吸， 一抽', 7010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crown', 'n. 王冠， 冕', 7011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'likely', 'adv. 可能 adj. 可能的；适合的', 7012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inquire', 'v. 打听， 询问； 调查', 7013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gymnasium', 'n. 体育馆， 健身房', 7014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'issue', 'v. 发行， 分发， 发出 n. 问题；发行，分发', 7015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vain', 'adj. 徒劳的； 自负的', 7016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lower', 'adj. 较低的；下面的 vt. 放下， 降低', 7017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'index', 'n. 索引； 指数， 指标', 7018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fry', 'vt. 油煎， 油炸， 油炒', 7019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'youngster', 'n. 青年， 年轻人， 孩子', 7020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'odd', 'adj. 奇特的； 临时的； 奇数的； 单只的； 剩余的， 挂零的', 7021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lung', 'n. 肺', 7022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conservation', 'n. 保存； 保护； 守恒', 7023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distraction', 'n. 分心的事； 心烦意乱； 精神错乱； 娱乐， 消遣', 7024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'supplement', 'n. 增补， 补充； 增刊， 副刊 vt. 增补， 补充', 7025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contrast', 'vi. 形成对比， 对比之下显出区别 n. 对比， 对照； 反差 vt. 对比，对照', 7026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'paragraph', 'n. 段， 节', 7027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'judgement', 'n. 意见； 审判； 判断', 7028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'proportion', 'n. 比例； 部分， 份儿； 均衡， 相称', 7029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'widen', 'v. 加宽， 变宽', 7030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crystal', 'n. 水晶， 结晶体， 晶粒', 7031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'occurrence', 'n. 发生， 出现； 发生的事件', 7032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inflation', 'n. 通货膨胀； 膨胀', 7033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thinking', 'adj. 深思的， 有理性的 n. 想法，意见，见解', 7034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cycle', 'n. 循环（周期） v. 骑自行车', 7035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'disposal', 'n. 丢掉， 销毁； 处理； 排列， 布置', 7036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'settlement', 'n. 解决； 协议； 居留地', 7037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'delegate', 'n. 代表， 代表团成员 vt. 委派…为代表； 授 ， 把…委托给', 7038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'literature', 'n. 文学， 文学作品； 文献， 图书资料', 7039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sphere', 'n. 球， 球体； 范围', 7040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inquiry', 'n. 询问， 打听； 调查', 7041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prejudice', 'n. 偏见，成见 vt. 使有偏见； 对…不利， 损害', 7042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dissolve', 'v. 溶解； 解散； 消失， 减弱； 结束', 7043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'digest', 'vt. 消化； 领会 n. 文摘； 摘要', 7044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'angle', 'n. 角， 角度； 观点， 立场', 7045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'immigrant', 'n. 移民， 侨民', 7046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tradition', 'n. 传统， 惯例', 7047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ability', 'n. 能力， 本领； 才能， 才智', 7048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'urgent', 'adj. 紧急的， 急迫的', 7049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'belief', 'n. 信任， 相信； 信念', 7050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bundle', 'n. 捆，包，束；包袱 vt. 收集， 归拢； 把…塞入', 7051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'suggestion', 'n. 建议， 意见； 细微的迹象； 暗示', 7052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'systematic', 'adj. 有系统的， 有计划的', 7053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cupboard', 'n. 柜橱； 碗碟橱， 食橱', 7054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'generally', 'adv. 一般地， 通常地； 普遍地', 7055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bacon', 'n. 咸肉', 7056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'likewise', 'adv. 同样地； 也， 又', 7057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'slender', 'adj. 细长的， 苗条的； 微薄的， 不足的', 7058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'troublesome', 'adj. 令人烦恼的， 麻烦的', 7059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'instruction', 'n. 命令， 指示； 用法说明； 教学， 教导', 7060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'oral', 'adj. 口头的； 口的', 7061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'married', 'adj. 已婚的； 婚姻的', 7062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'transaction', 'n. 办理， 处理； 交易， 业务； 会报， 学报', 7063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conscious', 'adj. 意识到的， 自觉的； 神志清醒的； 有意的， 存心的', 7064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fur', 'n. 软毛， 毛皮， 裘皮； 毛皮衣服', 7065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'auto', 'n. 汽车', 7066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sigh', 'vi. 叹气， 叹息 n. 叹息', 7067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'constant', 'adj. 经常的，不断的，连续发生的；永恒的；忠实的，忠诚的 n. 常数， 恒量', 7068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pants', 'n. 长裤， 便裤； 内裤', 7069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mislead', 'vt. 给…错误印象， 使误解； 把…带错路； 使误入歧途', 7070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'split', 'v. 分裂，分离；被撕裂，裂开；分担，分享 n. 裂口', 7071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'orchestra', 'n. 管弦乐队', 7072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'publication', 'n. 出版， 发行； 公布， 发表', 7073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sufficient', 'adj. 足够的， 充分的', 7074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'claim', 'vt. 声称，主张；对…提出要求，索取；以…为其成果；需要，值得 n. 要求， 认领， 索赔； 声称； 断言', 7075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'antique', 'adj. 古时的， 过时的 n. 古物，古董', 7076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sow', 'v. 播， 播种', 7077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'widespread', 'adj. 分布广的， 普遍的', 7078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'petroleum', 'n. 石油', 7079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'communication', 'n. 通讯， 交流， 交际； 通信工具， 交通联系', 7080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'directly', 'adv. 直接地； 正好地， 截然； 立即', 7081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tolerance', 'n. 忍受， 容忍， 忍耐力； 公差', 7082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'kneel', 'vi. 跪， 跪下， 跪着', 7083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'porter', 'n. 搬运工人； 看门人， 大楼管理员', 7084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fasten', 'v. 扎牢， 扣住', 7085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contest', 'n. 竞赛， 争夺 vt. 争夺， 与…竞争； 对…提出质疑， 辩驳', 7086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'author', 'n. 著作家， 作者', 7087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dirt', 'n. 灰尘， 土； 污物， 污垢', 7088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'astrophysics', 'n. 天体物理学', 7089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'greenhouse', 'n. 温室， 暖房', 7090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'preserve', 'vt. 保护， 维持； 保存； 腌制', 7091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'plus', 'adj. 表示加的；正的 prep. 加，加上 n. 加号， 正号', 7092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'establish', 'vt. 建立， 设立； 确立； 证实', 7093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expansion', 'n. 扩大， 扩充， 扩张， 膨胀', 7094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relevant', 'adj. 有关的， 切题的', 7095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'entry', 'n. 入口处； 登记； 进入； 参赛者名单； 条目', 7096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'license', 'n. 许可，执照 vt. 准许', 7097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'synthetic', 'adj. 综合的， 合成的； 虚假的', 7098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'headquarters', 'n. 司令部， 总部', 7099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expand', 'vt. 扩大， 使膨胀', 7100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gaze', 'n&vi. 凝视， 盯， 注视', 7101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'essay', 'n. 短文， 散文， 小品文', 7102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'survey', 'vt. 俯瞰； 检查； 测量 n. 调查， 勘察； 测量， 勘测； 全面审视， 概括论述', 7103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'plug', 'n. 插头，插座；塞子，栓 vt. 把…塞住， 用…塞住', 7104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bunch', 'vi. 集中， 挤在一起； 形成一束 n. 群，伙；束，串，捆 vt. 使成一束', 7105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thermometer', 'n. 温度计， 寒暑表', 7106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tense', 'adj. 拉紧的；紧张的 v. 拉紧， 绷紧 n. 时态', 7107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'postpone', 'vt. 延迟， 延期', 7108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bride', 'n. 新娘', 7109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'favourable', 'adj. 有利的， 赞成的； 顺利的', 7110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hammer', 'v. 锤击 n. 锤，榔头', 7111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'candy', 'n. 糖果', 7112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'seal', 'n. 封铅，封条；印，图章；海豹 vt. 封', 7113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mental', 'adj. 心理的， 精神的， 思想上的； 精神病的； 智力的', 7114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'decent', 'adj. 像样的， 过得去的， 体面的； 宽厚的， 大方的； 正派的； 合乎礼仪的， 得体的', 7115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'storage', 'n. 贮藏； 贮藏量', 7116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'investigate', 'v. 调查， 研究', 7117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'racial', 'adj. 种族的， 人种的', 7118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'switch', 'v. 转换， 改变 n. 开关，电闸；转换，改变', 7119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'niece', 'n. 侄女， 外甥女', 7120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'considerable', 'adj. 相当大的； 重要的', 7121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'auxiliary', 'adj. 辅助的， 附属的； 后备的', 7122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'heal', 'vi. 愈合， 痊愈， 恢复健康 vt. 使愈合，治愈，使康复；调停，消除', 7123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reserve', 'vt. 保留，留存；预订 n. 储备； 保留； 拘谨， 矜持； 替补队员， 后备部队； 自然保护区', 7124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'somehow', 'adv. 由于某种原因， 不知怎么的； 以某种方式', 7125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dive', 'vi. 跳水； 潜水； 俯冲', 7126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brick', 'n. 砖， 砖块， 砖状物', 7127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sympathy', 'n. 同情； 一致， 支持， 赞同', 7128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'heap', 'n. 堆， 大量', 7129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'consumer', 'n. 消费者， 用户， 消耗者', 7130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rescue', 'n&vt. 营救， 救援', 7131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cripple', 'n. 跛子；残疾人 vt. 使跛； 使残疾', 7132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'highly', 'adv. 高度地， 极， 非常赞许地', 7133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brief', 'adj. 简短的，短暂的 vt. 向…介绍基本情况，做…的提要 n. 概要， 摘要', 7134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'keyboard', 'n. 键盘', 7135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'initiative', 'n. 主动性； 首创精神； 主动的行动， 倡议； 主动权', 7136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recover', 'v. 重新获得， 挽回； 恢复', 7137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'determine', 'vi. 决意 vt. 决定；查明；使下决心', 7138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nature', 'n. 大自然； 本性； 性质', 7139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'social', 'adj. 社会的； 交际的， 社交的', 7140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'medication', 'n. 药物治疗； 药物', 7141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'drill', 'v. 钻， 打； 训练 n. 钻头；操练，训练', 7142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intelligent', 'adj. 聪明的， 理智的', 7143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'whilst', 'conj. 当…的时候', 7144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'clerk', 'n. 店员， 办事员， 职员', 7145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lobby', 'v. 向进行游说 n. 大厅；休息室；院外活动集团', 7146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'acknowledge', 'vt. 承认， 承认…的权威； 告知收到， 确认； 对…表示感谢， 报偿', 7147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'equip', 'vt. 装备， 配备； 使有准备', 7148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'radiation', 'n. 放射物， 辐射能； 辐射', 7149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'Christian', 'adj. 基督教的 n. 基督教徒，信徒', 7150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pulse', 'vi. 搏动， 跳动 n. 脉搏；脉冲', 7151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'luxury', 'n. 奢侈； 奢侈品', 7152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spiritual', 'adj. 精神的， 心灵的； 宗教的', 7153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'worthwhile', 'adj. 值得花时间的， 值得做的', 7154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mould', 'n. 霉，霉菌；模型，铸模；性格，气质 vt. 用模子做， 浇铸； 使形成， 把…铸造成', 7155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'increasingly', 'adv. 日益， 越来越多地', 7156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'elbow', 'n. 肘，肘部 vt. 用肘部， 用肘挤', 7157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'salad', 'n. 色拉， 凉拌菜', 7158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'strategic', 'adj. 对全局有重要意义的， 关键的； 战略的', 7159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vary', 'v. 改变； 多样化', 7160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'readily', 'adv. 乐意地， 欣然地； 容易地； 很快地， 立即', 7161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stoop', 'v. 俯身，弯腰；堕落，自贬 n. 弯腰， 曲背', 7162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'upper', 'adj. 上面的， 地位较高的', 7163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rocket', 'vi. 迅速上升， 猛涨 n. 火箭', 7164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'splendid', 'adj. 壮丽的； 极好的', 7165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'county', 'n. 郡， 县', 7166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'respondent', 'n. 回答者； 响应者； 被告', 7167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'episode', 'n. 一个事件； 插曲， 片段； 连续剧的一集', 7168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'convenience', 'n. 方便； 便利设施', 7169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'determination', 'n. 决心， 决定； 确定', 7170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discipline', 'n. 纪律；训练；惩罚；学科 vt. 训练； 惩罚， 处罚', 7171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'behalf', 'n. 利益', 7172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evidently', 'adv. 明显地， 显然', 7173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'objective', 'adj. 客观的， 无偏见的 n. 目标，目的', 7174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'injure', 'vt. 伤害， 损害， 使遭受损伤', 7175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'victimize', 'vt. 使受害， 使牺牲', 7176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exert', 'vt. 尽； 运用', 7177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'province', 'n. 省； 领域， 范围', 7178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scandal', 'n. 丑事， 丑闻； 流言蜚语； 反感， 愤慨', 7179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'horrible', 'adj. 令人恐惧的， 可怕的； 骇人听闻的； 极讨厌的， 使人不愉快的； 糟透的', 7180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'estimate', 'vt. 估计； 评价 n. 估计； 评价， 看法', 7181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'strengthen', 'vt. 加强， 巩固', 7182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'drip', 'vi. 滴下，漏水 n. 水滴； 滴水声', 7183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'injury', 'n. 损害， 伤害； 受伤处', 7184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exhibit', 'vt. 显示；陈列，展览 n. 展览品', 7185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brand', 'n. 品牌；烙印 vt. 铭刻， 打烙印于； 加污名于， 谴责', 7186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mushroom', 'vi. 迅速成长 n. 蘑菇', 7187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'alcohol', 'n. 酒精， 乙醇', 7188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'choke', 'vt. 使窒息； 塞满， 塞住', 7189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'proposal', 'n. 提议， 建议； 求婚', 7190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inevitable', 'adj. 不可避免的， 必然的', 7191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'deny', 'vt. 否定， 否认； 拒绝…的要求', 7192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'miserable', 'adj. 痛苦的； 悲惨的； 令人难受的', 7193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recreation', 'n. 娱乐活动， 消遣', 7194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'subtract', 'vt. 减， 减去， 去掉', 7195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'allowance', 'n. 津贴， 补贴； 零用钱', 7196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'portable', 'adj. 便于携带的， 手提式的', 7197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ancient', 'adj. 古代的， 古老的； 年老的， 看上去很老的', 7198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'glory', 'n. 光荣， 荣誉的事； 美丽', 7199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'secondary', 'adj. 次要的， 第二的； 中等的； 辅助的， 从属的', 7200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mission', 'n. 使命， 任务； 使团', 7201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'attorney', 'n. 律师， 代理人', 7202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wander', 'vi. 漫游， 闲逛， 漫步； 偏离正道； 走神， 恍惚', 7203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adopt', 'vt. 收养； 采用， 采取； 正式通过， 批准', 7204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'oppose', 'vt. 反对； 反抗', 7205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'singular', 'adj. 单数的； 非凡的， 奇特的； 独一无二的', 7206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'device', 'n. 器械， 装置， 设备； 手段， 策略', 7207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mainframe', 'n. 主机， 大型机', 7208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'motor', 'n. 发动机， 电动车', 7209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'minus', 'adj. 负的 prep. 减 n. 负数；减号', 7210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conservative', 'adj. 保守的，守旧的；不时兴的，传统的 n. 保守的人', 7211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'access', 'n. 接近；通道，入口；接近的机会 vt. 存取', 7212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conference', 'n. 会议， 讨论会； 讨论， 商谈', 7213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'activity', 'n. 活动； 活力； 行动', 7214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'primitive', 'adj. 原始的，早期的；简单的；粗糙的 n. 原人； 原始事物', 7215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'advisable', 'adj. 明智的， 可取的', 7216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dormitory', 'n. 集体寝室， 宿舍', 7217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'overcome', 'vt. 战胜， 克服； 压倒， 使受不了', 7218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cooperate', 'vi. 合作， 协作； 配合', 7219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cabin', 'n. 小屋； 船舱， 机舱', 7220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sum', 'vi. 共计 n. 总数；金额；算术', 7221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'current', 'adj. 当前的， 通用的； 流行的， 流传的', 7222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'heel', 'n. 脚后跟， 踵； 后跟', 7223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'variety', 'n. 多样化； 种类； 变种', 7224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'disturb', 'vt. 打扰， 扰乱； 弄乱； 使不安', 7225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'copper', 'n. 铜； 铜币， 铜制器', 7226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'persist', 'vi. 坚持， 持续', 7227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'audio', 'adj. 听觉的， 声音的', 7228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'civilian', 'n. 平民， 百姓', 7229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pump', 'n. 泵 vt. 抽， 泵送， 打气', 7230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pierce', 'vt. 刺穿， 穿孔于', 7231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'teenager', 'n. 青少年', 7232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apart', 'adv. 成距离，相间隔；分开，除去 adj. 分离的， 分隔的', 7233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'calendar', 'n. 日历， 历书， 历法', 7234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'offensive', 'adj. 冒犯的，无礼的；进攻的，攻击性的 n. 进攻， 攻势', 7235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cartoon', 'n. 卡通画， 幽默画； 动画片， 卡通片', 7236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'speculate', 'v. 推测， 推断； 投机， 做投机买卖', 7237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'launch', 'vt. 发射，投射，发动；使下水 n. 发射； 下水', 7238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'amid', 'prep. 在…中间， 在…之中， 被…围绕', 7239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beloved', 'adj. 所钟爱的， 所爱戴的', 7240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'single', 'adj. 单一的；独身的；单程的 n. 单程票；', 7241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confirm', 'vt. 证实， 肯定； 确认； 批准', 7242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cement', 'n. 水泥，胶泥 vt. 黏结； 巩固， 使团结', 7243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'subway', 'n. 地道； 地铁', 7244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gallon', 'n. 加仑', 7245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'acquaint', 'vt. 使认识， 使了解', 7246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appoint', 'vt. 任命， 委任； 约定， 指定', 7247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'elastic', 'adj. 有弹性的， 灵活的 n. 松紧带', 7248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assist', 'vt. 援助， 帮助， 协助', 7249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vast', 'adj. 巨大的， 大量的； 浩瀚的', 7250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intervene', 'vi. 干涉， 调停， 干预； 插入， 介入； 干扰， 打扰', 7251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'undergraduate', 'n. 大学本科生', 7252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'symbol', 'n. 象征； 符号， 标志', 7253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'commercial', 'adj. 商业的， 商务的； 商品化的， 商业性的', 7254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'joint', 'adj. 连接的； 共同的 n. 接头，接缝；关节', 7255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reasonable', 'adj. 通情达理的， 讲道理的； 合理的； 公道的； 尚好的， 过得去的', 7256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'available', 'adj. 现成可使用的， 通用的； 可取的； 联系的； 可得到的', 7257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confine', 'vt. 限制， 使局限； 使不外出， 禁闭', 7258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'advocate', 'vt. 拥护， 提倡， 主张 n. 拥护者， 提倡者； 辩护者， 律师', 7259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'frequency', 'n. 屡次； 次数， 频率', 7260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'horizontal', 'adj. 地平的， 水平的', 7261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'luggage', 'n. 行李', 7262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lick', 'vt. 舔，舔吃；打败，克服；轻拍，吞卷 n. 舔； 少量， 少许', 7263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'missile', 'n. 导弹， 飞弹， 投射物', 7264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dynamic', 'adj. 有活力的；动力的；不断变化的 n. 动力； 动力学', 7265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'satisfactory', 'adj. 令人满意的', 7266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'military', 'adj. 军事的，军用的 n. 军队， 武装力量', 7267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reluctant', 'adj. 不情愿的， 勉强的', 7268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'generate', 'vt. 发生， 引起； 生殖', 7269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'unusual', 'adj. 不平常的， 少有的； 独特的， 与众不同的', 7270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sector', 'n. 部门， 部分； 防御地段， 防区； 扇形', 7271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'passion', 'n. 激情， 热情； 酷爱', 7272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'extreme', 'adj. 极度的；末端的 n. 极端， 过分', 7273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'coil', 'n. 卷，圈；线圈 vt. 卷', 7274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ensure', 'vt. 保证； 保护', 7275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'coordinate', 'adj. 同等的， 并列的 vt. 协调， 调节 n. 坐标', 7276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'organism', 'n. 生物， 有机体； 机体， 有机组织', 7277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'athlete', 'n. 运动员， 体育家', 7278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'epidemic', 'adj. 流行性的；传染的 n. 流行病； 传播', 7279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'suppose', 'vt. 猜想， 假定， 让； [常用于被动语态]期望， 认为应该', 7280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'upright', 'adv. 挺直着， 竖立着 adj. 垂直的；正直的，诚实的', 7281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'remarkable', 'adj. 值得注意的， 引人注目的； 异常的， 非凡的', 7282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brake', 'v. 制动； 刹住， 用闸使放慢速度 n. 闸，刹车', 7283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tube', 'n. 管， 电子管， 显像管', 7284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'naval', 'adj. 海军的', 7285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'failure', 'n. 失败， 失败的人； 失灵， 故障； 不履行', 7286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accountancy', 'n. 会计工作； 会计学', 7287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'forge', 'vt. 打制， 锻造； 伪造', 7288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'carpet', 'n. 地毯', 7289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'solve', 'vt. 解答； 解释； 解决', 7290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hint', 'v. 暗示， 示意 n. 暗示，示意；细微的迹象；建议', 7291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'knot', 'vi. 打结 n. 结；节疤；节 vt. 把…打成结', 7292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'demonstrate', 'vt. 说明； 论证； 表露', 7293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'region', 'n. 地区， 地带， 区域； 范围， 幅度', 7294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'support', 'vt. 支撑；支持；供养；证实 n. 支持， 支撑物， 支持者', 7295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'yearly', 'adv. 一年一度地 adj. 每年的', 7296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'deceive', 'vt. 欺骗， 蒙蔽， 行骗', 7297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'saucer', 'n. 茶托， 碟子', 7298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hire', 'n&vt. 租用； 雇用', 7299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'kid', 'v. 戏弄， 开玩笑 n. 小孩；年轻人', 7300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'donkey', 'n. 驴； 笨蛋', 7301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'destination', 'n. 目的地， 终点， 目标', 7302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vertical', 'adj. 垂直的， 竖式的', 7303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'learning', 'n. 学习； 学问， 知识', 7304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'monument', 'n. 纪念碑， 纪念馆； 历史遗迹', 7305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'misconception', 'n. 误解', 7306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'damp', 'adj. 潮湿的，微湿的 n. 潮湿，湿气 vt. 使潮湿； 使沮丧； 抑制', 7307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vivid', 'adj. 鲜艳的； 生动的， 栩栩如生的', 7308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'honey', 'n. 蜜， 蜂蜜； 甜， 甜蜜； [常用于称呼] 宝贝儿', 7309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'screw', 'n. 螺丝 vt. 固定， 拧紧', 7310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gap', 'n. 缺口； 间隔； 差距； 缺陷', 7311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'missing', 'adj. 缺掉的， 失踪的', 7312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emphasize', 'vt. 强调， 着重', 7313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'virtue', 'n. 善， 美德； 优点， 长处', 7314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'normal', 'adj. 正常的， 平常的； 正规的， 规范的', 7315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'socialist', 'n. 社会主义者', 7316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gradual', 'adj. 逐渐的， 渐进的； 坡度平缓的', 7317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'figure', 'v. 出现； 合乎情理； 计算； 认为， 猜想 n. 数字；人物；算术；体形，体态；轮廓；画像，塑像；图，图形', 7318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ore', 'n. 矿， 矿石', 7319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'slight', 'adj. 轻微的，微小的 v. 侮慢；轻视，冷落', 7320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'previous', 'adj. 先的， 前的； 以前的', 7321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'transmit', 'vt. 传送， 传递； 传染； 播送， 发射', 7322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'socialism', 'n. 社会主义', 7323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'consumption', 'n. 消耗， 消费', 7324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'argue', 'vi. 争辩， 争论 vt. 争论，争辩，辩论；主张；说服', 7325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'technology', 'n. 工艺学； 工艺， 技术', 7326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'weaken', 'v. 削弱， 变弱', 7327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'voltage', 'n. 电压', 7328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'damn', 'interjection. 该死，见鬼〔表示很生气或失望〕 adv. 非常，很 adj. 该死的〔表示对某人或某事物生气〕', 7329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'superior', 'adj. 上级的，较高的；优越的；有优越感的，高傲的 n. 上级， 长官', 7330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'location', 'n. 位置， 场所； 外景拍摄地', 7331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compensation', 'n. 补偿， 赔偿', 7332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bankrupt', 'adj. 破产的', 7333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'punctual', 'adj. 严守时刻的， 准时的', 7334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'advertise', 'vt. 为…做广告， 宣传； 公告； 登广告', 7335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compromise', 'v. 妥协； 危及； 放弃 n. 妥协，和解，折中办法', 7336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sack', 'n. 麻袋，包；解雇；洗劫，劫掠 vt. 解雇； 洗劫， 劫掠', 7337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'software', 'n. 软件', 7338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'seminar', 'n. 研究班， 研讨会', 7339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comparative', 'adj. 比较的， 相对的', 7340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'competition', 'n. 竞争， 比赛', 7341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fruitful', 'adj. 多产的， 肥沃的', 7342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'react', 'vi. 反应， 作出反应', 7343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dragon', 'n. 龙', 7344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hesitant', 'adj. 犹豫的； 吞吞吐吐的', 7345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beyond', 'adv. 在更远处， 再往后 prep. 在…的那边，远于；迟于；越出', 7346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hell', 'n. 地狱； 极大的痛苦', 7347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'feedback', 'n. 回授， 反馈， 反应', 7348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hazard', 'n. 危险；公害 vt. 尝试着做； 冒…风险', 7349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'justify', 'vt. 证明…是正当的', 7350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'voluntary', 'adj. 自愿的， 志愿的', 7351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'connection', 'n. 联系， 关系； 连接， 衔接； 连贯性； 熟人， 关系', 7352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'proof', 'adj. 耐…的， 能防…的 n. 证据，证明；校样，样张', 7353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'timber', 'n. 木材， 原木； 大木料， 栋木', 7354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'roar', 'v. 吼叫，怒号，咆哮；轰鸣；大声喊出，大声表示 n. 呐喊声， 咆哮声， 吼叫声； 轰鸣', 7355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'presence', 'n. 出席， 到场； 存在； 仪表， 仪态', 7356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'phase', 'n. 阶段； 方面； 相， 相位', 7357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'surrounding', 'adj. 附近的；四周的', 7358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'efficiency', 'n. 效率； 功效， 效能', 7359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'overhead', 'adv. 在头顶上 adj. 在头顶上的，架空的 n. 经常费用， 管理费用', 7360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contract', 'v. 缩小； 订合同； 感染， 染上 n. 契约， 合同', 7361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conclude', 'v. 推断出， 推论出； 结束， 终了； 缔结， 议定', 7362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comprehension', 'n. 理解， 理解力， 领悟； 理解力测验', 7363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beggar', 'n. 乞丐 vt. 使贫穷', 7364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leather', 'n. 皮革， 皮革制品', 7365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comb', 'n. 梳子；鸡冠，冠状物 vt. 梳理； 在…搜寻； 彻底搜查', 7366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'innovative', 'adj. 创新的， 革新的', 7367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'insight', 'n. 洞察力； 洞悉； 深刻见解', 7368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fabric', 'n. 织物， 纺织品； 结构', 7369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'revolutionary', 'adj. 革命的，革新的 n. 革命者', 7370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'following', 'adj. 接着的，下列的 n. 一批追随者', 7371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exact', 'adj. 确切的，精确的 vt. 强求， 索取', 7372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'indoor', 'adv. 在室内， 在户内 adj. 室内的', 7373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'force', 'vt. 强迫；用力推动，用力打开 n. 军队， 兵力； 暴力， 武力； 力， 力气； 影响力， 效力', 7374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'centigrade', 'adj. 百分度的； 摄氏的', 7375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sexual', 'adj. 性的， 两性的； 性别的', 7376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sympathetic', 'adj. 同情的； 和谐的； 赞同的， 支持的； 合意的', 7377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'freight', 'n. 货运；货物；运费 vt. 运送', 7378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'range', 'v. 变动； 漫游， 四处搜索； 使排列成行 n. 一系列；范围；射程，距离；脉；射击场', 7379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distribution', 'n. 分发， 分配； 分布', 7380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tyre', 'n. 轮胎， 车胎', 7381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'derive', 'v. 取得； 起源', 7382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'capacity', 'n. 容量； 能力， 才能； 能量； 身份， 地位', 7383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cope', 'vi. 应付， 处理', 7384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'overseas', 'adv. 在海外 adj. 在海外的', 7385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impress', 'vi. 给人印象，引人注目 vt. 给…深刻印象；印，压印 n. 印记； 特征', 7386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confess', 'vt. 供认， 坦白； 承认', 7387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leak', 'v. 漏；泄露 n. 漏洞', 7388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ghost', 'n. 鬼， 灵魂， 鬼魂', 7389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'feature', 'vi. 起重要作用 n. 特征，特色；面貌；特写，专题节目；故事片 vt. 突出；由…主演', 7390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lean', 'v. 倾斜；屈身；靠 adj. 瘦的； 贫瘠的', 7391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'flat', 'adv. 平直地； 直截了当地 adj. 平的；固定的；漏气的；平淡的；沉闷的；浅的 n. 一套房间，单元住宅', 7392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recall', 'v. 回忆； 召回， 叫回； 收回， 撤销', 7393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leap', 'v. 跳，跃 n. 跳跃； 骤变', 7394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'waterproof', 'adj. 不透水的， 防水的', 7395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'barber', 'n. 理发师', 7396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'precise', 'adj. 精确的， 准确的； 严谨的', 7397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sensible', 'adj. 明智的； 合情理的； 有知觉的', 7398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'objection', 'n. 反对， 异议； 反对的理由', 7399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dispute', 'v. 争论， 争执； 对…表示异议 n. 争论', 7400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'precious', 'adj. 珍贵的， 宝贵的', 7401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'observation', 'n. 注意， 观察； 言论， 评论； 观察资料', 7402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tremble', 'vi. 发抖，哆嗦；摇动 n. 颤抖； 摇晃， 摇动', 7403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'suspect', 'adj. 可疑的， 不信任的 vt. 疑有；推测；对…表示怀疑 n. 嫌疑犯，可疑分子', 7404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apologize', 'vi. 道歉， 谢罪， 认错', 7405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inhabitant', 'n. 居民， 住户', 7406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fraction', 'n. 小部分； 片断； 分数', 7407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'filter', 'v. 过滤，透；走漏 n. 滤纸， 过滤嘴', 7408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sunlight', 'n. 日光， 阳光', 7409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'site', 'n. 地点，场所 vt. 使坐落在； 设置', 7410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emotion', 'n. 情感， 感情； 激动', 7411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'massive', 'adj. 大的， 大而重的； 大块的； 大量的， 大规模的', 7412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cease', 'v. 停止， 终止', 7413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assess', 'vt. 对估价； 评价， 评论', 7414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'asset', 'n. 资产， 财产； 有价值的特性或技能， 优点', 7415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'owe', 'vt. 欠； 应把…归功于； 感激， 感恩', 7416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scarce', 'adj. 缺乏的， 不足的； 稀少的， 罕见的', 7417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'minimum', 'adj. 最低的， 最小的 n. 最低限度；最小量', 7418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'queue', 'vi. 排队等候 n. 长队，行列', 7419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mathematical', 'adj. 数学的', 7420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apology', 'n. 道歉， 认错， 谢罪', 7421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'magic', 'adj. 有魔力的； 魔术的 n. 魔法，魅力', 7422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'argument', 'n. 争论， 辩论； 理由； 说理， 论证', 7423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reveal', 'vt. 揭露， 泄露； 展现， 显示', 7424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'data', 'n. 资料，数据', 7425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'theoretical', 'adj. 理论的', 7426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adequate', 'adj. 足够的； 可以胜任的', 7427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'utter', 'adj. 完全的，彻底的 vt. 发出， 说， 讲', 7428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'onion', 'n. 洋葱； 洋葱类植物', 7429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vibrate', 'v. 颤动', 7430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'drum', 'v. 有节奏地敲击 n. 鼓，鼓状物；圆桶', 7431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sausage', 'n. 香肠， 腊肠', 7432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hopeful', 'adj. 有希望的', 7433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tremendous', 'adj. 极大的， 非常的； 精彩的， 了不起的', 7434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'condense', 'v. 冷凝， 凝结； 浓缩， 压缩， 简缩', 7435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'barrier', 'n. 栅栏； 检票口； 屏障； 障碍， 隔阂', 7436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'realistic', 'adj. 现实的； 实际可行的； 现实主义的； 逼真的', 7437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'justice', 'n. 正义， 公正； 司法', 7438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'create', 'vt. 创造； 引起， 产生', 7439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'criminal', 'adj. 犯罪的， 刑事的 n. 犯人，罪犯，刑事犯', 7440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tag', 'vi. 尾随 n. 附加语；标签 vt. 给…加上标签', 7441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'notebook', 'n. 笔记本', 7442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'curious', 'adj. 好奇的； 奇怪的', 7443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'indirect', 'adj. 间接的， 婉转的', 7444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'individual', 'adj. 个别的；独特的 n. 个人， 个体', 7445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'resource', 'n. 资源； 财力； 应付办法， 谋略', 7446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ugly', 'adj. 丑陋的； 可怕的', 7447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nuisance', 'n. 讨厌的东西', 7448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tax', 'n. 税，税款；负担 vt. 对…征税； 使负担重， 使费尽力气', 7449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'earthquake', 'n. 地震， 大震荡', 7450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'excitement', 'n. 刺激， 激动， 兴奋； 令人兴奋的事， 刺激的因素', 7451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nightmare', 'n. 噩梦； 可怕的事物， 无法摆脱的恐惧', 7452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cord', 'n. 细绳， 粗线， 索； 灯芯绒裤', 7453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ending', 'n. 结尾， 结局； 死亡', 7454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'core', 'n. 果实的心； 核心， 要点', 7455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'council', 'n. 理事会， 委员会', 7456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'enforce', 'vt. 实施， 执行； 强制， 强迫， 迫使', 7457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'embassy', 'n. 大使馆； 大使馆全体成员', 7458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'departure', 'n. 离开， 起程， 出发； 背离， 违背', 7459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dash', 'vi. 猛冲，击碎 vt. 使猛撞，飞奔；溅 n. 猛冲； 破折号', 7460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'concrete', 'adj. 实在的， 具体的 n. 混凝土；具体物', 7461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'penalty', 'n. 处罚， 惩罚； 罚金', 7462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sociology', 'n. 社会学', 7463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'link', 'v. 连接，联系 n. 环节， 联系， 纽带', 7464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'flee', 'v. 逃走， 逃掉， 逃离； 避开， 逃避', 7465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distinct', 'adj. 与其他不同的； 清楚的， 明显的', 7466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scale', 'n. 大小，规模；等级，级别；天平，磅秤；比例；刻度，标度；鳞 vt. 攀登， 爬越', 7467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recovery', 'n. 恢复， 痊愈； 追回， 寻回， 收复', 7468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hedge', 'v. 用篱笆围； 避免直接回答 n. 篱笆，树篱；障碍物', 7469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tune', 'n. 调子；和谐 vt. 调整， 调节； 为调音', 7470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'weep', 'v. 哭泣， 流泪； 渗出', 7471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'aware', 'adj. 知道的， 意识到的', 7472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'drama', 'n. 戏剧， 剧本； 戏剧性事件', 7473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'security', 'n. 安全， 保障； 抵押品； 证券', 7474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'limp', 'adj. 软的；不强壮的 v. 〔因一腿受伤而〕跛行，一瘸一拐地走 n. 跛行', 7475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'award', 'n. 奖，奖品；判定 vt. 授予， 给予； 判给， 裁定', 7476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'organize', 'vt. 组织， 把…编组； 使有条理', 7477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'marriage', 'n. 结婚， 婚姻； 婚礼', 7478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stove', 'n. 炉， 火炉， 电炉', 7479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'alarm', 'n. 惊恐；忧虑；警报 vt. 使惊恐； 使担心', 7480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'weed', 'v. 除草 n. 杂草，野草', 7481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'continual', 'adj. 连续的； 频频的', 7482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'herd', 'n. 兽群，牧群 vt. 放牧', 7483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'limb', 'n. 肢， 臂， 腿； 树枝', 7484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'balloon', 'n. 气球， 玩具气球', 7485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'motion', 'v. 打手势， 示意 n. 运动；手势，眼色，动作；提议', 7486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'limited', 'adj. 有限的', 7487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'idle', 'adj. 空闲的，懒散的；无用的 v. 虚度， 无所事事', 7488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confidence', 'n. 信任， 信赖； 信心， 自信', 7489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'arbitrary', 'adj. 随心所欲的， 专断的', 7490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fearful', 'adj. 害怕的， 可怕的； 不安的， 忧虑的', 7491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accent', 'n. 口音， 腔调； 重音', 7492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'passive', 'adj. 被动的， 消极的', 7493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fertilizer', 'n. 肥料', 7494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lorry', 'n. 运货汽车， 卡车', 7495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'carrier', 'n. 运输工具， 运载工具； 带菌者； 载重架， 置物架', 7496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fragment', 'v. 成碎片 n. 碎片，破片，碎块', 7497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'corresponding', 'adj. 相应的， 符合的', 7498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'response', 'n. 回答， 答复； 反应， 响应', 7499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'treaty', 'n. 条约， 协议， 协定', 7500);
