INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'accept', 'vt.  接受； 承认； 相信', 3001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'zigzag', 'adj. “之”字形的 v.  弯弯曲曲行进 n. “之”字形；蜿蜒曲折', 3002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seat', 'v.  使坐下； 供给…座位， n. 座位，座部；所在地，场所；席位，职位', 3003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'horse', 'n.  马', 3004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twelve', 'num.  十二， 十二个', 3005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'London', 'n.  伦敦', 3006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'underwater', 'adv.  在水下， 在水中 adj. 水下的；水下使用的；水下行动的', 3007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'singular', 'adj.  单数的； 单一的', 3008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'autumn', 'n.  秋， 秋季', 3009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bridge', 'v.  架桥于； 把…连接起来 n. 桥，桥梁；桥牌', 3010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'conference', 'n.  会议； 讨论， 商谈', 3011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'activity', 'n.  活动， 行动； 活跃， 活力', 3012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dormitory', 'n.  宿舍', 3013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'recite', 'v.  背诵， 朗诵； 列举， 逐一讲述', 3014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seek', 'v.  [sought-sought] 寻找， 追求； 征求， 请求； 试图， 设法； 探索', 3015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sun', 'n.  太阳， 日', 3016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eighteenth', 'num.  第十八', 3017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seem', 'v.  好像， 似乎', 3018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'secretary', 'n.  秘书； 书记； 部长， 大臣', 3019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'heel', 'n.  脚后跟， 踵； 后跟', 3020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'disturb', 'v.  弄乱， 打乱； 打扰； 使烦恼', 3021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'so', 'adv.  如此， 那么； 非常， 很； 这样， 那样；', 3022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pierce', 'v.  刺穿， 刺破， 穿透； 穿孔， 打眼', 3023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'key', 'n.  钥匙； 关键， 要害； 键； 调； 答案， 题解； 图例', 3024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'teenager', 'n.  十几岁的青少年', 3025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'calendar', 'n.  日历， 月历； 日程表', 3026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'silk', 'n.  丝， 丝绸', 3027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dumpling', 'n.  饺子', 3028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'silent', 'adj.  寂静的； 沉默的； 无声的， 不发出声音的', 3029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'storm', 'v.  猛攻， 直捣； 怒气冲冲地走 n. 暴风雨，暴风雪；激动，爆发', 3030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'one', 'pron.  一人， 一个； 一个人， 任何人 num. 一，一个', 3031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'garage', 'n.  车库； 汽车修理行', 3032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'slipper', 'v.  用拖鞋打 n. 拖鞋；轻便舞鞋', 3033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'store', 'v.  贮藏， 储备， 存储 n. 商店，店铺；贮存，储备；储备品；仓库', 3034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flower', 'v.  开花； 发育， 成熟； 繁荣 n. 花；花卉', 3035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'single', 'adj.  单一的， 单个的； 未婚的， 独身的； (床或', 3036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hill', 'n.  小山， 山冈； 斜坡', 3037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pull', 'v. 拉，拖，拔；移动 n.  拉， 拖； 拉力， 牵引力， 引力', 3038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'subway', 'n.  地铁； 地道， 地下过道', 3039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'to', 'prep.  向， 往， 对着； 对， 给， 于； 趋于， 倾向； 直到…为止， 在…之前； 比， 对；', 3040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fourth', 'num. 第四 n.  四分之一', 3041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'story', 'n.  故事， 传说， 小说； 情况， 事情； 报道； 层', 3042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'but', 'adv.  只， 仅仅 conj. 但是，可是，然而；而 prep. 除…以外', 3043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'country', 'n.  国家； 国土； 国民， 全国人民； 农村， 乡村', 3044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'symbol', 'n.  符号， 标志； 象征', 3045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bus', 'n.  公共汽车', 3046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'separate', 'v.  使分离， 使分开； 划分， 区分， 区别； 分离， 分开； 分居； 使分离， 使分开； 划分， 区分， 区别； 分离， 分开； 分居', 3047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dislike', 'n&v.  不喜欢， 讨厌', 3048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'buy', 'v.  [bought-bought] 买， 买得； 向…行贿， 收买', 3049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'express', 'adv.  用快递方式； v. 表示，表达 adj. 特快的，直达的；明确的，明白表示的', 3050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ruler', 'n.  统治者， 支配者； 尺', 3051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'zero', 'num. 零 n.  零点， 零度', 3052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'amazing', 'adj.  令人惊异的', 3053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'postcard', 'n.  明信片', 3054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'up', 'adv. 向上，向较高处；往北；成直立姿势，起来；彻底地，完全地 n.  上升；　繁荣', 3055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fifteenth', 'num. 第十五 n.  十五分之一', 3056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'unusual', 'adj.  不平常的， 少有的； 独特的， 与众不同的', 3057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'us', 'pron.  我们', 3058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'usual', 'adj.  通常的， 惯常的', 3059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sink', 'v. 下沉，沉没 n. 洗脸盆；洗涤槽；洗碗池', 3060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'degree', 'n.  度， 度数； 程度； 学位； 地位， 身份', 3061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'this', 'pron.  这， 这个', 3062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'necessary', 'adj. 必要的，必需的；必然的，势必的，不可避免的 n.  必需品', 3063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thin', 'adv. 薄，细；稀疏 adj. 薄的；细的；瘦的；稀薄的；淡薄的 v.  变薄，', 3064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ocean', 'n.  洋， 海洋； 许多， 大量', 3065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'especially', 'adv.  特别， 尤其， 格外', 3066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'once', 'adv. 一次，一回；曾经，一度 conj.  一旦…就…', 3067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'solve', 'v.  解决， 处理； 解答', 3068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'desk', 'n.  书桌， 办公桌', 3069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'know', 'v.  [knew-known] 知道， 了解； 认识， 熟悉； 通晓， 会； 认出， 分辨', 3070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sing', 'v.  [sang-sung] 唱， 演唱； 鸡鸣', 3071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Internet', 'n.  互联网， 因特网', 3072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'support', 'v.  支撑， 扶持， 拥护； 供养， 赡养； 维持', 3073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coin', 'v.  创造 n. 硬币，钱币', 3074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drop', 'v. 掉下，落下 n. 〔液体的〕滴', 3075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'idea', 'n.  想法， 主意； 思想， 概念', 3076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kid', 'n. 小孩，儿童 v. (拿…)开玩笑', 3077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Yang', 'n.  阳', 3078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cold', 'adj. 冷的，寒冷的；冷淡的，冷酷的 n.  冷， 寒冷；', 3079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'life', 'n.  生命， 性命； 一生， 寿命； 生活， 生存； 人生； 生物； 生气， 活力', 3080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'we', 'pron.  我们', 3081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cola', 'n.  可乐饮料', 3082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'honey', 'n.  蜜， 蜂蜜； 甜蜜； 宝贝儿， 亲爱的', 3083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'normal', 'adj.  正常的， 平常的； 正规的， 规范的', 3084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wide', 'adv.  全部地， 充分地 adj. 宽阔的；广泛的；远离目标的，偏离的', 3085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'teach', 'v.  [taught-taught] 教， 讲授； 教导， 教训', 3086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'argue', 'v.  争论， 争吵， 争辩； 提出理由证明， 主张； 说服， 劝说', 3087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'stone', 'n.  石， 石头； 宝石； 果核', 3088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'succeed', 'v.  成功； 接着发生； 接在…后面； 接替， 继承', 3089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'specially', 'adv.  特意地， 专门地； 格外地， 特别地， 特殊地', 3090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'accessory', 'n.  附件， 零件， 配件； 装饰品', 3091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'gentleman', 'n.  有教养的人， 彬彬有礼的人； 先生， 男士', 3092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shampoo', 'n. 洗发剂；洗涤剂 vt.  用洗发剂洗头', 3093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yogurt', 'n.  酸奶， 酵母乳', 3094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'reach', 'v.  抵达； 达到； 延伸到； 伸出； 够到； 与…取得联系； 达成', 3095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'competition', 'n.  竞争； 比赛', 3096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'none', 'adv.  一点也不， 毫不， 毫无 pron. 没有一人，没有一点儿', 3097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'type', 'v.  打 n. 类型，种类；铅字', 3098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beyond', 'prep.  在…的那边； 远于； 迟于； 超出， 非…所及', 3099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pupil', 'n.  学生； 瞳孔', 3100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'problem', 'n.  问题， 疑难问题； 思考题， 讨论题', 3101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'road', 'n.  路， 道路； 途径', 3102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'review', 'n&v.  审查， 复查； 复习， 温习， 回顾； 评论； 检阅', 3103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sight', 'n. 视力，视觉；看见，瞥见；视域，眼界；情景，景象，奇观；', 3104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weather', 'n.  天气， 气候， 气象', 3105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'asleep', 'adj.  睡着的， 睡熟的', 3106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'between', 'prep.  在…之间； 介乎…之间', 3107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'method', 'n.  方法， 办法； 秩序， 条理', 3108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wife', 'n.  妻子', 3109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'come', 'v.  [came-come] 来， 来到； 达到， 至； 产生， 来； 变成； 实现； 开始；', 3110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'push', 'v.  推， 按； 推动， 推进； 催逼， 逼迫', 3111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nature', 'n.  大自然， 自然界； 本性， 性格， 性情； 性质， 类型', 3112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seventeen', 'num.  十七， 十七个', 3113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lift', 'v. 提，抬起 n.  电梯； 抬， 上升； 搭便车', 3114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'force', 'n. 军事行动，武力 v. 强制，逼迫，迫使', 3115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'scared', 'adj.  惊恐的， 恐惧的', 3116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flag', 'n.  旗， 旗帜； 标记', 3117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'south', 'adv. 向南方 adj.  南方的， 南部的， 来自南方的 n. 南，南部', 3118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'musician', 'n.  音乐家， 乐师', 3119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'night', 'n.  夜， 夜晚', 3120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'north', 'adv.  向北方 adj. 北方的，北部的；来自北方的 n. 北，北部', 3121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wear', 'v.  穿着， 戴着， 留； 面露， 面带， 呈现； 磨损， 用旧', 3122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'our', 'pron.  我们的', 3123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weak', 'adj.  虚弱的， 无力的； 弱的， 差的； 微', 3124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'out', 'adv.  出， 向外； 在外， 不在； 出', 3125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'overseas', 'adv. 在海外，在国外 adj.  海外的， 国外的，', 3126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rock', 'v.  摇， 摇动 n. 岩石，石块；摇滚乐', 3127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'impress', 'v.  给…深刻印象， 使铭记', 3128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'noon', 'n.  正午， 中午', 3129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'feature', 'n. 特征，特色；', 3130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flat', 'adj.  平的， 平坦的； 固定的， 统一的； 单调的， 沉闷的； 扁平的，', 3131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'get', 'v.  [got-gotten/got] 获得， 弄到； 收到； 变得； 拿来； 理解， 听到； 到达', 3132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dark', 'adj. 暗的，黑暗的；深色的，黑色的 n.  黑暗， 暗处； 暗色， 阴影', 3133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'course', 'n.  过程； 经过； 路线， 航线； 方针； 课程', 3134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'copy', 'v.  抄写； 复印； 抄袭； 模仿， 仿效 n. 复印件，副本；本，份', 3135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'place', 'n.  地方， 地点， 场所； 住所， 寓所； 地位； 资格； 名次， 等级', 3136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'regular', 'adj.  规则的； 有规律的， 定期的； 整齐的， 匀称的； 正规的， 正式的； 常规的，', 3137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dare', 'v. 敢，敢做', 3138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cook', 'v. 烹调，煮，烧 n.  厨师， 炊事员', 3139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sell', 'v.  [sold-sold] 卖， 出售； 推销', 3140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cool', 'adj. 凉的，凉快的；冷静的，从容的；冷淡的 v.  变凉， 冷却； 失去热', 3141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tired', 'adj.  疲劳的， 累的； 厌倦的， 厌烦的', 3142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'suggest', 'v.  建议， 提出； 使想起； 暗示', 3143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'leaf', 'n.  叶， 叶子； 张， 页； 薄金属片', 3144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'brain', 'n.  脑， 脑髓； 脑袋； 智慧', 3145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lead', 'n.  铅； 铅', 3146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'help', 'v. 帮助，援助；有助于，促进 n.  帮助， 援助； 帮手， 佣人； 救命', 3147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'expect', 'v.  预期； 指望， 盼望； 要求', 3148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'emotion', 'n.  感情； 激情； 情绪', 3149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'etiquette', 'n.  礼节， 礼仪', 3150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Chinese', 'adj.  中国的； 中国话的 n. 中国人；中国话，中文', 3151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'queue', 'v.  排队 n. 行列', 3152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'date', 'n.  日期， 日子； 时期， 年代； 约会， 约会的对象； 枣', 3153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'magic', 'adj.  有魔力的 n. 魔法，魔术；魔力，魅力', 3154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'impolite', 'adj.  不礼貌的， 粗鲁的', 3155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dress', 'v.  给…穿衣 n. 连衣裙；衣服，服装', 3156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'panda', 'n.  熊猫', 3157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'reveal', 'v.  揭露， 揭示； 泄露； 展现， 显示', 3158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'passage', 'n.  段落， 章节； 通道； 流逝， 推移', 3159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'onion', 'n.  洋葱， 洋葱类植物', 3160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sound', 'v.  发声， 发出响声； 测量…的深度， 探测； 听起来， 似 n. 声音，声响', 3161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'own', 'adj. 自己的 v.  有， 拥有', 3162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drum', 'n. 鼓 v. 击鼓，打鼓', 3163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sausage', 'n.  香肠， 腊肠', 3164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dozen', 'adj.  一打的 n. 打，十二个', 3165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'translate', 'v.  翻译', 3166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drug', 'n.  药， 药物； 麻醉药， 毒品', 3167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'negative', 'adj. 否定的；消极的；负的 n.  底片； 负数', 3168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'realistic', 'adj.  现实的； 现实主义的； 逼真的', 3169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twelfth', 'num. 第十二 n.  十二分之一', 3170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'monster', 'adj.  巨大的， 庞大的 n. 怪物；妖怪；巨人，巨兽，巨大的东西', 3171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plain', 'adj. 清晰的，明白的；相貌平平的，无姿色的；不矫饰的，朴素的 n.  平原', 3172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'should', 'modal verb. 应当，应该 〔用于提供或征求建议〕', 3173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'only', 'adv. 只，仅仅，才；不料，反而，结果却 adj.  唯一的， 仅有的； 最好的， 独一', 3174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'create', 'v.  创造； 创作； 引起， 产生', 3175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tag', 'n. 标签，标牌 v. 给…加上标签，给…挂上标牌', 3176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'blow', 'v. 〔风〕吹，刮 n. 打击', 3177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sunny', 'adj.  阳光充足的； 快活的', 3178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'notebook', 'n.  笔记本', 3179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'proud', 'adj.  骄傲的， 傲慢的； 自豪的， 得意的', 3180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'like', 'v. 喜欢；想要；希望，愿意', 3181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ugly', 'adj.  难看的， 丑陋的； 有敌意的', 3182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'earthquake', 'n.  地震', 3183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'towards', 'prep.  向， 朝， 面对； 接近', 3184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'person', 'n.  人', 3185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'safe', 'adj.  安全的， 平安的； 牢靠的， 可靠的； 谨慎的， 稳健的 n. 保险箱，保险柜', 3186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'send', 'v.  [sent-sent] 送， 寄； 派遣， 打发； 发送； 发射', 3187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'here', 'adv. 在这里，到这里；在这一点上 int.  嘿', 3188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'note', 'n.  短笺， 便条； 记录， 笔记； 注解； 音调， 音符', 3189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'everybody', 'pron.  每人， 人人， 各人', 3190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'week', 'n.  星期， 周', 3191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sail', 'v. 航行；驾驶；在…上航行 n.  帆； 航行', 3192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'purpose', 'n.  目的， 意图； 用途； 效果', 3193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'regret', 'n&v.  [regretted-regretted, regretting] 懊悔； 遗憾， 抱歉', 3194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'line', 'n.  线条， 界线； 条纹， 皱纹； 方针， 路线； 线路， 电话线； 线， 绳； 排， 行； 铁路', 3195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'snake', 'v.  蜿蜒； 弯弯曲曲地行进 n. 蛇', 3196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flee', 'v.  [fled-fled] 逃离， 逃跑', 3197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hero', 'n.  英雄， 勇士； 男主角， 男主人公', 3198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hers', 'pron.  她的', 3199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'can', 'modal verb. 能，会 n. 〔装食品或饮料的〕金属罐 v. 把…制成罐头', 3200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'award', 'v. 授予，给予；判给 n.  奖， 奖品； 报酬， 津贴', 3201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cap', 'v.  覆盖； 笼罩 n. 帽子，便帽；盖，罩，套', 3202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'organize', 'v.  组织， 安排； 使有条理； 使有机化', 3203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'car', 'n.  汽车， 轿车； 车厢', 3204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ready', 'adj.  准备好的， 现成的', 3205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'marriage', 'n.  结婚， 婚姻， 婚礼', 3206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cat', 'n.  猫； 猫科动物', 3207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'station', 'v.  安置； 派驻， 驻扎 n. 站，台，局；身份，地位', 3208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'disappointing', 'adj.  令人失望的， 令人扫兴的', 3209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'village', 'n.  乡村， 村庄', 3210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'player', 'n.  选手， 队员； 做游戏的人； 演员； 演奏者； 播', 3211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nose', 'v.  嗅出， 探出 n. 鼻子；鼻状物，前端突出部分', 3212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'balloon', 'n.  气球', 3213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cost', 'n. 费用；成本 v. 价格为；需支付〔某一数量的钱〕', 3214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'satisfy', 'v.  满足， 满意； 确信， 信服', 3215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'will', 'modal verb. 将，会，要〔用于构成将来时〕 n. 意志，毅力，决心 v. 设法用意志力驱使〔某事发生〕', 3216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'match', 'v.  和…相配， 和…相称 n. 比赛，竞赛；对手，敌手；匹配；火柴', 3217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'smoke', 'v.  冒烟， 冒气； 抽烟 n. 烟，烟尘；吸烟，抽烟', 3218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'follow', 'v. 跟随；接着；遵照，听从；听懂，领会 n.  跟随', 3219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'really', 'adv.  真正地， 实际上； 很， 十分， 全然', 3220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'clothes', 'n.  衣服， 服装； 被褥', 3221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'challenge', 'v.  向…挑战； 对…质疑； n. 挑战，艰巨任务；质疑，质询；邀请', 3222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wild', 'adj.  野生的， 未驯化的； 荒凉的， 荒芜的； 狂热的， 疯狂的； 野蛮的，', 3223);
