INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stairway', 'n. 楼梯', 9001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cape', 'n. 斗篷； 披肩；海角， 岬', 9002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delicate', 'adj. 纤弱的；精致的；微妙的； 灵敏的 A', 9003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fancy', 'adj. 花式的； 奇特的； 异样的 n. 爱好， 喜爱， 迷恋；想象， 设想 vt. 想象， 幻想', 9004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rebel', 'vi. 反抗， 反叛， 起义 n. 叛逆者， 起义者', 9005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bounce', 'v. 跳起， 弹起 n. 跳起， 弹回', 9006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'usage', 'n. 用法； 【语】惯用法', 9007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tissue', 'n. 组织；织物， 薄绢， 纸巾', 9008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loosen', 'v. 解开， 放松', 9009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rent', 'vt. 租， 租赁 n. 租金', 9010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carpenter', 'n. 木工， 木匠', 9011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Thanksgiving', 'n. 感恩节', 9012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proficiency', 'n. 熟练， 精通 <', 9013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'axe', 'n. 斧', 9014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cast', 'vt. 投， 扔， 掷， 抛；铸造 n. 演员表； 全体演员', 9015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hijack', 'vt. 劫持', 9016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'largely', 'adv. 主要地， 基本上；大量地， 大规模地', 9017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slice', 'n. 薄片， 切片 A；一份， 部分', 9018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frost', 'n. 霜， 霜冻； 严寒', 9019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'princess', 'n. 公主； 王妃', 9020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incline', 'v. 倾斜， 偏向；倾向于； 赞同 n. 斜坡， 斜面', 9021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cash', 'n. 现金， 现款 vt. 兑现， 付现款', 9022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elevate', 'vt. 抬起， 升高', 9023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'designate', 'vt. 指明； 指定', 9024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humiliate', 'vt. 使蒙羞， 使丢脸', 9025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'canvas', 'n. 帆布； 油画布；油画', 9026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'item', 'n. 条， 条款， 项目', 9027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gene', 'n. 基因 A', 9028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violet', 'n. 紫罗兰；紫罗兰色； 紫色', 9029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hollow', 'vi. 挖空， 凿空 adj. 空的， 中空的；空洞的， 空虚的', 9030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trunk', 'n. 大衣箱， 皮箱； 行李箱；树干； 躯干', 9031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'saving', 'adj. 节约的 n. 储蓄； 储蓄金， 存款', 9032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rely', 'vi. 依赖， 依靠；信赖， 信任', 9033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slide', 'v. 滑动， 滑行， 下滑 n. 滑动； 降低； 滑坡， 滑道；幻灯片', 9034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'style', 'n. 风格； 文体；式样， 类型', 9035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excessive', 'adj. 过多的， 过分的', 9036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flesh', 'n. 肉', 9037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jungle', 'n. 丛林， 密林；乱七八糟的一堆 A <', 9038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assault', 'n. /', 9039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cherry', 'n. 樱桃', 9040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feminine', 'adj. 女性的；娇柔的 A', 9041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pattern', 'v. 仿制， 模仿 n. 图案， 图样； 式样', 9042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heighten', 'v. 提高， 升高； 加强 A', 9043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harsh', 'adj. 严厉的， 刻薄的；粗糙的， 毛糙的；严酷的， 恶劣的；刺耳的； 刺目的', 9044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fireplace', 'n. 壁炉', 9045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vehicle', 'n. 车辆， 交通工具；媒介， 载体', 9046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scrape', 'v. 刮， 擦去；擦过； 勉强通过 n. 刮削， 刮削声；擦伤， 擦痕', 9047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bleak', 'adj. 荒凉的；没有希望的， 冷酷的', 9048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cushion', 'n. 垫子， 坐垫', 9049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glorious', 'adj. 壮丽的， 辉煌的；光荣的', 9050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plateau', 'n. 高原', 9051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'civilize', 'vt. 使文明， 教化', 9052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'architecture', 'n. 建筑；建筑学', 9053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stress', 'n. 压力；重音；【物】应力；强调， 重点， 着重 vt. 强调， 着重', 9054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mischief', 'n. 损害， 伤害， 危害；恶作剧， 捣蛋， 胡闹', 9055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reliance', 'n. 信赖， 依靠', 9056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'display', 'vt. 陈列， 展览；显示 n. 陈列； 展览； 展示', 9057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superfluous', 'adj. 过剩的， 多余的', 9058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conductor', 'n. 领队， 指挥；售票员， 列车员；导体， 导线', 9059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bore', 'v. 钻， 挖， 打眼， 钻探；烦扰， 使厌烦 n. 讨厌的人； 麻烦事', 9060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acrobat', 'n. 特技演员， 杂技演员', 9061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disorder', 'n. 混乱， 杂乱； 骚乱；【医】失调； 疾病', 9062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aggravate', 'vt. 使恶化， 加重， 加剧 <', 9063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dairy', 'n. 牛奶场； 奶店 <', 9064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transistor', 'n. 晶体管； 晶体管收音机', 9065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'giggle', 'n. /', 9066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persevere', 'vi. 坚持', 9067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mature', 'adj. 成熟的； 熟的； 成年人的 A v. 成熟', 9068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'navy', 'n. 海军', 9069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alleviate', 'vt. 减轻， 缓解； 缓和', 9070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'influence', 'n. 影响； 作用；势力， 权势 vt. 影响， 感化', 9071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'talent', 'n. 才能， 天资；人才', 9072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'percentage', 'n. 百分数， 百分率， 百分比', 9073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'negotiate', 'vi. 谈判， 交涉， 商议', 9074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violin', 'n. 小提琴', 9075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'package', 'n. 包装， 包裹， 箱', 9076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crisis', 'n. 危机； 紧要关头', 9077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'germ', 'n. 微生物； 细菌', 9078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shatter', 'vt. 使…粉碎； 使散开；使破灭； 使震惊', 9079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glamour', 'n. 魅力， 诱惑力', 9080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persuasion', 'n. 说服， 说服力', 9081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moss', 'n. 苔藓， 地衣', 9082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glimpse', 'n. /', 9083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detective', 'n. 侦探', 9084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transfer', 'vi. 换车；转业， 转学；调动， 转职 vt. 转移；转让， 过户 < n. 转变', 9085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'footstep', 'n. 脚步； 足迹', 9086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'veteran', 'adj. 经验丰富的 n. 老手； 老兵', 9087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'phrase', 'n. 短语， 词语， 习语', 9088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affection', 'n. 爱， 慈爱；感情；影响', 9089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nerve', 'n. 神经；勇气， 胆量', 9090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diversion', 'n. 转向， 转移 A', 9091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'omit', 'vt. 省略， 删去；遗漏， 忽略 <', 9092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'centimeter', 'n. 厘米', 9093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'erroneous', 'adj. 错误的， 不正确的', 9094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sponsor', 'n. 发起人； 主办者； 保证人 vt. 发起， 主办', 9095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limitation', 'n. 限制， 局限性', 9096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terrify', 'vt. 使害怕， 使惊恐', 9097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jog', 'n. 慢跑 A', 9098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ascertain', 'vt. 查明， 弄清， 确定', 9099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trolly', 'n. 手推车， 小车；〈英〉无轨电车； 〈美〉有轨电车', 9100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insert', 'vt. 插入， 嵌入', 9101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forbid', 'vt. 禁止， 不许', 9102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inspiration', 'n. 灵感；鼓舞， 激励', 9103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highlight', 'vt. 使显著， 使突出； 强调 n. 最精彩的部分； 最重要的事件', 9104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'database', 'n. 数据库', 9105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reject', 'vt. 拒绝； 抵制； 驳回；丢弃；排斥； 退掉', 9106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sheer', 'adj. 纯粹的； 十足的， 全然的；陡峭的， 险峻的', 9107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'miracle', 'n. 奇迹， 令人惊奇的人', 9108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compliment', 'n. 称赞； 恭维 vt. 称赞， 恭维', 9109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imitation', 'n. 模仿， 仿效；仿制； 仿造品', 9110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profit', 'v. 得利， 获益； 利用； 有利于 n. 利润， 收益；益处', 9111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amount', 'vi. 合计， 总共达；等于 n. 数量， 总额', 9112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comply', 'vi. 照做， 遵照， 应允', 9113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'original', 'adj. 最初的， 原始的； 原文的 <；新颖的， 有独创性的 n. 原物； 原作； 原文', 9114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nylon', 'n. 尼龙', 9115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deviate', 'vi. 背离， 偏离', 9116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'album', 'n. 粘贴簿； 集邮簿； 相册', 9117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assignment', 'n. 分配， 委派； 任务；作业', 9118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yawn', 'vi. 打呵欠 n. 呵欠', 9119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'saw', 'v. 锯， 锯开 n. 锯子； 锯床', 9120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feudal', 'adj. 封建的', 9121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kingdom', 'n. 王国； 领域', 9122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'differ', 'vi. 与…不同；与…意见不同', 9123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'puppet', 'n. 木偶； 傀儡', 9124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'latter', 'pron. 后者 adj. 后面的； 末尾的', 9125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affiliate', 'v. 隶属于 n. 附属机构， 分公司', 9126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equivalent', 'adj. 相等的， 等价的， 等值的  < n. 相等物， 等价物， 等值物； 对应词', 9127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'canoe', 'n. 独木舟， 小游艇', 9128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wedge', 'n. 楔， 楔形 vt. 楔牢， 楔入； 挤进', 9129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alienate', 'vt. 使疏远， 使格格不入；使不友好； 离间A', 9130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plague', 'n. 瘟疫； 祸患， 灾害', 9131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perpetual', 'adj. 永久的， 永恒的； 长期的 A', 9132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retrospect', 'n. 回顾， 回想', 9133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ban', 'vt. 取缔， 查禁； 禁止 n. 禁止， 禁令', 9134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fascinate', 'vt. 迷住， 强烈吸引', 9135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diplomatic', 'adj. 外交的， 从事外交的；有策略的， 有手腕的', 9136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suffer', 'vi. 受痛苦； 患病 vt. 遭受； 忍受， 忍耐 <', 9137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bar', 'n. 条， 杆， 棒， 棍， 闩；酒吧； 吧台；栅， 栏， 障碍 vt. 闩上； 阻拦， 拦住； 妨碍', 9138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bat', 'n. 球拍， 球棒； 短棒；蝙蝠', 9139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'projector', 'n. 放映机， 幻灯机， 投影仪', 9140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neighbourhood', 'n. 邻居； 四邻； 街道， 住宅区', 9141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'draft', 'n. 草稿， 草案， 草图 vt. 起草， 草拟', 9142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complex', 'adj. 复杂的；合成的， 综合的 n. 综合体', 9143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humidity', 'n. 湿气； 湿度', 9144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fluid', 'adj. 流动的； 液体的 < n. 流体， 液体', 9145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bay', 'n. 海湾， 湾', 9146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pamphlet', 'n. 小册子', 9147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'afterwards', 'adv. 后来， 以后', 9148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'artery', 'n. 【医】动脉；干线， 要道', 9149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underestimate', 'vt. 低估', 9150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plastic', 'adj. 塑料的， 塑胶的；可塑的， 塑性的 n. 塑料； 塑料制品 <', 9151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'globe', 'n. 球体， 地球仪；地球， 世界', 9152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transient', 'adj. 短暂的 <', 9153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enquiry', 'n. 打听， 询问；调查， 研究', 9154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'applause', 'n. 鼓掌； 欢呼', 9155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dean', 'n. 教长； 主持牧师 A；学院院长； 系主任； 训导主任', 9156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sponge', 'n. 海绵', 9157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abuse', 'vt. 滥用；虐待；谩骂 n. 滥用；虐待', 9158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insulate', 'v. 隔离， 孤立；使绝缘， 使绝热', 9159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scheme', 'v. 计划， 策划； 阴谋 n. 计划， 方案； 阴谋；配置； 安排', 9160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'affect', 'vt. 影响；感动， 感染', 9161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deaf', 'adj. 聋的；不愿听的', 9162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drain', 'v. 排去， 放干 n. 排水沟， 阴沟；流出； 消耗', 9163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amuse', 'vt. 逗…笑；给…以娱乐', 9164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'isolate', 'vt. 使隔离； 孤立', 9165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inward', 'adv. 向内， 在内 adj. 在内的， 里面的； 内心的 <', 9166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'responsibility', 'n. 责任， 责任心；职责， 任务', 9167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enquire', 'v. 询问；打听；问好， 问候', 9168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'civil', 'adj. 公民的， 市民的；国内的， 民间的；民用的；有礼貌的， 文明的', 9169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subsequent', 'adj. 随后的， 后来的 A', 9170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indicate', 'vt. 指出； 指示 A；表明或暗示…的可能性 A', 9171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contain', 'v. 包含； 容纳， 装有；等于， 相当于 A', 9172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'litter', 'v. 产 n. 垃圾；一窝 vt. 乱扔', 9173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sew', 'vi. 缝， 缝纫', 9174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oval', 'adj. 椭圆形的 n. 椭圆形', 9175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'column', 'n. 圆柱， 柱状物；列； 专栏', 9176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'biography', 'n. 传记', 9177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'procedure', 'n. 程序， 手续， 步骤', 9178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sample', 'n. 样品， 标本 vt. 抽样试验； 抽样调查', 9179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'integrate', 'v. 成为一体， 结合在一起， 合并 <', 9180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ultraviolet', 'adj. 紫外线的 n. 紫外线', 9181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'visa', 'n. 签证', 9182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diagnose', 'vt. 诊断', 9183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petition', 'n. 请愿书， 申请书 A <；诉状 vt. 请愿， 正式请求', 9184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'somewhat', 'adv. 稍微， 有点', 9185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vicinity', 'n. 邻近， 附近', 9186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'earnest', 'adj. 热心的； 诚挚的', 9187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jug', 'n. 大罐， 壶；一大罐的容量 vt. 关押', 9188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spider', 'n. 蜘蛛', 9189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precede', 'v. 领先， 在…之前； 优先， 先于 A', 9190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deck', 'n. 甲板', 9191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stroll', 'n. /', 9192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bowling', 'n. 保龄球运动', 9193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humorous', 'adj. 幽默的， 诙谐的', 9194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'differentiate', 'vi. 区分， 区别 vt. 不同', 9195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contact', 'vt. 接触， 联系， 交往 n. 接触， 联系， 交往', 9196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discharge', 'vi. 发射； 排出， 流出； 放 vt. 卸货；释放； 遣散， 解雇； 解除 <', 9197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prospective', 'adj. 未来的， 预期的； 可能的', 9198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plaster', 'n. 灰泥； 熟石膏； 膏药 <', 9199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grown-up', 'adj. 成长的； 成熟的； 成人的 n. 成年人', 9200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metropolitan', 'adj. 首都的；大都市的', 9201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'garbage', 'n. 垃圾', 9202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspicious', 'adj. 可疑的； 多疑的， 疑心的', 9203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complain', 'v. 抱怨； 申诉', 9204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zeal', 'n. 热情， 热忱', 9205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anxiety', 'n. 挂念； 焦虑， 忧虑 A；渴望， 热望', 9206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'renovate', 'vt. 更新， 修复', 9207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adjust', 'vi. 调整， 适应 vt. 调节， 调整 <；校正， 校准 <', 9208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vigorous', 'adj. 有力的； 朝气蓬勃的， 精力旺盛的', 9209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'debt', 'n. 债， 债务', 9210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deem', 'vt. 认为， 相信', 9211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compel', 'vt. 强迫， 迫使', 9212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capable', 'adj. 有能力的， 能…的', 9213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'depress', 'vt. 压抑； 降低； 削弱；使沮丧， 使抑郁', 9214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parade', 'vi. 列队行进， 游行 n. 游行； 检阅', 9215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'riddle', 'n. 谜， 谜语', 9216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salute', 'v. 敬礼； 向…致敬； 问候 n. 敬礼； 鸣礼炮；迎接， 欢迎', 9217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symposium', 'n. 讨论会， 专题报告会；专题论文集', 9218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lemon', 'n. 柠檬', 9219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'await', 'vt. 等候； 期待', 9220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'client', 'n. 顾客；委托人， 当事人', 9221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sin', 'vi. 犯罪 n. 罪， 罪恶', 9222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sip', 'v. 啜饮， 抿， 呷 A n. 小口喝， 一小口的量', 9223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lump', 'vi. 结块， 起小疙瘩 n. 团， 块 vt. 把…归并在一起', 9224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversion', 'n. 变换， 转化', 9225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ballot', 'v. 投票选举， 无记名投票 n. 投票表决； 无记名投票；选票', 9226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brilliant', 'adj. 光辉的， 灿烂的；卓越的， 有才华的', 9227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'historic', 'adj. 有历史意义的；历史的', 9228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oven', 'n. 炉， 灶， 烤箱', 9229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eyebrow', 'n. 眉毛', 9230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bound', 'vi. 跳 adj. 受约束的； 有义务的；注定的， 肯定的；准备到…去的， 开往…的 n. 跳', 9231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wreath', 'n. 花环， 花圈', 9232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stroke', 'n. 击， 敲； 报时的钟声 A；一击， 一划， 一笔；一次努力；中风 vt. 抚摸 A', 9233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'breed', 'vi. 繁殖， 生殖 vt. 造成， 引起；教养， 抚养；饲养 n. 品种， 种类 A', 9234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pyramid', 'n. 金字塔', 9235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'realm', 'n. 王国， 国土；领域', 9236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avoid', 'vt. 避免； 回避， 逃避 A', 9237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bid', 'vi. 报价， 投标 vt. 祝愿；命令， 吩咐 n. 出价， 投标', 9238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'astonish', 'vt. 使惊讶， 使吃惊', 9239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prompt', 'adj. 敏捷的； 迅速的；即刻的 vt. 激起；促进， 推动', 9240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comprehensive', 'adj. 全面的， 综合的', 9241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tunnel', 'n. 隧道； 山洞', 9242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elaborate', 'vi. 详细说明 adj. 精心制作的； 详尽的；复杂的 vt. 详细制定', 9243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corridor', 'n. 走廊； 狭长通道', 9244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expert', 'adj. 熟练的， 有经验的；专门的 n. 专家， 能手 <', 9245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'select', 'adj. 精选的， 选择的 A < vt. 选择， 挑选', 9246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fulfill', 'vt. 完成； 实现， 履行； 符合', 9247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advanced', 'adj. 高级的， 先进的； 前进的 <', 9248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bin', 'n. 大箱子', 9249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mechanical', 'adj. 机械的； 机械制的；机械的； 呆板的', 9250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slaughter', 'vt. 屠杀， 杀戮， 屠宰 n. 屠杀， 杀戮；屠宰', 9251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ski', 'vi. 滑雪 n. 雪橇', 9252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'output', 'n. 产量， 输出', 9253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maiden', 'adj. 首次的， 初次的 n. 少女， 未婚女子', 9254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fatigue', 'n. 疲劳', 9255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'striking', 'adj. 显著的， 惊人的', 9256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recognise', 'vt. 认出， 识别；承认', 9257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'majority', 'n. 多数， 大多数；【律】 成年', 9258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'costume', 'n. 戏装； 成套服装；服饰', 9259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crown', 'n. 王冠， 冕；君权； 君王 vt. 为…加冕', 9260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inquire', 'v. 询问；打听；问好， 问候', 9261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gymnasium', 'n. 体育馆， 健身房', 9262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'faithfully', 'adv. 忠诚地， 如实地', 9263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surface', 'n. 表面， 面； 外表', 9264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vain', 'adj. 徒劳的， 徒然的 <；自负的， 虚荣的 n. 徒劳， 白费', 9265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'youngster', 'n. 青年， 年轻人 A', 9266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lung', 'n. 肺', 9267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verdict', 'n. 裁定； 判断； 定论；意见', 9268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stereo', 'adj. 立体声的 n. 立体声', 9269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'defy', 'vt. 违抗， 反抗；蔑视', 9270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'doctrine', 'n. 教条， 主义， 学说', 9271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bacterium', 'n. 细菌', 9272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'judgement', 'n. 审判， 判决；判断力， 识别力； 看法， 意见', 9273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sly', 'adj. 狡猾的； 偷偷摸摸的', 9274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paragraph', 'n. 段， 节；小新闻， 短评', 9275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proportion', 'n. 比例；部分， 份儿；均衡， 相称', 9276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crystal', 'adj. 水晶的； 晶体的； 透明的 A < n. 水晶； 水晶饰品 <；结晶， 晶体', 9277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pursuit', 'n. 追赶； 追求；职业； 工作', 9278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prophet', 'n. 先知， 预言家', 9279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cycle', 'vi. 骑自行车；循环， 轮转 n. 自行车；周期； 循环', 9280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ruthless', 'adj. 残酷的， 无情的', 9281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lure', 'vt. 吸引， 诱惑 n. 诱惑物； 诱饵， 鱼饵', 9282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inquiry', 'n. 打听， 询问；调查， 研究', 9283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dissolve', 'vi. 解散； 取消 vt. 使溶解， 使融化', 9284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prejudice', 'v. 使抱偏见； 影响；损害 n. 偏见， 成见；损害， 侵害', 9285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'angle', 'n. 角；角度； 立场， 观点', 9286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clergy', 'n. 牧师， 圣职者， 神职人员', 9287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immigrant', 'adj. 移来的， 移民的 n. 移民， 侨民', 9288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tradition', 'n. 传统， 惯例', 9289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'urgent', 'adj. 急迫的， 紧迫的', 9290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bundle', 'n. 捆， 包， 束 A', 9291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thorn', 'n. 刺， 荆棘', 9292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'systematic', 'adj. 系统的， 有组织的', 9293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deceit', 'n. 欺骗， 谎言', 9294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cupboard', 'n. 碗柜， 小橱', 9295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'likewise', 'adv. 同样地， 照样地；又， 也， 而且', 9296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bacon', 'n. 咸肉， 熏肉', 9297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'married', 'adj. 已婚的， 夫妇的；与…结婚的； 密切结合在一起的', 9298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sigh', 'vi. 叹息， 叹气 n. 叹息， 叹息声', 9299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'constant', 'adj. 持续的， 不断的；永恒的， 不变的；坚定的， 忠实的 n. 常数， 恒量', 9300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sob', 'vi. 哭泣， 呜咽 n. 哭泣， 呜咽', 9301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mislead', 'vt. 把…带错路， 使误入歧途', 9302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intermittent', 'adj. 间歇的， 断断续续的', 9303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outrage', 'n. 暴行， 骇人听闻的事件；愤慨 vt. 激怒', 9304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diffuse', 'vi. 扩散 adj. 冗长的， 漫无边际的；四散的， 弥漫的 vt. 传播， 散布 <', 9305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scramble', 'vi. 攀登， 爬；争夺， 抢夺 vt. 扰乱， 搞乱 n. 攀登， 爬行；争夺， 抢夺', 9306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'split', 'v. 裂开， 劈开；分裂， 分离 n. 分化， 分裂； 裂口 A', 9307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contagious', 'adj. 传染性的， 会蔓延的', 9308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'immerse', 'vt. 使沉浸在， 使陷入；使浸没', 9309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'publication', 'n. 出版物；出版， 发行；公布， 发表', 9310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'champagne', 'n. 香槟酒', 9311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sow', 'vt. 播种', 9312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petroleum', 'n. 石油', 9313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kneel', 'vi. 跪， 下跪', 9314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preserve', 'vt. 保护， 维持 <；保存， 保藏；腌制 n. 专门领域', 9315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lever', 'n. 杆， 杠杆', 9316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'establish', 'vt. 建立， 设立；安置， 使定居', 9317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relevant', 'adj. 有关的， 相应的；适当的； 中肯的；实质性的； 有重大意义的', 9318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'synthetic', 'adj. 合成的， 人造的；综合的', 9319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proclaim', 'vt. 宣告， 声明 <', 9320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bunch', 'n. 一串， 一群， 一帮， 一伙', 9321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tense', 'adj. 拉紧的；紧张的 n. 时态', 9322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'candy', 'n. 糖果', 9323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'predominant', 'adj. 占优势的；主要的， 突出的', 9324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recipe', 'n. 烹饪法， 食谱；诀窍， 方法 <', 9325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decent', 'adj. 体面的， 像样的；正派的， 宽厚的', 9326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bow', 'vi. 鞠躬； 点头 n. 鞠躬； 点头', 9327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'racial', 'adj. 种的， 种族的', 9328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'switch', 'v. 转换；打开或关掉…的开关 n. 开关， 电闸；转换；枝条； 鞭子', 9329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'niece', 'n. 侄女； 外甥女', 9330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passerby', 'n. 过路人， 行人 A <', 9331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'auxiliary', 'adj. 辅助的， 补助的', 9332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'savage', 'adj. 野蛮的， 未开化的；凶恶的， 残暴的 n. 未开化的人， 野人', 9333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cripple', 'n. 跛子， 残疾人 A vt. 使跛， 使残疾', 9334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highly', 'adv. 高度地， 很， 非常；赞许地', 9335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zebra', 'n. 斑马 <', 9336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'console', 'vt. 安慰， 抚慰', 9337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'initiative', 'adj. 创始的； 起始的， 初步的 n. 第一步， 创始； 主动精神', 9338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'social', 'adj. 社会的 <；交际的', 9339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clockwise', 'adj. 顺时针方向的', 9340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lobby', 'n. 门廊， 门厅； 休息厅', 9341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acknowledge', 'vt. 承认；致谢， 报偿', 9342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pulse', 'n. 脉搏， 脉冲；意向， 动向； 情绪', 9343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overthrow', 'vt. 推翻， 颠覆 n. 推翻， 颠覆', 9344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heroine', 'n. 女英雄；女主角', 9345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inland', 'adv. 在国内； 在内地， 在内陆 adj. 国内的； 内地的， 内陆的', 9346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'worthwhile', 'adj. 值得的 A', 9347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mould', 'n. 模子， 铸型 vt. 浇铸， 造型； 塑造， 形成', 9348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stumble', 'vi. 跌， 绊；结结巴巴地说话 n. 跌， 绊', 9349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cunning', 'adj. 狡猾的， 狡诈的；精巧的， 巧妙的 n. 狡猾， 狡诈', 9350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stool', 'n. 凳子', 9351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specialty', 'n. 特产； 特色菜；专业； 专长', 9352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elbow', 'v. 用肘挤 n. 肘； 弯头 A', 9353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stoop', 'vi. 弯腰， 俯身 n. 弯腰， 曲背 A', 9354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vary', 'vi. 改变， 变化', 9355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coherent', 'adj. 黏着的， 黏附的；条理清楚的， 连贯的', 9356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'upper', 'adj. 较高的； 上面的；较高的； 上层的', 9357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'county', 'n. 郡， 县', 9358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intercourse', 'n. 交际， 往来 A', 9359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dwelling', 'n. 住宅， 寓所', 9360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infrared', 'adj. 红外线的 n. 红外线', 9361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'episode', 'n. 片断； 一集', 9362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'behalf', 'n. 利益', 9363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ponder', 'v. 思索， 考虑， 沉思', 9364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'objective', 'adj. 客观的， 真实的 n. 目标， 目的', 9365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'injure', 'vt. 损害， 损伤， 伤害 A', 9366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'guild', 'n. 协会， 行会', 9367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exert', 'vt. 尽； 施加<', 9368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scandal', 'n. 丑闻；恶意诽谤； 流言蜚语；反感， 愤慨', 9369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'composite', 'adj. 合成的， 复合的 n. 混合物， 合成物', 9370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hinder', 'vt. 阻止， 妨碍', 9371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horrible', 'adj. 令人恐怖的， 可怕的；极讨厌的， 使人不愉快的', 9372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'freelance', 'adj. 自由职业的', 9373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strengthen', 'v. 加强， 巩固', 9374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scent', 'n. 气味； 香味；香水', 9375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'injury', 'n. 损伤， 损害， 毁坏', 9376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exhibit', 'vt. 展出， 陈列', 9377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mushroom', 'n. 蘑菇', 9378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alcohol', 'n. 酒精， 乙醇', 9379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deny', 'vt. 否认， 否定；拒绝 <', 9380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trench', 'n. 沟， 沟渠', 9381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'miserable', 'adj. 痛苦的； 悲惨的', 9382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subtract', 'vt. 减', 9383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hurricane', 'n. 飓风', 9384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hike', 'vi. 徒步旅行 n. 徒步旅行；增加， 上升 vt. 提高', 9385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glory', 'n. 光荣， 荣誉； 荣耀的事', 9386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zigzag', 'adj. 之字形的 v. 成之字形， 曲折盘旋 A n. 之字形', 9387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secondary', 'adj. 次要的， 二级的；中级的； 第二的 A', 9388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'badge', 'n. 徽章', 9389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mission', 'n. 使命， 任务；使团， 代表团', 9390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'smuggle', 'vt. 走私； 偷运', 9391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sue', 'v. 控告， 对…提出诉讼， 起诉', 9392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'access', 'n. 接近， 进入； 接近的方法 A；入口； 通道', 9393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'primitive', 'adj. 原始的， 远古的， 早期的 <；粗糙的； 简单的', 9394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advisable', 'adj. 可取的； 明智的', 9395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dormitory', 'n. 宿舍', 9396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cooperate', 'vi. 合作， 协作， 相配合', 9397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overcome', 'vt. 战胜， 克服', 9398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sum', 'v. 合计， 总计 n. 总数， 和；金额；算术题', 9399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recite', 'v. 背诵； 朗诵', 9400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'current', 'adj. 当前的， 现在的 <；通用的， 流行的 n. 电流； 水流； 气流；潮流， 趋势', 9401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'audit', 'vt. 审计， 核对；旁听', 9402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'copper', 'n. 铜 <；铜币， 铜制器', 9403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'civilian', 'adj. 平民的； 民用的 < n. 平民', 9404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'audio', 'adj. 听觉的； 声音的', 9405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offensive', 'adj. 冒犯的， 攻击的； 讨厌的 < n. 攻势， 进攻', 9406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'texture', 'n. 质地， 纹理， 结构', 9407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slipper', 'n. 便鞋， 拖鞋', 9408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'launch', 'vt. 发射；使下水， 发动； 开展 n. 发射； 下水；新产品的投产或投放', 9409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amid', 'prep. 在…中间， 被…围绕', 9410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beloved', 'adj. 受爱戴的， 敬爱的 n. 爱人， 所爱的人', 9411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confirm', 'vt. 证实； 确认 <；批准； 确认； 巩固， 加强', 9412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bud', 'vi. 发芽， 萌芽 n. 芽， 花苞', 9413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cloak', 'n. 外套， 斗篷 vt. 掩盖， 蒙蔽', 9414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gallon', 'n. 加仑', 9415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bug', 'n. 臭虫 A；小毛病 A；窃听器 vt. 在…装窃听器', 9416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cricket', 'n. 板球；蟋蟀', 9417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gallop', 'vi. 奔驰， 飞跑 n. 奔驰， 飞跑', 9418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appoint', 'vt. 任命， 委任；约定， 指定', 9419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vast', 'adj. 巨大的； 辽阔的； 大量的；巨额的', 9420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intervene', 'vi. 插手， 干预， 调停；插入， 介入', 9421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ignite', 'v. 点火， 引燃', 9422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'symbol', 'n. 符号；标志， 象征', 9423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'declare', 'v. 宣布， 宣称；断言；公布， 发表， 披露', 9424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revelation', 'n. 揭示， 透露， 显示； 被揭示的真相； 新发现', 9425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'available', 'adj. 可用的， 可得到的；可以见到的， 随时可来的', 9426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advocate', 'n. 提倡者， 鼓吹者， 支持者 vt. 提倡， 鼓吹', 9427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confine', 'vt. 限制， 局限于；管制， 禁闭', 9428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quest', 'vi. 搜寻， 探求 n. 搜寻， 探求', 9429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frequency', 'n. 频率； 【物】周率', 9430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horizontal', 'adj. 地平线的；水平的', 9431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'luggage', 'n. 行李', 9432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drawback', 'n. 欠缺， 缺点', 9433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'missile', 'n. 导弹， 发射物', 9434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dynamic', 'adj. 动力的， 电动的；有生气的', 9435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sector', 'n. 部分； 部门；防御地段， 防区；扇形', 9436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passion', 'n. 热情， 激情； 酷爱；激怒， 大怒', 9437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generate', 'vt. 产生， 发生', 9438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extreme', 'adj. 末端的， 尽头的；极度的， 极端的 n. 极端， 极度', 9439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tuck', 'vt. 卷起； 塞进', 9440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coordinate', 'adj. 同等的； 并列的 A；坐标的 n. 坐标', 9441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'athlete', 'n. 运动员', 9442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'astronomy', 'n. 天文学', 9443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tube', 'n. 管， 软管；电子管， 显像管； 电视；地铁', 9444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'naval', 'adj. 海军的， 军舰的', 9445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dismay', 'n. 惊恐， 惊愕；失望， 绝望 vt. 使惊恐， 使惊愕；失望， 绝望', 9446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expend', 'vt. 消费， 花费', 9447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hint', 'v. 暗示， 示意 n. 暗示， 提示； 线索', 9448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'demonstrate', 'vt. 论证， 证实；展示， 说明 <', 9449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kid', 'v. 戏弄， 取笑 n. 小孩， 儿童', 9450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'throne', 'n. 王位， 君权', 9451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monument', 'n. 纪念碑， 纪念馆', 9452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inventory', 'n. 详细目录；存货清单， 物品清单， 库存物品', 9453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vivid', 'adj. 鲜艳的；生动的， 栩栩如生的', 9454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kin', 'n. 家属； 亲戚； 血缘关系 A；家族', 9455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flush', 'v. 冲洗； 使流 <；脸红 adj. 齐平的， 同高的 n. 脸红 A <', 9456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'manoeuvre', 'v. 演习；谨慎地运用技巧移动， 运动；熟练而巧妙地引导某人', 9457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kit', 'v. 装备 A n. 成套工具； 配套元件', 9458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'virtue', 'n. 美德， 德行；优点， 长处 A <', 9459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turnover', 'n. 翻倒， 翻转；人员调整；周转；成交量， 营业额', 9460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mortal', 'adj. 致命的；终有一死的 A；你死我活的， 不共戴天的 n. 凡人', 9461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gradual', 'adj. 逐渐的， 逐步的', 9462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brutal', 'adj. 残忍的；严峻的， 严酷的', 9463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preclude', 'vt. 妨碍， 阻止', 9464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corrupt', 'adj. 腐败的， 贪污的 vt. 使腐败， 使败坏 <', 9465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transmit', 'vt. 传播， 发射；传递； 传导', 9466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commemorate', 'vt. 纪念， 庆祝', 9467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consumption', 'n. 消费， 消耗 <', 9468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'technology', 'n. 工艺， 技术', 9469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'voltage', 'n. 电压', 9470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vaccine', 'n. 疫苗', 9471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drought', 'n. 旱灾， 干旱 A', 9472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'periodical', 'adj. 周期的， 定期的 n. 期刊， 杂志', 9473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leaflet', 'n. 小叶， 嫩叶；传单， 活页', 9474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'punctual', 'adj. 严守时刻的， 准时的， 正点的', 9475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advertise', 'v. 做广告', 9476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compromise', 'vi. 妥协， 折衷 < n. 妥协， 折衷', 9477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shampoo', 'n. 洗发膏， 香波；洗发， 洗头 vt. 洗发， 洗头', 9478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sack', 'n. 袋， 包， 麻袋 vt. 解雇', 9479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comparative', 'adj. 比较的， 相当的 <', 9480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fringe', 'n. 须边， 边缘 vt. 成为…的边缘', 9481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'react', 'vi. 作出反应， 回应 <；反对， 起反作用', 9482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feedback', 'n. 反馈', 9483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'justify', 'vt. 证明…是正当的， 认为有理', 9484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highjack', 'vt. 劫持', 9485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'roar', 'vi. 吼叫， 怒号 A；轰鸣； 咆哮', 9486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'timber', 'n. 木材， 木料；树林', 9487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'simulate', 'vt. 模仿， 模拟；假装， 冒充', 9488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inclusive', 'adj. 包括的， 包含的；范围广的', 9489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spectacle', 'n. 景象； 奇观', 9490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'efficiency', 'n. 效率， 功效', 9491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ethnic', 'adj. 种族的， 民族的', 9492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overhead', 'adv. 在头顶上， 在空中 adj. 在头顶上的； 架空的 A', 9493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comprehension', 'n. 理解， 领悟', 9494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intact', 'adj. 完整无缺的， 未经触动的， 未受损伤的', 9495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'following', 'adj. 接着的， 下列的', 9496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'juvenile', 'adj. 青少年的， 少年特有的； 幼稚的 n. 未成年人， 少年', 9497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sympathetic', 'adj. 同情的；共鸣的 <', 9498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'freight', 'n. 货物， 客货； 运费 <', 9499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'botany', 'n. 植物学', 9500);
