INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electrode', 'n. 顽皮雷弹', 1501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'difference', 'n. 差异；不同；争执', 1502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nauseous', 'adj. 令人作呕的；厌恶的', 1503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'protract', 'v. 绘制；延长；伸展', 1504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inebriate', 'v. 灌醉；使陶醉；使兴奋 adj. 酒醉的；醉醺醺的；陶醉的 n. 酒鬼；醉汉', 1505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'myopia', 'n. [眼科] 近视；目光短浅，缺乏远见', 1506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dour', 'adj. 严厉的；顽强的；阴沉的；不爱讲话的 n. (Dour)人名；(法)杜尔', 1507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'innovative', 'adj. 革新的，创新的；新颖的；有创新精神的', 1508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penumbra', 'n. 半影', 1509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'canon', 'n. 标准；教规；正典圣经；教士', 1510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volt', 'n. 伏特（电压单位）；环骑；闪避', 1511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tangible', 'adj. 有形的；切实的；可触摸的 n. 有形资产', 1512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stability', 'n. 稳定性；坚定，恒心', 1513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autopsy', 'n. 验尸；[病理][特医] 尸体解剖；[病理][特医] 尸体剖检', 1514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foreordain', 'v. 注定；预定命运', 1515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corpse', 'n. 尸体', 1516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'midpoint', 'n. 中点；正中央', 1517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quandary', 'n. 困惑；窘境；为难', 1518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transmit', 'v. 传输；传播；发射；传达；遗传', 1519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emit', 'v. 发出，放射；发行；发表', 1520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'atonement', 'n. 赎罪；补偿，弥补', 1521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'altar', 'n. 祭坛；圣坛；圣餐台', 1522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hoary', 'adj. 久远的，古老的；灰白的', 1523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'isothermal', 'adj. 等温的；等温线的 n. 等温线', 1524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corpulent', 'adj. 肥胖的', 1525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interrupt', 'v. 中断；打断；插嘴；妨碍 n. 中断', 1526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immediate', 'adj. 立即的；直接的；最接近的', 1527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complication', 'n. 并发症；复杂；复杂化；混乱', 1528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grandeur', 'n. 壮丽；庄严；宏伟', 1529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'altruist', 'n. 爱他主义者；利他主义者', 1530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'genetic', 'adj. 遗传的；基因的；起源的', 1531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'canny', 'adj. 精明的，谨慎的；节约的 n. (Canny)人名；(英)坎尼', 1532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'economical', 'adj. 经济的；节约的；合算的', 1533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wean', 'v. 使断奶；使断念；使放弃 n. （苏格兰）幼儿', 1534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'latest', 'adv. 最迟地；最后地 n. 最新的事物 adj. 最新的，最近的；最迟的，最后的', 1535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'altruism', 'n. 利他；利他主义', 1536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'munificence', 'n. 慷慨给与；宽宏大量', 1537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'curve', 'n. 曲线；弯曲；曲线球；曲线图表 v. 弯；使弯曲 adj. 弯曲的；曲线形的', 1538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonism', 'n. 对抗，敌对；对立；敌意', 1539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convoluted', 'adj. 复杂的；费解的；旋绕的 v. 盘绕；缠绕（convolute的过去分词）', 1540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polyglot', 'n. 通晓数种语言的人；用通晓数种语言记载的书 adj. 通数国语言，数国语言的', 1541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonist', 'n. 敌手；[解剖] 对抗肌；[生化] 拮抗物；反协同试剂', 1542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'opaque', 'adj. 不透明的；不传热的；迟钝的 n. 不透明物 vt. 使不透明；使不反光', 1543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'initiate', 'v. 开始，创始；发起；使初步了解 n. 开始；新加入者，接受初步知识者 adj. 新加入的；接受初步知识的', 1544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inexplicable', 'adj. 费解的；无法说明的；不能解释的', 1545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glucose', 'n. 葡萄糖；葡糖（等于dextrose）', 1546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perilous', 'adj. 危险的，冒险的', 1547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'soporific', 'n. 催眠剂；安眠药 adj. 催眠的；想睡的', 1548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingredient', 'n. 原料；要素；组成部分 adj. 构成组成部分的', 1549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pithy', 'adj. 有髓的，多髓的；精练的；简洁有力的', 1550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frugal', 'adj. 节俭的；朴素的；花钱少的', 1551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abbey', 'n. 大修道院，大寺院；修道院中全体修士或修女', 1552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refract', 'v. 使折射', 1553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disclose', 'v. 公开；揭露', 1554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comestibles', 'n. 食物 adj. 可吃的，可食的', 1555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undersell', 'v. 抛售；以低于市价售出', 1556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arrear', 'n. 欠款，逾期债款；待完成的工作', 1557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sumptuous', 'adj. 华丽的，豪华的；奢侈的', 1558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mendacious', 'adj. 虚假的；说谎的', 1559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gaiety', 'n. 快乐，兴高采烈；庆祝活动，喜庆；（服饰）华丽，艳丽', 1560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bisect', 'v. 平分；二等分', 1561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alcohol', 'n. 酒精，乙醇', 1562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'syndrome', 'n. [临床] 综合症状；并发症状；校验子；并发位', 1563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mediator', 'n. 调停者；传递者；中介物', 1564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radius', 'n. 半径，半径范围；[解剖] 桡骨；辐射光线；有效航程', 1565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invective', 'adj. 谩骂的；恶言的 n. 恶言漫骂', 1566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tonic', 'n. 补药；主调音或基音 adj. 滋补的；声调的；使精神振作的', 1567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loquacious', 'adj. 饶舌的，多话的', 1568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legacy', 'n. 遗赠，遗产', 1569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intrepid', 'adj. 无畏的；勇敢的；勇猛的', 1570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'egoism', 'n. 利己主义，自我主义', 1571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trestle', 'n. [交] 栈桥，高架桥；支架，搁凳', 1572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'switch', 'v. 转换；用鞭子等抽打 n. 开关；转换；鞭子', 1573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probation', 'n. 试用；缓刑；查验', 1574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bulwark', 'n. 壁垒；保障；防波堤 v. 保护；筑垒保卫', 1575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fluctuate', 'v. 波动；涨落；动摇', 1576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slothful', 'adj. 怠惰的，懒惰的；迟钝的', 1577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rectitude', 'n. 公正；诚实；清廉', 1578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gyrate', 'v. 旋转 adj. 旋涡状的', 1579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'zephyr', 'n. 和风；西风；轻薄织物', 1580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'furbish', 'v. 磨光；恢复；更新', 1581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artery', 'n. 动脉；干道；主流', 1582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equivocate', 'v. 说模棱两可的话；支吾， 躲闪；推诿；含糊其词', 1583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irreverent', 'adj. 不敬的，无礼的', 1584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedagogy', 'n. 教育；教育学；教授法', 1585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prelude', 'n. 前奏；序幕；前奏曲 v. 成为…的序幕；演奏…作为前奏曲', 1586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tedious', 'adj. 沉闷的；冗长乏味的', 1587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tarnish', 'n. 晦暗，无光泽；污点 v. 玷污；使……失去光泽；使……变灰暗', 1588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kernel', 'n. 核心，要点；[计] 内核；仁；麦粒，谷粒；精髓', 1589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'factual', 'adj. 事实的；真实的', 1590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'venial', 'adj. 可原谅的；（罪过）轻微的；可宽恕的', 1591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interrogate', 'v. 审问；质问；[计] 询问', 1592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endemic', 'adj. 地方性的；风土的 n. 地方病', 1593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'degree', 'n. 程度，等级；度；学位；阶层', 1594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verity', 'n. 真实；真理；事实；真实性', 1595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sonorous', 'adj. 响亮的；作响的；能发出响亮声音的', 1596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crystallization', 'n. 结晶化；具体化', 1597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bug', 'n. 臭虫，小虫；故障；窃听器 v. 烦扰，打扰；装窃听器', 1598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ratiocination', 'n. 推理；推论', 1599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monocracy', 'n. 独裁政治', 1600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reversible', 'adj. 可逆的；可撤消的；可反转的 n. 双面布料', 1601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beget', 'v. 产生；招致；引起；当…的父亲', 1602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'swift', 'n. 褐雨燕 adj. 快的；迅速的；敏捷的；立刻的 adv. 迅速地', 1603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inflammable', 'adj. 易燃的；易怒的；易激动的 n. 易燃物', 1604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hydrate', 'n. 水合物；氢氧化物 v. 使成水化合物', 1605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demur', 'v. 反对；抗辩；提出异议 n. 异议；反对', 1606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aroma', 'n. 芳香', 1607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incommodious', 'adj. 不便的；狭窄的', 1608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'latent', 'adj. 潜在的；潜伏的；隐藏的', 1609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'submission', 'n. 投降；提交（物）；服从；（向法官提出的）意见；谦恭', 1610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disguise', 'v. 掩饰；假装；隐瞒 n. 伪装；假装；用作伪装的东西', 1611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'geology', 'n. 地质学；地质情况', 1612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reproduce', 'v. 复制；再生；生殖；使…在脑海中重现', 1613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stratum', 'n. （组织的）层；[地质] 地层；社会阶层', 1614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regenerate', 'v. 使再生；革新 adj. 再生的；革新的', 1615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'engrave', 'v. 雕刻；铭记', 1616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epistolary', 'adj. 书信的；书信体的；用书信的', 1617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enterprise', 'n. 企业；事业；进取心；事业心', 1618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mollify', 'v. 平息，缓和；使…平静；使…变软', 1619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facetious', 'adj. 诙谐的；爱开玩笑的；滑稽的；(尤指在不合适的时候)开玩笑的', 1620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nutrition', 'n. 营养，营养学；营养品', 1621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cognitive', 'adj. 认知的，认识的', 1622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auspice', 'n. 赞助，主办；吉兆', 1623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outstretch', 'vt. 拉长；伸展得超出的范围', 1624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pitch', 'v. 倾斜；投掷；搭帐篷；坠落 n. 沥青；音高；程度；树脂；倾斜；投掷；球场', 1625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encumber', 'v. 阻塞；妨害；拖累', 1626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exposure', 'n. 暴露；曝光；揭露；陈列', 1627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'litmus', 'n. [试剂] 石蕊', 1628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'audacity', 'n. 大胆；厚颜无耻', 1629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'imbue', 'v. 灌输；使感染；使渗透', 1630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'armful', 'n. 一抱之量；双手合抱量', 1631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eject', 'v. 喷射；驱逐，逐出', 1632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hilarious', 'adj. 欢闹的；非常滑稽的；喜不自禁的', 1633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complement', 'n. 补语；余角；补足物 v. 补足，补助', 1634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recurrent', 'adj. 复发的；周期性的，经常发生的', 1635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immortal', 'adj. 不朽的；神仙的；长生的 n. 神仙；不朽人物', 1636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comprehend', 'v. 理解；包含；由…组成', 1637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predetermine', 'v. 预先确定；预先决定；预先查明', 1638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cramp', 'n. 痉挛，绞痛；[五金] 铁夹钳 v. 束缚，限制；使…抽筋；以铁箍扣紧 adj. 狭窄的；难解的；受限制的', 1639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'harbinger', 'n. 先驱；前兆；预告者 v. 预告；充做…的前驱', 1640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boycott', 'v. 联合抵制；拒绝参加 n. 联合抵制', 1641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aphorism', 'n. 格言；警句', 1642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rampart', 'n. 壁垒；垒；防御土墙 vt. 用壁垒围绕；防卫', 1643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'afoot', 'adj. 在进行中的；徒步的；准备中 adv. 在进行中，在准备中', 1644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bacterium', 'n. [微] 细菌；杆菌属', 1645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'potential', 'n. 潜能；可能性；[电] 电势 adj. 潜在的；可能的；势的', 1646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eschew', 'v. 避免；避开；远避', 1647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dogmatic', 'adj. 教条的；武断的', 1648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bombardier', 'n. 投弹手；炮兵下士', 1649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inheritance', 'n. 继承；遗传；遗产', 1650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pillage', 'v. 掠夺；抢劫 n. 掠夺；掠夺物', 1651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blunder', 'v. 跌跌撞撞地走；犯大错 n. 大错', 1652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'uproarious', 'adj. 骚动的；喧嚣的', 1653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'centiliter', 'n. [计量] 厘升，公勺', 1654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonize', 'v. 使…敌对；使…对抗；对…起反作用', 1655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homogeneity', 'n. 同质；同种；同次性（等于homogeneousness）', 1656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belittle', 'v. 轻视；贬低；使相形见小', 1657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'magnanimous', 'adj. 宽宏大量的；有雅量的；宽大的', 1658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abyss', 'n. 深渊；深邃，无底洞，地狱', 1659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belated', 'adj. 迟来的；误期的', 1660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kidney', 'n. [解剖] 肾脏；腰子；个性', 1661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fledgling', 'n. 无经验的人；刚会飞的幼鸟', 1662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monk', 'n. 僧侣，修道士；和尚', 1663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indomitable', 'adj. 不屈不挠的；不服输的；不气馁的', 1664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solemn', 'adj. 庄严的，严肃的；隆重的，郑重的', 1665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arrogant', 'adj. 自大的，傲慢的', 1666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'upheaval', 'n. 剧变；隆起；举起', 1667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'personality', 'n. 个性；品格；名人', 1668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rescind', 'v. 解除；废除；撤回', 1669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allude', 'v. 暗指，转弯抹角地说到；略为提及，顺便提到', 1670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sapiential', 'adj. 智慧的；明智的；赋予智慧的', 1671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mutilate', 'v. 切断，毁坏；使…残缺不全；使…支离破碎', 1672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ravage', 'v. 毁坏；破坏；掠夺 n. 蹂躏，破坏', 1673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prophetic', 'adj. 预言的，预示的；先知的', 1674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instant', 'adj. 立即的；紧急的；紧迫的 n. 瞬间；立即；片刻', 1675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'charlatan', 'n. 吹牛者；江湖医生 adj. 骗人的', 1676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wreak', 'v. 发泄；报仇；造成（巨大的破坏或伤害）', 1677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portfolio', 'n. 公文包；文件夹；证券投资组合；部长职务', 1678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cathartic', 'adj. 导泻的；通便的 n. [药] 泻药；[药] 通便药', 1679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wretch', 'n. 可怜的人，不幸的人；卑鄙的人', 1680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'image', 'n. 影像；想象；肖像；偶像 v. 想象；反映；象征；作…的像', 1681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'residual', 'n. 剩余；残渣 adj. 剩余的；残留的', 1682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eloquence', 'n. 口才；雄辩；雄辩术；修辞', 1683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'causal', 'adj. 因果关系的；有原因的 n. 表示原因的连词', 1684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transmission', 'n. 传动装置，[机] 变速器；传递；传送；播送', 1685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pragmatic', 'adj. 实际的；实用主义的；国事的', 1686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indecipherable', 'adj. 无法解释的；破译不出的；难辨认的', 1687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'explicit', 'adj. 明确的；清楚的；直率的；详述的', 1688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valor', 'n. 英勇；勇猛（等于valour）', 1689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vermicide', 'n. 杀蠕虫药；打虫药', 1690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'citadel', 'n. 城堡；大本营；避难处', 1691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adjutant', 'n. 副官，助手 adj. 辅助的', 1692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cadent', 'adj. 有节奏的；降落的', 1693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resolute', 'adj. 坚决的；果断的', 1694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hemoglobin', 'n. [生化] 血红蛋白（等于haemoglobin）；血红素', 1695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beck', 'n. 招手；点头；（英）小河', 1696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fatalism', 'n. 宿命论', 1697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immense', 'adj. 巨大的，广大的；无边无际的；非常好的', 1698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blithe', 'adj. 愉快的；快乐无忧的', 1699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'florid', 'adj. 绚丽的；气色好的', 1700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satisfy', 'v. 令人满意；令人满足', 1701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superior', 'adj. 上级的；优秀的，出众的；高傲的 n. 上级，长官；优胜者，高手；长者', 1702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'treatise', 'n. 论述；论文；专著', 1703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exclusive', 'adj. 独有的；排外的；专一的 n. 独家新闻；独家经营的项目；排外者', 1704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excellent', 'adj. 卓越的；极好的；杰出的', 1705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extensive', 'adj. 广泛的；大量的；广阔的', 1706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loot', 'n. 战利品；抢劫；掠夺品 v. 抢劫，洗劫；强夺', 1707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repute', 'n. 名誉；声望 v. 名誉；认为；把…称为', 1708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'battery', 'n. [电] 电池，蓄电池', 1709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loop', 'v. 打环；翻筋斗 n. 环；圈；弯曲部分；翻筋斗', 1710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'domain', 'n. 领域；域名；产业；地产', 1711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carrion', 'adj. 腐肉的；腐朽的 n. 腐肉；臭尸；不洁之物', 1712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'biennial', 'adj. 两年一次的 n. [植] 二年生植物', 1713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'postwar', 'adj. 战后的 n. 战后时期 adv. 战后；在战后', 1714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intruder', 'n. 侵入者；干扰者；妨碍者', 1715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'populace', 'n. 大众；平民；人口', 1716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monologue', 'n. 独白', 1717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'needy', 'adj. 贫困的；贫穷的；生活艰苦的 n. (Needy)人名；(英)尼迪', 1718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sheer', 'adj. 绝对的；透明的；峻峭的；纯粹的 adv. 完全；陡峭地 v. 偏航 n. 偏航；透明薄织物', 1719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intensive', 'adj. 加强的；集中的；透彻的；加强语气的 n. 加强器', 1720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'linear', 'adj. 线的，线型的；直线的，线状的；长度的', 1721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beau', 'n. 花花公子；喜修饰者；情郎 adj. 美的；好的', 1722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inhospitable', 'adj. 荒凉的；冷淡的，不好客的；不适居留的', 1723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suggestive', 'adj. 暗示的；提示的；影射的', 1724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affix', 'v. 粘上；署名；将罪责加之于 n. [语] 词缀；附加物', 1725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exceptional', 'adj. 异常的，例外的 n. 超常的学生', 1726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'opportune', 'adj. 适当的；恰好的；合时宜的', 1727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'molt', 'v. 脱毛；换毛 n. 换毛；脱皮；换毛期', 1728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'independent', 'adj. 独立的；单独的；无党派的；不受约束的 n. 独立自主者；无党派者', 1729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'succor', 'n. 救援；援助者 v. 救援；援助', 1730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'earthworm', 'n. [无脊椎] 蚯蚓', 1731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rightful', 'adj. 合法的；正当的；公正的；正直的', 1732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'murderous', 'adj. 杀人的，残忍的；凶残的；蓄意谋杀的', 1733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beam', 'n. 横梁；光线；电波；船宽；[计量] 秤杆 v. 发送；以梁支撑；用…照射；流露', 1734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pervert', 'v. 使堕落；滥用；使反常 n. 堕落者；行为反常者；性欲反常者；变态', 1735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'docile', 'adj. 温顺的，驯服的；容易教的', 1736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'waive', 'v. 放弃；搁置', 1737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deficient', 'adj. 不足的；有缺陷的；不充分的', 1738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'almanac', 'n. 年鉴；历书；年历', 1739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autocratic', 'adj. 专制的；独裁的，专横的', 1740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chilly', 'adj. 寒冷的；怕冷的 n. (Chilly)人名；(法)希伊', 1741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accusatory', 'adj. 非难的，指责的；控诉的，控告的', 1742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fungible', 'adj. 代替的；可取代的 n. 代替物', 1743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propriety', 'n. 适当；礼节；得体', 1744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endurance', 'n. 忍耐力；忍耐；持久；耐久', 1745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abominate', 'v. 痛恨；憎恶', 1746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caitiff', 'adj. 卑劣的；胆小的 n. 卑鄙的人；胆小鬼', 1747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'turgid', 'adj. 肿胀的；浮夸的；浮肿的', 1748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'twinge', 'n. 阵痛；悔恨 v. 使刺痛；使感到剧痛', 1749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'liberal', 'adj. 自由主义的；慷慨的；不拘泥的；宽大的 n. 自由主义者', 1750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comical', 'adj. 滑稽的，好笑的', 1751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dignity', 'n. 尊严；高贵', 1752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buoyant', 'adj. 轻快的；有浮力的；上涨的', 1753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compressible', 'adj. 可压缩的；可压榨的', 1754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ailment', 'n. 小病；不安', 1755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'asinine', 'adj. 驴的；愚蠢的，固执的；驴子似的', 1756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kleptomaniac', 'n. 有窃盗癖的人', 1757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stellar', 'adj. 星的；星球的；主要的；一流的', 1758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abbess', 'n. 女修道院院长；女庵主持', 1759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'befriend', 'v. 帮助；待人如友；扶助', 1760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sinuous', 'adj. 蜿蜒的；弯曲的；迂回的', 1761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lens', 'n. 透镜，镜头；眼睛中的水晶体；晶状体；隐形眼镜；汽车的灯玻璃 vt. 给……摄影', 1762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sanction', 'n. 制裁，处罚；认可；支持 v. 制裁，处罚；批准；鼓励', 1763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interim', 'adj. 临时的，暂时的；中间的；间歇的 n. 过渡时期，中间时期；暂定', 1764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cadaverous', 'adj. 尸体样的；惨白的', 1765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contemporary', 'n. 同时代的人；同时期的东西 adj. 当代的；同时代的；属于同一时期的', 1766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gestate', 'v. 使怀孕', 1767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arrogate', 'v. 冒称；霸占；没来由地将…归属于', 1768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'promulgate', 'v. 公布；传播；发表', 1769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'phase', 'n. 月相', 1770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enforce', 'v. 实施，执行；强迫，强制', 1771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'redress', 'v. 救济；赔偿；纠正；重新调整 n. 救济；赔偿；矫正', 1772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'depress', 'v. 压抑；使沮丧；使萧条', 1773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gall', 'n. 胆汁；五倍子；怨恨；苦味 v. 烦恼；屈辱；磨伤', 1774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'poise', 'n. 平衡；姿势；镇静 v. 使平衡；保持姿势', 1775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ornate', 'adj. 华丽的；装饰的；（文体）绚丽的', 1776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'angelic', 'adj. 天使的；似天使的；天国的', 1777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensation', 'n. 感觉；轰动；感动', 1778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nettle', 'v. 刺激；惹恼；用荨麻刺 n. 荨麻 adj. 荨麻科的', 1779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disparity', 'n. 不同；不一致；不等', 1780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frequency', 'n. 频率；频繁', 1781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'copious', 'adj. 丰富的；很多的；多产的', 1782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'milestone', 'n. 里程碑，划时代的事件', 1783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fidelity', 'n. 保真度；忠诚；精确；尽责', 1784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apex', 'n. 顶点；尖端', 1785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clemency', 'n. 仁慈；温和；宽厚', 1786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quaint', 'adj. 古雅的；奇怪的；离奇有趣的；做得很精巧的', 1787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'baton', 'n. 指挥棒；接力棒；警棍；司令棒', 1788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'termination', 'n. 结束，终止', 1789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'speed', 'v. 超速，加速；加速，迅速前行；兴隆 n. 速度，速率；迅速，快速；昌盛，繁荣', 1790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presentient', 'adj. 有预感的', 1791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instill', 'v. 徐徐滴入；逐渐灌输', 1792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indicant', 'adj. 指示的；表示的 n. 指示物', 1793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approximation', 'n. [数] 近似法；接近；[数] 近似值', 1794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'privilege', 'n. 特权；优待 v. 给与…特权；特免', 1795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inculpable', 'adj. 无辜的；无可非议的', 1796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accompany', 'v. 陪伴，伴随；伴奏', 1797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repulsion', 'n. 排斥；反驳；反感；厌恶', 1798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amend', 'v. 修改；改善，改进 n. (Amend)人名；(德、英)阿门德', 1799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'asperity', 'n. （表面的）粗糙；（气候等的）严酷；艰苦的条件；（性格）粗暴', 1800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recondite', 'adj. 深奥的；隐藏的；默默无闻的', 1801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abusive', 'adj. 辱骂的；滥用的；虐待的', 1802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temperate', 'adj. 温和的；适度的；有节制的', 1803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inscrutable', 'adj. 神秘的；不可理解的；不能预测的；不可思议的', 1804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probity', 'n. 廉洁；正直', 1805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'herbivorous', 'adj. [动] 食草的', 1806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'onset', 'n. 开始，着手；发作；攻击，进攻', 1807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ignition', 'n. 点火，点燃；着火，燃烧；点火开关，点火装置', 1808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sustainable', 'adj. 可以忍受的；足可支撑的；养得起的；可持续的', 1809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ultimate', 'adj. 最终的；极限的；根本的 n. 终极；根本；基本原则', 1810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ardent', 'adj. 热情的；热心的；激烈的；燃烧般的 n. (Ardent)人名；(法)阿尔当', 1811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'camouflage', 'n. 伪装，掩饰 v. 伪装，掩饰', 1812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inclusive', 'adj. 包括的，包含的', 1813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adherence', 'n. 坚持；依附；忠诚', 1814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'argumentation', 'n. 论证；争论；辩论', 1815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rouse', 'v. 唤醒；激起，使振奋；惊起 n. 觉醒；奋起', 1816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'realm', 'n. 领域，范围；王国', 1817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verbose', 'adj. 冗长的；啰嗦的', 1818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'feast', 'v. 享受；款待，宴请 n. 筵席，宴会；节日', 1819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'palatial', 'adj. 宫殿似的；宏伟的；壮丽的', 1820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'congest', 'v. 使充血；充塞', 1821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hospitable', 'adj. 热情友好的；（环境）舒适的', 1822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regime', 'n. 政权，政体；社会制度；管理体制', 1823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perforate', 'v. 穿孔于，打孔穿透；在…上打齿孔', 1824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abominable', 'adj. 讨厌的；令人憎恶的；糟透的', 1825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vilify', 'v. 诽谤；中伤；轻视；贬低', 1826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commitment', 'n. 承诺，保证；委托；承担义务；献身', 1827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disillusion', 'v. 使醒悟；使不再抱幻想 n. 幻灭；醒悟', 1828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endorse', 'v. 背书；认可；签署；赞同；在背面签名', 1829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neophyte', 'n. 新信徒；新入教者；初学者', 1830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transgress', 'v. 违反；侵犯；犯罪', 1831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inertia', 'n. [力] 惯性；惰性，迟钝；不活动', 1832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapacious', 'adj. 贪婪的；掠夺的', 1833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oppressive', 'adj. 压迫的；沉重的；压制性的；难以忍受的', 1834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approbation', 'n. 认可；赞许；批准', 1835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reputable', 'adj. 声誉好的；受尊敬的；卓越的', 1836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rampage', 'n. 暴怒；暴跳；乱闹 v. 狂暴；乱闹；发怒', 1837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generosity', 'n. 慷慨，大方；宽宏大量', 1838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accumulate', 'v. 累积；积聚', 1839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'listless', 'adj. 倦怠的；无精打采的；百无聊赖的', 1840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exterminate', 'v. 消灭；根除', 1841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probate', 'v. [法] 遗嘱认证；处以缓刑；加以监护；在遗嘱认证法庭证明…精神失常 n. 遗嘱检验；经认证的遗嘱；遗嘱认证法院管辖范围内的一切事项 adj. [法] 遗嘱认证的', 1842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sediment', 'n. 沉积；沉淀物', 1843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emancipation', 'n. 解放；释放', 1844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'necessity', 'n. 需要；必然性；必需品', 1845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'strait', 'adj. 狭窄的；苦恼的 n. 海峡；困境', 1846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'surround', 'v. 围绕；包围 n. 围绕物 adj. 环绕立体声的', 1847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utmost', 'n. 极限；最大可能 adj. 极度的；最远的', 1848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gluttonous', 'adj. 贪吃的，暴食的；饕餮的', 1849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parallelogram', 'n. 平行四边形', 1850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wrangle', 'n. 争论；吵嘴 v. 争论；争吵', 1851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gambol', 'v. 雀跃；耍闹 n. 雀跃；嬉戏', 1852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vegetarian', 'n. 素食者；食草动物 adj. 素食的', 1853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hypocritical', 'adj. 虚伪的；伪善的', 1854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outrageous', 'adj. 粗暴的；可恶的；令人吃惊的', 1855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crepuscular', 'adj. 黄昏的；朦胧的；拂晓的', 1856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vague', 'adj. 模糊的；含糊的；不明确的；暧昧的 n. (Vague)人名；(法)瓦格；(英)韦格', 1857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'catastrophe', 'n. 大灾难；大祸；惨败', 1858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portent', 'n. 前兆；预示；迹象；异常之物', 1859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malignant', 'adj. [医] 恶性的；有害的；有恶意的 n. 保王党员；怀恶意的人', 1860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'piecemeal', 'adv. 零碎地；逐个地 adj. 零碎的；逐渐的 n. 片；块 vt. 粉碎', 1861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'product', 'n. 产品；结果；[数] 乘积；作品', 1862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'idle', 'adj. 闲置的；懒惰的；停顿的 v. 无所事事；虚度；空转', 1863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plane', 'n. 飞机；平面；程度，水平 v. 刨；乘飞机旅行；翱翔 adj. 平的；平面的', 1864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hoard', 'v. 积聚钱财；贮藏货物 n. 贮藏物', 1865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auspicious', 'adj. 吉兆的，吉利的；幸运的', 1866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'archive', 'n. 档案馆；档案文件 v. 把…存档', 1867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evanescent', 'adj. 容易消散的；逐渐消失的；会凋零的', 1868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reveal', 'v. 显示；透露；揭露；泄露 n. 揭露；暴露；门侧，窗侧', 1869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auburn', 'n. 赤褐色 adj. 赤褐色的，赭色的', 1870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mingle', 'v. 混合；交往 n. (Mingle)人名；(加纳、英)明格尔', 1871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'technology', 'n. 技术；工艺；术语', 1872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insipid', 'adj. 清淡的；无趣的', 1873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'palette', 'n. 调色板；颜料', 1874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seditious', 'adj. 煽动性的；扰乱治安的；参与煽动的', 1875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hypnotic', 'adj. 催眠的，催眠术的；易于催眠的 n. 安眠药；催眠状态的人', 1876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temper', 'n. 脾气；（钢等）回火；性情；倾向 v. 使回火；锻炼；调和；使缓和', 1877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'versatile', 'adj. 多才多艺的；通用的，万能的；多面手的', 1878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pontiff', 'n. 主教，教皇；罗马教宗', 1879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instigate', 'v. 唆使；煽动；教唆；怂恿', 1880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eclectic', 'adj. 折衷的；选择的；折衷学派的 n. 折衷派的人；折衷主义者', 1881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'underscore', 'v. 强调；划线于…下 n. 底线，[计] 下划线', 1882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enmity', 'n. 敌意；憎恨', 1883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pristine', 'adj. 原始的，古时的；纯朴的', 1884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trait', 'n. 特性，特点；品质；少许', 1885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salamander', 'n. 火蜥蜴；蝾螈目动物；耐火的人；烤箱', 1886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'herbaceous', 'adj. 草本的；绿色的；叶状的', 1887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reiterate', 'v. 重申；反复地做', 1888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deplete', 'v. 耗尽，用尽；使衰竭，使空虚', 1889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stature', 'n. 身高，身材；（精神、道德等的）高度', 1890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abbreviate', 'v. 缩写，使省略；使简短', 1891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glance', 'n. 一瞥；一滑；闪光 v. 扫视，匆匆一看；反光；瞥闪，瞥见', 1892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'expulsion', 'n. 驱逐；开除', 1893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loophole', 'n. 漏洞；枪眼；换气孔；射弹孔', 1894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'understate', 'v. 少说，少报；保守地说；有意轻描淡写', 1895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remonstrate', 'v. 责备，告诫；抗议；表示异议', 1896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discrepant', 'adj. 有差异的；相差的；矛盾的', 1897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endure', 'v. 忍耐；容忍', 1898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hostility', 'n. 敌意；战争行动', 1899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amply', 'adv. 充足地；广大地 n. (Amply)人名；(俄)安普利', 1900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'euphonious', 'adj. 悦耳的', 1901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'levy', 'n. 征收；征兵，征税 v. 征收（税等）；征集（兵等）', 1902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fluctuation', 'n. 起伏，波动', 1903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precarious', 'adj. 危险的；不确定的', 1904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superstitious', 'adj. 迷信的；由迷信引起的', 1905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acrid', 'adj. 辛辣的；苦的；刻薄的', 1906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alteration', 'n. 修改，改变；变更', 1907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ado', 'n. 忙乱，纷扰，麻烦', 1908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'catastrophic', 'adj. 灾难的；悲惨的；灾难性的，毁灭性的', 1909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ethics', 'n. 伦理学；伦理观；道德标准', 1910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'theory', 'n. 理论；原理；学说；推测', 1911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insight', 'n. 洞察力；洞悉', 1912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dome', 'n. 圆屋顶 vi. 成圆顶状 vt. 加圆屋顶于…上', 1913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'add', 'v. 加；增加；加起来；做加法 n. 加法，加法运算', 1914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gibe', 'v. 嘲笑；愚弄 n. 嘲讽话', 1915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'microscope', 'n. 显微镜', 1916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'isochronous', 'adj. [物] 等时的；等步的', 1917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interchangeable', 'adj. 可互换的；可交换的；可交替的', 1918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'butane', 'n. [有化] 丁烷', 1919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nausea', 'n. 恶心，晕船；极端的憎恶', 1920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ample', 'adj. 丰富的；足够的；宽敞的 n. (Ample)人名；(西)安普尔', 1921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'semblance', 'n. 外貌；假装；类似', 1922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radiate', 'v. 辐射；传播；流露；发射；广播 adj. 辐射状的，有射线的', 1923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frustrate', 'v. 挫败；阻挠；使感到灰心 adj. 挫败的；无益的', 1924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'celebrate', 'v. 庆祝；举行；赞美；祝贺；宣告', 1925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'statute', 'n. [法] 法规；法令；条例', 1926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transcribe', 'v. 转录；抄写', 1927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'effectual', 'adj. 奏效的；会应验的；有法律效力的', 1928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deft', 'adj. 灵巧的；机敏的；敏捷熟练的', 1929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'potent', 'adj. 有效的；强有力的，有权势的；有说服力的', 1930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buffoonery', 'n. 滑稽；打诨', 1931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resource', 'n. 资源，财力；办法；智谋', 1932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'destructive', 'adj. 破坏的；毁灭性的；有害的，消极的', 1933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'yip', 'n. 叫喊声 v. 犬吠；尖叫', 1934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumspect', 'adj. 细心的，周到的；慎重的', 1935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insulate', 'v. 隔离，使孤立；使绝缘，使隔热', 1936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salvageable', 'adj. 可抢救的；可打捞的；可挽回的；能利用的', 1937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'congenital', 'adj. 先天的，天生的；天赋的', 1938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nimble', 'adj. 敏捷的；聪明的；敏感的', 1939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'painstaking', 'adj. 艰苦的；勤勉的；小心的 n. 辛苦；勤勉', 1940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intonation', 'n. 声调，语调；语音的抑扬', 1941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monition', 'n. 忠告；法庭传票；宗教法庭的诫谕', 1942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'place', 'n. 地方；住所；座位 v. 放置；任命；寄予', 1943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'castigate', 'v. 严惩；苛评；矫正；修订', 1944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'composed', 'adj. 镇静的；沉着的 v. 组成；作曲（compose的过去分词）；著作', 1945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jocund', 'adj. 快活的；高兴的', 1946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'untimely', 'adj. 不合时宜的；过早的 adv. 不合时宜地；过早地', 1947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'respite', 'n. 缓解；暂缓；暂时的休息；缓期执行 v. 使缓解；使暂缓；使延期；缓期执行', 1948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tantalize', 'v. 逗弄；使干着急', 1949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homeostasis', 'n. [生理] 体内平衡；[自] 内稳态', 1950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquaint', 'v. 使熟悉；使认识', 1951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tortuous', 'adj. 扭曲的，弯曲的；啰嗦的', 1952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hadron', 'n. [高能] 强子（参与强相互作用的基本粒子）', 1953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bristle', 'n. 猪鬃；刚毛 v. 发怒；竖起', 1954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abhorrent', 'adj. 可恶的；厌恶的；格格不入的', 1955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appease', 'v. 使平息；使满足；使和缓；对…让步', 1956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'digression', 'n. 离题；脱轨', 1957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indulgent', 'adj. 放纵的；宽容的；任性的', 1958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ownership', 'n. 所有权；物主身份', 1959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'descendent', 'adj. 派生的；降落的；世袭的 n. 后裔；派生物', 1960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disparage', 'v. 蔑视；毁谤', 1961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minuscule', 'n. 小写字；草写小字 adj. 极小的；用草写小字写的', 1962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fallible', 'adj. 易犯错误的；不可靠的', 1963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hypercritical', 'adj. 吹毛求疵的，苛评的', 1964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'zealous', 'adj. 热心的，热情的，积极的 n. (Zealous)人名；(英)泽勒斯', 1965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prescription', 'n. 药方；指示；惯例 adj. 凭处方方可购买的', 1966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apprehensible', 'adj. 可理解的，可了解的', 1967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irritate', 'v. 刺激，使兴奋；激怒', 1968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'havoc', 'n. 大破坏；浩劫；蹂躏 vt. 严重破坏 vi. 损毁', 1969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'centipede', 'n. [无脊椎][中医] 蜈蚣', 1970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'percipient', 'adj. 目光敏锐的；有洞察力的 n. 有感知力的人', 1971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shrivel', 'v. 枯萎；皱缩', 1972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'consummate', 'adj. 至上的；完美的；圆满的 v. 完成；作成；使达到极点', 1973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transgression', 'n. [地质] 海侵；犯罪；违反；逸出', 1974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'descry', 'v. 看见；发现；察看', 1975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demagoguery', 'n. 散布谣言；煽动行为；群众煽动', 1976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irrevocable', 'adj. 不可改变的；不能取消的；不能挽回的', 1977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'noxious', 'adj. 有害的；有毒的；败坏道德的；讨厌的', 1978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denote', 'v. 表示，指示', 1979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'induct', 'v. 引导；感应；使…就职；征召入伍', 1980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discourse', 'n. 论述；谈话；演讲 v. 演说；谈论；讲述', 1981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bipartisan', 'adj. 两党连立的；代表两党的', 1982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'procrastinate', 'v. 耽搁，延迟', 1983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facilitate', 'v. 促进；帮助；使容易', 1984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transcend', 'v. 胜过，超越', 1985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocal', 'adj. 歌唱的；声音的，有声的 n. 声乐作品；元音', 1986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epidermis', 'n. 上皮，表皮', 1987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'induce', 'v. 诱导；引起；引诱；感应', 1988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pare', 'v. 消减；削皮；剪；修掉（边等） n. (Pare)人名；(英)佩尔；(法)帕尔', 1989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deleterious', 'adj. 有毒的，有害的', 1990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambiguous', 'adj. 模糊不清的；引起歧义的', 1991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reasonable', 'adj. 合理的，公道的；通情达理的', 1992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'field', 'n. 领域；牧场；旷野；战场；运动场 v. 担任场外队员 adj. 扫描场；田赛的；野生的', 1993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'concoct', 'v. 捏造；混合而制；调合；图谋', 1994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slick', 'adj. 光滑的；华而不实的；聪明的；熟练的；老套的 n. [机] 平滑器；[机] 修光工具；通俗杂志 adv. 灵活地；聪明地 v. 使光滑；使漂亮', 1995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensibility', 'n. 情感；敏感性；感觉；识别力', 1996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'despicable', 'adj. 卑劣的；可鄙的', 1997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'braggadocio', 'n. 自夸，吹牛；吹牛大王', 1998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'string', 'n. 线，弦，细绳；一串，一行', 1999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plumb', 'v. 使垂直；探测，探索 n. 垂直；铅锤 adv. 恰恰，正；垂直地 adj. 垂直的', 2000);
