INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'minus', 'adj. 负的； 减的 prep. 减去 n. 负号； 减号', 7501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conservative', 'adj. 保守的， 守旧的 < n. 保守主义者', 7502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'belly', 'n. 肚子， 腹部', 7503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conference', 'n. 会议， 讨论会', 7504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'activity', 'n. 活动；活性； 活力', 7505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knob', 'n. 门把手， 把手； 旋钮', 7506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cabin', 'n. 客舱， 机舱；小屋', 7507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oppress', 'vt. 压迫， 压制', 7508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heel', 'n. 脚后跟； 鞋跟', 7509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'variety', 'n. 种种， 多种多样；种类， 品种 A', 7510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disturb', 'vt. 扰乱， 妨碍；使不安； 使烦恼', 7511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adore', 'vt. 崇拜， 敬慕； 爱慕', 7512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persist', 'vi. 坚持， 持续', 7513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pump', 'n. 泵 vt. 用泵抽运；给…打气', 7514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'caution', 'n. 小心， 谨慎 <；警告， 告诫 vt. 警告 <', 7515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pierce', 'vt. 刺穿， 刺破', 7516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'teenager', 'n. 青少年', 7517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apart', 'adv. 撇开； 分开， 分离；相距， 相隔', 7518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calendar', 'n. 日历， 月历', 7519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'badminton', 'n. 羽毛球', 7520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'closet', 'adj. 私下的； 隐蔽的 n. 橱， 壁橱 vt. 把…引进密室会谈', 7521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'speculate', 'v. 预测， 推断；投机', 7522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monster', 'n. 怪物， 妖怪 A', 7523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cement', 'n. 水泥， 胶泥 vt. 粘合；巩固， 加强', 7524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subway', 'n. 地下铁道， 地铁', 7525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dealer', 'n. 商人；〔尤指贵重物品的〕经销商', 7526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elastic', 'adj. 弹性的 n. 松紧带； 橡皮圈', 7527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acquaint', 'vt. 使认识， 使了解', 7528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assist', 'vt. 帮助， 协助', 7529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'censorship', 'n. 审查制度 <', 7530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'undergraduate', 'n. 大学生； 大学肄业生', 7531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commercial', 'adj. 商业的， 商务的， 贸易的 n. 广告', 7532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'joint', 'adj. 联合的， 共同的； 连接的 n. 接合处； 接头； 接缝；关节， 骨节', 7533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reasonable', 'adj. 合理的， 有道理的；通情达理的；适度的', 7534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'innumerable', 'adj. 无数的， 数不清的', 7535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trivial', 'adj. 琐碎的； 无足轻重的  <', 7536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lick', 'vt. 舔 n. 舔', 7537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'military', 'adj. 军事的， 军用的， 军队的 A', 7538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'satisfactory', 'adj. 令人满意的', 7539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reluctant', 'adj. 不愿的， 勉强的', 7540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wardrobe', 'n. 衣橱；全部衣物 A', 7541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conscientious', 'adj. 认真的， 勤勤恳恳的 A', 7542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coil', 'v. 卷， 盘绕 < n. 卷， 圈；线圈， 绕组', 7543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ensure', 'vt. 确保， 保证', 7544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'organism', 'n. 生物体， 有机体', 7545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'epidemic', 'adj. 流行性的； 传染的 n. 流行病； 传播', 7546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'upright', 'adv. 竖立着 adj. 垂直的， 直立的；正直的， 诚实的', 7547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remarkable', 'adj. 值得注意的； 显著的； 异常的； 非凡的 <', 7548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brake', 'v. 刹车 n. 制动， 闸， 刹车', 7549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chancellor', 'n. 大臣； 总理；首席法官；大学校长', 7550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opt', 'vi. 选择， 挑选', 7551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'extract', 'vt. 拔出， 抽出 <；摘录 n. 提炼物， 精华；摘录', 7552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obscure', 'adj. 暗的； 朦胧的；模糊的； 晦涩的 vt. 使暗， 使不明显', 7553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forge', 'vi. 稳步前进 A vt. 锻造；伪造 n. 锻工车间； 锻炉', 7554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'failure', 'n. 失败； 不及格 <；失败者 A；故障， 失灵；未能', 7555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solve', 'vt. 解决， 解答', 7556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knot', 'v. 打结 n. 结； 节； 群， 簇；节 <；难题， 疙瘩', 7557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'region', 'n. 地区， 区域， 范围', 7558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'organise', 'vt. 组织， 编组', 7559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deceive', 'vt. 欺骗， 蒙蔽 <', 7560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ingenious', 'adj. 有独创性的；心灵手巧的；精制的', 7561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'questionnaire', 'n. 问卷， 调查表， 征求意见表', 7562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'saucer', 'n. 茶托， 碟子', 7563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snack', 'n. 快餐； 小吃， 点心 <', 7564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'destination', 'n. 目的地， 终点', 7565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'privacy', 'n. 隐居；私事， 隐私', 7566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vertical', 'adj. 垂直的， 竖的 n. 垂线', 7567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reciprocal', 'adj. 相互的； 往复的； 互利的', 7568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'damp', 'adj. 有湿气的， 潮湿的', 7569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heir', 'n. 继承人', 7570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'screw', 'n. 螺旋， 螺丝 vt. 拧， 拧紧', 7571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gap', 'n. 间隙， 间隔； 分歧； 差距', 7572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gas', 'n. 气体； 煤气；汽油', 7573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emphasize', 'vt. 强调， 着重', 7574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slight', 'adj. 轻微的， 微小的；纤细的， 瘦弱的', 7575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ore', 'n. 矿石， 矿砂', 7576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'previous', 'adv. 在…之前 < adj. 早先的， 在前的', 7577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'regime', 'n. 政体， 制度', 7578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coke', 'n. 焦炭； 焦煤；可卡因', 7579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'argue', 'vi. 争论， 辩论 vt. 坚持， 主张；说服， 劝说', 7580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'damn', 'adj. 该死的 vt. 严厉地批评， 谴责', 7581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'daunt', 'vt. 使气馁， 使畏缩', 7582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superior', 'adj. 优良的， 卓越的；较…多的； 优于… n. 上级， 长官', 7583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'location', 'n. 位置， 场所', 7584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bankrupt', 'adj. 破产的', 7585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accessory', 'adj. 附属的 n. 附件， 配件', 7586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retort', 'vt. 反驳， 回嘴 n. 反驳， 回嘴', 7587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'antenna', 'n. 天线', 7588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torment', 'n. 痛苦， 折磨；令人痛苦的东西； 折磨者 vt. 折磨， 使痛苦；纠缠， 戏弄， 烦扰', 7589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'software', 'n. 软件', 7590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seminar', 'n. 研究班， 研讨会', 7591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fruitful', 'adj. 多产的， 果实累累的；富有成效的', 7592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dragon', 'n. 龙', 7593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hell', 'n. 地狱， 阴间；苦境， 极大痛苦', 7594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hazard', 'n. 危险； 冒险； 危害 vt. 冒险； 拼命', 7595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'depressed', 'adj. 沮丧的； 降低的', 7596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'voluntary', 'adj. 自愿的， 志愿的', 7597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'connection', 'n. 联系， 连接', 7598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'militant', 'adj. 好战的； 好斗的 n. 激进分子', 7599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proof', 'n. 证据， 证明；校样； 样张', 7600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'presence', 'n. 出席， 到场；存在， 在', 7601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'phase', 'n. 阶段， 状态， 时期；相， 相位', 7602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dilute', 'adj. 冲淡的， 稀释的 vt. 冲淡， 稀释', 7603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contract', 'vi. 缩小； 收缩；订 n. 契约， 合同； 包工', 7604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conclude', 'vt. 结束， 终止；断定， 下结论；缔结， 议定 <', 7605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profitable', 'adj. 有利可图的； 有益的', 7606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'misfortune', 'n. 不幸， 灾祸， 灾难 <', 7607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leather', 'n. 皮革， 皮革制品', 7608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shilling', 'n. 先令', 7609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'susceptible', 'adj. 易受感染的， 过敏的；易受影响的；能经受的； 有某种能力的', 7610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insight', 'n. 洞察力， 见识', 7611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instrumental', 'adj. 起作用的， 有帮助的；乐器的', 7612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revolutionary', 'adj. 革命的； 大变革的， 完全创新的 n. 革命者', 7613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fabric', 'n. 织物；结构', 7614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unemployment', 'n. 失业 <；失业人数', 7615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indoor', 'adj. 室内的， 户内的', 7616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'centigrade', 'adj. 摄氏温度计的； 百分度的 n. 摄氏温度计； 百分度', 7617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cope', 'vi. 竞争， 对抗；对付， 应付， 妥善处理', 7618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capacity', 'n. 容量， 容积； 接受力；能量， 能力', 7619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confess', 'v. 供认， 承认 <；坦白； 忏悔', 7620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ghost', 'n. 鬼魂， 幽灵', 7621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'saturate', 'vt. 使浸透， 渗透；使充满', 7622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'waterproof', 'adj. 防水的； 耐水的 <', 7623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precise', 'adj. 精确的， 准确的', 7624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barber', 'n. 理发师', 7625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sensible', 'adj. 明智的， 达理的；可觉察的， 觉察到的', 7626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'precious', 'adj. 珍贵的； 贵重的', 7627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pickup', 'n. 拾起， 获得', 7628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspect', 'vt. 疑心， 怀疑 n. 嫌疑犯； 可疑分子', 7629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abide', 'vi. 坚持， 遵守', 7630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contrive', 'vt. 设法做到；谋划， 策划 <', 7631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'massive', 'adj. 大而重的； 厚实的； 粗大的；大规模的， 大量的', 7632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'seaside', 'n. 海滨， 海边', 7633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mingle', 'vi. 混合起来， 相混合；相交往 vt. 使混合', 7634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superstition', 'n. 迷信， 迷信行为； 盲目的恐惧', 7635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'edible', 'adj. 可以吃的， 可食用的 <', 7636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chorus', 'n. 合唱队； 合唱 vt. 异口同声地说； 合唱', 7637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prone', 'adj. 平卧的， 俯卧的；易于做…的， 倾向于…的', 7638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'asset', 'n. 资产， 财产；优点； 有用的东西', 7639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'minimum', 'adj. 最小的， 最低的 n. 最小值， 最低限度 A', 7640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mathematical', 'adj. 数学的', 7641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magic', 'adj. 有魔力的； 魔术的 n. 魔法； 魔术， 戏法', 7642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reveal', 'vt. 展现， 显示；揭示， 揭露； 告诉， 泄露', 7643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'data', 'n. 资料，数据', 7644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'owl', 'n. 猫头鹰', 7645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'onion', 'n. 洋葱', 7646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harbor', 'n. 港口， 海港；避难所， 藏身处 vt. 隐匿； 窝藏， 包庇', 7647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drum', 'n. 鼓；圆桶', 7648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vibrate', 'v. 振动， 摇摆， 颤动', 7649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blog', 'n. 博客， 日志', 7650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'norm', 'n. 规范 A；准则', 7651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impetus', 'n. 推动， 促进', 7652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indignation', 'n. 愤怒， 愤慨', 7653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barrier', 'n. 栅栏， 屏障； 障碍', 7654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'realistic', 'adj. 现实的', 7655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'create', 'vt. 创造， 创作；引起， 造成； 建立', 7656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'criminal', 'adj. 犯罪的， 刑事的 n. 罪犯， 刑事犯', 7657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curious', 'adj. 好奇的； 稀奇的', 7658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resource', 'n. 办法， 智谋， 应变之才', 7659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nuisance', 'n. 讨厌的人；麻烦事', 7660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brace', 'vt. 使防备， 使受锻炼；支撑； 使绷紧 n. 托架， 支架', 7661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'earthquake', 'n. 地震', 7662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brisk', 'adj. 轻快的；刻薄的；生气勃勃的， 兴隆的', 7663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prestige', 'n. 威信， 威望', 7664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nightmare', 'n. 噩梦；无法摆脱的恐惧； 可怕的事', 7665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cord', 'n. 绳， 索', 7666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'startle', 'vt. 惊吓； 使吃惊', 7667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'core', 'n. 果核；中心， 核心 <', 7668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'council', 'n. 理事会， 委员会， 议事机构', 7669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fraud', 'n. 诈骗， 欺骗；骗子； 冒名顶替者', 7670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rectangle', 'n. 长方形， 矩形', 7671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'embassy', 'n. 大使馆', 7672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'repression', 'n. 压制， 压抑， 镇压', 7673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dash', 'vi. 冲； 猛冲， 突进 < n. 冲； 猛冲， 突进；破折号', 7674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concrete', 'adj. 具体的， 有形的， 实质性的 n. 混凝土 vt. 用混凝土修筑， 浇混凝土', 7675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'penalty', 'n. 处罚， 惩罚', 7676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'link', 'vt. 连接， 联系 n. 环节； 联系', 7677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exile', 'n. /', 7678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scale', 'v. 缩减， 缩小 n. 刻度， 标度；天平， 磅秤； 比例尺；规模；【音】音阶', 7679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vegetation', 'n. 植物， 草木 <', 7680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recovery', 'n. 痊愈； 复原；重获； 收复', 7681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quart', 'n. 夸脱', 7682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'security', 'n. 安全', 7683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limp', 'adj. 柔软的， 易曲的， 无力的 n. /', 7684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'organize', 'vt. 组织， 编组', 7685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salient', 'adj. 显著的， 突出的A', 7686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feeble', 'adj. 虚弱的， 无力的', 7687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'herb', 'n. 药草， 香草； 草本植物', 7688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continual', 'adj. 不断的， 连续的； 频繁的', 7689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'herd', 'n. 群， 兽群， 牛群 A vt. 放牧； 把…赶在一起', 7690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limb', 'n. 肢， 腿， 翼， 臂；大树枝', 7691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prose', 'n. 散文', 7692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inverse', 'adj. 倒转的， 反向的 n. 反面；倒数', 7693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confidence', 'n. 信任；信心， 自信；秘密， 机密 A', 7694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arbitrary', 'adj. 任意的， 专断的', 7695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fertilizer', 'n. 肥料', 7696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oath', 'n. 誓言， 誓约；咒骂， 诅咒语', 7697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emphasise', 'vt. 强调， 着重', 7698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'treaty', 'n. 条约', 7699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'challenge', 'n. 挑战； 艰巨任务 vt. 向…挑战', 7700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dignity', 'n. 庄严， 端庄；尊严， 高贵', 7701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ounce', 'n. 盎司， 英两', 7702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cosy', 'adj. 温暖而舒适的', 7703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emit', 'vt. 散发， 放射', 7704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intend', 'v. 想要； 打算， 企图', 7705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snap', 'vi. 咔嚓折断， 啪地绷断； 猛咬； 猛然断裂 <；吧嗒一声；厉声说话， 怒声责骂 adj. 仓促的， 突然的 vt. 给…拍快照 n. 吧嗒声；快照', 7706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'numerous', 'adj. 众多的， 许多的， 大批的 <', 7707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'govern', 'v. 统治， 管理；支配； 约束', 7708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analyse', 'vt. 分析； 分解', 7709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spacious', 'adj. 宽广的， 宽敞的， 广阔的', 7710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resemble', 'vt. 像， 类似', 7711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cafeteria', 'n. 自助餐厅', 7712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'remote', 'adj. 远的； 长久的 <；偏僻的；关系疏远的； 漠不关心的', 7713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kettle', 'n. 水壶', 7714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'virgin', 'adj. 未经开发的； 未经使用的 n. 处女， 未婚女子', 7715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fluctuate', 'vi. 波动， 起伏', 7716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compartment', 'n. 卧车包房， 隔间；分隔的空间', 7717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kidnap', 'vt. 绑架', 7718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calculate', 'v. 计算， 推算；计划， 打算', 7719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whatsoever', 'adv. 任何', 7720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'audience', 'n. 听众， 观众， 读者；谒见， 会见', 7721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possess', 'vt. 占有， 拥有', 7722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'neutral', 'adj. 中立的；中性的， 中和的', 7723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'optional', 'adj. 可以任选的， 非强制的', 7724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analysis', 'n. 分析， 分解', 7725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fashionable', 'adj. 流行的， 时髦的', 7726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'devise', 'vt. 设计， 想出， 发明 <', 7727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apparent', 'adj. 明显的， 显而易见的； 表面的， 貌似的', 7728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'journalist', 'n. 记者， 新闻工作者', 7729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exposure', 'n. 暴露， 揭露；受到', 7730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clutch', 'vt. 抓住， 攫住， 掌握 < n. 离合器', 7731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evacuate', 'vt. 疏散， 撤出；排空', 7732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wink', 'vi. 眨眼； 闪烁 n. 眨眼， 眨眼示意', 7733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grope', 'vi. 暗中摸； 探索， 搜寻， 搜索', 7734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humble', 'adj. 谦卑的， 恭顺的；低下的， 卑贱的； 粗陋的 vt. 降低； 贬抑', 7735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chapter', 'n. 章', 7736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harbour', 'n. 港口， 海港；避难所， 藏身处 vt. 隐匿； 窝藏， 包庇', 7737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commodity', 'n. 商品， 物品 <', 7738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carriage', 'n. 马车；客车厢', 7739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'independent', 'adj. 独立的， 自主的', 7740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obedient', 'adj. 服从的， 顺从的', 7741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'misery', 'n. 痛苦， 悲惨， 不幸', 7742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blur', 'v. 模糊； 涂污， 污损 n. 模糊不清的事物；污点', 7743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plausible', 'adj. 似乎合理的， 似乎可信的', 7744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'equator', 'n. 赤道', 7745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'headline', 'n. 大字标题； 头条新闻', 7746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'editorial', 'n. 社论', 7747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'committee', 'n. 委员会， 全体委员', 7748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'namely', 'adv. 即， 也就是', 7749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'union', 'n. 协会， 工会， 同盟；联合， 合并；一致， 融洽 <', 7750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plentiful', 'adj. 富裕的； 丰富的', 7751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subtle', 'adj. 精巧的， 巧妙的；细微的， 微妙的 <', 7752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'component', 'adj. 组成的， 合成的 n. 组成部分， 成分； 元件， 部件 A', 7753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suite', 'n. 套间；家具；套， 组， 系列', 7754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overwhelm', 'vt. 压倒， 制服', 7755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consultant', 'n. 会诊医师， 顾问医生；顾问', 7756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illustration', 'n. 说明， 例证；插图， 图解', 7757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arch', 'n. 拱门； 弓形结构； 桥拱洞 vt. 拱起， 使变成弓形', 7758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disguise', 'n. 假装， 伪装 vt. 假装， 伪装， 掩饰', 7759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imperial', 'adj. 帝国的， 帝王的；至尊的， 最高权力的；专横的； 傲慢的 A；英制的 <', 7760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wrap', 'vt. 裹， 缠， 卷， 包 n. 披肩； 围巾', 7761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'novel', 'adj. 新奇的， 新颖的 n. 小说', 7762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liberal', 'adj. 自由的， 思想开明的；丰富的， 富足的；慷慨的， 大方的', 7763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harmony', 'n. 协调， 和谐；融洽', 7764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cozy', 'adj. 温暖而舒适的', 7765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chill', 'n. 寒冷， 寒气， 寒战 vt. 使寒冷 <', 7766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dominate', 'v. 支配，统治，控制；占优势', 7767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imitate', 'vt. 模仿， 仿效；仿造， 伪造 <', 7768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compute', 'n. /', 7769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deadly', 'adj. 致命的， 致死的', 7770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'institution', 'n. 公共机构， 协会， 学校 <；制度； 惯例', 7771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pad', 'n. 垫， 衬垫；便笺簿； 拍纸簿 vt. 填塞', 7772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ambition', 'n. 雄心； 野心', 7773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exceed', 'vt. 超过， 胜过', 7774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enlarge', 'v. 扩大， 放大， 增大', 7775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avert', 'vt. 防止， 避免 A；转移', 7776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Christ', 'n. 基督， 救世主', 7777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pat', 'vt. 轻拍， 轻打； 抚摸 n. 轻拍， 轻打； 抚摸', 7778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shipment', 'n. 装船， 装运；装载的货物； 装货量', 7779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'horsepower', 'n. 马力', 7780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vicious', 'adj. 邪恶的， 恶毒的， 凶残的', 7781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lace', 'v. 系带， 扎带 n. 蕾丝， 花边；带子， 鞋带', 7782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invitation', 'n. 邀请， 招待；请柬', 7783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paw', 'n. 爪', 7784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moisture', 'n. 潮湿， 湿气， 湿度', 7785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enormous', 'adj. 巨大的， 庞大的', 7786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'toast', 'v. 烘， 烤；祝酒 n. 烤面包， 吐司；祝酒', 7787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'external', 'adj. 外部的， 外面的', 7788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circumstance', 'n. 情况，情形', 7789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vowel', 'n. 元音； 元音字母', 7790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revise', 'vt. 修订， 校订 <；修正， 修改', 7791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'authority', 'n. 权力； 威信； 权威；学术权威， 专家； 权威的典籍 A', 7792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creature', 'n. 人， 动物；产物', 7793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sociable', 'adj. 友善的， 友好的；好交际的， 合群的', 7794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'semiconductor', 'n. 半导体', 7795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obsolete', 'adj. 已废弃的， 过时的', 7796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instrument', 'n. 工具， 仪器， 器械 A；乐器', 7797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gasoline', 'n. 汽油', 7798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medium', 'adj. 中等的， 适中的 n. 中间； 适中；媒介物， 媒体； 传导体', 7799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interface', 'n. 界面； 分界面；接口', 7800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hormone', 'n. 激素， 荷尔蒙', 7801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wisdom', 'n. 智慧， 明智；名言， 格言', 7802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fatal', 'adj. 致命的； 毁灭性的', 7803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'psychology', 'n. 心理学；心理', 7804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ridge', 'n. 岭， 山脉；屋脊 A；鼻梁', 7805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'airline', 'n. 航线；航空公司', 7806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mobile', 'adj. 可动的， 活动的， 运动的', 7807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perform', 'v. 履行， 执行； 做；表演， 演出', 7808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evolution', 'n. 进化， 渐进， 演化', 7809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peak', 'adj. 高峰的； 最高的 n. 顶点， 最高点；峰， 山峰', 7810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'portrait', 'n. 肖像， 画像', 7811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complaint', 'n. 抱怨， 诉苦；申诉；疾病', 7812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inject', 'vt. 注射， 注入', 7813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'channel', 'v. 引导； 集中 n. 海峡， 水道；信道， 频道；途径， 渠道', 7814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'focus', 'vi. 聚集， 集中 A n. 焦点， 中心', 7815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invisible', 'adj. 看不见的； 无形的', 7816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hamper', 'vt. 妨碍， 阻碍； 牵制， 束缚', 7817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'favorable', 'adj. 赞许的； 有利的， 顺利的', 7818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entire', 'adj. 完全的， 全部的， 完整的', 7819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motel', 'n. 汽车旅馆', 7820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wrist', 'n. 腕， 腕关节', 7821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'approach', 'v. 靠近， 接近， 邻近 n. 方法， 途径；探讨； 试探', 7822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pea', 'n. 豌豆', 7823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'encyclopaedia', 'n. 百科全书', 7824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shopkeeper', 'n. 店主', 7825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decisive', 'adj. 决定性的', 7826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concise', 'adj. 简明的， 简洁的', 7827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thesis', 'n. 论文；论题； 论点', 7828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bump', 'v. 碰， 撞；颠簸着前进 n. 碰， 撞；隆起物', 7829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revive', 'v. 恢复； 复苏 <', 7830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'per', 'prep. 每；经， 由', 7831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wage', 'n. 工资， 报酬 vt. 进行， 开展', 7832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fiber', 'n. 纤维， 纤维质', 7833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proceed', 'vi. 进行， 继续下去； 发生', 7834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corporation', 'n. 公司， 企业； 团体 <', 7835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loyalty', 'n. 忠诚， 忠心', 7836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bulb', 'n. 灯泡； 球状物', 7837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dismiss', 'vt. 免职， 解雇， 开除； 解散', 7838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underlying', 'adj. 含蓄的； 潜在的； 根本的； 在下面的', 7839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intelligence', 'n. 智力， 才智； 灵性， 悟性；情报， 消息； 报道', 7840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analyze', 'vt. 分析； 分解', 7841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indication', 'n. 指出， 指示；迹象， 暗示', 7842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bulk', 'n. 体积， 容积；大批， 大量， 大块', 7843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'despair', 'vi. 对…绝望 n. 绝望', 7844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bull', 'n. 公牛', 7845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'champion', 'n. 冠军， 得胜者；拥护者； 勇士', 7846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gum', 'n. 树胶；口香糖', 7847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'queer', 'adj. 奇怪的， 异常的；不舒服的； 眩晕的', 7848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circuit', 'n. 周线； 巡回； 环行；电路， 线路', 7849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gut', 'adj. 本能的， 直觉的 n. 肠； 肠线 vt. 毁坏的内部；取出…的内脏', 7850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnificent', 'adj. 壮丽的， 宏伟的', 7851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'guy', 'n. 家伙， 伙计', 7852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'restrict', 'vt. 限制， 约束 <', 7853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'instant', 'adj. 立即的， 直接的；紧迫的；速溶的； 方便的 n. 瞬间， 时刻', 7854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peep', 'vi. 偷看， 窥视', 7855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peer', 'vi. 仔细看， 费力地看 n. 同龄人； 同等地位的人；贵族', 7856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persecute', 'vt. 迫害 <', 7857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'costly', 'adj. 昂贵的； 价值高的； 豪华的', 7858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'imperative', 'adj. 必要的； 紧急的， 极重要的；命令的 n. 必要的事， 必须完成的事；祈使语气 “', 7859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hitherto', 'adv. 到目前为止， 迄今 <', 7860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'documentary', 'adj. 文献的 n. 纪录片', 7861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violence', 'n. 暴力， 暴行；激烈， 猛烈', 7862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accordingly', 'adv. 因此， 从而；相应地， 照着', 7863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consequence', 'n. 结果， 后果， 影响；重要性', 7864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'robust', 'adj. 健壮的， 强壮的， 健康的', 7865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'linear', 'adj. 线的， 直线的 A；长度的；【数】线性的', 7866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dominant', 'adj. 支配的， 统治的；占优势的', 7867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'peel', 'vt. 削皮， 剥皮 n. 果皮', 7868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'denounce', 'vt. 公开指责， 抨击；告发某人', 7869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verge', 'v. 接近， 濒临 n. 边， 边缘', 7870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'framework', 'n. 构架， 框架， 结构', 7871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irrespective', 'adj. 不顾的， 不考虑的 <', 7872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entity', 'n. 实体； 事物的存在', 7873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tide', 'n. 潮， 潮汐；潮流， 趋势', 7874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prohibit', 'vt. 禁止， 阻止， 不准 <；使不可能', 7875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'franchise', 'n. 特许权；选举权；经销权 vt. 特许', 7876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'steward', 'n. 乘务员', 7877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arrow', 'n. 箭； 箭头， 箭状物', 7878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reign', 'vi. 统治， 支配；盛行； 占优势 n. 统治， 支配； 统治时期； 朝代', 7879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tempo', 'n. 节奏， 速度； 行进速度', 7880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'descendant', 'n. 子孙， 后代', 7881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'manner', 'n. 方式， 方法；举止；风俗', 7882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foresee', 'vt. 预见， 预知 <', 7883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'associate', 'vi. 交往， 结合 adj. 副的 vt. 使联系， 使联合 n. 合作人， 伙伴， 同事， 同行', 7884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'kidney', 'n. 肾， 肾脏', 7885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'judgment', 'n. 审判， 判决；判断力， 识别力； 看法， 意见', 7886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'charity', 'n. 慈善， 仁慈， 施舍 <', 7887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stationery', 'n. 文具', 7888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pit', 'n. 坑， 陷阱；煤矿， 矿井', 7889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sneak', 'v. 偷偷地走， 溜， 潜行；偷偷地做 A', 7890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stock', 'n. 备料， 库存， 现货；股票； 公债 vt. 储存', 7891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspend', 'vt. 吊， 悬挂；推迟； 暂停', 7892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'terror', 'n. 恐怖；可怕的人', 7893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beneath', 'adv. 在下方 A prep. 在…下边， 在…之下', 7894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heroin', 'n. 海洛因', 7895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'void', 'adj. 空的， 空虚的；没有的， 缺乏的；无效的', 7896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ritual', 'adj. 作为仪式一部分的；例行的 A n. 典礼， 仪式；例行公事， 老规矩', 7897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surge', 'vi. 汹涌， 奔腾， 波动； 蜂拥而出 n. 洋溢， 奔放；急剧上升， 猛增；浪涛般汹涌奔腾 A', 7898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liability', 'n. 责任， 义务', 7899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'swan', 'n. 天鹅', 7900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'heroic', 'adj. 英雄的， 英勇的', 7901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sway', 'v. 摇摆， 摇动', 7902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tick', 'v. 滴答响；标以记号 n. 滴答声；勾号', 7903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basis', 'n. 基础； 根据', 7904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resolute', 'adj. 坚决的， 果断的', 7905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tutor', 'n. 家庭教师， 指导教师 vt. 个别指导', 7906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'senator', 'n. 参议员 <', 7907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reconcile', 'vt. 使和好， 调解， 使调和；使一致 A', 7908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quantify', 'vt. 确定数量， 量化 <', 7909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tempt', 'vt. 诱惑， 引诱；吸引， 使感兴趣', 7910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ethic', 'n. 道德准则， 行为准则， 伦理标准；', 7911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gym', 'n. 体育馆， 健身房', 7912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'governor', 'n. 总督， 州长， 地方长官', 7913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rarely', 'adv. 很少， 难得； 稀有地', 7914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evil', 'adj. 邪恶的， 罪恶的 < n. 邪恶， 罪恶', 7915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'twist', 'vi. 捻， 搓； 绞， 拧 A vt. 歪曲， 曲解 n. 搓， 拧 A <；新手法， 窍门', 7916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forthcoming', 'adj. 即将到来的', 7917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'perplex', 'vt. 使困惑； 使费解； 使复杂化', 7918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'locate', 'vt. 查找…的位置；使…坐落于， 位于', 7919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abdomen', 'n. 腹部', 7920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'combat', 'v. 战斗， 搏斗， 格斗 n. 战斗， 搏斗， 格斗', 7921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'despise', 'vt. 轻视， 蔑视', 7922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dioxide', 'n. 二氧化物', 7923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indulge', 'vt. 沉溺， 纵容自己， 肆意从事；允许延期付款', 7924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'unity', 'n. 团结， 一致；统一体， 整体', 7925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pursue', 'vt. 追赶， 追踪；继续， 从事 <', 7926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genetics', 'n. 遗传学', 7927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vulgar', 'adj. 粗野的， 下流的；庸俗的， 粗俗的；普通的， 通俗的', 7928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'catastrophe', 'n. 突如其来的大灾难', 7929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convey', 'vt. 运送， 搬运， 转运；表达； 传播', 7930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'redeem', 'vt. 赎回；挽回；救赎', 7931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'victim', 'n. 牺牲品； 受害者', 7932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skull', 'n. 颅骨， 脑壳', 7933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hysterical', 'adj. 情绪异常激动的， 歇斯底里的 A', 7934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contaminate', 'vt. 弄脏， 污染', 7935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lane', 'n. 小路， 小巷； 行车道', 7936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'garlic', 'n. 大蒜， 蒜头', 7937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aircraft', 'n. 飞行器； 航空器； 飞机', 7938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accord', 'vi. 相符合， 相一致 n. 一致， 符合；协议， 条约 vt. 授予， 赠与', 7939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'automatic', 'adj. 自动的； 机械的； 无意识的 n. 自动机械', 7940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foremost', 'adv. 首先， 第一 adj. 最重要的', 7941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'despite', 'prep. 不管， 尽管 <', 7942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consecutive', 'adj. 连续不断的， 连贯的', 7943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'groan', 'vi. 呻吟 n. 呻吟', 7944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merchandise', 'n. 商品， 货物', 7945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pebble', 'n. 卵石', 7946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'encyclopedia', 'n. 百科全书', 7947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jewellery', 'n. 珠宝', 7948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conduct', 'n. 行为， 举动， 品行；引导， 实施 vt. 引导， 带领；处理， 实施， 管理；传导， 传；指挥', 7949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'velvet', 'adj. 丝绒制的， 柔软的 n. 丝绒， 天鹅绒', 7950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lamb', 'n. 羔羊， 小羊；羔羊肉', 7951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fantastic', 'adj. 奇异的， 幻想的， 异想天开的；极好的', 7952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tidy', 'adj. 整洁的， 整齐的 v. 使整齐； 整理， 收拾', 7953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lame', 'adj. 跛的； 站不住脚的； 有缺陷的', 7954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apparatus', 'n. 器械， 设备， 仪器， 装置', 7955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decay', 'vi. 衰减， 衰退 vt. 使腐朽， 腐烂 n. 腐朽， 腐烂；衰减， 衰退', 7956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grieve', 'vt. 使悲伤， 使伤心', 7957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fracture', 'v. 断裂， 折断 n. 裂缝， 裂痕；骨折', 7958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liberty', 'n. 自由', 7959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recycle', 'vt. 回收利用， 再应用', 7960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'civilisation', 'n. 文明， 文化', 7961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drift', 'vi. 漂， 漂流 n. 漂， 漂流', 7962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'confidential', 'adj. 秘密的， 机密的；亲信的', 7963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chaos', 'n. 混乱， 杂乱的一团', 7964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mankind', 'n. 人类 A', 7965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abundant', 'adj. 丰富的， 充分的， 充裕的', 7966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mute', 'adj. 哑的； 缄默的；弱化的， 微弱的 n. 哑巴；弱音器 vt. 减弱…的声音', 7967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forecast', 'vt. 预测， 预报 n. 预测， 预报', 7968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deteriorate', 'vi. 恶化， 变坏', 7969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uncover', 'vt. 揭开， 揭露', 7970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'warehouse', 'n. 仓库， 货栈 <', 7971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recognize', 'vt. 认出， 识别；承认', 7972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'input', 'n. 输入 vt. 输入', 7973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'induce', 'vt. 引诱， 劝使；引起， 导致', 7974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'abnormal', 'adj. 反常的， 不正常的', 7975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'volt', 'n. 伏特', 7976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reality', 'n. 现实， 实际；真实', 7977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shrewd', 'adj. 机灵的， 敏锐的；精明的', 7978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'offend', 'vi. 冒犯， 触犯， 得罪 vt. 使不快， 使恼火', 7979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'molecule', 'n. 分子', 7980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memorandum', 'n. 备忘录', 7981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resign', 'v. 辞去， 辞职', 7982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'safeguard', 'vt. 保护； 维护， 捍卫 n. 防护装置； 预防措施', 7983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diligent', 'adj. 勤奋的， 用功的 A', 7984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sophisticated', 'adj. 尖端的， 复杂的， 先进的 <；老练的， 老于世故的', 7985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sunrise', 'n. 日出', 7986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aluminum', 'n. 铝', 7987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ward', 'v. 保护， 守卫 n. 病房；行政区；受监护人', 7988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indicative', 'adj. 指示的， 暗示的', 7989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scrutiny', 'n. 仔细观察， 详细审查；监督 A', 7990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chase', 'v. 追逐； 追求 n. 追逐； 追求', 7991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marine', 'adj. 海的， 海生的；船舶的； 航海的', 7992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pop', 'adj. 流行的， 通俗的 < v. 突然出现， 发生A n. 砰的一声', 7993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'summarise', 'v. 概括， 总结', 7994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'routine', 'adj. 常规的， 例行的 n. 例行公事， 常规', 7995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tariff', 'n. 关税， 税率；价目表， 收费表', 7996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'currency', 'n. 货币； 通货', 7997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'canal', 'n. 运河； 渠', 7998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convict', 'vt. 证明…有罪， 宣判…有罪 n. 囚犯', 7999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'retention', 'n. 保留， 保持', 8000);
