INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cohesive', 'adj.  黏着的； 使凝结的， 使内聚的', 9501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'battery', 'n.  电池； 排炮； 一系列， 一批', 9502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clay', 'n.  泥土， 黏土', 9503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irreverent', 'adj.  不敬的', 9504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'promote', 'vt.  促进； 提升； 宣传， 推销', 9505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'façade', 'n.  正面； 表面', 9506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'divorce', 'v.  与…离婚； 使分离， 使脱离 n. 离婚；分离，脱离', 9507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distribute', 'vt.  分配， 分发； 散布', 9508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attach', 'vt.  连接； 依附于； 系， 贴， 连接； 使依恋， 使喜爱 ； 认为有', 9509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cornerstone', 'n.  墙角石， 奠基石； 基础', 9510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quiz', 'n. 小测验；智力竞赛 vt.  测验； 盘问， 查问， 询问', 9511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inclination', 'n.  爱好， 意愿； 趋向， 趋势； 倾斜度', 9512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'participate', 'vi.  参与， 参加', 9513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ingredient', 'n.  成分， 要素； 原料', 9514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consolidate', 'v.  巩固； 合并', 9515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biochemical', 'adj.  生物化学的， 生化的', 9516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'librarian', 'n.  图书馆馆长； 图书管理员', 9517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contour', 'n.  等高线； 轮廓', 9518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lyric', 'adj. 抒情的 n. 抒情诗；', 9519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suborn', 'vt.  收买， 买通， 唆使', 9520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clan', 'n.  家族， 宗族， 氏族； 帮派', 9521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purple', 'adj. 紫色的 n.  紫色', 9522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quit', 'v.  停止； 放弃； 离开； 辞', 9523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clam', 'n.  蛤， 蛤肉； 〈口〉守口如瓶的人， 寡言的人', 9524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'economical', 'adj.  经济的， 实惠的； 节俭的， 节约的； 精打细算的', 9525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polish', 'v.  磨光， 擦亮； 修改， 润色 n.  上光剂', 9526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cabinet', 'n.  内阁； 储藏柜， 陈列柜', 9527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ordinal', 'adj. 序数的；顺序的 n.  序数词', 9528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insurance', 'n.  保险； 保险费； 保险业', 9529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'principle', 'n.  原则； 原理； 道德准则， 行为规范； 信念', 9530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tedious', 'adj.  单调乏味的， 令人厌烦的', 9531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'source', 'n.  源， 源泉； 来源， 出处； 信息来源', 9532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telecommunication', 'n.  电信', 9533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'participant', 'n.  参与者； 参赛者', 9534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'initiate', 'vt.  发起， 开始， 创始； 接纳， 让…加入 n.  新加入组织的人', 9535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domestic', 'adj.  国内的； 家庭的； 驯养的', 9536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detergent', 'adj.  净化的， 清洁的 n. 清洁剂', 9537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glare', 'v.  怒目而视； 发出刺眼的光 n. 耀眼的光；怒视，瞪眼', 9538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrestrial', 'adj.  陆地的， 陆生的， 陆栖的； 地球的', 9539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deception', 'n.  骗局； 诡计； 欺骗， 欺诈', 9540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compile', 'vt.  汇编； 编辑， 编纂', 9541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bias', 'n. 偏见，偏心 vt.  使有偏见， 使偏心', 9542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fume', 'vi.  冒烟； 大为恼火', 9543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'budget', 'v. 做预算 adj.  价格低廉的 n. 预算', 9544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiate', 'v.  辐射， 发射； 流露， 显示； 自中心向各方伸展', 9545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tension', 'n.  紧张； 拉紧； 张力', 9546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenuous', 'adj.  纤细的； 稀薄的； 脆弱的', 9547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reflection', 'n.  反映； 映像； 深思， 考虑； 回忆； 记录， 描述', 9548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'campus', 'n.  校园', 9549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ultimate', 'adj. 最后的，最终的；根本的 n.  最好的事物； 最大的或最先进的事物', 9550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prosecute', 'v.  起诉， 控告， 检举； 担任控方律师； 继续从事', 9551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verbal', 'adj.  口头的； 言辞的； 动词的', 9552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'district', 'n.  地区， 区域； 管区， 行政区', 9553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arboreal', 'adj.  树栖的； 树木的', 9554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overall', 'adv.  总共 adj. 全面的，综合的 n.  工作服， 工装裤', 9555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assume', 'vt.  假定； 承担', 9556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pepper', 'n. 胡椒；辣椒 vt.  撒胡椒粉； 大量给予', 9557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mellow', 'adj. 醇香的；柔和的；成熟的 v.  醇香； 柔和； 成熟', 9558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concept', 'n.  概念， 观念； 设想', 9559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impersonal', 'adj.  没有人情味的， 冷淡的； 客观的', 9560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'millennium', 'n. 一千年，千年期', 9561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resistant', 'adj.  抵抗的， 有抵抗力的； 抵制的； 抗…的， 耐…的', 9562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salamander', 'n.  火蜥蜴； 火蛇', 9563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disaster', 'n.  灾难； 彻底的失败', 9564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stark', 'adv.  十足 adj. 赤裸的；严酷的，严峻的；明显的，鲜明的；十足的，极端的', 9565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hitch', 'v. 搭便车；提起，拉起；拴住 n.  故障， 障碍', 9566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perceptual', 'adj.  感知的， 知觉的', 9567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furry', 'adj.  毛皮似的； 盖着毛皮的； 生苔的', 9568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enhance', 'vt.  提高； 增强', 9569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convention', 'n.  会议； 习俗， 惯例； 公约', 9570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cranial', 'n.  头盖骨的， 颅骨的', 9571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purchase', 'n. 购买；购买的物品 vt.  购买', 9572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shore', 'n. 滨，岸 vt.  支撑， 支持', 9573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'teem', 'vi.  充满， 到处都是', 9574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anomie', 'n.  社会道德沦丧， 失范； 混乱', 9575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chlorine', 'n.  氯', 9576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manage', 'v.  勉力完成； 应付； 操纵， 控制； 管理', 9577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equal', 'adj. 相同的 vt. 等于；相当于 n.  同等的人； 相等的事物', 9578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stylish', 'adj.  漂亮的， 时髦的； 高雅的， 有格调的', 9579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marvel', 'v. 对…感到惊异，大为赞叹 n.  令人惊异的人， 奇迹； 不凡的成果', 9580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silicon', 'n.  硅', 9581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silicate', 'n.  硅酸盐', 9582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fund', 'n. 基金，专款；储备，蕴藏； vt.  为…提供资金', 9583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravity', 'n.  重力； 严重性； 严肃， 庄严', 9584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recipient', 'n.  接受者， 收受者', 9585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mesmerize', 'vt.  施催眠术； 使入迷， 迷住', 9586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finance', 'vt. 给…提供资金 n. 财政，金融；', 9587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stash', 'vt. 隐藏，藏匿 n.  贮藏物', 9588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parking', 'n.  机动车停放； 停车场', 9589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'studio', 'n.  工作室， 画室； 摄影室， 演播室， 录音室； 练习室； 电影公司', 9590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incur', 'vt.  招致， 招惹， 遭受', 9591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'downward', 'adv. 向下，往下 adj.  向下的', 9592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plump', 'adj.  微胖的； 丰满的', 9593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abreast', 'adv.  并列地， 并排地', 9594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recoil', 'vi. 弹回；后退，退缩；产生后坐力 n.  后退， 退缩； 反冲， 后坐力', 9595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regulate', 'v.  管理， 控制； 调整， 调节； 校准', 9596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interactive', 'adj.  交互式的； 合作的， 互相配合的', 9597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'listless', 'adj.  倦怠的， 没精打采的', 9598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gland', 'n.  腺', 9599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complementary', 'adj.  补充的； 互补的', 9600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consistency', 'n.  浓度， 密度； 一致性， 协调； 连接， 结合', 9601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ordeal', 'n.  折磨； 严峻考验', 9602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primate', 'n.  灵长类， 灵长目动物； 大主教', 9603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wispy', 'adj.  成束的； 纤细的', 9604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'premise', 'n.  房屋和地基， 经营场址； 前提， 假设', 9605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonize', 'vt.  聚居于， 大批生长于； 开拓殖民地， 移居于', 9606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'season', 'n.  季节； 时节； 时期', 9607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'controversial', 'adj.  引起争论的， 有争议的', 9608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attain', 'vt.  达到； 获得', 9609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenant', 'n. 房客，承租人 vt.  居住', 9610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gallery', 'n.  画廊， 美术馆', 9611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restoration', 'n.  恢复； 整修， 修复； 复位， 复原； 归还', 9612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pale', 'vi.  变得苍白， 变得暗淡 adj. 苍白的；淡色的；暗淡的，微弱的', 9613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardware', 'n.  五金制品， 金属制品； 硬件', 9614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'batter', 'v. 连续猛击 n.  击球手； 面糊', 9615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wretch', 'n.  不幸的人； 恶棍， 无赖', 9616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'priority', 'n.  优先权， 优先； 优先考虑的事， 最重要的事', 9617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metallic', 'adj.  金属般的； 金属制的； 含金属的', 9618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creative', 'adj.  有创造力的， 创造性的', 9619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mythology', 'n.  神话； 神话学； 虚幻的想法', 9620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shuttle', 'v. 穿梭往返；短程往返运送 n.  航天飞机； 梭子； 航班', 9621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allocate', 'vt.  分配， 分派， 把…拨给', 9622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bagel', 'n.  硬面包圈', 9623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primary', 'adj.  最初的； 首要的； 基本的', 9624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'log', 'n. 原木，木材；日志，航海日志，飞行日志 vt.  记录； 伐木', 9625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enterprise', 'n.  企业， 公司； 事业', 9626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'falcon', 'n.  猎鹰， 隼', 9627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ventilation', 'n.  通风设备； 空气流通', 9628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solar', 'adj.  太阳的， 日光的； 太阳能的', 9629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consume', 'vt.  消耗， 损耗； 消费； 吃， 喝； 使充满； 烧毁， 毁灭', 9630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formation', 'n.  形成， 构成； 形成物； 编队', 9631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'psychoanalysis', 'n.  心理分析， 精神分析', 9632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bilingualism', 'n.  双语现象', 9633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'competence', 'n.  能力， 胜任； 权限； 技能', 9634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fuse', 'v. 融合；熔接；熔化；因保险丝烧断而断电；合并 n.  保险丝； 引信； 导火线', 9635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frivolous', 'adj.  琐碎的， 无关紧要的； 愚蠢的， 可笑的； 无聊的， 不严肃的， 轻佻的', 9636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretext', 'n.  借口， 托词', 9637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emergent', 'adj.  突现的； 新兴的； 紧急的', 9638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assure', 'vt.  确保； 使确信', 9639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consult', 'v.  请教； 商议； 参考， 翻阅', 9640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'funding', 'n.  基金， 资金； 提供资金', 9641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'survive', 'v.  幸免， 幸存； 继续存在， 存货； 艰难度过； 比…长命', 9642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'initial', 'adj. 开始的，最初的 n.  词首大写字母', 9643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rudimentary', 'adj.  未充分发展的， 原始的； 基本的， 基础的', 9644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adversary', 'n.  对手， 敌手', 9645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postulate', 'vt.  假定， 假设', 9646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infest', 'vt.  大批滋生， 大批出没于', 9647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satiric', 'adj.  讽刺的， 嘲讽的', 9648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eternal', 'adj.  永恒的， 不朽的', 9649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crumple', 'v.  变皱， 起皱； 破裂； 崩溃， 垮台', 9650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satire', 'n.  讽刺文学， 讽刺作品； 讽刺', 9651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevalent', 'adj.  流行的， 普遍的', 9652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cling', 'vi.  附着， 黏住； 紧紧抓住； 挨近', 9653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clip', 'v. 夹住，扣住；修剪；剪下 n.  夹子， 回形针， 别针； 弹夹， 弹仓； 电影片段， 剪报', 9654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oasis', 'n.  绿洲； 避风港', 9655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutrient', 'adj.  滋养的， 有营养的 n. 滋养物，营养品', 9656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compact', 'adj. 紧凑的；简洁的 vt.  压缩', 9657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outlaw', 'vt. 宣布…为非法 n.  罪犯， 歹徒， 亡命之徒； 被剥夺法律权益者', 9658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irrigate', 'vt.  灌溉； 冲洗', 9659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrivel', 'v.  枯萎', 9660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encrust', 'v.  在表面形成硬壳， 结壳； 用…装饰外层', 9661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upsurge', 'n.  高涨； 激增', 9662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dam', 'n. 坝，堤 vt.  筑坝； 控制', 9663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bloom', 'v.  开花 n. 花；开花；青春焕发', 9664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'denote', 'v.  表示， 意指； 标示， 预示， 象征', 9665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'zone', 'vt. 将…划做特殊区域；分区，划分地带 n.  地区， 地域， 地带； 气候带', 9666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'audible', 'adj.  听得见的', 9667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhort', 'vt.  劝告， 规劝， 告诫', 9668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'propagate', 'v.  繁殖； 散布， 传播', 9669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'checked', 'adj.  格子花纹的； 棋盘状的', 9670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'necessitate', 'vt.  需要， 使成为必要', 9671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orthodox', 'adj.  传统的； 正统的', 9672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depredation', 'n.  劫掠， 掠夺， 破坏', 9673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'combination', 'n.  结合， 混合； 化合； 组合', 9674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambush', 'n&vt.  埋伏， 伏击', 9675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jewelry', 'n.  〈总称〉首饰； 珠宝', 9676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obtain', 'v.  获得； 通用， 流行', 9677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statesman', 'n.  政治家', 9678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quadruple', 'v. 成四倍 adj. 四部分组成的；四倍的 n.  四倍', 9679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adept', 'adj. 熟练的，精通的，内行的 n.  行家， 熟手', 9680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curiosity', 'n.  好奇心， 求知欲； 罕见而有趣之物， 珍品', 9681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repute', 'v. 称为，认为 n.  名声， 名誉', 9682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nimble', 'adj.  敏捷的， 灵活的', 9683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amiable', 'adj.  可爱的； 友好的， 和蔼的， 亲切的', 9684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'format', 'n. 设计，安排；格式，样式 vt.  使格式化', 9685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sacrifice', 'v. 牺牲，献出；以…做祭献 n.  牺牲， 献身； 献祭， 祭品', 9686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'particular', 'adj. 特定的；独特的；详细的；挑剔的 n.  详情， 细目', 9687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corps', 'n.  军团， 兵团； 特种部队； 一群人， 一组人', 9688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pause', 'n&v.  中止， 暂停', 9689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formal', 'adj.  正规的， 正式的； 形式的', 9690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rainbow', 'n.  彩虹', 9691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instructor', 'n.  导师， 讲师； 教练， 指导员', 9692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fervor', 'n.  热情， 热烈', 9693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ample', 'adj.  富足的， 充足的， 丰富的； 宽敞的', 9694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cohesion', 'n.  内聚力； 凝聚力； 团结， 结合', 9695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entertain', 'v.  招待， 款待； 使快乐， 娱乐', 9696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ease', 'v.  缓和， 减轻 n. 不费力，容易；悠闲，自在', 9697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'condiment', 'n.  调味品', 9698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'certitude', 'n.  确定， 确信； 必然性', 9699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overrun', 'v. 超过，溢出；泛滥；横行 n.  泛滥； 超出的部分', 9700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deceptive', 'adj.  欺骗性的， 导致误解的', 9701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mathematics', 'n.  数学', 9702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reactor', 'n.  反应堆', 9703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cookout', 'n.  野外烧烤宴会', 9704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'envision', 'vt.  想象， 展望， 预想', 9705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outcry', 'n.  大声疾呼， 强烈的抗议', 9706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penetrate', 'v.  刺穿； 渗透； 洞察', 9707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paddle', 'v.  用桨划船； 涉水， 戏水 n. 桨；桡足', 9708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reschedule', 'vt.  重新计划， 重订…的时间表', 9709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'principal', 'adj. 主要的，最重要的 n.  校长； 资本； 主角', 9710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tend', 'v.  趋于， 易于； 照料， 看护', 9711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'somber', 'adj.  昏暗的； 忧郁的', 9712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synonym', 'n.  同义词', 9713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'equitable', 'adj.  公平的， 公正的', 9714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inconspicuous', 'adj.  不引人瞩目的， 不显眼的', 9715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specimen', 'n.  标本， 样本； 范例； 抽样', 9716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exotic', 'adj.  外来的， 来自异国的； 奇异的', 9717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relief', 'n.  缓解， 减轻， 轻松； 援救， 救济； 宽慰； 浮雕', 9718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boycott', 'vt.  联合抵制， 拒绝购买', 9719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'introduction', 'n.  介绍； 传入， 引进； 导言， 绪论', 9720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subscribe', 'v.  订购， 订阅； 申请， 预订； 捐助， 赞助', 9721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'therapy', 'n.  治疗， 疗法', 9722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chromosome', 'n.  染色体', 9723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concentration', 'n.  专注， 专心； 浓度， 含量； 集中， 聚集', 9724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'velocity', 'n.  速度， 速率； 迅速', 9725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fellowship', 'n.  友谊； 奖学金； 团体， 协会', 9726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colleague', 'n.  同事， 同僚', 9727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unadorned', 'adj.  未装饰的， 朴实的', 9728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confession', 'n.  供认， 招供， 坦白； 供词； 承认', 9729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meridian', 'n.  子午线， 经线', 9730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interfere', 'vi.  干涉， 干扰， 妨碍', 9731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apartment', 'n.  公寓套房； 房间', 9732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tolerate', 'vt.  忍受； 容许， 承认', 9733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stack', 'v.  堆积， 堆放 n. 堆', 9734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resent', 'v.  憎恶， 愤恨， 怨恨', 9735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fiery', 'adj.  似火的； 易怒的， 暴躁的', 9736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mime', 'v. 模拟，模仿 n.  喜剧； 哑剧； 哑剧演员； 模拟表演', 9737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambiguous', 'adj.  不明确的， 模棱两可的', 9738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parliament', 'n.  国会， 议会', 9739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allay', 'vt.  减轻， 减少', 9740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'path', 'n.  道路； 路线； 小路， 小径', 9741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crack', 'v. 破裂，断裂；发出爆裂声；重击，猛击；崩溃，', 9742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dote', 'vi.  溺爱', 9743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrieval', 'n.  数据检索； 取回， 索回', 9744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conceivable', 'adj.  可能的； 可信的， 可想象的', 9745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cube', 'n.  立方体； 立方形的东西； 立方', 9746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synchronize', 'v.  同步， 同时发生', 9747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sequoia', 'n.  美洲杉， 红杉', 9748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impact', 'v.  影响； 冲击， 撞击 n.  影响； 冲击， 撞击', 9749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mild', 'adj.  轻微的； 温和的； 随和的', 9750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'profile', 'n. 人物专访；概述，传略，人物简介；面部的侧影；轮廓，外形 vt.  扼要介绍， 概述', 9751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bill', 'n. 账单；纸币，钞票；议案，法案；节目单；招贴，海报 vt.  用招贴宣布； 给…开账单', 9752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tributary', 'n. 支流；', 9753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clog', 'v. 堵塞，阻塞 n.  障碍', 9754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'senior', 'adj. 地位较高的；', 9755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dilate', 'v.  膨胀， 扩大； 详述', 9756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domain', 'n.  领土； 领域', 9757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'census', 'n.  人口普查， 人口统计', 9758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smear', 'v. 胡乱涂抹；弄脏；诽谤，诋毁 n.  污迹， 污斑； 诽谤， 诋毁； 涂片', 9759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'willful', 'adj.  成心的， 有意的； 任性的', 9760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relative', 'adj. 相对的；有关的 n.  亲属， 亲戚', 9761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'average', 'adj. 平均的；一般的；平庸的 v.  平均为 n. 平均水平；平均数', 9762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compare', 'v.  比较， 相比， 对比', 9763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pluralism', 'n.  多元化， 多元性； 多元主义', 9764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'influential', 'adj.  有影响力的； 有权势的', 9765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amenity', 'n. 生活设施；便利设施', 9766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bequeath', 'vt.  遗赠； 流传', 9767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transparent', 'adj.  透明的； 明显的， 显而易见的； 直率的', 9768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adaptive', 'adj.  适合的， 有适应性的', 9769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mint', 'v. 铸造 n.  薄荷； 造币厂； 大量的钱', 9770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grasp', 'vt&n.  抓住； 掌握， 理解， 领会', 9771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'journal', 'n.  期刊， 杂志； 日记， 日志', 9772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pave', 'v.  铺； 密布', 9773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distinctive', 'adj.  出众的， 有特色的', 9774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chaotic', 'adj.  混乱的， 无秩序的', 9775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brag', 'v.  吹嘘， 自夸， 自吹自擂', 9776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'annoyed', 'adj.  生气的', 9777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chimpanzee', 'n.  黑猩猩', 9778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'term', 'n. 学期；期限，期间；条件，条款；术语 vt.  把…称为', 9779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volcano', 'n.  火山', 9780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquisition', 'n.  习得， 获得； 收购， 购置', 9781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigid', 'adj.  严格的； 刚硬的， 不易弯曲的； 死板的， 刻板的； 僵硬的', 9782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deadline', 'n.  最后期限， 截止时间', 9783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'so-called', 'adj.  所谓的', 9784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mine', 'pron. 我的 v. 开矿，采矿；在…布雷 n.  矿， 矿井； 地雷， 水雷', 9785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'advent', 'n.  到来， 来临； 出现', 9786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'medieval', 'adj.  中世纪的， 中古的', 9787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staff', 'n. 全体职工；行政人员；棍棒 vt.  为…配备人员； 任职于', 9788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'involve', 'vt.  包含； 牵涉， 牵连； 使参加', 9789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stage', 'n. 阶段；步骤；舞台；戏剧 vt.   上演； 筹划', 9790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complicated', 'adj.  难懂的， 复杂的', 9791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maximum', 'adj. 最大的，最大限度的 n.  最大量， 极限', 9792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finch', 'n.  雀类', 9793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'syllabus', 'n.  教学大纲， 课程提纲', 9794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fragrant', 'adj.  芬芳的， 香的', 9795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tolerant', 'adj.  宽容的； 容忍的', 9796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dialect', 'n.  方言， 土话', 9797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigor', 'n.  严格； 严酷', 9798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dim', 'adj. 模糊的；暗淡的；朦胧的；不乐观的 v.  变暗淡； 变冷漠', 9799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impel', 'vt.  驱使， 促使', 9800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lichen', 'n.  青苔， 地衣', 9801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paralyze', 'vt.  使瘫痪， 使麻痹； 使无效', 9802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'besiege', 'vt.  包围； 使应接不暇', 9803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exemplary', 'adj.  模范的； 典型的', 9804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faculty', 'n.  学院； 全体教职员工； 能力', 9805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photodissociation', 'n.  光解', 9806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adamant', 'adj.  坚定不移的， 坚决的； 固执的', 9807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydraulic', 'adj.  水力的， 液压的； 液压驱动的； 与水力系统有关的', 9808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'habit', 'n.  习惯； 习性， 脾性', 9809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limestone', 'n.  石灰石', 9810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'considerate', 'adj.  考虑周到的， 体贴的， 体谅的', 9811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'livestock', 'n.  〈总称〉家畜， 牲畜', 9812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clue', 'n.  线索； 提示', 9813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorite', 'n.  陨石', 9814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'molten', 'adj.  熔化的， 熔融的', 9815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radius', 'n.  半径； 周围， 范围', 9816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signal', 'v. 发信号，示意；标志 adj.  显要的， 重大的 n. 信号，暗号；标志', 9817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scruffy', 'adj.  不整洁的， 邋遢的', 9818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impair', 'vt.  削弱； 损害', 9819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sumptuous', 'adj.  奢华的， 豪华的', 9820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stray', 'vi. 迷路；分心，走神；离题 adj. 迷路的；', 9821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'static', 'adj.  静态的， 静止的； 静电的； 静力的 n. 静电噪音；静电；[-s]静力学', 9822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinship', 'n.  血缘关系， 亲属关系', 9823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhaust', 'n. 废气；排气管 vt.  用尽， 耗尽； 使非常疲倦； 详尽讨论', 9824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soluble', 'adj.  可溶的； 可解决的', 9825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'varied', 'adj.  各式各样的', 9826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intriguing', 'adj.  引起兴趣的， 吸引人的', 9827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strap', 'n. 带 vt.  用带捆扎， 束牢； 用绷带包扎', 9828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diversify', 'v.  多样化， 不同', 9829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'graph', 'n.  图表', 9830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feast', 'v.  尽情享用 n. 节日；盛宴，宴会', 9831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sodium', 'n.  钠', 9832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imbibe', 'v.  喝； 吸收， 接受', 9833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impermeable', 'adj.  不可渗透的， 不透水的', 9834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precautionary', 'adj.  预防的', 9835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretentious', 'adj.  自负的', 9836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tackle', 'v. 对付，处理；阻截；抢球 n.  拦截； 用具', 9837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solvent', 'adj.  有溶解力的； 有偿付能力的 n. 溶剂', 9838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nude', 'adj.  裸体的', 9839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distract', 'vt.  分散注意力， 使分心', 9840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'palate', 'n.  上腭； 味觉， 品尝力', 9841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'influenza', 'n.  流行性感冒', 9842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loan', 'n. 贷款；出借，借出；暂借的东西 vt.  借出； 贷给', 9843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virtual', 'adj.  模拟的， 虚拟的； 实际上的， 事实上的', 9844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squeeze', 'v. 挤压；挤入；挤过，塞入；压榨，榨取；', 9845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endless', 'adj.  无止境的， 无穷尽的', 9846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pound', 'v. 猛击；捣碎；怦怦跳 n.  磅； 英镑', 9847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'load', 'n. 负荷，负担；装载 vt.  装载， 使负担', 9848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plantation', 'n.  种植园； 人造林', 9849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ignore', 'vt.  忽视； 不顾， 不理', 9850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hemisphere', 'n.  半球； 大脑半球', 9851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'continuation', 'n.  延长， 延续， 持续； 延长物， 扩建物； 延续部分', 9852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'applaud', 'v.  鼓掌， 喝彩； 称赞', 9853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lunar', 'adj.  月亮的', 9854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poetry', 'n.  诗歌； 诗集； 诗意', 9855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arrogant', 'adj.  傲慢的， 自大的', 9856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relay', 'vt.  转播； 传达， 转述 n.  接替人员， 轮换者； 接力赛； 中继设备', 9857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permission', 'n.  允许， 同意； 许可证， 书面许可', 9858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permeate', 'v.  弥漫； 渗透', 9859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monogamous', 'adj.  一夫一妻制的； 单配的', 9860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'schedule', 'vt. 安排，预定 n.  时刻表， 日程表； 清单， 明细表', 9861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apprehend', 'vt.  逮捕； 领会， 理解', 9862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crippling', 'adj.  令人震惊的； 严重损害身体的； 极其有害的', 9863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inherit', 'v.  继承， 遗传而得', 9864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arduous', 'adj.  费力的， 艰巨的', 9865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interpret', 'v.  解释， 说明； 理解； 翻译', 9866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faction', 'n.  派别， 派系， 小集团； 派系斗争', 9867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beach', 'n.  海滩， 湖滩， 河滩', 9868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universe', 'n.  宇宙； 世界', 9869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blanket', 'n.  毯子； 覆盖物', 9870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grant', 'v. 给予，授予；允许，同意；承认 n.  拨款； 津贴； 授予物', 9871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recoup', 'vt.  收回， 弥补', 9872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aquifer', 'n.  含水土层', 9873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'append', 'vt.  附加， 增补', 9874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newsletter', 'n.  时事通讯', 9875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'copilot', 'n.  副驾驶员', 9876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frigid', 'adj.  寒冷的； 冷淡的', 9877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relic', 'n.  遗物， 遗迹， 遗风', 9878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bellows', 'n.  风箱', 9879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discount', 'n.  折扣 vt.  把…打折扣； 不全信， 漠视， 低估', 9880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convert', 'v.  改变； 转变， 转化', 9881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'construct', 'vt.  建造； 创立 n.  构想， 观念', 9882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attempt', 'n&vi.  尝试； 努力', 9883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rivalry', 'n.  竞争 ； 敌对', 9884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charisma', 'n.  超凡魅力； 感召力； 号召力', 9885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'division', 'n.  除， 除法； 分开， 分隔； 分配； 部分； 分歧， 分裂； 部门', 9886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balance', 'vt. 使平衡，使均衡 n.  天平， 秤； 平衡； 差额； 余款', 9887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stalk', 'v.  偷偷接近； 跟踪； 趾高气扬地走 n. 茎，梗，柄', 9888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pancreas', 'n.  胰腺', 9889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplier', 'n.  供应者， 供应商， 供货方', 9890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patriarchic', 'adj.  家长的， 族长的； 德高望重的', 9891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mimic', 'adj.  模仿的， 模拟的 vt. 模仿；像 n. 模仿者；小丑', 9892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pitch', 'n. 音高，音调；倾斜度；沥青，柏油；', 9893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feat', 'n.  功绩， 壮举', 9894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incessant', 'adj.  不断的， 不停的', 9895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'torrent', 'n.  洪流， 急流； 爆发， 迸发', 9896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appreciation', 'n.  欣赏； 理解， 体谅； 感激； 鉴定， 评价', 9897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statue', 'n.  雕像', 9898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sense', 'v.  觉得， 意识到 n. 感官，官能；感觉；判断力；意义，意思', 9899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brew', 'v. 酿造；冲泡；酝酿，行将发生 n.  冲泡的饮料； 啤酒', 9900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretension', 'n.  要求， 主张； 自命不凡； 虚饰', 9901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deflect', 'v.  偏斜， 转向', 9902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virtuous', 'adj.  有道德的， 品行端正的， 品德高的； 〈贬〉自命清高的， 自以为是的', 9903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invalid', 'adj.  无效的； 无可靠根据的， 站不住脚的 n.  病弱者， 残疾者', 9904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legitimate', 'adj.  合法的， 法定的； 正当合理的， 合情合理的', 9905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interval', 'n.  间隔时间； 间距； 幕间休息', 9906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whereby', 'ad&conj.  借以， 凭', 9907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evaluate', 'vt.  评价， 估计', 9908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'status', 'n.  身份， 地位； 情况', 9909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ooze', 'v. 渗出，慢慢流出；洋溢着，充满 n.  泥浆； 缓慢渗出', 9910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renown', 'n.  名望， 声誉', 9911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'semantic', 'adj.  语义的', 9912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upset', 'adj.  心烦意乱的； 不适的 vt.  使心烦意乱； 颠覆， 推翻； 搅乱 n.  困扰， 麻烦； 出乎意料的结局； 苦恼', 9913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diffusion', 'n.  散布， 扩散； 传播', 9914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curve', 'v. 弄弯，成曲线形 n.  曲线； 曲线图； 弯曲', 9915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dot', 'v. 星罗棋布于；打点于；点缀 n.  点， 圆点； 小数点', 9916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skim', 'v.  撇去； 掠过， 擦过； 浏览， 略读', 9917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skip', 'v. 跳；跳过，略过，漏过；不出席 n.  跳； 跳过', 9918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disseminate', 'v.  散布， 传播', 9919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liquefy', 'v.  溶解， 液化', 9920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exodus', 'n.  大批离去， 成群外出', 9921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mention', 'v.  提及， 说起', 9922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stream', 'v. 涌 n.  溪流； 串， 股', 9923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laundry', 'n.  洗衣店， 洗衣房； 洗好的衣服； 待洗的衣服', 9924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'digression', 'n.  离题， 扯到枝节上； 题外话， 枝节内容', 9925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grudge', 'v.  勉强做； 不情愿地给 n. 怨恨，积怨', 9926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herald', 'vt. 预示；宣布，宣告 n.  信使； 预示， 预兆', 9927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accumulate', 'v.  积累， 积聚， 堆积', 9928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coalition', 'n.  联盟， 同盟； 结合， 联合', 9929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dwarf', 'adj. 矮小的 vt. 使显得矮小，使相形见绌 n.  侏儒， 矮人', 9930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crime', 'n.  犯罪； 罪行', 9931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leisure', 'n.  空闲， 闲暇', 9932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surround', 'v.  包围， 圈住； 围绕， 环绕', 9933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mar', 'vt&n.  损坏， 损毁', 9934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mat', 'n.  垫子', 9935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forward', 'adv. 向前； vt. 发送；转交，转递', 9936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melanin', 'n.  黑色素', 9937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assimilate', 'v.  透彻理解， 吸收， 消化； 同化', 9938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ethical', 'adj.  道德的', 9939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'zealous', 'adj.  狂热的， 热烈的， 充满激情的', 9940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comparable', 'adj.  可比较的， 类似的； 比得上的', 9941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bait', 'n. 鱼饵，诱饵 vt.  下诱饵； 激怒', 9942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mail', 'n. 邮件 vt.  邮寄', 9943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dimensional', 'adj.  …度空间的', 9944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subject', 'adj.  受…支配的 n. 主题；对象 vt.  使服从', 9945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recognition', 'n.  承认， 认同； 认出， 识别， 辨认； 赏识', 9946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disinterest', 'n.  无兴趣， 冷漠； 客观， 公正', 9947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lunge', 'vi&n.  猛冲， 猛扑', 9948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convene', 'v.  召集， 召开； 聚集， 集合', 9949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revenue', 'n.  收入； 税收', 9950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strip', 'vt. 剥夺，剥掉；脱去…的衣服 n.  条， 带状物； 条纹', 9951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monopoly', 'n.  垄断， 专卖； 垄断商品， 专卖商品； 独占， 专利', 9952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negotiation', 'n.  商议， 谈判； 流通', 9953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grain', 'n.  谷物； 颗粒； 纹理； 少量', 9954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credit', 'vt. 把…归于 n.  荣誉； 学分； 信用； 贷款', 9955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oxygen', 'n.  氧， 氧气', 9956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'combine', 'v.  联合， 结合', 9957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alter', 'vt.  改变', 9958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fraudulent', 'adj.  欺诈的， 欺骗性的', 9959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waste', 'adj. 无用的，废弃的；荒芜的 n. 浪费；废料，废弃物 vt.  浪费， 消耗', 9960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approximation', 'n.  接近； 近似值', 9961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'syllable', 'n.  音节', 9962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comedy', 'n.  喜剧； 喜剧性， 滑稽， 幽默', 9963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literacy', 'n.  有文化， 有教养； 读写能力', 9964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'originate', 'v.  起源； 发起； 创立', 9965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compass', 'n. 罗盘，罗盘仪；', 9966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soloist', 'n.  独奏者， 独唱者， 单独表演者', 9967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonetheless', 'adv.  虽然如此， 但是， 依然', 9968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dispose', 'v.  安排， 布置； 使倾向于', 9969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disconcert', 'vt.  使惊慌， 使不安； 使困惑', 9970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constitution', 'n.  宪法， 章程； 体质； 构成', 9971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paradigm', 'n.  范例， 典范', 9972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blend', 'v. 混合，混杂 n.  混合； 混合物', 9973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overact', 'v.  把表演得过火； 表现做作', 9974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fidelity', 'n.  忠诚， 忠实； 精确， 逼真', 9975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conceive', 'v.  构思， 构想， 设想； 怀孕', 9976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incursion', 'n.  袭击， 突然入侵； 介入', 9977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonsense', 'n.  胡说， 废话； 冒失的行为', 9978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stain', 'v. 沾污；留下污渍 n.  污点， 污渍', 9979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balk', 'v.  畏缩； 阻止； 妨碍 n. 障碍', 9980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electrode', 'n.  电极', 9981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'airborne', 'adj.  空气传播的； 空运的', 9982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reckless', 'adj.  轻率的， 鲁莽的， 无所顾忌的', 9983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oversleep', 'v.  睡过头； 睡得过久', 9984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bald', 'adj.  光秃的， 秃头的； 简单的， 单调的', 9985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paradox', 'n.  似非而是的论点； 自相矛盾的话', 9986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oratorio', 'n.  清唱剧， 宗教剧', 9987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'X-ray', 'n.  X射线， X光； X光照片', 9988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physical', 'adj. 物理的；物质的，有形的；身体的，肉体的 n.  体检', 9989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'categorize', 'vt.  将…分类， 把…加以分类', 9990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mania', 'n.  躁狂； 狂热； 癖好', 9991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poetic', 'adj.  诗歌的； 诗意的', 9992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opposed', 'adj.  反对的； 截然不同的', 9993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'familiarize', 'vt.  使熟悉', 9994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apportionment', 'n.  分派， 分摊， 分配', 9995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thread', 'v. 穿；穿过，通过 n.  线； 线索； 思路', 9996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enrollment', 'n.  登记， 注册； 入学', 9997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tyrannical', 'adj.  专制的， 残暴的， 专横的', 9998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stake', 'n. 股份；赌注；利害关系 vt.  以…打赌， 拿…冒险', 9999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortify', 'vt.  支持， 给…以勇气； 加强， 增强； 筑防御工事于', 10000);
