INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reproduce', 'v.  翻版； 繁殖； 复制； 再现', 4501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'skeleton', 'n.  骨骼', 4502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'illiterate', 'adj.  文盲的， 未受教育的', 4503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'federate', 'v.  使联合， 使结成同盟', 4504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'myriad', 'adj.  无数的； 一万的', 4505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inflammable', 'adj.  易燃的', 4506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pervade', 'v.  遍及', 4507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'implement', 'v.  贯彻， 实现 n. 工具，器具', 4508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erratic', 'adj.  不规律的； 不稳定的', 4509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'justifiable', 'adj.  有理由的； 可辩护的', 4510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incinerate', 'v.  把…烧成灰， 烧掉， 火化', 4511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cajolery', 'n.  甜言蜜语； 诱骗； 谄媚', 4512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adoration', 'n.  崇拜， 爱慕', 4513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sagacious', 'adj.  有洞察力的， 有远见的； 精明的， 敏锐的', 4514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capillary', 'adj.  毛状的； 毛细血管的 n. 毛细管', 4515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erode', 'v.  侵蚀， 腐蚀； 使变化', 4516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beset', 'vt.  困扰', 4517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nestle', 'v.  舒适地安顿下来', 4518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frustrate', 'v.  挫败， 阻挠， 使灰心； 阻止', 4519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sparse', 'adj.  稀少的， 稀疏的', 4520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pragmatic', 'adj.  实际的； 注重实效的', 4521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anticyclone', 'n.  反气旋， 高气压', 4522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erosion', 'n.  腐蚀， 磨损， 侵蚀； 削弱， 减少', 4523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'methane', 'n.  甲烷', 4524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plenteous', 'adj.  许多的， 丰饶的， 充足的， 丰富的', 4525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superstitious', 'adj.  迷信的', 4526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neural', 'adj.  神经系统的', 4527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embezzle', 'v.  盗用； 挪用', 4528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'absent-minded', 'adj.  心不在焉的， 出神的', 4529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elasticity', 'n.  弹性', 4530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aboriginal', 'adj. 土著的，原始的 n.  土著居民', 4531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emollient', 'adj. 柔软的；有缓和作用的 n.  润肤剂', 4532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lens', 'n.  透镜', 4533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embody', 'v.  体现， 使具体化', 4534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regale', 'v.  使愉悦， 使高兴', 4535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tripod', 'n.  三脚桌； 三脚架', 4536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verifiable', 'adj.  可证实的', 4537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comprehensible', 'adj.  可理解的， 易于了解的', 4538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ascent', 'n.  上升；  提高； 攀登； 上坡路', 4539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emancipate', 'vt.  解放， 解除', 4540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elliptical', 'adj.  椭圆的', 4541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'root', 'n.  方根； 方程的根', 4542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'possessive', 'adj.  所有的， 占有的 n. 所有格', 4543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hedonism', 'n.  享乐主义', 4544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'projection', 'v.  发射； 计划； 投影', 4545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'multiply', 'v.  乘', 4546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preponderate', 'v.  占优势， 超过， 胜过', 4547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'iridescent', 'adj.  彩虹色的；  闪光的', 4548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approval', 'n.  赞成， 同意； 认可， 批准', 4549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cartilage', 'n.  【解】 软骨', 4550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'multiple', 'adj. 多倍的，', 4551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adjuration', 'n.  恳请， 请愿', 4552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'requite', 'v.  报答， 酬谢', 4553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'versatile', 'adj.  通用的， 万用的； 多才多艺的， 多方面的', 4554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'magnet', 'n.  磁体', 4555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bemoan', 'v.  哀叹', 4556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avow', 'vt.  公开声明； 承认', 4557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tundra', 'n.  苔原； 冻土地带', 4558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'explosion', 'n.  爆炸', 4559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aggrieve', 'v.  使委屈； 使苦恼； 侵害', 4560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'haggard', 'adj.  憔悴的， 形容枯槁的； 野性的', 4561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'omnivorous', 'adj.  杂食的', 4562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'poignant', 'adj.  强烈的； 尖刻的', 4563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'translation', 'n.  平移', 4564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cancer', 'n.  癌症', 4565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'personnel', 'n.  全体人员， 全体职员； 人事', 4566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bestride', 'v.  骑', 4567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refractory', 'adj.  难控制的', 4568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'biodegradable', 'adj.  生物可降解的', 4569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irrelevant', 'adj.  不相关的， 不切题的', 4570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pile', 'n.  电池组', 4571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artistry', 'n.  艺术技巧； 艺术性', 4572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'catalog', 'n.  目录； 目录册', 4573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hilarious', 'adj.  欢闹的', 4574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immortal', 'adj.  不死的； 不会消亡的', 4575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chilly', 'adj.  寒冷的； 冷淡的', 4576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conjecture', 'v.  推测， 猜想', 4577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'myth', 'n.  神话； 虚构的理论， 荒诞的说法', 4578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'experiment', 'n.  实验', 4579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'implication', 'n.  含意， 暗示', 4580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cordial', 'adj.  诚恳的， 亲切的， 热诚的', 4581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'odorous', 'adj.  有气味的', 4582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'order', 'n.  顺序； 订单', 4583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carrion', 'n.  死肉； 腐肉', 4584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocative', 'adj.  呼唤的', 4585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aghast', 'adj.  惊骇的， 吓呆的', 4586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scurrilous', 'adj.  说话粗鄙恶劣的； 下流的', 4587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'modulate', 'vt.  调整， 调节', 4588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indelible', 'adj.  去不掉的， 不能拭除的', 4589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'felicity', 'n.  幸福， 幸运， 福气', 4590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resonance', 'n.  共鸣， 回声， 反响； 共振', 4591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gaiety', 'n.  高兴， 快乐； 作乐， 欢庆', 4592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reform', 'v. 改进；改革 n. 改进；改革', 4593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mutation', 'n.  变化； 转变', 4594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fallow', 'adj.  休耕的 n. 休耕地', 4595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malevolent', 'adj.  有恶意的； 坏心肠的', 4596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fermentation', 'n.  发酵', 4597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homage', 'n.  敬意', 4598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'averse', 'adj.  不愿意的； 反对的', 4599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refract', 'v.   折射', 4600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'successor', 'n.  继承人， 继任者', 4601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'matter', 'n.  物质', 4602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irony', 'n.  具有讽刺意味的事， 出人意料的事情或情况； 反话， 讽刺， 嘲弄', 4603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mandatory', 'n.  命令的； 委托的', 4604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'syndrome', 'n.  综合症', 4605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutrality', 'n.  中立， 中性', 4606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recumbent', 'adj.  靠着的， 斜躺着的； 休息的', 4607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'energetic', 'adj.  有力的， 精力旺盛的', 4608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'product', 'n.   生成物', 4609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impoverish', 'v.  使贫穷； 使枯竭', 4610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hallowed', 'adj.  神圣的， 奉为神圣的', 4611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foreordain', 'v.  注定； 预先决定', 4612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'premier', 'adj.  第一的， 首要的 n. 首相，总理', 4613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hydrate', 'n.  水合物', 4614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intellectual', 'adj. 智力的，脑力的 n. 知识分子', 4615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reclaim', 'v.  要求归还， 收回； 开垦', 4616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interchangeable', 'adj.  可交换的', 4617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allegory', 'n.  寓言', 4618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nautical', 'adj.  船员的； 船舶的； 海上的， 航海的', 4619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disengage', 'v.  脱离， 松开', 4620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gibber', 'v.  模糊地讲话', 4621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'descendent', 'adj.  派生的', 4622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anecdote', 'n.  轶事， 奇闻； 短故事', 4623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mendicant', 'n.  乞丐', 4624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extravagance', 'n.  过度， 放肆', 4625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cantankerous', 'adj.  脾气坏的； 好吵架的', 4626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kudos', 'n.  名望； 荣誉； 声誉', 4627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irreversible', 'adj.  不能撤回的， 不能取消的', 4628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coy', 'adj.  腼腆的， 羞涩的， 忸怩的； 献媚的， 卖弄风情的', 4629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'AluminumAl', 'n.  铝', 4630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pacify', 'v.  使平静， 安慰， 抚慰', 4631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bulwark', 'n.  壁垒； 防波堤', 4632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'identical', 'adj.  同一的， 完全相同的； 相等的， 恒等的', 4633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abject', 'adj.  卑贱的', 4634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monologue', 'n.  独白， 独角戏', 4635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incontrovertible', 'adj.  无可争议的， 无疑的， 明白的', 4636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambitious', 'adj.  有雄心的， 雄心勃勃的', 4637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contemptuous', 'adj.  轻蔑的， 侮辱的', 4638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'academic', 'adj.  学院的； 学术的 n. 学者；大学教师；学会会员', 4639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hadron', 'n.  强子', 4640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grisly', 'adj.  恐怖的， 可怕的， 令人毛骨悚然的', 4641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revere', 'v.  尊敬， 敬畏， 崇敬', 4642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salacious', 'adj.  猥亵的， 好色的', 4643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comparison', 'n.  比较， 对比； 比喻， 比拟', 4644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'law', 'n.  定律', 4645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parallel lines', '平行线', 4646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distingusihed', 'adj.  著名的， 卓越的', 4647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pernicious', 'adj.  有害的， 有毒的', 4648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'centiliter', 'n.  毫升', 4649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revert', 'v.  回复， 回返', 4650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'herbivore', 'n.  食草动物', 4651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'successive', 'adj.  连续的， 相继的', 4652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peddle', 'v.  挑卖， 沿街叫卖', 4653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'violation', 'n.  违反， 违背； 妨碍， 侵害', 4654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'metabolism', 'n.  新陈代谢', 4655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abdicate', 'v.  退位； 放弃', 4656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emanate', 'v.  流出， 发出； 发散， 放射', 4657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impenitent', 'adj.  不悔悟的； 顽固的', 4658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avocation', 'n.   副业； 业余爱好', 4659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exterior', 'adj. 外部的，外在的 n.  外部', 4660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'censure', 'n. 严厉批评，谴责 v. 严厉批评，正式谴责', 4661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'technique', 'n.  技术， 技巧', 4662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chattel', 'n. 动产；私人财产', 4663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'levy', 'vt. 征收 n.  征税， 税款； 征兵', 4664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intimidate', 'vt.  恐吓， 威胁， 胁迫', 4665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'xenophobe', 'n.  畏惧或憎恨外国人 / 事物的人', 4666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'timer', 'n.  定时器', 4667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malinger', 'v.  装病', 4668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flux', 'n.  流， 流出， 流动； 涨潮； 变迁', 4669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coincidence', 'n.  一致， 符合， 同时发生或同时存在  的事', 4670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'becalm', 'v.  使安静； 因无风而使停航', 4671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'detrimental', 'adj.  有害的', 4672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'well-wisher', 'n.  祝福者', 4673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capitulate', 'vi.  有条件投降； 屈服， 停止抵抗', 4674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'celibate', 'n.  独身者， 独身主义者', 4675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vicarious', 'adj.  代理的； 间接感受到的', 4676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satiate', 'v.  使充分满足； 享用过度； 使厌腻', 4677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lengthy', 'adj.   冗长的， 过分的', 4678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'spore', 'n.  孢子', 4679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rampage', 'v.  发怒， 乱闹， 狂暴', 4680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kinsfolk', 'n.  亲属， 家属', 4681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probe', 'v.   探查， 穿刺， 查究 n. 针；探测器', 4682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensuous', 'adj.  感觉的', 4683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quantitative', 'adj.  数量的， 定量的', 4684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remission', 'n.   减轻； 豁免', 4685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foment', 'v.  煽动', 4686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'skirmish', 'n.  小冲突', 4687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equilibrium', 'n.  平衡； 平静； 均衡', 4688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bereft', 'adj.  被剥夺的； 失去亲人的； 丧失的', 4689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'narcissism', 'n.  自我陶醉； 自恋', 4690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'esophagus', 'n.  食管', 4691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incident', 'n.  事件， 事变', 4692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maintenance', 'n.  维修， 保养； 维持， 保持', 4693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intermit', 'v.  间歇， 中断', 4694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hypercritical', 'adj.  吹毛求疵的， 过分苛刻的', 4695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peccant', 'adj.  犯罪的； 堕落的', 4696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neuron', 'n.  神经元', 4697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'absorb', 'vt.  吸收； 使专心', 4698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'burgher', 'n.  自治市  居民， 市民', 4699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circulate', 'vt.   流通，  运行，  循环；  传播', 4700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'leg', 'n.  梯形的两条不平行的边', 4701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resuscitate', 'v.   复苏；  复活', 4702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rectify', 'v.  纠正， 整顿', 4703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antonym', 'n.  反义词', 4704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'integrity', 'n.  正直， 诚实； 完整， 完全', 4705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'liable', 'adj.  有责任的， 有义务的； 有…倾向的， 易于…的', 4706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'midpoint', 'n.  中点', 4707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quagmire', 'n.  沼泽； 困境', 4708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undue', 'adj.  不适当的， 过度的', 4709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'element', 'n.  元素； 组成部分， 成分', 4710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'panacea', 'n.  万灵药', 4711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symphonious', 'adj.  和谐的， 调和的', 4712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mendacious', 'adj.  虚伪的； 说谎的', 4713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'callosity', 'n.  无情， 冷酷', 4714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pervious', 'adj.  能被通过的', 4715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lucubration', 'n.  刻苦钻研', 4716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tutelage', 'n.  指导； 教导', 4717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cartridge', 'n.  弹药筒', 4718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'theorem', 'n.  原理', 4719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cue', 'n.  提示， 暗示', 4720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lewd', 'adj.  好色的， 淫荡的', 4721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supple', 'v.  使柔软， 使顺从', 4722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infringe', 'v.  破坏， 侵犯， 违反', 4723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bravado', 'n.  虚张声势， 装作有自信的样子', 4724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ardent', 'adj.  热心的， 热情洋溢的； 激烈的， 燃烧般的', 4725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'concurrent', 'adj.  并发的； 协作的， 一致的', 4726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assonance', 'n.  谐音； 半谐音', 4727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cohesive', 'adj.  黏着的， 黏合性的', 4728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'untoward', 'adj.  麻烦的； 不幸的', 4729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'battery', 'n.  电池组', 4730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'harass', 'vt.  侵扰， 烦扰', 4731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'moment', 'n.  时刻', 4732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irreverent', 'adj.  不敬的', 4733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'promote', 'v.  促进， 发扬； 提升， 提拔； 增进， 助长； 宣传', 4734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hackney', 'v.  役使； 出租', 4735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'graphic', 'adj.  生动的， 形象的； 绘画的， 文字的， 图表的', 4736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'creation', 'n.  产生', 4737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inclination', 'n.  倾斜； 倾向， 爱好', 4738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingredient', 'n.  组成部分， 成分', 4739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'participate', 'v.  参与， 参加； 分享， 分担', 4740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'authenticity', 'n.  确实性； 真实性', 4741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapacious', 'adj.  掠夺的； 贪婪的', 4742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unisonous', 'adj.  和谐的； 同音的', 4743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cadenza', 'n.  【乐】  装饰奏', 4744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'absolution', 'n.  免罪， 赦免', 4745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'haughty', 'adj.  傲慢的', 4746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contour', 'n.  轮廓； 周线', 4747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lyric', 'n.  抒情诗， 歌词', 4748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misrepresent', 'v.  误传', 4749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salvageable', 'adj.  可抢救的； 可打捞的； 可挽救的', 4750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homily', 'n.  布道； 说教', 4751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bibliomania', 'n.  藏书癖', 4752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clan', 'n.  部落； 氏族， 宗族； 帮派', 4753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'economical', 'adj.  节约的， 节俭的， 节省的， 经济的', 4754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'urchin', 'n.  顽童； 小淘气', 4755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vitalize', 'v.  使有生气', 4756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polish', 'v. 磨光，擦亮；使优美，润饰 n.  擦光剂， 上光蜡', 4757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cabinet', 'adj.  内阁的 n. 橱柜；内阁', 4758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quip', 'n.  嘲弄， 挖苦话； 双关语', 4759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ostensible', 'adj.  可公开的；  表面的， 虚假的', 4760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'principle', 'n.  原理； 原则； 主义， 信念', 4761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'litigant', 'n.  诉讼人', 4762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tedious', 'adj.  乏味的， 单调的， 冗长的', 4763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'source', 'n.  电源', 4764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'initiate', 'v.  开始， 发动', 4765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'domestic', 'adj.  家里的， 家庭的； 本国的； 驯养的', 4766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infirmary', 'n.  医院； 医务室', 4767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prepossessing', 'adj.  讨人喜欢的； 给人好感的', 4768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prim', 'adj.  整齐的', 4769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terrestrial', 'adj.  陆地的； 陆栖的', 4770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'smelt', 'v.  冶炼', 4771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vitality', 'n.  生命力， 活力', 4772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slovenly', 'adj.  懒散的； 不修边幅的', 4773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lackadaisical', 'adj.  懒洋洋的', 4774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ravenous', 'adj.  贪婪的， 渴望的， 狼吞虎咽的', 4775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abbess', 'n.  女修道院院长， 尼姑庵住持', 4776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquired', 'adj.  已获得的； 后天通过自己的努力得到的', 4777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stability', 'n.  稳定 ， 安定', 4778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radiate', 'v.  放射， 辐射； 散布， 传播', 4779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tension', 'n.  张力', 4780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reflection', 'n.  反射； 映象， 倒影； 反省， 沉思', 4781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tenuous', 'adj.  簿的； 稀薄的， 空洞无力的', 4782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'winsome', 'adj.  迷人的', 4783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ultimate', 'adj.  最后的， 最终的； 根本的', 4784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ballad', 'n.  民歌； 歌谣； 叙事歌； 流行歌曲； 情歌', 4785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caustic', 'adj.  腐蚀性的； 刻薄的', 4786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prosecute', 'v.  实行， 从事； 告发， 起诉', 4787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misunderstand', 'vt.  误解， 误会', 4788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hydrocarbon', 'n.  碳氢化合物', 4789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ampere', 'n.  安培', 4790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precocious', 'adj.  早熟的', 4791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pecuniary', 'adj.  金钱的， 金钱上的', 4792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'redound', 'v.  有助于', 4793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arboreal', 'adj.  树的， 乔木的； 树栖的', 4794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carnivorous', 'adj.  食肉类的', 4795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'philanthropy', 'n.  慈爱； 慈善事业', 4796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fetid', 'adj.  有恶臭的', 4797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predestine', 'v.  注定； 预先确定', 4798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polymer', 'n.  聚合物', 4799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'askance', 'adv.  斜， 斜视', 4800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contort', 'v.  扭曲， 歪曲', 4801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resistant', 'adj.  抵抗的， 有抵抗力的', 4802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salamander', 'n.  蝾螈', 4803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intercede', 'v.  调解', 4804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'catholicity', 'n.  普遍性； 宽容', 4805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'progeny', 'n.  后裔', 4806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enhance', 'v.  提高 ， 增强', 4807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'witchcraft', 'n.  魔法； 魔力', 4808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antiseptic', 'adj.  防腐的， 杀菌的， 消过毒的 n. 防腐剂，杀菌剂', 4809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polytechnic', 'adj.  各种工艺的； 综合技术的', 4810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suspicion', 'n.  怀疑， 猜疑', 4811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'center', 'n.  圆心', 4812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refusal', 'n.  拒绝， 推却', 4813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'churlish', 'adj.  粗野的； 脾气坏的； 无礼的', 4814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'isochronous', 'adj.  同步的', 4815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dogmatist', 'n.  武断论者； 教条主义者', 4816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flaunt', 'v.  夸耀， 炫耀', 4817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'teem', 'v.  大量出现', 4818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutralize', 'v.  使中立； 抵消', 4819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foreshadow', 'v.  预示', 4820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gravity', 'n.  重力， 引力； 严肃， 庄重', 4821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homologous chromosome', '[遗] 同源染色体', 4822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'replete', 'adj.  充分供应的， 饱足的； 充满的', 4823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enfranchise', 'v.  释放， 解放， 给予自由； 给予…公民权', 4824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alight', 'v. 落下 adj.  点着的， 发亮的', 4825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blemish', 'v.  弄脏， 玷污， 损害 n. 污点，缺点，瑕疵', 4826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'befuddle', 'vt.  使酒醉昏迷； 使迷惑， 使迷糊', 4827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inundate', 'v.  淹没', 4828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recoil', 'v.  反冲', 4829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'funnel', 'n.  漏斗', 4830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dogmatic', 'adj.  教条的， 独断的', 4831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dilettante', 'n.  业余文学、 艺术爱好者； 浅薄的涉猎者', 4832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regulate', 'v.  管理， 控制， 使遵守规章； 调节 ， 调整， 校对', 4833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'listless', 'adj.  倦怠的； 冷漠的； 情绪低落的', 4834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'punitive', 'adj.  刑罚的； 惩罚  的', 4835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gland', 'n.  腺体', 4836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complementary', 'adj.  互补的', 4837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scapegoat', 'n.  替罪羊', 4838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extant', 'adj.  现存的', 4839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'consistency', 'n.  始终一贯， 前后一致', 4840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complacent', 'adj.  自满的', 4841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plumb', 'n.  铅锤', 4842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'premise', 'n.  前提， 假设；   房屋和地基， 经营场', 4843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vilify', 'v.  诽谤， 辱骂； 贬低， 轻视', 4844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cliché', 'n.  陈词滥调', 4845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'controversial', 'adj.  引起争论的， 有争议的', 4846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intransigent', 'adj. 非妥协性的 n.  不妥协的人', 4847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unbecoming', 'adj.  不恰当的， 不得体的', 4848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'restoration', 'n.  修复； 恢复', 4849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epidermis', 'n.  表皮； 上皮', 4850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'benignant', 'adj.  仁慈的， 和蔼的； 有益的', 4851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plaintiff', 'n.  原告', 4852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heteromorphic', 'adj.  异形的', 4853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quadrant', 'n.  象限', 4854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bide', 'v.  居住， 滞留； 忍受', 4855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inveigh', 'v.  猛烈抨击； 痛骂， 漫骂', 4856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anathema', 'n.  诅咒； 令人厌恶的事', 4857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wretch', 'n.  不幸的人， 苦命的人； 卑劣的人， 无耻的人， 坏人', 4858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'detonate', 'v.  使突发大爆炸', 4859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prudish', 'adj.  过分拘谨的', 4860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mythology', 'n.  神话学', 4861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symptomatic', 'adj.  症状的， 征候的', 4862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allocate', 'vt.  分配， 分派， 把…拨给', 4863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tonic', 'adj. 激励的；滋补的 n.  滋补品', 4864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'muffle', 'v.  包， 蒙住； 压抑', 4865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abjure', 'vt.  发誓放弃； 避免', 4866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enterprise', 'n.   工作； 事业， 企业； 事业心， 进取心， 冒险精神', 4867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solar', 'adj.  太阳的， 日光的', 4868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dome', 'n.  圆屋顶； 半球形物； 苍穹', 4869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collegian', 'n.  大学生', 4870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'benefactor', 'n.  恩人； 捐助者； 赠送者； 赞助人', 4871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'domineer', 'v.  跋扈， 作威作福', 4872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unknown', 'n.  未知量', 4873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fuse', 'v.  熔化， 熔合 n. 保险丝，导火线', 4874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'competence', 'n.  胜任， 能力', 4875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frivolous', 'adj.  轻佻的， 琐碎的', 4876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tutorship', 'n.  家庭教师； 辅导', 4877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pretext', 'n.  借口， 托词', 4878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emergent', 'adj.  突现的； 意外的； 紧急的', 4879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homonym', 'n.  同音异义字， 同名异物', 4880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undervalue', 'v.  低估', 4881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'test tube', 'n. 试管', 4882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incisive', 'adj.  深刻的； 尖锐的； 激烈的', 4883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rudimentary', 'adj.  基础的； 未发展的', 4884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'Phosphorus', 'n.  磷', 4885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precarious', 'adj.  不确定的， 不安全的； 靠不住的， 根据不充足的', 4886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heterogeneity', 'n.  异质性', 4887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capacitor', 'n.  电容器', 4888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infest', 'v.  扰乱， 骚扰', 4889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contemplation', 'n.  注视； 沉思； 预期， 打算', 4890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'miff', 'v.  发脾气， 微怒； 无谓的争吵', 4891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eternal', 'adj.  永恒的， 永远的； 不灭的； 不朽的', 4892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'redress', 'v.  纠正， 矫正', 4893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parentage', 'n.  出身； 起源', 4894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'habituate', 'v.  使习惯于', 4895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plebeian', 'adj.  卑俗的 n. 平民，庶民', 4896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'randomly', 'adv.  随机地', 4897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prevalent', 'adj.  流行的； 普遍的', 4898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satire', 'n.  讽刺文学， 讽刺', 4899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'projectile', 'n.  抛体', 4900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sprightly', 'adj.  轻快的', 4901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overpower', 'v.  制服， 压倒； 供给…过强的力量', 4902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recapitulate', 'v.  扼要重述； 概括', 4903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alliance', 'n.  结盟， 联盟； 联姻', 4904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invaluable', 'adj.  非常宝贵的， 无价的', 4905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outlaw', 'n.  罪犯， 歹徒', 4906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'omniscient', 'adj.  全知的， 无所不知的', 4907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shrivel', 'v.   起皱纹；  失效', 4908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solecism', 'n.  语法错误； 失礼', 4909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denote', 'v.  指示， 表示', 4910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bedeck', 'v.  装饰， 修饰', 4911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'celebrated', 'adj.  著名的', 4912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'audible', 'adj.  听得见的', 4913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propagate', 'v.  增殖； 扩散', 4914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affair', 'n.  事， 事情， 事件', 4915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'galore', 'adj.  丰盛的， 丰富的', 4916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'Anglo-Saxon', 'n.  盎格鲁—撒克逊人', 4917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'orthodox', 'adj.  传统的， 符合社会风俗的； 正统的', 4918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accustomed', 'adj.  通常的； 习惯的', 4919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maverick', 'n.  未烙印的小牛  ； 不服从的人', 4920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'combination', 'n.  合成作用', 4921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unkempt', 'adj.   不整洁的， 未梳理的，  蓬乱的', 4922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambush', 'v.  埋伏 n. 埋伏；伏兵', 4923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adept', 'adj.  精通的， 内行的 n.  行家， 熟手', 4924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repute', 'v.  认为， 称为 n. 名誉，名声', 4925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nimble', 'adj.  敏捷的， 灵巧的', 4926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amiable', 'adj.  和蔼可亲的， 友好的， 可爱的， 亲切的', 4927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sacrifice', 'n.  牺牲； 供奉', 4928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'illegal', 'adj.  不合法的， 非法的', 4929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'countless', 'adj.  无数的', 4930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fervor', 'n.  热情， 热烈； 炽热', 4931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ample', 'adj.  充分的， 富裕的； 宽敞的， 宽大的', 4932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wavelet', 'n.  小浪； 微波', 4933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'surety', 'n.  担保， 保证', 4934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cohesion', 'n.  结合， 凝聚', 4935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrench', 'v.  节省； 减少； 缩减', 4936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overrun', 'v.  超过； 泛滥 n. 泛滥成灾，超出限度', 4937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reactor', 'n.  核反应堆', 4938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outcry', 'n.  大声疾呼； 强烈抗议', 4939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penetrate', 'v.  穿过； 渗入； 看穿， 洞察', 4940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reproof', 'n.  谴责， 非难', 4941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homogeneity', 'n.  同种； 同质', 4942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'principal', 'adj.  主要的， 首要的 n. 负责人，首长；主犯', 4943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pare', 'v.  剥， 削， 修', 4944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'synonym', 'n.  同义词', 4945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'somber', 'adj.  昏暗的； 忧郁的', 4946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perspicuity', 'n.  明白', 4947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equitable', 'adj.  公平的， 公正的', 4948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'specimen', 'n.  标本， 样本', 4949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exotic', 'adj.  异国情调的， 外来的； 奇异的', 4950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'psychic', 'adj.  精神的； 超自然的', 4951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amply', 'adv.  充足地， 详细地', 4952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boycott', 'vt.  联合抵制； 联合排斥某国货物或与某国绝交', 4953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preposterous', 'adj.  荒谬的', 4954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'semiannual', 'adj.  每半年的； 半年期的', 4955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'annals', 'n.  编年史； 年报', 4956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subscribe', 'v.  订购， 订阅， 预订', 4957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distill', 'vt.  蒸馏， 用蒸馏法提取； 吸取， 提炼', 4958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chromosome', 'n.  染色体', 4959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'concentration', 'n.  浓度', 4960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aristocrat', 'n.  贵族', 4961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'velocity', 'n.  速度', 4962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invalidate', 'v.  使无效', 4963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'colleague', 'n.  同事， 同僚', 4964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malfeasance', 'n.  违法行为， 渎职', 4965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commiserate', 'v.  怜悯， 同情', 4966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'confession', 'n.  供认， 承认， 招供', 4967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lithe', 'adj.  柔软的； 易弯的', 4968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antenatal', 'adj.  【医】 出生前的', 4969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reclamation', 'n.  开垦； 改造；  收回', 4970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tolerate', 'v.  容忍， 默许', 4971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intangible', 'adj.  感觉不到的', 4972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bombardier', 'n.  投弹手， 炮兵下士', 4973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resent', 'v.  愤恨， 怨恨', 4974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'underling', 'n.  部下， 下属； 走卒', 4975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instigate', 'v.  教唆； 怂恿', 4976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambiguous', 'adj.  不明确的； 模棱两可的', 4977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'asylum', 'n.  庇护； 收容所', 4978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allay', 'vt.  减轻， 减少； 使安静', 4979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avidity', 'n.  热望； 贪婪', 4980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'path', 'n.  路程', 4981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impulsive', 'adj.  冲动的', 4982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ashen', 'adj.  灰色的； 苍白的', 4983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'palliate', 'v.  减轻', 4984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gravitation', 'n.  引力', 4985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'botanical', 'adj. 植物学的 n.  植物性药材', 4986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'soporific', 'adj.  催眠的， 想睡的', 4987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'angelic', 'adj.  天使的； 天使般的', 4988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acoustics', 'n.  声学', 4989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scanner', 'n.  扫描器', 4990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conceivable', 'adj.  可能的， 想得到的， 可想像的', 4991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cube', 'n.  立方体； 立方； 三次幂', 4992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adulterate', 'vt.  掺杂', 4993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apparition', 'n.  离奇出现的东西；  鬼怪， 幻影', 4994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impact', 'n. 作用；影响 v. (对…)产生〔重要或明显的〕影响', 4995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'profile', 'n.  侧面 ； 轮廓， 外形； 人物简介', 4996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bilk', 'vt.  诈骗', 4997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paralysis', 'n.  瘫痪， 麻痹', 4998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'macrophage', 'n.  巨噬细胞', 4999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laudation', 'n.  赞美， 称赞， 颂词', 5000);
