INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foible', 'n. 弱点；小缺点；癖好', 3501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pseudonym', 'n. 笔名；假名', 3502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acid', 'n. 酸；<俚>迷幻药 adj. 酸的；讽刺的；刻薄的', 3503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'source', 'n. 来源；水源；原始资料', 3504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrieve', 'v. [计] 检索；恢复；重新得到 n. [计] 检索；恢复，取回', 3505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obligate', 'v. 使负义务；强使，强迫；对…施以恩惠 adj. 有责任的，有义务的；必需的', 3506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'botanize', 'v. 研究植物；采集植物 n. 研究并采集植物', 3507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'knighthood', 'n. 骑士；骑士身份', 3508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vitamin', 'n. [生化] 维生素；[生化] 维他命', 3509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'meager', 'adj. 贫乏的；瘦的 n. 兆', 3510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thermal', 'adj. 热的；热量的；保热的 n. 上升的热气流', 3511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plaudit', 'n. 喝彩；赞美', 3512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shrubbery', 'n. 灌木；[林] 灌木林', 3513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deliberate', 'adj. 故意的；深思熟虑的；从容的 v. 仔细考虑；商议', 3514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'habitable', 'adj. 可居住的；适于居住的', 3515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brotherhood', 'n. 兄弟关系；手足情谊；四海之内皆兄弟的信念', 3516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acne', 'n. [皮肤] 痤疮，[皮肤] 粉刺', 3517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cue', 'n. 提示，暗示；线索 v. 给…暗示', 3518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convey', 'v. 传达；运输；让与', 3519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'troubadour', 'n. 行吟诗人；民谣歌手', 3520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undersize', 'adj. 不够大的；小于一般尺寸的 n. 尺寸不足', 3521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rotation', 'n. 旋转；循环，轮流', 3522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'audacious', 'adj. 无畏的；鲁莽的', 3523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'redound', 'v. 有助于；报偿，报应；被转移', 3524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intolerable', 'adj. 无法忍受的；难耐的', 3525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dispel', 'v. 驱散，驱逐；消除（烦恼等）', 3526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wile', 'vt. 欺骗，诱骗；消遣 n. 诡计，阴谋', 3527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maudlin', 'adj. 感情脆弱的；容易流泪的；酒后伤感的 n. 伤感；易流泪', 3528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reproof', 'n. 责备；谴责', 3529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'luminary', 'n. 发光体；杰出人物；知识渊博的人', 3530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'numerous', 'adj. 许多的，很多的', 3531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'privacy', 'n. 隐私；秘密；隐居；隐居处', 3532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'secretive', 'adj. 秘密的；偷偷摸摸的；促进分泌的', 3533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antenna', 'n. [电讯] 天线；[动] 触角，[昆] 触须', 3534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reconsider', 'v. 重新考虑；重新审议', 3535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wily', 'adj. 狡猾的；诡计多端的 n. (Wily)人名；(英)威利', 3536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compliant', 'adj. 顺从的；服从的；应允的', 3537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forbearance', 'n. 自制，忍耐；宽容', 3538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dehydration', 'n. 脱水', 3539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gypsy', 'n. 吉卜赛人；吉卜赛语；像吉布赛的人；歌舞剧中的歌舞队员 adj. 象吉卜赛人的；吉卜赛人的；无照的 vi. 流浪', 3540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incident', 'n. 事件，事变；插曲 adj. [光] 入射的；附带的；易发生的，伴随而来的', 3541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virtual', 'adj. [计] 虚拟的；实质上的，事实上的（但未在名义上或正式获承认）', 3542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foresight', 'n. 先见，远见；预见；深谋远虑', 3543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'debacle', 'n. 崩溃；灾害；解冻', 3544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'entangle', 'v. 使纠缠；卷入；使混乱', 3545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'playful', 'adj. 开玩笑的；幽默的；爱嬉戏的', 3546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lecherous', 'adj. 好色的；淫荡的；引起淫欲的', 3547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beatitude', 'n. 祝福；至福', 3548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preceding', 'adj. 在前的；前述的 v. 在之前（precede的ing形式）', 3549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quip', 'n. 妙语；嘲弄；讽刺语 v. 嘲弄；讥讽', 3550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dexterity', 'n. 灵巧；敏捷；机敏', 3551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'susceptible', 'adj. 易受影响的；易感动的；容许…的 n. 易得病的人', 3552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predatory', 'adj. 掠夺的，掠夺成性的；食肉的；捕食生物的', 3553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excavate', 'v. 挖掘；开凿', 3554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symbolize', 'v. 象征；用符号表现', 3555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perplexing', 'adj. 复杂的，令人费解的；令人困惑的', 3556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'depot', 'n. 仓库；停车场；航空站 vt. 把…存放在储藏处 adj. 药性持久的', 3557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'macabre', 'adj. 可怕的；以死亡为主题的；令人毛骨悚然的（等于macaber）', 3558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probability', 'n. 可能性；机率；[数] 或然率', 3559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'introvert', 'v. 使内向；使内倾；使内弯 n. 内向的人；内翻的东西', 3560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ardor', 'n. 热情；狂热；灼热', 3561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'primitive', 'adj. 原始的，远古的；简单的，粗糙的 n. 原始人', 3562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'baffle', 'v. 使…困惑；使…受挫折；用挡板控制 n. 挡板；困惑', 3563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fertile', 'adj. 富饶的，肥沃的；能生育的', 3564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portion', 'n. 部分；一份；命运 v. 分配；给…嫁妆', 3565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reactionary', 'adj. 保守的，反动的；反动主义的；反对改革的 n. 反动分子；反动派；保守派', 3566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diversity', 'n. 多样性；差异', 3567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hone', 'n. 磨刀石；想念；抱怨 v. 用磨刀石磨', 3568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unfavorable', 'adj. 不宜的；令人不快的；不顺利的', 3569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vendor', 'n. 卖主；小贩；供应商；[贸易] 自动售货机', 3570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acme', 'n. 顶点，极点；最高点', 3571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'yummy', 'adj. 好吃的；美味的；愉快的 n. 美味的东西；令人喜爱的东西', 3572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amenity', 'n. 舒适；礼仪；愉快；便利设施', 3573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'populous', 'adj. 人口稠密的；人口多的', 3574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verisimilar', 'adj. 好像是真的', 3575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'workmanship', 'n. 手艺，工艺；技巧', 3576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frequent', 'adj. 频繁的；时常发生的；惯常的 v. 常到，常去；时常出入于', 3577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anomaly', 'n. 异常；不规则；反常事物', 3578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extraordinary', 'adj. 非凡的；特别的；离奇的；临时的；特派的', 3579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'secede', 'v. 脱离；退出', 3580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outcry', 'n. 强烈抗议；大声疾呼；尖叫；倒彩', 3581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gainsay', 'v. 反驳；否定 n. 否认；反对', 3582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'magnification', 'n. 放大；放大率；放大的复制品', 3583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'littoral', 'adj. 沿海的；海滨的 n. 沿海地区（等于litora）', 3584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'omission', 'n. 疏忽，遗漏；省略；冗长', 3585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inflammatory', 'adj. 炎症性的；煽动性的；激动的', 3586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auricle', 'n. 耳廓；外耳；心耳', 3587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'devour', 'v. 吞食；毁灭', 3588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'asexual', 'adj. [生物] 无性的；无性生殖的', 3589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recalcitrant', 'adj. 反抗的；反对的；顽强的 n. 顽抗者；不服从的人', 3590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'debunk', 'v. 揭穿；拆穿…的假面具；暴露', 3591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carnivorous', 'adj. 食肉的；肉食性的', 3592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embroil', 'v. 使卷入；使混乱', 3593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'narrative', 'n. 叙述；故事；讲述 adj. 叙事的，叙述的；叙事体的', 3594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'segment', 'v. 分割 n. 段；部分', 3595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'variation', 'n. 变化；[生物] 变异，变种', 3596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'defect', 'n. 缺点，缺陷；不足之处 v. 变节；叛变', 3597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aforesaid', 'adj. 前述的，上述的', 3598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exert', 'v. 运用，发挥；施以影响', 3599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revoke', 'v. 撤回，取消；废除 n. 有牌不跟', 3600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambivalent', 'adj. 矛盾的；好恶相克的', 3601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocation', 'n. 职业；天职；天命；神召', 3602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peerless', 'adj. 无与伦比的；出类拔萃的；无比的', 3603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preferable', 'adj. 更好的，更可取的；更合意的', 3604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presumption', 'n. 放肆，傲慢；推测', 3605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'census', 'v. 实施统计调查 n. 人口普查，人口调查', 3606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minus', 'prep. 减，减去 n. 负号，减号；不足；负数 adj. 减的；负的', 3607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tirade', 'n. 激烈的长篇演说', 3608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'labyrinth', 'n. 迷宫；[解剖] 迷路；难解的事物', 3609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumnavigate', 'v. 环航', 3610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'empower', 'v. 授权，允许；使能够', 3611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'depth', 'n. [海洋] 深度；深奥', 3612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'condemn', 'v. 谴责；判刑，定罪；声讨', 3613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fainthearted', 'adj. 懦弱的，胆小的；无精神的', 3614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'panic', 'n. 恐慌，惊慌；大恐慌 adj. 恐慌的；没有理由的 v. 使恐慌', 3615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'synthesize', 'v. 合成；综合', 3616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intricate', 'adj. 复杂的；错综的，缠结的', 3617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remnant', 'n. 剩余 adj. 剩余的', 3618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acerbic', 'adj. 尖刻的（等于acerb）；酸的；辛辣的', 3619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aeronautics', 'n. 航空学；飞行术', 3620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laconic', 'adj. 简洁的，简明的', 3621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misbehavior', 'n. 品行不端；不礼貌（等于misbehaviour）', 3622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'randomly', 'adv. 随便地，任意地；无目的地，胡乱地；未加计划地', 3623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ultimatum', 'n. 最后通牒；最后结论；基本原理', 3624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reassure', 'v. 使…安心，使消除疑虑', 3625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lackadaisical', 'adj. 懒洋洋的；无精打采的；伤感的', 3626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anterior', 'adj. 前面的；先前的', 3627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affray', 'n. 滋事；骚乱；争论', 3628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erode', 'v. 腐蚀，侵蚀', 3629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'potion', 'n. 一剂；一服；饮剂', 3630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sedentary', 'adj. 久坐的；坐惯的；定栖的；静坐的', 3631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'animadversion', 'n. 批评；非难；评语', 3632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misinterpret', 'v. 曲解，误解', 3633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alto', 'n. 女低音；男声最高音；中音乐器 adj. 中音部的', 3634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'leaflet', 'n. 小叶；传单', 3635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interpose', 'v. 提出（异议等）；使插入；使干涉', 3636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anemometer', 'n. 风力计，[气象] 风速计', 3637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'munificent', 'adj. 慷慨的；丰厚的；宽宏的', 3638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocabulary', 'n. 词汇；词表；词汇量', 3639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bawl', 'v. 大叫；放声痛哭 n. 叫骂声', 3640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demographic', 'adj. 人口统计学的；人口学的', 3641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blazon', 'v. 宣布；装饰 n. 纹章；描绘', 3642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laggard', 'adj. 落后的；迟钝的；迟缓的 n. 落后者；迟钝者', 3643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excoriate', 'v. 严厉的责难；擦破的皮肤', 3644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convenient', 'adj. 方便的；[废语]适当的；[口语]近便的；实用的', 3645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'genial', 'adj. 亲切的，友好的；和蔼的；适宜的', 3646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subterfuge', 'n. 托词；借口；诡计', 3647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'meditate', 'v. 考虑；计划；企图', 3648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'characteristic', 'adj. 典型的；特有的；表示特性的 n. 特征；特性；特色', 3649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bungle', 'v. 笨手笨脚地做；把…搞糟 n. 粗劣；失败；笨拙', 3650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aspire', 'v. 渴望；立志；追求', 3651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'drudgery', 'n. 苦工，苦差事', 3652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'photosynthesis', 'n. 光合作用', 3653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disclaim', 'v. 否认，拒绝；放弃，弃权；拒绝承认', 3654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insulator', 'n. [物] 绝缘体；从事绝缘工作的工人', 3655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inevitable', 'adj. 必然的，不可避免的', 3656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enrapture', 'v. 使狂喜；使著迷', 3657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'baldness', 'n. 光秃；率直；枯燥', 3658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equipment', 'n. 设备，装备；器材', 3659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abject', 'adj. 卑鄙的；可怜的；不幸的；（境况）凄惨的，绝望的', 3660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissension', 'n. 纠纷；意见不合；争吵；倾轧', 3661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'validate', 'v. 证实，验证；确认；使生效', 3662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utopian', 'adj. 乌托邦的；空想的；理想化的 n. 空想家；乌托邦的居民', 3663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vertigo', 'n. 晕头转向，[临床] 眩晕', 3664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recruit', 'n. 招聘；新兵；新成员 v. 补充；聘用；征募；使…恢复健康', 3665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sear', 'v. 烤焦；使…枯萎 adj. 枯萎的；烤焦的 n. 烙印；烧焦痕迹', 3666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beset', 'v. 困扰；镶嵌；围绕', 3667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'battalion', 'n. 营，军营；军队，部队', 3668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'torpor', 'n. 不活泼；麻木；懒散，迟缓', 3669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rigorous', 'adj. 严格的，严厉的；严密的；严酷的', 3670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stupendous', 'adj. 惊人的；巨大的', 3671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commission', 'n. 委员会；佣金；犯；委任；委任状 v. 委任；使服役；委托制作', 3672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bureau', 'n. 局，处；衣柜；办公桌', 3673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barring', 'prep. 除非；不包括；除…以外 v. 阻拦（bar的ing形式） n. (Barring)人名；(德)巴林', 3674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fickle', 'adj. 浮躁的；易变的；变幻无常的', 3675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gnash', 'v. 咬牙切齿 n. 咬', 3676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ignoble', 'adj. 不光彩的；卑鄙的；卑贱的', 3677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'static', 'adj. 静态的；静电的；静力的 n. 静电；静电干扰', 3678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vexation', 'n. 苦恼；恼怒；令人烦恼的事', 3679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insensate', 'adj. 无感觉的；无情的；无生命的', 3680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hamper', 'v. 妨碍；束缚；使困累 n. 食盒，食篮；阻碍物', 3681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'narcissism', 'n. [心理] 自恋，自我陶醉', 3682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conscious', 'adj. 意识到的；故意的；神志清醒的', 3683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aloof', 'adj. 冷淡的；远离的；冷漠的 adv. 远离；避开地', 3684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antecede', 'v. 在之前；胜过；居前', 3685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exaggerate', 'v. 使扩大；使增大', 3686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'graphic', 'adj. 形象的；图表的；绘画似的', 3687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'expatriate', 'v. 使移居国外；流放，放逐；使放弃国籍 n. 被流放者；移居国外者 adj. 移居国外的；被流放的', 3688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'daunt', 'v. 使气馁，使畏缩；威吓 n. (Daunt)人名；(英)当特', 3689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adorn', 'v. 装饰；使生色 n. (Adorn)人名；(泰)阿隆', 3690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subdivide', 'v. 细分，再分', 3691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resurgent', 'adj. 复活的；复苏的 n. 复活者', 3692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apposite', 'adj. 适当的；贴切的', 3693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remission', 'n. 缓解；宽恕；豁免', 3694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serviceable', 'adj. 有用的，可供使用的；耐用的', 3695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lengthy', 'adj. 漫长的，冗长的；啰唆的', 3696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kismet', 'n. 天命；命运', 3697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immutable', 'adj. 不变的；不可变的；不能变的', 3698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedestal', 'n. 基架，基座；基础 vt. 搁在台上；支持；加座', 3699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unsavoury', 'adj. 难吃的；令人讨厌的', 3700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proficient', 'adj. 熟练的，精通的 n. 精通；专家，能手', 3701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'license', 'n. 执照，许可证；特许 v. 许可；特许；发许可证给', 3702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'communicative', 'adj. 交际的；爱说话的，健谈的；无隐讳交谈的', 3703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'landlord', 'n. 房东，老板；地主', 3704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diffusion', 'n. 扩散，传播；[光] 漫射', 3705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lifetime', 'n. 一生；寿命；终生；使用期 adj. 一生的；终身的', 3706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autumnal', 'adj. 秋天的；已过中年的', 3707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plaintiff', 'n. 原告', 3708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seed', 'n. 种子；根据；精液；萌芽；子孙；原由 v. 播种；结实；成熟；去…籽', 3709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'litigious', 'adj. 好诉讼的；好争论的', 3710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oxide', 'n. [化学] 氧化物', 3711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prevaricate', 'v. 搪塞；支吾其辞，闪烁其辞', 3712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'original', 'n. 原件；原作；原物；原型 adj. 原始的；最初的；独创的；新颖的', 3713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'periodicity', 'n. [数] 周期性；频率；定期性', 3714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suppress', 'v. 抑制；镇压；废止', 3715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'orifice', 'n. [机] 孔口', 3716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auditory', 'n. 听众；礼堂 adj. 听觉的；耳朵的', 3717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'implicate', 'v. 使卷入；涉及；暗指；影响', 3718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'progeny', 'n. 子孙；后裔；成果', 3719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'synonym', 'n. 同义词；同义字', 3720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'doctrinaire', 'adj. 教条主义的；空谈理论的 n. 教条主义者；空论家，纯理论家', 3721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coy', 'adj. 腼腆的；忸怩作态的；怕羞的 vi. 忸怩作态 vt. 爱抚 n. (Coy)人名；(法)库瓦；(英、德、西)科伊', 3722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discretion', 'n. 自由裁量权；谨慎；判断力；判定；考虑周到', 3723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'somnolent', 'adj. 催眠的，想睡的', 3724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapprochement', 'n. 友好；恢复邦交；友善关系的建立', 3725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compunction', 'n. 悔恨，后悔；内疚', 3726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquiesce', 'v. 默许；勉强同意', 3727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scrupulous', 'adj. 细心的；小心谨慎的；一丝不苟的', 3728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resilient', 'adj. 弹回的，有弹力的', 3729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vibration', 'n. 振动；犹豫；心灵感应', 3730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'replica', 'n. 复制品，复制物', 3731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'devious', 'adj. 偏僻的；弯曲的；不光明正大的', 3732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cacophonous', 'adj. 粗腔横调的；发音不和谐的', 3733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dauntless', 'adj. 无畏的；勇敢的；不屈不挠的', 3734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prudent', 'adj. 谨慎的；精明的；节俭的 n. (Prudent)人名；(法)普吕当', 3735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cylinder', 'n. 圆筒；汽缸；[数] 柱面；圆柱状物', 3736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beneficent', 'adj. 慈善的；善行的', 3737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vehement', 'adj. 激烈的，猛烈的；热烈的', 3738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'period', 'n. 周期，期间；时期；月经；课时；（语法学）句点，句号 adj. 某一时代的', 3739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scribe', 'n. 抄写员；作家；划线器 v. 写下，记下；用划线器划', 3740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thesis', 'n. 论文；论点', 3741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambrosial', 'adj. 特别美味的；芬香的', 3742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prankster', 'n. 爱开玩笑的人；顽皮的人；恶作剧的人', 3743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sound', 'v. 听（诊）；测量，测…深；使发声；试探；宣告 n. 声音，语音；噪音；海峡；吵闹；听力范围；[医] 探条 adj. 健全的，健康的；合理的；可靠的；有效彻底的 adv. 彻底地，充分地', 3744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crest', 'n. [物] 波峰；冠；山顶；顶饰 v. 到达绝顶；形成浪峰', 3745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'simile', 'n. 明喻；直喻', 3746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutron', 'n. [核] 中子', 3747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abomination', 'n. 厌恶；憎恨；令人厌恶的事物', 3748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'christen', 'v. 为…命名；为…施洗礼 n. (Christen)人名；(法、德、西、丹、挪)克里斯滕；(英)克里森', 3749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exorbitant', 'adj. （要价等）过高的；（性格等）过分的；不在法律范围之内的', 3750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acreage', 'n. 面积，英亩数', 3751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hurricane', 'n. 飓风，暴风', 3752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hirsute', 'adj. 多毛的；[昆] 有粗毛的', 3753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arrant', 'adj. 极恶的；声名狼藉的；彻头彻尾的', 3754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glycerol', 'n. [有化] 甘油；丙三醇', 3755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clairvoyance', 'n. 千里眼；异常的洞察力', 3756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'telepathy', 'n. 心灵感应；传心术', 3757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inspire', 'v. 激发；鼓舞；启示；产生；使生灵感', 3758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'censor', 'v. 审查，检查；检查和删节 n. 检查员；[心理] 潜意识压抑力；信件检查员', 3759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'profile', 'n. 侧面；轮廓；外形；剖面；简况 v. 描…的轮廓；扼要描述', 3760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reactor', 'n. [化工] 反应器；[核] 反应堆；起反应的人', 3761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contrition', 'n. 痛悔；悔悟', 3762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unilateral', 'adj. 单边的；[植] 单侧的；单方面的；单边音；（父母）单系的', 3763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vernal', 'adj. 春天的；和煦的；青春的', 3764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'condensation', 'n. 冷凝；凝结；压缩；缩合聚合', 3765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'callow', 'adj. 年轻而无经验的；羽毛未丰的 n. (Callow)人名；(英)卡洛', 3766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fluent', 'adj. 流畅的，流利的；液态的；畅流的', 3767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cabinet', 'n. 内阁；橱柜；展览艺术品的小陈列室 adj. 内阁的；私下的，秘密的', 3768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approval', 'n. 批准；认可；赞成', 3769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avocation', 'n. 副业；业余爱好；嗜好', 3770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precession', 'n. 岁差（等于precession of the equinoxes）；先行；优先', 3771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coincidence', 'n. 巧合；一致；同时发生', 3772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arboreal', 'adj. 树木的；栖息在树上的', 3773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exploit', 'v. 开发，开拓；剥削；开采 n. 勋绩；功绩', 3774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unit', 'n. 单位，单元；装置；[军] 部队；部件', 3775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misadventure', 'n. 灾难；不幸遭遇', 3776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nationality', 'n. 国籍，国家；民族；部落', 3777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valedictory', 'adj. 告别的 n. 告别辞', 3778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'usage', 'n. 使用；用法；惯例', 3779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cleanliness', 'n. 清洁', 3780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gossamer', 'n. 蛛丝；薄纱；小蜘蛛网 adj. 轻飘飘的；薄弱的', 3781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'purgatory', 'n. 炼狱；涤罪；暂时的苦难 adj. 涤罪的（等于purgative）', 3782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'felonious', 'adj. 凶恶的；重罪的；极恶的', 3783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'melodrama', 'n. 情节剧；音乐剧；耸人听闻的事件，闹剧', 3784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trapezoid', 'n. [数] 梯形；[数] 不规则四边形 adj. 梯形的；[数] 不规则四边形的', 3785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deficit', 'n. 赤字；不足额', 3786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissimilar', 'adj. 不同的', 3787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brokerage', 'n. 佣金；回扣；中间人业务', 3788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fracture', 'n. 破裂，断裂；[外科] 骨折 v. 破裂；折断', 3789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'modest', 'adj. 谦虚的，谦逊的；适度的；端庄的；羞怯的 n. (Modest)人名；(罗)莫代斯特；(德)莫德斯特；(俄)莫杰斯特', 3790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vaporize', 'v. 蒸发', 3791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prolix', 'adj. 冗长的；说话啰嗦的', 3792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'spectroscope', 'n. [光] 分光镜', 3793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elocutionist', 'n. 演说家；雄辩家；朗诵者', 3794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jocular', 'adj. 爱开玩笑的；打趣的；滑稽的', 3795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'focus', 'n. 焦点；中心；清晰；焦距 v. 使集中；使聚焦', 3796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unused', 'adj. 不用的；从未用过的', 3797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'betrothal', 'n. 订婚；婚约', 3798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'setback', 'n. 挫折；退步；逆流', 3799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stimulant', 'n. [药] 兴奋剂；刺激物；酒精饮料 adj. 激励的；使人兴奋的', 3800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dwindle', 'v. 减少；变小', 3801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'greedy', 'adj. 贪婪的；贪吃的；渴望的', 3802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slender', 'adj. 细长的；苗条的；微薄的', 3803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outcast', 'n. 流浪的人；被驱逐的人 adj. 被遗弃的；无家可归的；被逐出的', 3804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'curtail', 'v. 缩减；剪短；剥夺…特权等', 3805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'logical', 'adj. 合逻辑的，合理的；逻辑学的', 3806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transact', 'v. 交易；谈判', 3807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amenable', 'adj. 有责任的：顺从的，服从的；有义务的；经得起检验的', 3808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utilize', 'v. 利用', 3809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'educe', 'v. 引出；演绎；使显出', 3810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loathe', 'v. 讨厌，厌恶', 3811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foment', 'v. 煽动；挑起；热敷', 3812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'judicious', 'adj. 明智的；头脑精明的；判断正确的', 3813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'straightforward', 'adj. 简单的；坦率的；明确的；径直的 adv. 直截了当地；坦率地', 3814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anarchy', 'n. 无政府状态；混乱；无秩序', 3815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polarization', 'n. 极化；偏振；两极分化', 3816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emancipate', 'v. 解放；释放', 3817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'funnel', 'n. 漏斗；烟囱 v. 通过漏斗或烟囱等；使成漏斗形', 3818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'miscreant', 'adj. 异端的；邪道的；极恶的 n. 异端；恶棍；罪大恶极之人', 3819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parentage', 'n. 出身；亲子关系；门第；起源', 3820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'torpid', 'adj. 迟钝的，迟缓的；不活泼的；麻痹的；[生物] 蛰伏的', 3821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'galvanize', 'v. 镀锌；通电；刺激', 3822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pandemic', 'adj. （疾病等）（全国、全球i）流行的；普遍的 n. 流行性疾病', 3823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antonym', 'n. [语] 反义词', 3824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gusto', 'n. 爱好；由衷的高兴；嗜好', 3825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'zealot', 'n. 狂热者；犹太教狂热信徒', 3826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lifelong', 'adj. 终身的', 3827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gibber', 'v. 喋喋而言；胡扯 n. 三棱石；无法听懂的话', 3828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'furrow', 'n. 皱纹；犁沟；车辙 v. 犁；耕；弄绉', 3829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mirror', 'n. 镜子；真实的写照；榜样 v. 反射；反映', 3830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sardonic', 'adj. 讽刺的；嘲笑的，冷笑的', 3831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ravenous', 'adj. 贪婪的；渴望的；狼吞虎咽的', 3832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remorseless', 'adj. 冷酷的；不知过错的；坚持不懈的；不屈不挠的', 3833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chloroplast', 'n. [植] 叶绿体', 3834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'balk', 'n. 障碍；错误 v. 阻止；推诿；错过', 3835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penetrate', 'v. 渗透；穿透；洞察', 3836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cache', 'n. 电脑高速缓冲存储器；贮存物；隐藏处 v. 隐藏；窖藏', 3837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bale', 'n. 包；捆；灾祸；不幸 v. 将打包', 3838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nurture', 'v. 养育；鼓励；培植 n. 养育；教养；营养物', 3839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'levity', 'n. 多变；轻浮；轻率；不稳定', 3840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'practicable', 'adj. 可用的；行得通的；可实行的', 3841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transplant', 'v. 移植；迁移；使移居 n. 移植；移植器官；被移植物；移居者', 3842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'leg', 'n. 腿；支柱', 3843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'omnipresent', 'adj. 无所不在的', 3844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nickel', 'n. 镍；镍币；五分镍币 v. 镀镍于', 3845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bland', 'adj. 乏味的；温和的；冷漠的 vt. 使…变得淡而无味；除掉…的特性 vi. 变得平淡无奇；丧失特性 n. (Bland)人名；(英)布兰德', 3846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overleap', 'v. 越过；跳过；忽略', 3847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fractious', 'adj. 易怒的；倔强的，难以对待的', 3848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carbohydrate', 'n. [有化] 碳水化合物；[有化] 糖类', 3849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lethal', 'adj. 致命的，致死的 n. 致死因子', 3850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radar', 'n. [雷达] 雷达，无线电探测器', 3851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remote', 'adj. 遥远的；偏僻的；疏远的 n. 远程', 3852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chord', 'n. 弦；和弦；香水的基调', 3853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'explode', 'v. 爆炸，爆发；激增', 3854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commonplace', 'n. 老生常谈；司空见惯的事；普通的东西 adj. 平凡的；陈腐的', 3855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'synchronous', 'adj. 同步的；同时的', 3856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deceive', 'v. 欺骗；行骗', 3857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antibiotics', 'n. [药] 抗生素；抗生学', 3858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parochial', 'adj. 教区的；狭小的；地方范围的', 3859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'status', 'n. 地位；状态；情形；重要身份', 3860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'herald', 'n. 预兆，征兆；先驱；传令官；报信者 v. 通报；预示…的来临', 3861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'literature', 'n. 文学；文献；文艺；著作', 3862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'limitation', 'n. 限制；限度；极限；追诉时效；有效期限；缺陷', 3863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'biography', 'n. 传记；档案；个人简介', 3864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insensible', 'adj. 昏迷的；无知觉的；麻木不仁的', 3865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endurable', 'adj. 能忍耐的；可忍受的；能持久的', 3866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preparatory', 'adj. 预备的 n. 预科；预备学校', 3867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wavelength', 'n. [物] 波长', 3868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'statue', 'n. 雕像，塑像 vt. 以雕像装饰', 3869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barren', 'adj. 贫瘠的；不生育的；无益的；沉闷无趣的；空洞的 n. 荒地', 3870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transitory', 'adj. 短暂的，暂时的；瞬息的', 3871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presentiment', 'n. 预感', 3872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unkempt', 'adj. 蓬乱的，不整洁的；（言语等）粗野的', 3873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legislate', 'v. 用立法规定；通过立法', 3874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barrel', 'v. 把……装入桶内 n. 桶；枪管，炮管', 3875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'output', 'n. 输出，输出量；产量；出产 v. 输出', 3876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antemundane', '世界形成前的', 3877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'delineate', 'v. 描绘；描写；画…的轮廓', 3878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ferocious', 'adj. 残忍的；惊人的', 3879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laudable', 'adj. 值得赞赏的', 3880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anticyclone', 'n. 反气旋，反旋风；高气压', 3881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'manometer', 'n. 压力计；[流] 测压计；血压计', 3882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convert', 'v. 使转变；转换…；使…改变信仰 n. 皈依者；改变宗教信仰者', 3883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'desertification', 'n. （土壤）荒漠化；沙漠化（等于desertization）', 3884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proscribe', 'v. 剥夺……的公权；禁止', 3885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solution', 'n. 解决方案；溶液；溶解；解答', 3886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'modicum', 'n. 少量，一点点', 3887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beatify', 'v. 行宣福礼；使享福', 3888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transfigure', 'v. 使变形；使改观；美化；理想化', 3889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'veneer', 'n. 外表；虚饰；饰面；胶合板的一层；薄木片 v. 胶合；虚饰；给…镶以饰片', 3890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'devoid', 'adj. 缺乏的；全无的', 3891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affair', 'n. 事情；事务；私事；（尤指关系不长久的）风流韵事', 3892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carnivore', 'n. [动] 食肉动物；食虫植物', 3893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pellucid', 'adj. 透明的；清晰的；明了的', 3894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blase', 'adj. 玩厌了的，厌烦于享乐的 n. (Blase)人名；(德)布拉泽；(法)布拉斯', 3895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transverse', 'adj. 横向的；横断的；贯轴的 n. 横断面；贯轴；横肌', 3896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'veracious', 'adj. 诚实的；真实的', 3897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coalescence', 'n. 合并；联合；接合', 3898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'purport', 'v. 声称；意图；意指；打算 n. 意义，主旨；意图', 3899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'participate', 'v. 参与，参加；分享', 3900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ceremonious', 'adj. 隆重的；讲究仪式的；正式的', 3901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unspeakable', 'adj. 无法形容的；不能以言语表达的；坏透了的', 3902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anachronism', 'n. 时代错误；不合潮流的人或物', 3903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abnormal', 'adj. 反常的，不规则的；变态的', 3904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pressure', 'n. 压力；压迫，[物] 压强 v. 迫使；密封；使……增压', 3905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'palpable', 'adj. 明显的；可感知的；易觉察的', 3906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excerpt', 'n. 摘录，引用 v. 引用，摘录', 3907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aerial', 'adj. 空中的，航空的；空气的；空想的 n. [电讯] 天线', 3908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embarrass', 'v. 使局促不安；使困窘；阻碍', 3909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kinsfolk', 'n. 亲属；家属', 3910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regimen', 'n. [医] 养生法；生活规则；政体；支配', 3911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'Calvinism', 'n. 加尔文主义；加尔文教派', 3912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ampere', 'n. 安培（计算电流强度的标准单位）', 3913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coil', 'v. 盘绕，把…卷成圈 n. 线圈；卷', 3914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hesitation', 'n. 犹豫', 3915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'berth', 'n. 卧铺；停泊处，锚位；差事 v. 使……停泊；为……提供铺位', 3916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evict', 'v. 驱逐；逐出', 3917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'punitive', 'adj. 惩罚性的；刑罚的', 3918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ebb', 'n. 衰退；退潮；衰落 v. 衰退；减少；衰落；潮退', 3919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revelation', 'n. 启示；揭露；出乎意料的事；被揭露的真相', 3920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'triumph', 'n. 胜利，凯旋；欢欣 v. 获得胜利，成功', 3921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oblivious', 'adj. 遗忘的；健忘的；不注意的；不知道的', 3922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'principal', 'adj. 主要的；资本的 n. 首长；校长；资本；当事人', 3923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'spider', 'n. 蜘蛛；设圈套者；三脚架', 3924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tremor', 'n. [医] 震颤；颤动', 3925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frantic', 'adj. 狂乱的，疯狂的', 3926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conduit', 'n. [电] 导管；沟渠；导水管', 3927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pyre', 'n. 火葬用的柴堆', 3928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'duplicity', 'n. 口是心非；表里不一；不诚实', 3929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conflagration', 'n. 大火；快速燃烧；突发；冲突', 3930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supplicant', 'n. 恳求者，乞求者', 3931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tutorship', 'n. 辅导；教师职位', 3932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capitulate', 'v. 认输，屈服；屈从，停止反抗；有条件投降；让步', 3933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'despotic', 'adj. 暴虐的，暴君的；专横的', 3934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'withstand', 'v. 抵挡；禁得起；反抗', 3935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stringent', 'adj. 严格的；严厉的；紧缩的；短缺的', 3936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jubilation', 'n. 喜欢；庆祝；欢呼', 3937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ratio', 'n. 比率，比例', 3938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'persuade', 'v. 说服，劝说；使某人相信；劝某人做（不做）某事 adj. 空闲的，有闲的', 3939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'upbraid', 'v. 责骂；训斥', 3940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appendage', 'n. 附加物；下属；[动][解剖] 附器（如植物的枝叶和动物的腿尾）', 3941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'averse', 'adj. 反对的；不愿意的', 3942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'senator', 'n. 参议员；（古罗马的）元老院议员；评议员，理事', 3943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingratiate', 'v. 使迎合；使讨好；使逢迎', 3944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exuberant', 'adj. 繁茂的；生气勃勃的，充溢的', 3945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perjure', 'v. 作伪证；使发伪誓；使破坏誓言', 3946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nude', 'adj. 裸的，裸体的；无装饰的；与生俱有的 n. 裸体；裸体画', 3947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peak', 'n. 山峰；最高点；顶点；帽舌 v. 使达到最高点；使竖起 adj. 最高的；最大值的', 3948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reprieve', 'v. 缓期执行；暂时解救 n. 暂缓；缓刑', 3949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ignominious', 'adj. 可耻的；下流的', 3950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'midway', 'n. 中途；娱乐场 adj. 中途的 adv. 中途', 3951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affluence', 'n. 富裕；丰富；流入；汇聚', 3952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emaciated', 'adj. 瘦弱的；憔悴的 v. 憔悴；消瘦下去（emaciate的过去分词）', 3953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aqueduct', 'n. [水利] 渡槽；导水管；沟渠', 3954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collage', 'n. 抽象拚贴画（用报纸、布、压平的花等碎片拼合而成的） vt. 把…创作成拼贴画，拼贴', 3955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unveil', 'v. 使公之于众，揭开；揭幕', 3956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disastrous', 'adj. 灾难性的；损失惨重的；悲伤的', 3957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vestige', 'n. 遗迹；残余；退化的器官', 3958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tabulate', 'adj. 平板状的；有平面的 v. 使成平面；把…制成表格', 3959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'needlework', 'n. 刺绣，缝纫；女红的作品', 3960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fraternal', 'adj. 兄弟般的；友好的', 3961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commemorate', 'v. 庆祝，纪念；成为…的纪念', 3962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repine', 'v. 抱怨；不满', 3963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unanimous', 'adj. 全体一致的；意见一致的；无异议的', 3964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alienate', 'v. 使疏远，离间；让与', 3965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unscrupulous', 'adj. 肆无忌惮的；寡廉鲜耻的；不讲道德的', 3966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volume', 'n. 量；体积；卷；音量；大量；册 adj. 大量的 vi. 成团卷起 vt. 把…收集成卷', 3967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'debase', 'v. 降低；使…贬值；掺杂 n. (Debase)人名；(意)德巴塞', 3968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precede', 'v. 领先，在…之前；优于，高于', 3969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disagreeable', 'adj. 不愉快的；厌恶的；不为人喜的；难相处的；脾气坏的', 3970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heinous', 'adj. 可憎的；极凶恶的', 3971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distressed', 'adj. 痛苦的；忧虑的；贫困的；受损的 v. 使痛苦；使紧张；使困苦（distress的过去分词）', 3972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'expression', 'n. 表现，表示，表达；表情，脸色，态度，腔调，声调；式，符号；词句，语句，措辞，说法', 3973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'successor', 'n. 继承者；后续的事物', 3974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'counselor', 'n. 顾问；法律顾问；参事（等于counsellor）', 3975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supplicate', 'v. 恳求，哀求；恳请', 3976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ossify', 'v. 骨化；硬化；僵化', 3977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ablution', 'n. 洗礼；洗澡（常用复数）；斋戒沐浴', 3978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'balance', 'n. 平衡；余额；匀称 v. 使平衡；结算；使相称', 3979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propagate', 'v. 传播；传送；繁殖；宣传', 3980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approximately', 'adv. 大约，近似地；近于', 3981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sufficiency', 'n. 足量，充足；自满', 3982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collide', 'v. 碰撞；抵触，冲突', 3983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'squalid', 'adj. 肮脏的；污秽的；卑劣的', 3984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distillation', 'n. 精馏，蒸馏，净化；蒸馏法；精华，蒸馏物', 3985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superb', 'adj. 极好的；华丽的；宏伟的 n. (Superb)人名；(罗)苏佩尔布', 3986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contemptible', 'adj. 可鄙的；卑劣的；可轻视的', 3987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'breakdown', 'n. 故障；崩溃；分解；分类；衰弱；跺脚曳步舞', 3988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accountant', 'n. 会计师；会计人员', 3989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'colloquial', 'adj. 白话的；通俗的；口语体的', 3990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impale', 'v. 刺穿；钉住；使绝望', 3991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reclusive', 'adj. 隐居的；隐遁的', 3992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jingoism', 'n. 侵略主义；沙文主义；武力外交政策', 3993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ratify', 'v. 批准；认可', 3994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collier', 'n. 矿工；运煤船', 3995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brooch', 'n. （女用的）胸针，领针', 3996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bemoan', 'v. 惋惜；为…恸哭', 3997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arguable', 'adj. 可论证的；可议的；可疑的', 3998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nitrogen', 'n. [化学] 氮', 3999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legislative', 'adj. 立法的；有立法权的 n. 立法权；立法机构', 4000);
