INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'against', 'prep. 反对，违反；靠；倚；防备 adj. 不利的；对立的', 501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'discovery', 'n. 发现，发觉；被发现的事物', 502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'student', 'n. 学生；学者', 503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'November', 'n. 十一月', 504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Japanese', 'adj. 日本（人）的；日语的 n. 日本人；日语', 505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ink', 'v. 签署；涂墨水于 n. 墨水，墨汁；油墨', 506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'instruction', 'n. 指令，命令；指示；教导；用法说明', 507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'supper', 'n. 晚餐，晚饭；夜宵', 508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fisherman', 'n. 渔夫；渔人', 509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flower', 'n. 花；精华；开花植物 v. 成熟，发育；开花；繁荣；旺盛', 510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lot', 'n. 份额；许多；命运；阄 adv. （与形容词和副词连用）很，非常；（与动词连用）非常 pron. 大量，许多 v. 分组，把…划分（常与out连用）；把（土地）划分成块', 511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'or', 'conj. 或，或者；还是 n. (Or)人名；(中)柯(广东话·威妥玛)；(柬)奥；(土、匈、土库、阿塞、瑞典)奥尔', 512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'maybe', 'adv. 也许；可能；大概 n. 可能性；不确定性', 513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'duty', 'n. 责任；[税收] 关税；职务', 514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'count', 'v. 计算；认为 n. 计数；计算；伯爵', 515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thirty', 'n. 三十年代 num. 三十 adj. 三十个的', 516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'goal', 'n. 目标；球门，得分数；终点 vi. 攻门，射门得分', 517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dictionary', 'n. 字典；词典', 518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shirt', 'n. 衬衫；汗衫，内衣', 519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'meeting', 'n. 会议；会见；集会；汇合点 v. 会面；会合（meet的ing形式）', 520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'half', 'n. 一半；半场；半学年 adv. 一半地；部分地 adj. 一半的；不完全的；半途的', 521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'short', 'adj. 短的；不足的；矮的，低的 n. 短；缺乏；短路；短裤 adv. 不足；突然；唐突地', 522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tie', 'v. 系；约束；打结；与…成平局 n. 领带；平局；鞋带；领结；不分胜负', 523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hope', 'n. 希望；期望；信心 v. 希望；期望', 524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eighty', 'n. 八十；八十岁；八十年代 adj. 八十的，八十个的；八十岁的 num. 八十', 525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'private', 'adj. 私人的；私有的；私下的 n. 列兵；二等兵', 526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'prize', 'n. 奖品；奖赏；战利品 v. 珍视；捕获；估价 adj. 获奖的', 527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wife', 'n. 妻子，已婚妇女；夫人', 528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twelfth', 'adj. 第十二的，第十二个的；十二分之一的 n. 第十二；月的第十二日', 529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shorts', 'n. 短裤', 530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'write', 'v. 写，写字；写作，作曲；写信', 531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'energy', 'n. [物] 能量；精力；活力；精神', 532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sir', 'n. 先生；（用于姓名前）爵士；阁下；（中小学生对男教师的称呼）先生；老师', 533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'store', 'n. 商店；储备，贮藏；仓库 v. 贮藏，储存', 534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'grass', 'n. 草；草地，草坪 v. 放牧；使……长满草；使……吃草', 535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'soup', 'n. 汤，羹；马力 v. 加速；增加马力', 536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'street', 'n. 街道 adj. 街道的', 537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fact', 'n. 事实；实际；真相', 538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'help', 'v. 帮助；促进；治疗；补救 n. 帮助；补救办法；帮忙者；有益的东西', 539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'till', 'n. [地理][水文] 冰碛；放钱的抽屉；备用现金 prep. 直到 conj. 直到为止 v. 耕种；犁', 540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tale', 'n. 故事；传说；叙述；流言蜚语', 541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'alive', 'adj. 活着的；活泼的；有生气的', 542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'oil', 'n. 油；石油；油画颜料 v. 加油；涂油；使融化', 543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lovely', 'adj. 可爱的；令人愉快的；爱恋的；秀丽的，优美的 n. 美女；可爱的东西', 544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'role', 'n. 角色；任务', 545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'quiet', 'adj. 安静的；安定的；不动的；温顺的 n. 安静；和平 v. 使平息；安慰', 546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'test', 'n. 试验；检验 v. 试验；测试', 547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'include', 'v. 包含，包括', 548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plain', 'adj. 平的；简单的；朴素的；清晰的 n. 平原；无格式；朴实无华的东西 adv. 清楚地；平易地', 549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'somewhere', 'adv. 在某处；到某处 n. 某个地方', 550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'spirit', 'n. 精神；心灵；情绪；志气；烈酒 v. 鼓励；鼓舞；诱拐', 551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'office', 'n. 办公室；政府机关；官职；营业处', 552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'healthy', 'adj. 健康的，健全的；有益于健康的', 553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twentieth', 'n. 二十分之一 adj. 第二十的；二十分之一的 num. 第二十', 554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pear', 'n. [园艺] 梨树；梨子', 555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'smart', 'adj. 聪明的；巧妙的；敏捷的；厉害的；潇洒的；剧烈的；时髦的 n. (Smart)人名；(法)斯马尔；(英、德)斯马特', 556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'panda', 'n. 熊猫；猫熊', 557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'train', 'n. 火车；行列；长队；裙裾 v. 培养；训练；瞄准', 558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'park', 'n. 公园；[交] 停车场 v. 停放；放置；寄存', 559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'born', 'v. 出世（bear的过去分词） adj. 天生的 n. (Born)人名；(柬)邦；(英、西、俄、捷、德、瑞典、匈)博恩', 560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'progress', 'n. 进步，发展；前进 v. 前进，进步；进行', 561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'zebra', 'n. [脊椎] 斑马 adj. 有斑纹的', 562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nurse', 'v. 看护，护理；照顾；培养；给…喂奶 n. 护士；奶妈，保姆', 563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'promise', 'n. 许诺，允诺；希望 v. 允诺，许诺；给人以…的指望或希望', 564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'girl', 'n. 女孩；姑娘，未婚女子；女职员，女演员；（男人的）女朋友', 565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'traffic', 'n. 交通；运输；贸易；[通信] 通信量 v. 用…作交换；在…通行', 566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'translate', 'v. 翻译；转化；解释；转变为；调动', 567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'risk', 'n. 风险；危险；冒险 v. 冒…的危险', 568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'top', 'n. 顶部，顶端；上部；首席；陀螺 v. 高出，超越；结束；达到顶点 adj. 最高的，顶上的；头等的', 569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'candy', 'v. 用糖煮；使结晶为砂糖；美化 n. 糖果（等于sweets）；冰糖（等于sugar candy，rock candy）；毒品 adj. 新潮的（服饰）；甜言蜜语的', 570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'west', 'n. 西；西方；西部 adj. 西方的；朝西的 adv. 在西方；向西方；自西方', 571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shoulder', 'n. 肩，肩膀；肩部 v. 肩负，承担', 572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'successful', 'adj. 成功的；一帆风顺的', 573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dinner', 'n. 晚餐，晚宴；宴会；正餐', 574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'stranger', 'n. 陌生人；外地人；局外人', 575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'education', 'n. 教育；培养；教育学', 576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'war', 'n. 战争，斗争；军事，战术；冲突，对抗，竞争 v. 打仗，作战；对抗', 577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deep', 'n. 深处；深渊 adj. 深的；低沉的；深奥的 adv. 深入地；深深地；迟', 578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'watermelon', 'n. 西瓜', 579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'duck', 'n. 鸭子；鸭肉；（英）宝贝儿；零分 v. 闪避；没入水中', 580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'forward', 'adj. 向前的；早的；迅速的 adv. 向前地；向将来 v. 促进；转寄；运送 n. 前锋', 581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'climb', 'v. 爬；攀登；上升 n. 爬；攀登', 582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'immediately', 'adv. 立即，立刻；直接地 conj. 一…就', 583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chess', 'n. 国际象棋，西洋棋', 584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'discussion', 'n. 讨论，议论', 585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lamb', 'n. 羔羊，小羊；羔羊肉 v. 生小羊，产羔羊', 586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plenty', 'n. 丰富，大量；充足 adj. 足够的，很多的 adv. 足够', 587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'car', 'n. 汽车；车厢', 588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tidy', 'adj. 整齐的；相当大的 v. 整理；收拾；弄整齐 n. 椅子的背罩', 589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pink', 'n. 粉红色；化身，典范；石竹花；头面人物 v. 扎，刺，戳；使…变粉红色；使…面红耳赤 adj. 粉红的；比较激进的；石竹科的；脸色发红的', 590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'certain', 'adj. 某一；必然的；确信；无疑的；有把握的 pron. 某些；某几个 n. (Certain)人名；(葡)塞尔塔因；(法)塞尔坦', 591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'necessary', 'adj. 必要的；必需的；必然的 n. 必需品', 592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bridge', 'n. 桥；桥牌；桥接器；船桥 v. 架桥；渡过', 593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'level', 'n. 水平；标准；水平面 adj. 水平的；平坦的；同高的 v. 瞄准；拉平；变得平坦', 594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'son', 'n. 儿子；孩子（对年轻人的称呼）；男性后裔', 595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'available', 'adj. 可获得的；可购得的；可找到的；有空的', 596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pie', 'n. 馅饼；饼图；爱说话的人 vt. 使杂乱', 597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'population', 'n. 人口；[生物] 种群，[生物] 群体；全体居民', 598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'care', 'n. 关怀；照料；谨慎；忧虑 v. 照顾；关心；喜爱；顾虑', 599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ugly', 'adj. 丑陋的；邪恶的；令人厌恶的', 600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'luck', 'n. 运气；幸运；带来好运的东西 v. 靠运气，走运；凑巧碰上', 601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'close', 'adj. 紧密的；亲密的；亲近的 v. 关；结束；使靠近 adv. 紧密地 n. 结束', 602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'university', 'n. 大学；综合性大学；大学校舍', 603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pretty', 'adj. 漂亮的；可爱的；优美的 adv. 相当地；颇 n. 有吸引力的事物（尤指饰品）；漂亮的人', 604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'die', 'v. 死亡；凋零；熄灭 n. 冲模，钢模；骰子', 605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'round', 'n. 圆；循环；一回合；圆形物 adj. 圆的；完全的；大概的；肥胖的 adv. 在周围；迂回地；朝反方向；挨个 v. 完成；围捕；绕行；弄圆 prep. 附近；绕过；大约；在…周围', 606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thirsty', 'adj. 口渴的，口干的；渴望的，热望的', 607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'free', 'adj. 免费的；自由的，不受约束的；[化学] 游离的 v. 使自由，解放；释放 adv. 自由地；免费 n. (Free)人名；(英)弗里', 608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Atlantic', 'n. 大西洋 adj. 大西洋的', 609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ham', 'n. 火腿；业余无线电爱好者；蹩脚演员 v. 表演过火 adj. 过火的；做作的', 610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'comfortable', 'adj. 舒适的，舒服的 n. 盖被', 611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'silence', 'n. 沉默；寂静；缄默；不谈；无声状态 v. 使沉默；使安静；压制；消除噪音 int. 安静！；别作声！', 612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deaf', 'adj. 聋的', 613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'father', 'n. 父亲，爸爸；神父；祖先；前辈 v. 发明，创立；当…的父亲', 614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'circle', 'n. 循环，周期；圆；圈子；圆形物 v. 盘旋，旋转；环行', 615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wealth', 'n. 财富；大量；富有', 616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'then', 'adv. 然后；那么；于是；当时；此外 n. 那时 conj. 然后，当时', 617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bank', 'n. 银行；岸；浅滩；储库 v. 将…存入银行；倾斜转弯', 618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dog', 'n. 狗；丑女人；卑鄙的人；(俚)朋友 v. 跟踪；尾随', 619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'difficulty', 'n. 困难，困境', 620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ear', 'n. 耳朵；穗；听觉；倾听 vi. （美俚）听见；抽穗', 621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kick', 'v. 踢；反冲，朝后座 n. 踢；反冲，后座力', 622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'alone', 'adj. 独自的；单独的；孤独的 adv. 独自地；单独地', 623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'proper', 'adj. 适当的；本身的；特有的；正派的 adv. 完全地 n. (Proper)人名；(英、德)普罗珀', 624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fast', 'adj. 快速的，迅速的；紧的，稳固的 adv. 迅速地；紧紧地；彻底地 v. 禁食，斋戒 n. 斋戒；绝食', 625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'litter', 'n. 垃圾；轿，担架；一窝（动物的幼崽）；凌乱 v. 乱丢；给…垫褥草；把…弄得乱七八糟', 626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'water', 'n. 水；海水；雨水；海域，大片的水 v. 使湿；供以水；给…浇水', 627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'station', 'n. 车站；驻地；地位；身份 v. 配置；安置；驻扎', 628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'strawberry', 'n. 草莓；草莓色', 629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'afraid', 'adj. 害怕的；恐怕；担心的', 630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'brain', 'n. 头脑，智力；脑袋 v. 猛击…的头部', 631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coat', 'n. 外套 v. 覆盖…的表面', 632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'none', 'pron. 没有人；一个也没有；没有任何东西 adj. 没有的，一点没有的 adv. 决不，一点也不 n. (None)人名；(葡、罗)诺内；(日)野根(姓)', 633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'require', 'v. 需要；要求；命令', 634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dumpling', 'n. 饺子，汤团；面团布丁', 635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drop', 'v. 滴；使降低；使终止；随口漏出 n. 滴；落下；空投；微量；滴剂', 636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'almost', 'adv. 差不多，几乎', 637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'second', 'n. 秒；第二名；瞬间；二等品 v. 支持 adj. 第二的；次要的；附加的 num. 第二 adv. 第二；其次；居第二位', 638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'friendship', 'n. 友谊；友爱；友善', 639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'traditional', 'adj. 传统的；惯例的', 640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'copy', 'v. 复制；复印；抄袭 n. 副本；一册；摹仿', 641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seem', 'v. 似乎；像是；装作 n. (Seem)人名；(英)西姆', 642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'history', 'n. 历史，历史学；历史记录；来历', 643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'list', 'n. [计] 列表；清单；目录 v. 列于表上', 644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beyond', 'prep. 超过；越过；那一边；在较远的一边 adv. 在远处；在更远处 n. 远处', 645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Monday', 'n. 星期一', 646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'season', 'n. 时期；季节；赛季 v. 给…调味；使适应', 647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pronounce', 'v. 发音；宣判；断言', 648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'few', 'adj. 很少的；几乎没有的 pron. 很少 n. 很少数', 649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'among', 'prep. 在…中间；在…之中', 650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'again', 'adv. 又，此外；再一次；再说；增加 n. （英、保）阿盖恩', 651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'reach', 'v. 达到；延伸；伸出手；传开 n. 范围；延伸；河段；横风行驶', 652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'research', 'n. 研究；调查 v. 研究；调查', 653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'text', 'n. [计] 文本；课文；主题 v. 发短信', 654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'autumn', 'n. 秋天；成熟期；渐衰期，凋落期 adj. 秋天的，秋季的', 655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fit', 'v. 安装；使……适应；使……合身；与……相符 adj. 健康的；合适的；恰当的；准备好的 n. 合身；发作；痉挛', 656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'quite', 'adv. 很；相当；完全', 657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'high', 'adj. 高的；高级的；崇高的；高音调的 n. 高水平；天空；由麻醉品引起的快感；高压地带 adv. 高；奢侈地', 658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'army', 'n. 陆军，军队', 659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'silly', 'adj. 愚蠢的；不明事理的；没头脑的 n. 傻瓜', 660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'airline', 'n. 航空公司；航线 adj. 航线的', 661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bright', 'adj. 明亮的，鲜明的；聪明的；愉快的 adv. 明亮地；光明地；欢快地 n. 车头灯光', 662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'than', 'conj. 比（用于形容词、副词的比较级之后）；除…外（用于other等之后）；与其…（用于 rather等之后）；一…就（用于 no sooner等之后） prep. 比；超过 n. (Than)人名；(老、柬、德)坦；(缅)丹', 663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Japan', 'n. 日本（东亚国家名）', 664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'captain', 'n. 队长，首领；船长；上尉；海军上校 v. 指挥；率领', 665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'whenever', 'conj. 每当；无论何时 adv. 不论何时；随便什么时候', 666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'road', 'n. 公路，马路；道路；手段 vt. （狗）沿臭迹追逐（猎物） adj. （美）巡回的', 667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fourteen', 'num. 十四；十四个；第十四 n. 十四的记号；十四岁；十四点钟；十五世纪', 668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'trip', 'v. 绊倒；远足；犯错误；轻快地走 n. 旅行；绊倒；差错', 669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bike', 'n. 自行车；脚踏车 v. 骑自行车（或摩托车）', 670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'robot', 'n. 机器人；遥控设备，自动机械；机械般工作的人', 671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sale', 'n. 销售；出售；拍卖；销售额；廉价出售', 672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'symbol', 'n. 象征；符号；标志', 673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weekend', 'n. 周末，周末休假；周末聚会 adj. 周末的，周末用的 v. 度周末', 674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'warm', 'adj. 温暖的；热情的 v. 同情；激动；变温暖 n. 取暖；加热', 675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dollar', 'n. 美元', 676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'useless', 'adj. 无用的；无效的', 677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cancer', 'n. 癌症；恶性肿瘤', 678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'there', 'adv. 在那里；在那边；在那点上 int. 你瞧 n. 那个地方', 679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'blood', 'n. 血，血液；血统 v. 从…抽血；使先取得经验', 680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'separate', 'v. 使分离；使分开；使分居 adj. 单独的；分开的；不同的；各自的； n. 分开；抽印本', 681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'situation', 'n. 情况；形势；处境；位置', 682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yourselves', 'pron. 你们自己；你们本人（yourself的复数）', 683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nobody', 'pron. 无人，没有人；没有任何人 n. 无名小卒；小人物', 684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'horse', 'n. 马；骑兵；脚架；海洛因 v. 使骑马；系马于；捉弄', 685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pleasant', 'adj. 令人愉快的，舒适的；讨人喜欢的，和蔼可亲的 n. (Pleasant)人名；(英)普莱曾特', 686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lock', 'v. 锁，锁上；隐藏 n. 锁；水闸；刹车', 687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eraser', 'n. 橡皮；擦除器；[计] 清除器', 688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shower', 'n. 淋浴；（倾泻般出现的）一阵，一大批；阵雨 v. 大量地给予；把……弄湿', 689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'reply', 'v. 回答；[法] 答辩；回击 n. 回答；[法] 答辩', 690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'raincoat', 'n. （美）雨衣', 691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sixth', 'n. 月的第六日，（与the连用的）第六个；六分之一 adj. （与 the 连用）第六的，第六个的；六分之一的', 692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'regret', 'n. 遗憾；抱歉；悲叹 v. 后悔；惋惜；哀悼', 693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dress', 'v. 给…穿衣 n. 连衣裙；女装', 694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'crazy', 'adj. 疯狂的；狂热的，着迷的', 695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'learn', 'v. 学习；得知；认识到', 696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ice', 'n. 冰；冰淇淋；矜持；（俚）钻石 v. 冰镇；结冰 adj. 冰的', 697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'treasure', 'n. 财富，财产；财宝；珍品 v. 珍爱；珍藏', 698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'page', 'n. 页；记录；大事件，时期；男侍者 v. 给…标页码', 699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plastic', 'adj. 塑料的；（外科）造型的；可塑的 n. 塑料制品；整形；可塑体', 700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rain', 'n. 雨；下雨；雨天；雨季 v. 下雨；降雨', 701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hotel', 'n. 旅馆，饭店；客栈 vt. 使…在饭店下榻 vi. 进行旅馆式办公', 702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'noodle', 'n. 面条；笨蛋', 703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'riddle', 'v. 解谜；给出谜；充满于 n. 谜语；粗筛；谜一般的人、东西、事情等', 704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thirteen', 'n. 十三；十三岁；十三个 num. 十三 adj. 十三的；十三个的', 705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'least', 'adj. 最小的；最少的（little的最高级） adv. 最小；最少 n. 最小；最少', 706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'guard', 'n. 守卫；警戒；护卫队；防护装置 v. 警惕', 707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'couple', 'n. 对；夫妇；数个 v. 结合；成婚', 708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'describe', 'v. 描述，形容；描绘', 709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'air', 'n. 空气，大气；天空；样子；曲调 v. 使通风，晾干；夸耀', 710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hate', 'v. 憎恨；厌恶；遗憾 n. 憎恨；反感', 711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'small', 'adj. 少的，小的；微弱的；几乎没有的；不重要的；幼小的 adv. 小小地；卑鄙地 n. 小件物品；矮小的人', 712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sight', 'n. 视力；景象；眼界；见解 v. 看见；瞄准 adj. 见票即付的；即席的', 713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'avoid', 'v. 避免；避开，躲避；消除', 714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'science', 'n. 科学；技术；学科；理科', 715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hungry', 'adj. 饥饿的；渴望的；荒年的；不毛的', 716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'present', 'v. 提出；介绍；呈现；赠送 adj. 现在的；出席的 n. 现在；礼物；瞄准', 717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'madam', 'n. 夫人；女士；鸨母', 718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bathroom', 'n. 浴室；厕所；盥洗室', 719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'goat', 'n. 山羊；替罪羊（美俚）；色鬼（美俚）', 720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pass', 'n. 及格；经过；护照；途径；传球 v. 经过；传递；变化；终止', 721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'boy', 'n. 男孩；男人', 722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'young', 'adj. 年轻的；初期的；没有经验的 n. 年轻人；（动物的）崽，仔', 723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'jeans', 'n. 牛仔裤；工装裤', 724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'model', 'n. 模型；典型；模范；模特儿；样式 v. 模拟；塑造；模仿 adj. 模范的；作模型用的', 725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'like', 'v. 喜欢；想；愿意 prep. 像；如同 adj. 同样的；相似的 n. 爱好；同样的人或物 adv. 可能 conj. 好像', 726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'push', 'v. 推动，增加；对…施加压力，逼迫；按；说服 n. 推，决心；大规模攻势；矢志的追求', 727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'happy', 'adj. 幸福的；高兴的；巧妙的 n. (Happy)人名；(英、瑞典、喀)哈皮', 728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pronunciation', 'n. 发音；读法', 729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twice', 'adv. 两次；两倍', 730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'toilet', 'n. 厕所，盥洗室；梳妆，打扮 vi. 梳妆，打扮 vt. 给…梳妆打扮', 731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'husband', 'v. 节约地使用（或管理） n. 丈夫', 732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'herself', 'pron. 她自己（she的反身代词）；她亲自', 733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'earth', 'n. 地球；地表，陆地；土地，土壤；尘事，俗事；兽穴 v. 把（电线）[电] 接地；盖（土）；追赶入洞穴', 734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'elder', 'n. 老人；长辈；年长者；父辈 adj. 年长的；年龄较大的；资格老的', 735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'flu', 'n. 流感', 736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'card', 'n. 卡片；纸牌；明信片 v. 记于卡片上', 737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'encourage', 'v. 鼓励，怂恿；激励；支持', 738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wine', 'n. 酒，葡萄酒；紫红色 v. 喝酒', 739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'afternoon', 'n. 午后，下午', 740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'force', 'n. 力量；武力；军队；魄力 v. 促使，推动；强迫；强加', 741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'east', 'n. 东方；东风；东方国家 adj. 东方的；向东的；从东方来的 adv. 向东方，在东方', 742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'daily', 'adj. 日常的；每日的 n. 日报；朝来夜去的女佣 adv. 日常地；每日；天天', 743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'gun', 'n. 枪支；枪状物；持枪歹徒 v. 用枪射击；加大油门快速前进', 744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'remain', 'v. 保持；依然；留下；剩余；逗留；残存 n. 遗迹；剩余物，残骸', 745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'language', 'n. 语言；语言文字；表达能力', 746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'anywhere', 'adv. 在任何地方；无论何处 n. 任何地方', 747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lesson', 'n. 教训；课 vt. 教训；上课', 748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'save', 'v. 节省；保存；储蓄；解救 prep. 除之外 n. 救援', 749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cousin', 'n. 堂兄弟姊妹；表兄弟姊妹', 750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'granddaughter', 'n. 孙女；外孙女', 751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'class', 'n. 阶级；班级；种类；班；等级 v. 分类；把…分等级；把…归入某等级，把…看作（或分类、归类）；把…编入某一班级 adj. 极好的；很好的，优秀的，出色的', 752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'violin', 'n. 小提琴；小提琴手', 753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'me', 'pron. 我（宾格） n. 自我；极端自私的人；自我的一部分', 754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sound', 'v. 听（诊）；测量，测…深；使发声；试探；宣告 n. 声音，语音；噪音；海峡；吵闹；听力范围；[医] 探条 adj. 健全的，健康的；合理的；可靠的；有效彻底的 adv. 彻底地，充分地', 755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beef', 'n. 牛肉；肌肉；食用牛；牢骚 v. 抱怨，告发；发牢骚', 756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'market', 'n. 市场；行情；股票市场；市面；集市；销路；商店 v. 在市场上出售', 757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'airport', 'n. 机场；航空站', 758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'marry', 'v. 嫁；娶；与……结婚 n. (Marry)人名；(阿拉伯)马雷；(法)马里', 759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pencil', 'n. 铅笔；笔状物 v. 用铅笔写；用眉笔涂', 760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'first', 'adv. 第一；首先；优先；宁愿 n. 第一；开始；冠军 adj. 第一的；基本的；最早的 num. 第一', 761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thousand', 'n. 一千；一千个；许许多多 adj. 成千的；无数的', 762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'next', 'adv. 然后；下次；其次 adj. 下一个的；其次的；贴近的 n. 下一个 prep. 靠近；居于…之后', 763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'strange', 'adj. 奇怪的；陌生的；外行的 adv. 奇怪地；陌生地，冷淡地 n. (Strange)人名；(英)斯特兰奇；(瑞典、塞)斯特朗格', 764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'them', 'pron. 他们；它们；她们 n. (Them)人名；(老)探', 765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twelve', 'n. 十二；十二个 num. 十二；十二个 adj. 十二的；十二个的', 766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'zero', 'n. 零点，零度 num. 零', 767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ill', 'adj. 生病的；坏的；邪恶的；不吉利的 adv. 不利地；恶劣地；几乎不 n. 疾病；不幸', 768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'surface', 'n. 表面；表层；外观 adj. 表面的，肤浅的 v. 浮出水面', 769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chemistry', 'n. 化学；化学过程', 770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'twenty', 'n. 二十；二十年代 num. 二十 adj. 二十的', 771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'suggestion', 'n. 建议；示意；微量，细微的迹象', 772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sail', 'v. 航行；启航，开船 n. 帆，篷；航行', 773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'whether', 'conj. 是否；不论 pron. 两个中的哪一个', 774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'final', 'adj. 最终的；决定性的；不可更改的 n. 决赛；期末考试；当日报纸的末版', 775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'stay', 'v. 停留；坚持；暂住；停下 n. 逗留；停止；支柱', 776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'because', 'conj. 因为', 777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'interview', 'n. 接见，采访；面试，面谈 v. 采访；接见；对…进行面谈；对某人进行面试', 778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'state', 'n. 国家；州；情形 v. 规定；声明；陈述 adj. 国家的；州的；正式的', 779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Wheel', 'n. 车轮；方向盘；转动 v. 转动；使变换方向；给…装轮子', 780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'which', 'pron. 哪/那一个；哪/那一些 adj. 哪一个；哪一些', 781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'still', 'adv. 仍然；更；静止地 adj. 静止的，不动的；寂静的，平静的；不起泡的 n. 寂静；剧照；蒸馏室 conj. 仍然；但是；尽管如此 v. 蒸馏；使…静止；使…平静下来', 782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'create', 'v. 创造，创作；造成', 783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'in', 'prep. 按照（表示方式）；从事于；在…之内 adv. 进入；当选；（服装等）时髦；在屋里 adj. 在里面的；时髦的 n. 执政者；门路；知情者', 784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worker', 'n. 工人；劳动者；职蚁', 785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'these', 'pron. 这些 adj. 这些的', 786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'solid', 'adj. 固体的；可靠的；立体的；结实的；一致的 n. 固体；立方体', 787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'shape', 'n. 形状；模型；身材；具体化 v. 形成；塑造，使成形；使符合', 788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'homework', 'n. 家庭作业，课外作业', 789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chant', 'n. 圣歌；赞美诗 v. 唱；诵扬', 790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'relation', 'n. 关系；叙述；故事；亲属关系', 791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'date', 'n. 日期；约会；年代；枣椰子 v. 过时；注明日期；始于（某一历史时期）', 792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'drug', 'n. 药；毒品；麻醉药；滞销货 v. 使服麻醉药；使服毒品；掺麻醉药于', 793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'plate', 'n. 碟；金属板；金属牌；感光底片 v. 电镀；给…装甲', 794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'policy', 'n. 政策，方针；保险单', 795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sea', 'n. 海；海洋；许多；大量', 796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'right', 'adj. 正确的；直接的；右方的 v. 复正；恢复平稳 n. 正确；右边；正义 adv. 正确地；恰当地；彻底地', 797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'percent', 'n. 百分比，百分率；部分；百分数 adj. 百分之…的 adv. 以百分之…地', 798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'corner', 'n. 角落，拐角处；地区，偏僻处；困境，窘境 v. 囤积；相交成角', 799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'form', 'n. 形式，形状；形态，外形；方式；表格 v. 构成，组成；排列，组织；产生，塑造', 800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pity', 'n. 怜悯，同情；遗憾 v. 对……表示怜悯；对……感到同情', 801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lunch', 'n. 午餐 v. 吃午餐；供给午餐', 802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'towel', 'n. 毛巾，手巾；[纸] 纸巾 v. 用毛巾擦', 803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'even', 'adj. [数] 偶数的；平坦的；相等的 adv. 甚至；即使；还；实际上 v. 使平坦；使相等 n. (Even)人名；(法)埃旺；(德)埃文；(英)埃文', 804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Christmas', 'n. 圣诞节；圣诞节期间', 805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weekday', 'n. 平日，普通日；工作日', 806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'so', 'adv. 如此，这么；确是如此 conj. 所以；因此 pron. 这样 n. (So)人名；(柬)索', 807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sad', 'adj. 难过的；悲哀的，令人悲痛的；凄惨的，阴郁的（形容颜色）', 808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dry', 'adj. 干的；口渴的；枯燥无味的；禁酒的 v. 把…弄干 n. 干涸', 809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'garden', 'n. 花园；菜园 v. 栽培花木', 810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tiny', 'adj. 微小的；很少的 n. (Tiny)人名；(葡、印)蒂尼', 811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'can', 'v. 将…装入密封罐中保存 aux. 能； 能够； 可以； 可能 n. 罐头； （用金属或塑料制作的）容器； （马口铁或其他金属制作的）食品罐头', 812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'mile', 'n. 英里；一英里赛跑；较大的距离', 813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Canada', 'n. 加拿大（北美洲国家）', 814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'off', 'prep. 离开；脱落 adv. 切断；走开 adj. 远离的；空闲的', 815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'allow', 'v. 允许；给予；认可', 816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'invite', 'v. 邀请，招待；招致 n. 邀请', 817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thought', 'n. 思想；思考；想法；关心 v. 想，思考；认为（think的过去式和过去分词）', 818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'handsome', 'adj. （男子）英俊的；可观的；大方的，慷慨的；健美而端庄的', 819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'housework', 'n. 家务事', 820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'myself', 'pron. 我自己；我亲自；我的正常的健康状况和正常情绪', 821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'April', 'n. 四月', 822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'balloon', 'v. 激增；膨胀如气球 n. 气球 adj. 像气球般鼓起的', 823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sky', 'n. 天空；顶点 v. 把…投向空中；把…挂得过高', 824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'storm', 'n. 暴风雨；大动荡 v. 起风暴；横冲直撞；狂怒咆哮', 825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'biscuit', 'n. 小点心，饼干', 826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'down', 'adv. 向下，下去；在下面 adj. 向下的 n. 软毛，绒毛；[地质] 开阔的高地 prep. 沿着，往下 v. 打倒，击败', 827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Asian', 'n. 亚洲人 adj. 亚洲的；亚洲人的', 828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bill', 'n. [法] 法案；广告；账单；[金融] 票据；钞票；清单 v. 宣布；开账单；用海报宣传', 829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'enjoy', 'v. 欣赏，享受；喜爱；使过得快活', 830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'heart', 'n. 心脏；感情；勇气；心形；要点 vt. 鼓励；铭记 vi. 结心', 831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'south', 'n. 南方，南边；南部 adv. 在南方，向南方 adj. 南的，南方的', 832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lively', 'adj. 活泼的；生动的；真实的；生气勃勃的 n. (Lively)人名；(英)莱夫利', 833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rapid', 'adj. 迅速的，急促的；飞快的；险峻的 n. 急流；高速交通工具，高速交通网', 834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'frog', 'n. 青蛙；[铁路] 辙叉；饰扣 v. 捕蛙', 835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'control', 'n. 控制；管理；抑制；操纵装置 v. 控制；管理；抑制', 836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'toothache', 'n. [口腔] 牙痛', 837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'clever', 'adj. 聪明的；机灵的；熟练的', 838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'raise', 'v. 提高；筹集；养育；升起 n. 高地；上升；加薪', 839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lead', 'n. 领导；铅；导线；榜样 v. 领导；致使；引导；指挥 adj. 带头的；最重要的', 840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'deal', 'v. 处理；给予；分配；发牌 n. 交易；（美）政策；待遇；份量', 841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'package', 'n. 包，包裹；套装软件，[计] 程序包 adj. 一揽子的 v. 打包；将…包装', 842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'what', 'pron. 什么；多么；多少 adj. 什么；多么；何等 adv. 到什么程度，在哪一方面 int. 什么；多么', 843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pig', 'n. 猪；猪肉 v. 生小猪；像猪一样过活', 844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'head', 'n. 头；头痛；上端；最前的部分；理解力 v. 前进；用头顶；作为…的首领；站在…的前头；给…加标题 adj. 头的；主要的；在顶端的', 845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'experience', 'n. 经验；经历；体验 v. 经验；经历；体验', 846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'punish', 'v. 惩罚；严厉对待；贪婪地吃喝', 847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'develop', 'v. 开发；进步；使成长；使显影', 848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'birthday', 'n. 生日，诞辰；诞生的日子', 849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'scientist', 'n. 科学家', 850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fail', 'v. 失败，不及格；破产；缺乏；衰退 n. 不及格', 851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'swing', 'n. 摇摆；摆动；秋千；音律；涨落 v. 摇摆；转向；悬挂；大摇大摆地行走 adj. 旋转的；悬挂的；强节奏爵士音乐的', 852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'everyone', 'pron. 每个人；人人 n. 每个人', 853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'this', 'pron. 这；这个；这里 adj. 这；本；这个；今 adv. 这样地；这么 n. (This)人名；(法)蒂斯', 854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'milk', 'n. 牛奶；乳状物 v. 榨取；挤…的奶', 855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'waste', 'n. 浪费；废物；荒地；损耗；地面风化物 v. 浪费；消耗；使荒芜 adj. 废弃的；多余的；荒芜的', 856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'absent', 'adj. 缺席的；缺少的；心不在焉的；茫然的 v. 使缺席', 857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tomorrow', 'n. 明天；未来 adv. 明天；未来地（等于to-morrow）', 858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Internet', 'n. 因特网', 859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'toothbrush', 'n. 牙刷', 860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'near', 'adj. 近的；亲近的；近似的 adv. 近；接近 prep. 靠近；近似于', 861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'body', 'n. 身体；主体；大量；团体；主要部分 v. 赋以形体', 862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'baby', 'n. 婴儿，婴孩；孩子气的人 v. 纵容，娇纵；把……当婴儿般对待 adj. 婴儿的；幼小的', 863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ceiling', 'n. 天花板；上限', 864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'honest', 'adj. 诚实的，实在的；可靠的；坦率的', 865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'middle', 'adj. 中间的，中部的；中级的，中等的 n. 中间，中央；腰部', 866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'away', 'adv. 离去，离开；在远处', 867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'meaning', 'n. 意义；含义；意图 adj. 意味深长的 v. 意味；意思是（mean的ing形式）', 868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'evening', 'n. 晚上；傍晚；（联欢性的）晚会；后期 adj. 在晚上的；为晚上的；晚上用的 int. 晚上好（等于good evening）', 869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'beautiful', 'adj. 美丽的', 870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'gift', 'n. 礼物；天赋；赠品 v. 赋予；向…赠送', 871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pork', 'n. 猪肉 vt. 与女子性交', 872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'try', 'v. 试图，努力；试验；审判；考验 n. 尝试；努力；试验', 873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'monkey', 'n. 猴子；顽童 v. 胡闹；捣蛋', 874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'famous', 'adj. 著名的；极好的，非常令人满意的', 875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'green', 'adj. 绿色的；青春的 n. 绿色；青春 v. 使…变绿色', 876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'line', 'n. 路线，航线；排；绳 v. 排成一行；划线于；以线条标示；使…起皱纹', 877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'factory', 'n. 工厂；制造厂；代理店', 878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Saturday', 'n. 星期六', 879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'trouble', 'n. 麻烦；烦恼；故障；动乱 v. 麻烦；使烦恼；折磨', 880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'careful', 'adj. 仔细的，小心的', 881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cabbage', 'n. 卷心菜，甘蓝菜，洋白菜；（俚)脑袋；（非正式、侮辱）植物人（常用于英式英语）；（俚）钱，尤指纸币（常用于美式俚语）', 882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'winner', 'n. 胜利者', 883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'protect', 'v. 保护，防卫；警戒', 884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'correct', 'v. 改正；告诫 adj. 正确的；恰当的；端正的', 885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'want', 'v. 需要；希望；应该；缺少 n. 需要；缺乏；贫困；必需品', 886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'rest', 'v. 使休息，使轻松；把…寄托于 n. 休息，静止；休息时间；剩余部分；支架', 887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'difficult', 'adj. 困难的；不随和的；执拗的', 888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'accent', 'n. 口音；重音；强调；特点；重音符号 v. 强调；重读；带…口音讲话', 889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'oneself', 'pron. 自己；亲自', 890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coal', 'v. 上煤；加煤 n. 煤；煤块；木炭', 891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'coin', 'v. 铸造（货币）；杜撰，创造 n. 硬币，钱币', 892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'real', 'adj. 实际的；真实的；实在的 adv. 真正地；确实地 n. 现实；实数', 893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'though', 'adv. 可是，虽然；不过；然而 conj. 虽然；尽管 prep. 但', 894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'divide', 'v. 划分；除；分开；使产生分歧 n. [地理] 分水岭，分水线', 895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'leaf', 'n. 叶子；（书籍等的）一张；扇页 v. 生叶；翻书页', 896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fourth', 'adj. 第四的，第四个的；四分之一的 n. 第四，月的第四日；四分之一 num. 第四', 897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'treatment', 'n. 治疗，疗法；处理；对待', 898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'skill', 'n. 技能，技巧；本领，技术', 899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'their', 'pron. 他们的，她们的；它们的 n. (Their)人名；(英)蒂尔；(芬、瑞典)泰尔', 900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'danger', 'n. 危险；危险物，威胁', 901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cross', 'n. 交叉，十字；十字架，十字形物 v. 交叉；杂交；横过 adj. 交叉的，相反的；乖戾的；生气的', 902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'point', 'n. 要点；得分；标点；[机] 尖端 v. 指向；弄尖；加标点于', 903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'now', 'adv. 现在；如今；立刻 adj. 现在的 n. 现在；目前 conj. 由于；既然', 904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'magic', 'n. 巫术；魔法；戏法 adj. 不可思议的；有魔力的；魔术的', 905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'would', 'aux. 将，将要；愿意 v. will的过去式', 906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cinema', 'n. 电影；电影院；电影业，电影制作术', 907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'downstairs', 'adv. 在楼下 adj. 楼下的 n. 楼下', 908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'neither', 'conj. 也不；既不 adv. 两个都不；既不……也不 adj. 两者都不的 pron. 两者都不', 909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'dirty', 'adj. 下流的，卑鄙的；肮脏的；恶劣的；暗淡的 v. 弄脏', 910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'breathe', 'v. 呼吸；低语；松口气；（风）轻拂', 911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'neck', 'n. 脖子；衣领；海峡 v. 搂著脖子亲吻；变狭窄', 912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'influence', 'n. 影响；势力；感化；有影响的人或事 v. 影响；改变', 913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'poor', 'adj. 贫穷的；可怜的；贫乏的；卑鄙的 n. (Poor)人名；(英、伊朗)普尔', 914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'Sunday', 'n. 星期日；礼拜日', 915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bit', 'n. [计] 比特（二进位制信息单位）；少量；马嚼子；辅币；老一套；一点，一块 vt. 控制 adj. 很小的；微不足道的 adv. 有点儿；相当', 916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bird', 'n. 鸟；家伙；羽毛球 v. 向…喝倒彩；起哄', 917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'happen', 'v. 发生；碰巧；偶然遇到', 918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'delicious', 'adj. 美味的；可口的', 919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'operation', 'n. 操作；经营；[外科] 手术；[数][计] 运算', 920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pool', 'n. 联营；撞球；水塘；共同资金 v. 联营，合伙经营', 921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'skate', 'v. 滑冰；滑过 n. 溜冰；冰鞋', 922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wrong', 'adv. 错误地；邪恶地，不正当地 n. 坏事；不公正 adj. 错误的；失常的；不适当的 v. 委屈；无理地对待；诽谤', 923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'day', 'n. 一天；时期；白昼 adv. 每天；经常在白天地 adj. 日间的；逐日的', 924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'golden', 'adj. 金色的，黄金般的；珍贵的；金制的 n. (Golden)人名；(英、法、罗、德、瑞典)戈尔登', 925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'excuse', 'n. 借口；理由 v. 原谅；为…申辩；给…免去', 926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lonely', 'adj. 寂寞的；偏僻的 n. 孤独者', 927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'silent', 'adj. 沉默的；寂静的；无记载的 n. 无声电影', 928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'poem', 'n. 诗', 929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'late', 'adj. 晚的；迟的；已故的；最近的 adv. 晚；迟；最近；在晚期', 930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'disease', 'n. 病，[医] 疾病；弊病 vt. 传染；使…有病', 931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bell', 'n. 铃，钟；钟声，铃声；钟状物 v. 装钟于，系铃于', 932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lab', 'n. 实验室，研究室', 933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'grandson', 'n. 孙子；外孙', 934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'welcome', 'adj. 受欢迎的 n. 欢迎 v. 欢迎 int. 欢迎', 935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'daughter', 'n. 女儿；[遗][农学] 子代 adj. 女儿的；子代的', 936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'meat', 'n. 肉，肉类（食用）', 937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'path', 'n. 道路；小路；轨道', 938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'both', 'adj. 两个的；两者的 adv. 并；又；两者皆 pron. 双方都；两者都 conj. 既…且… n. (Both)人名；(德、罗、捷、南非、匈)博特', 939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'up', 'adv. 起来；上涨；向上 prep. 在…之上；向…的较高处 adj. 涨的；起床的；向上的 n. 上升；繁荣', 940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'possible', 'adj. 可能的；合理的；合适的 n. 可能性；合适的人；可能的事物', 941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'thing', 'n. 事情；东西；事物；情况', 942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'India', 'n. 印度（南亚国家）', 943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pick', 'v. 挑选；采摘；挖 n. 选择；鹤嘴锄；挖；掩护', 944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'area', 'n. 区域，地区；面积；范围', 945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'explain', 'v. 说明；解释', 946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'social', 'adj. 社会的，社交的；群居的 n. 联谊会；联欢会', 947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'weigh', 'v. 权衡；考虑；称…重量 n. 权衡；称重量', 948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nine', 'n. 九，九个 num. 九；九个 adj. 九的，九个的', 949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'nothing', 'neg. 没什么；毫不 n. 无；零；不关紧要之事 adv. 毫不；决不 pron. 无事；无物 int. 什么也没有', 950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'job', 'n. 工作；职业 v. 承包；代客买卖', 951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'museum', 'n. 博物馆', 952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'inside', 'n. 里面；内部；内情；内脏 adj. 里面的；内部的；秘密的 adv. 在里面 prep. 少于；在…之内', 953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'patient', 'adj. 有耐心的，能容忍的 n. 病人；患者', 954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'tomato', 'n. 番茄，西红柿', 955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'different', 'adj. 不同的；个别的，与众不同的', 956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'word', 'n. [语] 单词；话语；消息；诺言；命令 v. 用言辞表达', 957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'lady', 'n. 女士，夫人；小姐；妻子', 958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'kite', 'n. 风筝 v. 使用空头支票；像风筝一样飞；轻快地移动', 959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'foreigner', 'n. 外地人，外国人', 960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'never', 'adv. 从未；决不', 961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'refuse', 'n. 垃圾；废物 v. 拒绝；不愿；抵制', 962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'heat', 'n. 高温；压力；热度；热烈 v. 使激动；把…加热', 963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'fire', 'n. 火；火灾；炮火；炉火；热情；激情；磨难 v. 点燃；解雇；开除；使发光；烧制；激动；放枪', 964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'perhaps', 'adv. 或许；（表示不确定）也许；（用于粗略的估计）或许；（表示勉强同意或其实不赞成）也许；可能 n. 假定；猜想；未定之事', 965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'boss', 'n. 老板；首领；工头 v. 指挥，调遣；当…的领导', 966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'supply', 'n. 供给，补给；供应品 v. 供给，提供；补充', 967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'socks', 'n. 袜子（sock的复数）', 968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'yesterday', 'n. 昨天；往昔 adv. 昨天', 969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'those', 'adj. 那些的 pron. 那些（that的复数）', 970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'success', 'n. 成功，成就；胜利；大获成功的人或事物', 971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'website', 'n. 网站（全球资讯网的主机站）', 972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'similar', 'adj. 相似的 n. 类似物', 973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'steel', 'n. 钢铁；钢制品；坚固 v. 钢化；使冷酷 adj. 钢制的；钢铁业的；坚强的', 974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'besides', 'adv. 此外；而且 prep. 除…之外', 975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'all', 'adj. 全部的 adv. 全然地；越发 n. 全部 pron. 全部', 976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'advice', 'n. 建议；忠告；劝告；通知', 977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'music', 'n. 音乐，乐曲', 978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'practice', 'n. 实践；练习；惯例 v. 练习；实习；实行', 979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'eight', 'num. 八；八个；第八 adj. 八的 n. 八字形', 980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seventy', 'n. 七十；七十个；七十岁；七十年代 adj. 七十的；七十个的；七十岁的 num. 七十', 981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'worry', 'n. 担心；烦恼；撕咬 v. 担心；发愁；折磨', 982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'wonder', 'n. 惊奇；奇迹；惊愕 v. 怀疑；想知道；惊讶 adj. 奇妙的；非凡的', 983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'every', 'adj. 每一的，每个的；每隔…的 n. (Every)人名；(英)埃夫里', 984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'screen', 'n. 屏，幕；屏风 v. 筛；拍摄；放映；掩蔽', 985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hen', 'n. 母鸡；女人；雌禽', 986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'bread', 'n. 面包；生计 v. 在…上洒面包屑', 987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'person', 'n. 人；身体；容貌，外表；人称', 988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'themselves', 'pron. 他们自己；他们亲自', 989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'chalk', 'v. 用粉笔写；用白垩粉擦；记录；规划 n. 粉笔；白垩；用粉笔划的记号 adj. 用粉笔写的', 990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cheese', 'n. [食品] 奶酪；干酪；要人 v. 停止 adj. 叛变的；胆小的', 991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sleepy', 'adj. 欲睡的；困乏的；不活跃的', 992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'sixteen', 'adj. 十六的，十六个的 num. 十六', 993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'pancake', 'n. 薄烤饼；粉饼；平降（全称pancake landing） vi. 平坠着陆；平展 vt. 使平坠著陆；使平展', 994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'ton', 'n. 吨；很多，大量', 995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'hair', 'n. 头发；毛发；些微 vt. 除去…的毛发 vi. 生长毛发；形成毛状纤维 adj. 毛发的；护理毛发的；用毛发制成的', 996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'granny', 'n. 奶奶；外婆；婆婆妈妈的人', 997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'cloud', 'n. 云；阴云；云状物；一大群；黑斑 v. 使混乱；以云遮敝；使忧郁；玷污', 998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'seldom', 'adv. 很少，不常', 999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (5, 'telephone', 'n. （美）电话；电话机；电话耳机 v. 打电话', 1000);
