INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seek', 'v. 寻找,探索', 1001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surge', 'n&v. (波涛)汹涌,涌起', 1002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ogallala', 'n. 奥加拉拉(美国地名)', 1003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'availability', 'n. 可用性,有效性,实用性', 1004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sophisticate', 'adj. 诡辩的,久经世故的', 1005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaeological', 'adj. 考古学的', 1006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universe', 'n. 宇宙,万物', 1007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impulse', 'n. 冲动 vt. 推动', 1008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'debris', 'n. 碎片,残骸', 1009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unknown', 'adj. 不知道的,未知的', 1010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tooth', 'n. 牙齿', 1011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twenty', 'num. 二十,二十个', 1012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'office', 'n. 办公室,事务所', 1013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wet', 'adj. 湿的,多雨的', 1014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'texture', 'n. 质地,(材料等的)结构', 1015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remarkable', 'adj. 非凡的,显著的', 1016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enormous', 'adj. 巨大的,庞大的', 1017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaeologist', 'n. 考古学家', 1018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neither', 'a&pron. 两者都不 conj. 既不也不', 1019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formal', 'adj. 正式的,正规的', 1020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perspective', 'n. 视角,观点,远景', 1021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cetacean', 'n. 鲸类动物', 1022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sunlight', 'n. 日光,阳光', 1023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gap', 'n. 缺口裂缝,差距', 1024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destructive', 'adj. 破坏(性)的', 1025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plankton', 'n. 浮游生物', 1026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radio', 'n. 收音机,无线电', 1027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reproduce', 'v. 再生,复制', 1028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enter', 'v. 进入,参加', 1029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oak', 'n. 橡树,橡木', 1030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'key', 'n. 关键,钥匙', 1031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silver', 'n. 银 v. 镀银', 1032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hole', 'n. 洞,孔 v. 凿洞', 1033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nearby', 'adj. 附近的,邻近的 adv. 在附近', 1034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yellow', 'n&a. 黄色(的)', 1035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'press', 'n&v. 压,压迫 n. 报刊,新闻界', 1036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credit', 'n. 信任 v. 相信,信任', 1037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ware', 'n. 陶器,器皿', 1038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diameter', 'n. 直径', 1039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neanderthal', 'adv. 穴居人的', 1040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frame', 'n. 镜框,构架 v. 镶框,制定', 1041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distinction', 'n. 差别,区分,优秀', 1042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'French', 'n&a. 法国(人)(的)', 1043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ideal', 'n. 理想 adj. 理想的,完美的', 1044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exact', 'adj. 精确的,准确的', 1045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'behind', 'prep. 在…后,落后于 adv. 在后面', 1046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foreign', 'adj. 外国的', 1047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flat', 'adj. 平坦的', 1048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enjoy', 'v. 享受,喜爱', 1049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'furthermore', 'adv. 而且,此外', 1050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'independence', 'n. 独立,自主', 1051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beach', 'n. 海滩', 1052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'technical', 'adj. 技术的,技巧的', 1053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artificial', 'adj. 人造的,虚伪的', 1054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drive', 'n&v. 驾驶', 1055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respect', 'n&v. 尊敬,敬重', 1056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precede', 'v. 领先(于),在之前,先于', 1057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'guild', 'n. 行会,协会', 1058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nile', 'n. 尼罗河', 1059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instance', 'n. 实例,建议', 1060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decoration', 'n. 装饰(品)', 1061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decay', 'v&n. 衰退,腐败', 1062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'originate', 'v. 起源于,创始', 1063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiation', 'n. 放射物,辐射', 1064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'massive', 'adj. 巨大的,大规模的', 1065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fundamental', 'adj. 基础的,基本的', 1066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'height', 'n. 高度,海拔', 1067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'butterfly', 'n. 蝴蝶', 1068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reproduction', 'n. 再现,复制品', 1069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asteroid', 'n. 小行星', 1070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tunnel', 'n. 隧道,地道', 1071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apartment', 'n. 公寓住宅', 1072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'him', 'pron. 他', 1073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burn', 'v. 烧 n. 烧伤', 1074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'export', 'v&n. 输出,出口', 1075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flash', 'n&v. 闪光,闪现', 1076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secondary', 'adj. 次要的,二级的', 1077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pottery', 'n. 陶器', 1078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chimpanzee', 'n. 黑猩猩', 1079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onto', 'prep. 在之上', 1080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occupy', 'v. 占,占领', 1081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harvest', 'n. 收获 v. 收获,收割', 1082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disappear', 'v. 消失', 1083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Australian', 'n. 澳大利亚(的)', 1084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conclusion', 'n. 结束,结论', 1085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dominant', 'adj. 有统治权的,占优势的', 1086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pull', 'v. 拉,拖,拔', 1087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tuna', 'n. 金枪鱼', 1088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restrict', 'v. 限制,约束', 1089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distribution', 'n. 分发,分配,分布', 1090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'movie', 'n. 电影', 1091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'projection', 'n. 发射', 1092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stretch', 'v&n. 伸展,延伸', 1093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'goal', 'n. 目的,目标', 1094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'requirement', 'n. 需求,要求', 1095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'operate', 'v. 操作,运转', 1096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trap', 'v. 设圈套,陷入(困境) n. 圈套', 1097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reject', 'v. 拒绝,退回', 1098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'majority', 'n. 大多数', 1099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volume', 'n. 卷,册', 1100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'float', 'v&n. 漂浮,浮现', 1101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'zone', 'n. 地域,地带 v. 分成区', 1102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pastoralism', 'n. 田园主义,牧歌体', 1103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliable', 'adj. 可靠的,可信赖的', 1104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frequency', 'n. 频率,发生次数', 1105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geologic', 'adj. 地质的', 1106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extent', 'n. 范围,程度,广度', 1107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pleistocene', 'n&a. [地]更新世(的)(一段时期)', 1108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enhance', 'v. 提高,增强', 1109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accompany', 'v. 陪伴,伴奏', 1110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interpret', 'v. 解释,说明', 1111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snowfall', 'n. 降雪,降雪量', 1112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storm', 'n. 暴风雨,暴风雪', 1113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'musician', 'n. 音乐家', 1114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'critical', 'adj. 批评的,挑剔的,决定性的', 1115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Netherlands', 'n. 荷兰[国家]', 1116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choose', 'v. 选择,选定', 1117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polar', 'adj. (近)地极的,对立的', 1118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollutant', 'n. 污染物质', 1119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unable', 'adj. 不能的,不会的', 1120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elite', 'n. 精英,精华', 1121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'branch', 'n. 树枝,分部,分支', 1122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seawater', 'n. 海水', 1123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Chicago', 'n. 芝加哥', 1124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'walk', 'v. 行,走 n. 步行', 1125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Health', 'n. 健康', 1126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decorate', 'v. 装饰', 1127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portion', 'n. 一部分', 1128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'combination', 'n. 结合,联合,合并', 1129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'active', 'adj. 积极的,活跃的,起作用的', 1130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'division', 'n. 分开,分割,区分', 1131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pure', 'adj. 纯的,纯粹的', 1132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engage', 'v. 雇佣,从事,参加', 1133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stay', 'v&n. 逗留,保持,延缓', 1134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regulate', 'v. 管理,控制,调整', 1135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'send', 'v. 发送,派遣', 1136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'copper', 'n. 铜,警察', 1137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engineer', 'n. 工程师 v. 设计,建造', 1138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'critic', 'n. 批评家,评论家', 1139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'investment', 'n. 投资,可获利的东西', 1140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Boston', 'n. 波士顿', 1141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opportunist', 'n. 机会主义者,投机取巧者', 1142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dependent', 'adj. 依靠的,依赖的', 1143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'week', 'n. 星期,周', 1144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balance', 'n. 平衡 v. 使平衡', 1145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollution', 'n. 污染', 1146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mother', 'n. 母亲', 1147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drought', 'n. 干旱,缺乏', 1148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'survey', 'n&vt. 调查', 1149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repeat', 'n&v. 重复,重做,使再现', 1150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reflective', 'adj. 反射的,反映的,沉思的', 1151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'status', 'n. 身份,地位,情形,', 1152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authority', 'n. 权威,权力', 1153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perception', 'n. 观念,洞察力,认识能力', 1154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ridge', 'n. 背脊,山脊', 1155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stress', 'n. 压力,重点 v. 着重,强调', 1156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accumulation', 'n. 积聚,堆积物', 1157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bound', 'n. 范围,界限', 1158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Alaska', 'n. 阿拉斯加州(美国州名)', 1159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'context', 'n. 上下文', 1160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perfect', 'adj. 完美的 v. 使完美,修改', 1161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'millennium', 'n. 太平盛世,一千年', 1162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'somewhat', 'adv. 稍微,有点,有些', 1163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'China', 'n. 中国,瓷器', 1164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'favorable', 'adj. 赞成的,有利的', 1165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'broad', 'adj. 宽的,广泛的', 1166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'risk', 'vt&n. 冒险,风险', 1167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antarctica', 'n. 南极洲', 1168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinetoscope', 'n. 活动电影放映机', 1169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absence', 'n. 不在, 缺席, 缺乏, 没有', 1170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'representative', 'n. 代表 a典型的, 有代表性的', 1171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enlarge', 'v. 扩大, 放大', 1172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'defense', 'n. 国防部,防卫', 1173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'category', 'n. 种类', 1174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intensity', 'n. 强度,强烈', 1175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abandon', 'v. 放弃,遗弃', 1176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relation', 'n. 关系,联系', 1177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virus', 'n. 病毒', 1178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhibition', 'n. 表现,展览会', 1179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alter', 'v. 改变', 1180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'myth', 'n. 神话', 1181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arid', 'adj. 干旱的,贫瘠的', 1182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erode', 'v. 侵蚀,腐蚀', 1183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dramatic', 'adj. 戏剧性的,生动的', 1184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arise', 'v. 出现,发生,起因于', 1185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reverse', 'v. 颠倒,倒转', 1186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capacity', 'n. 容量,能力', 1187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'competitor', 'n. 竞争者', 1188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'promise', 'vt&n. 允诺,答应', 1189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wooden', 'adj. 木制的', 1190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portray', 'v. 描绘', 1191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'composer', 'n. 作家,作曲家', 1192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stick', 'n. 棍 v. 刺,戳', 1193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glaciation', 'n. 冻结成冰,冰河作用', 1194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arm', 'n. 臂 v. 供给,武装', 1195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transfer', 'n&v. 迁移,移动,转移', 1196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arch', 'n. 拱门v(使)弯成弓形', 1197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prediction', 'n. 预言', 1198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stencil', 'n. 模版,蜡纸 v. 用蜡纸印刷', 1199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distinctive', 'adj. 有区别的,独特的', 1200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tail', 'n. 尾巴 v. 跟踪,尾随', 1201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'France', 'n. 法国,法兰西', 1202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toxic', 'adj. 有毒的,中毒的', 1203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnetic', 'adj. 磁的,有吸引力的', 1204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'visit', 'n&v. 拜访,访问', 1205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apart', 'adv. 相间隔,分离 adj. 分离(隔)的', 1206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gull', 'n. 海鸥 v. 欺骗', 1207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herbivore', 'n. 草食动物', 1208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cross', 'n. 十字,交叉 v. 使交叉,横过', 1209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tornado', 'n. 龙卷风', 1210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metallic', 'adj. 金属(性)的', 1211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loud', 'a&ad. 高声的,大声地', 1212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drain', 'n. 排水,消耗', 1213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'realize', 'v. 认识到,了解', 1214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shallow', 'adj. 浅的', 1215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surplus', 'n. 剩余,过剩', 1216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explore', 'v. 探险,探测', 1217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classify', 'v. 分类,分等', 1218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'possibility', 'n. 可能性', 1219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'novel', 'n. 小说,长篇故事', 1220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afford', 'v. 提供,给予', 1221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'southeast', 'n&a. 东南(的)', 1222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrow', 'adj. 狭窄(隘)的,勉强的 v. 变窄,压缩', 1223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'northwest', 'n&a. 西北方(的)', 1224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collision', 'n. 碰撞,冲突', 1225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lung', 'n. 肺,呼吸器', 1226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diverse', 'adj. 不同的,变化多的', 1227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temperate', 'adj. 温和的,适度的,有节制的', 1228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'widespread', 'adj. 分布广泛的,普遍的', 1229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'isotope', 'n. 同位素', 1230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detect', 'v. 察觉,侦查,发现', 1231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nevertheless', 'adv. 尽管如此 conj. 然而,不过', 1232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wheat', 'n. 小麦', 1233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peak', 'n. 山顶,顶点', 1234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parlor', 'n. 客厅,会客室', 1235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'navigate', 'v. 航行,航海', 1236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tendency', 'n. 趋向,倾向', 1237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flourish', 'v&n. 繁荣,茂盛', 1238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catch', 'v. 捕获,抓住', 1239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evolutionary', 'adj. 进化的,发展的,演变的', 1240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bead', 'n. 珠子,水珠', 1241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variability', 'n. 可变性', 1242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'turbine', 'n. 涡轮', 1243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'highland', 'n. 高地,丘陵地带', 1244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meat', 'n. (食用)肉,肉类', 1245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'match', 'v. 相配,相称', 1246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tall', 'adj. 高的,长的', 1247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'communicate', 'v. 沟通,通信,传达', 1248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distribute', 'v. 分发,分配', 1249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comparative', 'adj. 比较的,相当的', 1250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newly', 'adj. 重新,最近', 1251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mill', 'v. 碾磨,搅拌', 1252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indirect', 'adj. 间接的,迂回的', 1253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stop', 'n&v. 停止,阻止', 1254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destruction', 'n. 破坏,毁灭', 1255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'customer', 'n. 消费者', 1256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suddenly', 'adv. 突然地', 1257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multiple', 'adj. 多样的 n. 倍数', 1258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vitamin', 'n. 维他命,维生素', 1259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manner', 'n. 礼貌,方式', 1260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vegetable', 'n. 蔬菜,植物', 1261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conclude', 'v. 推断出,结束,总结', 1262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barrier', 'n. 障碍物,栅栏', 1263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mud', 'n. 泥,泥浆', 1264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motif', 'n. 主题,主旨', 1265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wheel', 'n. 轮 v. 推,拉,转动', 1266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rough', 'adj. 粗糙的,大致的', 1267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corridor', 'n. 走廊', 1268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'challenger', 'n. 挑战者', 1269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fragment', 'n. 碎片 v. (使)成碎片', 1270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occasionally', 'adv. 有时候,偶而', 1271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'component', 'n. 成分', 1272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beaver', 'n. 海狸(毛皮)', 1273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprehension', 'n. 理解,包含', 1274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physiological', 'adj. 生理(学)的', 1275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ceremony', 'n. 典礼,仪式', 1276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'altitude', 'n. 高度(海拔)', 1277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arrive', 'v. 到达,抵达', 1278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exploit', 'v. 开拓,开采', 1279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microscopic', 'adj. 显微镜的,极小的', 1280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'schedule', 'n. 时刻表,日程 v. 安排,排定', 1281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'former', 'adj. 从前的,以前的', 1282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'career', 'n. 事业,生涯', 1283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aim', 'n. 目标v对瞄准,打算', 1284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inventor', 'n. 发明家', 1285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consume', 'v. 消耗,消费,消灭', 1286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'examine', 'v. 检查,调查,考试', 1287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atmospheric', 'adj. 大气的', 1288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fore', 'adj. 在前的 n. 前头,船头', 1289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'province', 'n. 省(一个国家的大行政区)', 1290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'introduction', 'n. 介绍,传入', 1291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encode', 'v. 把编码', 1292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squirrel', 'n. 松鼠', 1293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'random', 'n&a. 任意(的),随便(的)', 1294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tulip', 'n. 郁金香', 1295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invent', 'v. 发明,创造', 1296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pueblo', 'n. 印第安人村庄', 1297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pound', 'n. 磅,英镑 v. (连续)猛击,捣碎', 1298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pebble', 'n. 小圆石,小鹅卵石', 1299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lot', 'n. 许多,大量', 1300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obvious', 'adj. 明显的,显而易见的', 1301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'station', 'n. (车)站,台 v. 安置,派驻', 1302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'limestone', 'n. 石灰石', 1303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sumerian', 'n. 闪族人[语]', 1304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brown', 'n&a. 棕色(的),人名', 1305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gazelle', 'n. 瞪羚,小羚羊', 1306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Columbia', 'n. 哥伦比亚', 1307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statistic', 'n. 统计数值', 1308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evaporation', 'n. 蒸发', 1309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaeology', 'n. 考古学', 1310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dweller', 'n. 居住者,居民', 1311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'possess', 'v. 占有,拥有', 1312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elsewhere', 'adv. 在别处', 1313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seasonal', 'adj. 季节的,周期性的', 1314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assemble', 'v. 集合,聚集,装配', 1315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mask', 'n. 面具', 1316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reality', 'n. 真实,事实', 1317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alone', 'adj. 单独的', 1318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'college', 'n. 学院', 1319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'definition', 'n. 定义,解说', 1320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dead', 'adj. 死的 n. 死者', 1321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regional', 'adj. 整个地区的,地域性地', 1322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'border', 'n. 边界 v. 与接壤,接近', 1323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'household', 'n. 家庭', 1324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trend', 'n&v. 倾向,趋势', 1325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sandstone', 'n. 沙岩', 1326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Sweden', 'n. 瑞典', 1327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suck', 'v. 吸,吮', 1328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speech', 'n. 演说', 1329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consequent', 'n. 推论,结论', 1330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crisis', 'n. 决定性时刻,危机', 1331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modem', 'n. [计]调制解调器', 1332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literary', 'adj. 文学的', 1333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pioneer', 'n. 先驱者,创始人 v. 开拓(创)', 1334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'criticize', 'v. 批评,责备', 1335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'originally', 'adv. 最初,原先', 1336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salinity', 'n. 盐分,盐度', 1337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'room', 'n. 房间', 1338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrub', 'n. 灌木, 灌木丛', 1339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weapon', 'n. 武器', 1340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clean', 'adj. 清洁的 v. 打扫,使干净', 1341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corn', 'n. 玉米', 1342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dynasty', 'n. 朝代,王朝', 1343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'livestock', 'n. 家畜', 1344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drama', 'n. 戏剧', 1345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photography', 'n. 摄影', 1346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonist', 'n. 殖民地居民,殖民者', 1347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extra', 'adj. 额外的', 1348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'algae', 'n. 水藻', 1349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lowland', 'n. 低地', 1350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'otherwise', 'conj. 否则 adv. 否则,除此以外', 1351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'round', 'adj. 圆的 adv. 在周围 prep. 大约', 1352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imagine', 'v. 想象,设想', 1353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'selection', 'n. 选择,挑选', 1354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vertebrate', 'n. 脊椎动物', 1355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sixteenth', 'num. 第十六,十六分之一', 1356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recover', 'v. 恢复,复原,重获', 1357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forward', 'adv. 向前,从今往后 adj. 前部的', 1358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expense', 'n. 费用,代价', 1359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smooth', 'adj. 光滑的,平整的 v. 弄平', 1360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'talk', 'v&n. 谈话', 1361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scheme', 'n. 安排 v. 计划,策划', 1362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tower', 'n. 塔,城堡', 1363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bright', 'adj. 明亮的', 1364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anthropologist', 'n. 人类学家', 1365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discipline', 'n. 纪律,学科 v. 训练', 1366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opposite', 'adj. 相对的,对面的 n. 相反的事物', 1367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oyster', 'n. 牡蛎,蚝', 1368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interval', 'n. 间隔,距离', 1369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volcano', 'n. 火山', 1370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'love', 'n&v. 爱', 1371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mind', 'n. 头脑,意见 v. 介意,注意', 1372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steady', 'adj. 稳固的,坚定的', 1373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'full', 'n. 全部 adj. 充满的,完全的', 1374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universal', 'adj. 普遍的,全体的', 1375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'union', 'n. 联合,联盟', 1376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrain', 'n. 地形', 1377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluid', 'n. 液体 adj. 流体的,流动的', 1378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wildebeest', 'n. 羚羊(其中一种)', 1379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resistance', 'n. 反抗,抵抗', 1380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rabbit', 'n. 兔', 1381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'candidate', 'n. 候选人,投考者', 1382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'museum', 'n. 博物馆', 1383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hormone', 'n. 荷尔蒙,激素', 1384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'countryside', 'n. 乡下地方', 1385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thereby', 'adv. 因此,从而', 1386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'violin', 'n. 小提琴', 1387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bad', 'adj. 劣质的,有害的,坏的', 1388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'copy', 'n. 副本 v. 复印,抄袭', 1389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distant', 'adj. 远的,疏远的', 1390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lens', 'n. 透镜,镜头', 1391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'track', 'n. 轨道,踪迹 v. 跟踪', 1392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'porcelain', 'n. 瓷,瓷器', 1393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pellet', 'n. 小球', 1394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physics', 'n. 物理学', 1395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spectrum', 'n. 光谱', 1396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forth', 'adv. 往前,向外', 1397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mesozoic', 'n&a. 中生代(的)', 1398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assign', 'v. 分配,指派', 1399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'giant', 'n. 巨人,天才', 1400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superior', 'n. 长者,上级 adj. 较高的,上级的', 1401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sheet', 'n. (一)片,(一)张', 1402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigid', 'adj. 刚硬的,严格的', 1403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Denmark', 'n. 丹麦', 1404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbol', 'n. 符号,记号,象征', 1405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gar', 'n. 雀鳝属鱼, 雀鳝', 1406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'functional', 'adj. 功能的', 1407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cultivation', 'n. 培养,教养', 1408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impossible', 'adj. 不可能的', 1409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domestic', 'adj. 国内的,家庭的', 1410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emphasis', 'n. 强调,重点', 1411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonize', 'v. 拓殖,殖民', 1412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flipper', 'n. 鳍状肢', 1413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peninsula', 'n. 半岛', 1414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acid', 'n. 酸 adj. 酸的', 1415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'droplet', 'n. 小滴', 1416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paleontologist', 'n. 古生物学者', 1417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apprentice', 'n. 学徒 v. 当学徒', 1418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grandma', 'n. 奶奶', 1419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'justify', 'v. 证明是正当的', 1420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cereal', 'n. 谷类食品', 1421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'investigation', 'n. 调查,研究', 1422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rail', 'n. 栏杆 v. 抱怨,责骂', 1423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'post', 'n. 邮政(件),职位 v. 邮寄,贴出', 1424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lock', 'n. 锁 v. 锁上', 1425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feeling', 'n. 触觉,知觉', 1426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ore', 'n. 矿石', 1427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fossilization', 'n. 化石作用', 1428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precise', 'adj. 精确的,准确的', 1429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consistent', 'adj. 一致的,调和的', 1430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homeland', 'n. 祖国,本国', 1431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'policy', 'n. 政策,方针', 1432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wrong', 'a&ad. 错误的,不正当的', 1433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transition', 'n. 转变,过渡', 1434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Greece', 'n. 希腊', 1435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'screen', 'n. 屏幕 v. 掩蔽,放映', 1436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freezing', 'adj. 冰冻的,严寒的', 1437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mislead', 'v. 误导', 1438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hind', 'adj. 后边的,后面的', 1439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'psychological', 'adj. 心理(上)的', 1440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'venus', 'n. 维纳斯,金星', 1441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aid', 'n. 帮助,资助', 1442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fern', 'n. 蕨类植物', 1443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aurora', 'n. 黎明的女神,极光', 1444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'zebra', 'n. 斑马', 1445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heart', 'n. 心,心脏', 1446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whatever', 'pron. 凡是,无论什么 adj. 无论怎样的', 1447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skull', 'n. 头脑,头骨', 1448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'list', 'n. 目录,列表 v. 列出', 1449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scandinavian', 'n. 斯堪的纳维亚人[语]', 1450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Paris', 'n. 巴黎', 1451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handle', 'v. 处理,操作', 1452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'profit', 'n. 利润,益处 v. 得益,有利于', 1453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revise', 'v. 修订,校订', 1454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fracture', 'v. (使)破碎,(使)破裂', 1455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hence', 'adv. 因此,从此', 1456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'investigator', 'n. 调查人', 1457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rent', 'v. 租用,出租 n. 租金', 1458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interpretation', 'n. 解释,阐明', 1459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overcome', 'v. 战胜,克服', 1460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dam', 'n. 水坝,障碍', 1461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reduction', 'n. 减少,缩影', 1462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unless', 'conj. 如果不,除非', 1463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preference', 'n. 偏爱,优先选择', 1464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transformation', 'n. 变化,转化', 1465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calculate', 'v. 计算,考虑', 1466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'basket', 'n. 篮,一篮', 1467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'establishment', 'n. 确立,制定', 1468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canopy', 'n. 天篷,遮篷', 1469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dig', 'v. 挖', 1470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consumption', 'n. 消费', 1471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reservoir', 'n. 水库,蓄水池', 1472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'description', 'n. 描写,记述', 1473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pore', 'n. 小孔', 1474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'operation', 'n. 运转,操作,实施', 1475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cast', 'v. 投, 抛', 1476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oral', 'adj. 口头的', 1477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circumstance', 'n. 环境,详情,境况', 1478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potash', 'n. 碳酸钾,苛性钾', 1479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'severe', 'adj. 严厉的,剧烈的,严重的', 1480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satellite', 'n. 人造卫星', 1481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trouble', 'n&v. 烦恼,麻烦', 1482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'string', 'n. 线 v. 排成一列', 1483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'architect', 'n. 建筑师', 1484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhibitor', 'n. 展出者,显示者', 1485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'classical', 'adj. 古典的,正统派的', 1486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extract', 'v. 取出,提取 n. 摘录', 1487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'none', 'adv. 决不,毫不 pron. 一个也没有', 1488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compact', 'v. 使坚实 n. 契约', 1489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undergo', 'v. 经历,遭受', 1490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fragile', 'adj. 易碎的,脆的', 1491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'responsibility', 'n. 责任,职责', 1492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exaggerate', 'v. 夸大,夸张', 1493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'output', 'n. 产量,输出', 1494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skyscraper', 'n. 摩天楼', 1495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wing', 'n. 翅膀 v. 飞过', 1496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disease', 'n. 疾病', 1497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resist', 'v. 抵抗,反抗', 1498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'win', 'v. (获)胜,赢得', 1499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluctuation', 'n. 波动,起伏', 1500);
