INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agitate', 'v. 摇动；骚动；使…激动', 501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tour', 'n. 旅游，旅行；巡回演出 v. 旅行，在……旅游；在……作巡回演出', 502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blithesome', 'adj. 愉快的', 503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tout', 'v. 兜售；招徕；刺探赛马情报 n. 侦查者；兜售者', 504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anecdote', 'n. 轶事；奇闻；秘史', 505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cerebellum', 'n. [解剖] 小脑', 506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'factious', 'adj. 好捣乱的；好搞派系的；源于派别的', 507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artistry', 'n. 艺术性；工艺；艺术技巧；艺术效果；艺术工作', 508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obdurate', 'adj. 顽固的，执拗的；冷酷无情的', 509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overcome', 'v. 克服；胜过', 510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'iconoclast', 'n. 偶像破坏者；提倡打破旧习的人', 511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acceleration', 'n. 加速，促进；[物] 加速度', 512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'poignant', 'adj. 尖锐的；辛酸的；深刻的；切中要害的 n. (Poignant)人名；(法)普瓦尼昂', 513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pungent', 'adj. 辛辣的；刺激性的；刺鼻的；苦痛的；尖刻的', 514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heat', 'n. 高温；压力；热度；热烈 v. 使激动；把…加热', 515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'restitution', 'n. 恢复；赔偿；归还', 516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'awry', 'adj. 错误的；扭曲的 adv. 歪曲地；歪斜地；错误地', 517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mordent', 'n. 涟音；波音', 518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dejected', 'adj. 沮丧的，灰心的', 519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'upshot', 'n. 结果，结局；要点', 520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'relegate', 'v. 把降低到；归入；提交', 521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'narcissistic', 'adj. 自恋的；自我陶醉的', 522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intellectual', 'adj. 智力的；聪明的；理智的 n. 知识分子；凭理智做事者', 523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sloth', 'n. 怠惰，懒惰；[脊椎] 树懒', 524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heedless', 'adj. 不注意的；不留心的', 525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arboriculture', 'n. 树木的培植/栽培', 526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fulminate', 'v. 爆炸；电闪；怒喝 n. 雷酸盐；烈性炸药', 527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dwarf', 'v. 变矮小 n. 侏儒，矮子 adj. 矮小的', 528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resonance', 'n. [力] 共振；共鸣；反响', 529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrace', 'v. 追溯；折回；重描', 530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dogged', 'adj. 顽强的；顽固的 vt. 跟踪；尾随（dog的过去式）', 531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diminutive', 'adj. 小的，小型的，微小的 n. 爱称；指小词；身材极小的人', 532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symmetry', 'n. 对称（性）；整齐，匀称', 533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facile', 'adj. （言语或理论）轻率的，未经深思熟虑的', 534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissolve', 'v. 使溶解；使分解；使液化 n. 叠化画面；画面的溶暗', 535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repetition', 'n. 重复；背诵；副本', 536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stoic', 'n. 斯多葛学派哲学家；禁欲主义者；恬淡寡欲的人，不以苦乐为意的人 adj. 坚忍的，苦修的；斯多葛派的；禁欲主义的', 537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gross', 'adj. 总共的；粗野的；恶劣的；显而易见的 v. 总共收入 n. 总额，总数', 538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allegory', 'n. 寓言', 539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artless', 'adj. 天真的；朴实的；无虚饰的', 540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reciprocate', 'v. 报答；互换；互给', 541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virus', 'n. [病毒] 病毒；恶毒；毒害', 542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quarantine', 'v. 检疫；隔离；使隔离 n. 检疫；隔离；检疫期；封锁', 543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temporary', 'adj. 暂时的，临时的 n. 临时工，临时雇员', 544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superintendent', 'n. 监督人；负责人；主管；指挥者', 545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'remiss', 'adj. 怠慢的；迟缓的；不小心的', 546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eclipse', 'v. 使黯然失色；形成蚀 n. 日蚀，月蚀；黯然失色', 547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equality', 'n. 平等；相等；[数] 等式', 548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virtu', 'n. 古董；艺术品爱好', 549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dramatic', 'adj. 戏剧的；急剧的；引人注目的；激动人心的', 550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reprimand', 'n. 谴责；训斥；申诉 v. 谴责；训斥；责难', 551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'august', 'adj. 威严的；令人敬畏的 n. 八月（简写为Aug）', 552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immerse', 'v. 沉浸；使陷入', 553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suffrage', 'n. 选举权；投票；参政权；代祷；赞成票', 554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'truculent', 'adj. 好斗的；野蛮的；言词刻毒的', 555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bailiff', 'n. 法警；执行官；区镇的地方长官', 556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indignant', 'adj. 愤愤不平的；义愤的', 557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paramount', 'adj. 最重要的，主要的；至高无上的 n. 最高统治者', 558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grievance', 'n. 不满，不平；委屈；冤情', 559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affectation', 'n. 做作；矫揉造作；假装', 560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neuron', 'n. [解剖] 神经元，神经单位', 561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'savor', 'v. 尽情享受；使有风味；加调味品于；品尝，欣赏 n. 滋味；气味；食欲', 562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quagmire', 'n. 沼泽，沼泽地；无法脱身的困境', 563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unconscionable', 'adj. 不合理的；昧着良心的；肆无忌惮的；过度的', 564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'posse', 'n. 一队；民防团；地方武装团队', 565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nutriment', 'n. 营养物；促进生长的东西', 566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bombast', 'n. 夸大的言辞 adj. 夸大的', 567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chateau', 'n. （法国封建时代的）城堡；（尤指法国的）别墅', 568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'formula', 'n. [数] 公式，准则；配方；婴儿食品', 569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'harass', 'v. 使困扰；使烦恼；反复袭击', 570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'combustible', 'adj. 易燃的；易激动的；燃烧性的 n. 可燃物；易燃物', 571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'purity', 'n. [化学] 纯度；纯洁；纯净；纯粹', 572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'calamity', 'n. 灾难；不幸事件', 573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inhuman', 'adj. 残忍的；野蛮的；无人性的', 574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disavow', 'v. 否认，否定；抵赖；拒绝对…的责任', 575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diversify', 'v. 使多样化，使变化；增加产品种类以扩大', 576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amity', 'n. 友好；亲善关系；友好关系', 577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'juncture', 'n. 接缝；连接；接合', 578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'askew', 'adj. 歪斜的 adv. 歪斜地，斜地 n. (Askew)人名；(英)艾斯丘', 579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preface', 'n. 前言；引语 v. 为…加序言；以…开始', 580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arithmetic', 'n. 算术，算法', 581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cadenza', 'n. 装饰乐段', 582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'memorize', 'v. 记住，背熟；记忆', 583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingenious', 'adj. 有独创性的；机灵的，精制的；心灵手巧的', 584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'waif', 'n. 流浪者；流浪儿；飘流物；无主物；信号旗', 585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collision', 'n. 碰撞；冲突；（意见，看法）的抵触；（政党等的）倾轧', 586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stanch', 'v. 止血；使不漏；平息 adj. 坚固的；忠实的；防水的', 587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prehensile', 'adj. 适于抓握的；善于领会的', 588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hodgepodge', 'n. 大杂烩；混煮；一团糟 vt. 使混乱', 589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ribald', 'adj. 下流的；言谈粗俗的 n. 言谈粗俗的人；说下流话的人', 590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undue', 'adj. 过度的，过分的；不适当的；未到期的', 591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'biodegradable', 'adj. 生物所能分解的，能进行生物降解的', 592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'saline', 'adj. 盐的；含盐分的 n. 盐湖；碱盐泻药', 593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recombination', 'n. 复合，再结合；[遗] 重组', 594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preferential', 'adj. 优先的；选择的；特惠的；先取的', 595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vulnerable', 'adj. 易受攻击的，易受…的攻击；易受伤害的；有弱点的', 596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'digit', 'n. 数字；手指或足趾；一指宽', 597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antipathy', 'n. 反感；厌恶；憎恶；不相容', 598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carnal', 'adj. 肉体的；肉欲的；淫荡的；性欲的 n. (Carnal)人名；(西)卡纳尔', 599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stealth', 'n. 秘密；秘密行动；鬼祟', 600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beaker', 'n. 烧杯；大口杯', 601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'meddler', 'n. 干涉者；爱管闲事的人', 602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'decent', 'adj. 正派的；得体的；相当好的', 603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transcendent', 'adj. 卓越的；超常的；出类拔萃的 n. 卓越的人；超绝物', 604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'modulate', 'v. 调节；（信号）调制；调整', 605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'untoward', 'adj. 不幸的；麻烦的；倔强的；困难的', 606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'Iron', 'n. 熨斗；烙铁；坚强 v. 熨；用铁铸成 adj. 铁的；残酷的；刚强的', 607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acclaim', 'v. 称赞；为…喝彩，向…欢呼 n. 欢呼，喝彩；称赞', 608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adhere', 'v. 坚持；依附；粘着；追随', 609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fern', 'n. [植] 蕨；[植] 蕨类植物', 610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'naive', 'adj. 天真的,幼稚的', 611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distraught', 'adj. 发狂的；心烦意乱的', 612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salacious', 'adj. 好色的；猥亵的；淫荡的', 613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supercilious', 'adj. 目空一切的，高傲的；傲慢的，自大的', 614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'giraffe', 'n. 长颈鹿', 615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perspicuous', 'adj. 明了的；清晰明白的；易懂的', 616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'donate', 'v. 捐赠；捐献 n. 捐赠；捐献', 617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'skirt', 'n. 裙子 v. 绕过，回避；位于…边缘', 618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'elicit', 'v. 抽出，引出；引起', 619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'integer', 'n. [数] 整数；整体；完整的事物', 620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clergy', 'n. 神职人员；牧师；僧侣', 621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compliment', 'n. 恭维；称赞；问候；致意；道贺 v. 恭维；称赞', 622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unequivocal', 'adj. 明确的；不含糊的', 623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incredulous', 'adj. 怀疑的；不轻信的', 624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glimpse', 'n. 一瞥，一看 v. 瞥见', 625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'soda', 'n. 苏打；碳酸水', 626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'altruistic', 'adj. 利他的；无私心的', 627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pallid', 'adj. 苍白的；暗淡的；无生气的', 628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cession', 'n. （权利的）转让，出让；（领土的）割让', 629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adjuration', 'n. 严令；恳请；立誓', 630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forage', 'n. 饲料；草料；搜索 v. 搜寻粮草；搜寻', 631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erudite', 'adj. 博学的；有学问的 n. 饱学之士', 632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retouch', 'n. 润饰；修整部分 v. 润饰；修整', 633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conception', 'n. 怀孕；概念；设想；开始', 634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'warrant', 'n. 根据；证明；正当理由；委任状 v. 保证；担保；批准；辩解', 635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'body', 'n. 身体；主体；大量；团体；主要部分 v. 赋以形体', 636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trepidation', 'n. 恐惧；惊恐；忧虑；颤抖', 637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'haggard', 'adj. 憔悴的；野性的 n. 野鹰', 638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'egregious', 'adj. 惊人的；过分的；恶名昭彰的', 639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acclivity', 'n. 向上的斜坡；[建] 上斜', 640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virtuoso', 'n. 艺术品鉴赏家；古董收藏家；艺术大师 adj. 行家里手的；艺术爱好者的', 641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'captious', 'adj. 挑剔的；吹毛求疵的', 642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adulate', 'v. 过分称赞；谄媚；奉承', 643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antenatal', 'adj. 产前的；出生前的', 644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solecism', 'n. 语法错误，文理不通；谬误，失礼', 645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'semiconscious', 'adj. 半意识的；半清醒的', 646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perambulate', 'v. 巡行；巡视；漫步', 647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mishap', 'n. 灾祸；不幸事故；晦气', 648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'butte', 'n. 孤峰；孤立的丘', 649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impromptu', 'n. 即兴曲；即席演出 adv. 即席地 adj. 即席的', 650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mystify', 'v. 使神秘化；使迷惑，使困惑', 651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frenzied', 'adj. 疯狂的；狂乱的；激怒的 v. 使狂乱（frenzy的过去式）', 652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ken', 'n. 视野范围，见地，知识范围', 653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'counterpoint', 'n. 复调；对位法；旋律配合；对应物', 654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'submerge', 'v. 淹没；把…浸入；沉浸', 655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'derisive', 'adj. 嘲笑的，嘲弄的；可付之一笑的', 656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'light', 'n. 光；光线；灯；打火机；领悟；浅色；天窗 adj. 轻的；浅色的；明亮的；轻松的；容易的；清淡的 v. 点着；变亮；着火 adv. 轻地；清楚地；轻便地', 657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'key', 'n. （打字机等的）键；关键；钥匙 v. 键入；锁上；调节…的音调；提供线索 adj. 关键的', 658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coup', 'n. 政变；妙计；出乎意料的行动；砰然的一击 vt. 使…颠倒；使…倾斜 vi. 推倒；倾斜；溢出', 659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insulin', 'n. [生化][药] 胰岛素', 660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'script', 'n. 脚本；手迹；书写用的字母 v. 把…改编为剧本', 661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'measurement', 'n. 测量；[计量] 度量；尺寸；量度制', 662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scowl', 'n. 愁容；怒容；阴沉沉的样子 v. 皱眉；怒视', 663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'receptive', 'adj. 善于接受的；能容纳的', 664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propellant', 'n. 推进物；推进燃料；发射火药 adj. 推进的', 665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comprise', 'v. 包含；由…组成', 666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'typography', 'n. 排印；[印刷] 活版印刷术；印刷格式', 667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedantic', 'adj. 迂腐的；学究式的；卖弄学问的；假装学者的', 668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diode', 'n. [电子] 二极管', 669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'statuesque', 'adj. 雕像般的；轮廓清晰的；均衡的', 670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terminate', 'v. 使终止；使结束；解雇 adj. 结束的', 671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'illustrious', 'adj. 著名的，杰出的；辉煌的', 672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'set', 'n. [数] 集合；一套；布景；[机] 装置 v. 树立；点燃；点缀； adj. 固定的；规定的；固执的', 673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virtuous', 'adj. 善良的；有道德的；贞洁的；正直的；有效力的', 674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kinetic', 'adj. [力] 运动的；活跃的', 675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'consensus', 'n. 一致；舆论；合意', 676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dictatorial', 'adj. 独裁的，专政的；专横傲慢的', 677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'submersion', 'n. 淹没，浸没', 678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plural', 'adj. 复数的 n. 复数', 679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bursar', 'n. 财务主管；会计员；领取奖学金的学生', 680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assimilation', 'n. 同化；吸收；[生化] 同化作用', 681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enhance', 'v. 提高；加强；增加', 682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irascible', 'adj. 易怒的', 683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gratuity', 'n. 赏钱，小费；赠物；[劳经] 退职金', 684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instantaneous', 'adj. 瞬间的；即时的；猝发的', 685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'naturalistic', 'adj. 自然的；自然主义的；博物学的', 686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'suspension', 'n. 悬浮；暂停；停职', 687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tenuous', 'adj. 纤细的；稀薄的；贫乏的', 688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'languish', 'v. 憔悴；凋萎；失去活力；苦思', 689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equanimity', 'n. 平静；镇定', 690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dimension', 'n. 方面;[数] 维；尺寸；次元；容积 vt标出尺寸 adj. 规格的', 691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recollect', 'v. 回忆，想起', 692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trammel', 'v. 束缚；拘束；阻碍 n. 拘束；束缚；束缚物', 693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peevish', 'adj. 易怒的，暴躁的；带怒气的；撒娇的', 694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cilia', 'n. 纤毛；睫毛', 695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outlaw', 'n. 歹徒；罪犯；亡命之徒；被剥夺法律保护者 v. 宣布…为不合法；将…放逐；剥夺…的法律保护', 696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'camaraderie', 'n. 友情；同志之爱', 697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'respiration', 'n. 呼吸；呼吸作用', 698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ancestry', 'n. 祖先；血统', 699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symphonious', 'adj. 和谐的；调和的', 700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'punctuate', 'v. 不时打断；强调；加标点于', 701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indigence', 'n. 穷困；贫乏；贫穷', 702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cajole', 'v. 以甜言蜜语哄骗；勾引', 703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forsake', 'v. 放弃；断念', 704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mariner', 'n. 水手；船员', 705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bizarre', 'adj. 奇异的（指态度，容貌，款式等）', 706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'saccharine', 'adj. 含糖的；极甜的；和颜悦色的 n. （美）糖精', 707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terse', 'adj. 简洁的，精练的，扼要的', 708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polemics', 'n. 辩论术；论证法（polemic的复数）', 709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retinue', 'n. 随行人员；扈从', 710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'renaissance', 'n. 文艺复兴（欧洲14至17世纪）', 711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'urbane', 'adj. 彬彬有礼的，温文尔雅的；都市化的', 712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ecstatic', 'adj. 狂喜的；入迷的 n. 狂喜的人', 713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gypsum', 'vt. 用石膏处理；施石膏肥料于 n. 石膏；石膏肥料', 714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apparatus', 'n. 装置，设备；仪器；器官', 715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embrace', 'v. 拥抱；信奉，皈依；包含 n. 拥抱', 716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inhibit', 'v. 抑制；禁止', 717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contradictory', 'adj. 矛盾的；反对的；反驳的；抗辩的 n. 对立物；矛盾因素', 718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prohibitive', 'adj. 禁止的，禁止性的；抑制的；（费用，价格等）过高的；类同禁止的', 719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vociferate', 'v. 喊叫；大叫', 720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'archaeology', 'n. 考古学', 721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alimentary', 'adj. 滋养的；食物的', 722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'credulity', 'n. 轻信；易受骗', 723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'counteract', 'v. 抵消；中和；阻碍', 724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apogee', 'n. 最高点，极点；远地点 vt. 位于远地点；位于最高点', 725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rabid', 'adj. 激烈的；狂暴的；偏激的；患狂犬病的', 726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diurnal', 'adj. 白天的；每日的，一日间的 n. 日记账；日报，日刊', 727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emotion', 'n. 情感；情绪', 728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heteromorphic', 'adj. [生物] 异形的，[生物] 异态的；[化学] 多晶型的', 729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'displace', 'v. 取代；置换；转移；把…免职；排水', 730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stripling', 'n. 年轻人，小伙子', 731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terrify', 'v. 恐吓；使恐怖；使害怕', 732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indolent', 'adj. 懒惰的；无痛的', 733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recriminate', 'v. 反责；反唇相讥', 734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apparent', 'adj. 显然的；表面上的', 735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perennial', 'adj. 多年生的；常年的；四季不断的；常在的；反复的 n. 多年生植物', 736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inimical', 'adj. 敌意的；有害的', 737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heterogeneity', 'n. [生物] 异质性；[化学] 不均匀性；[化学] 多相性', 738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nominate', 'v. 推荐；提名；任命；指定', 739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seclusion', 'n. 隔离；隐退；隐蔽的地方', 740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'polar', 'adj. 极地的；两极的；正好相反的 n. 极面；极线', 741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scour', 'v. 冲刷；擦；腹泻 n. 擦，冲刷；洗涤剂；（畜类等的）腹泻', 742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stigma', 'n. [植] 柱头；耻辱；污名；烙印；特征', 743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refractory', 'adj. 难治的；难熔的；不听话的 n. 倔强的人；耐火物质', 744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disregard', 'v. 忽视；不理；漠视；不顾 n. 忽视；不尊重', 745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'simultaneous', 'adj. 同时的；联立的；同时发生的 n. 同时译员', 746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'levee', 'n. 堤坝（码头）；（旧时君主或显贵的）早晨接见 vt. 为…筑堤', 747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pollute', 'v. 污染；玷污；败坏', 748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prejudice', 'n. 偏见；侵害 v. 损害；使有偏见', 749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stern', 'n. 船尾；末端 adj. 严厉的；坚定的', 750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'colloid', 'adj. 胶质的 n. [物化] 胶质', 751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'admittance', 'n. 进入；入场权；通道', 752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ductile', 'adj. 柔软的；易教导的；易延展的', 753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divergent', 'adj. 相异的，分歧的；散开的', 754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'triangle', 'n. 三角（形）；三角关系；三角形之物；三人一组', 755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'detonate', 'v. 使爆炸', 756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'occult', 'adj. 神秘的；超自然的；难以理解的 v. 掩蔽 n. 神秘学', 757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inchoate', 'adj. 早期的；刚开始的；未充分发展的 vt. 开始 vi. 开始', 758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'placenta', 'n. [胚] 胎盘；[植] 胎座', 759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inconsistent', 'adj. 不一致的；前后矛盾的', 760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adhesion', 'n. 粘附；支持；固定', 761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'taunt', 'n. 嘲弄；讥讽 v. 奚落；逗弄 adj. 很高的', 762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'juxtaposition', 'n. 并置，并列；毗邻', 763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'testament', 'n. [法] 遗嘱；圣约；确实的证明', 764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acquainted', 'adj. 熟识的；知晓的；有知识的 v. 使了解（acquaint的过去分词）', 765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inventive', 'adj. 发明的；有发明才能的；独出心裁的', 766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adversity', 'n. 逆境；不幸；灾难；灾祸', 767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erratic', 'adj. 不稳定的；古怪的 n. 漂泊无定的人；古怪的人', 768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reck', 'vt. 顾虑；和…相干 vi. 介意；有关系 n. (Reck)人名；(英、德、匈、波)雷克', 769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instruct', 'v. 指导；通知；命令；教授', 770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'substantiate', 'v. 证实；使实体化', 771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'centurion', 'n. 百夫长；百人队队长', 772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recuperate', 'v. 恢复，复原；挽回损失', 773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diagonal', 'adj. 斜的；对角线的；斜纹的 n. 对角线；斜线', 774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prehension', 'n. 理解；抓住', 775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'effigy', 'n. 雕像，肖像', 776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutrality', 'n. 中立；中性；中立立场', 777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'competence', 'n. 能力，胜任；权限；作证能力；足以过舒适生活的收入', 778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rapine', 'n. 掠夺；劫掠', 779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appropriate', 'adj. 适当的；恰当的；合适的 v. 占用，拨出', 780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'benignant', 'adj. 良性的；仁慈的；有益的；和蔼的', 781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overlap', 'n. 重叠；重复 v. 部分重叠；部分的同时发生', 782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'premise', 'v. 引出，预先提出；作为…的前提 n. 前提；上述各项；房屋连地基', 783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outburst', 'n. （火山、情感等的）爆发；破裂', 784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'usurious', 'adj. 高利贷的', 785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forthright', 'adj. 直率的；直截了当的 adv. 直率地；马上；立即 n. 直路', 786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inviolable', 'adj. 不可侵犯的；神圣的；不可亵渎的', 787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'academy', 'n. 学院；研究院；学会；专科院校', 788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encyclopedia', 'n. 百科全书（亦是encyclopaedia）', 789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conventional', 'adj. 符合习俗的，传统的；常见的；惯例的', 790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intersect', 'v. 相交，交叉', 791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dearth', 'n. 缺乏；饥馑；粮食不足', 792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bridge', 'n. 桥；桥牌；桥接器；船桥 v. 架桥；渡过', 793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'release', 'v. 释放；发射；让与；允许发表 n. 释放；发布；让与', 794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accolade', 'n. 荣誉；荣誉称号授予仪式；连谱号；称赞', 795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appreciate', 'v. 欣赏；感激；领会；鉴别', 796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equivalent', 'adj. 等价的，相等的；同意义的 n. 等价物，相等物', 797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nomadic', 'adj. 游牧的；流浪的；游动的', 798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scope', 'n. 范围；余地；视野；眼界；导弹射程 v. 审视', 799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'erosion', 'n. 侵蚀，腐蚀', 800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'organelle', 'n. [细胞] 细胞器；细胞器官', 801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mutation', 'n. [遗] 突变；变化；元音变化', 802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'combustion', 'n. 燃烧，氧化；骚动', 803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adverse', 'adj. 不利的；相反的；敌对的（名词adverseness，副词adversely）', 804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'achromatic', 'adj. 消色差的；非染色质的；非彩色的', 805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affiliate', 'n. 联号；隶属的机构等 v. 使附属；接纳；使紧密联系', 806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fungi', 'n. 真菌；菌类；蘑菇（fungus的复数）', 807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'variegated', 'adj. 杂色的；斑驳的；富于变化的 v. 成为杂色（variegate的过去式）', 808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'poverty', 'n. 贫困；困难；缺少；低劣', 809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stupor', 'n. 昏迷，恍惚；麻木', 810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inhume', 'v. 埋葬；土葬', 811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indifferent', 'adj. 漠不关心的；无关紧要的；中性的，中立的', 812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generator', 'n. 发电机；发生器；生产者', 813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evolve', 'v. 发展，进化；进化；使逐步形成；推断出', 814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abstract', 'n. 摘要；抽象；抽象的概念 adj. 抽象的；深奥的 v. 摘要；提取；使……抽象化；转移(注意力、兴趣等)；使心不在焉', 815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'granule', 'n. 颗粒', 816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bauxite', 'n. 矾土，[矿物] 铁铝氧石；[矿物] 铝土矿', 817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bowdlerize', 'v. 删改；删除不妥的文句', 818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'puissant', 'adj. 强大的，强盛的；有势力的，有权力的 n. (Puissant)人名；(法)皮桑', 819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shriek', 'v. 尖叫；促人注意 n. 尖声；尖锐的响声', 820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'esteem', 'v. 尊敬；认为；考虑；估价 n. 尊重；尊敬', 821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diligent', 'adj. 勤勉的；用功的，费尽心血的 n. (Diligent)人名；(法)迪利让', 822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'renunciation', 'n. 放弃；脱离关系；拒绝承认；抛弃；弃权', 823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propitious', 'adj. 适合的；吉利的；顺利的', 824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divisor', 'n. 除数；因子', 825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vile', 'adj. 卑鄙的；邪恶的；低廉的；肮脏的 n. (Vile)人名；(英)瓦伊尔；(芬)维莱', 826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eradicate', 'v. 根除，根绝；消灭', 827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'everlasting', 'adj. 永恒的；接连不断的', 828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'venerate', 'v. 崇敬，尊敬', 829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'duration', 'n. 持续，持续的时间，期间', 830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'benediction', 'n. 祝福；赐福；恩赐；祈求上帝赐福的仪式', 831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unconscious', 'adj. 无意识的；失去知觉的；不省人事的；未发觉的', 832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fossil', 'n. 化石；僵化的事物；顽固不化的人 adj. 化石的；陈腐的，守旧的', 833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'digestion', 'n. 消化；领悟', 834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accursed', 'adj. 被诅咒的；讨厌的；可憎的', 835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'constitute', 'v. 组成，构成；建立；任命', 836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volitive', 'adj. 意志的；表示意志的；发自意志的', 837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'introspect', 'v. 反省；内省', 838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compound', 'n. [化学] 化合物；混合物；复合词 adj. 复合的；混合的 v. 合成；混合；恶化，加重；和解，妥协', 839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'decorous', 'adj. 有礼貌的，高雅的；端正的', 840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'redeem', 'v. 赎回；挽回；兑换；履行；补偿；恢复', 841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'metabolic', 'adj. 变化的；新陈代谢的', 842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lucid', 'adj. 明晰的；透明的；易懂的；头脑清楚的', 843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quail', 'v. 畏缩，胆怯；感到恐惧 n. 鹌鹑', 844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutralize', 'v. 抵销；使…中和；使…无效；使…中立', 845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'torque', 'n. 转矩，[力] 扭矩；项圈，金属领圈 v. (向轴、螺栓、圆轮等)施以扭动力；(使)沿轴转动；使(绕轴等)扭转；施加转矩', 846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'optimal', 'adj. 最佳的；最理想的', 847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wistful', 'adj. 渴望的；沉思的，默想的；引起怀念的；不满足似的', 848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'playwright', 'n. 剧作家', 849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'calumniate', 'v. 诽谤；中伤；诬蔑', 850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bustle', 'v. 喧闹；忙乱；充满 n. 喧闹；活跃；裙撑；热闹的活动', 851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conscientious', 'adj. 认真的；尽责的；本着良心的；小心谨慎的', 852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cerebration', 'n. 思考；精神活动；脑髓作用', 853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'imperative', 'adj. 必要的，不可避免的；紧急的；命令的，专横的；势在必行的；[语]祈使的 n. 必要的事；命令；需要；规则；[语]祈使语气', 854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inspiration', 'n. 灵感；鼓舞；吸气；妙计', 855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'befog', 'v. 使困惑，使模糊；罩入雾中', 856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equiangular', 'adj. 等角的', 857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acidify', 'v. [化学] 酸化；变酸', 858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avalanche', 'n. 雪崩 v. 雪崩', 859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homogeneous', 'adj. 均匀的；[数] 齐次的；同种的；同类的，同质的', 860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pugnacious', 'adj. 好斗的，好战的', 861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'callosity', 'n. 无情；老茧皮；硬结', 862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ultramontane', 'n. 山那边的人；教皇绝对权力主义者 adj. 山那边的', 863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'calumny', 'n. 诽谤；中伤；诬蔑', 864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seedy', 'adj. 多种子的；结籽的；破烂的；没精打采的；下流的', 865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'qualm', 'n. 疑虑；不安', 866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'taciturn', 'adj. 沉默寡言的；无言的，不太说话的', 867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'punctual', 'adj. 准时的，守时的；精确的', 868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'displacement', 'n. 取代，位移；[船] 排水量', 869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'periscope', 'n. 潜望镜', 870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assess', 'v. 评定；估价；对…征税', 871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pauper', 'n. 乞丐；穷人；靠救济度日者 adj. 贫民的', 872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'colloquy', 'n. 以对话体写的文章；谈话，会话', 873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bestrew', 'v. 布满；散布', 874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intrinsic', 'adj. 本质的，固有的', 875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comely', 'adj. 清秀的，标致的', 876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homologous', 'adj. 相应的；[生物] 同源的；类似的；一致的', 877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingenuous', 'adj. 天真的；坦白的；正直的；朴实的', 878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nebula', 'n. 星云；角膜云翳', 879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prosecute', 'v. 检举；贯彻；从事；依法进行', 880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ebullient', 'adj. 热情洋溢的；沸腾的', 881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'absence', 'n. 没有；缺乏；缺席；不注意', 882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coercion', 'n. 强制；强迫；高压政治；威压', 883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumvent', 'v. 包围；智取；绕行，规避', 884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amatory', 'adj. 恋爱的，情人的', 885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'swindle', 'n. 欺诈；骗局 v. 诈骗；骗取', 886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preemption', 'n. 优先购买；强制收购；抢先占有；取代', 887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'athirst', 'adj. 渴望的', 888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ensemble', 'n. 全体；总效果；全套服装；全套家具；合奏组 adv. 同时', 889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artifact', 'n. 人工制品；手工艺品', 890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'succumb', 'v. 屈服；死；被压垮', 891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mixture', 'n. 混合；混合物；混合剂', 892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assert', 'v. 维护，坚持；断言；主张；声称', 893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'viceroy', 'n. 总督；（北美）一种黑色蝴蝶', 894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'variable', 'adj. 变量的；可变的；易变的，多变的；变异的，[生物] 畸变的 n. [数] 变量；可变物，可变因素', 895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'feat', 'n. 功绩，壮举；技艺表演 adj. 合适的；灵巧的', 896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'decrease', 'n. 减少，减小；减少量 v. 减少，减小', 897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'figurine', 'n. 小雕像，小塑像', 898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prohibition', 'n. 禁止；禁令；禁酒；诉讼中止令', 899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caucus', 'n. 干部会议；核心会议；党团会议 v. 召开干部会议；开核心会议', 900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hormone', 'n. [生理] 激素，荷尔蒙', 901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sentient', 'adj. 有感情的；有感觉力的；意识到的 n. 有知觉的人', 902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blockbuster', 'n. 轰动；巨型炸弹；一鸣惊人者', 903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'questionable', 'adj. 可疑的；有问题的', 904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'punctilious', 'adj. 一丝不苟的；精密细心的；拘泥形式的', 905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'album', 'n. 相簿；唱片集；集邮簿；签名纪念册', 906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valediction', 'n. 告别演说；告别词', 907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encounter', 'v. 遭遇，邂逅；遇到 n. 遭遇，偶然碰见', 908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ruminate', 'v. 反刍；沉思；反复思考', 909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stunt', 'n. 噱头，手腕；绝技 v. 阻碍…的正常生长或发展', 910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abrupt', 'adj. 生硬的；突然的；唐突的；陡峭的', 911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'drought', 'n. 干旱；缺乏', 912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affected', 'adj. 受到影响的；做作的；假装的 vt. 影响；假装；使…感动（affect的过去式和过去分词）', 913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commit', 'v. 犯罪，做错事；把交托给；指派…作战；使…承担义务', 914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cherish', 'v. 珍爱', 915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glamorous', 'adj. 迷人的，富有魅力的', 916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pluralism', 'n. 多元主义；多元论；兼任', 917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instance', 'n. 实例；情况；建议 v. 举为例', 918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barometer', 'n. [气象] 气压计；晴雨表；显示变化的事物', 919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'austere', 'adj. 严峻的；简朴的；苦行的；无装饰的', 920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disingenuous', 'adj. 虚伪的；不诚实的；不老实的；狡猾的', 921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'miscount', 'v. 数错；算错 n. 数错；误算', 922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'charming', 'adj. 迷人的；可爱的 v. 使陶醉（charm的现在分词）', 923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deference', 'n. 顺从；尊重', 924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preempt', 'v. 先占；先取；以先买权获得', 925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'practitioner', 'n. 开业者，从业者，执业医生', 926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pageant', 'n. 盛会；游行；虚饰；露天表演', 927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pigment', 'n. [物][生化] 色素；颜料 v. 给…着色', 928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lacerate', 'v. 伤害，使…痛心；割裂；撕碎 adj. 受折磨的；撕碎的', 929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'efficacious', 'adj. 有效的；灵验的', 930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conjugation', 'n. 结合，配合；动词的词形变化', 931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambulance', 'n. [车辆][医] 救护车；战时流动医院', 932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'humble', 'adj. 谦逊的；简陋的；（级别或地位）低下的；不大的 v. 使谦恭；轻松打败（尤指强大的对手）；低声下气', 933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minority', 'n. 少数民族；少数派；未成年 adj. 少数的；属于少数派的', 934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fortitude', 'n. 刚毅；不屈不挠；勇气', 935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antibody', 'n. [免疫] 抗体', 936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'narrate', 'v. 叙述；给…作旁白', 937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sophism', 'n. 诡辩', 938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sum', 'n. 金额；总数 v. 概括', 939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unyielding', 'adj. 不屈的；坚强的；[材] 不易弯曲的', 940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paragon', 'n. 模范；完美之物；优秀之人 adj. 完美的', 941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aliment', 'n. 滋养品；食物 v. 向…提供营养物', 942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'illiterate', 'adj. 文盲的；不识字的；没受教育的 n. 文盲', 943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'panorama', 'n. 全景，全貌；全景画；概论', 944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vivify', 'v. 使生动；使活跃；给与生气', 945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abundant', 'adj. 丰富的；充裕的；盛产', 946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acrimony', 'n. 辛辣；尖刻；严厉', 947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rust', 'n. 锈；生锈；[植保] 锈病 v. 使生锈；腐蚀', 948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fission', 'n. 裂变；分裂；分体；分裂生殖法', 949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volition', 'n. 意志，意志力；决断力', 950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recapitulate', 'v. 概括；重述要点；摘要', 951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ominous', 'adj. 预兆的；不吉利的', 952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedigree', 'n. 血统；家谱 adj. 纯种的', 953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ethnic', 'adj. 种族的；人种的', 954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'negate', 'v. 否定；取消；使无效 n. 对立面；反面', 955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'granular', 'adj. 颗粒的；粒状的', 956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malodorous', 'adj. 有恶臭的；令人极为反感的；不合法的', 957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nascent', 'adj. 初期的；开始存在的，发生中的', 958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'negotiate', 'v. 谈判，商议；转让；越过', 959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'capricious', 'adj. 反复无常的；任性的', 960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impartial', 'adj. 公平的，公正的；不偏不倚的', 961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'organic', 'adj. [有化] 有机的；组织的；器官的；根本的', 962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distort', 'v. 扭曲；使失真；曲解', 963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temporal', 'adj. 暂时的；当时的；现世的 n. 世间万物；暂存的事物', 964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scribble', 'n. 潦草写成的东西；潦草的写法；杂文 v. 乱写；滥写；潦草地书写', 965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'calculus', 'n. [病理] 结石；微积分学', 966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electrolysis', 'n. [化学] 电解，[化学] 电解作用；以电针除痣', 967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circuit', 'n. [电子] 电路，回路；巡回；一圈；环道 v. 环行', 968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissuade', 'v. 劝阻，劝止', 969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'relish', 'n. 滋味；风味；食欲；开胃小菜；含义；调味品 v. 盼望;期待;享受; 品味；喜爱；给…加佐料', 970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brief', 'adj. 简短的，简洁的；短暂的，草率的 n. 摘要，简报；概要，诉书 v. 简报，摘要；作…的提要', 971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impetuous', 'adj. 冲动的；鲁莽的；猛烈的', 972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'odorous', 'adj. 香的；有气味的；难闻的', 973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malice', 'n. 恶意；怨恨；预谋', 974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'astringent', 'adj. 涩的；收敛性的；止血的；严厉的 n. [药] 收敛剂；止血药', 975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brine', 'n. 卤水；盐水；海水 v. 用浓盐水处理（或浸泡）', 976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'venerable', 'adj. 庄严的，值得尊敬的；珍贵的', 977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prototype', 'n. 原型；标准，模范', 978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corrupt', 'adj. 腐败的，贪污的；堕落的 v. 使腐烂；使堕落，使恶化', 979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agility', 'n. 敏捷；灵活；机敏', 980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coercive', 'adj. 强制的；胁迫的；高压的', 981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'carnage', 'n. 大屠杀；残杀；大量绝灭', 982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'simultaneously', 'adv. 同时地', 983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'urea', 'n. [肥料] 尿素', 984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serenity', 'n. 平静，宁静；晴朗，风和日丽', 985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'toxic', 'adj. 有毒的；中毒的', 986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'yearling', 'n. 一岁家畜；满一岁的动物 adj. 一岁的', 987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'guile', 'n. 狡猾；诡计；欺诈', 988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affiliation', 'n. 友好关系；加入；联盟；从属关系', 989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compression', 'n. 压缩，浓缩；压榨，压迫', 990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cameo', 'n. （影视剧中的）配角；刻有浮雕的宝石或贝壳；小品文', 991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sacrosanct', 'adj. 神圣不可侵犯的；极神圣的', 992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nugatory', 'adj. 无价值的；琐碎的；无效的；无法律效力的', 993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brigadier', 'n. 准将；陆军准将', 994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gregarious', 'adj. 社交的；群居的', 995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unqualified', 'adj. 不合格的；无资格的；不胜任的；不受限制的；无条件的；绝对的', 996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'risible', 'adj. 可笑的；爱笑的；引人笑的', 997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'criticize', 'v. 批评；评论；非难', 998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bauble', 'n. 小玩意；美观而无价值的饰物', 999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assiduous', 'adj. 刻苦的，勤勉的', 1000);
