INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'induce', 'v.  劝诱； 促使； 引起， 导致； 感应', 7001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bisect', 'v.  把…二等分', 7002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'thoroughbred', 'adj.   纯种的， 良种的', 7003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abnormal', 'adj.  反常的， 不正常的', 7004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wane', 'v.  变小， 衰落', 7005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volt', 'n.  伏特', 7006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satirize', 'v.  讽刺', 7007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shrewd', 'adj.  敏捷的， 机灵的， 精明的， 伶俐的', 7008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'difference', 'n.  差； 差额', 7009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'baffle', 'vt.  困惑； 阻碍； 为难', 7010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extricate', 'v.  救出； 使脱离', 7011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'molecule', 'n.  分子', 7012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circle', 'n.  圆', 7013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reminiscent', 'adj.  回忆往事的', 7014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'butt', 'v.  以头低撞， 碰撞 n. 粗大的一端；笑柄', 7015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'safeguard', 'v. 维护，保护，捍卫 n.  安全装置， 安全措施', 7016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diligent', 'adj.  勤奋的， 刻苦的', 7017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sophisticated', 'adj.  尖端的， 复杂的， 先进的； 老练的， 老于世故的', 7018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anomaly', 'n.  不规则， 异常的人或物', 7019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equivocal', 'adj.  意义不明确的； 模棱两可的； 可疑的', 7020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prehensile', 'adj.  适于抓住的', 7021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scrutiny', 'n.  详细审查', 7022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'realism', 'n.  现实主义', 7023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'archaic', 'adj.  古老的； 古代的； 陈旧的', 7024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ravine', 'n.  沟壑； 峡谷', 7025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inalienable', 'adj.   不能让与的， 不可剥夺的', 7026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quadrilateral', 'n.  四边形', 7027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chasm', 'n.  深坑， 裂口', 7028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'butane', 'n.  丁烷', 7029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reprobate', 'v.  非难', 7030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'digestion', 'n.  消化', 7031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'putrid', 'adj.  腐烂的； 非常讨厌的', 7032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inclement', 'adj.  险恶的； 严酷的', 7033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enlist', 'v.  征募， 征召， 参军', 7034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'latest', 'adj.  最近的', 7035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'validate', 'v.  使有效， 使有法律效力； 批准； 确认', 7036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'guileless', 'adj.  坦率的', 7037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'a. 灵巧的， 熟练的', 'n.  灵巧， 机敏', 7038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inhibit', 'vt.  阻止， 妨碍， 抑制', 7039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disclose', 'v.  泄露； 揭发； 解开', 7040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unspeakable', 'adj.  无法形容的， 不能以言语表达的', 7041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disparate', 'adj.  全异的', 7042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clientele', 'n.  诉讼委托人， 客户', 7043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dilapidate', 'v.   荒废，  毁坏', 7044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'defiant', 'adj.  挑战的， 挑衅的， 目中无人的', 7045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'powerless', 'adj.  无能力的', 7046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oxide', 'n.  氧化物', 7047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perusal', 'n.  熟读， 精读', 7048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arbor', 'n.  树阴处，  藤架， 凉亭', 7049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonize', 'v.   敌对；  对抗', 7050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chart', 'n.  图表', 7051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evoke', 'vt.  唤起， 引起， 使人想起', 7052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preface', 'n.  序言， 引言， 前言', 7053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonism', 'n.  对抗； 敌对', 7054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antagonist', 'n.  敌手， 对手', 7055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incite', 'v.  激动， 煽动', 7056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutron', 'n.  中子', 7057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mediocrity', 'n.  平凡； 平庸之才', 7058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interpose', 'v.  插入', 7059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inexcusable', 'adj.  无法辩解的， 不可宽赦的', 7060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immense', 'adj.  广大的， 巨大的', 7061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vacate', 'v.  腾出； 空出， 离 ， 退', 7062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inherent', 'adj.  固有的， 内在的， 天生的', 7063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'advantageous', 'adj.  有利的', 7064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encroach', 'v.   侵占， 蚕食； 超出通常  界线', 7065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facsimile', 'n.  复制品， 摹本', 7066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'definite', 'adj.  明确的， 肯定的， 一定的', 7067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wary', 'adj.  机警的', 7068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'weight', 'n.  重量', 7069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intrinsic', 'adj.  固有的， 本质的， 内在的', 7070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissemble', 'v.  掩饰', 7071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'guilty', 'adj.  犯罪的， 有罪的； 自觉有罪的， 内疚的， 心虚的', 7072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'median', 'n.  中点； 中线', 7073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vestige', 'n.  退化器官； 残余', 7074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kleptomaniac', 'n.  有盗窃癖的人', 7075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'proximity', 'n.  接近， 近似', 7076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maritime', 'adj.  海上的； 海事的， 海运的； 海员的', 7077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'injurious', 'adj.  有害的', 7078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quibble', 'n.  谬论； 双关话； 俏皮话； 吹毛求疵的意见', 7079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plural', 'adj. 复数的 n.  复数', 7080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prank', 'n.  胡闹， 开玩笑， 恶作剧', 7081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bullock', 'n.  阉牛； 一岁半以下的小公牛', 7082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heartrending', 'adj.  悲惨的； 令人心碎的', 7083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ceremonial', 'adj.  仪式的； 礼仪的 n. 仪式', 7084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ozone', 'n.  臭氧', 7085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wave', 'n.  波', 7086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'squabble', 'v.  争论', 7087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rustic', 'adj.  乡村的', 7088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distend', 'v.  扩大； 膨胀', 7089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tipsy', 'adj.  喝醉的', 7090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lave', 'v.  为…沐浴； 洗', 7091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prudent', 'adj.  谨慎的， 深谋远虑的', 7092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autocrat', 'n.  独裁者', 7093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cower', 'v.  畏缩， 退缩', 7094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'attenuate', 'v.  稀释', 7095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'juxtapose', 'v.  并置， 并列', 7096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'loathe', 'vt.  厌恶， 憎恶', 7097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rotation', 'n.  转动', 7098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temerity', 'n.  鲁莽； 冒失', 7099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intruder', 'n.  入侵者', 7100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infinitesimal', 'adj. 无穷小的，极小的 n.  极小量， 极微量， 无限小', 7101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volatile', 'adj.  挥发性的； 易变的； 不稳定的', 7102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contentious', 'adj.  好争吵的； 争论的， 有异议的', 7103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'communicative', 'adj.  爱说话的， 畅谈的', 7104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generic', 'adj.  一般的， 普通的', 7105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endorse', 'v.  在  背面签名； 签注 ； 认可', 7106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clarity', 'n.  清楚， 透明', 7107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laud', 'n.  称赞， 赞美； 颂歌', 7108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seclude', 'v.  隐居， 与世隔绝', 7109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heinous', 'adj.  可憎的， 极恶的', 7110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'typical', 'adj.  典型的， 象征性的', 7111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embargo', 'v.  禁止  出入港口， 禁止通商， 禁运', 7112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quotation', 'n.  引用语', 7113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'watt', 'n.  瓦特', 7114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nocturnal', 'adj.  夜的， 夜间发生的', 7115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corrosion', 'n.  腐蚀', 7116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vortex', 'n.  旋涡， 旋风， 涡流；  的中心', 7117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'notorious', 'adj.  臭名昭著的， 声名狼藉的', 7118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accusatory', 'adj.  非难的， 控诉的， 指责的', 7119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'verisimilar', 'adj.  好像真实的', 7120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aggravation', 'n.  加重， 恶化； 恼怒', 7121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hydrogen', 'n.  氢', 7122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outstretch', 'v.  伸出， 伸展', 7123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prate', 'v.  唠叨； 闲聊', 7124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artifact', 'n.  人工制品', 7125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hypotenuse', 'n.  直角三角形的斜边', 7126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aviary', 'n.   大型鸟舍； 鸟类饲养场', 7127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedal', 'v.  踩踏板； 骑自行车 n. 踏板', 7128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'endemic', 'adj.  风土的； 地方的 n. 地方病', 7129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nugatory', 'adj.  无价值的； 无效的', 7130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insightful', 'adj.  洞察力强的', 7131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ambulance', 'n.  救护车', 7132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extraction', 'n.  萃取', 7133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'philosophy', 'n.  哲学', 7134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'slope', 'n.   斜率', 7135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blatant', 'adj.  明显的； 明目张胆的； 厚颜无耻的', 7136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pungent', 'adj.  辣的；  有刺激性的', 7137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lapse', 'vi.  终止， 失效； 陷入  …状态 n. 失误，疏忽；行为有失检点，失足；流逝，间隔', 7138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perfunctory', 'adj.  马虎的； 敷衍的', 7139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'latent', 'adj.  潜在的， 潜伏的， 不易察觉的', 7140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quandary', 'n.  困惑， 窘境， 进退两难', 7141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'regenerate', 'v.  使再生； 重建', 7142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'light', 'n.  光', 7143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nauseate', 'v.  产生恶感， 厌恶； 作呕', 7144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corporal', 'adj.  肉体的； 身体的', 7145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stanza', 'n.  诗的一节', 7146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diode', 'n.  二级管', 7147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impute', 'v.  归罪于， 归咎于， 归因于', 7148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indomitable', 'adj.  不屈服的， 不屈不挠的', 7149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acidify', 'v.  使酸化， 使成酸性', 7150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antibiotics', 'n.  抗生素', 7151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'muddle', 'v.  混合', 7152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jocund', 'adj.  欢乐的， 高兴的', 7153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ponderous', 'adj.  笨重的； 冗长的， 沉重的； 呆板的', 7154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'infection', 'n.  感染', 7155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stubborn', 'adj.  顽固的， 倔强的； 难对付的， 难以克服的', 7156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'actuate', 'vt.  开动， 促使', 7157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emigrate', 'v.  迁居', 7158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'triangle', 'n.  三角形', 7159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sinuous', 'adj.  蜿蜒的； 曲折的', 7160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alien', 'adj.  外国的； 相异的； 不相容的 n. 外侨；外星人', 7161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bucolic', 'adj.  牧羊的； 牧歌的； 田园风味的', 7162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'attest', 'v.  证明', 7163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cavil', 'v.  吹毛求疵， 挑剔； 指责', 7164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'berate', 'vt.  严厉指责； 申斥', 7165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'profligate', 'adj.  放荡的， 荒淫的； 挥霍浪费的', 7166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lexicon', 'n.  词典', 7167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predatory', 'adj.  掠夺的； 食肉的', 7168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deficient', 'adj.  不足的， 缺乏的， 欠缺的', 7169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impropriety', 'n.  不适当的行为； 不适当', 7170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'yip', 'v.  犬吠； 叫喊', 7171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barrel', 'n.  桶； 枪管， 炮管', 7172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unify', 'v.  统一， 使成一体', 7173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sapiential', 'adj.  明智的', 7174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rookie', 'n.  新手', 7175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ravage', 'v.  毁坏， 掠夺', 7176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'barren', 'adj.   贫瘠的， 荒芜的； 不结果实的， 不  育的； 无益的， 没有结果的', 7177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'garrulous', 'adj.  饶舌的， 多嘴的', 7178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accompanist', 'n.  伴奏者', 7179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fungi', 'n.  真菌', 7180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grandiose', 'adj.  宏伟的； 冠冕堂皇的， 浮夸的', 7181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'permanent', 'adj.  永久的， 持久的', 7182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foster', 'adj.  收养的， 收养孩子的 vt. 收养，养育；领养；培养，促进', 7183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tricycle', 'n.  三轮车', 7184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facility', 'n. 设施；设备；容易；灵巧', 7185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gregarious', 'adj.  社交的； 群居的', 7186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hydrolysis', 'n.  水解作用', 7187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beam', 'n.  光束', 7188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peevish', 'adj.  易怒的， 暴躁的', 7189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gallant', 'adj.  英勇的， 豪侠的', 7190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inalterable', 'adj.  不能变更的， 不变的', 7191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'visage', 'n.  面貌， 容貌', 7192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solidification', 'n.  凝固', 7193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perspire', 'v.  出汗， 流汗', 7194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emulate', 'n.  仿效； 超越', 7195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assonant', 'adj.  谐韵的', 7196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'synthesize', 'v.  综合； 合成', 7197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irascible', 'adj.  易怒的， 暴躁的', 7198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sanguineous', 'adj.  血的', 7199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peremptory', 'adj.  断然的； 专横的； 强制的', 7200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumlocution', 'n.  婉转曲折的陈述', 7201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vindictive', 'adj.  报复性的', 7202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'playwright', 'n.  剧作家', 7203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interrupt', 'v.  中断， 阻碍； 打断 ， 打扰', 7204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emphasis', 'n.  强调， 重点', 7205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beau', 'n.  好打扮者； 花花公子； 男朋友', 7206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'feasible', 'adj.  可行的， 切实可行的', 7207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unassuming', 'adj.  谦逊的； 不装腔作势的', 7208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forebode', 'v.  预示， 预言， 预兆', 7209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prepossess', 'vt.  使先有好感， 使偏爱； 预先拥有', 7210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'potential', 'adj. 潜在的，可能的；势的，位的 n.  潜能， 潜力', 7211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volant', 'adj.  会飞的； 迅速的， 敏捷的', 7212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'actuary', 'n.  保险进算师， 保险  计算员', 7213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gross', 'adj.  总的， 毛的', 7214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vigilant', 'adj.  警惕着的， 警醒的', 7215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tact', 'n.  机智， 老练', 7216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bereave', 'vt.  剥夺， 使失去', 7217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epicure', 'n.  美食家', 7218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allotment', 'n.  分配', 7219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'archive', 'n. 档案馆 vt.  存档', 7220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valorous', 'adj.  勇敢的， 无畏的', 7221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stimulate', 'v.  刺激， 使兴奋； 激励， 鼓舞', 7222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'eclipse', 'n.  日食， 月食', 7223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'square', 'n.  正方形', 7224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'counteract', 'v.  抵消， 中和； 阻碍', 7225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'animosity', 'n.  仇恨， 憎恶', 7226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'debilitate', 'v.  使衰弱， 使虚弱', 7227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interference', 'n.  干涉', 7228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commute', 'v.  交换； 减刑； 通勤', 7229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'altitude', 'n.  高度， 海拔', 7230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'riddance', 'n.  摆脱； 解除', 7231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'classify', 'v.  分类， 分等', 7232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nadir', 'n.  天底； 最低点； 深渊', 7233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'composure', 'n.  镇静， 沉着', 7234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beck', 'n.  点头示意； 招手示意', 7235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convergence', 'n.  集中', 7236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stipend', 'n.  薪金， 定期生活津贴', 7237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allusion', 'n.  典故， 引用典故； 暗示', 7238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sacrosanct', 'adj.  不可侵犯的； 极神圣的', 7239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'point', 'n.  小数点', 7240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'beguile', 'vt.  诱骗； 诱惑', 7241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'debut', 'n.  初次登台', 7242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forerun', 'v.  预示； 跑在…之前', 7243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prehension', 'n.  抓住； 理解', 7244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evanescent', 'adj.  易消散的； 会凋零的', 7245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stripling', 'n.  年轻人', 7246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'uphold', 'v.  支持， 赞成； 举起； 坚持', 7247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alias', 'n.  别名， 化名', 7248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dimension', 'n.  尺寸， 尺度； 维  ； 度  ， 元', 7249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nostalgia', 'n.  思家病， 乡愁； 向往过去, 怀旧之情', 7250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obtrusive', 'adj.  突出的； 强迫的； 引人注意的', 7251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alternative', 'adj.  选择性的， 两者择一的 n. 两者择一，可供选择的办法', 7252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'workmanship', 'n.  手艺， 技艺， 技巧', 7253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encounter', 'v. 遇到，遭遇〔尤指问题或反对〕 n. 相遇，邂逅', 7254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'soda', 'n.  苏打', 7255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'empathetic', 'adj.  移情作用的， 感情移入的', 7256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lassitude', 'n.  疲乏； 没精打采', 7257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agrarian', 'adj.  有关土地的， 耕地的', 7258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extrovert', 'n.  性格外向者', 7259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mean', 'v. 表示…的意思；意指；意味着；意欲，打算；注定；怀有特定用意；具有意义 adj. 低劣的，卑鄙的；平庸的；没有价值的；难看的，破旧的；吝啬的；中等的；平均的；中项的 n.  平均 ， 中数', 7260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pedestrian', 'adj.  徒步的； 呆板的； 平庸的 n. 步行者', 7261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appall', 'vt.  使惊骇， 使大吃一惊， 使恐怖', 7262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radioactive', 'adj.  放射性的， 放射引起的', 7263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repulse', 'v.  拒绝， 排斥； 憎恶', 7264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hoarse', 'adj.  嘶哑的', 7265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rectitude', 'n.  正直； 公正', 7266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tenable', 'adj.   守得住的， 可防守的；  站得住脚的；  有条理的', 7267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stimulant', 'n.  刺激物', 7268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vivacity', 'n.  活泼', 7269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appreciate', 'vt.  感谢， 感激； 正确评价， 欣赏， 赏识', 7270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undersize', 'adj.  较一般为小的， 不够大的', 7271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'qualitative', 'adj.  性质上的， 定性的', 7272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diverse', 'adj.  多种多样的， 不同的， 变化多的', 7273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'murderous', 'adj.  行凶的， 凶恶的； 非常危险的', 7274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fictitious', 'adj.  小说中的， 假想的； 假装的； 虚伪的', 7275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intellect', 'n.  智力', 7276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preoccupy', 'v.  使全神贯注， 迷住', 7277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preference', 'n.  偏爱， 喜爱； 优惠； 优先选择', 7278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mainstream', 'n.  主流', 7279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enthusiast', 'n.  热情者， 热衷者', 7280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apotheosis', 'n.  尊为神， 神话； 典范', 7281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'temperate grassland', '温带草原，温带草地', 7282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alchemy', 'n.  炼金术', 7283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'distort', 'v.  弄歪  ； 扭曲， 歪曲', 7284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'litigious', 'adj.  好诉讼的； 好争论的', 7285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'population', 'n.  种群', 7286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discern', 'v.  认出， 发现； 辨别， 识别； 看清楚', 7287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cancellation', 'n.  约掉； 消掉', 7288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flexible', 'adj.  柔韧的， 易弯曲的， 灵活的', 7289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diurnal', 'adj.  日间的', 7290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transience', 'n.  短暂', 7291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overstride', 'v.  跨过， 超过， 越过', 7292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'timorous', 'adj.  胆小的', 7293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agile', 'adj.  敏捷的， 轻快的； 灵活的', 7294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corpse', 'n.  尸体', 7295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'phonic', 'adj.  声音的； 有声的', 7296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intoxicate', 'v.  使陶醉； 使中毒', 7297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'replenish', 'v.  补充', 7298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amenable', 'adj.  顺从的， 服从劝导的', 7299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mirror', 'n.  镜', 7300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'edify', 'v.  启发； 教化', 7301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perennial', 'adj.  四季不断的， 终年的', 7302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sustainable', 'adj.  可维持的', 7303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inflammatory', 'adj.  煽动性的', 7304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'liquor', 'n.  酒， 烈性酒', 7305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'catabolism', 'n.  分解代谢', 7306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'characteristic', 'adj.  特有的， 表示特性的； 典型的', 7307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'secede', 'v.  脱离， 分离', 7308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rouse', 'v.  惊起； 唤起， 唤醒', 7309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boorish', 'adj.  粗野的， 粗鄙的', 7310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reprehend', 'v.  责备', 7311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disparity', 'n.  不同， 不等； 不一致', 7312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affix', 'vt.  使附于， 黏贴', 7313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'saccharine', 'adj.  糖  的， 似糖的； 产糖的， 含糖的', 7314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'replicate', 'v.  复制', 7315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'desultory', 'adj.  散漫的， 不连贯的', 7316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'parsimonious', 'adj.  吝啬的； 过于俭省的', 7317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'assemble', 'vt.  集合， 集会； 装配， 组装', 7318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'noticeable', 'adj.  显而易见的， 值得注意的', 7319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transition', 'n.  转变， 过渡', 7320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'atonement', 'n.  赎罪， 弥补过失', 7321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chivalry', 'n.   骑士精神； 骑士制度', 7322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repel', 'v.  击退； 抵制， 拒绝， 排斥', 7323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'underscore', 'v.  画线于…下； 强调', 7324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'series', 'n.  系列', 7325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'timidity', 'n.  胆小， 羞怯， 怯懦', 7326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'imaginative', 'adj.  富有想象力的， 想象的； 幻想的， 虚构的', 7327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serum', 'n.  血清', 7328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blase', 'adj.  不感兴趣的； 厌倦的', 7329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'celebrity', 'n.  名声', 7330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'archaeologist', 'n.  考古学家', 7331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accountant', 'n.  会计人员， 会计师', 7332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malignancy', 'n.  恶意', 7333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apathetic', 'adj.  缺乏兴趣的， 缺乏感情的； 无动于衷的', 7334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inborn', 'adj.  天生的， 生来的， 先天的', 7335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inconvenient', 'adj.  不便的， 有困难的', 7336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presentiment', 'n.  预感， 不祥之感', 7337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'absurd', 'adj.  荒唐的', 7338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blockade', 'v.  封锁 n. 阻塞', 7339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'purgatory', 'n.  炼狱， 暂时的苦难', 7340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trait', 'n.  特征， 特点， 特性', 7341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solute', 'n.  溶质', 7342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serviceable', 'adj.  耐用的', 7343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'landmark', 'n.   明显的陆标， 地标； 划时代的事件； 界碑', 7344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hundredth', 'n.  第一百个； 百分之一', 7345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impregnable', 'adj.  无法攻取的， 坚不可摧的', 7346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'venerate', 'v.  崇敬', 7347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vacuous', 'adj.  空虚的； 茫然若失的， 无所事事的', 7348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'afterthought', 'n.  事后的想法， 追悔', 7349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trough', 'n.  波谷', 7350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blandishment', 'n.  奉承， 哄诱', 7351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abed', 'adv.  在床上', 7352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contradictory', 'adj.  反对的， 矛盾的', 7353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preeminence', 'n.  卓越， 杰出', 7354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'succulent', 'adj.  多汁的， 多水分的', 7355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accompany', 'v.  陪同， 伴随； 为…伴奏', 7356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obviate', 'v.  消除； 排除； 预防', 7357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'probity', 'n.  正直； 诚实', 7358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perspicuous', 'adj.   明白易懂的， 清楚的', 7359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'immediate', 'adj.  直接的； 立即的， 即刻的', 7360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excerpt', 'n.  摘录， 选录， 节录', 7361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abet', 'vt.  教唆， 煽动； 帮助， 支持', 7362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minnow', 'n.  鲤类小鱼', 7363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'platitude', 'n.  陈词滥调； 陈腐', 7364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subtlety', 'n.  微妙， 敏锐， 细微的区别', 7365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'upbraid', 'v.  责备， 叱责', 7366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'landlord', 'n.  房东， 地主', 7367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'factious', 'adj.  闹派别的； 好捣乱的', 7368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ingratiate', 'v.  使迎合， 使讨好', 7369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'introductory', 'adj.  引导的， 介绍的', 7370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buffoon', 'n.  小丑', 7371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caitiff', 'adj.  卑劣的； 胆小的', 7372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'apiece', 'adv.  每人， 每个', 7373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lurid', 'adj.  苍白的， 可怕的； 血红的； 耸人听闻的', 7374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preempt', 'v.  预先制止； 抢在…之前做或说', 7375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hone', 'v.   磨， 把…放在磨石上磨 n. 细磨刀石', 7376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cursory', 'adj.  仓促的， 草率的', 7377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insouciance', 'n.  漫不经心， 不在乎', 7378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'primp', 'v.  细心打扮， 过分装饰', 7379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corroborate', 'v.  使坚固； 确证', 7380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bland', 'adj.  温和的， 柔和的； 乏味的； 冷漠的', 7381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'atone', 'vi.  弥补', 7382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disparage', 'v.  蔑视， 贬损； 使失去信誉', 7383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'yummy', 'adj.  美味的； 赏心悦目的', 7384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bursar', 'n.   会计', 7385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outlast', 'v.  比…长久， 比…活得长', 7386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utopian', 'adj.  乌托邦的， 理想化的', 7387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tangible', 'adj.  确实的， 触摸得到的， 具体的', 7388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impend', 'v.  即将发生', 7389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pious', 'adj.  虔诚的', 7390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'congest', 'v.  使充满， 使拥塞', 7391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mordent', 'n.  【音】 波音', 7392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'witticism', 'n.  妙语； 俏皮话', 7393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'approximately', 'adv.  近似地， 大约地', 7394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diplomat', 'n.  外交官', 7395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monocracy', 'n.  独裁政治', 7396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incubus', 'n.  梦魇； 沉重的负担', 7397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hut', 'n.  小屋， 棚屋', 7398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'artifice', 'n.  巧办法； 欺骗', 7399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'collaborate', 'v.  协作， 合作', 7400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'superficial', 'adj.  表面的； 肤浅的， 浅薄的', 7401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'opprobrium', 'n.  耻辱； 责骂', 7402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mirage', 'n.  海市蜃楼； 幻想', 7403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impasse', 'n.  僵局', 7404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subterranean', 'adj.  地下的', 7405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lacerate', 'v.  割裂', 7406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demolition', 'n.  毁坏', 7407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'displacement', 'n.  位移', 7408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oration', 'n.  演说', 7409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'casualty', 'n.  伤亡事故； 人员伤亡', 7410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'whimsical', 'adj.  异想天开的； 反复无常的', 7411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prism', 'n.  棱镜', 7412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penury', 'n.  贫困， 贫穷', 7413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cartographer', 'n.  地图制作者', 7414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'valedictory', 'adj. 告别的 n.  告别词', 7415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'idolatry', 'n.  偶像崇拜； 盲目崇拜', 7416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'studious', 'adj.  好学的； 刻苦的， 勤奋的', 7417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ridicule', 'v.  嘲笑， 奚落', 7418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'propulsion', 'n.  推进力', 7419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'butte', 'n.   孤山， 孤峰', 7420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensitive', 'adj.  敏感的； 灵敏的', 7421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scintillate', 'v.  发出火花', 7422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'singe', 'v.  烧焦， 烤焦', 7423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irate', 'adj.  生气的， 发怒的', 7424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impression', 'n.  印象， 感想； 盖印， 压痕', 7425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inequity', 'n.  不公平， 不公正', 7426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appease', 'vt.  平息； 安抚， 缓和； 满足', 7427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impede', 'v.  妨碍， 阻碍， 阻止', 7428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'volitive', 'adj.  意志的， 表示祈望或准许的', 7429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pepsin', 'n.  胃蛋白酶', 7430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'shield', 'v.  保护， 防护， 遮蔽 n.  防护物， 护罩， 盾， 盾状物', 7431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'statuesque', 'adj.  雕像般的； 庄严而优雅的', 7432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anatomy', 'n.  解剖学； 解剖结构', 7433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gratuity', 'n.  赠物， 赏钱', 7434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'credo', 'n.  信条', 7435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instantaneous', 'adj.  瞬间的， 即刻的', 7436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'phenomenon', 'n. 现象', 7437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'writhe', 'v.  扭曲， 扭歪； 翻腾', 7438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quarterly', 'adv. 每季一次 adj. 每季的 n.  季刊', 7439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'zephyr', 'n.  西风； 微风', 7440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alienable', 'adj.  可让与的', 7441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abbey', 'n.  大修道院； 大教堂', 7442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sensibility', 'n.  敏感性', 7443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bibliography', 'n.   书目； 参考书目', 7444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buoyant', 'adj.  有浮力的； 轻快的', 7445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'chloroplast', 'n.  叶绿体', 7446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intrepid', 'adj.  无畏的； 勇猛的', 7447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'travail', 'n.  辛苦； 苦役； 工作', 7448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dullard', 'n.  傻瓜', 7449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'generalize', 'v.  推广', 7450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accredit', 'v.  信任', 7451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'condenser', 'n.  冷凝器', 7452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paradoxical', 'adj.  似非而是的； 自相矛盾的', 7453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissever', 'v.  割裂； 分开', 7454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'postdate', 'v.  推迟…的日期', 7455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subdue', 'v.  征服； 抑制', 7456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'positive', 'adj. 确实的，明确的；积极的，肯定的；正的，阳性的；十足的，完全的 n.   正片', 7457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trigger', 'vt. 引发，导致 n.  扳机', 7458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'culmination', 'n.  顶点', 7459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'meticulous', 'adj.  小心翼翼的', 7460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recriminate', 'v.  反责， 反唇相讥', 7461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jubilation', 'n.  庆祝', 7462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'radar', 'n.  雷达', 7463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'withhold', 'v.  拒绝， 不给', 7464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presumptuous', 'adj.  自以为是的； 专横的', 7465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'twinge', 'n.  阵痛， 刺痛， 剧痛', 7466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refugee', 'n.  难民， 流亡者', 7467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'kinetic', 'adj.   动学， 动力  的', 7468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rotate', 'v.   旋转', 7469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bowler', 'n.  玩保龄球的人；  投手', 7470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instance', 'n.  例子， 事例， 例证', 7471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'spartan', 'n.  斯巴达人； 强悍勇敢、 结实强壮的人', 7472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inconsequential', 'adj.  不合逻辑的； 不合理的', 7473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inheritance', 'n.  遗传', 7474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convoluted', 'adj.  旋绕的； 费解的', 7475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'laconic', 'adj.  简洁的， 简明的', 7476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embitter', 'v.  使有苦味； 使受苦， 使难受； 使怨恨', 7477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reptile', 'n.  爬行动物', 7478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'integer', 'n.  整数', 7479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tantalize', 'v.  挑逗， 惹弄', 7480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'receptive', 'adj.  善于接受的， 能接纳的', 7481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'heterogeneous', 'adj.  不同种类的', 7482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'astound', 'vt.  使惊骇， 使大吃一惊', 7483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solution', 'n.  溶解', 7484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extrude', 'v.  突出， 伸出', 7485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'opponent', 'adj.  对立的， 对抗的 n. 对手，反对者，敌手', 7486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supplementary', 'adj.  增补的， 补充的', 7487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accelerate', 'v.  加速； 促进', 7488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'spate', 'n.  大水； 大量', 7489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emblem', 'n.  象征， 徽章， 符号', 7490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sophism', 'n.  诡辩； 谬论', 7491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wavelength', 'n.  波长', 7492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clutter', 'n.  混乱， 喧嚣', 7493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'meteorology', 'n.  气象学', 7494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divisible', 'adj.  可整除的', 7495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'canonical', 'adj.  规范的； 权威的', 7496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nomad', 'n.  游牧民； 流浪者', 7497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abrade', 'v.  磨损， 摩擦； 折磨', 7498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'convenient', 'adj.  方便的； 便利的', 7499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vernal', 'adj.  春天的', 7500);
