INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conjunction', 'n. 连接， 结合；连词', 6001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'syndrome', 'n. 综合征', 6002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orderly', 'adj. 整齐的， 有秩序的， 有条理的 n. 勤务兵', 6003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tow', 'n. /', 6004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'meadow', 'n. 草地； 牧场', 6005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'roast', 'vt. 烤， 炙， 烘', 6006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'haul', 'v. 拖， 拉', 6007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'succession', 'n. 连续， 系列；继任， 继承', 6008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'energetic', 'adj. 有力的， 精力旺盛的 <', 6009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'avail', 'v. 有益于， 有助于； 利用 n. 效用， 利益； 帮助', 6010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'product', 'n. 产品， 产物；乘积', 6011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quilt', 'n. 被子', 6012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vinegar', 'n. 醋', 6013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'premier', 'n. 首相， 总理', 6014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intellectual', 'adj. 智力的， 有智力的， 显示智力的 < n. 知识分子', 6015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reclaim', 'vt. 要求归还， 收回 <；开垦', 6016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sarcastic', 'adj. 讽刺的， 挖苦的， 嘲笑的', 6017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cheat', 'vi. 欺骗； 作弊 < n. 骗子；欺诈， 欺骗行为', 6018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disable', 'vt. 使残废； 使丧失能力', 6019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'witch', 'v. 施巫术， 迷惑 n. 女巫， 巫婆', 6020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'anecdote', 'n. 短故事； 轶事， 奇闻', 6021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infect', 'vt. 传染， 感染；影响', 6022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'minor', 'vi. 兼修 adj. 较小的， 较少的， 较次要的 n. 兼修学科', 6023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cop', 'n. 警察', 6024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hostile', 'adj. 敌对的， 敌方的； 怀有敌意的', 6025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bruise', 'vt. 使…受挫伤；打青 n. 伤痕， 擦痕， 青肿', 6026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lad', 'n. 男孩， 小伙子', 6027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pray', 'vt. 请求， 恳求；祈祷， 祈求', 6028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crawl', 'vi. 爬行， 蠕动；缓慢行进 A n. 爬行， 蠕动； 缓慢行进', 6029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gown', 'n. 女式礼服， 女裙服；罩衣； 长袍', 6030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'identical', 'adj. 同一的， 同样的', 6031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plead', 'vi. 恳求， 请求；为…辩护 vt. 提出…为理由', 6032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lag', 'vi. 落后于， 滞后于 n. 落后， 滞后', 6033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'automation', 'n. 自动', 6034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ambitious', 'adj. 有雄心的， 野心勃勃的', 6035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'towel', 'n. 毛巾', 6036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'academic', 'adj. 学院的；学术的 n. 学者， 大学教师， 学会会员', 6037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'function', 'vi. 起作用 n. 功能， 作用 <；函数', 6038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lap', 'n. 大腿， 膝盖', 6039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'representative', 'adj. 典型的， 有代表性的 n. 代表， 代理人', 6040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'longitude', 'n. 经度', 6041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pigeon', 'n. 鸽 <', 6042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comparison', 'n. 比较， 对比； 比喻， 比拟', 6043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hatch', 'vi. 孵， 孵出 vt. 策划， 图谋 n. 舱口， 小门', 6044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lest', 'conj. 唯恐， 免得', 6045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'successive', 'adj. 接连的， 连续的', 6046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obligation', 'n. 义务， 责任', 6047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ceremony', 'n. 典礼， 仪式；礼节， 礼仪', 6048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paperback', 'n. 简装本， 平装本', 6049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hawk', 'n. 鹰， 隼', 6050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'patriotic', 'adj. 爱国的', 6051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lavatory', 'n. 厕所， 盥洗室', 6052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exterior', 'adj. 外部的， 外面的 n. 外部', 6053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'troop', 'n. 群， 队 A <', 6054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shorthand', 'n. 速记', 6055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scenery', 'n. 风景；舞台布景 A', 6056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'levy', 'vt. 征收 n. 征税， 税款；征兵', 6057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intimidate', 'vt. 恐吓， 威胁； 胁迫', 6058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'effective', 'adj. 有效的， 生效的 <；给人深刻印象的； 显著的', 6059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'muscle', 'n. 肌肉； 体力', 6060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generous', 'adj. 宽宏大量的， 慷慨的', 6061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'possibility', 'n. 可能， 可能性； 可能的事； 希望', 6062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bachelor', 'n. 单身汉；学士', 6063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necklace', 'n. 项链', 6064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opening', 'adj. 开始的， 开幕的 n. 口子； 孔；开始， 开端；空缺', 6065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'probe', 'v. 探查， 穿刺；查究 < n. 探针； 探测器', 6066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'industrial', 'adj. 工业的； 产业的', 6067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quantitative', 'adj. 数量的， 定量的', 6068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stable', 'adj. 稳定的， 安定的 < n. 马厩， 马棚', 6069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pillow', 'n. 枕头', 6070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harness', 'vt. 治理； 利用 <', 6071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sketch', 'v. 概述， 简述；勾画； 写生； 素描； 绘略图 n. 略图， 草图；梗概， 大意；素描， 速写', 6072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'respond', 'vi. 回答， 答复；响应', 6073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maintenance', 'n. 维修， 保养；维持， 保持', 6074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incident', 'n. 事件； 事变', 6075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tub', 'n. 木盆， 澡盆', 6076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cluster', 'v. 群集， 丛生 n. 丛， 群， 串 <；星团 A', 6077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prey', 'vi. 猎取食物 n. 猎物， 捕获物；受害者', 6078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tug', 'v. 用力拖 n. 猛拉； 牵引 <；拖船', 6079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expedition', 'n. 远征， 探险', 6080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'absorb', 'vt. 吸收；吸引， 使专心；承受， 忍受', 6081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concern', 'vt. 涉及， 关系到；关心， 挂念 n. 关心， 挂念；关系', 6082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circulate', 'v. 循环， 流通；传播', 6083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rectify', 'vt. 纠正， 整顿 <', 6084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'integrity', 'n. 完整， 完全；正直， 诚实', 6085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refrain', 'vi. 抑制， 克制；戒除 n. 反复句， 叠句；副歌', 6086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pact', 'n. 协定， 条约， 公约', 6087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liable', 'adj. 有责任的， 有义务的；有…倾向的， 易于…的', 6088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merge', 'v. 合并， 并入； 吞没 A', 6089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'state', 'n. 状态， 情况；国， 州 vt. 陈述， 说明；规定', 6090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dock', 'n. 船坞， 码头', 6091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cargo', 'n. 船货， 货物', 6092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'element', 'n. 元素；组成部分', 6093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pace', 'vi. 踱步 n. 步， 步伐', 6094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'probable', 'adj. 很可能的； 大概的； 有希望的', 6095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exclaim', 'v. 呼喊， 惊叫； 大声说', 6096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ballet', 'n. 芭蕾舞； 芭蕾舞剧； 芭蕾舞团 <', 6097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'courtesy', 'n. 谦恭有礼；有礼貌的举止', 6098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'restraint', 'n. 抑制， 制止', 6099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cue', 'n. 提示； 暗示， 信号', 6100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stereotype', 'n. 陈规， 旧框框， 固定形式， 老套；铅版 vt. 成固定形象， 对…形成固定看法', 6101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enroll', 'v. 招收； 登记； 入学', 6102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entertainment', 'n. 招待， 款待；娱乐， 表演文娱节目', 6103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'document', 'n. 公文， 文件， 文献', 6104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cohesive', 'adj. 凝聚的；黏着的', 6105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dread', 'n. /', 6106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'battery', 'n. 电池；炮兵连， 排炮', 6107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'starve', 'v. 饿死， 挨饿 <', 6108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clay', 'n. 黏土， 泥土', 6109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'promote', 'vt. 促进， 增进 <；提升， 提拔；宣传； 助长', 6110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scenario', 'n. 情境 “；剧本', 6111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'humour', 'n. 幽默， 诙谐', 6112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divorce', 'vt. 离婚； 分离 n. 离婚； 分离', 6113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distribute', 'v. 分配； 分布； 配 <；散布', 6114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attach', 'vt. 缚上， 系上， 贴上；使依附， 使隶属， 使依恋 <', 6115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graphic', 'adj. 生动的， 形象的；绘画的； 文字的； 图表的 <', 6116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ankle', 'n. 踝', 6117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legislation', 'n. 法律， 法规；立法 <', 6118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clause', 'n. 条款；从句， 分句', 6119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quiz', 'n. 小型考试， 测验； 问答比赛', 6120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ingredient', 'n. 组成部分， 成分', 6121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thirst', 'n. 渴， 口渴；渴望， 热望', 6122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'participate', 'vi. 参与， 参加；分享， 分担', 6123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consolidate', 'v. 巩固， 加强', 6124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'librarian', 'n. 图书管理员', 6125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lottery', 'n. 彩票， 抽彩给奖法；碰运气的事 A', 6126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reporter', 'n. 记者， 报导者；报告人； 通讯员', 6127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shove', 'v. 乱推， 挤， 用力推；乱塞， 随意放 n. 猛推', 6128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'claw', 'v. 抓 n. 爪； 脚爪', 6129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torture', 'vt. 拷问， 拷打；折磨， 磨难 n. 拷问， 拷打；折磨， 痛苦', 6130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mistress', 'n. 女主人， 主妇；情妇， 情人 A', 6131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prayer', 'n. 祈祷， 祷告； 祷文', 6132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lyric', 'adj. 抒情的 n. 抒情诗；歌词', 6133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clap', 'vt. 拍手， 拍， 轻拍 n. 拍； 击掌声； 霹雳声', 6134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'purple', 'adj. 紫的； 紫红的 n. 紫色 <', 6135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quit', 'vt. 从离开， 退出； 辞职 <；停止， 放弃 <', 6136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'economical', 'adj. 经济的； 节约的', 6137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'polish', 'v. 磨光， 擦亮；使优美； 润饰 < n. 擦光剂， 上光蜡', 6138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cabinet', 'n. 橱柜；内阁', 6139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'optical', 'adj. 眼的， 视力的；光学的', 6140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fashion', 'n. 流行式样； 风尚， 风气；样子， 方式', 6141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insurance', 'n. 保险， 保险费， 保险业', 6142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'principle', 'n. 原理， 原则；主义， 信念', 6143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dazzle', 'vt. 使惊奇， 使倾倒；使眩目， 耀 n. 耀眼的光；令人眼花缭乱的东西', 6144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thigh', 'n. 大腿', 6145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lid', 'n. 盖， 盖子', 6146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tedious', 'adj. 乏味的， 单调的， 冗长的； 使人厌烦的', 6147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'source', 'n. 来源， 出处； 源', 6148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'participant', 'n. 参加者， 参与者', 6149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'domestic', 'adj. 家的， 家庭的 <；本国的；驯养的', 6150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'initiate', 'vt. 开始， 发动', 6151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glare', 'vi. 怒视， 瞪眼；闪耀， 闪光 n. 怒视， 瞪眼；闪耀， 闪光', 6152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compile', 'vt. 搜集； 汇编 <', 6153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bias', 'n. 偏见， 偏心， 偏袒 vt. 使有偏见， 偏心， 偏袒', 6154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fume', 'vi. 发怒；冒烟 n. 烟； 气； 汽', 6155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stability', 'n. 稳定， 安定', 6156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'budget', 'vi. 做预算 n. 预算', 6157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radiate', 'v. 放射， 辐射；散布， 传播', 6158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tension', 'n. 【物】张力； 拉力；紧张', 6159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chess', 'n. 棋', 6160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reflection', 'n. 映像， 倒影；反省， 沉思', 6161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'campus', 'n. 校园', 6162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ultimate', 'adj. 最后的， 最终的；根本的， 基本的', 6163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosecute', 'vt. 继续从事；对…提起公诉； 告发， 检举', 6164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verbal', 'adj. 用言辞的， 用文字的；口头的；动词的', 6165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'harassment', 'n. 骚扰， 扰乱； 烦恼， 烦乱', 6166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'district', 'n. 地区， 区域； 行政区', 6167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overall', 'adj. 全面的， 综合的 n. 工作服； 工装裤', 6168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assume', 'vt. 假装；假定， 设想；采取， 承担， 呈现 <', 6169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pepper', 'n. 胡椒粉， 胡椒；辣椒', 6170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'destiny', 'n. 命运；天数， 天命 <', 6171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'memory', 'n. 记忆， 回忆； 记忆力；存储', 6172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'concept', 'n. 概念， 观念； 思想', 6173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resistant', 'adj. 抵抗的， 有抵抗力的', 6174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'disaster', 'n. 灾难， 天灾', 6175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grocer', 'n. 食品商， 杂货商', 6176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enhance', 'vt. 提高， 增强 <', 6177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pail', 'n. 提桶', 6178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convention', 'n. 大会， 会议；惯例， 常规， 习俗；公约， 协定', 6179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'calcium', 'n. 钙 <', 6180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suspicion', 'n. 猜疑， 怀疑', 6181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'purchase', 'vt. 买， 购买 n. 购买的物品', 6182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'refusal', 'n. 拒绝， 回绝', 6183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bypass', 'n. 旁路， 迂回的旁道； 搭桥术； 旁通管', 6184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'silicon', 'n. 硅 <', 6185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fund', 'n. 专款， 基金； vt. 拨款； 资助', 6186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gravity', 'n. 重力， 引力；庄重； 严重', 6187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recipient', 'n. 接受者， 收受者', 6188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commonwealth', 'n. 共和国， 联邦， 共同体', 6189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'finance', 'n. 财政， 金融 vt. 为…提供资金', 6190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'studio', 'n. 画室；播音室； 制片厂', 6191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'incur', 'vt. 招致， 惹起； 遭受', 6192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'downward', 'adv. 向下， 往下 adj. 向下的', 6193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cabbage', 'n. 洋白菜， 卷心菜', 6194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'regulate', 'vt. 管制， 控制 <；调节， 校准；调整', 6195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'palm', 'n. 手掌； 掌状物；棕榈', 6196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complementary', 'adj. 补充的； 辅助的', 6197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'premise', 'n. 前提； 假设', 6198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'payment', 'n. 支付， 付款额  <', 6199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'controversial', 'adj. 引起争论的， 有争议的', 6200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attain', 'vt. 达到， 获得 <', 6201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gallery', 'n. 长廊， 画廊， 美术馆', 6202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tenant', 'n. 承租人； 房客； 佃户', 6203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hardware', 'n. 五金， 金属制品；硬件', 6204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plaintiff', 'n. 原告', 6205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deputy', 'adj. 副的； 代理的 n. 代理人， 代表', 6206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'warmth', 'n. 暖和， 温暖 A；热心， 热情', 6207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hostage', 'n. 人质', 6208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'priority', 'n. 先， 前；优先， 优先权', 6209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inlet', 'n. 水湾， 小湾；进口， 入口 A', 6210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'creative', 'adj. 有创造力的， 创造性的', 6211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'judicial', 'adj. 审判的， 司法的； 法庭的， 法官的；公正的， 明断的', 6212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'analog', 'n. 类似物； 模拟 A', 6213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shuttle', 'v. 穿梭般来回， 短程穿梭运送 n. 航天飞机；梭子；短程穿梭运行的飞机', 6214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'allocate', 'v. 分配， 分派； 把…拨给', 6215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'primary', 'adj. 最初的， 初级的；首要的， 主要的， 基本的', 6216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pant', 'vi. 气喘 n. 喘气', 6217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'log', 'n. 原木， 圆木；航海日志', 6218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enterprise', 'n. 事业； 企业单位；事业心， 进取心', 6219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solar', 'adj. 太阳的； 日光的 <', 6220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consume', 'vt. 消费， 消耗， 耗尽 <', 6221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formation', 'n. 形成； 构成', 6222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dome', 'n. 圆屋顶， 拱顶', 6223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fuse', 'v. 熔化， 熔合 n. 保险丝， 导火线， 引信', 6224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'premium', 'adj. 高级的， 优质的；售价高的 n. 保险金；额外费用， 加付款；奖赏； 赠品； 额外津贴', 6225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pretext', 'n. 借口， 托词', 6226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assure', 'vt. 使确信， 使放心；保证， 担保', 6227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solidarity', 'n. 团结， 一致', 6228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tumble', 'v. 摔倒；打滚， 翻腾 n. 摔跤， 跌倒', 6229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consult', 'vi. 与…商量， 商议 vt. 请教； 查阅', 6230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gracious', 'adj. 亲切的； 有礼的； 仁慈的', 6231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'merely', 'adv. 仅仅， 只不过', 6232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fuss', 'vi. 忙乱， 大惊小怪 n. 忙乱， 大惊小怪', 6233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'means', 'n. 方法， 手段', 6234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'survive', 'vi. 幸免于， 幸存 vt. 比…长命', 6235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'initial', 'adj. 最初的， 开头的；词首的 n. 首字母', 6236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hound', 'n. 猎犬 vt. 追逼； 烦扰， 纠缠', 6237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orphan', 'n. 孤儿', 6238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eternal', 'adj. 永久的， 永恒的 <', 6239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'barely', 'adv. 赤裸裸地， 无遮蔽地；仅仅， 勉强； 几乎没有', 6240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cling', 'vi. 粘住， 依附；坚持', 6241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'satire', 'n. 讽刺； 讽刺作品', 6242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prevalent', 'adj. 流行的， 普遍的', 6243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diabetes', 'n. 糖尿病； 多尿症', 6244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clip', 'vi. 钳， 夹住 vt. 剪， 修剪 n. 夹， 钳； 回形针', 6245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invaluable', 'adj. 非常宝贵的， 无价的 <', 6246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compact', 'adj. 紧密的， 结实的；简洁的；紧凑的 vt. 使紧密； 压缩', 6247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alliance', 'n. 结盟， 联盟；联姻', 6248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'doom', 'n. 厄运， 劫数 vt. 注定， 命定', 6249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irrigate', 'vt. 灌溉；冲洗', 6250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dam', 'n. 水坝， 水闸', 6251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'denote', 'vt. 表示， 意味着', 6252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bloom', 'vi. 开花 n. 花；开花', 6253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zone', 'n. 地区， 区域 vt. 分区， 划分地带', 6254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'majesty', 'n. 雄伟， 壮丽， 庄严', 6255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necessitate', 'vt. 需要， 成为必要', 6256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orthodox', 'adj. 传统的， 符合社会风俗的；正统的', 6257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'industrialise', 'vt. 使工业化', 6258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'combination', 'n. 结合， 联合， 合并 A；化合', 6259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obtain', 'vt. 获得， 得到 <', 6260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jewelry', 'n. 珠宝', 6261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statesman', 'n. 政治家， 国务活动家', 6262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curiosity', 'n. 好奇心； 求知欲；古董， 古玩', 6263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amiable', 'adj. 可爱的； 和蔼的， 亲切的', 6264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liter', 'n. 升', 6265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'format', 'n. 设计； 安排； 样式 vt. 安排版式 <；格式化', 6266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sacrifice', 'n. 牺牲； 献身；牺牲品， 祭品， 供物 vt. 献祭； 献出； 牺牲', 6267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'illegal', 'adj. 不合法的， 非法的', 6268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'formal', 'adj. 正式的；形式的', 6269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'congratulate', 'vt. 祝贺； 恭喜；自我庆幸', 6270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rainbow', 'n. 彩虹 A', 6271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loudspeaker', 'n. 扬声器， 扩音器', 6272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'correlate', 'v. 相关， 关联 n. 相关联的人', 6273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ample', 'adj. 充分的， 富裕的 <；宽敞的， 宽大的', 6274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'salesman', 'n. 售货员， 推销员', 6275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entertain', 'v. 招待， 款待 vt. 使娱乐； 使欢乐', 6276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ease', 'vt. 减轻， 缓和；使舒适， 使安心 n. 容易， 轻松；舒适， 悠闲', 6277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tent', 'n. 帐篷', 6278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'critical', 'adj. 批评的， 评论的；危急的， 紧要的；挑剔的', 6279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gasolene', 'n. 汽油', 6280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elsewhere', 'adv. 在别处， 向别处', 6281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radiant', 'adj. 容光焕发的， 喜形于色的；光芒四射的， 光辉灿烂的；辐射的', 6282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paddle', 'n. 桨 vt. 用桨划', 6283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'penetrate', 'v. 穿过， 渗入；看穿， 洞察', 6284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'principal', 'adj. 最重要的， 主要的 n. 负责人； 校长； 首长；资本， 本金', 6285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exceedingly', 'adv. 极端地， 非常', 6286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tend', 'vi. 趋向， 往往是 vt. 照料， 看护', 6287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specimen', 'n. 标本， 样本', 6288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exotic', 'adj. 由外国引进的； 外国风味的；奇异的， 异乎寻常的', 6289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relief', 'n. 减轻， 解除；援救； 救济', 6290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'boycott', 'n. /', 6291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'introduction', 'n. 介绍；传入， 引进；导言， 导论， 绪论', 6292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revenge', 'n. 报复， 复仇 vt. 替…报仇', 6293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'subscribe', 'vi. 订购， 订阅； 预订 <；赞成', 6294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distill', 'vt. 蒸馏； 用蒸馏法提取；吸取， 提炼', 6295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'therapy', 'n. 治疗， 理疗', 6296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'zoom', 'vi. 急速移动；急升， 猛涨 n. 嗡嗡声， 隆隆声', 6297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'velocity', 'n. 速度； 速率', 6298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fellowship', 'n. 伙伴关系； 友谊； 团体', 6299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'colleague', 'n. 同事， 同僚', 6300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'economics', 'n. 经济学； 经济情况', 6301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gratitude', 'n. 感激， 感谢', 6302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interfere', 'vi. 干涉， 干预；妨碍， 打扰', 6303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apartment', 'n. 房间， 套间；公寓', 6304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fitting', 'adj. 适当的， 恰当的 n. 装配， 安装', 6305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tolerate', 'vt. 容忍， 默许', 6306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stack', 'n. 堆， 一堆 vt. 堆积， 堆起', 6307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'siren', 'n. 警报声， 警报器 A', 6308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'underline', 'vt. 在…下画线；强调', 6309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'resent', 'vt. 对…表示愤恨， 怨恨', 6310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compassion', 'n. 同情， 怜悯', 6311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ambiguous', 'adj. 模棱两可的', 6312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parliament', 'n. 国会； 议会', 6313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crack', 'v. 破裂； 砸开；发出爆裂声 n. 裂纹， 裂缝， 缝隙；破裂声， 爆裂声', 6314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bind', 'vt. 捆； 包扎； 束缚', 6315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dew', 'n. 露水', 6316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'railway', 'n. 铁路 vt. 由铁道运输', 6317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cube', 'n. 立方形， 立方体；立方， 三次幂', 6318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crisp', 'adj. 脆的， 易碎的', 6319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'profile', 'n. 侧面；轮廓， 外形；人物简介', 6320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impact', 'n. 冲击， 碰撞；效果； 影响', 6321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mild', 'adj. 温暖的， 暖和的；温和的； 轻微的；味淡的', 6322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mill', 'n. 磨粉机； 磨坊；作坊； 工厂', 6323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'senior', 'adj. 年长的 <；资格老的； 地位较高的； 高级的 n. 毕业班学生', 6324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dose', 'n. 剂量； 一服， 一剂 vt. 服药', 6325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'census', 'n. 人口普查', 6326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'domain', 'n. 领域， 范围', 6327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adult', 'adj. 成年人的， 已成熟的 n. 成人 <', 6328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attitude', 'n. 态度， 看法；姿势', 6329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'average', 'adj. 平均的； 通常的， 一般的 v. 平均， 均分 A n. 平均', 6330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'influential', 'adj. 有影响的， 有权势的', 6331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'Bible', 'n. 圣经', 6332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transparent', 'adj. 透明的；显然的， 明显的', 6333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grasp', 'vt. 抓住， 抓紧；掌握， 领会 n. 抓住， 抓紧；掌握， 领会', 6334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'journal', 'n. 定期刊物， 杂志， 日报；日志， 日记', 6335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pave', 'vt. 铺砌， 铺', 6336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'composition', 'n. 作品， 作文， 乐曲； 写作， 作曲；结构， 组成， 成分', 6337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acquisition', 'n. 获得； 获得物', 6338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'volcano', 'n. 火山', 6339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'so-called', 'adj. 所谓的， 号称的', 6340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deadline', 'n. 最后期限', 6341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rigid', 'adj. 刚性的；刻板的， 严格的；严厉的， 严明的', 6342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grateful', 'adj. 感激的； 感谢的', 6343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advent', 'n. 到来， 来临， 出现', 6344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'medieval', 'adj. 中世纪的， 中古的', 6345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'operational', 'adj. 操作的， 运转的 <', 6346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'staff', 'n. 全体职工， 全体人员；杆， 棒；参谋部 vt. 配备工作人员', 6347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'involve', 'vt. 使某人卷入， 陷入； 连累；包含， 含有； 涉及', 6348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tanker', 'n. 油船', 6349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'complicated', 'adj. 错综复杂的； 麻烦的； 难解的', 6350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maximum', 'adj. 最大的； 最高的 n. 最大值； 极限', 6351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'masterpiece', 'n. 杰作， 名著', 6352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tolerant', 'adj. 容忍的， 宽容的', 6353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fragrant', 'adj. 香的', 6354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dialect', 'n. 方言', 6355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stocking', 'n. 长袜', 6356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emergency', 'n. 紧急情况， 突发事件； 非常时刻', 6357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dim', 'adj. 暗淡的； 模糊的', 6358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paralyze', 'vt. 使瘫痪； 使丧失作用', 6359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dip', 'vt. 浸， 蘸 n. 浸， 蘸； 洗澡 A', 6360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'faculty', 'n. 才能；系， 科， 院；全体教学人员', 6361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layoff', 'n. 解雇 <；失业工人', 6362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passport', 'n. 护照', 6363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'considerate', 'adj. 考虑周到的， 体谅的', 6364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clue', 'n. 线索， 暗示', 6365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legal', 'adj. 法律的； 法定的 <；合法的， 正当的', 6366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bracket', 'n. 括号', 6367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'midst', 'n. 中间， 当中', 6368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radius', 'n. 半径', 6369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'highway', 'n. 公路， 大路', 6370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'signal', 'v. 发信号， 用信号通知 n. 信号， 暗号', 6371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impair', 'vt. 损害， 损伤； 削弱； 减少', 6372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'parcel', 'v. 打包， 捆扎 n. 包裹， 邮包', 6373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'static', 'adj. 静态的； 静力的', 6374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exhaust', 'vt. 使筋疲力尽， 耗尽；抽完， 汲干 n. 排气装置； 废气', 6375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'soluble', 'adj. 可溶的', 6376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thereafter', 'adv. 此后， 以后', 6377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grape', 'n. 葡萄', 6378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strap', 'n. 带， 皮带 vt. 捆扎', 6379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conviction', 'n. 深信， 确信', 6380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'straw', 'n. 稻草， 麦秆；吸管', 6381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graph', 'n. 图表， 曲线图 A', 6382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'regarding', 'prep. 关于', 6383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feast', 'n. 节日；宴会', 6384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acceptance', 'n. 接受； 验收；承认， 认可', 6385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'petrol', 'n. 汽油', 6386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relativity', 'n. 相关；相对论', 6387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paradise', 'n. 天堂', 6388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tackle', 'n. 用具， 器械； 滑车 vt. 处理， 解决， 对付 <', 6389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distract', 'vt. 分散， 打扰；迷惑， 扰乱', 6390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occasion', 'n. 场合， 时节， 时刻；时机， 机会', 6391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loan', 'n. 贷款；暂借的东西 vt. 借出', 6392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'squeeze', 'vt. 压榨， 挤 < n. 榨取， 勒索', 6393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'virtual', 'adj. 实际上的， 事实上的； 虚的', 6394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'worthy', 'adj. 值得…的， 配得上…的；可尊敬的； 有价值的', 6395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expectation', 'n. 预期， 期望， 指望', 6396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'title', 'n. 书名； 标题；头衔， 称号', 6397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mist', 'n. 薄雾， 霭 A', 6398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'duration', 'n. 期间；持久， 持续时间', 6399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plantation', 'n. 种植园', 6400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ferry', 'n. 渡船 vt. 渡运', 6401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'doze', 'vi. 瞌睡； 假寐 < n. 瞌睡； 假寐', 6402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hemisphere', 'n. 半球', 6403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loaf', 'vi. 游荡， 闲逛 n. 一条面包', 6404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nuclear', 'adj. 核心的， 中心的；原子核的， 核能的 <', 6405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'applaud', 'v. 喝彩， 欢呼， 鼓掌 A', 6406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lunar', 'adj. 月的， 月亮的', 6407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'poetry', 'n. 诗歌； 诗集', 6408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prince', 'n. 王子； 亲王', 6409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'arrogant', 'adj. 傲慢的， 自大的', 6410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relax', 'v. 松弛， 放松； 休息', 6411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relay', 'vt. 中继， 转播；接力传递 n. 接替人员； 替班', 6412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'priest', 'n. 教士， 神父', 6413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'permission', 'n. 允许， 同意', 6414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grand', 'adj. 盛大的， 豪华的；重大的， 主要的', 6415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'permeate', 'vi. 扩散， 弥漫；渗透， 渗入', 6416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'schedule', 'n. 时间表， 进度表 vt. 安排， 预定', 6417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interpret', 'vi. 做口译 vt. 解释， 说明；了解， 认为；口译', 6418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'universe', 'n. 宇宙， 万物', 6419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inherit', 'vt. 继承', 6420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blanket', 'n. 毛毯， 毯子', 6421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grant', 'vt. 同意， 准予 <；给予， 授予 A n. 授予 A <', 6422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discount', 'n. 折扣 vt. 打折', 6423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fascinated', 'adj. 兴奋的， 着迷的', 6424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'convert', 'v. 变换， 转化', 6425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'construct', 'vt. 建造， 构造 <；创立 <；解释， 说明 n. 构想； 概念', 6426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'attempt', 'v. 尝试， 试图 n. 企图， 努力', 6427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relish', 'n. 〈喻〉滋味； 兴趣； 兴味， 爱好；调味品； 好味道， 美味 vt. 欣赏； 品尝', 6428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'division', 'n. 分， 分割；部门， 科， 处；除法', 6429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'navigation', 'n. 航海， 航空；导航， 领航', 6430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stale', 'adj. 变质的， 不新鲜的；陈旧的， 陈腐的', 6431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'balance', 'vt. 称； 平衡 n. 天平， 秤；平衡， 均衡 A <；差额， 结余， 余款', 6432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stalk', 'v. 悄悄地跟踪；高视阔步地走 A n. 茎， 梗， 柄', 6433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cigar', 'n. 雪茄烟', 6434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pitch', 'n. 沥青；掷 A vt. 用沥青覆盖；投掷， 扔 <', 6435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whereas', 'conj. 而， 却， 反之', 6436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feat', 'n. 功绩， 壮举', 6437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oriental', 'adj. 东方的', 6438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'torrent', 'n. 激流， 山洪', 6439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statue', 'n. 塑像， 雕像', 6440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'electrical', 'adj. 电的， 电学的 <', 6441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stall', 'v. 停转， 停止 n. 货摊；畜栏， 厩', 6442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'being', 'n. 生物；存在， 生存', 6443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'classification', 'n. 分类， 分级 <', 6444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'physicist', 'n. 物理学家', 6445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'menace', 'n. 威胁；危险的人 vt. 威胁', 6446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curse', 'n. /', 6447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'invalid', 'adj. 有病的； 伤残的；供病人用的 A；无效的； 作废的；无根据的， 站不住脚的 n. 病人， 病弱者； 伤残人 A', 6448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interval', 'n. 间隔， 间距；休息', 6449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'legitimate', 'adj. 合法的；正当的， 合理的 v. 合法', 6450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'baseball', 'n. 棒球', 6451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evaluate', 'vt. 估价， 评价； 求…的值', 6452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'status', 'n. 地位， 身份；情形， 状况', 6453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'upset', 'n. 翻倒； 混乱 vt. 扰乱， 使…心烦意乱；打翻， 推翻 <', 6454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curve', 'v. 弄弯， 成曲形 n. 曲线； 弯曲', 6455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dot', 'n. 点， 圆点 vt. 在…上打点', 6456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skim', 'v. 撇；掠过， 擦过；浏览， 略读', 6457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skip', 'v. 跳来跳去； 蹦蹦跳跳；跳跃； 跳绳；跳过， 略过， 漏过 n. 跳， 蹦跳', 6458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scattered', 'adj. 离散的， 分散的', 6459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fertiliser', 'n. 肥料', 6460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stream', 'vi. 流出， 涌 n. 小河， 溪流；流， 一股， 一串', 6461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'laundry', 'n. 洗衣房  <；待洗衣物， 所洗衣物；洗熨 <', 6462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recur', 'vi. 再发生， 重现；重新提起', 6463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'herald', 'n. 预告， 先兆；传令官 A < vt. 预示…的来临', 6464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coalition', 'n. 结合体， 同盟；结合， 联合', 6465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accumulate', 'vt. 积累， 积蓄； 堆积', 6466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dwarf', 'adj. 矮小的； 发育不全的 n. 矮子， 侏儒 vt. 使显得矮小', 6467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crime', 'n. 罪行， 犯罪', 6468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brim', 'n. 边缘； 帽檐', 6469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leisure', 'n. 空闲， 闲暇；悠闲， 安逸 A', 6470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'surround', 'vt. 包围， 环绕 A', 6471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pavement', 'n. 人行道', 6472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mat', 'n. 席子； 垫子', 6473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assimilate', 'v. 经消化而吸收 <；同化', 6474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pilgrim', 'n. 朝圣者， 香客', 6475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'addict', 'n. 有瘾的人； 入迷的人 vt. 使成瘾， 使入迷', 6476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'marvellous', 'adj. 令人惊奇的； 奇迹般的； 〈口〉妙极的', 6477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aluminium', 'n. 铝', 6478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comparable', 'adj. 可比较的， 比得上的 <', 6479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'discreet', 'adj. 谨慎的， 慎重的', 6480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'opera', 'n. 歌剧', 6481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'presumably', 'adv. 推测起来， 大概', 6482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bait', 'n. 鱼饵， 诱饵 vt. 装饵于', 6483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bonus', 'n. 奖金； 红利', 6484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recognition', 'n. 认出， 辨认；承认 A', 6485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bail', 'n. 保释 vt. 保释 <；帮助脱离困境<', 6486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aisle', 'n. 过道， 通道', 6487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revenue', 'n. 收入； 财政收入， 税收', 6488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strip', 'vt. 剥， 剥去 n. 窄条， 带状物', 6489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monopoly', 'n. 垄断， 专卖', 6490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continuous', 'adj. 连续的， 持续的', 6491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grain', 'n. 谷物， 谷类； 粮食；颗粒， 细粒', 6492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'residence', 'n. 住处， 住宅', 6493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'credit', 'v. 相信， 信任 n. 信用; 信任；信用贷款， 赊欠；名誉， 名望； 光荣； 功劳；学分', 6494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maid', 'n. 少女； 女仆', 6495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oxygen', 'n. 氧， 氧气 <', 6496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intensive', 'adj. 加强的； 集中的； 深入细致的 <', 6497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alter', 'v. 改变， 变更', 6498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'combine', 'v. 结合， 联合； 化合', 6499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brook', 'n. 小河， 溪', 6500);
