INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'objective', 'adj. 客观的；目标的；宾格的 n. 目的；目标；[光] 物镜；宾格', 3001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coerce', 'v. 强制，迫使', 3002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'humility', 'n. 谦卑，谦逊', 3003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ammonia', 'n. [无化] 氨，阿摩尼亚', 3004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exhaustive', 'adj. 详尽的；彻底的；消耗的', 3005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misgiving', 'n. 担忧；疑虑；不安 v. 担忧；使…疑虑；害怕（misgive的ing形式）', 3006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intransigent', 'adj. 不妥协的；不让步的 n. 不妥协的人', 3007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'banal', 'adj. 陈腐的；平庸的；老一套的 n. (Banal)人名；(法、意)巴纳尔', 3008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'comparison', 'n. 比较；对照；比喻；比较关系', 3009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'federate', 'adj. 同盟的；联邦制度下的；联合的 v. 使结成同盟；使结成联邦', 3010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'statement', 'n. 声明；陈述，叙述；报表，清单', 3011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unassuming', 'adj. 谦逊的；不装腔作势的；不出风头的', 3012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denominate', 'v. 为…命名；把…称作… adj. 有特定名称的', 3013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extemporaneous', 'adj. 即席的，临时的；无准备的；不用讲稿的；善于即席讲话的', 3014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pique', 'v. 刺激；伤害…自尊心；激怒 n. 生气；愠怒；呕气', 3015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agglomerate', 'adj. 凝聚的；成团的，结块的 n. 团块；[岩] 集块岩；附聚物 v. 使结块；使成团', 3016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aural', 'adj. 听觉的；耳的；气味的；先兆的 n. (Aural)人名；(西)奥拉尔', 3017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'omniscient', 'adj. 全知的；无所不知的 n. 上帝；无所不知者', 3018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'captivate', 'v. 迷住，迷惑', 3019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seclude', 'v. 使隔离，使隔绝', 3020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plummet', 'n. [测] 铅锤，坠子 v. 垂直落下；（价格、水平等）骤然下跌', 3021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accomplish', 'v. 完成；实现；达到', 3022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'earnest', 'adj. 认真的，热心的；重要的 n. 认真；定金；诚挚', 3023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'projection', 'n. 投射；规划；突出；发射；推测', 3024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'circumscribe', 'v. 外切，外接；限制；在…周围画线', 3025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vitalize', 'v. 赋予…生命；激发；使有生气', 3026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disengage', 'v. 使脱离；解开；解除', 3027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'symphony', 'n. 交响乐；谐声，和声', 3028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'primp', 'v. 精心打扮；装饰', 3029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'network', 'n. 网络；广播网；网状物', 3030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'naval', 'adj. 海军的；军舰的 n. (Naval)人名；(西、德、印)纳瓦尔', 3031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ordinate', 'n. [数] 纵坐标', 3032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rudimentary', 'adj. 基本的；初步的；退化的；残遗的；未发展的', 3033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accessible', 'adj. 易接近的；可进入的；可理解的', 3034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'powerless', 'adj. 无力的；[劳经] 无能力的，无权的', 3035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vegetate', 'v. 过单调呆板的生活', 3036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undercharge', 'v. 充电不足；索价低于常价；弹药装填不足 n. 充电不足；低的索价；填不够量的火药', 3037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preoccupy', 'v. 迷住；使全神贯注', 3038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'avert', 'v. 避免，防止；转移', 3039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denigrate', 'v. 诋毁；使变黑；玷污', 3040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perfunctory', 'adj. 敷衍的；马虎的；得过且过的', 3041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sophistical', 'adj. 诡辩的；强词夺理的；诡辩法的', 3042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'posterior', 'adj. 其次的；较后的 n. 后部；臀部', 3043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fervor', 'n. 热情；热烈；热心；炽热', 3044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tundra', 'n. [生态] 苔原；[地理] 冻原；冻土地带', 3045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'solvent', 'adj. 有偿付能力的；有溶解力的 n. 溶剂；解决方法', 3046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epitome', 'n. 缩影；摘要；象征', 3047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blemish', 'n. 瑕疵；污点；缺点 v. 玷污；损害；弄脏', 3048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrospect', 'n. 回顾，追溯 v. 回顾，追溯；回想', 3049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contort', 'v. 扭曲；曲解', 3050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'phenomenon', 'n. 现象；奇迹；杰出的人才', 3051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rife', 'adj. 普遍的；流行的；盛传的 n. (Rife)人名；(西)里费；(英)赖夫', 3052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'classify', 'v. 分类；分等', 3053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'microorganism', 'n. [微] 微生物；微小动植物', 3054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anticipate', 'v. 预期，期望；占先，抢先；提前使用', 3055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'languid', 'adj. 倦怠的；呆滞的；软弱无力的', 3056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wanton', 'adj. 嬉戏的；繁茂的；荒唐的；无节制的；放纵的 n. 荡妇；水性杨花的女人 v. 放肆；嬉戏；闲荡', 3057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'connotation', 'n. 内涵；含蓄；暗示，隐含意义；储蓄的东西（词、语等）', 3058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resistance', 'n. 阻力；电阻；抵抗；反抗；抵抗力', 3059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adherent', 'n. 信徒；追随者 adj. 附着的；粘着的', 3060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bereft', 'adj. 丧失的；被剥夺的；失去亲人的 v. 失去…的（bereave的过去式）', 3061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flair', 'n. 天资；天分；资质；鉴别力', 3062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cynical', 'adj. 愤世嫉俗的；冷嘲的', 3063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'instinct', 'n. 本能，直觉；天性 adj. 充满着的', 3064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tolerable', 'adj. 可以的；可容忍的', 3065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'presumptuous', 'adj. 专横的；放肆的；冒昧的', 3066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'undermine', 'v. 破坏，渐渐破坏；挖掘地基', 3067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pentagon', 'n. 五角形', 3068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'voluptuous', 'adj. 撩人的；骄奢淫逸的；沉溺酒色的', 3069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'palliate', 'v. 减轻；掩饰；辩解', 3070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'abut', 'v. 邻接；毗邻；紧靠 n. (Abut)人名；(英、土)阿布特', 3071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intercede', 'v. 调解，调停；求情，说项', 3072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'academician', 'n. 院士；大学生；学会会员；大学教师', 3073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'theorize', 'v. 建立理论或学说；推理', 3074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glacial', 'adj. 冰的；冰冷的；冰河时代的', 3075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dielectric', 'adj. 非传导性的；诱电性的 n. 电介质；绝缘体', 3076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'face', 'n. 脸；表面；面子；面容；外观；威信 v. 向；朝', 3077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dilettante', 'n. 业余爱好者；一知半解者 adj. 浅薄的；业余艺术爱好的 vi. （在艺术、科学等方面）浅尝辄止', 3078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'progression', 'n. 前进；连续', 3079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outlandish', 'adj. 古怪的；奇异的；异国风格的；偏僻的', 3080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'scanty', 'adj. 缺乏的；吝啬的；仅有的；稀疏的', 3081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'monogamy', 'n. 一夫一妻制；[动] 单配偶，[动] 单配性', 3082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ramble', 'n. 漫步；漫游；随笔 v. 漫步于…', 3083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prohibit', 'v. 阻止，禁止', 3084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'desiccate', 'v. 变干', 3085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'defer', 'v. 推迟；延期；服从 n. (Defer)人名；(法)德费', 3086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lapse', 'n. (一时的) 走神，判断错误', 3087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'motor', 'n. 发动机，马达；汽车 adj. 汽车的；机动的 v. 乘汽车', 3088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'possess', 'v. 控制；使掌握；持有；迷住；拥有，具备', 3089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'itinerary', 'n. 旅程，路线； 旅行日程 adj. 旅程的； 巡回的，流动的', 3090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'underlie', 'v. 成为……的基础；位于……之下', 3091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equivocal', 'adj. 模棱两可的；可疑的', 3092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belle', 'n. 美女', 3093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ovum', 'n. [细胞][组织] 卵；卵子；卵形装饰', 3094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'projectile', 'adj. 抛射的；抛掷的；供抛射用的；（触角等）能伸出的 n. 射弹；抛射体；自动推进武器', 3095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'guzzle', 'v. 狂饮；暴食 n. 狂饮；豪饮作乐', 3096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resent', 'v. 怨恨；愤恨；厌恶', 3097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hail', 'n. 冰雹；致敬；招呼；一阵 v. 致敬；招呼；向欢呼；猛发；使像下雹样落下（过去式hailed，过去分词hailed，现在分词hailing，第三人称单数hails） int. 万岁；欢迎', 3098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encore', 'n. 再演唱的要求；经要求而再唱 v. 要求再演或唱 int. 再来一个', 3099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inaccessible', 'adj. 难达到的；难接近的；难见到的', 3100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'itinerate', 'v. 巡回；巡回传教', 3101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'plausible', 'adj. 貌似可信的，花言巧语的；貌似真实的，貌似有理的', 3102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'phosphate', 'n. 磷酸盐；皮膜化成', 3103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cull', 'v. 精选；采集（鲜花等）；剔除 n. 剔出来杀掉的动物；拣出的等外品', 3104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tumor', 'n. 肿瘤；肿块；赘生物', 3105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'factor', 'n. 因素；要素；[物] 因数；代理人 v. 做代理商', 3106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'telescope', 'v. 压缩；使套叠 n. 望远镜；缩叠式旅行袋', 3107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paroxysm', 'n. （疾病周期性）发作；突发', 3108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invalidate', 'v. 使无效；使无价值', 3109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affinity', 'n. 密切关系；吸引力；姻亲关系；类同', 3110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'angle', 'v. 钓鱼；谋取 n. 角度，角，方面', 3111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vulgar', 'adj. 粗俗的；通俗的；本土的 n. 平民，百姓', 3112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'requite', 'v. 报答，回报；酬谢', 3113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lung', 'n. 肺；呼吸器', 3114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intervene', 'v. 干涉；调停；插入', 3115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preference', 'n. 偏爱，倾向；优先权', 3116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'saturation', 'n. 饱和；色饱和度；浸透；磁化饱和', 3117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'producer', 'n. 制作人，制片人；生产者；发生器', 3118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'reclaim', 'v. 开拓；回收再利用；改造某人，使某人悔改 n. 改造，感化；再生胶', 3119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'irony', 'n. 讽刺；反语；具有讽刺意味的事 adj. 铁的；似铁的', 3120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unctuous', 'adj. 油质的；虚情假意的；油腔滑调的', 3121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'competitor', 'n. 竞争者，对手', 3122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'nomad', 'n. 游牧民；流浪者 adj. 游牧的；流浪的', 3123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alkaloid', 'n. [有化] 生物碱；植物碱基', 3124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facet', 'n. 面；方面；小平面 vt. 在…上琢面', 3125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'travesty', 'n. 歪曲；滑稽作品；拙劣的模仿作品 v. 歪曲；滑稽地模仿', 3126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resurrection', 'n. 复活；恢复；复兴', 3127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seize', 'v. 抓住；夺取；理解；逮捕', 3128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'surrender', 'v. 使投降；放弃；交出；听任 n. 投降；放弃；交出；屈服', 3129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'oblivion', 'n. 遗忘；湮没；赦免', 3130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'penitent', 'adj. 忏悔的，悔过的 n. 悔罪者，忏悔者', 3131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'marsh', 'n. 沼泽；湿地 adj. 沼泽的；生长在沼泽地的', 3132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'candidate', 'n. 候选人，候补者；应试者', 3133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'protrude', 'v. 使突出，使伸出', 3134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alley', 'n. 小巷；小路；小径', 3135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mendicant', 'adj. 行乞的；托钵修道会的 n. 乞丐；托钵僧', 3136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transistor', 'n. 晶体管（收音机）', 3137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'validity', 'n. [计] 有效性；正确；正确性', 3138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'provident', 'adj. 节俭的；有先见之明的；顾及未来的', 3139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interpolate', 'v. 篡改；插入新语句', 3140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fermentation', 'n. 发酵', 3141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'arboretum', 'n. 植物园；（供科研等的）树木园', 3142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pamphlet', 'n. 小册子', 3143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'excursion', 'n. 偏移；远足；短程旅行；离题；游览，游览团', 3144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demonstrate', 'v. 证明；展示；论证', 3145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inherent', 'adj. 固有的；内在的；与生俱来的，遗传的', 3146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contour', 'n. 轮廓；等高线；周线；电路；概要 v. 画轮廓；画等高线', 3147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prologue', 'n. 开场白；序言 vt. 加上…前言；为…作序', 3148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'transient', 'adj. 短暂的；路过的 n. 瞬变现象；过往旅客；候鸟', 3149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'billion', 'n. 十亿；大量 num. 十亿 adj. 十亿的', 3150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enlist', 'v. 支持；从军；应募；赞助', 3151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precocious', 'adj. 早熟的；过早发育的', 3152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'licit', 'adj. 正当的，合法的', 3153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extrovert', 'n. 外向；外倾者；性格外向者（等于extravert）', 3154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'linguist', 'n. 语言学家', 3155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glacier', 'n. 冰河，冰川', 3156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emigrate', 'v. 移居；移居外国', 3157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'explosion', 'n. 爆炸；爆发；激增', 3158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vicious', 'adj. 恶毒的；恶意的；堕落的；有错误的；品性不端的；剧烈的 n. (Vicious)人名；(英)维舍斯', 3159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'passive', 'adj. 被动的，消极的；被动语态的 n. 被动语态', 3160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obstreperous', 'adj. 吵闹的，喧嚣的；难驾驭的', 3161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forfeit', 'n. 罚金；没收物；丧失的东西 adj. 因受罚而丧失的；被没收的 v. （因犯罪、失职、违约等）丧失（权利、名誉、生命等）', 3162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embellish', 'v. 修饰；装饰；润色', 3163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rancor', 'n. 深仇；怨恨；敌意', 3164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blockade', 'v. 封锁 n. 阻塞', 3165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gaucherie', 'n. 笨拙；无礼', 3166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quorum', 'n. 法定人数', 3167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'onerous', 'adj. 繁重的；麻烦的；负有义务的；负有法律责任的', 3168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extraneous', 'adj. 外来的；没有关联的；来自体外的', 3169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tube', 'n. 管；电子管；隧道；电视机 v. 使成管状；把…装管；用管输送', 3170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prosecutor', 'n. 检察官；公诉人；[法] 起诉人；实行者', 3171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'acoustics', 'n. 声学；音响效果，音质', 3172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'compulsion', 'n. 强制；强迫；强制力', 3173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inclination', 'n. 倾向，爱好；斜坡', 3174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exotic', 'adj. 异国的；外来的；异国情调的', 3175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appreciable', 'adj. 可感知的；可评估的；相当可观的', 3176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'photography', 'n. 摄影；摄影术', 3177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impulse', 'n. 冲动；[电子] 脉冲；刺激；神经冲动；推动力 vt. 推动', 3178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'facility', 'n. 设施；设备；容易；灵巧', 3179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'equidistant', 'adj. 等距的；距离相等的', 3180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rail', 'n. 铁轨；扶手；横杆；围栏 v. 抱怨；责骂', 3181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'definite', 'adj. 一定的；确切的', 3182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rile', 'v. 激怒；搅浑；惹怒 n. (Rile)人名；(塞)里莱', 3183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stagnant', 'adj. 停滞的；不景气的；污浊的；迟钝的', 3184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'baleful', 'adj. 恶意的；有害的', 3185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'denude', 'v. 剥夺；使裸露', 3186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boorish', 'adj. 粗野的；粗鲁的；粗鄙的；笨拙的；乡土气的', 3187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'attenuate', 'adj. 减弱的；稀薄的；细小的 v. 使减弱；使纤细', 3188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quixotic', 'adj. 唐吉诃德式的；狂想家的；愚侠的', 3189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vinery', 'n. 葡萄园，葡萄温室', 3190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perfidious', 'adj. 背信弃义的；不忠的', 3191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impinge', 'v. 撞击；侵犯', 3192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'germinate', 'v. 使发芽；使生长', 3193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vaudeville', 'n. 杂耍；轻歌舞剧；歌舞杂耍表演', 3194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'glutinous', 'adj. 粘的；粘性的；胶状的', 3195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'supple', 'adj. 柔软的；灵活的；顺从的；易弯曲的；逢迎的 v. 使柔软；使顺从 n. (Supple)人名；(意、西)苏普莱', 3196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'desiccant', 'adj. 去湿的，使干燥的 n. [助剂] 干燥剂', 3197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'edify', 'v. 熏陶；启发；教诲', 3198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sedition', 'n. 暴动；煽动性的言论或行为；妨害治安', 3199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invoke', 'v. 调用；祈求；引起；恳求', 3200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belie', 'v. 掩饰；与…不符；使失望；证明…虚假错误', 3201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'commodious', 'adj. 宽敞的；方便的', 3202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unparalleled', 'adj. 无比的；无双的；空前未有的', 3203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subliminal', 'adj. [生理] 阈下的；潜在意识的；微小得难以察觉的 n. 潜意识；阈下意识', 3204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tension', 'n. 张力，拉力；紧张，不安；电压 vt. 使紧张；使拉紧', 3205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'epitomize', 'v. 摘要；概括；成为…的缩影', 3206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'quarterly', 'adj. 季度的，按季度的；一年四次的 adv. 按季度，[农] 一季一次地；纵横四分地 n. 季刊', 3207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flask', 'n. [分化] 烧瓶；长颈瓶，细颈瓶；酒瓶，携带瓶', 3208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sober', 'adj. 冷静的，清醒的；未醉的 v. 使严肃；使醒酒，使清醒 n. (Sober)人名；(英)索伯', 3209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'specious', 'adj. 似是而非的；外表美观的；华而不实的；徒有其表的', 3210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exultant', 'adj. 非常高兴的；欢跃的；狂喜的；欢欣鼓舞的', 3211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inclement', 'adj. 险恶的；气候严酷的；狂风暴雨的', 3212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antipodes', 'n. 地球上处于正相对应的两个地区，尤指（与欧洲形成对跖地的）澳大拉西亚', 3213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'belay', 'v. 把缆绳拴在系索栓上 n. (Belay)人名；(法)贝莱', 3214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'declaim', 'v. 慷慨陈词；演讲；朗读', 3215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jocose', 'adj. 诙谐的；开玩笑的', 3216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'possessive', 'adj. 占有的；所有的；所有格的；占有欲强的 n. 所有格', 3217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satiate', 'v. 充分满足；使厌腻 adj. 饱足的；厌腻的', 3218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misbehave', 'v. 作弊；行为不礼貌', 3219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tricycle', 'n. [车辆] 三轮车', 3220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anatomy', 'n. 解剖；解剖学；剖析；骨骼', 3221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'xenophobe', 'n. 仇外；害怕生人者；畏惧和憎恨外国人的人', 3222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'devastate', 'v. 毁灭；毁坏', 3223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'agile', 'adj. 敏捷的；机敏的；活泼的', 3224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sedative', 'n. [药] 镇静剂；能使安静的东西；止痛药 adj. 使镇静的；使安静的', 3225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vie', 'v. 争；竞争 n. (Vie)人名；(英)维', 3226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'legislator', 'n. 立法者', 3227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satire', 'n. 讽刺；讽刺文学，讽刺作品', 3228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'respondent', 'adj. 回答的；应答的 n. [法] 被告；应答者', 3229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pediatrics', 'n. 小儿科', 3230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'satirize', 'v. 讽刺；挖苦', 3231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exhausted', 'adj. 疲惫的；耗尽的 v. 耗尽；用尽；使…精疲力尽（exhaust的过去式）', 3232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contempt', 'n. 轻视，蔑视；耻辱', 3233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hideous', 'adj. 可怕的；丑恶的', 3234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'guilty', 'adj. 有罪的；内疚的', 3235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obtuse', 'adj. 迟钝的；圆头的；不锋利的', 3236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anachronistic', 'adj. 时代错误的', 3237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'table', 'n. 桌子；表格；平地层 v. 制表；搁置；嵌合 adj. 桌子的', 3238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prescript', 'adj. 规定的；有时效的 n. 规定；命令', 3239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'imbibe', 'v. 吸收，接受；喝；吸入', 3240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'adduce', 'v. 举出；引证', 3241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boiling', 'adj. 沸腾的；激昂的 n. 沸腾；煮沸；起泡 adv. 沸腾', 3242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unwitting', 'adj. 不知情的；不知不觉的，无意的 v. 使精神错乱；使丧失智能（unwit的ing形式）', 3243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diffident', 'adj. 羞怯的；缺乏自信的；谦虚谨慎的', 3244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'motto', 'n. 座右铭，格言；箴言', 3245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cube', 'n. 立方；立方体；骰子 v. 使成立方形；使自乘二次；量…的体积', 3246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frenetic', 'adj. 狂热的；发狂的 n. 疯子；狂人', 3247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'benefactor', 'n. 恩人；捐助者；施主', 3248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'inkling', 'n. 暗示；略知；模糊概念 v. 暗示 （inkle的ing形式）；略知；低声说出', 3249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'matriarchy', 'n. 母权制；女家长制；女族长制；母系氏族', 3250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impasse', 'n. 僵局；死路', 3251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'query', 'n. 疑问，质问；疑问号 ；[计] 查询 v. 询问；对……表示疑问', 3252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'expurgate', 'v. 删除，删去', 3253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enamor', 'v. 使迷恋，使倾心', 3254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dual', 'adj. 双的；双重的 n. 双数；双数词', 3255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fanatic', 'n. 狂热入迷者；盲信者；盲信 adj. 狂热的；盲信的', 3256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'particle', 'n. 颗粒；[物] 质点；极小量；小品词', 3257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sapid', 'adj. 有滋味的；有趣的', 3258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'repellent', 'adj. 排斥的；防水的；弹回的；令人讨厌的 n. 防护剂；防水布；排斥力', 3259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'feudal', 'adj. 封建制度的；领地的；世仇的', 3260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'velocity', 'n. 【物】速度', 3261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fake', 'n. 假货；骗子；假动作 v. 捏造；假装…的样子 adj. 伪造的', 3262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'simplify', 'v. 简化；使单纯；使简易', 3263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recur', 'v. 复发；重现；采用；再来；循环；递归', 3264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crestfallen', 'adj. 垂头丧气的，气馁的', 3265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'algebra', 'n. 代数学', 3266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'autarchy', 'n. 专制，独裁；专制国家', 3267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gigantic', 'adj. 巨大的，庞大的', 3268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'desert', 'v. 遗弃；放弃；逃跑 n. 沙漠；荒原；应得的赏罚 adj. 沙漠的；荒凉的；不毛的', 3269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cantonment', 'n. 宿营地；兵营', 3270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'decagon', 'n. [数] 十角形；[数] 十边形', 3271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'caption', 'n. 标题；字幕；说明；逮捕 v. 加上说明；加上标题', 3272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unbiased', 'adj. 公正的；无偏见的', 3273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'crystal', 'n. 结晶，晶体；水晶；水晶饰品 adj. 水晶的；透明的，清澈的', 3274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'demolish', 'v. 拆除；破坏；毁坏；推翻；驳倒', 3275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prattle', 'v. 闲聊；胡说；小孩般说话 n. 无聊话；咿咿呀呀声', 3276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'effrontery', 'n. 厚颜无耻', 3277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cardiac', 'n. 强心剂；强胃剂 adj. 心脏的；心脏病的；贲门的', 3278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'afterthought', 'n. 事后的想法；后来添加的东西', 3279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vainglorious', 'adj. 虚荣心强的；非常自负的', 3280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vermin', 'n. 害虫；寄生虫；歹徒', 3281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disburse', 'v. 支付；支出', 3282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'advertiser', 'n. 广告客户；刊登广告的人', 3283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diplomat', 'n. 外交家，外交官；有外交手腕的人；处事圆滑机敏的人', 3284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'affable', 'adj. 和蔼可亲的；友善的', 3285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'genre', 'n. 类型；种类；体裁；样式；流派；风俗画 adj. 风俗画的；以日常情景为主题的', 3286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sector', 'n. 部门；扇形，扇区；象限仪；函数尺 vt. 把…分成扇形', 3287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'virile', 'adj. 男性的；有男子气概的；刚健的 n. (Virile)人名；(意)维里莱', 3288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cortex', 'n. [解剖] 皮质；树皮；果皮', 3289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ascendant', 'n. 优势；运星；支配地位 adj. 上升的；优越的', 3290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pretension', 'n. 自负；要求；主张；借口；骄傲', 3291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'anthropology', 'n. 人类学', 3292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preclude', 'v. 排除；妨碍；阻止', 3293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'discomfit', 'v. 挫败；扰乱，破坏；使…为难；使…破灭', 3294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lasting', 'adj. 持久的；永恒的 n. [纺] 厚实斜纹织物 v. 持续；维持（last的ing形式）', 3295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interposition', 'n. 干涉，介入；插入，放入', 3296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'justification', 'n. 理由；辩护；认为有理，认为正当；释罪', 3297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appertain', 'v. 属于；和……有关，有关系', 3298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stymie', 'v. 从中作梗，阻挠；妨碍 n. 妨碍球', 3299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'audition', 'n. 听力，听觉；试听 v. 试听；试音', 3300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'misfortune', 'n. 不幸；灾祸，灾难', 3301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'characterize', 'v. 描绘…的特性；具有…的特征', 3302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'positive', 'adj. 积极的；[数] 正的，[医][化学] 阳性的；确定的，肯定的；实际的，真实的；绝对的 n. 正数；[摄] 正片', 3303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'work', 'n. 工作；[物] 功；产品；操作；职业；行为；事业；工厂；著作；文学、音乐或艺术作品 v. 使工作；操作；经营；使缓慢前进', 3304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recrudescent', 'adj. 复发的，再发作的', 3305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'celebrated', 'adj. 著名的；有名望的 v. 庆祝（celebrate的过去式和过去分词）', 3306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dialect', 'n. 方言，土话；同源语；行话；个人用语特征 adj. 方言的', 3307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'global', 'adj. 全球的；总体的；球形的', 3308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'platitude', 'n. 陈词滥调；平凡；陈腐', 3309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'restrict', 'v. 限制；约束；限定', 3310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'annihilate', 'v. 歼灭；战胜；废止', 3311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'landmark', 'n. [航]陆标；地标；界标；里程碑；纪念碑；地界标；划时代的事 adj. 有重大意义或影响的', 3312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'appall', 'v. 使胆寒；使惊骇', 3313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'righteous', 'adj. 正义的；正直的；公正的', 3314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'prostrate', 'adj. 俯卧的；拜倒的；降伏的；沮丧的 v. 使…屈服；将…弄倒；使…俯伏', 3315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'promote', 'v. 促进；提升；推销；发扬', 3316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'torturous', 'adj. 折磨人的，痛苦的', 3317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conditional', 'adj. 有条件的；假定的 n. 条件句；条件语', 3318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cryptic', 'adj. 神秘的，含义模糊的；[动] 隐藏的', 3319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'racy', 'adj. 生动的；保持原味的；适于赛跑的；猥亵的 n. (Racy)人名；(葡、阿拉伯)拉西', 3320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'encompass', 'v. 包含；包围，环绕；完成', 3321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'brandish', 'v. 挥舞；炫耀 n. 挥舞', 3322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'pulley', 'n. 滑轮；皮带轮；滑车 vt. 用滑轮升起', 3323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'herbivore', 'n. [动] 食草动物', 3324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'enfranchise', 'v. 给予选举权；给予自治权；解放，释放', 3325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'malfeasance', 'n. 渎职，违法行为；不正当，坏事', 3326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'botany', 'n. 植物学；地区植物总称', 3327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precedence', 'n. 优先；居先', 3328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'alloy', 'v. 使成合金；使减低成色 n. 合金', 3329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cursory', 'adj. 粗略的；草率的；匆忙的', 3330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'forebode', 'v. 预示；预感；预兆', 3331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allot', 'v. 分配；拨给；分派 n. (Allot)人名；(英)阿洛特；(西)阿略特；(法)阿洛', 3332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'serum', 'n. 血清；浆液；免疫血清；乳清；树液', 3333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'congenial', 'adj. 意气相投的；性格相似的；适意的；一致的', 3334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'flame', 'n. 火焰；热情；光辉 v. 焚烧；泛红', 3335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minute', 'n. 分，分钟；片刻，一会儿；备忘录，笔记；会议记录 v. 将…记录下来 adj. 微小的，详细的 [maɪˈnjuːt; US -ˈnuːt; maɪˋnut]', 3336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'paralyze', 'v. 使麻痹；使瘫痪', 3337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'protuberate', 'v. 伸出的', 3338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'graph', 'n. 图表；曲线图 v. 用曲线图表示', 3339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'outdo', 'v. 超过；胜过', 3340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dipper', 'n. 长柄勺；浸染工；[鸟] 河鸟', 3341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retroactive', 'adj. 追溯的；有追溯效力的；反动的', 3342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'defraud', 'v. 欺骗', 3343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'wintry', 'adj. 寒冷的，冬天的；冷淡的', 3344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cupidity', 'n. 贪心，贪婪', 3345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrench', 'v. 删除；减少；紧缩开支', 3346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'foreshadow', 'v. 预示；成为…的前兆 n. 预兆', 3347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'antitoxin', 'n. 抗毒素；抗毒素血清', 3348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retaliate', 'v. 报复；回敬', 3349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contentment', 'n. 满足；满意', 3350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'moderate', 'adj. 稳健的，温和的；适度的，中等的；有节制的 v. 变缓和，变弱', 3351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'visceral', 'adj. 内脏的；出于本能的；发自肺腑的；粗俗的', 3352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stolid', 'adj. 迟钝的；缺乏热情的；冷漠的', 3353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'electroscope', 'n. [电] 验电器', 3354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complaisance', 'n. 殷勤；彬彬有礼；柔顺', 3355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'genesis', 'n. 发生；起源', 3356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'exculpate', 'v. 开脱；使无罪', 3357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'clan', 'n. 宗族；部落；集团', 3358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accomplice', 'n. 同谋者，[法] 共犯', 3359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'savage', 'adj. 野蛮的；残酷的；狂怒的；荒凉的 n. 未开化的人；粗鲁的人；残暴成性的人 v. 乱咬；粗暴的对待', 3360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fortuitous', 'adj. 偶然的，意外的；幸运的', 3361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'frizzle', 'v. 使卷缩；使卷曲 n. 卷发；吱吱响声', 3362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'preservation', 'n. 保存，保留', 3363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'tantamount', 'adj. 同等的；相当于…的', 3364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unawares', 'adv. 不知不觉地；出其不意地；不料', 3365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'photon', 'n. [物] 光子；辐射量子；见光度（等于light quantum）', 3366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'lascivious', 'adj. 好色的；淫荡的；挑动情欲的', 3367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'external', 'adj. 外部的；表面的；[药] 外用的；外国的；外面的 n. 外部；外观；外面', 3368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'portray', 'v. 描绘；扮演', 3369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'seminary', 'n. 神学院；学校；发源地；高级中学', 3370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'minnow', 'n. [鱼] 鲦鱼（一种小淡水鱼）', 3371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'obsolescent', 'adj. 荒废的；即将过时的；逐渐被废弃的', 3372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'academic', 'adj. 学术的；理论的；学院的 n. 大学生，大学教师；学者', 3373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'incorporate', 'v. 包含，吸收；体现；把……合并 adj. 合并的；一体化的；组成公司的', 3374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'refer', 'v. 参考；涉及；提到；查阅', 3375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auxiliary', 'n. 助动词；辅助者，辅助物；附属机构 adj. 辅助的；副的；附加的', 3376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rebuke', 'v. 指责，非难；制止；使相形见绌 n. 非难，指责；谴责，鞭策', 3377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'condense', 'v. 浓缩；凝结', 3378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'buttress', 'n. 扶壁；拱壁；支撑物 v. 支持；以扶壁支撑', 3379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'microphone', 'n. 扩音器，麦克风', 3380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'contentious', 'adj. 诉讼的；有异议的，引起争论的；爱争论的', 3381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'duplicate', 'v. 复制；使加倍 n. 副本；复制品 adj. 复制的；二重的', 3382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mansion', 'n. 大厦；宅邸', 3383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intoxicate', 'v. 使陶醉；使喝醉；使中毒', 3384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'insightful', 'adj. 有深刻见解的，富有洞察力的', 3385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'numerator', 'n. 分子；计算者；计算器', 3386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'neutral', 'adj. 中立的，中性的；中立国的；非彩色的 n. 中立国；中立者；非彩色；齿轮的空档', 3387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gruesome', 'adj. 可怕的；阴森的', 3388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ratification', 'n. 批准；承认，认可', 3389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divers', 'adj. 不同种类的，各式各样的 n. (Divers)人名；(英)戴弗斯；(法)迪韦尔', 3390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divert', 'v. 转移；使…欢娱；使…转向 n. (Divert)人名；(法)迪韦尔', 3391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bygone', 'adj. 过去的 n. 过去的事', 3392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'fawn', 'v. 奉承 n. 小鹿；浅黄褐色；小动物 adj. 浅黄褐色的', 3393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'resumption', 'n. 恢复；重新开始；取回；重获；恢复硬币支付', 3394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'besmirch', 'v. 弄污；损害；诽谤', 3395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vex', 'v. 使烦恼；使困惑；使恼怒', 3396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'intermit', 'v. 使中断', 3397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'trickery', 'n. 欺骗；诡计；奸计', 3398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ostracize', 'v. 放逐；排斥；按贝壳流放法放逐', 3399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'perceive', 'v. 察觉，感觉；理解；认知', 3400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'jargon', 'n. 行话，术语；黄锆石', 3401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'liquefy', 'v. 液化；溶解', 3402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'divest', 'v. 剥夺；使脱去，迫使放弃', 3403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'detract', 'v. 转移，使分心', 3404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emphasis', 'n. 重点；强调；加强语气', 3405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'liberate', 'v. 解放；放出；释放', 3406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subtlety', 'n. 微妙；敏锐；精明', 3407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coherent', 'adj. 连贯的，一致的；明了的；清晰的；凝聚性的；互相耦合的；粘在一起的', 3408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'materialist', 'n. 唯物主义者；实利主义者', 3409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'juvenile', 'adj. 青少年的；幼稚的 n. 青少年；少年读物', 3410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'recoil', 'v. 畏缩；弹回；报应 n. 畏缩；弹回；反作用', 3411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'ensure', 'v. 保证，确保；使安全', 3412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'waver', 'v. 摇曳；踌躇；摆动 n. 动摇；踌躇；挥动者', 3413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cartridge', 'n. 弹药筒，打印机的（墨盒）；[摄] 暗盒；笔芯；一卷软片', 3414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'censure', 'v. 责难，责备 n. 责难', 3415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'revitalize', 'v. 使…复活；使…复兴；使…恢复生气', 3416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dullard', 'n. 笨蛋；愚人', 3417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'edible', 'adj. 可食用的 n. 食品；食物', 3418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'sonar', 'n. 声纳；声波定位仪（等于asdic）', 3419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'salubrious', 'adj. 清爽的；气候有益健康的', 3420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'utility', 'n. 实用；效用；公共设施；功用 adj. 实用的；通用的；有多种用途的', 3421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bass', 'n. 鲈鱼；男低音；低音部；椴树 adj. 低音的', 3422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'unduly', 'adv. 过度地；不适当地；不正当地', 3423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'base', 'n. 基础；底部；垒 adj. 卑鄙的；低劣的 v. 以…作基础', 3424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'grisly', 'adj. 可怕的；厉害的；严重的', 3425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rehabilitate', 'v. 使康复；使恢复名誉；使恢复原状', 3426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coincide', 'v. 一致，符合；同时发生', 3427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'raucous', 'adj. 沙哑的；刺耳的；粗声的', 3428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predominate', 'v. 支配，主宰；在…中占优势', 3429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bask', 'v. 晒太阳；取暖；愉快或舒适 n. (Bask)人名；(芬)巴斯克', 3430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coefficient', 'n. [数] 系数；率；协同因素 adj. 合作的；共同作用的', 3431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'hesitant', 'adj. 迟疑的；踌躇的；犹豫不定的', 3432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'conviction', 'n. 定罪；确信；证明有罪；确信，坚定的信仰', 3433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precursor', 'n. 先驱，前导', 3434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'qualify', 'v. 限制；使具有资格；证明…合格', 3435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'extenuate', 'v. 减轻；低估；为…找借口；使人原谅', 3436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rustic', 'adj. 乡村的；纯朴的；粗野的；手工粗糙的 n. 乡下人；乡巴佬', 3437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bounce', 'n. 跳；弹力；活力 v. 弹跳；使弹起', 3438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bane', 'n. 毒药；祸害；灭亡的原因', 3439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'overwork', 'v. 工作过度 n. 过度工作', 3440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'retrospective', 'adj. 回顾的；怀旧的；可追溯的 n. 回顾展', 3441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'boatswain', 'n. 水手长', 3442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'empiricism', 'n. 经验主义；经验论', 3443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'terminal', 'n. 末端；终点；终端机；极限 adj. 末端的；终点的；晚期的', 3444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'diversion', 'n. 转移；消遣；分散注意力', 3445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'interlocutor', 'n. 对话者；谈话者', 3446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'specimen', 'n. 样品，样本；标本', 3447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mythology', 'n. 神话；神话学；神话集', 3448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'invasion', 'n. 入侵，侵略；侵袭；侵犯', 3449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'squabble', 'v. 发生口角；大声争吵 n. 争吵；口角', 3450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'dissever', 'v. 使分离；使分裂', 3451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'peccant', 'adj. 犯罪的；有过失的', 3452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'widespread', 'adj. 普遍的，广泛的；分布广的', 3453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'effuse', 'v. 流出；涌出；泻出 adj. [植] 疏展的', 3454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'corrosion', 'n. 腐蚀；腐蚀产生的物质；衰败', 3455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'derogate', 'v. 减损；贬损', 3456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vital', 'adj. 至关重要的；生死攸关的；有活力的 n. (Vital)人名；(法、德、意、俄、葡)维塔尔；(西)比塔尔', 3457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'mandatory', 'adj. 强制的；托管的；命令的 n. 受托者（等于mandatary）', 3458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'cognizant', 'adj. 审理的；已认知的', 3459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'allusion', 'n. 暗示；提及', 3460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'orbit', 'n. 轨道；眼眶；势力范围；生活常规 v. 盘旋；绕轨道运行', 3461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'furlough', 'n. 休假；暂时解雇；放假 v. 准假；暂时解雇', 3462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blatant', 'adj. 喧嚣的；公然的；炫耀的；俗丽的', 3463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'subjection', 'n. 隶属；服从；征服', 3464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disorder', 'n. 混乱；骚乱 v. 使失调；扰乱', 3465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'accustomed', 'adj. 习惯的；通常的；独有的 v. 使习惯于（accustom的过去分词）', 3466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'rebuff', 'n. 断然拒绝；回绝；漠不关心 v. 断然拒绝', 3467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'aerate', 'v. 充气；让空气进入；使暴露于空气中', 3468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'deteriorate', 'v. 恶化，变坏', 3469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'miasma', 'n. 瘴气；臭气；不良影响', 3470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bile', 'n. 胆汁；愤怒', 3471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'auricular', 'adj. 耳的；耳状的', 3472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'bilk', 'v. 欺骗，诈骗；使受挫折；赖帐 n. 诈骗；骗子；赖帐', 3473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'evidence', 'n. 证据，证明；迹象；明显 v. 证明', 3474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'stimulus', 'n. 刺激；激励；刺激物', 3475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'credo', 'n. 信条，教义', 3476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blaze', 'v. 在树皮上刻路标；公开宣布 n. 火焰，烈火；光辉；情感爆发', 3477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'embargo', 'v. 禁止出入港口；禁止或限制贸易；征用或扣押 n. 禁令；禁止；封港令', 3478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'algae', 'n. [植] 藻类；[植] 海藻', 3479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vacate', 'v. 空出，腾出；辞职；休假', 3480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'blight', 'n. 枯萎病；荒芜 v. 破坏；使…枯萎', 3481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'gallant', 'adj. 英勇的，勇敢的；华丽的；雄伟的 n. (Gallant)人名；(法)加朗；(英)加伦特', 3482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'vocative', 'adj. 呼格的；称呼的 n. 呼格', 3483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'homily', 'n. 说教；训诫', 3484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complementary', 'adj. 补足的，补充的', 3485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'predominant', 'adj. 主要的；卓越的；支配的；有力的；有影响的', 3486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'derange', 'v. 扰乱；使错乱；使发狂', 3487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'emphasize', 'v. 强调，着重', 3488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'timorous', 'adj. 胆怯的；胆小的；羞怯的', 3489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'complaint', 'n. 抱怨；诉苦；疾病；委屈', 3490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'indistinct', 'adj. 模糊的，不清楚的；朦胧的；难以清楚辨认的', 3491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'impenitent', 'n. 顽固的人；不知悔改的人 adj. 顽固的；不知悔改的', 3492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'law', 'n. 法律；规律；法治；法学；诉讼；司法界 vi. 起诉；控告 vt. 控告；对…起诉', 3493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'coax', 'v. 哄；哄诱；慢慢将…弄好', 3494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'precision', 'n. 精度，[数] 精密度；精确 adj. 精密的，精确的', 3495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'constant', 'adj. 不变的；恒定的；经常的 n. [数] 常数；恒量', 3496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'witchcraft', 'n. 巫术；魔法', 3497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'amiable', 'adj. 和蔼可亲的，亲切的 n. (Amiable)人名；(法)阿米亚布勒；(英)阿米娅布尔', 3498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'maverick', 'n. 没打烙印的动物；持不同意见的人 vt. 用不正当手段获取 vi. 迷途；背离 adj. 未打烙印的；行为不合常规的；特立独行的', 3499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (11, 'disrupt', 'v. 破坏；使瓦解；使分裂；使中断；使陷于混乱 adj. 分裂的，中断的；分散的', 3500);
