INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'squeeze', 'v. 压榨，挤 n. 榨取， 勒索', 4001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'blank', 'adj. 空白的；茫然的，无表情的 n. 空白； 空白表格', 4002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'additional', 'adj. 附加的， 追加的', 4003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'worthy', 'adj. 有价值的， 值得的', 4004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'primarily', 'adv. 首先， 主要地', 4005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'telecommunications', 'n. 通信， 电信', 4006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ferry', 'n. 渡船 vt. 渡运', 4007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ignore', 'vt. 不顾， 不理； 忽视', 4008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'hemisphere', 'n. 地球的半球； 大脑半球', 4009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reception', 'n. 招待会， 欢迎会； 接受， 接纳； 接待， 迎接； 接收效果', 4010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'applaud', 'vi. 鼓掌，喝彩 vt. 向…鼓掌， 向…喝彩； 称赞， 赞许', 4011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'outward', 'adv. 向外地 adj. 外面的，外表的', 4012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'lunar', 'adj. 月的， 月球的', 4013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'poetry', 'n. 诗， 诗歌， 诗集', 4014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'jury', 'n. 陪审团， 评奖团', 4015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'arrogant', 'adj. 傲慢的， 自大的', 4016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'idiot', 'n. 白痴； 傻子， 笨蛋', 4017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'relay', 'n. 接力赛；中继转播 vt. 传送， 传达， 转述； 中继转播', 4018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'priest', 'n. 神父， 牧师', 4019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'monitor', 'n. 班长；监视器，检测器；显示器 vt. 监听， 检测', 4020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'solo', 'adv. 以独力，单独地 adj. 单独的，单独进行的 n. 独奏， 独唱， 独舞', 4021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'tuition', 'n. 教学， 讲授， 指导； 学费', 4022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'permeate', 'v. 弥漫， 遍布， 散布； 渗入， 渗透', 4023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'utopian', 'adj. 乌托邦的； 理想的', 4024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'schedule', 'n. 时刻表，日程安排表；清单，明细表 vt. 安排， 排定', 4025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'tame', 'adj. 驯服的，顺从的；沉闷的，乏味的 vt. 制服， 控制并利用； 驯化， 驯服', 4026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'adjoin', 'vt. 贴近； 与…毗连', 4027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'universe', 'n. 宇宙， 世界； 领域， 范围', 4028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'inherit', 'vt. 继承', 4029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'overwhelming', 'adj. 势不可挡的， 压倒的； 巨大的', 4030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'interpret', 'v. 解释， 说明； 口译', 4031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'peculiar', 'adj. 奇怪的， 古怪的； 特有的', 4032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'idiom', 'n. 习语， 成语； 风格， 特色', 4033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'diplomat', 'n. 外交官， 外交家； 有交际手腕的人， 圆滑的人', 4034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'hug', 'vi. 紧抱在一起，互相拥抱 vt. 拥抱；紧抱，怀抱 n. 紧抱， 热烈拥抱', 4035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'grant', 'n. 授给物 vt. 授予， 给予', 4036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'muscular', 'adj. 肌肉发达的， 强壮的； 肌肉的', 4037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sparkle', 'vi. 发光，闪耀，闪烁；活跃，焕发 n. 闪光， 闪耀， 闪烁； 活力， 生气', 4038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'hum', 'vi. 哼曲子；发嗡嗡声 vt. 哼 n. 嗡嗡声， 营营声， 嘈杂声', 4039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'staple', 'adj. 主要的； 经常需要的 n. 订书钉，U形钉；主食；主要产品 vt. 用订书钉订', 4040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'discount', 'n. 折扣 vt. 把…打折扣； 不全信； 漠视， 低估', 4041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'construct', 'vt. 建造； 构思 n. 建筑物； 构想； 观念', 4042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'royalty', 'n. 王族； 版税', 4043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'convert', 'vt. 转变， 转化； 改变', 4044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'attempt', 'vt. 尝试， 试图， 努力', 4045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'rivalry', 'n. 竞争， 竞赛； 对抗', 4046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'relish', 'vt. 享受，从…中获得乐趣 n. 享受， 滋味， 乐趣； 调味品', 4047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fluorescent', 'adj. 荧光的， 发荧光的', 4048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'division', 'n. 分， 分割； 部门， 科， 处； 除法', 4049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'superficial', 'adj. 表面的， 肤浅的', 4050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'executive', 'adj. 执行的；行政的 n. 执行者', 4051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'navigation', 'n. 航行， 航海， 航空； 导航， 领航', 4052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'melt', 'v. 融化； 溶化； 消散', 4053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stalk', 'vi. 高视阔步地走 n. 茎，梗，柄 vt. 悄悄地跟踪', 4054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'whereas', 'conj. 然而， 但是， 尽管', 4055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pitch', 'v. 投掷， 使猛然倒下； 表达， 定下特定程度； 定调； 架设， 搭， 扎； 颠簸 n. 球场；程度，强度；高度，高音；沥青', 4056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'casualty', 'n. 伤亡人员， 死伤者； 受害人， 损失的东西', 4057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'gauge', 'n. 测量仪表；厚度，直径；规格、尺寸 vt. 估计， 判断； 计量， 度量', 4058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'oriental', 'adj. 东方的； 东方人的； 东方文化的', 4059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'electrical', 'adj. 电的； 电气科学的', 4060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stall', 'v. 熄火； 拖延， 推迟 n. 货摊；', 4061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'protest', 'v. [\'prəutest] n. 抗议， 反对', 4062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sensitive', 'adj. 敏感的， 灵敏的； 神经过敏的， 容易生气的； 易受伤害的', 4063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'classification', 'n. 分类， 分级， 分类法； 类别， 级别', 4064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'brew', 'vi. 冲泡；酝酿，行将发生 vt. 酿造；冲泡 n. 冲泡的饮料', 4065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'vacant', 'adj. 空的， 未被占用的； 空缺的； 茫然的， 空虚的', 4066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'menace', 'n. 具有危险性的人；威胁，威吓 vt. 威胁， 威吓', 4067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'afford', 'vt. 担负得起； 提供', 4068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'invalid', 'adj. 无效的，作废的；无可靠根据的，站不住脚的 n. 病弱者， 残疾者', 4069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'curse', 'v. 诅咒，咒骂，天谴 n. 祸害， 祸根； 咒骂， 诅咒， 咒语', 4070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'legitimate', 'adj. 合情合理的；合理的，法律认可的 vt. 使合法', 4071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'appease', 'vt. 平息， 抚慰； 姑息', 4072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sieve', 'n. 筛子，漏勺 vt. 筛， 滤', 4073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'whereby', 'adv. 凭此； 借以； 由于', 4074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'evaluate', 'vt. 评价， 估…的价', 4075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'status', 'n. 地位， 身份； 情形， 状况', 4076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'machinery', 'n. 机器， 机械', 4077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'shield', 'n. 防护物，护罩；盾 vt. 保护， 防护', 4078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'skip', 'vi. 跳，蹦跳；跳绳 vt. 跳过，略过，漏过 n. 跳， 蹦跳', 4079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'instantaneous', 'adj. 瞬间的， 即刻的', 4080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'phenomenon', 'n. 现象， 迹象； 非凡的人', 4081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'quarterly', 'adv. 按季度，一季一次 adj. 季度的，每季一次的 n. 季刊', 4082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'notify', 'vt. 通知， 告知； 报告', 4083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bibliography', 'n. 参考书目； 书目', 4084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stream', 'v. 流出， 涌出 n. 河，溪流；一股，一串', 4085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'recur', 'vi. 再发生， 重现', 4086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'coalition', 'n. 结合体， 同盟； 结合， 联合', 4087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'generalize', 'vt. 概括， 归纳， 推断； 普及', 4088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'accumulate', 'v. 积累， 堆积', 4089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'crime', 'n. 罪， 罪行， 犯罪', 4090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dwarf', 'adj. 矮小的，发育不全的 n. 矮子，侏儒 vt. 使显得矮小， 使相形见绌', 4091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'heave', 'v. 举起，提起；扔；发出；起伏，隆起；呕吐，恶心 n. 举起， 升降', 4092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'leisure', 'n. 空闲时间； 悠闲', 4093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nourish', 'vt. 养育， 喂养， 滋养； 怀有， 增强', 4094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'grease', 'n. 油脂；润滑脂，润滑油 vt. 用油脂涂， 给…加润滑油', 4095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'allege', 'vt. 断言， 宣称， 硬说', 4096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pilgrim', 'n. 朝圣者', 4097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'trigger', 'n. 扳机；引起反应的行动 vt. 触发， 引起', 4098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'assimilate', 'vi. 被吸收， 被消化； 被同化 vt. 吸收，消化；使同化', 4099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'positive', 'adj. 确实的， 明确的； 积极的， 肯定的', 4100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'segregate', 'vt. 使隔离， 使分开', 4101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'addict', 'n. 有瘾的人； 入迷的人 vt. 使成瘾， 使入迷', 4102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'prospect', 'n. 前景， 前途， 可能性； 景象， 景色； 可能成为主顾的人， 有希望的候选人', 4103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'withhold', 'vt. 拒绝， 不给； 抑制， 制止', 4104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'comparable', 'adj. 可比较的； 类似的； 比得上的', 4105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'discreet', 'adj. 谨慎的， 慎重的， 审慎的', 4106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'specialize', 'vi. 专攻，专门研究 vt. 使适应特殊目的， 使专用于', 4107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'instance', 'n. 例子， 实例， 事例', 4108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'presumably', 'adv. 大概， 可能， 据推测', 4109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bonus', 'n. 奖金， 红利； 额外给予的东西', 4110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'recognition', 'n. 认出， 识别； 承认， 确认， 认可； 赏识， 表彰， 报偿', 4111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'banquet', 'n. 宴会， 盛宴', 4112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'thrill', 'v. 非常兴奋， 非常激动 n. 兴奋，激动；引起激动的事物', 4113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'aisle', 'n. 过道， 通道', 4114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'convene', 'vi. 开会，集合 vt. 召集', 4115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'arrangement', 'n. 整理， 排列； 安排； 准备工作', 4116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'revenue', 'n. 收入， 收益； 税收， 岁入', 4117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'solution', 'n. 解决； 解决办法； 溶液', 4118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'monopoly', 'n. 垄断， 专卖； 垄断物， 垄断商品， 专卖商品', 4119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'opponent', 'n. 对手； 敌手， 对抗者', 4120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'accelerate', 'vt. 使加快， 使增速', 4121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'supplementary', 'adj. 增补的， 补充的', 4122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'grain', 'n. 谷物， 谷粒， 颗粒； 少量， 微量', 4123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'credit', 'n. 信贷，赊欠；赞扬，荣誉；学分；信任 vt. 相信； 把…记入贷方； 把…归于', 4124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'oxygen', 'n. 氧， 氧气', 4125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'intensive', 'adj. 加强的； 精耕细作的', 4126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'alter', 'vt. 改变， 变更， 变动', 4127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'combine', 'v. 结合，联合；化合 n. 联合企业； 联合收割机', 4128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ideal', 'adj. 理想的，观念的，空想的 n. 理想， 理想的东西', 4129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'occur', 'vi. 发生， 出现， 存在； 被想起， 被想到', 4130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'illustrate', 'vt. 说明', 4131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'hose', 'n. 软管，水龙带 vt. 用软管淋浇', 4132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'definitive', 'adj. 最可靠的， 权威性的； 决定性的', 4133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'streak', 'vi. 飞跑，疾驶 n. 条纹，条痕；个性特征；一阵子，一连串 vt. 在…上加条纹', 4134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pressure', 'n. 压，压强；压迫 vt. 对…施加压力， 迫使， 说服', 4135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dentist', 'n. 牙科医生', 4136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'brood', 'vi. 沉思，考虑；孵蛋 n. 一窝； 全体孩子', 4137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'literacy', 'n. 识字， 有文化， 读写能力', 4138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'originate', 'vi. 起源于，来自，产生 vt. 创造， 创始， 开创', 4139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'specialist', 'n. 专家', 4140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'background', 'n. 出身背景， 经历； 背景资料； 背景， 底子', 4141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'millionaire', 'n. 百万富翁， 大富翁', 4142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'transit', 'n. 运输， 载运', 4143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'adolescent', 'adj. 青春期的； 青少年的 n. 青少年', 4144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nonetheless', 'adv. 尽管如此， 依然， 然而', 4145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dispose', 'v. 去掉， 销毁； 处理， 解决； 使倾向于', 4146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'petty', 'adj. 小的， 琐碎的； 不重要的； 气量小的， 心胸狭窄的', 4147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'glow', 'vi. 发光； 燃烧 n. 白热光；脸红；激情', 4148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sentiment', 'n. 意见， 观点； 感情， 情绪', 4149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'differentiation', 'n. 区别', 4150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'constitution', 'n. 宪法， 章程； 组成； 设立', 4151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'patent', 'adj. 专利的，受专利保护的 n. 专利，专利权 vt. 得到…的专利权', 4152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cocaine', 'n. 可卡因， 古柯碱', 4153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'groove', 'n. 沟， 槽', 4154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'abundance', 'n. 大量， 丰富， 充足', 4155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'racket', 'n. 喧嚷， 吵闹； 敲诈， 勒索， 诈骗； 球拍', 4156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'conceive', 'vi. 构想出， 设想； 怀孕 vt. 想出，认为；怀', 4157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sour', 'adj. 酸的；馊的，酸味的；脾气坏的 v. 变酸， 变馊； 变得乖戾', 4158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'transform', 'vt. 使改观， 改革； 变换， 把…转换成', 4159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'napkin', 'n. 餐巾', 4160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reckless', 'adj. 鲁莽的， 不考虑后果的', 4161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'paradox', 'n. 似乎矛盾而正确的说法； 自相矛盾的人', 4162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'magnitude', 'n. 重要性， 重大； 巨大， 广大', 4163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'justification', 'n. 正当的理由， 借口', 4164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'genuine', 'adj. 真的， 真正的； 真诚的', 4165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'execution', 'n. 死刑； 实行， 执行， 履行； 演奏， 表演', 4166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'immune', 'adj. 免疫的， 有免疫力的， 不受影响的； 免除的， 豁免的', 4167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'brochure', 'n. 小册子', 4168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stern', 'adj. 严厉的，严格的，严峻的 n. 船尾', 4169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'rotary', 'adj. 旋转的， 转动的', 4170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'compound', 'adj. 复合的，化合的 n. 化合物，复合物；复合词 vt. 使恶化， 加重； 使化合， 使合成', 4171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dub', 'vt. 给…起绰号， 把…称为； 为配音， 译制', 4172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'masculine', 'adj. 男性的， 男子的； 男子气的', 4173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'extraordinary', 'adj. 非同寻常的， 特别的', 4174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'witness', 'n. 证据；目击者，证人 vt. 目击； 为…作证， 证明', 4175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'conventional', 'adj. 普通的； 习惯的， 常规的； 因循守旧的', 4176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'regulation', 'n. 规章， 规则； 管理， 控制， 调节', 4177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'conform', 'vi. 遵守， 适应； 顺从； 相似， 一致， 符合', 4178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'circulation', 'n. 循环， 流通； 流传， 传播， 发行； 发行量； 流通', 4179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'authentic', 'adj. 真的， 真正的； 可靠的， 可信的', 4180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mere', 'adj. 仅仅的， 纯粹的', 4181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'accommodation', 'n. 住处， 膳宿', 4182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'evident', 'adj. 明显的， 明白的', 4183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'suburb', 'n. 郊区， 郊外， 近郊', 4184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pumpkin', 'n. 南瓜', 4185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'annoy', 'vt. 使恼怒； 打搅', 4186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'profess', 'vt. 表示， 承认； 宣称信仰', 4187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'psychological', 'adj. 心理的', 4188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'credible', 'adj. 可信的， 可靠的', 4189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'empirical', 'adj. 以经验为依据的， 经验主义的， 经验的', 4190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'commit', 'vt. 犯， 干； 使承诺； 把…托付给； 调拨…供使用， 拨出', 4191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'curb', 'vt. 控制，约束 n. 控制， 约束； 路缘', 4192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'crash', 'vi. 倒下，坠落；发出撞击声；垮台，破产 vt. 碰撞，砸碎；冲，闯 n. 碰撞； 破裂声', 4193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'character', 'n. 性格， 特性； 性质； 人物， 角色； 符号， 字', 4194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reflect', 'v. 反映， 显示； 反射， 映现； 深思， 考虑， 反省', 4195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'outfit', 'n. 全套服装； 一组人； 全套装备， 全套工具', 4196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'contribution', 'n. 贡献； 促成作用； 捐款， 捐献物； 稿件', 4197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ongoing', 'adj. 持续的， 继续的', 4198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'massacre', 'vt. 大规模屠杀，残杀；彻底击败 n. 大屠杀， 残杀； 惨败', 4199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reassure', 'vt. 使放心', 4200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bang', 'v. 猛击， 猛撞； 发出砰的一声， 砰砰地响； 砰地敲 n. 巨响；枪声；猛击', 4201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'magnetic', 'adj. 磁的； 有吸引力的', 4202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cholesterol', 'n. 胆固醇', 4203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'orbit', 'n. 轨道 vt. 作轨道运行', 4204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'band', 'n. 乐队；群，伙；带；条纹；波段 vt. 用带绑扎', 4205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'negligible', 'adj. 可忽略不计的， 微不足道的', 4206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'setback', 'n. 挫折， 倒退， 失败', 4207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'resident', 'adj. 居住的， 定居的； 住校的， 住院的 n. 居民，定居者；住院医生', 4208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'symbolic', 'adj. 符号的； 象征性的', 4209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'distinguish', 'vt. 区别， 辨别， 识别； 使杰出； 使著名', 4210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mall', 'n. 购物中心', 4211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'module', 'n. 组件， 模块， 模件； 舱', 4212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'howl', 'n&vi. 嗥叫； 呼啸； 吼叫， 哀号', 4213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'execute', 'vt. 将…处死； 实施', 4214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'substantial', 'adj. 可观的， 大量的； 物质的， 坚固的； 实质的， 真实的', 4215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'benefit', 'vi. 得益 n. 利益，恩惠；救济金，保险金，津贴 vt. 有益于', 4216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'booth', 'n. 小房间， 公用电话亭， 岗亭； 售货棚， 货摊', 4217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'enthusiastic', 'adj. 满腔热情的， 热心的， 极感兴趣的', 4218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'disastrous', 'adj. 灾难性的， 造成灾害的； 极坏的， 很糟的', 4219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'unique', 'adj. 唯一的， 独一无二的； 极不寻常的， 极好的', 4220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'processing', 'n. 处理', 4221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'boost', 'v. 推动， 促进， 激励； 替…做广告， 宣扬； 提高， 使增长 n. 提高，增长；推动，激励', 4222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'impulse', 'n. 冲动， 一时的念头； 推动， 驱使； 脉冲', 4223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sober', 'adj. 未醉的，有节制的；严肃的，持重的；素淡的，暗淡的 v. 醒酒， 清醒', 4224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'crystallize', 'v. 结晶； 变得清晰而明确； 使具体化', 4225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'religious', 'adj. 宗教的； 笃信宗教的， 虔诚的', 4226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'infectious', 'adj. 传染的， 有传染性的； 有感染力的', 4227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'shelter', 'v. 掩蔽， 躲避， 庇护 n. 掩蔽处，躲避处；掩蔽，保护', 4228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'prominent', 'adj. 突出的， 杰出的； 突起的； 凸出的', 4229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'expel', 'vt. 把…除名， 把…开除； 驱逐， 赶走， 放逐； 排出， 喷出', 4230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'superiority', 'n. 优越， 优等', 4231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'outset', 'n. 开始， 开端', 4232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'latitude', 'n. 纬度； 纬度地区； 回旋余地， 自由', 4233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'scan', 'vt. 细看，审视，浏览 n. 扫描', 4234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'association', 'n. 协会， 团体； 联合， 交往', 4235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fundamental', 'adj. 基础的，基本的 n. 基本原则', 4236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'eliminate', 'vt. 消灭， 消除， 排除； 淘汰', 4237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cute', 'adj. 漂亮的， 娇小可爱的； 聪明伶俐的， 精明的', 4238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'entitle', 'vt. 给…权利； 给题名', 4239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'outline', 'n. 提纲，要点；外形；略图 vt. 概述； 描…的外形', 4240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'partition', 'n. 分隔物，隔墙；分割，划分 vt. 隔开； 分割， 瓜分', 4241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nominal', 'adj. 名义上的， 有名无实的； 很少的， 象征性的； 名词性的', 4242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'excess', 'adj. 过量的， 额外的 n. 超越，过量，过度[\'3ks3s]', 4243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'glance', 'vi. 看一下 n. 一瞥', 4244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'perspective', 'n. 视角， 观点； 远景， 景观； 透视画法， 透视图', 4245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'galaxy', 'n. 星系； 银河系， 银河； 一群', 4246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'equality', 'n. 等同； 平等； 相等', 4247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'destruction', 'n. 破坏， 毁灭； 消灭', 4248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'rebellion', 'n. 反叛， 反抗', 4249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'expression', 'n. 词语； 表达， 表情', 4250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reaction', 'n. 反应， 反作用', 4251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'accordance', 'n. 一致， 和谐， 符合', 4252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'weary', 'vi. 厌烦， 不耐烦 adj. 疲劳的，疲倦的；使人疲劳的，令人厌倦的', 4253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'appeal', 'vi. 求助，诉请；要求；有吸引力 vt. 控诉，移交上级法院审理 n. 吸引力； 呼吁； 上诉', 4254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'swamp', 'n. 沼泽 vt. 淹没， 浸没； 难倒， 压倒', 4255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'entrepreneur', 'n. 企业家', 4256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dedicate', 'vt. 题献词于上； 把献给， 把用于', 4257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'peninsula', 'n. 半岛', 4258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'extensive', 'adj. 广阔的； 广泛的', 4259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'residential', 'adj. 居住的， 住宅的； 寄宿的， 住在住所的', 4260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'definitely', 'adv. 一定地， 明确地', 4261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stab', 'n&v. 刺， 戳', 4262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'abandon', 'vt. 离弃， 丢弃； 遗弃； 抛弃； 放弃', 4263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'collaboration', 'n. 合作， 协作； 勾结', 4264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'inspire', 'vt. 鼓舞； 给…以灵感', 4265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'impart', 'vt. 告知， 透露； 赋予， 给予', 4266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bureaucracy', 'n. 官僚主义， 官僚作风； 官僚机构； 官僚制度； 官僚', 4267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'household', 'adj. 家庭的， 家喻户晓的 n. 家庭，户；家务', 4268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'glide', 'n. 滑行， 滑动； 滑翔', 4269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'adverse', 'adj. 不利的， 有害的', 4270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bulletin', 'n. 简明新闻， 最新消息； 公告， 布告， 公报； 学报， 期刊', 4271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'devote', 'vt. 将…奉献给， 把…专用', 4272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'junction', 'n. 联结点， 交叉点， 枢纽', 4273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'crumble', 'vi. 崩溃， 瓦解 vt. 弄碎', 4274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'agent', 'n. 代理人， 代理商； 政府代表； 动因， 原因； 剂', 4275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'abortion', 'n. 流产， 堕胎', 4276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'salvation', 'n. 拯救， 解救； 解救措施', 4277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'instinct', 'n. 本能； 直觉， 生性', 4278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cannon', 'n. 加农炮， 大炮， 火炮', 4279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'invest', 'v. 投资， 投入； 授予', 4280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reputation', 'n. 名誉， 名气， 名声', 4281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'project', 'v. 伸出； 投射； 放映 n. 方案， 计划； 课题， 项目； 工程', 4282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'shrug', 'n&v. 耸肩', 4283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'arena', 'n. 表演场地， 竞技场； 活动场所', 4284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'independence', 'n. 独立； 自主； 自立', 4285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'shrub', 'n. 灌木', 4286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'presentation', 'n. 提供， 显示； 外观， 图像； 授予， 赠送； 报告， 介绍； 表演', 4287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nominate', 'vt. 提名， 任命； 推荐， 指定', 4288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'loom', 'vi. 阴森地逼近， 隐现； 即将来临 n. 织布机', 4289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'stationary', 'adj. 固定的， 静止不动的', 4290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'restrain', 'vt. 阻止， 控制； 抑制， 遏制', 4291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'awkward', 'adj. 笨拙的， 尴尬的； 难操纵的， 使用不便的； 不灵巧的', 4292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ruin', 'v. 毁坏 n. 毁灭；废墟', 4293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'beforehand', 'adv. 预先， 事先', 4294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'formidable', 'adj. 可怕的， 令人敬畏的； 难以克服的， 难对付的', 4295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'impatient', 'adj. 不耐烦的， 急躁的； 热切的， 急切的', 4296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'invert', 'vt. 使倒转， 使倒置， 使颠倒', 4297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cradle', 'n. 摇篮；策源地，发源地 vt. 轻轻地抱， 捧', 4298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'discrete', 'adj. 分离的， 不相关联的', 4299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'assurance', 'n. 把握， 信心； 保证， 表示保证的话； 保险', 4300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'psychiatrist', 'n. 精神科医生， 精神病专家', 4301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'squad', 'n. 班， 小队， 小组', 4302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'disrupt', 'vt. 使中断； 扰乱', 4303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'scar', 'v. 留下伤痕 n. 伤疤，伤痕；创伤', 4304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sergeant', 'n. 中士， 警官', 4305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'vital', 'adj. 生死攸关的， 极其重要的； 生命的， 有生命力的', 4306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'eccentric', 'adj. 古怪的，怪癖的，异乎寻常的 n. 古怪的人， 怪癖的人', 4307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'conflict', 'vi. 冲突， 抵触 n. 冲突， 抵触； 争论； 战斗， 战争', 4308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'appliance', 'n. 用具， 器具， 器械', 4309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'alloy', 'n. 合金 vt. 将…铸成合金', 4310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'delusion', 'n. 欺骗； 哄骗', 4311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mass', 'adj. 大量的，大规模的 v. 聚集， 集中 n. 众多，大量；团，块，堆；群众；质量', 4312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'detect', 'vt. 察觉， 发觉； 侦查出', 4313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'update', 'vt. 更新；使现代化 n. 最新信息', 4314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'renaissance', 'n. 文艺复兴， 文艺复兴时期； 复兴， 再生', 4315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'poisonous', 'adj. 有毒的； 恶毒的', 4316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'condemn', 'vt. 谴责， 指责； 判…刑， 宣告…有罪', 4317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'assistance', 'n. 协助， 援助', 4318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'auction', 'n&vt. 拍卖', 4319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'propel', 'vt. 推进， 推动； 激励， 驱使', 4320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'admit', 'vi. 承认 vt. 承认，供认；准许…进入', 4321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'uneven', 'adj. 不平坦的， 不平滑的； 不一致的， 不相等的', 4322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'definition', 'n. 定义， 释义， 定界； 清晰， 鲜明', 4323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mansion', 'n. 大厦， 宅邸', 4324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mask', 'n. 面具，面罩，口罩；伪装 vt. 遮盖， 掩饰', 4325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'patrol', 'v. 巡逻，巡查 n. 巡逻， 巡查； 巡逻兵， 巡逻队', 4326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nickel', 'n. 镍； 五分镍币， 五分钱', 4327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'patron', 'n. 资助人， 赞助人； 老主顾， 顾客', 4328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'entail', 'vt. 使承担； 使成为必要， 需要', 4329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'inferior', 'adj. 下等的，劣等的 n. 下级， 下属', 4330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'apply', 'vi. 应用，实施，使用；适用；申请，请求 vt. 涂， 敷， 施', 4331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'propaganda', 'n. 宣传', 4332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'overlook', 'vt. 忽视； 宽恕； 俯瞰', 4333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'refuge', 'n. 庇护所， 避难处； 庇护', 4334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dramatic', 'adj. 引人注目的， 激动人心的； 戏剧的', 4335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'incredible', 'adj. 不能相信的， 不可信的， 难以置信的； 惊人的', 4336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'certainty', 'n. 必然的事， 确定的事实； 确信， 确实', 4337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'corrode', 'v. 腐蚀， 侵蚀', 4338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'spine', 'n. 脊柱， 脊椎； 刺， 刺毛； 书脊', 4339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'commend', 'vt. 称赞， 表扬； 推荐', 4340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'parasite', 'n. 寄生生物； 寄生虫', 4341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'artificial', 'adj. 人工的， 人为的； 矫揉造作的； 模拟的', 4342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'deficiency', 'n. 缺乏， 不足； 缺点， 缺陷', 4343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'imaginary', 'adj. 想象中的， 假想的', 4344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'formula', 'n. 公式， 式； 原则， 方案； 配方', 4345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'disgust', 'n&vt. 厌恶， 憎恶', 4346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'transcend', 'vt. 超出， 超越范围', 4347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'tribute', 'n. 颂词， 称赞， 礼物； 贡品', 4348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mob', 'n. 暴民，乌合之众 vt. 成群围住， 聚众袭击', 4349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'subordinate', 'adj. 下级的，级别低的；次要的，从属的 n. 部属， 下级 vt. 使处于次要地位， 使从属于', 4350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'trend', 'vi. 伸向，倾向 n. 倾向', 4351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'achievement', 'n. 完成； 成就， 成绩', 4352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sturdy', 'adj. 强壮的， 结实的， 坚固的； 坚定的， 坚强的', 4353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'desirable', 'adj. 吸引人的， 可取的', 4354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'consist', 'vi. 由…组成； 在于； 一致', 4355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reliable', 'adj. 可靠的， 可依赖的', 4356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'compatible', 'adj. 兼容的； 能和睦相处的， 合得来的', 4357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'incentive', 'n. 刺激， 鼓励', 4358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'critic', 'n. 批评家， 爱挑剔的人', 4359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'preliminary', 'adj. 预备的，初步的 n. 初步做法， 起始行为', 4360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'obstacle', 'n. 障碍， 障碍物； 妨害', 4361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'profession', 'n. 职业； 公开表示', 4362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'van', 'n. 大篷车， 运货车', 4363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'dizzy', 'adj. 头晕目眩的，眩晕的；头晕的 vt. 令人发晕', 4364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'resemblance', 'n. 相似， 形似', 4365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'exceptional', 'adj. 优越的， 杰出的； 例外的， 独特的， 异常的', 4366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'constitute', 'vt. 组成， 形成； 设立； 任命', 4367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cherish', 'vt. 珍爱， 珍视； 爱护， 抚育； 抱有， 怀有', 4368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'discrepancy', 'n. 不符合， 不一致', 4369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'spectrum', 'n. 谱， 光谱， 频谱； 范围， 幅度， 系列', 4370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'convince', 'vt. 使确信， 使信服， 说服', 4371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'prolong', 'vt. 延长， 拉长， 拖延', 4372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'missionary', 'n. 传教士', 4373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'terminate', 'v. 停止， 终止', 4374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'valve', 'n. 阀， 活门； 瓣膜， 活瓣', 4375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'refund', 'n. 退款 vt. 退还', 4376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'remnant', 'n. 残留部分', 4377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'internal', 'adj. 内的， 国内的； 内心的', 4378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'literary', 'adj. 文学的； 文人的， 书卷气的', 4379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'classical', 'adj. 古典的， 经典的', 4380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'privilege', 'n. 特权； 优惠', 4381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'substitute', 'n. 代替人，代用品 vt. 用…代替', 4382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mortgage', 'n. 抵押，抵押借款 vt. 抵押', 4383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'blaze', 'vi. 熊熊燃烧，着火；发光，放光彩；迸发，爆发 n. 火焰， 烈火； 光辉， 强烈的光； 迸发， 爆发； 灿烂， 炫耀', 4384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'moreover', 'adv. 而且， 再者， 此外', 4385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'scatter', 'vt. 撒， 散播； 使散开， 驱散', 4386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'violate', 'vt. 违反， 违背； 亵渎； 侵犯， 妨碍', 4387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'federal', 'adj. 联邦的， 联盟的', 4388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'verify', 'vt. 证实， 查证， 证明', 4389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'excursion', 'n. 远足， 短途旅行', 4390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'inaugurate', 'vt. 开始， 开展； 为…举行就职典礼； 为…举行开幕式， 为…举行落成仪式', 4391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'undergo', 'vt. 经历； 经受， 忍受', 4392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reward', 'n. 报答，奖赏；报酬，酬金 vt. 报答， 酬谢， 奖励', 4393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'graze', 'vi. 吃青草 vt. 放牧；擦伤；擦过，掠过 n. 擦破', 4394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'coupon', 'n. 礼券， 优惠券； 配给券， 票证', 4395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'multitude', 'n. 大量， 许多； 大众， 民众', 4396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'inhabit', 'vt. 居住于， 栖居于', 4397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'siege', 'n. 包围， 围困', 4398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'abstract', 'adj. 抽象的，抽象派的 n. 摘要，梗概；抽象派艺术作品', 4399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'agenda', 'n. 议程', 4400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'degenerate', 'vi. 衰退，堕落，蜕化 adj. 衰退的，堕落的 n. 堕落者', 4401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'nurture', 'n&vt. 养育， 培育， 滋养', 4402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'destructive', 'adj. 破坏的， 毁灭的', 4403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'appearance', 'n. 出现， 来到； 外观', 4404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'culture', 'n. 文化， 文明； 教养； 培养； 培养菌', 4405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'paternity', 'n. 父权， 父子关系', 4406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'hasty', 'adj. 草率的， 轻率的； 急速的， 匆忙的， 仓促完成的', 4407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'anonymous', 'adj. 无名的， 不具名的； 匿名的； 无特色的， 无个性特征的', 4408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fake', 'adj. 假的，伪造的 n. 假货；骗子 vt. 伪造， 捏造； 伪装', 4409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'span', 'n. 跨距，一段时间 vt. 持续， 贯穿， 包括； 横跨， 跨越', 4410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'escort', 'n. 护卫者，护送者 vt. 护送， 护卫', 4411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'bizarre', 'adj. 奇形怪状的， 怪诞的', 4412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'existence', 'n. 存在， 实在； 生存', 4413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ascribe', 'vt. 把…归因于， 把…归属于', 4414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'threshold', 'n. 门槛， 门口； 入门， 开端， 起始点', 4415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'float', 'v. 浮动， 漂浮， 飘动', 4416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'minority', 'n. 少数； 少数民族', 4417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'axis', 'n. 轴， 轴线， 中心线； 坐标轴， 基准线', 4418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pole', 'n. 杆； 极， 磁极， 电极', 4419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'preferable', 'adj. 更可取的， 更好的， 更合意的', 4420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'reference', 'n. 提到， 论及； 参考， 查阅； 引文； 参考书目； 证明书， 推荐信', 4421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'spite', 'n. 恶意，怨恨；不顾 vt. 刁难， 欺侮', 4422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'defendant', 'n. 被告', 4423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'arrange', 'v. 安排， 准备； 整理', 4424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'olive', 'n. 橄榄， 橄榄树', 4425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'coarse', 'adj. 粗的， 粗糙的； 粗劣的； 粗俗的', 4426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'exaggerate', 'v. 夸大， 夸张', 4427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'streamline', 'vt. 使成流线型； 精简， 使效率更高', 4428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'imply', 'vt. 暗示， 意指', 4429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'offset', 'vt. 补偿， 抵消', 4430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'commitment', 'n. 承诺， 许诺， 保证； 信奉， 献身； 承担的义务', 4431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'cavity', 'n. 洞， 穴， 凹处； 龋洞', 4432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'coward', 'n. 胆小鬼， 懦夫', 4433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fossil', 'n. 化石； 食古不化的人， 老顽固', 4434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'poke', 'vi. 伸出，突出 vt. 戳，捅；用…戳，把…戳向；伸出，突出 n. 戳， 捅', 4435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'rejection', 'n. 拒绝', 4436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fixture', 'n. 固定装置； 固定在某位置的人', 4437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'manufacture', 'vt. 制造，加工 n. 制造， 制造业', 4438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'collision', 'n. 碰撞； 冲突， 抵触', 4439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sequence', 'n. 连续， 接续， 一连串； 次序， 顺序', 4440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'recruit', 'vt. 招募， 吸收', 4441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'provision', 'n. 供应； 准备， 预备； 条款， 规定； 给养， 口粮', 4442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'calorie', 'n. 大卡； 卡', 4443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'slogan', 'n. 标语， 口号； 广告语', 4444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'invariably', 'adv. 不变地， 始终如一地， 总是', 4445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'commence', 'v. 开始', 4446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'tract', 'n. 传单， 小册子； 大片', 4447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'configuration', 'n. 配置， 布局， 构造', 4448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'mercury', 'n. 水银， 汞', 4449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'frequent', 'adj. 时常发生的， 常见的', 4450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'chunk', 'n. 厚片， 大块； 相当大的部分', 4451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'interact', 'vi. 相互作用， 相互影响', 4452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'commonplace', 'adj. 普通的，平庸的 n. 寻常的事物， 平庸的东西', 4453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'aggregate', 'adj. 总计的， 合计的 n. 总数，合计 vt. 总计达， 合计； 使聚集， 使积聚', 4454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'seemingly', 'adv. 表面上， 看上去', 4455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'attendant', 'adj. 伴随的， 随之产生的 n. 服务人员，侍者，随从', 4456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'array', 'n. 展示；陈列，一系列；排列，队形；衣服，盛装；', 4457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'parameter', 'n. 界限， 范围； 参数', 4458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'extinct', 'adj. 灭绝的， 绝种的； 不再活跃的， 熄灭了的， 已废弃的', 4459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'discriminate', 'vi. 区别， 辨别； 有差别地对待， 歧视', 4460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'degrade', 'vt. 降低…的身份， 有辱…的人格； 使降解， 使退化', 4461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'opaque', 'adj. 不透明的， 不透光的； 难理解的， 晦涩的', 4462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'repay', 'vt. 归还； 报答', 4463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'monetary', 'adj. 钱的， 货币的； 金融的', 4464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'grave', 'adj. 严重的， 严肃的 n. 坟墓', 4465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'advantage', 'n. 优点， 优势； 好处', 4466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'controversy', 'n. 争论， 辩论', 4467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'command', 'n&vt. 命令， 指挥； 控制', 4468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'compulsory', 'adj. 必须做的， 强制性的； 必修的', 4469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'performance', 'n. 演出； 履行， 执行， 完成； 工作情况， 表现， 工作性能', 4470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'serial', 'adj. 连续的， 顺序排列的 n. 连续剧，连载故事', 4471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'anticipate', 'vt. 预料， 预期， 期望； 先于…行动， 提前使用', 4472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'detach', 'vt. 拆卸； 使分开， 使分离', 4473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'slash', 'vt. 砍；大幅度削减 n. 砍， 砍痕； 斜线号', 4474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'fabricate', 'vt. 捏造， 伪造， 编造； 建造', 4475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'comic', 'adj. 喜剧的，滑稽的 n. 连环漫画； 喜剧演员', 4476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'perfection', 'n. 完美， 完善', 4477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'vague', 'adj. 不明确的； 含糊的； 暧昧的', 4478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'pope', 'n. 教皇， 罗马主教', 4479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'exception', 'n. 例外， 除外', 4480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'ego', 'n. 自我， 自己， 自尊', 4481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'urge', 'vt. 鼓励；推进，催促；竭力主张，强烈要求 n. 冲动， 强烈的欲望', 4482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'spouse', 'n. 配偶', 4483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'score', 'n. 得分，比数，成绩；二十 vt. 分， 给…打分； 画线于； 获胜', 4484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'isle', 'n. 小岛， 岛', 4485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'enclosure', 'n. 四周有篱笆的场地， 围场； 附件', 4486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'graduate', 'adj. 研究生的 v. 毕业 n. 毕业生；研究生', 4487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'famine', 'n. 饥荒； 严重的缺乏', 4488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'quota', 'n. 定额， 限额， 配额', 4489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'unanimous', 'adj. 全体一致的， 一致同意的', 4490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'scorn', 'n. 轻蔑，鄙视 vt. 轻蔑， 鄙视； 拒绝， 不屑', 4491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'thermal', 'adj. 热的， 由热造成的； 保暖的', 4492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'sulfur', 'n. 硫', 4493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'visual', 'adj. 看的， 视觉的', 4494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'terrain', 'n. 地形， 地势', 4495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'grief', 'n. 悲伤， 悲痛； 悲伤的事， 悲痛的缘由', 4496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'rap', 'vi. 说唱 vt. 敲击，急敲；突然厉声说出；责备，训斥 n. 敲击， 急敲', 4497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'upgrade', 'vt. 提升，使升级 n. 向上的斜坡', 4498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'instruct', 'vt. 教， 指示； 通知； 教育', 4499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (8, 'appendix', 'n. 阑尾； 附录', 4500);
