INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artistry', 'n. 艺术之性质', 5501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knowledgeable', 'adj. 知识渊博的, 有见识的', 5502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cannon', 'n. 大炮, 加农炮 v. 炮轰', 5503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recede', 'v. 后退', 5504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'organically', 'adv. 器官上地, 有机地', 5505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unintentionally', 'adv. 无意地,非故意地', 5506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geomagnetic', 'adj. 地磁的,地磁气的', 5507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnetize', 'v. 使磁化, 吸引', 5508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recess', 'n. (墙壁等的)凹进处 v. 使凹进,休假', 5509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bonito', 'n. 鲣', 5510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hatchling', 'n. 人工孵化的鱼苗或小鸟', 5511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'specialist', 'n. 专门医师, 专家', 5512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vocal', 'adj. 声音的,有声的 n. 元音', 5513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hilly', 'adj. 多小山的, 多坡的', 5514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elongate', 'v. 拉长, (使)伸长 adj. 伸长的', 5515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linoleum', 'n. 油布, 油毯', 5516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'armor', 'n. 装甲 v. 为…装甲', 5517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'customarily', 'adv. 通常,习惯上', 5518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprehensive', 'adj. 全面的,能充分理解的', 5519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'franklin', 'n. 小地主, 乡绅', 5520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morally', 'adv. 道德上', 5521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lathe', 'n. 车床 vt. 用车床加工', 5522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inherent', 'adj. 固有的,与生俱来的', 5523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grand', 'adj. 盛大的,极重要的', 5524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inconspicuous', 'adj. 不显眼的,不引人注意的', 5525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'integrity', 'n. 正直, 诚实, 完整', 5526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enroll', 'v. 登记, 招收, 参加', 5527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utterance', 'n. 意见, 说话, 发表', 5528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'treasury', 'n. 财政部, 国库', 5529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apparatus', 'n. 器械, 设备, 仪器', 5530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heartbeat', 'n. 心跳', 5531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mast', 'n. 桅,桅杆 vt. 装桅杆于', 5532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unify', 'v. 统一,使成一体', 5533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scat', 'v. 迅速走开 n. 爵士音乐中无意义的音节的演唱', 5534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unexplored', 'adj. [地质] 未勘查过的', 5535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'playground', 'n. 运动场, 操场', 5536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upland', 'n. 丘陵地, 高地 adj. 高地的,山地的', 5537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'woodpecker', 'n. [鸟]啄木鸟', 5538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'friendliness', 'n. 友谊,友善', 5539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sympathy', 'n. 同情, 同情心', 5540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wingspan', 'n. [空]翼展', 5541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counter', 'n. 计算器,柜台 ad&prep. 相反地', 5542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'campus', 'n. <美>校园,大学教育', 5543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flicker', 'n&v. 闪烁,摇曳', 5544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'approve', 'v. 赞成, 批准', 5545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anvil', 'n. [解]砧骨', 5546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proximity', 'n. 接近, 亲近', 5547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excellence', 'n. 优秀, 卓越', 5548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loggerhead', 'n. 傻子,铁球棒', 5549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pertain', 'v. 适合, 属于', 5550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demonstration', 'n. 示范, 实证', 5551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dike', 'n. 堤防 v. 筑堤提防', 5552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ineffective', 'adj. 无效的, (指人)工作效率低的', 5553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explosive', 'adj. 爆炸(性)的,暴露 n. 爆炸物', 5554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rooftop', 'n. 屋顶 adj. 屋顶上的', 5555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interplanetary', 'adj. 太阳系内的,行星间的', 5556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'actor', 'n. 男演员,行动者', 5557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lovely', 'adj. 可爱的,有趣的', 5558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caput', 'n. 头, 首', 5559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receptiveness', 'n. 感受性,接受能力', 5560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'punish', 'v. 惩罚,处罚', 5561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'animate', 'v. 鼓舞 adj. 生气勃勃的', 5562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'militaristic', 'adj. 军国主义的', 5563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acreage', 'n. 英亩数, 面积', 5564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impersonation', 'n. 扮演', 5565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reabsorb', 'v. 再吸附,重吸收', 5566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interference', 'n. 冲突, 干涉', 5567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overturn', 'n. 倾覆, 破灭 v. 推翻, 颠倒', 5568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duke', 'n. 公爵', 5569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squarely', 'adv. 方形地, 直角地', 5570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Henderson', 'n. 亨德森（姓氏）', 5571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pronoun', 'n. 代名词', 5572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prisoner', 'adj. 囚犯的 n. 战俘', 5573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'October', 'n. 十月(略作Oct)', 5574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rawhide', 'n. 生牛皮 vt. 用生牛皮鞭抽打 adj. 生牛皮的', 5575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonagricultural', 'adj. 非农业的', 5576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dale', 'n. 宽谷, 溪谷', 5577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'devastation', 'n. 毁坏,荒废', 5578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fletcher', 'n. <古>造箭者,弗莱彻', 5579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paradoxically', 'adv. 相矛盾地,似非而是地', 5580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credible', 'adj. 可信的,可靠的', 5581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flute', 'n. 长笛 v. 吹长笛,刻槽', 5582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'automate', 'v. 使自动化, 自动操作', 5583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pedagogy', 'n. 教学, 教授', 5584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pregnant', 'adj. 怀孕的, 重要的', 5585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trait', 'n. 显著的特点, 特性', 5586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autonomy', 'n. 自治', 5587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exuberant', 'adj. 繁茂的,生气勃勃的', 5588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'option', 'n. 选项, 选择权', 5589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reaper', 'n. 收割者, 收割机', 5590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anxiously', 'adv. 忧虑地, 不安地', 5591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elephant', 'n. 象', 5592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plague', 'n. 瘟疫,麻烦 v. 折磨, 使苦恼', 5593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bellow', 'v. 怒吼, 咆哮', 5594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unreal', 'adj. 不真实的, 虚幻的', 5595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fond', 'adj. 喜欢的,温柔的', 5596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toad', 'n. [动]蟾蜍', 5597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heave', 'v. 举起 n. 举起,投掷', 5598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'parade', 'n. 游行,炫耀 v. 游行,炫耀', 5599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'receptive', 'adj. 善于接受的,能容纳的', 5600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scope', 'n. (活动)范围', 5601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unplanned', 'adj. 意外的,在计划外的', 5602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'longevity', 'n. 长命, 寿命', 5603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submit', 'v. (使)服从,递交', 5604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nomad', 'n. 游牧部落的人,流浪者 adj. 游牧的', 5605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Mongolia', 'n. 蒙古', 5606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clarity', 'n. 清楚,透明', 5607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sexually', 'adv. 性别地,两性之间地', 5608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lifeway', 'n. 生活方式, 生活', 5609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facade', 'n. 正面', 5610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'torrid', 'adj. 晒热的,热情的', 5611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kindergarten', 'n. 幼儿园 adj. 幼儿园的,启蒙阶段的', 5612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neuron', 'n. [解]神经细胞,神经元', 5613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transmission', 'n. 播送, 发射', 5614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eukaryote', 'n. 〈生〉真核细胞', 5615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commensal', 'adj. 共餐的 n. 共食伙伴, 共生物', 5616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'living', 'n. 生活,生计 adj. 活的,逼真的', 5617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inadvertently', 'adv. 非故意地,不注意地', 5618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volt', 'n. (马术中的)环骑,[电工]伏特', 5619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roadbed', 'n. 路基', 5620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encompass', 'v. 包围,环绕', 5621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outnumber', 'v. 数目超过, 比多', 5622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scar', 'n. 伤痕,疤痕 v. 结疤,使留下伤痕', 5623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metabolize', 'v. 产生代谢变化', 5624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'administer', 'v. 管理, 给予, 执行', 5625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fasten', 'v. 扎牢,扣住', 5626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diversify', 'v. 使多样化, 作多样性的投资', 5627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grumble', 'adj. 嘟囔地说 n. 怨言 v. 发牢骚', 5628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'degradation', 'n. 降级, 降格, 退化', 5629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neurospora', 'n. [微]脉孢菌', 5630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsidy', 'n. 补助金,津贴', 5631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commonsense', 'adj. 常识的,具有常识的', 5632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destination', 'n. 目的地', 5633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yellowstone', 'n. 黄石国家公园, 黄石河', 5634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mosquito', 'n. 蚊子', 5635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paucity', 'n. 极小量', 5636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infect', 'v. [医] 传染, 感染', 5637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burin', 'n. 冰凿,雕刻刀', 5638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'walrus', 'n. [动]海象, 海象胡须', 5639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deserve', 'v. 应受, 值得', 5640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incubator', 'n. 培养的器具, 孵卵器', 5641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poorhouse', 'n. 救济院', 5642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsidize', 'v. 资助,津贴', 5643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excitation', 'n. 刺激,兴奋, 激动', 5644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amniotic', 'adj. [昆] 羊膜的', 5645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'porpoise', 'n. [动]海豚, 小鲸', 5646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spew', 'v. 喷涌,呕吐', 5647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emanate', 'v. 散发,发出', 5648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noxious', 'adj. 有害的', 5649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deviate', 'v. 偏离,偏轨', 5650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shun', 'v. 避开,避免', 5651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'individually', 'adv. 个别地,单独地', 5652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggregation', 'n. 集合,集合体', 5653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erectus', 'adj. [拉丁语]直立的', 5654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sleepiness', 'n. 想睡,瞌睡', 5655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oneness', 'n. 单一,  统一', 5656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remainder', 'n. 残余, 剩余物 adj. 剩余的', 5657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'passive', 'adj. 被动的,消极的', 5658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excrete', 'v. 排泄, 分泌', 5659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'namely', 'adv. 即,也就是', 5660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infection', 'n. 传染病, 影响,', 5661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'piling', 'n. 打桩, 打桩工程', 5662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'button', 'n. 钮扣 v. 扣住,扣紧', 5663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'workforce', 'n. 劳动力,职工总数', 5664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'analyst', 'n. 分析家, 分解者', 5665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gradient', 'adj. 倾斜的 n. 梯度,坡度', 5666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brace', 'n. 支柱 v. 支住,撑牢', 5667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quest', 'n. 寻求 v. 追求,探索', 5668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regulator', 'n. 调整者,调整器', 5669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toolmaking', 'n. 工具(或刀具)制造,机床维修', 5670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'essay', 'n. 散文', 5671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morphology', 'n. [生物]形态学, [语法]词法', 5672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hiccup', 'n. 打嗝 v. 打嗝', 5673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sow', 'n. 大母猪 v. 播种,散布', 5674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'platypus', 'n. [动]鸭嘴兽', 5675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nurse', 'n. 护士,保姆 v. 护理,照料', 5676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'damp', 'n. 湿气 adj. 潮湿的 v. 使潮湿,阻尼', 5677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'halite', 'n. [化]岩盐', 5678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subsist', 'v. 生存, 存在, 供养', 5679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'straighten', 'v. (使)弄直, 伸直', 5680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'July', 'n. 七月(略作Jul)', 5681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lump', 'n. 肿块,笨人 v. 使成块状', 5682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balloon', 'n. 气球 v. 膨胀', 5683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteorologist', 'n. 气象学者', 5684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rust', 'n. 铁锈 v. (使)生锈,锈蚀', 5685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undeveloped', 'adj. 不发达的, 未开发的', 5686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conestoga', 'n. 一种大篷马车', 5687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unexpectedly', 'adv. 出乎意料地,意外地', 5688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disappearance', 'n. 不见,消失', 5689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abrupt', 'adj. 突然的,陡峭的,生硬的', 5690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nowcasting', 'n. 预告', 5691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'readership', 'n. 读者的身分, 读者人数', 5692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pencil', 'n. 铅笔', 5693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wharf', 'n. 码头 v. 靠在码头', 5694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'individuality', 'n. 个性,(通常用复数)个人的嗜好', 5695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squander', 'v. 浪费 n. 浪费', 5696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cheese', 'n. 干酪', 5697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mesopotamian', 'n. 美索不达米亚（两河流域）', 5698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'birdlike', 'adj. 敏捷轻快的,似鸟的', 5699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'somerset', 'n. 翻筋斗 vi. 翻筋斗', 5700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appetite', 'n. 食欲,欲望', 5701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrink', 'v. 收缩, (使)皱缩 n. 收缩', 5702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dampen', 'v. 使潮湿,沮丧', 5703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'textural', 'adj. 组织的,结构的', 5704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ribbon', 'n. 缎带,丝带 v. 撕成条', 5705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'derrick', 'n. 起重机, (钻井)井口上的铁架塔', 5706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phoenix', 'n. 凤凰,完人', 5707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impersonal', 'adj. 客观的,没有人情味的', 5708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secular', 'adj. 长期的,世俗的', 5709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onward', 'adj. 向前的 adv. 向前,在前面', 5710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expend', 'v. 花费,消耗,支出', 5711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imaginary', 'adj. 假想的,虚构的', 5712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinetic', 'adj. (运)动的,动力(学)的', 5713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commitment', 'n. 委托事项,许诺', 5714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pluto', 'n. 冥王星, 阴间之神', 5715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chicopee', 'n. 奇科皮（美国马萨诸塞州西南部城市）', 5716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seaport', 'n. 海港, 港口都市', 5717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patchy', 'adj. 补丁的, 不调和的', 5718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sacred', 'adj. 神的,害怕的', 5719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clinical', 'adj. 临床的,诊所的', 5720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verbalize', 'v. 用语言描述,累赘', 5721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generator', 'n. 发电机, 发生器', 5722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uphold', 'v. 支持, 赞成', 5723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fare', 'n. 费用,票价 v. 遭遇, 进展', 5724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cellulose', 'n. 纤维素,（植物的）细胞膜质', 5725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Patricia', 'n. 帕特丽夏（女子名）', 5726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yam', 'n. 山药, 洋芋', 5727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sharper', 'n. 磨具,(赌博中的)骗子', 5728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'candlelight', 'n. 烛火,黄昏', 5729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allocation', 'n. 分配,安置', 5730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vantage', 'n. 优势,有利情况', 5731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flowerbed', 'n. 花床,花圃', 5732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'debatable', 'adj. 成问题的,未决定的', 5733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'petrochemical', 'adj. 石化的 n. 石化产品', 5734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'objectify', 'v. 使客观化,具体化', 5735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alternatively', 'adv. 做为选择,二者择一地', 5736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lawn', 'n. 草坪, (均匀生长于固体培养基的)菌苔', 5737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intelligible', 'adj. 可理解的,明了的', 5738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deviation', 'n. 背离,偏离', 5739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacate', 'v. 腾出, 空出,离(职),退(位)', 5740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subtropic', 'adj. 亚热带的,副热带的', 5741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scenic', 'adj. 舞台的, 景色优美的 n. 风景照片', 5742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comic', 'n. 滑稽演员 adj. 滑稽的, 喜剧的', 5743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tusk', 'n. 长牙 v. 以牙刺戳', 5744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meaty', 'adj. 肉的,多肉的', 5745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resilient', 'n. 帕特森（美国一座城市）', 5746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indigestible', 'adj. 不吸收的,难理解的', 5747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subtitle', 'n. 说明对白的字幕 v. 给…加字幕', 5748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prolifically', 'adj. 丰富地,多产地', 5749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elevator', 'n. 电梯,升降机', 5750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigidity', 'n. 刻板,严格', 5751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soar', 'v. 高飞,昂扬 n. 高涨程度', 5752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dismantle', 'v. 拆除', 5753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refinery', 'n. 精炼厂', 5754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'riverbank', 'n. 河堤, 河岸', 5755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landslip', 'n. [地]山崩,塌方', 5756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ephemeral', 'adj. 朝生暮死的, 短暂的', 5757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clerk', 'n. 职员, 办事员', 5758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monotonous', 'adj. 单调的,无抑扬顿挫的', 5759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aquatic', 'adj. 水的,水生的 n. 水生动物', 5760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vibration', 'n. 振动,颤动', 5761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loop', 'n. 环,回路 v. 使成环,打环', 5762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unionization', 'n. 联合, 结合', 5763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aboveground', 'adj. 在地面上的 adv. 地面上地', 5764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encroachment', 'n. 侵蚀, 侵犯', 5765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'semicircular', 'adj. 半圆的', 5766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'handsome', 'adj. 英俊的,大方的', 5767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snout', 'n. 猪嘴,鼻子', 5768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weightlessness', 'n. 无重状态', 5769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suggestive', 'adj. 提示的,暗示的', 5770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rougher', 'n. 粗切机,粗选槽', 5771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peat', 'n. 泥煤, 泥炭块', 5772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mystique', 'n. 神秘性,奥秘', 5773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lengthwise', 'adj. 纵长的 adv. 纵长地', 5774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensation', 'n. 感觉,感情', 5775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Victorian', 'adj. 维多利亚女王时代的', 5776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contend', 'v. 斗争, 竞争, 主张', 5777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grace', 'n. 优美, 雅致 v. 使优雅', 5778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Chile', 'n. 智利', 5779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hander', 'n. 支持器,夹头', 5780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ninety', 'num. 九十', 5781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alpha', 'n. 希腊字母的第一个字母', 5782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slumber', 'n. 睡眠 v. 睡眠', 5783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dart', 'n. 标枪, 镖 v. 投掷', 5784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevalence', 'n. 流行,普遍', 5785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cousin', 'n. 堂兄弟姊妹, 表兄弟姊妹', 5786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negligible', 'adj. 可以忽略的, 不予重视的', 5787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'finite', 'adj. 有限的,限定的', 5788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sleeper', 'n. 睡眠,枕木', 5789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonizer', 'n. 殖民者,殖民地开拓者, 移民', 5790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'welland', 'n. 韦兰（加拿大东南部港口城市）', 5791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unmatched', 'adj. 无与伦比的,不相配的', 5792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutritive', 'adj. 营养的 n. 营养物', 5793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revision', 'n. 修订,修正,修订本', 5794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inception', 'n. 起初, 获得学位', 5795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clearing', 'n. 结算,空旷地 vi. 澄清', 5796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morris', 'n. 莫理斯舞(英国传统民间舞蹈)', 5797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonfiction', 'n. 非小说的散文文学', 5798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'straightforward', 'adj. 正直的,简单的 adv. 坦率地', 5799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brilliantly', 'adv. 辉煌地,灿烂地', 5800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bull', 'n. [动]公牛, 粗壮如牛的人', 5801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eighty', 'num. 八十, 八十个', 5802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flexibly', 'adv. 易曲地, 柔软地', 5803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sandal', 'n. 凉鞋, 檀香', 5804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cumulative', 'adj. 累积的', 5805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creep', 'v. 爬, 蹑手蹑脚 n. 爬行', 5806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tan', 'n. 日晒后的颜色 adj. 棕褐色的 v. 晒成褐色', 5807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wisdom', 'n. 智慧,学识', 5808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigor', 'n. 严格,精确', 5809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grotto', 'n. 洞穴,人工洞室', 5810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'salad', 'n. 色拉', 5811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prostrate', 'adj. 降伏的,俯卧的 v. 使屈服', 5812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protector', 'n. 保护者', 5813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bode', 'v. 预示', 5814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'club', 'n. 俱乐部,(扑克牌)梅花 v. 募集', 5815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hump', 'n. 驼峰,峰丘 v. (使)隆起', 5816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blaze', 'n. 火焰 v. 照耀,激发', 5817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indecipherable', 'adj. 无法解释的,难辨认的', 5818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substantiate', 'v. 使实体化,证实', 5819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ghost', 'n. 鬼, 幽灵', 5820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faint', 'n. 昏晕 v. 昏晕 adj. 头晕的', 5821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Peru', 'n. 秘鲁', 5822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diva', 'n. 歌剧中的首席女主角', 5823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonstop', 'adj. 不断的,直达的 adv. 不休息地', 5824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bifocal', 'adj. 双焦点的', 5825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cougar', 'n. [动]美洲狮(尤指Felis concolor)', 5826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'versatile', 'adj. 多才多艺的,万能的', 5827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smear', 'v. 涂污,弄脏 n. 油迹, 涂片', 5828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ocher', 'n. 黄土, 赭土', 5829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mentally', 'adv. 精神上, 智力上', 5830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obliterate', 'v. 涂去, 删除, 使湮没', 5831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aspiration', 'n. 热望, 渴望', 5832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conceivable', 'adj. 可能的,想得到的', 5833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'internationally', 'adv. 国际性地, 在国际间', 5834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'greenish', 'adj. 呈绿色的', 5835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'succinct', 'adj. 简洁的, 紧身的', 5836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midway', 'n. 中途,半路 adj. 中途的 adv. 在中途', 5837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsung', 'adj. 未唱的,未赞颂的', 5838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fungicide', 'n. 杀真菌剂', 5839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'popularize', 'v. 普及', 5840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'changeable', 'adj. 可改变的,无常的', 5841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'responsive', 'adj. 响应的,应答的', 5842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amplify', 'v. 放大,详述', 5843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notebook', 'n. 笔记簿, 笔记本', 5844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pertinent', 'adj. 有关的,相干的', 5845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concise', 'adj. 简明的,简练的', 5846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utilization', 'n. 利用', 5847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theoretical', 'adj. 理论的,理论上的', 5848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'figural', 'adj. 借喻的,比喻的', 5849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'determinant', 'adj. 决定性的 n. 决定因素', 5850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overtax', 'v. 课税过重, 使负担过度', 5851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'youth', 'n. 青春,少年', 5852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'custodial', 'adj. 保管的,保管人的 n. [宗]圣物保管容器', 5853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'academician', 'n. 院士, 大学生', 5854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cole', 'n. 油菜, 小菜', 5855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flatter', 'v. 过分夸赞, 奉承,使满意', 5856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impressionistic', 'adj. 印象派的,给人深刻印象的', 5857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faction', 'n. 派别,小集团', 5858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortuitously', 'adv. 偶然地,意外地', 5859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thriller', 'n. 使人毛骨悚然的东西, 使人毛骨悚然的小说', 5860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plentifully', 'adv. 丰富地,富裕地', 5861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monopolize', 'v. 独占, 垄断', 5862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burden', 'n. 担子, 负担 v. 烦扰', 5863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breadbasket', 'n. <俚>胃, 腹', 5864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'annihilate', 'v. 消灭,湮灭', 5865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sectional', 'adj. 可组合的,部分的', 5866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jealousy', 'n. 嫉妒,猜疑', 5867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'garbage', 'n. 垃圾, 废物', 5868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'routinely', 'adv. 例行公事地', 5869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predicament', 'n. 困境,窘状', 5870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thermometer', 'n. 温度计, 体温计', 5871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'divergence', 'n. 分歧', 5872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oceanography', 'n. 海洋学', 5873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outbuilding', 'n. [建]外屋, (指车库, 谷仓等)', 5874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forbes', 'n. 福布斯（美国著名财经杂志）', 5875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grama', 'n. 美国西部产的一种牧草', 5876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhyolite', 'n. [地]流纹岩', 5877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decisive', 'adj. 决定性的,果断的', 5878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comparably', 'adv. 同等地,可比较地', 5879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transmitter', 'n. 转送者,传导物,发射机', 5880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exponential', 'n. 指数 adj. 指数的, 幂数的', 5881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gesso', 'n. (雕刻、绘画用的)石膏, 石膏粉', 5882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attendant', 'n. 服务员 adj. 伴随的', 5883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capitalism', 'n. 资本主义', 5884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deference', 'n. 顺从, 尊重', 5885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cumbersome', 'adj. 笨重的,累赘的', 5886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weft', 'n. [纺]织物,信号旗', 5887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dire', 'adj. 可怕的,极端的', 5888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pendant', 'n. 垂饰, 下垂物', 5889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'basketmaking', 'n. 篮子编织', 5890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generalist', 'n. 多面手,通才', 5891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kennel', 'n. 狗窝 v. 置于狗窝,关进狗窝', 5892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postmaster', 'n. 邮局局长', 5893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interestingly', 'adv. 有趣地', 5894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perfume', 'n. 芳香,香水 v. 使发香,洒香水于', 5895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concomitant', 'adj. 伴随的 n. 伴随物', 5896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patient', 'n. 病人 adj. 耐心的', 5897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reckless', 'adj. 不计后果的,鲁莽的', 5898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rigidly', 'adv. 坚硬地, 严格地', 5899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renounce', 'v. 宣布放弃,断绝关系', 5900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overhang', 'v. 悬于之上,悬垂 n. 屋檐', 5901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'observatory', 'adj. 天文台,气象台', 5902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urbanism', 'n. 都市生活,都市化', 5903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refrigeration', 'n. 冷藏, 致冷', 5904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stuff', 'n. 原料,素材资料 v. 塞满', 5905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harshly', 'adv. 严厉地, 苛刻地', 5906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chitin', 'n. 壳质, 角素', 5907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polymer', 'n. 聚合体', 5908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Jules', 'n. 朱尔斯（男子名）', 5909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reviewer', 'n. 批评家,评论家', 5910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'triassic', 'adj. [地]三叠纪的 n. 三叠纪', 5911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adjunct', 'n. 附件, 助手 adj. 附属的', 5912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glasswork', 'n. 玻璃制品 v. 制成玻璃状的', 5913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sate', 'v. 使心满意足', 5914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flier', 'n. 飞行者,快车,宣传单', 5915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deplorable', 'adj. 可叹的,凄惨的', 5916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instructor', 'n. 教师,指导书', 5917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midday', 'n. 正午', 5918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auto', 'n. 自动,<美口>汽车', 5919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loneliness', 'n. 孤独, 寂寞', 5920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hopeless', 'adj. 没有希望的,不可救药', 5921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interchangeable', 'adj. 可互换的,可交换的', 5922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bizarre', 'adj. 奇异的(指态度,容貌,款式等)', 5923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laundry', 'n. 洗衣店, 要洗的衣服', 5924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'definitive', 'adj. 最后的,确定的', 5925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puncture', 'n. 小孔 v. 刺破', 5926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glandular', 'adj. 腺的,腺状的', 5927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glycoside', 'n. [化]配醣, 配糖类', 5928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interactive', 'adj. 交互式的,相互作用的', 5929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preform', 'v. 预先形成 n. 粗加工的成品', 5930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unusable', 'adj. 不能用的,与众不同的', 5931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inducible', 'adj. 可诱导的,可导致的', 5932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sepal', 'n. 萼片', 5933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snippet', 'n. 小片, 片断', 5934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'correlate', 'v. 相互关联 adj. 相互关联的', 5935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beetle', 'n. 甲虫', 5936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glycoprotein', 'n. [化]糖蛋白类, 醣蛋白', 5937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cardiac', 'n. 强心剂 adj. 心脏的, (胃的)贲门的', 5938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glial', 'adj. 神经胶质的', 5939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'autonomic', 'adj. 自治的, 自律的', 5940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ending', 'n. 结尾, 结局', 5941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preoccupation', 'n. 全神贯注,当务之急', 5942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coyote', 'n. 一种产于北美大草原的小狼, 山狗', 5943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endowment', 'n. 捐赠,天资,捐款', 5944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puddle', 'n. 水坑, 泥潭 v. 搅浊,搅泥泞', 5945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flare', 'n. 闪光, 闪耀 v. 闪光,闪耀', 5946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proboscis', 'n. 鼻子,[昆] 喙', 5947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crimson', 'adj. 深红色的 v. 变深红色 n. 深红色', 5948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhaustion', 'n. 耗尽枯竭,疲惫,竭尽', 5949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'winner', 'n. 胜利者,优胜者', 5950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anthropological', 'adj. 人类学的,人类学上的', 5951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sticky', 'adj. 粘的, 粘性的', 5952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'structurally', 'adv. 在结构上', 5953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wholesome', 'adj. 有益的,健康的,健全的', 5954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polyphony', 'n. 复调音乐, 多音', 5955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cornet', 'n. 圆锥形纸袋, 短号', 5956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maize', 'n. 玉米, 黄色 adj. 玉米色的', 5957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chivalry', 'n. 骑士精神, 骑士制度', 5958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unadorned', 'adj. 朴素的,未装饰的', 5959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brave', 'adj. 勇敢的', 5960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compatible', 'adj. 谐调的,兼容的', 5961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hotelkeeper', 'n. 旅馆经营者', 5962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inn', 'n. (尤指乡村或公路边的) 旅馆 vi. 住旅馆', 5963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multitude', 'n. 多数, 群众', 5964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paraphrase', 'v. 解释 n. 释义', 5965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unselfish', 'adj. 无私的,慷慨的', 5966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disco', 'n. 迪斯科舞厅', 5967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonself', 'n. (有机体的)异物', 5968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ragtime', 'n. 拉格泰姆音乐 adj. 使人发笑的', 5969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unrestricted', 'adj. 自由的,无限制的', 5970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quasar', 'n. 恒星状球体, 类星体', 5971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concertina', 'n. 类似风琴的六角形的乐器', 5972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bedroom', 'n. 卧室', 5973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quill', 'n. 羽茎,大翎毛 vt. 刺穿', 5974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bolster', 'n. 垫子 v. 支持', 5975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'halt', 'n. 停止,暂停 v. 停止,使立定', 5976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhale', 'v. 呼气,发出', 5977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'angstrom', 'n. [物理]埃(长度单位)', 5978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microscopy', 'n. 显微镜检查,显微镜使用', 5979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narcotic', 'n. 麻醉药,镇静剂 adj. 麻醉的', 5980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narcosis', 'n. 昏迷状态, 麻醉', 5981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complication', 'n. 复杂化, (使复杂的)因素', 5982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embolism', 'n. 加闰日, 栓塞', 5983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rupture', 'v. 破裂,裂开 n. 破裂, 决裂', 5984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abrasion', 'n. 磨损', 5985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proportionally', 'adv. 成比例地,相称地', 5986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virgo', 'n. 室女宫,室女(星)座', 5987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freighter', 'n. 货船,承运人', 5988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thinly', 'adv. 稀疏地,瘦', 5989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morality', 'n. 道德,品行', 5990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Andromeda', 'n. 埃塞俄比亚的公主, 仙女座', 5991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yardstick', 'n. <美> 码尺, 准绳', 5992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exalt', 'v. 晋升', 5993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monoxide', 'n. 一氧化物', 5994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comply', 'v. 顺从,答应', 5995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'owe', 'v. 欠(债等),感激', 5996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ingot', 'n. [冶]锭铁, 工业纯铁', 5997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'premature', 'adj. 未成熟的,早熟的', 5998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grievance', 'n. 委屈, 冤情, 不平', 5999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conjectural', 'adj. 推测的,好推测的', 6000);
