INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knead', 'v. 揉(面等)成团, 按摩', 9001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonchalant', 'adj. 若无其事的, 不关心的, 冷淡的', 9002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanlike', 'adj. 似人类的', 9003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boron', 'n. [化]硼', 9004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dump', 'v. 倾倒(垃圾), 倾卸 n. 堆存处', 9005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'topographically', 'adv. 地形地', 9006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mandatory', 'adj. 命令的, 托管的', 9007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scholarly', 'adj. 学者气质的, 学者风度的', 9008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offering', 'n. 提供, 奉献物', 9009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chlorine', 'n. [化]氯', 9010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bromine', 'n. [化]溴', 9011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gush', 'v. 涌出,滔滔不绝 n. 迸发', 9012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kea', 'n. 食肉鹦鹉', 9013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hillbilly', 'n. 山地内部的贫农,乡下人', 9014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pont', 'n. (南非的)缆拉渡船', 9015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resettle', 'v. (使)重新定居,再坐下来', 9016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pivotal', 'adj. 重要的, 轴的', 9017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untimely', 'a&ad. 不适时的, 不合时宜的', 9018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sack', 'n. 大袋, 大袋之量 v. 解雇, 洗劫', 9019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pointe', 'n. （芭蕾舞中的）足尖舞', 9020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'woodcutting', 'adj. 木雕的 n. 伐木, 木刻', 9021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chapter', 'n. (书籍)章,回', 9022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homely', 'adj. 家常的,平凡的', 9023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circulatory', 'adj. 循环的, 循环系统的', 9024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'variance', 'n. 不一致, 变化,', 9025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affiliate', 'v. 使隶属于 n. 附属机构', 9026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unquestioning', 'adj. 无条件的, 不犹豫的', 9027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'primatology', 'n. 灵长类动物学', 9028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demerit', 'n. 缺点,过失', 9029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inferiority', 'n. 自卑, 次等', 9030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tyrannical', 'adj. 暴虐的, 压制的, 残暴的', 9031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potentiality', 'n. (用复数)潜能,可能性', 9032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'applicability', 'n. 适用性, 适应性', 9033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enlightenment', 'n. 启迪, 教化', 9034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terrible', 'adj. 很糟的, 极坏的,骇人的', 9035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glossy', 'adj. 平滑的, 有光泽的', 9036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relevance', 'n. 中肯, 适当', 9037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wanderer', 'n. 流浪者, 徘徊者, 迷路的动物', 9038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebirth', 'n. 复活, 新生', 9039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unfertilized', 'adj. 未施肥的,  未受精的', 9040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untreated', 'adj. 未经处理的, 未经治疗的', 9041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'folklore', 'n. 民间传说, 民俗学', 9042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fumigate', 'v. 熏制, 以烟熏消毒', 9043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unverified', 'adj. 未经证实的,  未经核对的', 9044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'veil', 'n. 面纱 v. 遮蔽, 掩饰', 9045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncontested', 'adj. 无争论的, 无异议的', 9046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inspector', 'n. 检查员, 巡视员', 9047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nutritionist', 'n. 营养学家', 9048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dismal', 'adj. 阴沉的, 凄凉的n沼泽', 9049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thicken', 'v. (使)变厚, (使)变粗', 9050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'courageous', 'adj. 勇敢的', 9051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roe', 'n. 鱼卵,獐鹿', 9052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unrecognizable', 'adj. 未被承认的, 无法识别的', 9053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'soup', 'n. 汤', 9054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'directive', 'n. 指示 adj. 指导的', 9055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'september', 'n. 九月(略作Sep)', 9056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unreachable', 'adj. 不能到达的,  不能得到的', 9057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stew', 'v. 炖, 焖', 9058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slowness', 'n. 缓慢, 迟钝', 9059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slavery', 'n. 奴隶身分, 奴隶制度', 9060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herculean', 'adj. 极困难的,需要大力气的', 9061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colossal', 'adj. 巨大的,  <口>异常的', 9062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prudent', 'adj. 审慎的,小心谨慎的', 9063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liable', 'adj. 有责任的, 易的, 有倾向的', 9064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imprisonment', 'n. 关押,监禁', 9065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sour', 'adj. 酸的, 发酵的 v. 变酸', 9066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'treason', 'n. 叛逆, 通敌, 背信', 9067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wold', 'n. 无树木的山地, 荒野', 9068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abalone', 'n. [动]鲍鱼(软体动物)', 9069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mime', 'n. 哑剧 v. 做哑剧表演', 9070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dram', 'n. 液量特兰(药衡系统中的容量单位),  少量', 9071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'desperate', 'adj. 不顾一切的, 拚死的, 令人绝望的', 9072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retool', 'v. 将机械重新整备, 重组', 9073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urchin', 'n. 顽童, [动物]刺猥, [动物]海胆', 9074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'relational', 'adj. 有关系的, 亲属的', 9075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demobilize', 'v. 使复员, 使退伍, 遣散', 9076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bid', 'v. 出价, 投标 n. 投标,企图', 9077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'palimpsest', 'n. 重写本', 9078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hermetic', 'adj. 密封的, 与外界隔绝的', 9079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lust', 'n. 繁殖力, 强烈的性欲 v. 强烈欲望', 9080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'posthumously', 'adv. 在死后', 9081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outfit', 'n. 用具, 全套装配, vt配备, 装备', 9082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revolt', 'v& n. 反抗,反叛', 9083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maw', 'n. 动物的胃,口部', 9084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utmost', 'n. 极限, 最大可能 adj. 极度的, 最远的', 9085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bryn', 'n. 布琳', 9086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consistency', 'n. 坚固性, 浓度, 一致性', 9087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sentimentalism', 'n. 感情主义, 沉于情感', 9088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'philosophic', 'adj. 哲学的, 哲学家的', 9089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trilogy', 'n. 三部剧, 三部曲', 9090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diction', 'n. 措辞, 用语, 言语', 9091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stylish', 'adj. 时髦的, 漂亮的, 流行的', 9092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embarrass', 'v. 使困窘, 使局促不安', 9093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vocation', 'n. 召唤,天职,职业', 9094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arena', 'n. 竞技场, 舞台', 9095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waist', 'n. 腰部, 衣服的上身部分', 9096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irritate', 'v. 激怒, 使急躁', 9097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storehouses', 'n. 仓库,  储藏所,  宝藏', 9098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncharted', 'adj. 地图上没标明的,未知的', 9099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hanker', 'v. 渴望, 追求', 9100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rattlesnake', 'n. <美>[动]响尾蛇', 9101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glamorous', 'adj. 富有魅力的, 迷人的', 9102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brim', 'n. (杯, 碗等)边, 边缘 v. 注满', 9103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boot', 'n. <美> (长统)靴', 9104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'garb', 'n. 服装 v. 装扮', 9105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flannel', 'n. 法兰绒(衣服)', 9106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thigh', 'n. 大腿, 股', 9107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collarless', 'adj. 无领的,无马轭(或颈圈)的', 9108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cowhand', 'n. <美>(牧场的)牧牛工', 9109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taxonomy', 'n. 分类法, 分类学', 9110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrower', 'adj. 有限的, 精密的 n. 海峡', 9111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waterfall', 'n. 瀑布, 瀑布似的东西', 9112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hibernation', 'n. 过冬, 冬眠, 避寒', 9113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evenness', 'n. 平均, 平等, 平坦', 9114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poikilotherm', 'n. [动]变温动物,冷血动物', 9115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unload', 'v. 卸货 v. 摆脱之负担', 9116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depositor', 'n. 寄托者, 存款人', 9117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lyrically', 'adv. 抒情地,  狂热地', 9118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'theatrically', 'adv. 戏剧化地', 9119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'splinter', 'n. 尖片, 碎片 v. 分裂', 9120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tonnage', 'n. 登记吨位, 排水量', 9121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seagoing', 'adj. 适于远航的,出海的', 9122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jacket', 'n. 夹克,护封 v. 给穿夹克', 9123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fisherman', 'n. 渔民, 渔夫', 9124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mainsheet', 'n. 主桅帆操纵索', 9125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oblivious', 'adj. 没注意到, 健忘的', 9126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coaming', 'n. 舱口栏板, 边材', 9127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lad', 'n. 少年, 青年男子', 9128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tilt', 'v. (使)倾斜, 以言词或文字抨击', 9129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choppy', 'adj. （海等）波浪起伏的, (指风)不断改变方向的', 9130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'illustrator', 'n. 插图画家,说明者', 9131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ectothermic', 'n. 变温动物', 9132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poikilothermic', 'adj. [动]变温的, 冷血动物的', 9133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locomote', 'v. 移动, 行动', 9134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inadequately', 'adv. 不够地,  不够好', 9135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onetime', 'adj. 从前的,  一度的 adv. 从前', 9136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'citation', 'n. 引用,表扬', 9137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stillness', 'n. 静止, 沉静', 9138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eyesight', 'n. 视力, 目力', 9139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comical', 'adj. 好笑的, 滑稽的', 9140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mollusk', 'n. [动]软体动物', 9141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rediscover', 'v. 重新发现', 9142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eminent', 'adj. 著名的,  卓越的', 9143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bleak', 'adj. 寒冷的,荒凉的, 黯淡的', 9144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silence', 'n. 寂静, 沉默 v. 使沉默', 9145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sequester', 'v. 使隐退, 扣押, 没收', 9146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metazoan', 'n&a. [动]后生动物(的)', 9147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abreast', 'adv. 并肩地, 并排地', 9148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'serum', 'n. 浆液, 血清', 9149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adrenaline', 'n. 肾上腺素(使激动兴奋等)', 9150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'milieu', 'n. 周围, 环境', 9151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compensatory', 'adj. 赔偿的, 补偿的', 9152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unconventional', 'adj. 非传统的, 不合惯例的', 9153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gibe', 'v. 嘲笑,讥笑 n. 嘲笑', 9154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proprietor', 'n. 所有者, 经营者', 9155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mess', 'n. 混乱, 脏乱 v. 弄乱', 9156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silly', 'adj. 愚蠢的, 可笑的', 9157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'metric', 'adj. 米制的, 公制的', 9158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lintel', 'n. [建]楣, 过梁', 9159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untapped', 'adj. 塞子未开的, 未使用的', 9160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mysteriously', 'adv. 神秘地,  故弄玄虚地', 9161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corral', 'n. 畜栏 v. 关进畜栏', 9162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prevention', 'n. 预防, 防止', 9163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'playwright', 'n. 剧作家', 9164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Cuban', 'n. 古巴人 adj. 古巴(人)的', 9165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'char', 'v. 烧焦 n. 碳', 9166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tavernkeeper', 'n. 小餐馆老板', 9167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upgrade', 'n. 升级, 上升 v. 使升级, 提升 adv. 往上', 9168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incident', 'n. 事件 adj. 附带的, 易于发生的', 9169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slavish', 'adj. 奴隶的, 盲从的, 专横的', 9170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emotive', 'adj. 感情的, 引起强烈感情的', 9171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'physic', 'n. 医术 vt. 治愈', 9172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synapsis', 'n. [生]染色体结合, 突触', 9173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsophisticated', 'adj. 不谙世故的, 不复杂的', 9174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unspoiled', 'adj. 未损坏的, 未宠坏的', 9175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arthritis', 'n. 关节炎', 9176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whim', 'n. 一时的兴致, 奇想', 9177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hospitable', 'adj. 好客的, 宜人的', 9178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carnivorous', 'adj. 食肉的, 肉食性的', 9179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depredation', 'n. 掠夺, 破坏痕迹', 9180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nostalgia', 'n. 乡愁, 怀旧之情', 9181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stewpot', 'n. 双把炖锅', 9182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adolescence', 'n. 青春期', 9183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ministry', 'n. (政府的)部门', 9184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Toronto', 'n. 多伦多（加拿大）', 9185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrowly', 'adv. 勉强地, 精细地', 9186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proficiency', 'n. 熟练, 精通, 熟练程度', 9187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spar', 'n. 争论,园材(如桅,桁等)', 9188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hometown', 'n. 故乡', 9189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sociology', 'n. 社会学', 9190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dough', 'n. 生面团', 9191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flair', 'n. 才能, 本领', 9192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'esoteric', 'adj. 秘传的,  神秘的,  难懂的', 9193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potion', 'n. 一服, 一剂', 9194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laboriously', 'adv. 艰难地,  辛勤地', 9195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elixir', 'n. 炼金药, 不老长寿药', 9196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inextricably', 'adv. 分不开地, 无法摆脱地', 9197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imprecise', 'adj. 不精确的', 9198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bestow', 'v. 给予,利用', 9199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bless', 'v. 祝福, 保佑', 9200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quaker', 'n. 教友派信徒, 贵格会会员', 9201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alternately', 'adv. 交替地,轮流地', 9202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thermodynamic', 'adj. 热力学的, 使用热动力的', 9203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncrumple', 'vt. 去掉…的皱纹,使回复到平整状态', 9204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dinner', 'n. 正餐, 宴会', 9205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untwist', 'v. 拆开(搓合的绳,线等), 解开', 9206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'selfless', 'adj. 无私的', 9207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obligation', 'n. 义务, 职责, 债务', 9208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fanatical', 'adj. 狂热的, 入迷的', 9209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coax', 'v. 巧妙地（耐心地）处理,哄', 9210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flue', 'n. 烟道, 暖气管', 9211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pivot', 'n. 枢轴 v. 在枢轴上转动', 9212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coordination', 'n. 协调', 9213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cancel', 'v.  取消， 废除； 删去， 删除； 抵消', 9214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recline', 'v.  向后倚靠， 斜倚', 9215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explosive', 'adj. 爆炸的，爆发的；使人冲动的 n.  炸药', 9216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prepare', 'v.  准备， 预备', 9217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crusade', 'v.  加入十字军， 投身正义运动 n. 十字军；斗争，运动', 9218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplant', 'vt.  取代， 代替', 9219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surgeon', 'n.  外科医师', 9220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abrupt', 'adj.  突然的， 意外的； 唐突的， 鲁莽的', 9221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discourage', 'vt.  使泄气， 使灰心； 阻止， 劝阻', 9222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predispose', 'v.  事先影响某人； 易受感染', 9223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spontaneous', 'adj.  自发的， 自然产生的； 自然的， 无雕饰的', 9224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convection', 'n.  对流； 传送', 9225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wreck', 'vt. 使失事；破坏 n.  沉船； 失事', 9226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twinkling', 'adj.  闪光的 n. 瞬间，一眨眼', 9227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gloomy', 'adj.  忧郁的， 令人沮丧的； 昏暗的， 阴暗的， 阴沉的', 9228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reproach', 'v&n.  指责， 斥责， 批评', 9229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'customs', 'n.  关税， 进口税； 海关', 9230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'warrant', 'n. 授权，批准；许可证；委任状，执行令 vt.  保证， 担保； 使正当', 9231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sake', 'n.  缘故， 理由； 好处', 9232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conceal', 'vt.  隐蔽； 隐瞒； 覆盖', 9233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solid', 'adj. 固体的；实心的；结实的，稳固的；可靠的；连续的 n.  固体', 9234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrative', 'adj.  叙述性的 n. 叙述；记叙体，叙述技巧', 9235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coincide', 'vi.  同时发生； 一致， 相符； 重合', 9236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circular', 'adj.  圆形的， 环形的； 循环的； 绕行的', 9237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scratch', 'vt. 刮擦，划；抓，搔 n.  划痕； 挠痒', 9238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'require', 'vt.  需要； 要求， 命令', 9239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cooperative', 'adj. 合作的，协作的；配合的 n.  合作企业', 9240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'willow', 'n.  柳， 柳树； 柳木制品', 9241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corporeal', 'adj.  肉体的， 身体的； 物质的； 实体的', 9242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irritable', 'adj.  急躁的， 易怒的； 易受刺激的； 过敏的', 9243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'triple', 'v. 增至三倍 adj.  三部分的； 三方的； 三倍的', 9244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temper', 'n. 脾气，性情 vt.  缓和， 调节', 9245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legible', 'adj.  清楚的； 易读的', 9246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tickle', 'v. 发痒；使高兴，逗乐 n.  痒', 9247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cardiac', 'adj.  心脏的； 心脏病的', 9248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accessible', 'adj.  易接近的； 可得到的； 可进入的', 9249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ageism', 'n.  年龄歧视', 9250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cliff', 'n.  悬崖， 峭壁', 9251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roll', 'v. 滚动，转动；卷，绕；摇摆，摇晃 n.  卷； 卷形物； 名单， 花名册', 9252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notable', 'adj. 值得注意的，明显的；显著的；著名的；重要的 n.  名人， 要人', 9253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concede', 'v.  承认； 让步； 允许', 9254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unparalleled', 'adj.  空前的， 无比的', 9255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'evaporate', 'v.  蒸发； 消失， 不复存在', 9256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'luminosity', 'n.  亮度， 发光度； 光明', 9257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commission', 'n. 授权，委任；委员会；佣金，回扣 vt.  委托， 授权', 9258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'policy', 'n.  政策， 方针； 原则； 保险单', 9259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resume', 'v.  重新开始， 继续', 9260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'provocative', 'adj.  挑衅的， 煽动性的； 惹人讨厌的； 挑逗的', 9261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'address', 'v.  作讲话； 写姓名地址 n. 地址；讲话', 9262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spiral', 'vi. 盘旋；盘旋上升；急剧增长 adj. 螺旋形的 n.  螺旋形； 螺旋式的上升', 9263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artistic', 'adj.  艺术的； 富有艺术性的， 精美的； 有艺术天赋的', 9264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ramble', 'vi. 漫游；漫谈，闲聊 n.  漫步', 9265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vocation', 'n.  职业； 使命感； 圣召', 9266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'halt', 'v.  停住， 停下 n. 停止，阻止；暂停', 9267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'throw', 'v. 投，掷，抛；丢，扔；使陷入，使处于；使困惑，使吃惊 n.  投， 掷， 抛； 投掷的距离', 9268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sunset', 'n.  日落， 傍晚', 9269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stature', 'n.  身材， 身高； 地位， 声望， 名望', 9270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dogged', 'adj.  顽强的， 坚持不懈的； 顽固的， 固执的', 9271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plasma', 'n.  血浆； 等离子体', 9272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exorbitant', 'adj.  过高的， 不合理的', 9273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surgery', 'n.  外科手术； 外科学； 手术室， 诊疗室', 9274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'violent', 'adj.  暴力的； 感情强烈的， 激情的； 强烈的， 激烈的', 9275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inaccessible', 'adj.  难达到的， 不可及的； 不能得到的', 9276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resolve', 'v. 解决；决定，决心；分解；显现 n.  决心， 决议', 9277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choreograph', 'v.  设计舞蹈动作， 编舞', 9278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confront', 'vt.  使面临， 使遭遇； 对抗', 9279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonverbal', 'adj.  非语言的', 9280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deploy', 'vt.  部署， 调度； 利用', 9281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reproduce', 'v.  繁殖， 生育； 复制； 再现', 9282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skeleton', 'n.  梗概， 提纲； 骨架， 骨骼； 框架', 9283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'huddle', 'vi.  聚集在一起， 挤作一团； 蜷缩， 缩成一团， 蜷缩 n. 挤在一起的人', 9284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'syntactic', 'adj.  句法的； 按照句法的', 9285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rendition', 'n.  表演， 演唱； 提供， 给予； 翻译', 9286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intersection', 'n.  交点； 十字路口， 道路交叉口', 9287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scholarship', 'n.  奖学金； 学问， 学识', 9288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'myriad', 'adj.  无数的； 大量的 n. 无数；大量', 9289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'besides', 'adv.  而且， 还有 prep. 除…之外', 9290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implement', 'vt.  使生效， 执行， 实施', 9291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disperse', 'v.  分散， 散开； 疏散； 散布', 9292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erratic', 'adj.  古怪的， 反复无常的； 不规则的； 不稳定的', 9293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incinerate', 'vt.  焚化， 焚毁', 9294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fantasy', 'n.  想象， 幻想', 9295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capillary', 'adj.  毛状的； 毛细血管的 n. 毛细血管', 9296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deform', 'v.  变形', 9297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erode', 'v.  侵蚀， 腐蚀', 9298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'informative', 'adj.  提供消息的， 给予知识的； 见闻广博的', 9299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'check', 'n. 支票；账单；', 9300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frustrate', 'vt.  使感到灰心， 挫败； 阻止', 9301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sparse', 'adj.  稀疏的， 稀少的； 贫乏的', 9302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gorgeous', 'adj.  漂亮的； 令人愉快的； 华丽的， 灿烂的', 9303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pragmatic', 'adj.  务实的， 注重实效的， 实用的', 9304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erosion', 'n.  腐蚀， 侵蚀； 削弱， 减少', 9305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'methane', 'n.  甲烷， 沼气', 9306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tectonic', 'adj.  地壳构造的', 9307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superstitious', 'adj.  迷信的， 受迷信思想支配的', 9308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ascend', 'v.  上升， 升高； 攀登', 9309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elasticity', 'n.  弹力； 弹性', 9310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proactive', 'adj.  积极主动的； 先发制人的', 9311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aboriginal', 'adj. 原始的；土著的，土生土长的 n.  土著', 9312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indispensable', 'adj.  必不可少的', 9313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lens', 'n.  透镜； 镜头； 镜片', 9314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embody', 'vt.  表达， 体现； 含有', 9315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verifiable', 'adj.  可证实的， 可核实的', 9316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comprehensible', 'adj.  可理解的， 能懂的， 能充分理解的', 9317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motive', 'adj.  发动的； 导致运动的 n. 动机，目的', 9318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elliptical', 'adj.  椭圆的； 隐晦的； 省略的， 简略的', 9319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emancipate', 'vt.  解放， 解除', 9320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'romantic', 'adj.  爱情的； 浪漫的， 富有情调的； 多情的； 不切实际的， 幻想的； [R-]浪漫主义的', 9321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motivate', 'vt.  激励； 激发', 9322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spoil', 'v.  破坏； 宠坏， 溺爱； 变质', 9323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multiply', 'v.  增加； 繁殖； 乘', 9324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pasture', 'n. 牧场，草原；', 9325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conducive', 'adj.  有助于…的， 有益于…的', 9326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pilot', 'adj. 试验性的 n. 飞行员，领航员；领导人 vt.  驾驶， 领航； 试行， 试用； 使通过， 引导', 9327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curative', 'adj. 有助于治疗的，有疗效的 n.  药物', 9328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cartilage', 'n.  软骨', 9329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snide', 'adj.  伪造的； 不诚实的； 讽刺的， 挖苦的， 含沙射影的', 9330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multiple', 'adj. 多样的；多重的 n.  倍数', 9331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expose', 'vt.  暴露， 显露； 揭露， 揭穿； 使接触， 使面临', 9332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnet', 'n.  磁铁， 磁体； 有吸引力的人', 9333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'versatile', 'adj.  多才多艺的； 多用途的', 9334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concentrate', 'v. 集中，专心；', 9335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'versus', 'prep.  对， 对抗； 与…相对， 与…相比', 9336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penmanship', 'n.  书法', 9337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tundra', 'n.  苔原， 冻原， 冻土地带', 9338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'explosion', 'n.  爆炸； 爆发； 激增', 9339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tinker', 'vi. 做焊锅匠；做拙劣修补 n.  补锅匠', 9340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'populate', 'vt.  居住于', 9341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puncture', 'v. 刺穿；泄气，挫伤 n.  小孔； 刺伤', 9342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permit', 'v.  允许， 许可 n.  许可证， 执照', 9343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'translation', 'n.  翻译； 译文， 译本', 9344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personnel', 'n.  全体人员， 员工', 9345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'splash', 'v.  溅， 泼 n. 重点文章；溅上的液体；斑点', 9346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fountain', 'n.  喷泉； 丰富来源， 源泉', 9347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'porcelain', 'n.  瓷器， 瓷', 9348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catalog', 'n.  目录', 9349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'part-time', 'adj.  兼职的； 部分时间的', 9350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pioneer', 'vt. 开拓，开创 n.  开拓者， 创始人', 9351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chilly', 'adj.  寒冷的； 冷淡的， 不友好的', 9352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flagellum', 'n. [昆] 鞭毛；鞭子；鞭状匍匐枝', 9353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rhinoceros', 'n.  犀牛', 9354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implication', 'n.  含义； 暗示， 暗指； 卷入， 牵连', 9355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fierce', 'adj.  凶猛的， 残忍的； 狂热的， 强烈的； 激烈的， 猛烈的', 9356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reservation', 'n.  预约， 预订； 保留意见， 疑惑； 居留地', 9357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'block', 'vt. 阻塞；阻碍，妨碍 n.  大块； 街区； 障碍物', 9358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cordial', 'adj.  亲切的， 热诚的', 9359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'odorous', 'adj.  有气味的， 难闻的； 香的， 芬芳的', 9360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cooperation', 'n.  合作， 协作', 9361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conceit', 'n.  自负， 自大', 9362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modulate', 'v.  调整， 调节； 调制', 9363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mottled', 'adj.  有杂色的， 斑驳的', 9364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'morphology', 'n.  形态学， 形态论', 9365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distant', 'adj.  远离的， 遥远的； 疏远的， 冷淡的； 久远的； 不同的', 9366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resonance', 'n.  共振， 共鸣； 回声， 反响', 9367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'propose', 'v.  建议， 提议； 提名， 推荐； 打算， 计划； 求婚', 9368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spearhead', 'n. 先锋，前锋，先头部队 vt.  为…作先锋； 带头做', 9369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seismograph', 'n.  地震仪， 测震仪', 9370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reform', 'n&v.  改革， 改造， 革新； 改正， 改过自新', 9371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'angular', 'adj.  有角的， 尖角的； 消瘦的， 瘦骨嶙峋的', 9372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'daylight', 'n.  日光； 白昼', 9373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'podium', 'n.  讲坛， 讲台； 指挥台', 9374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'binary', 'adj.  二进制的； 二元的； 由两部分组成的', 9375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ensue', 'vi.  继而发生， 接着发生', 9376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crazy', 'adj.  疯狂的， 不理智的； 狂热的， 热衷的； 精神失常的', 9377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microscopic', 'adj.  用显微镜可见的； 极小的', 9378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homage', 'n.  尊敬， 敬意', 9379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penicillin', 'n.  青霉素， 盘尼西林', 9380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pine', 'vi.  憔悴； 难过， 悲伤 n. 松树', 9381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enlightenment', 'n.  启发， 教化， 启迪； [the E-]启蒙运动', 9382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irony', 'n.  反话， 讽刺， 嘲弄； 具有讽刺意味的事', 9383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mandatory', 'n. 强制的，法定的，义务的； 受托人； 代理人', 9384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caterpillar', 'n.  毛毛虫', 9385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypertext', 'n.  超文本', 9386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bedrock', 'n.  基础， 根基； 基岩', 9387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'syndrome', 'n.  综合征； 典型表现', 9388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newsprint', 'n.  新闻纸', 9389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tow', 'vt&n.  拖， 牵引', 9390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harmonic', 'n. 泛音；', 9391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haul', 'v. 拖，拖运 n.  拖， 拉， 拖运； 一次获得的数量； 旅行的距离', 9392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'energetic', 'adj.  精力充沛的， 积极的', 9393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quilt', 'v. 缝被；缝制 n.  被褥', 9394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'premier', 'adj.  第一的， 首要的； 最著名的 n. 首相，总理', 9395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allergic', 'adj.  过敏的， 变态反应的； 对…讨厌的', 9396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oceanographer', 'n.  海洋学者', 9397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anecdote', 'n.  秘闻； 轶事， 趣闻', 9398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'officious', 'adj.  爱发号施令的， 爱指手画脚的', 9399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infiltrate', 'v.  渗入， 渗透； 悄悄进入， 潜入', 9400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minor', 'vi.  辅修 adj. 较小的；次要的 n. 未成年人；辅修科目', 9401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hostile', 'adj.  不友好的， 敌意的； 敌方的', 9402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flora', 'n.  植物群', 9403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'celestial', 'adj.  天空的， 天上的', 9404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decode', 'vt.  译， 解， 破译', 9405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bruise', 'v. 出现伤痕；挫伤 n.  伤痕， 擦痕， 青肿', 9406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crawl', 'v. 缓慢行进；爬行 n.  缓慢的速度', 9407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identical', 'adj.  相同的； 同一的', 9408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unaided', 'adj.  未受协助的， 独立的', 9409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ambitious', 'adj.  有雄心的， 有野心的', 9410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'academic', 'adj. 学术的；学校的，学院的；纯理论的 n.  大学教师', 9411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coral', 'adj.  珊瑚色的， 红色的 n. 珊瑚', 9412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'function', 'v.  运行； 起作用 n. 机能，功能，作用；函数', 9413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'raise', 'v. 举起，提升；直立；增加；募集；饲养，养育；引起；提出 n.  提升， 增加', 9414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delinquency', 'n.  行为不良； 过失， 失职', 9415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pipe', 'vt. 用管道输送；用线路系统传输 n.  管子， 管道； 烟斗', 9416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pliant', 'adj.  柔软的； 温顺的； 易受影响的', 9417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revere', 'vt.  尊敬， 敬畏', 9418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'representative', 'adj.  典型的， 有代表性的 n. 代表，代理人', 9419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sneaky', 'adj.  偷偷摸摸的， 鬼鬼祟祟的', 9420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'longitude', 'n.  经度， 经线', 9421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pigeon', 'n.  鸽子', 9422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lax', 'adj.  懒散的； 不严格的， 马虎的', 9423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'comparison', 'n.  比较， 对比； 比拟， 比喻', 9424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lay', 'v.  产； 放置； 铺； 筹划， 设置； 提出， 提交', 9425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hatch', 'v. 孵化，孵出 n.  开口； 舱门', 9426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patriot', 'n.  爱国者', 9427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pernicious', 'adj.  有害的， 恶性的', 9428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revert', 'v.  恢复； 归还， 归属', 9429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cohabitation', 'n.  同居， 同住', 9430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herbivore', 'n.  食草动物', 9431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'successive', 'adj.  接替的， 继承的； 接连的， 连续的', 9432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adventure', 'n.  奇遇； 冒险活动', 9433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ceremony', 'n.  典礼， 仪式； 礼节', 9434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'improve', 'v.  改善， 改进， 增进； 好转， 进步', 9435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idyllic', 'adj.  田园诗般的， 田园风光的， 牧歌的', 9436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hawk', 'n. 鹰，隼；主战分子 vt.  叫卖， 兜售', 9437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speckle', 'v. 弄上斑点；点缀 n.  斑点； 色斑', 9438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emanate', 'v.  散发； 表现， 显示', 9439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exterior', 'adj. 外部的，外表的 n.  外部， 外表', 9440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'captivity', 'n.  囚禁， 拘留', 9441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'levy', 'vt. 征收 n.  征收额； 税款； 征兵', 9442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'effective', 'adj.  有效的， 生效的； 显著的； 实际的， 事实上的', 9443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'muscle', 'n.  肌肉； 体力， 力量， 实力； 影响力', 9444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generous', 'adj.  慷慨的， 大方的； 大量的， 丰富的； 宽厚的， 宽宏大量的', 9445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flux', 'n.  变迁， 不断的变动', 9446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jelly', 'n.  果冻， 胶状物', 9447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'probe', 'v. 探查，探测；盘问，追问 n.  探针； 探测器； 探索， 调查', 9448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crescent', 'adj. 新月形的；逐渐增强的 n.  新月； 新月形， 月牙形', 9449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inflate', 'v.  充气， 膨胀； 鼓吹， 吹捧； 涨价', 9450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stable', 'adj. 稳定的，安定的；牢固的；沉稳的 n.  马厩', 9451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quantitative', 'adj.  数量的， 定量的', 9452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clamor', 'n.  吵闹， 喧哗', 9453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harness', 'vt. 利用…产生动力；给上挽具 n.  马具', 9454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foment', 'vt.  煽动， 挑起， 激起', 9455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respond', 'vi.  回答， 答复； 作出反应； 响应', 9456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incident', 'n.  事情， 事件； 摩擦， 冲突', 9457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cluster', 'vi.  成群， 成串； 丛生； 群集 n. 簇，团，串，丛；群', 9458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prey', 'vi. 捕食，捕获 n.  猎物； 受害者， 牺牲品', 9459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attire', 'n. 穿着，服饰 vt.  给…穿衣， 打扮', 9460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tug', 'v. 拖，', 9461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neuron', 'n.  神经元， 神经细胞', 9462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vertebrate', 'adj.  有脊椎的 n. 脊椎动物', 9463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expedition', 'n.  远征； 探险', 9464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concert', 'n.  音乐会， 演奏会； 一致', 9465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absorb', 'vt.  吸收； 理解， 掌握； 吸引…的注意， 使全神贯注； 使并入， 同化', 9466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supply', 'n. 供应；储备；补给 vt.  供给， 供应； 满足， 弥补', 9467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concern', 'vt. 涉及，关系到；使关心，使担忧 n.  关心， 挂念； 关系； 有关的事， 负责的事； 公司， 企业', 9468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'circulate', 'v.  循环； 流通； 传播， 流传', 9469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incubate', 'v.  孵化； 培育； 潜伏', 9470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rectify', 'vt.  矫正， 纠正； 整顿', 9471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antonym', 'n.  反义词', 9472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'integrity', 'n.  正直； 完整', 9473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refrain', 'v.  抑制； 戒除 n. 反复句，副歌', 9474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pact', 'n.  协议， 条约， 公约', 9475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notation', 'n.  符号， 记号', 9476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liable', 'adj.  有责任的， 有义务的； 易于…的', 9477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homing', 'adj.  有返回原地本能的', 9478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'state', 'v.  陈述， 说明， 声明； 规定 n. 情况，状况；国家；州', 9479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cargo', 'n.  货物', 9480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'press', 'v.  压， 按， 挤； 压榨， 压迫； 催促， 逼迫 n. 报刊；新闻界，新闻工作者；报道，评论；出版社；印刷厂；压，按，挤', 9481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jumble', 'vt. 混杂，掺杂 n.  杂乱的一堆， 混乱的一团', 9482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'element', 'n. 元素，要素，组成部分；', 9483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'environmental', 'adj.  有关环境的， 自然环境的， 生态环境的； 环境的', 9484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'picky', 'adj.  挑剔的， 难以取悦的', 9485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crustacean', 'adj.  甲壳类的 n. 甲壳类动物', 9486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exclaim', 'v.  惊叫， 呼喊', 9487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'opposite', 'adj. 对面的；对立的；相反的 prep.  在…对面 n. 对立面；对立物', 9488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pack', 'v. 收拾，打包；捆扎；塞满 n.  包， 包裹', 9489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restraint', 'n.  抑制， 克制； 限制； 约束力； 管制措施', 9490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aftermath', 'n.  后果， 余波', 9491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pollutant', 'n.  污染物质， 有害物质', 9492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untapped', 'adj.  未开发的， 未使用的', 9493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cue', 'n.  暗示， 提示', 9494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'effluent', 'n.  流出物， 废水， 污水', 9495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'untamed', 'adj.  未驯服的， 难驾驭的', 9496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stereotype', 'n. 陈规；固定形式，老套；刻板印象 vt.  对…形成固定看法', 9497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enroll', 'v.  登记， 注册； 招收', 9498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sweeping', 'adj. 彻底的，广泛的；〈贬〉笼统的，一概而论的 n.  清扫， 扫除； 垃圾', 9499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ardent', 'adj.  热心的， 热情洋溢的', 9500);
