INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knot', 'n. (绳等的)结 v. 打结', 6001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'notch', 'n. 槽口,刻痕 v. 刻凹痕', 6002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oystercatcher', 'n. 〈动〉蛎鹬', 6003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shorebird', 'n. 岸禽类鸟,沙禽', 6004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photogrammetry', 'n. 照相测量法', 6005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mandible', 'n. 下颚, 下颚骨', 6006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attire', 'n. 服装 v. 打扮', 6007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corrosion', 'n. 侵蚀,腐蚀状态', 6008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upright', 'adj. 正直的 n. 垂直, 竖立', 6009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unravel', 'v. 拆开,拆开', 6010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glassmaking', 'n. 玻璃(或玻璃器皿等)制造(术)', 6011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Katherine', 'n. 凯瑟琳（女子名）', 6012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'malleability', 'n. 有延展性, 柔韧性', 6013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deft', 'adj. 敏捷熟练的, 灵巧的', 6014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'robust', 'adj. 精力充沛的', 6015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'baedeker', 'n. 旅行指南, 入门手册', 6016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sword', 'n. 剑', 6017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'microfossil', 'n. 微体化石,微化石', 6018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entomb', 'v. 埋葬, 成为的坟墓', 6019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burgher', 'n. 公民, 市民', 6020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'puffin', 'n. [鸟]角嘴海雀', 6021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insoluble', 'adj. 不能溶解的, 不能解决的', 6022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliability', 'n. 可靠性', 6023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unemployed', 'adj. 失业的, 未被利用的', 6024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immobility', 'n. 牢固,不动', 6025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preside', 'v. 主持,管理', 6026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spacious', 'adj. 广大的,大规模的', 6027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydrographic', 'adj. 水道测量数的,水道学的', 6028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portraiture', 'n. 肖像画法', 6029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'talented', 'adj. 有才能的', 6030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homework', 'n. 家庭作业, 副业', 6031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'filmmaker', 'n. 电影摄制者', 6032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'understate', 'v. 打着折扣说,有意轻描淡写', 6033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'narrate', 'v. 叙述,作解说', 6034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lean', 'n. 倾斜,倚靠 v. 依靠,倾斜 adj. 贫乏的', 6035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consort', 'v. 结交,符合 n. 配偶', 6036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gannet', 'n. 塘鹅', 6037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'underwing', 'n. 后翅, 后翅色彩瑰丽的蛾', 6038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exorbitant', 'adj. （要价等）过高的,（性格等）过分的', 6039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gondwanaland', 'n. [地]冈瓦纳大陆', 6040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gunpowder', 'n. 黑色火药, 有烟火药', 6041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herring', 'n. 青鱼, 鲱', 6042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'earner', 'n. 赚钱的人', 6043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'angular', 'adj. [生物] 有角的,生硬的,笨拙的', 6044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wren', 'n. [动] 鹪鹩', 6045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weary', 'adj. 疲倦的,厌倦的 v. 疲倦,厌倦', 6046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kinglet', 'n. <贬>懦弱的国王,小国君主', 6047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uniformity', 'n. 一致,均匀', 6048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'screw', 'n. 螺丝钉,螺旋 v. 调节,旋', 6049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'priestess', 'n. 女祭司, (基督教会以外的)神职人员', 6050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neoclassical', 'adj. 新古典主义的', 6051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thousandfold', 'adv. 千倍地 adj. 千倍的', 6052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enjoyment', 'n. 享乐, 快乐', 6053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forester', 'n. 林务官, 森林人', 6054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spoilage', 'n. 损坏', 6055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonthreatening', 'adj. 非胁迫的', 6056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solder', 'n. 焊料 v. 焊接', 6057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tumble', 'n. 跌倒,翻斤斗 v. 翻倒, 摔倒', 6058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harshness', 'n. 粗糙的事物, 严肃, 刺耳', 6059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'collagen', 'n. 胶原质', 6060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surgeon', 'n. 外科医生', 6061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idle', 'adj. 空闲的,懒惰的 v. 虚度, 闲散', 6062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sumptuous', 'adj. 奢侈的,华丽的', 6063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synchrotron', 'n. 同步加速器', 6064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landlord', 'n. 房东,地主', 6065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'familiarity', 'n. 熟悉,通晓,精通', 6066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stringent', 'adj. 严厉的,迫切的', 6067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signature', 'n. 签名,信号', 6068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cabinetmaker', 'n. 家具师,细工木匠', 6069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chord', 'n. 弦,和音', 6070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supervisory', 'adj. 监督的', 6071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resentment', 'n. 怨恨,愤恨', 6072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purposely', 'adv. 故意地,蓄意地', 6073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irresponsibly', 'adv. 不负责任地,不可靠地', 6074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quench', 'v. 结束,熄灭', 6075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grapple', 'v. 格斗,抓住 n. 格斗', 6076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haunt', 'v. 出没于', 6077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revealingly', 'adv. 启发人地,袒胸露肩地', 6078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'obedience', 'n. 服众, 顺从', 6079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rearrange', 'v. 再排列,重新整理', 6080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roar', 'n. 吼叫, 怒号 v. 滚动,咆哮', 6081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'armory', 'n. 兵工厂,军械库', 6082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tuck', 'n. 缝摺, 活力 v. 卷起,大口的吃', 6083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slippery', 'adj. 滑的,光滑的', 6084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'courtship', 'n. 求爱, 求爱时期', 6085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sleek', 'adj. 圆滑的,使…光滑', 6086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corselet', 'n. 盔甲,胸衣', 6087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'keel', 'n. 龙骨(船的脊骨),平底船 v. 装以龙骨,倾覆', 6088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'needle', 'n. 针 v. 缝纫,刺激', 6089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secrecy', 'n. 秘密,保密', 6090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lira', 'n. 里拉（意大利货币单位）', 6091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'livelihood', 'n. 生计,谋生', 6092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impediment', 'n. 妨碍,口吃, 障碍物', 6093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bow', 'n. 弓,弓形 v. 鞠躬,弯腰', 6094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nurture', 'n. 养育,教育 v. 养育,给与营养物', 6095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'silhouette', 'n. 侧面影象,轮廓 v. 使…照出影子来', 6096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inward', 'adv. 向内,在内 adj. 向内的,内在的', 6097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'misinterpret', 'v. 曲解', 6098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marketable', 'adj. 市场的,可销售的', 6099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mudstone', 'n. [地]泥岩', 6100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carcass', 'n. (屠宰后)畜体', 6101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subdivide', 'v. 再分, 细分', 6102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meteoritic', 'adj. 陨星的,陨石的', 6103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offshoot', 'n. 分支, 支流', 6104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inborn', 'adj. 天生的,生来的', 6105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stereotypical', 'adj. 老一套的,陈规的', 6106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manipulation', 'n. 处理,操纵', 6107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lifelike', 'adj. 栩栩如生的,逼真的', 6108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bipedal', 'adj. 两足动物的,两足的', 6109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antiquate', 'adj. 旧式的,过时的', 6110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chondritic', 'adj. 球粒状陨石的', 6111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'replicate', 'v. 复制 adj. 复制的', 6112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'painful', 'adj. 疼痛的,使痛苦的', 6113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weldon', 'n. 韦尔登（男子名）', 6114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scorch', 'v. 烧焦,枯萎 n. 烧焦,枯黄', 6115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stonework', 'n. 石雕工艺, 做石工的场所', 6116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shipwreck', 'n. 船只失事,海难 v. 使失事', 6117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncle', 'n. 伯父,叔父,援助者', 6118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unanswered', 'adj. 未答复的,无反应的', 6119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'misfortune', 'n. 不幸, 灾祸', 6120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'greet', 'v. 问候,向致意', 6121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aggregate', 'n. 合计 v. 聚集, 集合', 6122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'journalist', 'n. 新闻记者,从事新闻杂志业的人', 6123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mantel', 'n. 壁炉架', 6124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'desalination', 'n. 减少盐分, 脱盐作用', 6125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slit', 'v. 撕裂 n. 裂缝, 狭长切口', 6126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hydraulic', 'adj. 水力的,水压的', 6127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reappear', 'v. 再出现', 6128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carton', 'n. 硬纸盒, 纸板箱', 6129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wan', 'adj. 苍白的,病态的 v. (使)变苍白', 6130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elegance', 'n. 高雅,典雅', 6131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'horsepower', 'n. 马力', 6132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quiver', 'n. 震动,颤抖 v. 颤抖,射中', 6133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'airport', 'n. 机场,航空站', 6134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eternal', 'adj. 永恒的,永远的', 6135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duchenne', 'n. 杜氏营养不良症', 6136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reopen', 'v. 重开,再开始', 6137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immutable', 'adj. 不变的,不可变的', 6138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pave', 'v. 铺,安排', 6139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permeability', 'n. 渗透性', 6140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afterwards', 'adv. 然后, 后来地', 6141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consolidation', 'n. 巩固, 合并', 6142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waterfowl', 'n. 水鸟, 水禽', 6143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'efficacious', 'adj. 有效的,灵验的', 6144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'permeable', 'adj. 有浸透性的, 能透过的', 6145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fanwise', 'ad& adj. 呈扇形展开的', 6146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'riverbed', 'n. 河床', 6147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'destine', 'v. 注定, 预定', 6148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expertly', 'adv. 熟练地', 6149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stipulate', 'v. 规定, 保证', 6150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sandbar', 'n. 沙洲', 6151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contingent', 'adj. 可能发生的, 附随的 n. 偶然的事情', 6152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'congenial', 'adj. 意气相投的,性格相似的', 6153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faucet', 'n. 龙头, (连接管子的)插口', 6154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alienate', 'v. 疏远', 6155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'implicit', 'adj. 暗示的,盲从的', 6156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preponderance', 'n. 优势,占优势', 6157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imperfect', 'adj. 有缺点的,未完成的 n. 未完成体', 6158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homeotherm', 'n. <主美>恒温动物', 6159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'envy', 'n. 羡慕,嫉妒 v. 羡慕,嫉妒', 6160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drape', 'n. 窗帘 v. 使褶皱', 6161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drip', 'n. 水滴 v. (使)滴下', 6162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jewel', 'n. 宝石', 6163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'practicality', 'n. 实用性,实际', 6164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pictorial', 'adj. 图示的 n. 画报', 6165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bland', 'adj. 温和的,乏味的 v. 变得乏味', 6166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mortal', 'n. 凡人,人类 adj. 必死的,致命的', 6167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unschooled', 'adj. 天生的,未受学校教育的', 6168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harmless', 'adj. 无害的', 6169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burgeon', 'n. 嫩芽 v. 萌芽', 6170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ashcan', 'n. 垃圾桶, 深水炸弹', 6171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'literalness', 'n. 文字的,表面意义上的', 6172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flyspeck', 'n. 污点,小斑 v. 弄脏', 6173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rennin', 'n. 高血压蛋白原酶', 6174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hormonal', 'adj. 荷尔蒙的,激素的', 6175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'angiotensin', 'n. [医]血管紧缩素', 6176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deprivation', 'n. 剥夺', 6177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aldosterone', 'n. [生化]醛甾酮,醛固酮', 6178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mandate', 'n. (书面)命令,训令 v. 委任统治', 6179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'henceforth', 'adv. 今后,自此以后', 6180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mammalian', 'n. 哺乳动物 adj. 哺乳动物的', 6181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unfairly', 'adv. 不公平地,不正当地', 6182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irrelevant', 'adj. 不相干的,不切题的', 6183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jury', 'n. [律] 陪审团 adj. [海]临时应急的', 6184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'burdensome', 'adj. 繁重的,难以承担的', 6185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confederate', 'n. 同盟者,同盟国 adj. 同盟的 v. (使)联盟, 联合', 6186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pardon', 'v. 原谅,宽恕 n. 原谅', 6187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convict', 'v. 证明有罪 n. 罪犯', 6188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'authorization', 'n. 授权,认可', 6189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gymnastic', 'adj. 体操的,体育的 n. 训练课程', 6190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stagger', 'v. 蹒跚,交错 adj. 交错的', 6191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peacetime', 'n. 和平时期 adj. 和平时期的', 6192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'readjust', 'v. 重新调整,再调整', 6193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rivalry', 'n. 竞争,竞赛,敌对', 6194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nobility', 'n. 高贵,贵族', 6195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'revive', 'v. 苏醒, (使)复兴', 6196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ponderous', 'adj. 笨重的,沉闷的', 6197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thresher', 'n. 打谷者, 打谷机, [鱼]长尾鲨', 6198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'utensil', 'n. 器具', 6199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'knight', 'n. (欧洲中世纪的)骑士 v. 授以爵位', 6200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intentional', 'adj. 故意的,策划的', 6201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thrifty', 'adj. 节约的', 6202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enactment', 'n. 设定,制定', 6203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proclaim', 'v. 宣布,声明,显露', 6204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seafood', 'n. 海产食品, 海味', 6205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'besiege', 'v. 围困,围攻', 6206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsubstantiated', 'adj. 未经证实的,无事实根据的', 6207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unaware', 'adj. 不知道的, 没觉察到的', 6208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'semimolten', 'adj. 半熔的', 6209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incinerate', 'v. 把烧成灰,烧弃', 6210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'topographical', 'adj. 地志的,地形学的', 6211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'festival', 'n. 节日,喜庆日 adj. 节日的,快乐的', 6212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'canyon', 'n. <美>峡谷, 溪谷', 6213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'falconer', 'n. 以鹰狩猎者,养鹰者', 6214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lien', 'n. 留置权,抵押品所产生的利息', 6215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prejudice', 'n. 偏见,损害 v. 损害,有偏见', 6216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'starfish', 'n. 海星', 6217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extraordinarily', 'adv. 非常,格外地', 6218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dismember', 'v. 肢解,割断手足', 6219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unquestionably', 'adv. 无可非议地,确凿地', 6220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phylum', 'n. (生物分类学上的)门, 语群', 6221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spinet', 'n. 古时的小型竖琴, 小型立式钢琴', 6222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'avail', 'v. 有益于,有帮助 n. 效用, 利益', 6223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supremacy', 'n. 地位最高的人,至高,霸权', 6224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rumor', 'n. 流言,谣言 v. 谣传, 传闻', 6225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'passageway', 'n. 过道,出入口', 6226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Gothic', 'n. 哥特式 adj. 哥特式的,野蛮的', 6227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bluff', 'n. 断崖,诈骗 adj. 绝壁的 v. 诈骗', 6228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'versatility', 'n. 多功能性', 6229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tonal', 'adj. 音调的', 6230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pedal', 'n. 踏板 v. 踩的踏板', 6231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inconvenient', 'adj. 不便的,打扰的', 6232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contributor', 'n. 贡献者,捐助者', 6233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overcultivation', 'n. 耕种过度', 6234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'penetration', 'n. 穿过, 渗透, 突破', 6235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subtract', 'v. (～ from)减去, 减', 6236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hearth', 'n. 壁炉地面, 家庭（生活）', 6237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saguaro', 'n. 仙人掌之一种', 6238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transcend', 'v. 超越, 胜过', 6239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taproot', 'n. [植]主根, 直根', 6240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firing', 'n. 开火, 生火 v. 开火,烧制', 6241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distributor', 'n. 发行人,经销商', 6242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'signify', 'v. 颇为重要, 意味', 6243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heed', 'n. 注意,留意 v. 注意,留意', 6244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seminar', 'n. 研究会,讨论发表会', 6245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flavor', 'n. 情味, 风味 v. 加味于', 6246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissatisfy', 'v. 使感觉不满, 不满足', 6247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adequacy', 'n. 适当, 足够', 6248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uninteresting', 'adj. 无趣味的，乏味的', 6249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minstrel', 'n. 吟游诗人(或歌手)', 6250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irreversible', 'adj. 不可逆的,不能取消的', 6251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commend', 'v. 称赞, 表扬, 推荐', 6252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ling', 'n. 鳕鱼, 石南之一种', 6253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phosphate', 'n. 磷酸盐', 6254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apiece', 'adv. 每个, 每人, 各', 6255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'walker', 'n. 徒步者, 参加竞走者', 6256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distinctly', 'adv. 清楚地, 显然', 6257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deteriorate', 'v. (使)恶化', 6258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taut', 'adj. (绳子)拉紧的,紧张的 vt. 使纠缠', 6259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spur', 'n. 踢马剌 v. 鞭策, 刺激', 6260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stretcher', 'n. 担架, 延伸器', 6261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hoof', 'n. 蹄 v踢', 6262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discolor', 'v. 使脱色, (使)变色,(使)退色', 6263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foreleg', 'n. 前肢(指四肢或多肢动物的)前脚', 6264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buckskin', 'n. 鹿皮裤, 鹿皮', 6265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortify', 'v. 增强(体力,结构等) v. 筑防御工事', 6266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspender', 'n. 吊裤带, 悬挂物, 吊杆, 袜吊', 6267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buckle', 'n. 带扣 v扣住, 变弯曲', 6268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chafe', 'v. (将皮肤等)擦热, 使恼火', 6269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tourniquet', 'n. 止血带, 压脉器', 6270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bandanna', 'n. 大手帕', 6271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charm', 'n. 吸引力, 魅力 v. 迷人, 使陶醉', 6272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vestigial', 'adj. 退化的,发育不全的', 6273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harem', 'n. （伊斯兰教教徒之）闺房, 为一个雄性动物所控制的许多雌性动物', 6274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonfunctional', 'adj. 不运行的', 6275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'everest', 'n. 珠穆朗玛峰(世界最高峰)', 6276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trench', 'n. 沟渠, 堑壕 v. 掘沟, 挖战壕', 6277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Monroe', 'n. 门罗(m)', 6278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'concede', 'v. 勉强, 承认, 退让 vi让步', 6279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jawbone', 'n. 颚骨, 下颚骨, 信用 v赊买', 6280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'selective', 'adj. 选择的, 选择性的', 6281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Iraq', 'n. 伊拉克共和国', 6282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grande', 'adj. 重大的，显要的', 6283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facelift', 'n. 整容手术（除去面部皱纹）', 6284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'donation', 'n. 捐赠品, 捐款, 贡献', 6285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'massif', 'n. 山丘', 6286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atlas', 'n. 地图, 地图集', 6287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wireless', 'adj. 无线的 n. 无线', 6288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sterilize', 'v. 杀菌, 消毒, 使成不毛', 6289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reenter', 'n. 重进入, 再加入 v. 重返', 6290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retard', 'v. 延迟, 妨碍 n. 延迟', 6291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'logic', 'n. 逻辑, 逻辑学 adj. 逻辑的', 6292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rot', 'v. (使)腐烂, (使)腐败 n腐烂, 腐败', 6293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'satisfaction', 'n. 满意, 满足, 令人满意的事物', 6294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rapport', 'n. 和谐, 亲善', 6295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elevate', 'v. 举起, 提升的职位', 6296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gripe', 'n. 紧握, 柄 v. 握紧', 6297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gossip', 'n. 闲话, 闲谈', 6298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attendance', 'n. 出席, 出席的人数', 6299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'socialization', 'n. 社会化, 社会主义化', 6300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Irish', 'n&a. 爱尔兰人(的),爱尔兰语（的）', 6301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eyewitness', 'n. 目击者, 见证人', 6302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conglomerate', 'v. 聚结 n. 企业集团', 6303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gang', 'n. (一)伙, (一)群', 6304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'entail', 'v. 使必需, 使蒙受 n. [建]限定继承权', 6305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'punch', 'v. 冲孔, 打孔', 6306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'railhead', 'n. 铺设中的铁路末端, 终点', 6307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preferential', 'adj. 优先的；选择的', 6308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cerebral', 'adj. 脑的, 大脑的', 6309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Kenya', 'n. 肯尼亚', 6310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alphabet', 'n. 字母表', 6311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cleanly', 'adv. 干净地, 清洁地', 6312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quina', 'n. [植]金鸡纳树皮, 奎宁', 6313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unresolved', 'adj. 未解决的，未决定的', 6314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lunch', 'n. 午餐', 6315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhilarate', 'v. 使高兴, 使愉快', 6316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'choreography', 'n. 舞蹈术, 舞台舞蹈', 6317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'teem', 'v. 大量出现', 6318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lately', 'adv. 近来, 最近', 6319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scarcity', 'n. 缺乏, 不足', 6320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'premiere', 'v. 初次公演 n. 初次的演出 adj. 杰出的', 6321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'screening', 'n. 放映 v. 遮蔽,筛选', 6322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exemplary', 'adj. 典范的,惩戒性的', 6323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Austrian', 'n. 奥地利人 adj. 奥地利的, 奥地利人的', 6324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watershed', 'n. 分水岭', 6325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'periodization', 'n. (历史等的)时期(或时代)划分', 6326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homemaker', 'n. 主妇', 6327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronicle', 'n. 编年史 v. 编入编年史', 6328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substrate', 'n. （土地）底层,基础', 6329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sustenance', 'n. 食物, 生计, (受)支持', 6330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charitable', 'adj. 慈善事业的,慷慨的,仁慈的', 6331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tremendously', 'adv. 非常地,可怕地,惊人地', 6332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outlook', 'n. 景色, 展望', 6333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perceptive', 'adj. 感知的,知觉的', 6334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legacy', 'n. 遗赠(物), 遗产', 6335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'painstaking', 'n. 辛苦 adj. 辛苦的, 辛勤的', 6336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsure', 'adj. 没有自信的, 不确定的', 6337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loess', 'n. 黄土', 6338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reflectivity', 'n. 反射率', 6339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dishabituate', 'vt. 使戒除(或放弃)习惯,使不习惯', 6340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'roughness', 'n. 粗糙, 未加工, 粗糙程度', 6341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'responsiveness', 'n. 响应能力,有同情心', 6342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'partition', 'v. 区分, 分割 n分割, 划分', 6343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electro', 'n. 电镀物品, 电版', 6344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neutrality', 'n. 中立, 中性', 6345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alkaline', 'adj. 碱性的，碱的', 6346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ballad', 'n. 民歌, 流行歌曲', 6347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ratify', 'v. 批准, 认可', 6348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conflate', 'v. 合并', 6349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cardboard', 'n. 纸板', 6350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catechism', 'n. 问答教学法, 问答集', 6351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convection', 'n. 传送, 对流', 6352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rewrite', 'v. 重写, 改写', 6353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counterbalance', 'v. 使平均, 弥补 n. 平衡量, 平衡力', 6354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creditor', 'n. 债权人', 6355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regionalization', 'n. 分成地区, 按地区安排', 6356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cany', 'adj. 藤的,状似手杖的', 6357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telescopic', 'adj. 望远镜的,[眼科] 远视的', 6358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crayfish', 'n. 小龙虾', 6359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geophysical', 'adj. 地球物理学的', 6360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ample', 'adj. 充足的, 丰富的', 6361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synchronize', 'v. 同步', 6362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fluffy', 'adj. 绒毛似的, 蓬松的', 6363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'militarily', 'adv. 以武力, 以军事行动', 6364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'precision', 'n. 精确, 精密度, 精度', 6365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clause', 'n. 子句, 条款', 6366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enforcer', 'n. 实施者,强制执行者', 6367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ostracize', 'v. (古希腊)贝壳放逐法, 放逐, 排斥', 6368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extracurricular', 'adj. 课外的, 业余的', 6369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'habitual', 'adj. 习惯的, 惯常的', 6370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronobiology', 'n. [生]时间生物学, 生物钟学', 6371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thinker', 'n. 思想者, 思想家, 心智', 6372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'songwriter', 'n. 歌曲作家，歌曲作者', 6373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spotlight', 'n. 聚光灯', 6374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inducement', 'n. 诱因, 刺激物', 6375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vogue', 'n. 、a流行（的）, 时髦（的）', 6376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overgeneralize', 'v. 太笼统地概括', 6377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catalogue', 'n. 目录', 6378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'keplerian', 'adj. 开普勒理论的,开普勒定律的', 6379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grinder', 'n. 磨工, 研磨者', 6380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Galilean', 'adj. 伽利略的, 加利利的（位于巴基斯坦北部）', 6381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'align', 'v. 排列，使结盟', 6382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diffusely', 'adv. 广泛地,扩散地', 6383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caucasian', 'n. 高加索人 adj. 高加索的, 白种人的', 6384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Korean', 'n. 韩国人, 韩国语 a朝鲜人的, 朝鲜语的', 6385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crescent', 'n. 新月, 月牙', 6386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dodge', 'v. /n避开, 躲避', 6387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surrender', 'v&n. 放弃, 投降', 6388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preach', 'v. 鼓吹', 6389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impatient', 'adj. 焦躁的,不耐心的', 6390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gospel', 'n. 〈圣经·新约〉福音书', 6391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thirst', 'n. 口渴,热望 v. 渴望', 6392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ductless', 'adj. 无导管的', 6393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ridicule', 'n. 嘲笑, 奚落 v. 嘲笑', 6394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admiration', 'n. 钦佩, 赞美, 羡慕', 6395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'garland', 'n. 花环 vt戴花环', 6396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recreate', 'v. (使)得到休养, (使)得到娱乐', 6397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncritical', 'adj. 无批判力的,不加批判的', 6398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resonator', 'n. 共鸣器', 6399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Jewett', 'n. 朱厄特（姓氏）', 6400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chaotic', 'adj. 混乱的, 无秩序的', 6401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fen', 'n. 沼泽, 沼池', 6402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'toss', 'v. 投, 掷', 6403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glance', 'n. /v一瞥,匆匆一看', 6404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretension', 'n. 借口, 要求, 自负', 6405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remuneration', 'n. 报酬', 6406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expressiveness', 'n. 表现, 表示', 6407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scant', 'adj. 缺乏的,不足的 v节省,减少', 6408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pancreatic', 'adj. 胰的,胰腺的', 6409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pancreas', 'n. [解]胰腺', 6410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'juice', 'n. (水果)汁, 液', 6411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'celebratory', 'adj. 快乐的', 6412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'digestion', 'n. 消化力, 领悟', 6413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endocrinology', 'n. 内分泌学', 6414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intestinal', 'adj. 肠的', 6415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'secretin', 'n. 分泌素', 6416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hamlin', 'n. 哈姆林（姓氏）', 6417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crustacean', 'adj. 甲壳类的 n. 甲壳纲动物', 6418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dragon', 'n. 龙, 凶暴的人', 6419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consultant', 'n. 顾问, 商议者, 咨询者', 6420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lobster', 'n. 龙虾', 6421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bliss', 'n. 福佑, 天赐的福 v. 狂喜', 6422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empress', 'n. 皇后, 女皇帝, 皇太后, 极有权力的女人', 6423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pomegranate', 'n. [植]石榴', 6424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'misunderstand', 'v. 误解, 误会', 6425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spatter', 'v. 溅污 n滴落', 6426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refurbish', 'v. 再磨光, 刷新', 6427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mottle', 'v. 使有斑点 n杂色, 斑点', 6428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indifferent', 'adj. 漠不关心的,中性的', 6429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doubtful', 'adj. 可疑的, 不确的, 疑心的', 6430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idealization', 'n. 理想化, 理想化的事物', 6431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fidelity', 'n. 忠实, 诚实, 忠诚, 保真度, (收音机, 录音设备等的)逼真度, 保真度, 重现精度', 6432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appreciably', 'adv. 略微, 有一点', 6433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exceedingly', 'adv. 非常,极度地', 6434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immensely', 'adv. 极大地,无限地', 6435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interdependent', 'adj. 相互依赖的,互助的', 6436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'understandably', 'adv. 可理解地', 6437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'misunderstanding', 'n. 误会, 误解', 6438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emblem', 'n. 象征, 徽章 vt. 用象征表示', 6439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lyrical', 'adj. 抒情诗调的, 充满感情的', 6440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'module', 'n. 模数, 模块', 6441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Yuan', 'n. 元(中国货币单位)', 6442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'victimize', 'v. 使牺牲,使受害', 6443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uppermost', 'a&ad. 至上的，最高的', 6444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cheater', 'n. 骗子, 欺诈者, 背叛者', 6445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beggar', 'n. 乞丐', 6446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'siliceous', 'adj. 硅酸的；硅土的', 6447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grassy', 'adj. 绿色的, 象草的', 6448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ape', 'n. 猿', 6449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suburban', 'adj. 郊外的, 偏远的', 6450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edible', 'adj. 可食用的', 6451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hiss', 'v. 嘶嘶作声, 用嘘声表示', 6452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scramble', 'n&v. 混乱, 攀爬', 6453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'discontent', 'n. 不满a不满的vt使不满', 6454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tressed', 'adj. 有一绺绺长发的', 6455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rib', 'n. 肋骨vt戏弄', 6456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bongo', 'n. 非洲产大羚羊, 一种用手指敲的小鼓', 6457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recital', 'n. 朗诵, 背诵, 独奏会', 6458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restaurant', 'n. 餐馆, 饭店', 6459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nursery', 'n. 托儿所', 6460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dizzy', 'adj. (指人)晕眩的 v. 使人晕眩的', 6461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stir', 'n. 轰动, 搅动 v. 搅拌,激起', 6462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'woodwind', 'n. 木管乐器', 6463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humble', 'adj. 卑下的, 微贱的 v. 使卑下, 挫', 6464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unsuccessful', 'adj. 不成功的,失败的', 6465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seeker', 'n. 搜索者, 探求者', 6466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unfavorably', 'adv. 不利地,不适宜地', 6467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spatial', 'adj. 空间的', 6468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symphony', 'n. 交响乐, 交响曲', 6469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronological', 'adj. 按年代顺序排列的', 6470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superb', 'adj. 庄重的, 华丽的, 极好的', 6471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pylon', 'n. 塔门, 路标塔', 6472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acquaintance', 'n. 相识, 熟人', 6473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'decease', 'n. 死亡 v. 死', 6474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cult', 'n. 祭仪, 礼拜式', 6475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'divine', 'adj. 神圣的, 非凡的 n牧师 v占卜', 6476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colonel', 'n. 陆军上校, 团长', 6477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'marshal', 'n. 元帅 v整顿, 排列', 6478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dilemma', 'n. 进退两难的局面, 困难的选择', 6479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'validity', 'n. 有效性, 合法性, 正确性', 6480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Militant', 'adj. 好战的n好斗者', 6481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dismiss', 'v. 解散, 下课, 解职,', 6482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'superficial', 'adj. 表面的, 肤浅的n浅薄的人', 6483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'federalist', 'n. 联邦党,联邦制拥护者', 6484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biographical', 'adj. 传记的,传记体的', 6485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnetism', 'n. 磁, 磁力, 吸引力, 磁学', 6486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sonar', 'n. 声纳, 声波定位仪', 6487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perennial', 'adj. 终年的, 长期的', 6488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'infiltration', 'n. 渗透', 6489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breakage', 'n. 破坏, 破损, 破损量', 6490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bounce', 'v. (使)反跳, 弹起 n(球)跳起, 弹回', 6491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apace', 'adv. 快速地, 急速地', 6492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herbicide', 'n. 除草剂', 6493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compactness', 'n. 紧密, 简洁', 6494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pluck', 'n. 勇气v拔, 采集', 6495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'springboard', 'n. 跳板vi利用跳板', 6496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hurl', 'n. 用力或猛烈的投掷v用力投掷', 6497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'genu', 'n. 膝', 6498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'localization', 'n. 地方化, 局限, 定位', 6499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'airborne', 'adj. 空运的, 空气传播的', 6500);
