INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'therapy', 'n. 治疗， 理疗', 5501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'alternative', 'adj. 两者选一的， 供选择的； 另类的 n. 替换物，选择；选择的自由', 5502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'banner', 'n. 横幅； 旗， 旗帜', 5503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'concentration', 'n. 集中； 专注， 专心； 浓缩， 浓度', 5504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'encounter', 'vt. 遭遇，遇到 n. 遭遇', 5505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'soda', 'n. 碳酸钠， 纯碱； 汽水， 苏打水', 5506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'colleague', 'n. 同事， 同僚', 5507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gratitude', 'n. 感激， 感谢， 感恩', 5508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'approve', 'vt. 赞成， 称许； 批准', 5509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interaction', 'n. 相互作用， 干扰', 5510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chew', 'vt. 咀嚼， 嚼碎', 5511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interfere', 'vi. 干涉， 干预， 妨碍', 5512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'apartment', 'n. 一套公寓房间', 5513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'account', 'vi. 说明原因； 占 n. 记述；解释；账目', 5514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'uneasy', 'adj. 心神不安的， 忧虑的', 5515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tolerate', 'vt. 忍受， 容忍； 容许， 承认', 5516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'developmental', 'adj. 发展的', 5517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stack', 'n. 堆，垛 vt. 堆积， 堆放于', 5518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'underline', 'vt. 在…下面画线； 强调， 使…突出', 5519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'innocent', 'adj. 清白的； 幼稚的； 没有恶意的', 5520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compassion', 'n. 同情， 怜悯', 5521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'alphabet', 'n. 字母表， 字母系统', 5522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'parliament', 'n. 议会， 国会', 5523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evaluation', 'n. 评价； 估计', 5524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crack', 'vi. 爆裂； 噼啪地响； 打， 击 n. 裂缝，裂纹；破裂声', 5525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bind', 'vt. 捆绑， 包扎； 装订； 约束； 使结合， 使黏合', 5526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'trim', 'adj. 整齐的 vt. 使整齐', 5527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appreciate', 'vt. 重视， 赏识； 领会， 体会； 感谢； 增值', 5528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dental', 'adj. 牙齿的， 牙科的', 5529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'predictable', 'adj. 可预料的', 5530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'diverse', 'adj. 不一样的， 相异的； 多种多样的', 5531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'railway', 'n. 铁路', 5532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cube', 'adj. 清澈透明的 n. 立方形，立方', 5533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rally', 'v. 集合， 团结； 恢复， 重新振作 n. 集会；公路汽车赛', 5534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prime', 'adj. 首要的；最好的 n. 青春；全盛时期 vt. 使准备好', 5535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'happen', 'vi. 发生； 碰巧， 恰好', 5536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'festival', 'n. 节日； 音乐节', 5537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mild', 'adj. 温柔的； 温暖的； 轻微的', 5538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'profile', 'n. 侧面；人物简介；轮廓，形象；姿态，引人注目的状态 vt. 为…描绘； 写…的传略', 5539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'loyal', 'adj. 忠诚的， 忠心的', 5540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'preference', 'n. 喜爱， 偏爱； 偏爱的事物； 优先', 5541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impact', 'n. 影响， 作用， 冲击', 5542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'opportunity', 'n. 机会， 良机', 5543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'active', 'adj. 活跃的， 积极的； 主动的； 起作用的', 5544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dorm', 'n. 宿舍', 5545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'whichever', 'pron&adj. 无论哪个， 无论哪些', 5546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'court', 'n. 法院， 法庭； 庭院； 宫廷； 球场', 5547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'venture', 'v. 冒险， 敢于 n. 风险投资，风险项目', 5548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mill', 'v. 磨， 碾 n. 磨坊；碾磨机；制造厂，工厂', 5549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bucket', 'n. 水桶， 吊桶； 铲斗', 5550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'senior', 'adj. 资格较老的，地位较高的；年长的 n. 较年长者； 毕业班学生', 5551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dose', 'n. 剂量， 用量， 一剂', 5552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'route', 'n. 路线， 路程', 5553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'enthusiasm', 'n. 热情， 热心， 热忱； 巨大兴趣', 5554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'flexible', 'adj. 易弯曲的， 灵活的', 5555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adult', 'adj. 成年的； 成年人的， 适宜于成年人的 n. 成年人', 5556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'attitude', 'n. 态度， 看法； 姿势', 5557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relative', 'adj. 有关系的，相对的 n. 亲属， 亲戚', 5558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'organ', 'n. 器官； 机构； 管风琴； 新闻媒介', 5559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'average', 'adj. 平均的；平常的 v. 平均 n. 平均数，平均', 5560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'treatment', 'n. 待遇； 治疗， 疗法； 对待， 处理', 5561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compare', 'vt. 比较， 对照； 把…比作', 5562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pluralism', 'n. 多重性； 兼职， 兼任', 5563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'influential', 'adj. 有影响的； 有权势的', 5564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shiver', 'n&vi. 战栗， 颤抖', 5565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'Bible', 'n. 圣经', 5566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'liquor', 'n. 酒， 烈性酒', 5567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'honourable', 'adj. 光荣的； 可敬的； 正直的', 5568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'characteristic', 'adj. 特有的，典型的 n. 特性', 5569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'transparent', 'adj. 透明的； 易识破的； 明显的， 清楚的', 5570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interior', 'adj. 内部的；内地的 n. 内部', 5571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rouse', 'vt. 惊起； 唤起； 唤醒', 5572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'journal', 'n. 日报， 杂志， 日志', 5573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grasp', 'vt. 抓紧，握紧；理解 n. 抓； 理解', 5574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'involvement', 'n. 连累； 包含', 5575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spark', 'vi. 发出火花 n. 火花，火星', 5576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'unlike', 'adj. 不同的 prep. 不像…', 5577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assembly', 'n. 立法机构； 议会； 集合； 集会的人们； 装配， 组装', 5578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hearing', 'n. 听力， 听觉； 听力所及之距离； 意见听取会； 申辩的机会', 5579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'acquisition', 'n. 取得， 获得， 习得； 获得物， 增添的人', 5580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'volcano', 'n. 火山', 5581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rigid', 'adj. 严格的； 死板的； 刚硬的， 僵硬的', 5582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'deadline', 'n. 最后期限', 5583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'so-called', 'adj. 所谓的， 号称的', 5584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grateful', 'adj. 感激的； 令人愉快的', 5585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chip', 'n. 屑片， 碎片； 炸土豆条； 集成电路片， 集成块； 缺口， 瑕疵', 5586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chin', 'n. 颏， 下巴', 5587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emotional', 'adj. 感情的， 情绪的', 5588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'operational', 'adj. 运转的； 可使用的； 操作上的', 5589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'staff', 'n. 工作人员；参谋 vt. 为…配备人员', 5590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'involve', 'vt. 使卷入， 牵涉； 包含， 含有', 5591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'noticeable', 'adj. 显而易见的', 5592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assemble', 'v. 集合， 召集； 装配', 5593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'blast', 'n. 爆炸，冲击波；一阵 vt. 炸', 5594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'series', 'n. 一系列， 连续； 丛书， 连续剧', 5595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'complicated', 'adj. 复杂的， 难懂的', 5596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cultivate', 'vt. 耕作， 种植； 培养， 陶冶', 5597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'maximum', 'adj. 最大的， 最高的， 顶点的 n. 最大量，顶点', 5598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thrive', 'vi. 兴旺， 繁荣， 旺盛', 5599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'purse', 'n. 钱包， 女用小提包', 5600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'represent', 'vt. 作为…的代表； 表示， 象征； 描绘， 表现', 5601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compete', 'vi. 比赛， 竞争， 对抗', 5602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dialect', 'n. 方言， 土语， 地方话', 5603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accountant', 'n. 会计人员， 会计师', 5604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stocking', 'n. 长袜', 5605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dim', 'adj. 昏暗的；朦胧的；模糊不清的 v. 变暗淡', 5606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'emergency', 'n. 紧急情况， 突然事件', 5607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dip', 'v. 蘸，浸 n. 游一会儿泳', 5608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recreational', 'adj. 休养的； 娱乐的', 5609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'faculty', 'n. 才能， 能力； 系， 科； 全体教员', 5610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'trail', 'n. 痕迹，小径 vt. 跟踪， 追踪', 5611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'passport', 'n. 护照', 5612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prior', 'adj. 在前的； 优先的', 5613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'considerate', 'adj. 考虑周到的， 体贴的， 体谅的', 5614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'clue', 'n. 线索， 暗示， 提示', 5615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'legal', 'adj. 法律的； 合法的', 5616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bracket', 'n. 括号 vt. 把…归为同一类', 5617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'highway', 'n. 公路， 大路', 5618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vanish', 'v. 突然不见， 消失； 不复存在， 绝迹', 5619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'signal', 'adj. 显著的， 重大的 n. 信号，暗号；标志，表示 vt. 发信号；标志着', 5620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sightseeing', 'n. 观光， 游览', 5621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'parcel', 'n. 包裹，小包，邮包 vt. 分， 分配； 把…包起来， 捆扎', 5622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'static', 'adj. 静的，静态的；静止的，停滞的 n. 静电', 5623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'journey', 'vi. 旅行 n. 旅行，旅程', 5624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'planet', 'n. 行星', 5625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'finally', 'adv. 最后； 决定性地', 5626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'exhaust', 'vt. 使筋疲力尽；用尽；详尽论述 n. 排气装置； 废气', 5627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'creep', 'vi. 爬行， 缓慢地行进', 5628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'strap', 'n. 带子 vt. 捆扎； 用绷带包扎', 5629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grape', 'n. 葡萄， 葡萄藤', 5630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conviction', 'n. 确信； 坚定的信仰； 说服， 信服； 定罪， 判罪', 5631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scholar', 'n. 学者； 奖学金获得者', 5632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'straw', 'n. 稻草； 麦秆吸管， 吸管', 5633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'regarding', 'prep. 关于', 5634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'graph', 'n. 图， 图表', 5635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vision', 'n. 想象力； 梦幻； 视力， 视觉', 5636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accompany', 'vt. 陪伴， 陪同， 伴随； 为…伴奏', 5637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'petrol', 'n. 汽油', 5638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'acceptance', 'n. 接受； 承认； 容忍', 5639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relativity', 'n. 相对论； 相关性', 5640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beneficial', 'adj. 有利的， 有益的', 5641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tackle', 'vt. 对付，处理；与…交涉；阻截，擒抱 n. 阻截， 擒抱； 用具， 钓具； 辘轳， 滑车', 5642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reckon', 'vt. 认为， 估计； 指望， 盼望； 测算， 测量', 5643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'confusion', 'n. 困惑， 糊涂； 混淆； 骚乱', 5644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'occasion', 'n. 场合，时刻；重大活动；时机；起因 vt. 引起', 5645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'loan', 'n&v. 贷款， 借', 5646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'virtual', 'adj. 实质上的， 事实上的， 实际上的', 5647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'squeeze', 'v. 挤；压榨，榨取；捏，握 n. 挤； 握手； 拮据， 紧缺', 5648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'blank', 'adj. 空白的；茫然的，无表情的 n. 空白； 空白表格', 5649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'landlord', 'n. 地主， 房东； 店主', 5650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'session', 'n. 会议， 一届会期； 集会', 5651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'additional', 'adj. 附加的， 追加的', 5652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'worthy', 'adj. 有价值的， 值得的', 5653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'endless', 'adj. 无止境的', 5654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expectation', 'n. 期待， 期望， 预期； 前程， 成功的前景', 5655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'title', 'n. 标题， 题目； 称号， 头衔； 权利， 权益', 5656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mist', 'v. 蒙上薄雾； 模糊 n. 薄雾', 5657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'primarily', 'adv. 首先； 主要地', 5658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'duration', 'n. 持续， 持久', 5659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'plantation', 'n. 种植园， 人工林', 5660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ignore', 'vt. 不顾， 不理， 忽视', 5661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'loaf', 'vi. 游荡， 闲逛 n. 面包', 5662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nuclear', 'adj. 核子的， 核能的， 核武器的； 核心的', 5663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reception', 'n. 招待会， 欢迎会； 接受； 接待； 接收效果', 5664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'outward', 'adj. 外面的； 外表的； 向外的', 5665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bloody', 'adv. [用于加强语气]非常，很 adj. [用于加强语气]非常的；该死的；流血的；嗜杀的 vt. 血染', 5666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'poetry', 'n. 诗， 诗歌， 诗集', 5667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'owner', 'n. 物主， 所有人', 5668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vapour', 'n. 蒸汽', 5669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sole', 'adj. 单独的， 唯一的 n. 脚底，鞋底，袜底', 5670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'jury', 'n. 陪审团； 评奖团', 5671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'holy', 'adj. 神圣的， 圣洁的， 虔诚的', 5672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spelling', 'n. 拼字， 拼法， 拼写法', 5673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relax', 'v. 放松， 松弛； 放宽， 缓和', 5674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'priest', 'n. 神父， 牧师', 5675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'monitor', 'n. 班长；监视器，检测器；显示器 vt. 监听； 检测', 5676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'permission', 'n. 允许， 许可， 准许', 5677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grand', 'adj. 宏伟的； 重大的； 傲慢的； 派头大的； 绝佳的； 全部的', 5678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'schedule', 'n. 时刻表，日程安排表；清单，明细表 vt. 安排， 排定', 5679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'postage', 'n. 邮费， 邮资', 5680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'tame', 'adj. 驯服的，顺从的；沉闷的，乏味的 vt. 制服， 控制并利用； 驯化， 驯服', 5681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'material', 'adj. 物质的， 实体的； 肉体的； 重要的， 实质性的 n. 材料，素材', 5682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'universe', 'n. 宇宙， 世界； 领域， 范围', 5683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interpret', 'v. 解释， 说明； 口译', 5684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spectacular', 'adj. 壮观的，引人注目的 n. 壮观的演出； 惊人之举', 5685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inherit', 'vi. 成为继承人 vt. 继承', 5686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'peculiar', 'adj. 奇怪的， 古怪的； 特有的', 5687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'blanket', 'n. 毛毯， 毯子， 羊毛毯', 5688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grant', 'n. 授予物；补助金 vt. 授予， 给予； 同意', 5689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'injection', 'n. 注射， 注入； 充满', 5690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'envy', 'n. 妒忌，羡慕；妒忌的对象 vt. 妒忌， 羡慕', 5691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hut', 'n. 小屋， 棚屋', 5692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'invincible', 'adj. 不能征服的， 无敌的', 5693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'discount', 'n. 折扣 vt. 将…打折扣； 不信； 漠视， 低估', 5694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'convert', 'v. 转变， 转化； 改变', 5695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'construct', 'vt. 建造； 构思 n. 建筑物； 构想， 观念', 5696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'attempt', 'vt. 尝试， 试图， 努力', 5697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thick', 'adv. 厚厚地 adj. 厚的，密的，浓的；不清楚的，口音重的', 5698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'superficial', 'adj. 表面的， 肤浅的', 5699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'division', 'n. 分， 分配； 除法； 分歧； 分裂', 5700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'executive', 'adj. 执行的 n. 执行者', 5701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'navigation', 'n. 航行， 航海， 航空； 导航， 领航', 5702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'melt', 'v. 融化； 熔化； 消散', 5703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'hook', 'v. 钩住 n. 钩，挂钩', 5704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stale', 'adj. 不新鲜的； 陈腐的， 过时的', 5705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'balance', 'vt. 使平衡；称；权衡，比较 n. 天平； 平衡； 结存， 结欠', 5706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cigar', 'n. 雪茄烟', 5707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'action', 'n. 行动； 已做的事； 作用， 功能； 情节', 5708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stadium', 'n. 运动场， 体育场', 5709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'whereas', 'conj. 然而， 但是， 尽管', 5710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pitch', 'vi. 投， 掷； 架设， 搭， 营； 颠簸 n. 球场；程度，强度；高度；音高；沥青 vt. 投掷；使猛然倒下；表达；把…定于特定程度；定调', 5711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'kindness', 'n. 仁慈， 好意', 5712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'adoptive', 'adj. 收养关系的； 采用的', 5713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'chop', 'vt. 砍，劈；切细 n. 排骨', 5714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'electrical', 'adj. 电的， 电气科学的', 5715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'statue', 'n. 塑像， 雕像， 铸像', 5716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'being', 'n. 存在； 生物， 生命', 5717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sensitive', 'adj. 敏感的， 灵敏的， 神经过敏的； 容易生气的， 易受伤害的', 5718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'protest', 'v. 抗议， 反对 n. 抗议， 反对', 5719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'classification', 'n. 分类， 分级， 分类法； 类别， 级别', 5720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vacant', 'adj. 空的， 未被占用的； 空缺的； 茫然的， 空虚的', 5721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'physicist', 'n. 物理学家', 5722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'afford', 'vt. 担负得起； 提供', 5723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'underground', 'adv. 在地下，往地下；秘密地，不公开地 adj. 地下的；秘密的，不公开的 n. 地铁； 地下组织', 5724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'curse', 'v. 诅咒，咒骂 n. 天谴； 祸害， 祸根', 5725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impression', 'n. 印象； 印记', 5726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'baseball', 'n. 棒球', 5727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'interval', 'n. 间隔， 间距； 幕间休息', 5728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evaluate', 'vt. 评价； 估…的价', 5729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'machinery', 'n. 机器， 机械', 5730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'status', 'n. 地位， 身份； 情形， 状况', 5731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shield', 'n. 防护物，护罩；盾 vt. 保护， 防护', 5732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'upset', 'adj. 心烦的， 苦恼的； 不适的 vt. 使心烦意乱，使苦恼，使不适；搅乱；弄翻，倾覆 n. 翻倒；搅乱；不安；不适', 5733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inference', 'n. 推断结果， 结论； 推论， 推理， 推断', 5734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'curve', 'v. 弯曲 n. 曲线，弯，弯曲处', 5735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dot', 'n. 点，圆点 vt. 打点于', 5736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'skim', 'v. 撇去， 掠过， 擦过； 浏览， 略读', 5737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'phenomenon', 'n. 现象', 5738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'notify', 'vt. 通知， 告知， 报告', 5739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mention', 'n&vt. 提及， 说起', 5740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stream', 'v. 流出， 涌出 n. 河，溪流；一股，一串', 5741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'laundry', 'n. 洗衣房， 洗衣店； 待洗的衣服， 洗好的衣服', 5742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accumulate', 'v. 积累， 堆积', 5743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crime', 'n. 罪， 罪行， 犯罪', 5744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'heave', 'vi. 起伏，隆起；呕吐，恶心 vt. 举起，提起，拉起，拖；扔；发出 n. 举起； 起伏， 升降', 5745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leisure', 'n. 空闲时间； 悠闲', 5746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nourish', 'vt. 提供养分， 养育', 5747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'surround', 'vt. 围， 围绕； 圈住', 5748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mat', 'n. 席子， 垫子', 5749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cigarette', 'n. 香烟， 纸烟， 卷烟', 5750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'torch', 'n. 火炬， 火把； 手电筒', 5751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'positive', 'adj. 确实的， 明确的； 积极的， 肯定的', 5752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'favourite', 'adj. 特别受喜爱的 n. 特别受喜爱的人', 5753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'menu', 'n. 菜单', 5754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prospect', 'v. 勘探， 勘察 n. 前景， 前途， 可能性； 景象， 景色； 可能成为主顾的人； 有希望的候选人', 5755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'radar', 'n. 雷达', 5756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'refugee', 'n. 难民', 5757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'aluminium', 'n. 铝', 5758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comparable', 'adj. 可比较的； 类似的； 比得上的', 5759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'specialize', 'vi. 成为…专家； 专攻', 5760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rotate', 'v. 旋转， 转动； 轮流', 5761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'instance', 'n. 例子， 实例， 事例', 5762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'opera', 'n. 歌剧', 5763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'presumably', 'adv. 大概， 可能， 据推测', 5764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conscience', 'n. 良心， 道德心', 5765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'subject', 'n. 题目； 学科； 主语 vt. 使隶属', 5766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'practically', 'adv. 几乎， 简直； 实际上', 5767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'recognition', 'n. 认出， 识别； 承认； 赏识， 表彰， 报偿', 5768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'cassette', 'n. 盒式录音带', 5769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'blade', 'n. 刀刃， 刀片， 叶片', 5770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'arrangement', 'n. 整理， 排列， 安排； 准备工作', 5771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'revenue', 'n. 收入， 收益； 税收， 岁入', 5772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'strip', 'v. 脱光衣服；剥夺，夺去 n. 条带', 5773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'solution', 'n. 解决； 解决办法； 溶液', 5774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'continuous', 'adj. 连续不断的； 延伸的', 5775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'opponent', 'n. 对手， 敌手， 对抗者', 5776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accelerate', 'vt. 使加快， 使增速', 5777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'backward', 'adv. [-]倒； 向后， 往回 adj. 向后的，倒的；落后的，进步慢的', 5778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'grain', 'n. 谷物， 谷粒； 颗粒； 少量， 微量', 5779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'maid', 'n. 女仆， 侍女', 5780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'residence', 'n. 住处， 住宅； 居住； 居住资格', 5781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'credit', 'n. 信贷，赊欠；赞扬，荣誉；学分；信任 vt. 相信； 把…记入贷方； 把…归于', 5782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'regardless', 'adv. 不顾后果地； 不管怎样， 无论如何', 5783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'oxygen', 'n. 氧， 氧气', 5784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intensive', 'adj. 加强的； 精深的， 透彻的； 精耕细作的', 5785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'alter', 'vt. 改变， 变更， 变动', 5786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'combine', 'v. 结合， 联合； 化合 n. 联合企业； 联合收割机', 5787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ideal', 'adj. 理想的；观念的；空想的 n. 理想； 理想的东西', 5788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bearing', 'n. 举止， 风度； 方位， 方向感； 影响', 5789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'illustrate', 'vt. 说明', 5790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'occur', 'vi. 发生， 出现， 存在； 被想起， 被想到', 5791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comedy', 'n. 喜剧， 喜剧性', 5792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'broom', 'n. 扫帚', 5793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'establishment', 'n. 建立， 设立， 确立； 企业； 当权人物', 5794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pressure', 'n. 压，压强；压迫 vt. 对…施加压力， 迫使', 5795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'breeze', 'vi. 飘然而行 n. 微风，和风', 5796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'trash', 'n. 垃圾，废物；拙劣的文学作品；没用的人，社会渣滓，败类 vt. 捣毁， 破坏', 5797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'painter', 'n. 漆工； 画家', 5798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'millimetre', 'n. 毫米', 5799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'horn', 'n. 角； 号角； 警报器', 5800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'specialist', 'n. 专家', 5801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'infer', 'vt. 推论， 推断； 猜想', 5802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compass', 'n. 罗盘， 指南针； 圆规； 界限， 范围', 5803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'background', 'n. 出身背景， 经历； 背景资料； 背景， 底子', 5804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sore', 'adj. 痛的；恼火的；急剧的，剧烈的 n. 疮， 痛处', 5805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dispose', 'vt. 处理， 解决； 使倾向于', 5806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'glow', 'v. 发白热光 n. 白热光；脸红；激情', 5807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'curtain', 'n. 门帘， 窗帘； 幕', 5808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'laughter', 'n. 笑， 笑声', 5809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'constitution', 'n. 宪法， 章程； 组成； 设立', 5810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'blend', 'n&v. 混合', 5811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'certificate', 'n. 证书， 证件， 执照', 5812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mess', 'n. 凌乱状态，混乱的局面；困境 vt. 弄糟， 弄脏， 搞乱', 5813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sour', 'adj. 酸的；馊的，酸味的；脾气坏的 v. 变酸， 变馊； 变得乖戾', 5814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'delete', 'vt. 删除， 擦掉', 5815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nonsense', 'n. 胡说， 废话； 冒失的行动', 5816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stain', 'vt. 玷污；给…着色 n. 污点， 污迹', 5817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'transform', 'vt. 使改观， 改革； 变换， 把…转换成', 5818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'leadership', 'n. 领导', 5819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'genuine', 'adj. 真的， 真正的； 真诚的', 5820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'X-ray', 'n. X射线， X光', 5821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'physical', 'adj. 身体的； 物理的； 物质的， 有形的', 5822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fulfil', 'vt. 履行， 实现， 完成； 满足， 使满意', 5823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wicked', 'adj. 坏的， 令人厌恶的； 淘气的， 顽皮的', 5824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spokesman', 'n. 发言人', 5825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'equation', 'n. 方程， 等式', 5826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impressive', 'adj. 给人深刻印象的', 5827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'compound', 'adj. 复合的， 化合的 n. 化合物，复合物；复合词 vt. 使恶化， 加重； 使化合， 使合成', 5828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'structure', 'n. 结构，构造 vt. 建造', 5829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intensity', 'n. 强烈， 剧烈； 强度', 5830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'waken', 'v. 醒来， 弄醒', 5831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stake', 'n. 桩；利害关系；股份；赌金，赌注 vt. 以…打赌， 拿…冒险', 5832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'extraordinary', 'adj. 非同寻常的， 特别的', 5833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'witness', 'n. 证据；目击者，证人 vt. 目击； 为…作证， 证明', 5834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'concerning', 'prep. 关于', 5835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'attraction', 'n. 吸引， 吸引力； 引力； 具有吸引力的事物', 5836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conventional', 'adj. 普通的； 习惯的， 常规的； 因循守旧的', 5837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'regulation', 'n. 规章， 规则； 管理， 控制； 调节', 5838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'puzzle', 'v. 迷惑，为难；苦思 n. 智力测验； 谜， 难题， 令人费解的事； 困惑， 迷惑', 5839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'circulation', 'n. 循环； 流传； 发行， 流通', 5840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bake', 'vt. 烤， 烘， 焙', 5841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mere', 'adj. 仅仅的； 纯粹的', 5842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accommodation', 'n. 住处； 膳宿', 5843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evident', 'adj. 明显的， 明白的', 5844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'suburb', 'n. 郊区， 郊外， 近郊', 5845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lodge', 'v. 暂住，借宿 n. 乡间小屋； 旅舍', 5846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'threat', 'n. 威胁， 恐吓； 凶兆， 征兆', 5847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'writer', 'n. 作者， 作家', 5848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'simplify', 'vt. 简化， 使简明', 5849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'breast', 'n. 乳房； 胸脯， 胸膛', 5850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'invention', 'n. 发明， 创造； 捏造', 5851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mercy', 'n. 仁慈， 宽容； 恩惠； 幸运', 5852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'annoy', 'vt. 使恼怒； 打搅', 5853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'curl', 'n. 鬈发； 卷曲， 卷曲物', 5854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inform', 'vi. 告发， 告密 vt. 通知；报告', 5855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'psychological', 'adj. 心理的', 5856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'glue', 'n. 胶，胶水 vt. 胶合', 5857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'commit', 'vt. 犯， 干； 使承诺； 把…托付给； 调拨…供使用， 拨出', 5858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scream', 'vi. 尖叫，呼啸 n. 尖叫声', 5859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sorrow', 'n. 悲痛， 悲哀， 悲伤； 伤心事， 不幸的事', 5860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crash', 'vi. 发出撞击声；垮台，破产；冲，闯 vt. 碰撞；坠落 n. 碰撞； 破裂声', 5861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'patch', 'n. 补丁；斑，与周围不同的部分；一小块地 vt. 补， 修补', 5862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'observer', 'n. 观察员， 观察者', 5863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'character', 'n. 性格， 特性； 性质； 人物， 角色； 符号； 字', 5864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reflect', 'v. 反映， 显示； 反射， 映现； 深思， 考虑， 反省', 5865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'procession', 'n. 队伍， 行列', 5866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'contribution', 'n. 贡献， 促成作用； 捐款， 捐献物； 稿件', 5867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'Marxist', 'adj. 马克思主义的 n. 马克思主义者', 5868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bang', 'vi. 猛击， 猛撞； 发出砰的一声， 砰砰地响 n. 巨响，枪声；猛击 vt. 猛击，猛撞；砰地敲', 5869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'brow', 'n. 额， 眉， 眉毛', 5870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'meaning', 'n. 意义， 意思； 目的； 重要性', 5871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ignorant', 'adj. 不知道的， 无知的', 5872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'magnetic', 'adj. 磁的； 有吸引力的', 5873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'band', 'n. 乐队；群，伙；带；条纹；波段 vt. 用带绑扎', 5874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'orbit', 'n. 轨道 vt. 做轨道运行', 5875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'comprise', 'vt. 包含， 包括， 构成', 5876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'moderate', 'adj. 中等的； 温和的， 稳健的； 有节制的 v. 和缓， 减轻； 节制', 5877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'resident', 'adj. 居住的， 定居的； 住校的， 住院的 n. 居民，定居者；住院医生', 5878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spray', 'v. 喷， 溅散 n. 浪花，水花；喷雾', 5879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'distinguish', 'vt. 区别， 辨别， 识别； 使显出特色， 使杰出', 5880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'receiver', 'n. 听筒； 接收器', 5881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'outer', 'adj. 外面的， 外层的', 5882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'invent', 'vt. 发明， 创造； 捏造', 5883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fluent', 'adj. 流利的， 流畅的', 5884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shortcoming', 'n. 短处， 缺点', 5885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'substantial', 'adj. 可观的， 大量的； 结实的， 坚固的； 实质的， 真实的', 5886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'execute', 'vt. 将…处死； 实施， 执行', 5887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'benefit', 'v. 有益于； 得益 n. 利益，恩惠；救济金，保险金，津贴', 5888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'flood', 'v. 淹没； 涌入 n. 洪水；大量', 5889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vitamin', 'n. 维生素', 5890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'intention', 'n. 意图， 意向， 目的', 5891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'rude', 'adj. 粗鲁的， 不礼貌的； 粗糙的， 粗陋的', 5892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'symptom', 'n. 症状； 征候， 征兆', 5893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'pillar', 'n. 柱， 柱子； 栋梁', 5894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thereby', 'adv. 因此， 从而， 由此', 5895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'unique', 'adj. 唯一的， 独一无二的； 极不寻常的， 极好的', 5896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'funeral', 'n. 葬礼， 丧礼， 丧葬', 5897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'boost', 'vt. 提高，使增长；推动，激励；替…做广告，宣扬 n. 提高， 增长； 推动， 激励', 5898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fireman', 'n. 消防队员； 司炉工', 5899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'sincere', 'adj. 真诚的， 诚挚的', 5900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'male', 'adj. 男的，雄的 n. 男子， 雄性动物', 5901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ministry', 'n. 部', 5902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'religious', 'adj. 宗教的； 笃信宗教的， 虔诚的', 5903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'nevertheless', 'adv. 仍然， 然而', 5904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'prominent', 'adj. 突出的， 杰出的； 突起的， 凸出的', 5905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shelter', 'n. 掩蔽处，躲避处；住所；掩蔽，保护 vt. 掩蔽， 庇护； 躲避', 5906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'outset', 'n. 开始， 开端', 5907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'jewel', 'n. 宝石； 宝石饰物', 5908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'scan', 'vt. 细看，审视；扫描，浏览 n. 扫描', 5909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'association', 'n. 协会， 团体； 联合， 交往', 5910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fundamental', 'adj. 基础的，基本的 n. 基本原则', 5911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'eliminate', 'vt. 消灭， 消除， 排除； 淘汰', 5912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'global', 'adj. 全球的， 全世界的； 总的， 完整的', 5913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'entitle', 'vt. 给…权利； 给题名', 5914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'outline', 'n. 提纲，要点；外形，略图 vt. 概述； 描…外形', 5915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fade', 'vi. 褪色；逐渐消失；凋谢 vt. 使褪色', 5916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'unless', 'conj. 除非， 如果不', 5917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'butterfly', 'n. 蝴蝶', 5918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'excess', 'adj. 过量的， 额外的 n. 超越； 过量， 过度', 5919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'glance', 'vi. 看一下 n. 一瞥 vt. 用扫视； 反射', 5920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'perspective', 'n. 视角， 观点； 远景， 景观； 透视画法， 透视图', 5921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'relationship', 'n. 关系， 关联', 5922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'equality', 'n. 等同， 平等， 相等', 5923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'destruction', 'n. 破坏， 毁灭， 消灭', 5924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dictation', 'n. 口授； 听写', 5925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'stiff', 'adv. 极其， 非常； 僵硬地 adj. 硬的，僵直的；不灵活的；拘谨的，生硬的；费劲的；强烈的', 5926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'expression', 'n. 词语； 表达； 表情', 5927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'invade', 'vt. 入侵， 侵略， 侵袭', 5928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reaction', 'n. 反应； 反作用', 5929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'childhood', 'n. 童年， 幼年， 早期', 5930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wolf', 'n. 狼', 5931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'accordance', 'n. 一致； 和谐', 5932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'thorough', 'adj. 彻底的， 详尽的', 5933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appeal', 'vi. 呼吁，恳求；申诉，上诉 vt. 上诉 n. 感染力， 吸引力； 呼吁， 上诉', 5934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'democracy', 'n. 民主， 民主制； 民主国家', 5935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'transportation', 'n. 运输， 运送， 客运', 5936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dye', 'vt. 染 n. 染料； 染色', 5937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'evolve', 'vt. 使进化， 使发展', 5938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'extensive', 'adj. 广阔的， 广泛的', 5939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'congratulation', 'n. 贺词； 祝贺， 恭喜', 5940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'abandon', 'vt. 离弃，丢弃；遗弃，抛弃；放弃 n. 放任； 纵情', 5941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'definitely', 'adv. 一定地， 明确地', 5942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inspire', 'vi. 吸气； 赋予灵感 vt. 鼓舞，给…以灵感', 5943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'marvelous', 'adj. 奇迹般的， 了不起的', 5944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'household', 'adj. 家庭的； 家喻户晓的 n. 家庭，户；家务', 5945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'geometry', 'n. 几何， 几何学', 5946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ratio', 'n. 比， 比率', 5947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'devote', 'vt. 将…奉献给； 把…专用', 5948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'agent', 'n. 代理人， 代理商； 政府代表； 动因， 原因； 剂', 5949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wool', 'n. 羊毛； 毛线， 绒线', 5950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'wholly', 'adv. 完全地， 全部地', 5951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'instinct', 'n. 本能， 天性； 直觉', 5952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'approximate', 'adj. 近似的 vt. 近似； 估计', 5953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'invest', 'v. 投资， 投入； 授予', 5954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'afterward', 'adv. 后来， 以后', 5955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'reputation', 'n. 名誉， 名气， 名声', 5956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'project', 'v. 伸出； 投射； 预计 n. 方案， 计划； 课题， 项目； 工程', 5957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'shrug', 'n&v. 耸肩', 5958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'independence', 'n. 独立， 自主， 自立', 5959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'coordination', 'n. 同等； 调和', 5960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'presentation', 'n. 提供， 显示； 外观， 图像； 授予， 赠送； 报告， 介绍； 表演', 5961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'diameter', 'n. 直径', 5962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'barn', 'n. 谷仓； 牲口棚', 5963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bark', 'vi. 吠，叫 n. 吠声， 叫声； 树皮', 5964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'loop', 'v. 成环， 成圈 n. 圈，环，回路；循环', 5965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'restrain', 'vt. 阻止， 控制； 抑制， 遏制', 5966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'greedy', 'adj. 贪吃的； 贪婪的； 渴望的', 5967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'awkward', 'adj. 笨拙的， 尴尬的； 难操纵的， 使用不便的； 不灵巧的', 5968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'bare', 'adj. 赤裸的；光秃的，无遮盖的；刚刚够的，勉强的 vt. 露出， 显露', 5969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'ruin', 'v. 毁坏 n. 毁灭；废墟', 5970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'crane', 'n. 起重机， 摄影升降机； 鹤', 5971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beard', 'n. 胡须， 络腮胡子', 5972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'impatient', 'adj. 不耐烦的， 急躁的', 5973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'spill', 'v. 溢出，洒落 n. 溢出', 5974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'owing', 'adj. 应付的， 未付的', 5975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'collection', 'n. 搜集， 聚集， 积聚； 收集， 收取； 收藏品， 收集的东西', 5976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gardener', 'n. 园丁， 花匠', 5977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conquest', 'n. 攻取， 征服， 克服', 5978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'finding', 'n. 发现； 调查的结果； 裁决', 5979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'dense', 'adj. 密集的， 浓厚的； 密度大的', 5980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'fortnight', 'n. 两星期， 十四天', 5981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'laboratory', 'n. 实验室， 研究室', 5982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'inspect', 'vi. 进行检查； 进行视察 vt. 检查，审查；检阅', 5983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'campaign', 'vi. 参加运动； 参加竞选 n. 战役；运动', 5984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'systematical', 'adj. 有系统的， 有计划的', 5985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'vital', 'adj. 致命的， 生死攸关的； 极其重要的； 生命的， 有生命力的', 5986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'conflict', 'vi. 冲突， 抵触 n. 冲突， 抵触， 争论； 战斗， 战争', 5987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'farewell', 'n. 告别， 欢送会', 5988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'allow', 'vt. 允许， 准许； 同意给； 承认； 允许…进入', 5989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'appliance', 'n. 用具， 器具， 器械； 家电', 5990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'mass', 'adj. 大量的，大规模的 v. 聚集， 集中 n. 众多，大量；团，块，堆；群众；质量', 5991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'lord', 'n. 领主， 君主， 贵族', 5992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'detect', 'vt. 察觉， 发觉； 侦查出', 5993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'amateur', 'adj. 业余爱好的， 业余的； 外行的 n. 业余爱好者；外行', 5994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'poisonous', 'adj. 有毒的； 恶毒的', 5995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'condemn', 'vt. 谴责， 指责； 判…刑， 宣告…有罪', 5996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'beast', 'n. 兽， 野兽， 牲畜； 凶残的人， 令人厌憎的人', 5997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'assistance', 'n. 协助， 援助', 5998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'commerce', 'n. 商业， 贸易； 社交', 5999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (7, 'gesture', 'v. 做手势 n. 姿势，手势，姿态', 6000);
