INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'line', 'n. 路线，航线；排；绳 v. 排成一行；划线于；以线条标示；使…起皱纹', 501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bag', 'n. 袋；猎获物；（俚）一瓶啤酒 v. 猎获；把…装入袋中；占据，私吞；使膨大', 502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sail', 'v. 航行；启航，开船 n. 帆，篷；航行', 503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'untrue', 'adj. 不真实的；不合标准的；不忠实的；不正当的', 504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reading', 'n. 阅读，朗读；读物；读数 adj. 阅读的 v. 阅读（read的ing形式）', 505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'toward', 'prep. 向；对于；为了；接近 adj. 即将来到的，进行中的 n. (Toward)人名；(英)特沃德', 506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'discrimination', 'n. 歧视；区别，辨别；识别力', 507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interval', 'n. 间隔；间距；幕间休息', 508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'outgoing', 'adj. 对人友好的，开朗的；出发的，外出的；即将离职的；乐于助人的 n. 外出；流出；开支 v. 超过；优于（outgo的ing形式）', 509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'subtraction', 'n. [数] 减法；减少；差集', 510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'kid', 'n. 小孩；小山羊 v. 欺骗；取笑；戏弄 adj. 小山羊皮制的；较年幼的', 511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'singer', 'n. 歌手，歌唱家', 512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hire', 'n. 雇用，租用；租金，工钱 v. 雇用；出租', 513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Scottish', 'adj. 苏格兰的；苏格兰人的；苏格兰语的 n. 苏格兰人；苏格兰语', 514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deadline', 'n. 截止期限，最后期限', 515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rob', 'v. 抢劫；使…丧失；非法剥夺', 516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'April', 'n. 四月', 517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'truck', 'n. 卡车；交易；手推车 v. 驾驶卡车；以物易物 adj. （美）运货汽车的', 518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gallery', 'n. 画廊；走廊；旁听席；地道 vt. 在…修建走廊；在…挖地道 vi. 挖地道', 519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stove', 'n. 火炉；窑；温室 vt. 用火炉烤', 520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Pacific', 'adj. 太平洋的 n. 太平洋', 521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ripen', 'v. 使成熟', 522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'glad', 'adj. 高兴的；乐意的；令人高兴的；灿烂美丽的 vt. 使高兴 n. (Glad)人名；(塞、瑞典)格拉德；(英)格莱德；(法、挪)格拉', 523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'inch', 'n. 英寸；身高；少许 v. 使缓慢地移动', 524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'teach', 'v. 教；教授；教导 n. (Teach)人名；(英)蒂奇', 525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sausage', 'n. 香肠；腊肠；装香肠的碎肉', 526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'northeast', 'adj. 东北的；向东北的；来自东北的 n. 东北 adv. 向东北；来自东北', 527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'insurance', 'n. 保险；保险费；保险契约；赔偿金', 528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'messy', 'adj. 凌乱的，散乱的；肮脏的，污秽的；麻烦的', 529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'countryside', 'n. 农村，乡下；乡下的全体居民', 530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'teapot', 'n. 茶壶', 531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'staff', 'n. 职员；参谋；棒；支撑 adj. 职员的；行政工作的 v. 供给人员；给…配备职员', 532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'canteen', 'n. 食堂，小卖部；水壶', 533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'touch', 'v. 接触；触动；使轻度受害 n. 接触；触觉；格调；少许', 534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'are', 'v. 是（be的第二人称单复数现在式） n. 公亩', 535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fairness', 'n. 公平；美好；清晰；顺利性', 536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'report', 'n. 报告；报道；成绩单 v. 报告；报导；使报到', 537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'neck', 'n. 脖子；衣领；海峡 v. 搂著脖子亲吻；变狭窄', 538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'member', 'n. 成员；会员；议员', 539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'constitution', 'n. 宪法；体制；章程；构造；建立，组成；体格', 540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pass', 'n. 及格；经过；护照；途径；传球 v. 经过；传递；变化；终止', 541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'medical', 'adj. 医学的；药的；内科的 n. 医生；体格检查', 542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jam', 'n. 果酱；拥挤；困境；扣篮 v. 使堵塞；挤进，使塞满；混杂；压碎', 543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'behalf', 'n. 代表；利益', 544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'govern', 'v. 管理；支配；统治；控制 n. (Govern)人名；(英)戈文', 545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cross', 'n. 交叉，十字；十字架，十字形物 v. 交叉；杂交；横过 adj. 交叉的，相反的；乖戾的；生气的', 546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fifth', 'adj. 第五的；五分之一的 n. 第五；五分之一 num. 第五', 547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dawn', 'n. 黎明；开端 v. 破晓；出现；被领悟', 548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diverse', 'adj. 不同的；多种多样的；变化多的', 549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'someone', 'pron. 有人，某人', 550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'skateboard', 'n. 溜冰板 v. 用滑板滑行', 551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wish', 'n. 希望；祝福；心愿 v. 祝愿；渴望；向…致问候语', 552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'smell', 'v. 嗅，闻；有…气味 n. 气味，嗅觉；臭味', 553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'matter', 'n. 物质；事件 v. 有关系；要紧', 554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'barbecue', 'n. 烤肉；吃烤肉的野宴 v. 烧烤；烤肉', 555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aside', 'adv. 离开，撇开；在旁边 n. 旁白；私语，悄悄话；离题的话 prep. 在…旁边', 556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appreciate', 'v. 欣赏；感激；领会；鉴别', 557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lake', 'n. 湖；深红色颜料；胭脂红 vt. （使）血球溶解 vi. （使）血球溶解', 558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'my', 'pron. 我的 int. 哎呀（表示惊奇等）；喔唷 n. (My)人名；(越)美；(老、柬)米', 559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plate', 'n. 碟；金属板；金属牌；感光底片 v. 电镀；给…装甲', 560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'approximately', 'adv. 大约，近似地；近于', 561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diet', 'n. 饮食；食物；规定饮食 v. 节食', 562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'way', 'n. 方法；道路；方向；行业；习惯 adv. 大大地；远远地 adj. 途中的', 563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diamond', 'n. 钻石，金刚石；菱形；方块牌 adj. 菱形的；金刚钻的', 564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'remain', 'v. 保持；依然；留下；剩余；逗留；残存 n. 遗迹；剩余物，残骸', 565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aircraft', 'n. 飞机，航空器', 566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'curtain', 'n. 幕；窗帘 v. 遮蔽；装上门帘', 567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dig', 'v. 挖，掘；探究 n. 戳，刺；挖苦', 568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Scotland', 'n. 苏格兰', 569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'age', 'n. 年龄；时代；寿命，使用年限；阶段 v. 成熟；变老', 570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bamboo', 'n. 竹，竹子 vt. 为…装上篾条 adj. 竹制的；土著居民的', 571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'arch', 'n. 弓形，拱形；拱门 adj. 主要的 v. 使…弯成弓形；用拱连接', 572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'poet', 'n. 诗人', 573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fan', 'v. 煽动；刺激；吹拂 n. 迷；风扇；爱好者', 574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'breast', 'n. 乳房，胸部；胸怀；心情 v. 以胸对着；与…搏斗', 575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sleeve', 'n. [机] 套筒，[机] 套管；袖子，[服装] 袖套 vt. 给……装袖子；给……装套筒', 576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mentally', 'adv. 精神上，智力上；心理上', 577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'power', 'n. 力量，能力；电力，功率；政权，势力；[数] 幂 v. 激励；供以动力；使…有力量 adj. 借影响有权势人物以操纵权力的', 578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'via', 'prep. 渠道，通过；经由', 579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tick', 'v. 标记号于；滴答地记录 n. 滴答声；扁虱；记号；赊欠', 580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relax', 'v. 放松，休息；松懈，松弛；变从容；休养', 581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'drawing', 'n. 图画；牵引；素描术 v. 绘画；吸引（draw的ing形式）；拖曳', 582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rough', 'adj. 粗糙的；粗略的；粗野的；艰苦的；未经加工的 v. 使粗糙；粗暴对待；草拟 n. 艰苦；高低不平的地面；未经加工的材料；粗糙的部分 adv. 粗糙地；粗略地；粗暴地', 583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'systematic', 'adj. 系统的；体系的；有系统的；[图情] 分类的；一贯的，惯常的', 584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'barber', 'v. 为…理发；修整 n. 理发师', 585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'trouble', 'n. 麻烦；烦恼；故障；动乱 v. 麻烦；使烦恼；折磨', 586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'male', 'adj. 男性的；雄性的；有力的 n. 男人；雄性动物', 587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'production', 'n. 成果；产品；生产；作品', 588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'down', 'adv. 向下，下去；在下面 adj. 向下的 n. 软毛，绒毛；[地质] 开阔的高地 prep. 沿着，往下 v. 打倒，击败', 589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'liquid', 'adj. 液体的；清澈的；明亮的；易变的 n. 液体，流体；流音', 590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adolescence', 'n. 青春期', 591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'neighbour', 'n. n邻居;同胞；仁慈的人 v. 邻接 adj. 邻居的；邻近的', 592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'potential', 'n. 潜能；可能性；[电] 电势 adj. 潜在的；可能的；势的', 593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'first', 'adv. 第一；首先；优先；宁愿 n. 第一；开始；冠军 adj. 第一的；基本的；最早的 num. 第一', 594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'diagram', 'n. 图表；图解 v. 用图解法表示', 595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'memory', 'n. 记忆，记忆力；内存，[计] 存储器；回忆', 596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unhappy', 'adj. 不快乐的；不幸福的；不适当的', 597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'distant', 'adj. 遥远的；冷漠的；远隔的；不友好的，冷淡的', 598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fence', 'n. 栅栏；围墙；剑术 v. 防护；用篱笆围住；练习剑术', 599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'crowd', 'n. 群众,一伙;一堆,许多,大众 v. 拥挤,挤满,挤进', 600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'function', 'n. 功能；[数] 函数；职责；盛大的集会 v. 运行；活动；行使职责', 601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bird', 'n. 鸟；家伙；羽毛球 v. 向…喝倒彩；起哄', 602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'classify', 'v. 分类；分等', 603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'explicit', 'adj. 明确的；清楚的；直率的；详述的', 604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lightning', 'adj. 闪电的；快速的 n. 闪电 vi. 闪电', 605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'step', 'n. 步，脚步；步骤；步伐；梯级 v. 踏，踩；走', 606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jog', 'v. 慢跑；轻推；蹒跚行进；使颠簸 n. 慢跑；轻推，轻撞', 607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'already', 'adv. 已经，早已；先前', 608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'night', 'n. 夜晚，晚上；黑暗，黑夜 adj. 夜晚的，夜间的', 609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'drawer', 'n. 抽屉；开票人；出票人；起草者；酒馆侍', 610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wooden', 'adj. 木制的；僵硬的，呆板的', 611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accessible', 'adj. 易接近的；可进入的；可理解的', 612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'passive', 'adj. 被动的，消极的；被动语态的 n. 被动语态', 613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wonder', 'n. 惊奇；奇迹；惊愕 v. 怀疑；想知道；惊讶 adj. 奇妙的；非凡的', 614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ought', 'aux. 应该，应当；大概 vi. 应该，应当；大概', 615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'transform', 'v. 改变，使…变形；转换', 616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'defend', 'v. 辩护；防护', 617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'kilometre', 'n. [计量] 公里；[计量] 千米', 618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'talk', 'v. 说；谈话；讨论 n. 谈话；演讲；空谈', 619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'girl', 'n. 女孩；姑娘，未婚女子；女职员，女演员；（男人的）女朋友', 620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ambassador', 'n. 大使；代表；使节', 621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grass', 'n. 草；草地，草坪 v. 放牧；使……长满草；使……吃草', 622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'billion', 'n. 十亿；大量 num. 十亿 adj. 十亿的', 623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'summary', 'adj. 简易的；扼要的 n. 概要，摘要，总结', 624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Moslem', 'adj. 穆斯林的；伊斯兰教的；回教的 n. 穆斯林；穆罕默德信徒；伊斯兰', 625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wire', 'n. 电线；金属丝；电报 v. 拍电报；给…装电线', 626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'morning', 'n. 早晨；黎明；初期', 627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'depend', 'v. 依赖，依靠；取决于；相信，信赖', 628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fold', 'v. 折叠；合拢；抱住；笼罩 n. 折痕；信徒；羊栏', 629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'precise', 'adj. 精确的；明确的；严格的', 630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'quick', 'n. 核心；伤口的嫩肉 adj. 快的；迅速的，敏捷的；灵敏的 adv. 迅速地，快', 631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'conference', 'n. 会议；讨论；协商；联盟；（正式）讨论会；[工会、工党用语]（每年的）大会 vi. 举行或参加（系列）会议', 632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'instead', 'adv. 代替；反而；相反', 633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Canadian', 'adj. 加拿大（人）的 n. 加拿大人', 634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'properly', 'adv. 适当地；正确地；恰当地', 635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'absolute', 'adj. 绝对的；完全的；专制的 n. 绝对；绝对事物', 636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'example', 'n. 例子；榜样 vt. 作为…的例子；为…做出榜样 vi. 举例', 637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bill', 'n. [法] 法案；广告；账单；[金融] 票据；钞票；清单 v. 宣布；开账单；用海报宣传', 638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'since', 'conj. 因为；由于；既然；自…以来；自…以后 prep. 自…以来；自…以后 adv. 后来', 639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'almost', 'adv. 差不多，几乎', 640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'marry', 'v. 嫁；娶；与……结婚 n. (Marry)人名；(阿拉伯)马雷；(法)马里', 641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adore', 'v. 崇拜；爱慕；喜爱；极喜欢 n. (Adore)人名；(法)阿多尔', 642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'starvation', 'n. 饿死；挨饿；绝食', 643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'handful', 'n. 少数；一把；棘手事', 644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'porridge', 'n. 粥，糊；麦片粥 vt. 服刑', 645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jet', 'n. 喷射，喷嘴；喷气式飞机；黑玉 adj. 墨黑的 v. 射出', 646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'volleyball', 'n. 排球', 647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'draft', 'n. 汇票；草稿；选派；（尤指房间、烟囱、炉子等供暖系统中的）（小股）气流 v. 起草；制定；征募 adj. 初步画出或（写出）的；（设计、草图、提纲或版本）正在起草中的，草拟的；以草稿形式的；草图的', 648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'festival', 'n. 节日；庆祝，纪念活动；欢乐 adj. 节日的，喜庆的；快乐的', 649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alarm', 'n. 闹钟；警报，警告器；惊慌 v. 警告；使惊恐', 650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sharp', 'adj. 急剧的；锋利的；强烈的；敏捷的；刺耳的 adv. 急剧地；锐利地；突然地 n. 尖头；骗子；内行 vt. 磨快；把音调升高 vi. 打扮；升音演奏', 651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'regular', 'adj. 定期的；有规律的；合格的；整齐的；普通的 n. 常客；正式队员；中坚分子 adv. 定期地；经常地', 652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'application', 'n. 应用；申请；应用程序；敷用', 653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'republic', 'n. 共和国；共和政体', 654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rubbish', 'n. 垃圾，废物；废话 adj. 毫无价值的', 655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'heavy', 'adj. 沉重的；繁重的，巨大的；拥挤的；阴沉的 n. 重物；严肃角色 adv. 大量地；笨重地', 656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'drown', 'v. 淹没；把…淹死 n. (Drown)人名；(英)德朗', 657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'quality', 'n. 质量，[统计] 品质；特性；才能 adj. 优质的；高品质的；<英俚>棒极了', 658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'catalogue', 'n. 目录；（美）大学情况一览 v. 把…编入目录', 659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cube', 'n. 立方；立方体；骰子 v. 使成立方形；使自乘二次；量…的体积', 660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wrinkle', 'n. 皱纹 v. 起皱', 661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bookshop', 'n. 书店', 662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eat', 'v. 吃，喝；腐蚀；烦扰', 663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'egg', 'n. 蛋；卵子；家伙；鸡蛋 v. 煽动；怂恿', 664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'highway', 'n. 公路，大路；捷径', 665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'white', 'adj. 白色的；白种的；纯洁的 n. 白色；洁白；白种人', 666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pencil', 'n. 铅笔；笔状物 v. 用铅笔写；用眉笔涂', 667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'weigh', 'v. 权衡；考虑；称…重量 n. 权衡；称重量', 668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'abuse', 'n. 滥用；虐待；辱骂；弊端；恶习，陋习 v. 滥用；虐待；辱骂', 669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tiger', 'n. 老虎；凶暴的人', 670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'TRUE', 'adj. 真实的；正确的 adv. 真实地；准确地 n. 真实；准确 v. 装准', 671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eighty', 'n. 八十；八十岁；八十年代 adj. 八十的，八十个的；八十岁的 num. 八十', 672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sickness', 'n. 疾病；呕吐；弊病', 673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spiritual', 'n. 圣歌（尤指美国南部黑人的） adj. 精神的，心灵的', 674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'I', 'pron. 我 n. 碘元素；英语字母I', 675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blank', 'adj. 空白的；空虚的；单调的 n. 空白；空虚；空白表格 v. 使…无效；使…模糊；封锁', 676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'through', 'prep. 通过；穿过；凭借 adv. 彻底；从头至尾 adj. 直达的；过境的；完结的', 677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'boycott', 'v. 联合抵制；拒绝参加 n. 联合抵制', 678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harmony', 'n. 协调；和睦；融洽；调和', 679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aunt', 'n. 阿姨；姑妈；伯母；舅妈', 680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fuel', 'v. 得到燃料 n. 燃料；刺激因素', 681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Paris', 'n. 巴黎（法国首都）；帕里斯（特洛伊王子）', 682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'frost', 'v. 结霜于；冻坏 n. 霜；冰冻，严寒；冷淡', 683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'central', 'adj. 中心的；主要的；中枢的 n. 电话总机', 684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'farmer', 'n. 农夫，农民', 685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'vote', 'n. 投票，选举；选票；得票数 v. 提议，使投票；投票决定；公认', 686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ruin', 'n. 废墟；毁坏；灭亡 v. 毁灭；使破产', 687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'England', 'n. 英格兰', 688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'helmet', 'n. 钢盔，头盔', 689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'the', 'art. 这；那 adv. 更加（用于比较级，最高级前）', 690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'seaside', 'n. 海边；海滨 adj. 海边的；海滨的', 691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'perfect', 'adj. 完美的；最好的；精通的 v. 使完美；使熟练 n. 完成式', 692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'airport', 'n. 机场；航空站', 693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flee', 'v. 逃走；消失，消散', 694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'housewife', 'n. 家庭主妇', 695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fight', 'v. 打架；与…打仗，与…斗争；反对…提案 n. 打架；战斗，斗志', 696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'piece', 'n. 块；件；篇；硬币 v. 修补；接合；凑合', 697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'breath', 'n. 呼吸，气息；一口气，（呼吸的）一次；瞬间，瞬息；微风；迹象；无声音，气音', 698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ownership', 'n. 所有权；物主身份', 699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plane', 'n. 飞机；平面；程度，水平 v. 刨；乘飞机旅行；翱翔 adj. 平的；平面的', 700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fluent', 'adj. 流畅的，流利的；液态的；畅流的', 701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gun', 'n. 枪支；枪状物；持枪歹徒 v. 用枪射击；加大油门快速前进', 702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Indian', 'adj. 印度的；印第安人的；印第安语的 n. 印度人；印第安人；印第安语', 703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bad', 'adj. 坏的；严重的；劣质的 n. 坏事；坏人 adv. 很，非常；坏地；邪恶地', 704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'boy', 'n. 男孩；男人', 705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'howl', 'v. 咆哮；怒吼；狂吠 n. 嗥叫；怒号；嚎哭', 706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'doll', 'n. 洋娃娃；玩偶；无头脑的美丽女人 v. 把…打扮得花枝招展', 707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'yellow', 'adj. 黄色的；黄皮肤的 n. 黄色；黄种人；黄色颜料 v. 使变黄或发黄', 708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'settler', 'n. 移居者；殖民者', 709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unwilling', 'adj. 不愿意的；不情愿的；勉强的', 710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bridegroom', 'n. 新郎', 711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'favourite', 'adj. 特别受喜爱的 n. 特别喜爱的人（或物）', 712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'delicious', 'adj. 美味的；可口的', 713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stage', 'n. 阶段；舞台；戏剧；驿站 v. 举行；上演；筹划', 714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'academic', 'adj. 学术的；理论的；学院的 n. 大学生，大学教师；学者', 715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rainbow', 'n. 彩虹；五彩缤纷的排列；幻想 adj. 五彩缤纷的；彩虹状的 vt. 使呈彩虹状；如彩虹般装饰 vi. 呈彩虹状', 716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interview', 'n. 接见，采访；面试，面谈 v. 采访；接见；对…进行面谈；对某人进行面试', 717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'income', 'n. 收入，收益；所得', 718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flag', 'v. 标记；衰退；枯萎 n. 标志；旗子', 719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spaceship', 'n. [航] 宇宙飞船', 720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deed', 'n. 行动；功绩；证书；[法] 契据 vt. 立契转让', 721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pain', 'n. 疼痛；努力 v. 使…痛苦；使…烦恼', 722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fox', 'v. 欺骗；使变酸 n. 狐狸；狡猾的人', 723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'penny', 'n. （美）分；便士', 724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'around', 'adv. 大约；到处；在附近 prep. 四处；在…周围', 725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grandma', 'n. 奶奶；外婆', 726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'read', 'v. 阅读；读懂，理解 n. 阅读；读物 adj. 有学问的', 727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'granddaughter', 'n. 孙女；外孙女', 728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'trade', 'n. 贸易，交易；行业；职业 v. 交易，买卖；以物易物', 729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'European', 'adj. 欧洲的；欧洲人的 n. 欧洲人', 730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mat', 'n. 垫；垫子；衬边 v. 缠结；铺席于……上 adj. 无光泽的', 731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wine', 'n. 酒，葡萄酒；紫红色 v. 喝酒', 732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'physician', 'n. [医] 医师；内科医师', 733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hillside', 'n. 山坡，山腹；山腰', 734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Britain', 'n. 英国；不列颠', 735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hero', 'n. 英雄；男主角，男主人公', 736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plan', 'n. 计划；平面图 v. 计划；设计；打算', 737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mourn', 'v. 哀悼；忧伤；服丧', 738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'engineer', 'n. 工程师；工兵；火车司机 v. 设计；策划；精明地处理', 739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spend', 'v. 度过，消磨（时光）；花费；浪费；用尽 n. 预算', 740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bread', 'n. 面包；生计 v. 在…上洒面包屑', 741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interpreter', 'n. 解释者；口译者；注释器', 742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'operate', 'v. 运转；动手术；起作用', 743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'affect', 'v. 影响；感染；感动；假装 n. 情感；引起感情的因素', 744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bike', 'n. 自行车；脚踏车 v. 骑自行车（或摩托车）', 745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sacred', 'adj. 神的；神圣的；宗教的；庄严的', 746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'means', 'n. 手段；方法；财产 v. 意思是；打算（mean的第三人称单数） [ 复数means ]', 747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tire', 'v. 疲劳；厌倦 n. 轮胎；头饰', 748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'marble', 'n. 大理石；大理石制品；弹珠 adj. 大理石的；冷酷无情的', 749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ferry', 'n. 渡船；摆渡；渡口 v. （乘渡船）渡过；用渡船运送；空运', 750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'break', 'v. 打破；折断；弄坏；削弱 n. 破裂；间断；（持续一段时间的状况的）改变；间歇', 751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'natural', 'adj. 自然的；物质的；天生的；不做作的 n. 自然的事情；白痴；本位音', 752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'letter', 'n. 信；字母，文字；证书；文学，学问；字面意义 v. 写字母于', 753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'extreme', 'adj. 极端的；极度的；偏激的；尽头的 n. 极端；末端；最大程度；极端的事物', 754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disappointment', 'n. 失望；沮丧', 755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'kitchen', 'n. 厨房；炊具；炊事人员', 756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consideration', 'n. 考虑；原因；关心；报酬', 757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'merchant', 'n. 商人，批发商；店主 adj. 商业的，商人的', 758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'jewelry', 'n. 珠宝；珠宝类', 759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'status', 'n. 地位；状态；情形；重要身份', 760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'homework', 'n. 家庭作业，课外作业', 761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'autumn', 'n. 秋天；成熟期；渐衰期，凋落期 adj. 秋天的，秋季的', 762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'forever', 'adv. 永远；不断地；常常', 763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'selfish', 'adj. 自私的；利己主义的', 764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'athlete', 'n. 运动员，体育家；身强力壮的人', 765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'before', 'prep. 在…之前，先于 adv. 以前；在前 conj. 在…以前；在…之前', 766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'itself', 'pron. 它自己；它本身', 767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'role', 'n. 角色；任务', 768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'family', 'n. 家庭；亲属；家族；子女；[生]科；语族；[化]族 adj. 家庭的；家族的；适合于全家的', 769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'victim', 'n. 受害人；牺牲品；牺牲者', 770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worm', 'n. 虫，蠕虫；蜗杆；螺纹；小人物 v. 使蠕动；给除虫；使缓慢前进', 771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shopkeeper', 'n. 店主，老板', 772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wedding', 'n. 婚礼，婚宴；结婚；结合 v. 与…结婚（wed的ing形式）', 773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'classical', 'adj. 古典的；经典的；传统的；第一流的 n. 古典音乐', 774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'surplus', 'n. 剩余；[贸易] 顺差；盈余；过剩 adj. 剩余的；过剩的', 775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'steep', 'adj. 陡峭的；不合理的；夸大的；急剧升降的 v. 泡；浸；使…充满 n. 峭壁；浸渍', 776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'woollen', 'adj. 羊毛制的 n. 毛织品', 777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'of', 'prep. 关于；属于；…的；由…组成的', 778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fibre', 'n. 纤维；纤维制品', 779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tasteless', 'adj. 无味的；无鉴赏力的', 780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dog', 'n. 狗；丑女人；卑鄙的人；(俚)朋友 v. 跟踪；尾随', 781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sensitive', 'adj. 敏感的；感觉的；[仪] 灵敏的；感光的；易受伤害的；易受影响的 n. 敏感的人；有灵异能力的人', 782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'junior', 'adj. 年少的；后进的；下级的 n. 年少者，晚辈；地位较低者；大学三年级学生', 783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'translator', 'n. 译者；翻译器', 784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adventure', 'n. 冒险；冒险精神；投机活动 v. 冒险；大胆说出', 785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'qualification', 'n. 资格；条件；限制；赋予资格', 786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'planet', 'n. 行星', 787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ugly', 'adj. 丑陋的；邪恶的；令人厌恶的', 788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'history', 'n. 历史，历史学；历史记录；来历', 789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'house', 'n. 住宅；家庭；机构；议会；某种用途的建筑物 v. 覆盖；给…房子住；把…储藏在房内', 790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'surface', 'n. 表面；表层；外观 adj. 表面的，肤浅的 v. 浮出水面', 791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'devote', 'v. 致力于；奉献', 792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aid', 'n. 援助；帮助；助手；帮助者 v. 援助；帮助；有助于', 793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'component', 'adj. 组成的，构成的 n. 成分；组件；[电子] 元件', 794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'generation', 'n. 一代；产生；一代人；生殖', 795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'edge', 'n. 边缘；优势；刀刃；锋利 v. 使锐利；将…开刃；给…加上边', 796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'organ', 'n. [生物] 器官；机构；风琴；管风琴；嗓音', 797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'federal', 'adj. 联邦的；同盟的；联邦政府的； 联邦制的 adv. 联邦政府地 n. (Federal)人名；(英)费德勒尔', 798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alive', 'adj. 活着的；活泼的；有生气的', 799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'top', 'n. 顶部，顶端；上部；首席；陀螺 v. 高出，超越；结束；达到顶点 adj. 最高的，顶上的；头等的', 800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'minority', 'n. 少数民族；少数派；未成年 adj. 少数的；属于少数派的', 801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'have', 'v. 有；让；拿；从事；允许 aux. 已经 n. (Have)人名；(芬)哈韦；(德)哈弗', 802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'notice', 'n. 通知，布告；注意；公告 v. 通知；注意到；留心', 803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tower', 'n. 塔；高楼；堡垒 v. 高耸；超越', 804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'actress', 'n. 女演员', 805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'enthusiastic', 'adj. 热情的；热心的；狂热的', 806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'loose', 'adj. 宽松的；散漫的；不牢固的；不精确的 v. 释放；开船；放枪 adv. 松散地 n. 放纵；放任；发射', 807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adequate', 'adj. 充足的；适当的；胜任的', 808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lock', 'v. 锁，锁上；隐藏 n. 锁；水闸；刹车', 809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blood', 'n. 血，血液；血统 v. 从…抽血；使先取得经验', 810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'birthplace', 'n. 出生地', 811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'navy', 'n. 海军', 812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'American', 'n. 美国人，美洲人；美国英语 adj. 美国的，美洲的；地道美国式的', 813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'problem', 'n. 难题；引起麻烦的人 adj. 成问题的；难处理的', 814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shall', 'aux. 应；会；将；必须', 815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'for', 'prep. 为，为了；因为；给；对于；至于；适合于 conj. 因为', 816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cordless', 'n. 不用电线的 adj. 无线的（副词cordlessly）', 817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pleasure', 'n. 快乐；希望；娱乐；令人高兴的事 vt. 使高兴；使满意 vi. 高兴；寻欢作乐', 818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appointment', 'n. 任命；约定；任命的职位', 819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'would', 'aux. 将，将要；愿意 v. will的过去式', 820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grandchild', 'n. 孙子；孙女；外孙；外孙女', 821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'window', 'n. 窗；窗口；窗户', 822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'redirect', 'v. 使改方向；重新寄送 adj. 再直接的 n. 再直接询问', 823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'niece', 'n. 外甥女，侄女', 824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coal', 'v. 上煤；加煤 n. 煤；煤块；木炭', 825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mainland', 'n. 大陆；本土 adj. 大陆的；本土的', 826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mother', 'n. 母亲；大娘；女修道院院长 v. 生下；养育；像母亲般关怀或照管 adj. 母亲的；出生地的', 827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chaos', 'n. 混沌，混乱', 828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'polite', 'adj. 有礼貌的，客气的；文雅的；上流的；优雅的', 829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'entertainment', 'n. 娱乐；消遣；款待', 830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'personnel', 'n. 人事部门；全体人员 adj. 人员的；有关人事的', 831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circle', 'n. 循环，周期；圆；圈子；圆形物 v. 盘旋，旋转；环行', 832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Chinese', 'n. 中文，汉语；中国人 adj. 中国的，中国人的；中国话的', 833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Monday', 'n. 星期一', 834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'save', 'v. 节省；保存；储蓄；解救 prep. 除之外 n. 救援', 835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'collar', 'n. 衣领；颈圈 v. 抓住；给…上领子；给…套上颈圈', 836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dot', 'n. 点，圆点；嫁妆 v. 打上点', 837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coach', 'n. 教练；旅客车厢；长途公车；四轮大马车 v. 训练；指导', 838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'nuclear', 'adj. 原子能的；[细胞] 细胞核的；中心的；原子核的', 839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'voice', 'n. 声音；嗓音；发言权；愿望 v. 表达；吐露', 840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'select', 'v. 挑选；选拔 adj. 精选的；挑选出来的；极好的 n. 被挑选者；精萃', 841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thunder', 'n. 雷；轰隆声；恐吓 v. 打雷；怒喝', 842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ancestor', 'n. 始祖，祖先；被继承人', 843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tend', 'v. 趋向，倾向；照料，照顾', 844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bowl', 'n. 碗；木球；大酒杯 v. 玩保龄球；滑动；平稳快速移动', 845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pretend', 'v. 假装，伪装，佯装 adj. 假装的', 846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'majority', 'n. 多数；成年', 847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'minute', 'n. 分，分钟；片刻，一会儿；备忘录，笔记；会议记录 v. 将…记录下来 adj. 微小的，详细的 [maɪˈnjuːt; US -ˈnuːt; maɪˋnut]', 848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'weather', 'n. 天气；气象；气候；处境 v. 经受住；使风化；侵蚀；使受风吹雨打 adj. 露天的；迎风的', 849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'suggestion', 'n. 建议；示意；微量，细微的迹象', 850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sunrise', 'n. 日出；黎明', 851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alike', 'adj. 相似的；相同的 adv. 以同样的方式；类似于', 852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'district', 'n. 区域；地方；行政区', 853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'compulsory', 'adj. 义务的；必修的；被强制的 n. （花样滑冰、竞技体操等的）规定动作', 854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Tibet', 'n. 西藏（中国一自治区）', 855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lay', 'v. 躺下；产卵；搁放；放置；铺放；涂，敷 adj. 世俗的；外行的；没有经验的 n. 位置；短诗；花纹方向；叙事诗；性伙伴', 856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stomach', 'n. 胃；腹部；胃口 v. 忍受；吃下', 857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'damage', 'n. 损害；损毁；赔偿金 v. 损害；损毁', 858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cough', 'n. 咳嗽，咳嗽声；咳嗽病 v. 咳出', 859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shut', 'v. 关闭；停业；幽禁 n. 关闭 adj. 关闭的；围绕的', 860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anniversary', 'n. 周年纪念日', 861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coat', 'n. 外套 v. 覆盖…的表面', 862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ham', 'n. 火腿；业余无线电爱好者；蹩脚演员 v. 表演过火 adj. 过火的；做作的', 863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'depth', 'n. [海洋] 深度；深奥', 864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'somebody', 'n. 大人物；重要人物 pron. 有人；某人', 865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'requirement', 'n. 要求；必要条件；必需品', 866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'guard', 'n. 守卫；警戒；护卫队；防护装置 v. 警惕', 867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'superman', 'n. 超人，能力非凡的', 868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'artist', 'n. 艺术家；美术家（尤指画家）；大师', 869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prove', 'v. 证明；检验；显示', 870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cry', 'v. 叫喊；哭出；大声说 n. 叫喊；叫声；口号；呼叫', 871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lunch', 'n. 午餐 v. 吃午餐；供给午餐', 872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fourth', 'adj. 第四的，第四个的；四分之一的 n. 第四，月的第四日；四分之一 num. 第四', 873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tractor', 'n. 拖拉机；牵引机', 874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'entire', 'adj. 全部的，整个的；全体的 n. (Entire)人名；(英)恩泰尔', 875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bare', 'adj. 空的；赤裸的，无遮蔽的 v. 露出，使赤裸 n. (Bare)人名；(英)贝尔', 876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'guess', 'v. 猜测；认为；推测；猜中 n. 猜测；推测', 877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'outside', 'adj. 外面的，外部的；外来的 n. 外部；外观 adv. 在外面，向外面；在室外 prep. 在…范围之外', 878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'absent', 'adj. 缺席的；缺少的；心不在焉的；茫然的 v. 使缺席', 879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'firewood', 'n. 柴火；木柴', 880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'our', 'pron. 我们的', 881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Iceland', 'n. 冰岛（欧洲岛名，在大西洋北部，近北极圈）', 882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ecology', 'n. 生态学；社会生态学', 883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'religion', 'n. 宗教；宗教信仰', 884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'participate', 'v. 参与，参加；分享', 885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unusual', 'adj. 不寻常的；与众不同的；不平常的', 886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gravity', 'n. 重力，地心引力；严重性；庄严', 887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dust', 'n. 灰尘；尘埃；尘土 v. 撒；拂去灰尘', 888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'science', 'n. 科学；技术；学科；理科', 889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'money', 'n. 钱；货币；财富', 890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ship', 'v. 运送，乘船；以船运送 n. 船；舰；太空船', 891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'precious', 'adj. 宝贵的；珍贵的；矫揉造作的 n. (Precious)人名；(英)普雷舍斯，普雷舍丝(女名)', 892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'today', 'adv. 今天；现今 n. 今天；现今', 893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'overlook', 'v. 忽略；俯瞰；远眺；检查；高耸于…之上 n. 忽视；眺望', 894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hang', 'v. 悬挂，垂下；装饰；绞死；使悬而未决 n. 悬挂；暂停，中止', 895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ticket', 'n. 票；入场券，标签；（美）候选人名单；证明书；交通罚款单 v. 加标签于；指派；对…开出交通违规罚单', 896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Mosquito', 'n. 蚊子', 897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'repairs', 'n. 修理；[会计] 修理费；备件；修理工作（repair的复数形式） v. 修理；恢复（repair的三单形式）；弥补；纠正', 898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dormitory', 'n. 宿舍，学生宿舍 adj. 住宅区的', 899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'write', 'v. 写，写字；写作，作曲；写信', 900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'seat', 'n. 座位；所在地；职位 v. 使…坐下；可容纳…的；使就职', 901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wander', 'v. 徘徊；漫步；迷路；离题 n. (Wander)人名；(英)万德(女子教名)', 902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tentative', 'adj. 试验性的，暂定的；踌躇的 n. 假设，试验', 903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eighteen', 'n. 十八，十八个 adj. 十八个的，十八的 num. 十八', 904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hold', 'v. 持有；拥有；保存；拘留；约束或控制 n. 控制；保留', 905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'habit', 'n. 习惯，习性；嗜好 v. 使穿衣', 906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'future', 'n. 未来；前途；期货；将来时 adj. 将来的，未来的', 907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'independent', 'adj. 独立的；单独的；无党派的；不受约束的 n. 独立自主者；无党派者', 908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'subject', 'n. 主题；科目；[语] 主语；国民 adj. 服从的；易患…的；受制于…的 v. 使…隶属；使屈从于…', 909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'say', 'v. 讲；说明；例如；声称；假设；指明 n. (Say)人名；(土)萨伊；(法、老、柬)赛；(英)塞伊；(匈、罗)绍伊', 910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'target', 'n. 目标；靶子 v. 把……作为目标；规定……的指标；瞄准某物', 911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disease', 'n. 病，[医] 疾病；弊病 vt. 传染；使…有病', 912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'death', 'n. 死；死亡；死神；毁灭', 913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ago', 'adv. 以前，以往 adj. 以前的；过去的 n. (Ago)人名；(英、西、意、塞、瑞典)阿戈', 914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shore', 'v. 支撑，使稳住；用支柱撑住 n. 海滨；支柱', 915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'obey', 'v. 服从，听从；按照……行动 n. (Obey)人名；(英、法)奥贝', 916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thankful', 'adj. 感谢的；欣慰的', 917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'restaurant', 'n. 餐馆；[经] 饭店', 918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'awesome', 'adj. 令人敬畏的；使人畏惧的；可怕的；极好的', 919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'decorate', 'v. 装饰；布置；授勋给', 920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'judgement', 'n. 意见；判断力；[法] 审判；评价', 921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'congratulation', 'n. 祝贺；贺辞', 922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'appropriate', 'adj. 适当的；恰当的；合适的 v. 占用，拨出', 923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'assessment', 'n. 评定；估价', 924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'supper', 'n. 晚餐，晚饭；夜宵', 925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bent', 'n. 爱好，嗜好 adj. 弯曲的；决心的', 926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'they', 'pron. 他们；它们；她们', 927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'move', 'n. 移动；步骤；迁居；策略 v. 移动；搬家，迁移；离开', 928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eagle', 'n. 鹰；鹰状标饰', 929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'common', 'adj. 共同的；普通的；一般的；通常的 n. 普通；平民；公有地', 930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'customer', 'n. 顾客；家伙', 931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cast', 'v. 投，抛；计算；浇铸；投射（光、影、视线等） n. 投掷，抛；铸件，[古生] 铸型；演员阵容；脱落物', 932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'million', 'n. 百万；无数 adj. 百万的；无数的 num. 百万', 933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'custom', 'n. 习惯，惯例；风俗；海关，关税；经常光顾；[总称]（经常性的）顾客 adj. （衣服等）定做的，定制的', 934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'extra', 'adv. 特别地，非常；另外 n. 临时演员；号外；额外的事物；上等产品 adj. 额外的，另外收费的；特大的', 935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ash', 'n. 灰；灰烬', 936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'evaluate', 'v. 评价；估价；求…的值', 937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'suit', 'v. 适合；使适应 n. 诉讼；恳求；套装，西装；一套外衣', 938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'servant', 'n. 仆人，佣人；公务员；雇工', 939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Wednesday', 'n. 星期三', 940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'after', 'adv. 后来，以后 prep. 在……之后 conj. 在……之后 adj. 以后的', 941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'attempt', 'n. 企图，试图；攻击 v. 企图，试图；尝试', 942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'retire', 'v. 退休；撤退；退却 n. 退休；退隐；退兵信号', 943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'return', 'v. 返回；报答 n. 返回；归还；回球 adj. 报答的；回程的；返回的', 944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'celebrate', 'v. 庆祝；举行；赞美；祝贺；宣告', 945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'switch', 'v. 转换；用鞭子等抽打 n. 开关；转换；鞭子', 946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cure', 'v. 治疗；治愈；使硫化；加工处理 n. 治疗；治愈；[临床] 疗法', 947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'primary', 'adj. 主要的；初级的；基本的 n. 原色；最主要者', 948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'keep', 'v. 保持；经营；遵守；饲养 n. 保持；生计；生活费', 949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pyramid', 'n. 金字塔；角锥体 v. 渐增；上涨；成金字塔状', 950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'afford', 'v. 给予，提供；买得起 n. (Afford)人名；(英)阿福德', 951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cut', 'n. 伤口；切口；削减；（服装等的）式样；削球；切入 v. [机] 切割；削减；缩短；刺痛 adj. 割下的；雕过的；缩减的', 952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ban', 'v. 禁止，取缔 n. 禁令，禁忌', 953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tablet', 'n. 碑；药片；写字板；小块；平板电脑 vt. 用碑牌纪念；将(备忘录等)写在板上；将…制成小片或小块', 954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'head', 'n. 头；头痛；上端；最前的部分；理解力 v. 前进；用头顶；作为…的首领；站在…的前头；给…加标题 adj. 头的；主要的；在顶端的', 955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'foreigner', 'n. 外地人，外国人', 956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'willing', 'adj. 乐意的；自愿的；心甘情愿的 v. 决心；用意志力驱使；将（财产等）遗赠某人（will的现在分词） n. (Willing)人名；(德、芬、瑞典)维林；(英)威林', 957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mineral', 'n. 矿物；（英）矿泉水；无机物；苏打水（常用复数表示） adj. 矿物的；矿质的', 958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shade', 'n. 树荫；阴影；阴凉处；遮阳物；（照片等的）明暗度；少量、些微；细微的差别 v. 使阴暗；使渐变；为…遮阳；使阴郁；掩盖', 959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'various', 'adj. 各种各样的；多方面的', 960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'poem', 'n. 诗', 961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'above', 'prep. 超过；在……上面；在……之上 adv. 在上面；在上文 adj. 上文的 n. 上文', 962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dinosaur', 'n. 恐龙；过时、落伍的人或事物', 963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'valuable', 'adj. 有价值的；贵重的；可估价的 n. 贵重物品', 964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'swallow', 'v. 忍受；吞没 n. 燕子；一次吞咽的量', 965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'blue', 'n. 蓝色；[复数]（美国海、陆、空三军穿的）蓝色制服；蓝颜料；[the blue(s)][用作单数或复数]布鲁斯（歌曲）（一种伤感的美国黑人民歌 adj. 蓝色的；沮丧的，忧郁的；下流的 v. 把…染成蓝色；使成蓝色；给…用上蓝剂；用上蓝剂于', 966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'teamwork', 'n. 团队合作；协力', 967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wax', 'n. 蜡；蜡状物 v. 给…上蜡 adj. 蜡制的；似蜡的', 968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tyre', 'vt. 装轮胎于 n. [橡胶] 轮胎；轮箍', 969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hour', 'n. 小时；钟头；课时；…点钟', 970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'battleground', 'n. 战场', 971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sometimes', 'adv. 有时，间或', 972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mud', 'v. 弄脏；用泥涂 n. 泥；诽谤的话；无价值的东西', 973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'office', 'n. 办公室；政府机关；官职；营业处', 974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'leg', 'n. 腿；支柱', 975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'melon', 'n. 瓜；甜瓜；大肚子；圆鼓鼓像瓜似的东西', 976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'race', 'n. 属，种；种族，人种；家庭，门第 v. 使参加比赛；和…竞赛；使急走，使全速行进', 977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'optional', 'adj. 可选择的，随意的 n. 选修科目', 978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stop', 'v. 停止；堵塞；断绝 n. 停止；车站；障碍；逗留', 979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dustbin', 'n. 垃圾箱；吃货', 980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'screen', 'n. 屏，幕；屏风 v. 筛；拍摄；放映；掩蔽', 981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stocking', 'n. 长袜', 982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flat', 'adj. 平的；单调的；不景气的；干脆的；平坦的；扁平的；浅的 adv. （尤指贴着另一表面）平直地；断然地；水平地；直接地，完全地 n. 平地；公寓；平面 vt. 使变平；[音乐]使（音调）下降，尤指降半音 vi. 逐渐变平；[音乐]以降调唱（或奏）', 983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alone', 'adj. 独自的；单独的；孤独的 adv. 独自地；单独地', 984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'print', 'n. 印刷业；印花布；印刷字体；印章；印记 v. 印刷；打印；刊载；用印刷体写；在…印花样', 985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'die', 'v. 死亡；凋零；熄灭 n. 冲模，钢模；骰子', 986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mouse', 'n. 鼠标；老鼠；胆小羞怯的人 v. 探出', 987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'space', 'n. 空间；太空；距离 v. 留间隔', 988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'early', 'adj. 早期的；早熟的 adv. 提早；在初期 n. (Early)人名；(英)厄尔利', 989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'athletic', 'adj. 运动的，运动员的；体格健壮的', 990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cubic', 'adj. 立方体的，立方的 n. (Cubic)人名；(罗)库比克', 991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'secret', 'n. 秘密；秘诀；机密 adj. 秘密的；机密的', 992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bush', 'n. 灌木；矮树丛 v. 以灌木装饰；使…精疲力竭 adj. 如灌木般长得低矮的；粗野的', 993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'calculate', 'v. 计算；以为；作打算', 994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'super', 'adj. 特级的；极好的 n. 特级品，特大号；临时雇员', 995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'people', 'n. 人；人类；民族；公民 v. 居住于；使住满人', 996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'brake', 'v. 刹车 n. 闸，刹车；阻碍', 997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'side', 'n. 方面；侧面；旁边 v. 支持；赞助；偏袒 adj. 旁的，侧的', 998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'safety', 'n. 安全；保险；安全设备；保险装置；安打', 999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'snowball', 'n. 雪球 v. 掷雪球；滚雪球般增大', 1000);
