INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handy', 'adj. 便利的；手边的，就近的；容易取得的；敏捷的 n. (Handy)人名；(英)汉迪', 4501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'export', 'n. 输出，出口；出口商品 v. 输出物资', 4502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tropic', 'n. 热带；回归线 adj. 热带的', 4503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'urban', 'adj. 城市的；住在都市的 n. (Urban)人名；(西)乌尔万；(斯洛伐)乌尔班；(德、俄、罗、匈、塞、波、捷、瑞典、意)乌尔班；(英)厄本；(法)于尔邦', 4504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metre', 'n. 米；公尺；韵律', 4505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reckon', 'v. 测算，估计；认为；计算', 4506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cooperative', 'adj. 合作的；合作社的 n. 合作社', 4507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amend', 'v. 修改；改善，改进 n. (Amend)人名；(德、英)阿门德', 4508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'idiom', 'n. 成语，习语；土话', 4509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'door', 'n. 门；家，户；门口；通道', 4510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'luggage', 'n. 行李；皮箱', 4511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inclusive', 'adj. 包括的，包含的', 4512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rouse', 'v. 唤醒；激起，使振奋；惊起 n. 觉醒；奋起', 4513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'button', 'n. 按钮；纽扣 v. 扣住；扣紧；在…上装纽扣', 4514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'realm', 'n. 领域，范围；王国', 4515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feast', 'v. 享受；款待，宴请 n. 筵席，宴会；节日', 4516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosper', 'v. 繁荣，昌盛；成功 n. (Prosper)人名；(英、德、罗、法)普罗斯珀', 4517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'idiot', 'n. 笨蛋，傻瓜；白痴', 4518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tramp', 'v. 流浪；践踏，踩；脚步沉重地行走 n. 流浪者；沉重的脚步声；徒步旅行', 4519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knob', 'n. 把手；瘤；球形突出物 vi. 鼓起 vt. 使有球形突出物', 4520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'wonderful', 'adj. 极好的，精彩的，绝妙的；奇妙的；美妙；胜；神妙', 4521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'waterproof', 'adj. 防水的，不透水的 v. 使防水 n. 防水材料', 4522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ox', 'n. 牛；公牛', 4523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commend', 'v. 推荐；称赞；把…委托', 4524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inertia', 'n. [力] 惯性；惰性，迟钝；不活动', 4525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'melon', 'n. 瓜；甜瓜；大肚子；圆鼓鼓像瓜似的东西', 4526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gramme', 'n. 克', 4527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fireman', 'n. 消防队员；救火队员；锅炉工', 4528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'industrialize', 'v. 使工业化', 4529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'warfare', 'n. 战争；冲突', 4530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accumulate', 'v. 累积；积聚', 4531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crew', 'n. 队，组；全体人员，全体船员 v. 一起工作', 4532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moss', 'n. 苔藓；泥沼 vt. 使长满苔藓', 4533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necessity', 'n. 需要；必然性；必需品', 4534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'utmost', 'n. 极限；最大可能 adj. 极度的；最远的', 4535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'detector', 'n. 探测器；检测器；发现者；侦察器', 4536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obsession', 'n. 痴迷；困扰；[内科][心理] 强迫观念', 4537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'southwest', 'n. 西南方 adj. 西南的 adv. 往西南；来自西南', 4538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vegetarian', 'n. 素食者；食草动物 adj. 素食的', 4539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inhale', 'v. 吸入；猛吃猛喝', 4540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'porch', 'n. 门廊；走廊', 4541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crawl', 'v. 爬行；匍匐行进 n. 爬行；养鱼池；匍匐而行', 4542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'catastrophe', 'n. 大灾难；大祸；惨败', 4543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delicious', 'adj. 美味的；可口的', 4544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'malignant', 'adj. [医] 恶性的；有害的；有恶意的 n. 保王党员；怀恶意的人', 4545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violin', 'n. 小提琴；小提琴手', 4546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plane', 'n. 飞机；平面；程度，水平 v. 刨；乘飞机旅行；翱翔 adj. 平的；平面的', 4547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'item', 'n. 条款，项目；一则；一件商品（或物品） adj. 又，同上 v. 记下；逐条列出', 4548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'puff', 'v. 喷出，张开；使膨胀；夸张；使骄傲自满 n. 粉扑；泡芙；蓬松；一阵喷烟；肿块；吹嘘，宣传广告', 4549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cousin', 'n. 堂兄弟姊妹；表兄弟姊妹', 4550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bracket', 'n. 支架；括号；墙上凸出的托架 v. 括在一起；把…归入同一类；排除', 4551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fatigue', 'n. 疲劳，疲乏；杂役 v. 使疲劳；使心智衰弱 adj. 疲劳的', 4552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'versatile', 'adj. 多才多艺的；通用的，万能的；多面手的', 4553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trail', 'v. 追踪；拖；蔓延；落后于 n. 小径；痕迹；尾部；踪迹；一串，一系列', 4554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lavatory', 'n. 厕所，盥洗室', 4555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lover', 'n. 爱人，恋人；爱好者', 4556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stove', 'n. 火炉；窑；温室 vt. 用火炉烤', 4557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ink', 'v. 签署；涂墨水于 n. 墨水，墨汁；油墨', 4558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'levy', 'n. 征收；征兵，征税 v. 征收（税等）；征集（兵等）', 4559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'moon', 'n. 月亮；月球；月光；卫星 v. 闲荡；出神', 4560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outfit', 'n. 机构；用具；全套装备 v. 得到装备', 4561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dome', 'n. 圆屋顶 vi. 成圆顶状 vt. 加圆屋顶于…上', 4562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blur', 'v. 涂污；使…模糊不清；使暗淡；玷污 n. 污迹；模糊不清的事物', 4563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drift', 'n. 漂流，漂移；趋势；漂流物 v. 漂流，漂移；漂泊', 4564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'microscope', 'n. 显微镜', 4565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'paperback', 'n. 平装本；廉价本 vt. 以平装本出版 adj. 纸面装订的；纸面平装本书籍的', 4566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agony', 'n. 苦恼；极大的痛苦；临死的挣扎', 4567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crazy', 'adj. 疯狂的；狂热的，着迷的', 4568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corrode', 'v. 侵蚀；损害', 4569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ample', 'adj. 丰富的；足够的；宽敞的 n. (Ample)人名；(西)安普尔', 4570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'radiate', 'v. 辐射；传播；流露；发射；广播 adj. 辐射状的，有射线的', 4571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'statute', 'n. [法] 法规；法令；条例', 4572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dispose', 'v. 处理；处置；安排 n. 处置；性情', 4573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expel', 'v. 驱逐；开除', 4574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'afternoon', 'n. 午后，下午', 4575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'destructive', 'adj. 破坏的；毁灭性的；有害的，消极的', 4576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'smash', 'v. 粉碎；使破产；溃裂 n. 破碎；扣球；冲突；大败 adj. 了不起的；非常轰动的；出色的', 4577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'devil', 'n. 魔鬼；撒旦；家伙；恶棍；淘气鬼；冒失鬼 v. 虐待，折磨；（用扯碎机）扯碎；（替作家，律师等）做助手；抹辣味料烤制或煎煮', 4578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'insulate', 'v. 隔离，使孤立；使绝缘，使隔热', 4579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knot', 'n. （绳等的）结；节瘤，疙瘩；海里/小时（航速单位） v. 打结', 4580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'electrical', 'adj. 有关电的；电气科学的', 4581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'violet', 'n. 紫罗兰；堇菜；羞怯的人 adj. 紫色的；紫罗兰色的', 4582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shear', 'v. 剪；修剪；剥夺 n. [力] 切变；修剪；大剪刀', 4583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'meadow', 'n. 草地；牧场', 4584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bench', 'n. 长凳；工作台；替补队员 v. 给…以席位；为…设置条凳', 4585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'metropolitan', 'adj. 大都市的；大主教辖区的；宗主国的 n. 大城市人；大主教；宗主国的公民', 4586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'advisable', 'adj. 明智的，可取的，适当的', 4587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'elevator', 'n. 电梯；升降机；升降舵；起卸机', 4588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aluminum', 'n. 铝', 4589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suicide', 'n. 自杀；自杀行为；自杀者 adj. 自杀的 vt. 自杀 vi. 自杀', 4590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rubber', 'n. 橡胶；橡皮；合成橡胶；按摩师 adj. 橡胶制成的 v. 涂橡胶于；用橡胶制造', 4591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'normalization', 'n. 正常化；标准化；正规化；常态化', 4592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'acquaint', 'v. 使熟悉；使认识', 4593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grace', 'n. 优雅；恩惠；魅力；慈悲 v. 使优美', 4594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pure', 'adj. 纯的；纯粹的；纯洁的；清白的；纯理论的 n. (Pure)人名；(俄)普雷', 4595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'loaf', 'n. 条，一条面包；块；游荡 v. 游荡；游手好闲；虚度光阴', 4596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trademark', 'n. 商标', 4597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'load', 'n. 负载，负荷；工作量；装载量 v. [力] 加载；装载；装货', 4598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nearby', 'adj. 附近的，邻近的 adv. 在附近 prep. 在…附近', 4599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'presume', 'v. 假定；推测；擅自；意味着', 4600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversion', 'n. 转换；变换；[金融] 兑换；改变信仰', 4601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irritate', 'v. 刺激，使兴奋；激怒', 4602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plot', 'n. 情节；图；阴谋 v. 密谋；绘图；划分；标绘', 4603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outskirts', 'n. 市郊，郊区', 4604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'grade', 'n. 年级；等级；成绩；级别；阶段 v. 评分；把…分等级', 4605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'slide', 'n. 滑动；幻灯片；滑梯；雪崩 v. 滑动；滑落；不知不觉陷入', 4606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'axe', 'n. 斧 v. 削减；用斧砍', 4607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solitary', 'adj. 孤独的；独居的 n. 独居者；隐士', 4608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scratch', 'n. 擦伤；抓痕；刮擦声；乱写 adj. 打草稿用的；凑合的；碰巧的 v. 抓；刮；挖出；乱涂', 4609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vocal', 'adj. 歌唱的；声音的，有声的 n. 声乐作品；元音', 4610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transcend', 'v. 胜过，超越', 4611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outward', 'adj. 向外的；外面的；公开的；外服的；肉体的 adv. 向外（等于outwards）；在外；显而易见地 n. 外表；外面；物质世界', 4612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'park', 'n. 公园；[交] 停车场 v. 停放；放置；寄存', 4613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'settlement', 'n. 解决，处理；[会计] 结算；沉降；殖民', 4614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'banana', 'n. 香蕉；喜剧演员；大鹰钩鼻', 4615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'isle', 'n. 岛 vt. 使成为岛屿 vi. 住在岛屿上', 4616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'necessitate', 'v. 使成为必需，需要；迫使', 4617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orphan', 'adj. 孤儿的；无双亲的 n. 孤儿 v. 使成孤儿', 4618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pistol', 'n. 手枪；信号枪 vt. 用手枪射击', 4619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'piston', 'n. 活塞', 4620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'keen', 'adj. 敏锐的，敏捷的；渴望的；强烈的；热心的；锐利的 n. 痛哭，挽歌', 4621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'squirrel', 'n. 松鼠；松鼠毛皮 v. 贮藏', 4622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'optical', 'adj. 光学的；眼睛的，视觉的', 4623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conspiracy', 'n. 阴谋；共谋；阴谋集团', 4624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hug', 'v. 拥抱；紧抱；抱有，坚持 n. 拥抱；紧抱；固执', 4625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frost', 'v. 结霜于；冻坏 n. 霜；冰冻，严寒；冷淡', 4626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'crow', 'v. 啼叫；报晓 n. [鸟] 乌鸦；鸡鸣；撬棍', 4627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cancel', 'v. 取消；删去 n. 取消，撤销', 4628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bathroom', 'n. 浴室；厕所；盥洗室', 4629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eligible', 'adj. 合格的，合适的；符合条件的；有资格当选的 n. 合格者；适任者；有资格者', 4630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handbook', 'n. 手册；指南', 4631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'knit', 'v. 编织；结合；皱眉 n. 编织衣物；编织法', 4632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dessert', 'n. 餐后甜点；甜点心', 4633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verse', 'n. 诗，诗篇；韵文；诗节 v. 作诗', 4634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shallow', 'adj. 浅的；肤浅的 n. [地理] 浅滩 v. 使变浅', 4635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pump', 'v. 打气；用抽水机抽… n. 泵，抽水机；打气筒', 4636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'input', 'n. 投入；输入电路 v. [自][电子] 输入；将…输入电脑', 4637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'handwriting', 'n. 笔迹；书法；书写；手稿 v. 亲手写（handwrite的ing形式）', 4638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'expend', 'v. 花费；消耗；用光；耗尽', 4639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forthcoming', 'adj. 即将来临的 n. 来临', 4640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prince', 'n. 王子，国君；亲王；贵族', 4641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tolerant', 'adj. 宽容的；容忍的；有耐药力的', 4642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'implement', 'v. 实施，执行；实现，使生效 n. 工具，器具；手段', 4643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bunch', 'n. 群；串；突出物 v. 隆起；打褶；形成一串', 4644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plain', 'adj. 平的；简单的；朴素的；清晰的 n. 平原；无格式；朴实无华的东西 adv. 清楚地；平易地', 4645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foul', 'adj. 犯规的；邪恶的；污秽的；淤塞的 v. 犯规；弄脏；淤塞；缠住，妨害 n. 犯规；缠绕 adv. 违反规则地，不正当地', 4646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'consult', 'v. 查阅；商量；向…请教', 4647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ladder', 'n. 阶梯；途径；梯状物 v. 成名；发迹', 4648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'centigrade', 'adj. 摄氏的；[仪] 摄氏温度的；百分度的', 4649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dilemma', 'n. 困境；进退两难；两刀论法', 4650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'halt', 'v. 停止；立定；踌躇，犹豫 n. 停止；立定；休息', 4651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'countryside', 'n. 农村，乡下；乡下的全体居民', 4652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'relay', 'v. 转播；接替 n. [电] 继电器；接替，接替人员；驿马', 4653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'generalize', 'v. 概括；推广；使一般化', 4654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sarcastic', 'adj. 挖苦的；尖刻的，辛辣的', 4655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bibliography', 'n. 参考书目；文献目录', 4656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dealer', 'n. 经销商；商人', 4657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circular', 'adj. 循环的；圆形的；间接的 n. 通知，传单', 4658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'airport', 'n. 机场；航空站', 4659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'periodical', 'adj. [数] 周期的；定期的 n. 期刊；杂志', 4660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'brutal', 'adj. 残忍的；野蛮的，不讲理的', 4661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'projector', 'n. [仪] 投影仪；放映机；探照灯；设计者', 4662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sturdy', 'adj. 坚定的；强健的；健全的 n. 羊晕倒病', 4663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yawn', 'n. 哈欠；裂口 v. 打哈欠；裂开', 4664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ash', 'n. 灰；灰烬', 4665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plug', 'n. 插头；塞子；栓 v. 塞住；用插头将与电源接通', 4666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'picnic', 'n. 野餐 v. 去野餐', 4667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tomorrow', 'n. 明天；未来 adv. 明天；未来地（等于to-morrow）', 4668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ship', 'v. 运送，乘船；以船运送 n. 船；舰；太空船', 4669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pail', 'n. 桶，提桶', 4670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stranger', 'n. 陌生人；外地人；局外人', 4671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'qualitative', 'adj. 定性的；质的，性质上的', 4672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glamor', 'n. 魅力；魔法；迷人的美（等于glamour） vt. 迷惑；使有魅力（等于glamour）', 4673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spit', 'v. 吐痰；吐口水；发出劈啪声 n. 唾液', 4674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'evaporate', 'v. 使……蒸发；使……脱水；使……消失', 4675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spin', 'v. 旋转；纺纱；吐丝；晕眩 n. 旋转；疾驰', 4676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'litter', 'n. 垃圾；轿，担架；一窝（动物的幼崽）；凌乱 v. 乱丢；给…垫褥草；把…弄得乱七八糟', 4677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fore', 'adj. 以前的；在前部的 n. 前部；船头 adv. 在前面；在船头 prep. 在前 int. （打高尔夫球者的叫声）让开！', 4678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hum', 'v. 发低哼声 n. 嗡嗡声；哼声；杂声 int. 哼；嗯', 4679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spear', 'n. 矛，枪 v. 用矛刺', 4680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hut', 'n. 小屋；临时营房 vt. 使住在小屋中；驻扎 vi. 住在小屋中；驻扎', 4681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apt', 'adj. 恰当的；有…倾向的；灵敏的 n. (Apt)人名；(法、波、英)阿普特', 4682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mayor', 'n. 市长', 4683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'frown', 'v. 皱眉；不同意 n. 皱眉，蹙额', 4684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exquisite', 'adj. 精致的；细腻的；优美的，高雅的；异常的；剧烈的 n. 服饰过于讲究的男子', 4685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scatter', 'v. 分散，散开；散射 n. 分散；散播，撒播', 4686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'outbreak', 'n. （战争的）爆发；（疾病的）发作 vi. 爆发', 4687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blackboard', 'n. 黑板', 4688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'devise', 'v. 设计；想出；发明；图谋；遗赠给 n. 遗赠', 4689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'noun', 'n. 名词', 4690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'propel', 'v. 推进；驱使；激励；驱策', 4691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persevere', 'v. 坚持；不屈不挠；固执己见（在辩论中）', 4692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bosom', 'n. 胸；胸怀；中间；胸襟；内心；乳房；内部 v. 怀抱；把…藏在心中 adj. 知心的；亲密的', 4693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cigaret', 'n. 香烟；纸烟（等于cigarette）', 4694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pack', 'n. 包装；一群；背包；包裹；一副 v. 包装；压紧；捆扎；挑选；塞满', 4695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fool', 'v. 欺骗；开玩笑；戏弄 n. 傻瓜；愚人；受骗者 adj. 傻的', 4696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'amplifier', 'n. [电子] 放大器，扩大器；扩音器', 4697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dismay', 'n. 沮丧，灰心；惊慌 v. 使沮丧；使惊慌', 4698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contaminate', 'v. 污染，弄脏', 4699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shoe', 'n. 鞋；蹄铁；外胎 v. 给……穿上鞋；穿……鞋', 4700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'awe', 'v. 使敬畏；使畏怯 n. 敬畏', 4701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'millionaire', 'n. 百万富翁；大富豪 adj. 100万以上人口的', 4702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pact', 'n. 协定；公约；条约；契约', 4703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pathetic', 'adj. 可怜的，悲哀的；感伤的；乏味的', 4704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'revenge', 'n. 报复；复仇 v. 报复；替…报仇；洗雪', 4705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yard', 'n. 院子；码（英制中丈量长度单位，1码=3英尺）；庭院；帆桁 vt. 把…关进或围在畜栏里', 4706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'testimony', 'n. [法] 证词，证言；证据', 4707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excess', 'n. 超过，超额；过度，过量；无节制 adj. 额外的，过量的；附加的', 4708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beneficial', 'adj. 有益的，有利的；可享利益的', 4709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fond', 'adj. 喜欢的；温柔的；宠爱的 n. (Fond)人名；(法)丰；(瑞典)丰德', 4710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scarcely', 'adv. 几乎不，简直不；简直没有', 4711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intrigue', 'n. 阴谋；诡计；复杂的事；私通 v. 用诡计取得；激起的兴趣', 4712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intuition', 'n. 直觉；直觉力；直觉的知识', 4713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'monument', 'n. 纪念碑；历史遗迹；不朽的作品 vt. 为…树碑', 4714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maiden', 'adj. 未婚的，处女的；初次的 n. 少女；处女', 4715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lock', 'v. 锁，锁上；隐藏 n. 锁；水闸；刹车', 4716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'denounce', 'v. 谴责；告发；公然抨击；通告废除', 4717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'superficial', 'adj. 表面的；肤浅的 ；表面文章的；外表的；（人）浅薄的', 4718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'menace', 'n. 威胁；恐吓 v. 恐吓；进行威胁', 4719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'specification', 'n. 规格；说明书；详述', 4720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gauge', 'n. 计量器；标准尺寸；容量规格 v. 测量；估计；给…定规格', 4721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'supersonic', 'adj. 超音速的；超声波的 n. 超音速；超声波', 4722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'haul', 'n. 拖，拉；用力拖拉；努力得到的结果；捕获物；一网捕获的鱼量；拖运距离 v. 拖运；拖拉', 4723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stocking', 'n. 长袜', 4724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'shatter', 'v. 粉碎；打碎；破坏；破掉；使散开 n. 碎片；乱七八糟的状态', 4725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnish', 'v. 提供；供应；装备', 4726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'autonomy', 'n. 自治，自治权', 4727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sprinkle', 'n. 撒，洒；少量 v. 洒；微雨；散置', 4728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trick', 'n. 诡计；恶作剧；窍门；花招；骗局；欺诈 v. 欺骗；哄骗；装饰；打扮 adj. 特技的；欺诈的；有决窍的', 4729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distinction', 'n. 区别；差别；特性；荣誉、勋章', 4730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spaceship', 'n. [航] 宇宙飞船', 4731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'comic', 'adj. 喜剧的；滑稽的；有趣的 n. 连环漫画；喜剧演员；滑稽人物', 4732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'texture', 'n. 质地；纹理；结构；本质，实质', 4733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'differentiate', 'v. 区分，区别', 4734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rigid', 'adj. 严格的；僵硬的，死板的；坚硬的；精确的', 4735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deadly', 'adj. 致命的；非常的；死一般的 adv. 非常；如死一般地', 4736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'junction', 'n. 连接，接合；交叉点；接合点', 4737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cheque', 'n. 支票', 4738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'typist', 'n. 打字员，打字者', 4739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'naughty', 'adj. 顽皮的，淘气的；不听话的；没规矩的；不适当的；下流的', 4740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'secondary', 'adj. 第二的；中等的；次要的；中级的 n. 副手；代理人', 4741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fantasy', 'n. 幻想；白日梦；幻觉 adj. 虚幻的 v. 空想；想像', 4742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'suburb', 'n. 郊区；边缘', 4743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conversation', 'n. 交谈，会话；社交；交往，交际；会谈；（人与计算机的）人机对话', 4744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foundation', 'n. 基础；地基；基金会；根据；创立', 4745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'trial', 'n. 试验；审讯；努力；磨炼 adj. 试验的；审讯的', 4746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tragic', 'adj. 悲剧的；悲痛的，不幸的', 4747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sophisticated', 'adj. 复杂的；精致的；久经世故的；富有经验的 v. 使变得世故；使迷惑；篡改（sophisticate的过去分词形式）', 4748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ridiculous', 'adj. 可笑的；荒谬的', 4749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'purple', 'adj. 紫色的；帝王的；华而不实的 n. 紫色；紫袍 v. 变成紫色', 4750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tribe', 'n. 部落；族；宗族；一伙', 4751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jazz', 'n. 爵士乐，爵士舞；喧闹 v. 奏爵士乐，跳爵士舞；游荡 adj. 爵士乐的；喧吵的', 4752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hazard', 'v. 赌运气；冒…的危险，使遭受危险 n. 危险，冒险；冒险的事', 4753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excel', 'v. 超过；擅长', 4754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'solar', 'adj. 太阳的；日光的；利用太阳光的；与太阳相关的 n. 日光浴室', 4755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distill', 'v. 提取；蒸馏；使滴下', 4756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hinge', 'n. 铰链，折叶；关键，转折点；枢要，中枢 v. 用铰链连接；依…为转移；给…安装铰链；（门等）装有蝶铰', 4757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'guest', 'n. 客人，宾客；顾客 v. 款待，招待 adj. 客人的；特邀的，客座的', 4758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bullet', 'n. 子弹；只选某党全部候选人的投票；豆子 vi. 射出；迅速行进', 4759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rehearsal', 'n. 排演；预演；练习；训练；叙述', 4760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'compact', 'n. 合同，契约；小粉盒 adj. 紧凑的，紧密的；简洁的 v. 使简洁；使紧密结合', 4761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rope', 'n. 绳，绳索 v. 捆，绑', 4762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'witch', 'n. 巫婆，女巫 v. 迷惑；施巫术', 4763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lorry', 'n. （英）卡车；[车辆] 货车；运料车', 4764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'execute', 'v. 实行；执行；处死', 4765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fax', 'v. 传真 n. 传真', 4766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pickup', 'n. 收集，整理；小卡车；拾起；搭车者；偶然结识者', 4767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'notable', 'adj. 值得注意的，显著的；著名的 n. 名人，显要人物', 4768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yesterday', 'n. 昨天；往昔 adv. 昨天', 4769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'canvas', 'n. 帆布 v. 用帆布覆盖，用帆布装备 adj. 帆布制的', 4770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'label', 'v. 标注；贴标签于 n. 标签；商标；签条', 4771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rural', 'adj. 农村的，乡下的；田园的，有乡村风味的', 4772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'roof', 'n. 屋顶；最高处，顶部；最高限度 v. 给…盖屋顶，覆盖', 4773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'procession', 'n. 队伍，行列；一列，一排；列队行进 vi. 列队行进 vt. 沿著……行进', 4774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leak', 'n. 泄漏；漏洞，裂缝 v. 使渗漏，泄露', 4775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tough', 'adj. 艰苦的，困难的；坚强的，不屈不挠的；坚韧的，牢固的；强壮的，结实的 n. 恶棍 v. 坚持；忍受，忍耐 adv. 强硬地，顽强地', 4776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'curriculum', 'n. 课程', 4777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leap', 'v. 跳，跳跃 n. 飞跃；跳跃', 4778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sweater', 'n. 毛线衣，运动衫；大量出汗的人，发汗剂', 4779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indoor', 'adj. 室内的，户内的', 4780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nap', 'n. 小睡，打盹儿；细毛；孤注一掷 v. 使拉毛', 4781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indication', 'n. 指示，指出；迹象；象征', 4782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occasion', 'n. 时机，机会；场合；理由 v. 引起，惹起', 4783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rational', 'adj. 合理的；理性的 n. 有理数', 4784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circulate', 'v. 传播，流传；循环；流通', 4785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'noticeable', 'adj. 显而易见的，显著的；值得注意的', 4786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obsolete', 'adj. 废弃的；老式的 n. 废词；陈腐的人 vt. 淘汰；废弃', 4787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'layer', 'n. 层，层次；膜；[植]压条；放置者，计划者 v. 把…分层堆放；借助压条法；生根繁殖；将（头发）剪成不同层次', 4788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'destiny', 'n. 命运，定数，天命', 4789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tremendous', 'adj. 极大的，巨大的；惊人的；极好的', 4790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'freeze', 'v. 冻结；冷冻；僵硬 n. 冻结；凝固', 4791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appal', 'v. 使惊骇；惊吓', 4792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'maid', 'n. 女仆；少女 vt. 侍候；做新娘的女傧相 vi. 当女仆', 4793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dense', 'adj. 稠密的；浓厚的；愚钝的', 4794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circus', 'n. 马戏；马戏团', 4795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'deposit', 'n. 存款；押金；订金；保证金；沉淀物 v. 使沉积；存放', 4796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prescribe', 'v. 规定；开药方', 4797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glow', 'v. 发热；洋溢；绚丽夺目 n. 灼热；色彩鲜艳；兴高采烈', 4798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'honey', 'n. 蜂蜜；宝贝；甜蜜 adj. 甘美的；蜂蜜似的 v. 对…说甜言蜜语；加蜜使甜', 4799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ventilate', 'v. 使通风；给…装通风设备；宣布', 4800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accelerate', 'v. 使……加快；使……增速', 4801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hill', 'n. 小山；丘陵；斜坡；山冈', 4802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forehead', 'n. 额，前额', 4803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dairy', 'n. 奶制品；乳牛；制酪场；乳品店；牛奶及乳品业 adj. 乳品的；牛奶的；牛奶制的；产乳的', 4804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mischief', 'n. 恶作剧；伤害；顽皮；不和', 4805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vacation', 'n. 假期；（房屋）搬出 v. 休假，度假', 4806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'session', 'n. 会议；（法庭的）开庭；（议会等的）开会；学期；讲习会', 4807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'silence', 'n. 沉默；寂静；缄默；不谈；无声状态 v. 使沉默；使安静；压制；消除噪音 int. 安静！；别作声！', 4808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'needle', 'n. 针；指针；刺激；针状物 v. 缝纫；做针线', 4809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'antique', 'adj. 古老的，年代久远的；过时的，古董的；古风的，古式的 n. 古董，古玩；古风，古希腊和古罗马艺术风格 v. 觅购古玩', 4810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reservoir', 'n. 水库；蓄水池', 4811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'benign', 'adj. 良性的；和蔼的，亲切的；吉利的 n. (Benign)人名；(俄)贝尼根', 4812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'volcano', 'n. 火山', 4813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stereotype', 'v. 使用铅版；套用老套，使一成不变 n. 陈腔滥调，老套；铅版', 4814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fiction', 'n. 小说；虚构，编造；谎言', 4815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rape', 'n. 强奸，掠夺；[园艺] 油菜；葡萄渣 v. 强奸；掠夺，抢夺', 4816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'movie', 'n. 电影；电影院；电影业 adj. 电影的', 4817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nourish', 'v. 滋养；怀有；使健壮', 4818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pollution', 'n. 污染', 4819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prosperity', 'n. 繁荣，成功', 4820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diploma', 'n. 毕业证书，学位证书；公文，文书；奖状 vt. 发给…毕业文凭', 4821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cigar', 'n. 雪茄', 4822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'improvement', 'n. 改进，改善；提高', 4823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'square', 'adj. 平方的；正方形的；直角的；正直的 v. 使成方形；与…一致 n. 平方；广场；正方形 adv. 成直角地', 4824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hike', 'v. 远足；徒步旅行；上升 n. 远足；徒步旅行；涨价', 4825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'patch', 'n. 眼罩；斑点；碎片；小块土地 v. 修补；解决；掩饰', 4826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'midst', 'n. 当中，中间 prep. 在…中间（等于amidst）', 4827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'physicist', 'n. 物理学家；唯物论者', 4828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'oriental', 'adj. 东方的；东方人的 n. 东方人', 4829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'envy', 'n. 嫉妒，妒忌；羡慕 v. 嫉妒，妒忌；羡慕', 4830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'capsule', 'n. 胶囊；[植] 蒴果；太空舱；小容器 adj. 压缩的；概要的 v. 压缩；简述', 4831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'synthetic', 'adj. 综合的；合成的，人造的 n. 合成物', 4832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fable', 'n. 寓言；无稽之谈 vi. 编寓言；虚构 vt. 煞有介事地讲述；虚构', 4833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'correspondent', 'n. 通讯记者；客户；通信者；代理商行', 4834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pretext', 'n. 借口；托辞 vt. 以…为借口', 4835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gentle', 'adj. 温和的；文雅的 v. 使温和，使驯服 n. 蛆，饵', 4836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'postpone', 'v. 使…延期；把…放在次要地位；把…放在后面', 4837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'january', 'n. 一月', 4838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'proceed', 'v. 开始；继续进行；发生；行进 n. 收入，获利', 4839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mutton', 'n. 羊肉', 4840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'occupation', 'n. 职业；占有；消遣；占有期', 4841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'momentum', 'n. 势头；[物] 动量；动力；冲力', 4842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'console', 'n. [计] 控制台；[电] 操纵台 v. 安慰；慰藉', 4843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'apple', 'n. 苹果，苹果树，苹果似的东西；[美俚]炸弹，手榴弹，（棒球的）球；[美俚]人，家伙。', 4844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cathedral', 'n. 大教堂', 4845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gently', 'adv. 轻轻地；温柔地，温和地', 4846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drastic', 'adj. 激烈的；猛烈的 n. 烈性泻药', 4847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rainbow', 'n. 彩虹；五彩缤纷的排列；幻想 adj. 五彩缤纷的；彩虹状的 vt. 使呈彩虹状；如彩虹般装饰 vi. 呈彩虹状', 4848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'noon', 'n. 中午；正午；全盛期', 4849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'circle', 'n. 循环，周期；圆；圈子；圆形物 v. 盘旋，旋转；环行', 4850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'northeast', 'adj. 东北的；向东北的；来自东北的 n. 东北 adv. 向东北；来自东北', 4851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'silicon', 'n. [化学] 硅；硅元素', 4852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'exceedingly', 'adv. 非常；极其；极度地；极端', 4853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'majesty', 'n. 威严；最高权威，王权；雄伟；权威', 4854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spokesman', 'n. 发言人；代言人', 4855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hint', 'n. 暗示；线索 v. 暗示；示意', 4856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bottle', 'n. 瓶子；一瓶的容量 v. 控制；把…装入瓶中', 4857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interface', 'n. 界面；<计>接口；交界面 v. （使通过界面或接口）接合，连接；[计算机]使联系', 4858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cereal', 'n. 谷类，谷物；谷类食品；谷类植物 adj. 谷类的；谷类制成的', 4859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'entertainment', 'n. 娱乐；消遣；款待', 4860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'schedule', 'v. 安排，计划；编制目录；将……列入计划表 n. 时间表；计划表；一览表', 4861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mainland', 'n. 大陆；本土 adj. 大陆的；本土的', 4862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rash', 'adj. 轻率的；鲁莽的；不顾后果的 n. [皮肤] 皮疹；突然大量出现的事物', 4863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'identification', 'n. 鉴定，识别；认同；身份证明', 4864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tender', 'adj. 温柔的；柔软的；脆弱的；幼稚的；难对付的 n. 偿付，清偿；看管人；小船 v. 提供，偿还；使…变嫩；使…变柔软', 4865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clothe', 'v. 给…穿衣；覆盖；赋予', 4866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'velvet', 'n. 天鹅绒，丝绒；天鹅绒似的东西 adj. 天鹅绒的', 4867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overtime', 'n. [劳经] 加班时间；延长时间；加时赛 adj. 超时的；加班的 vt. 使超过时间 adv. 加班地', 4868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scar', 'v. 伤害；给留下伤痕 n. 创伤；伤痕', 4869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blunt', 'adj. 钝的，不锋利的；生硬的；直率的 v. 使迟钝 n. (Blunt)人名；(英)布伦特', 4870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'temperature', 'n. 温度；体温；气温；发烧', 4871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'candle', 'n. 蜡烛；烛光；烛形物 v. 对着光检查', 4872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bundle', 'n. 束；捆 v. 捆', 4873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overtake', 'v. 赶上；压倒；突然来袭', 4874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chaos', 'n. 混沌，混乱', 4875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hysterical', 'adj. 歇斯底里的；异常兴奋的', 4876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'meditation', 'n. 冥想；沉思，深思', 4877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accordance', 'n. 一致；和谐', 4878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'corridor', 'n. 走廊', 4879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chase', 'v. 追逐；追捕；试图赢得；雕镂 n. 追逐；追赶；追击', 4880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'restrain', 'v. 抑制，控制；约束；制止', 4881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'substance', 'n. 物质；实质；资产；主旨', 4882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adventure', 'n. 冒险；冒险精神；投机活动 v. 冒险；大胆说出', 4883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adverb', 'n. 副词 adj. 副词的', 4884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furnace', 'n. 火炉，熔炉', 4885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dubious', 'adj. 可疑的；暧昧的；无把握的；半信半疑的', 4886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'annoy', 'v. 骚扰；惹恼；打搅 n. 烦恼（等于annoyance）', 4887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'liable', 'adj. 有责任的，有义务的；应受罚的；有…倾向的；易…的', 4888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sticky', 'adj. 粘的；粘性的', 4889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thirsty', 'adj. 口渴的，口干的；渴望的，热望的', 4890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'basket', 'n. 篮子；（篮球比赛的）得分；一篮之量；篮筐 vt. 装入篮', 4891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chart', 'n. 图表；海图；图纸；排行榜 v. 绘制…的图表；在海图上标出；详细计划；记录；记述；跟踪（进展或发展', 4892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'nut', 'n. 螺母，螺帽；坚果；难对付的人，难解的问题 v. 采坚果', 4893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'upstairs', 'adv. 在楼上，向楼上；上楼；往楼上 adj. 楼上的 n. 楼上', 4894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'garden', 'n. 花园；菜园 v. 栽培花木', 4895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mate', 'n. 助手，大副；配偶；同事；配对物 v. 使配对；使一致；结伴', 4896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vertical', 'adj. 垂直的，直立的；[解剖] 头顶的，顶点的 n. 垂直线，垂直面', 4897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cemetery', 'n. 墓地；公墓', 4898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fairy', 'n. 仙女，小精灵；漂亮姑娘 adj. 虚构的；仙女的', 4899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lantern', 'n. 灯笼；提灯；灯笼式天窗', 4900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ignorant', 'adj. 无知的；愚昧的', 4901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glitter', 'v. 闪光；闪烁 n. 闪光；灿烂', 4902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vest', 'n. 背心；汗衫 v. 授予；使穿衣', 4903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orange', 'adj. 橙色的；橘色的 n. 橙；橙色；桔子', 4904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'persecute', 'v. 迫害；困扰；同…捣乱', 4905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'veto', 'n. 否决权 v. 否决；禁止', 4906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'agriculture', 'n. 农业；农耕；农业生产；农艺，农学', 4907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'housewife', 'n. 家庭主妇', 4908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'preliminary', 'n. 准备；预赛；初步措施 adj. 初步的；开始的；预备的', 4909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chalk', 'v. 用粉笔写；用白垩粉擦；记录；规划 n. 粉笔；白垩；用粉笔划的记号 adj. 用粉笔写的', 4910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ceiling', 'n. 天花板；上限', 4911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'navigation', 'n. 航行；航海', 4912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'communism', 'n. 共产主义', 4913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scarf', 'n. 围巾；嵌接，嵌接处；头巾领巾 v. 披嵌接；用围巾围', 4914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scare', 'v. 惊吓；把…吓跑 n. 恐慌；惊吓；惊恐 adj. （美）骇人的', 4915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'engagement', 'n. 婚约；约会；交战；诺言', 4916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'uproar', 'n. 骚动；喧嚣', 4917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mouse', 'n. 鼠标；老鼠；胆小羞怯的人 v. 探出', 4918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'romance', 'n. 传奇；浪漫史；风流韵事；冒险故事 v. 虚构；渲染；写传奇', 4919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verb', 'n. 动词；动词词性；动词性短语或从句 adj. 动词的；有动词性质的；起动词作用的', 4920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tutor', 'v. 辅导；约束 n. 导师；家庭教师；助教', 4921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sociable', 'adj. 社交的；好交际的；友善的 n. 联谊会', 4922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dirty', 'adj. 下流的，卑鄙的；肮脏的；恶劣的；暗淡的 v. 弄脏', 4923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'transparent', 'adj. 透明的；显然的；坦率的；易懂的', 4924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'forecast', 'v. 预报，预测；预示 n. 预测，预报；预想', 4925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infrared', 'n. 红外线 adj. 红外线的', 4926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mourn', 'v. 哀悼；忧伤；服丧', 4927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'chill', 'n. 寒冷；寒意；寒心 adj. 寒冷的；冷漠的；扫兴的 v. 冷冻，冷藏；使寒心；使感到冷', 4928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'myth', 'n. 神话；虚构的人，虚构的事', 4929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'designate', 'v. 指定；指派；标出；把…定名为 adj. 指定的；选定的', 4930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'clarity', 'n. 清楚，明晰；透明', 4931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'whisky', 'n. 威士忌酒 adj. 威士忌酒的', 4932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'pretend', 'v. 假装，伪装，佯装 adj. 假装的', 4933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scan', 'v. 扫描；浏览；细看；详细调查；标出格律 n. 扫描；浏览；审视；细看', 4934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'strife', 'n. 冲突；争吵；不和', 4935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'magnet', 'n. 磁铁；[电磁] 磁体；磁石', 4936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'graceful', 'adj. 优雅的；优美的', 4937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cashier', 'n. 出纳员；司库；收银员 v. 解雇；抛弃', 4938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'daylight', 'n. 白天；日光；黎明；公开', 4939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'litre', 'n. [计量] 公升（米制容量单位）', 4940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mortal', 'adj. 凡人的；致死的；终有一死的；不共戴天的 n. 人类，凡人', 4941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'articulate', 'v. 清晰地发（音）；明确有力地表达；用关节连接；使相互连贯 adj. 发音清晰的；口才好的；有关节的 n. 【动物学】有节体的动物', 4942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stare', 'v. 凝视，盯着看；显眼 n. 凝视；注视', 4943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vigorous', 'adj. 有力的；精力充沛的', 4944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sacrifice', 'n. 牺牲；祭品；供奉 v. 牺牲；献祭；亏本出售', 4945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'milk', 'n. 牛奶；乳状物 v. 榨取；挤…的奶', 4946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mild', 'adj. 温和的；轻微的；淡味的；文雅的；不含有害物质的的 n. （英国的一种）淡味麦芽啤酒', 4947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'continuous', 'adj. 连续的，持续的；继续的；连绵不断的', 4948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overseas', 'adv. 在海外，海外 adj. 海外的，国外的', 4949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stride', 'n. 大步；步幅；进展 v. 跨过；大踏步走过；跨坐在…', 4950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'probable', 'adj. 很可能的；可信的 n. 很可能的事；大有希望的候选者', 4951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'jungle', 'n. 丛林，密林；危险地带 adj. 丛林的；蛮荒的', 4952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conclusion', 'n. 结论；结局；推论', 4953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'propaganda', 'n. 宣传；传道总会', 4954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'valley', 'n. 山谷；流域；溪谷', 4955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'foolish', 'adj. 愚蠢的；傻的', 4956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'delegate', 'v. 委派…为代表 n. 代表', 4957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'irrigate', 'v. 灌溉；冲洗；使清新', 4958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blanket', 'n. 毛毯，毯子；毯状物，覆盖层 adj. 总括的，全体的；没有限制的 v. 覆盖，掩盖；用毯覆盖', 4959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'genuine', 'adj. 真实的，真正的；诚恳的', 4960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'district', 'n. 区域；地方；行政区', 4961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assassinate', 'v. 暗杀；行刺', 4962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'mutter', 'v. 咕哝；喃喃自语 n. 咕哝；喃喃低语', 4963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fortnight', 'n. 两星期', 4964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tackle', 'n. 滑车；装备；用具；扭倒 v. 处理；抓住；固定；与…交涉', 4965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blush', 'v. 脸红；感到惭愧 n. 脸红；红色；羞愧', 4966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'missionary', 'adj. 传教的；传教士的 n. 传教士', 4967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'bloody', 'adj. 血腥的；非常的；嗜杀的，残忍的；血色的 v. 使流血 adv. 很', 4968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'ego', 'n. 自我；自负；自我意识', 4969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'indicative', 'adj. 象征的；指示的；表示…的 n. 陈述语气；陈述语气的动词形式', 4970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'courage', 'n. 勇气；胆量', 4971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'beach', 'n. 海滩；湖滨 v. 将…拖上岸', 4972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'egg', 'n. 蛋；卵子；家伙；鸡蛋 v. 煽动；怂恿', 4973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skin', 'n. 皮肤；外皮 v. 剥皮', 4974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skim', 'v. 略读；撇去…的浮物；从…表面飞掠而过；去除；（为逃税而）隐瞒（部分收入） n. 撇；撇去的东西；表层物；瞒报所得的收入 adj. 脱脂的；撇去浮沫的；表层的', 4975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'semiconductor', 'n. [电子][物] 半导体', 4976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'commute', 'v. （搭乘车、船等）通勤；代偿 n. 通勤（口语）', 4977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'splendid', 'adj. 辉煌的；灿烂的；极好的；杰出的', 4978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'contradiction', 'n. 矛盾；否认；反驳', 4979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'temptation', 'n. 引诱；诱惑物', 4980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'coward', 'n. 懦夫，懦弱的人 adj. 胆小的，懦怯的', 4981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'yell', 'v. 大叫，叫喊 n. 喊声，叫声', 4982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fountain', 'n. 喷泉，泉水；源泉', 4983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obstruction', 'n. 障碍；阻碍；妨碍', 4984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'redundant', 'adj. 多余的，过剩的；被解雇的，失业的；冗长的，累赘的', 4985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'veil', 'n. 面纱；面罩；遮蔽物；托词 v. 遮蔽；掩饰；以面纱遮掩；用帷幕分隔', 4986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'skeleton', 'n. 骨架，骨骼；纲要；骨瘦如柴的人 adj. 骨骼的；骨瘦如柴的；概略的', 4987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quench', 'v. 熄灭，[机] 淬火；解渴；结束；冷浸', 4988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vein', 'n. 血管；叶脉；[地质] 岩脉；纹理；翅脉；性情 v. 使成脉络；象脉络般分布于', 4989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'quota', 'n. 配额；定额；限额', 4990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'intelligible', 'adj. 可理解的；明了的；仅能用智力了解的', 4991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blow', 'n. 吹；打击；殴打 v. 风吹；喘气', 4992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flatter', 'v. 奉承；谄媚；使高兴', 4993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'decimal', 'adj. 小数的；十进位的 n. 小数', 4994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'diagnose', 'v. 诊断；断定', 4995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'vinegar', 'n. 醋', 4996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'infect', 'v. 感染，传染', 4997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'costume', 'n. 服装，装束；戏装，剧装 v. 给…穿上服装', 4998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'thief', 'n. 小偷，贼', 4999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'turkey', 'n. 火鸡；笨蛋；失败之作', 5000);
