INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'range', 'n. 范围； 距离； 领域 <；排列； 连续；脉 vt. 排列成行', 9501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sportsman', 'n. 运动员', 9502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'derive', 'vi. 起源 vt. 取得； 导出， 引申', 9503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overseas', 'adv. 在海外 adj. 外国的， 海外的 <', 9504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'overhear', 'vt. 偶然听到， 从旁听到', 9505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'impress', 'vt. 印， 盖印；留下印象， 引人注目 < n. 印记', 9506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leak', 'v. 漏；泄漏 n. 漏洞， 漏隙；泄漏， 漏出', 9507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flaw', 'n. 裂缝；缺陷', 9508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'feature', 'v. 以…为特点 n. 特征， 特色；特写', 9509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lean', 'vi. 倾斜； 屈身；倚， 靠； 依赖 adj. 瘦的， 无脂肪的', 9510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assert', 'vt. 断言， 宣称 <', 9511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'climax', 'n. 顶点； 高潮', 9512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'recall', 'vt. 回忆， 回想 <；撤销， 收回', 9513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flap', 'v. 拍打， 拍动 n. 垂下物； 帽檐； 袋盖；慌乱， 紧张', 9514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'leap', 'vi. 跳， 跳跃 < n. 跳跃， 飞跃', 9515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'objection', 'n. 反对， 异议', 9516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'dispute', 'vi. 争论， 争执 n. 争论， 辩论', 9517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blouse', 'n. 女衬衫', 9518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'observation', 'n. 观察； 观测； 监视；观察资料或报告； 言论', 9519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tremble', 'vi. 发抖， 颤抖；摇动， 晃动', 9520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'inhabitant', 'n. 居民， 住户', 9521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fraction', 'n. 碎片； 小部分， 一点儿；分数', 9522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'token', 'adj. 象征性的 n. 表示， 象征； 标志， 记号；礼券， 代金券；信物； 纪念品；筹码', 9523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'filter', 'vi. 滤过， 渗透 n. 滤器； 滤纸； 滤嘴', 9524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spaceship', 'n. 宇宙飞船', 9525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cease', 'n. /', 9526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'emotion', 'n. 情绪； 情感', 9527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'assess', 'vt. 估价， 评价', 9528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'robe', 'n. 长袍， 上衣', 9529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'prescription', 'n. 药方， 处方', 9530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'spectator', 'n. 观众； 旁观者', 9531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'behaviour', 'n. 行为， 举止；特性； 运转情况 A', 9532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'scarce', 'adj. 缺乏的， 不足的；稀少的， 罕见的', 9533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'queue', 'vi. 排队 n. 行列， 长队', 9534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'argument', 'n. 争论， 辩论；论据， 论点', 9535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'utter', 'adj. 彻底的， 完全的 vt. 说， 发出', 9536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'adequate', 'adj. 足够的， 充分的； 恰当的', 9537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hopeful', 'adj. 有希望的， 给以人希望的；抱有希望的； 充满希望的', 9538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sausage', 'n. 香肠， 腊肠', 9539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tremendous', 'adj. 巨大的， 极大的', 9540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'escalate', 'v. 逐步增长或发展， 更紧张；逐步上升， 逐步加强， 扩大', 9541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'condense', 'v. 压缩， 凝结；精简， 压缩', 9542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'divert', 'vt. 使转向， 使改道；转移， 转移…的注意力 <；使娱乐， 使消遣', 9543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hygiene', 'n. 卫生', 9544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'justice', 'n. 正义； 公平；审判， 司法， 法律制裁', 9545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'conspicuous', 'adj. 显眼的； 明显的', 9546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tag', 'n. 标签， 货签 vt. 贴标签于', 9547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'verse', 'n. 韵文， 诗；诗节， 诗句', 9548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'furious', 'adj. 狂怒的； 狂暴的， 猛烈的', 9549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'obesity', 'n. 肥大， 肥胖', 9550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tan', 'vi. 晒黑 adj. 棕褐色的 n. 黝黑', 9551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tar', 'n. 柏油， 焦油', 9552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'individual', 'adj. 个人的； 单独的； 独特的 < n. 个人， 个体', 9553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'briefcase', 'n. 公文包， 公事包', 9554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'snowstorm', 'n. 暴风雪 A', 9555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tax', 'n. 税；负担 vt. 对…征税；使负重担； 使受压力', 9556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'constrain', 'vt. 束缚， 限制；强迫， 强制', 9557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'excitement', 'n. 刺激； 激动， 兴奋', 9558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'blueprint', 'n. 蓝图； 方案', 9559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'interim', 'adj. 暂时的， 临时的 n. 间歇； 过渡期间', 9560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'testimony', 'n. 证据； 证词；表明， 说明', 9561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'enforce', 'vt. 实施， 执行 <；强制 <', 9562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glitter', 'vi. 闪耀 n. 光辉， 灿烂', 9563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'departure', 'n. 离开， 起程', 9564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fragile', 'adj. 易碎的， 易损的；脆弱的， 易受伤害的', 9565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'reflexion', 'n. 映像， 倒影；反省， 沉思', 9566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'cab', 'n. 出租汽车； 轻便马车；司机室， 驾驶室 A', 9567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'sociology', 'n. 社会学', 9568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'gigantic', 'adj. 巨大的， 庞大的', 9569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'flee', 'vi. 逃走； 逃避；消失', 9570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'distinct', 'adj. 清楚的， 明显的；截然不同的', 9571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'geology', 'n. 地质', 9572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hedge', 'n. 篱笆， 树篱； 障碍物 vt. 保护…以免； 预防', 9573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'weep', 'v. 哭泣； 流泪 n. 悲叹， 哀悼， 为…伤心', 9574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'tune', 'v. 调音； 调频；调整； 调节 n. 调子， 曲调', 9575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hoist', 'vt. 举起， 升起， 吊起', 9576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'aware', 'adj. 知道的， 意识到的', 9577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'numerical', 'adj. 数字的， 用数字表示的', 9578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'drama', 'n. 戏剧； 剧本；戏剧性事件或场面', 9579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'award', 'n. 奖 vt. 授予， 奖给', 9580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'eligible', 'adj. 有条件被选中的， 有资格当选的； 合格的', 9581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'stove', 'n. 炉子， 火炉', 9582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'alarm', 'n. 警报；惊恐， 惊慌 vt. 使惊恐， 惊动， 惊吓 A；向…报警； 警告', 9583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'appraisal', 'n. 估计， 估量；评价', 9584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'weed', 'v. 锄草 n. 杂草， 野草', 9585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'glacier', 'n. 冰河， 冰川', 9586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'balloon', 'n. 气球', 9587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'orientation', 'n. 方向， 方位， 定位；熟悉， 适应； 〈主美〉 情况介绍', 9588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'motion', 'n. 运动， 动；提议， 动议 vt. 向…示意 A', 9589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'idle', 'adj. 空闲的， 闲置的；无用的， 无效的；懒散的 vt. 浪费， 虚度', 9590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'limited', 'adj. 有限的， 被限制的', 9591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'plight', 'n. 困境， 苦境', 9592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'hail', 'vi. 下雹 vt. 向…欢呼， 欢迎 A n. 冰雹', 9593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fearful', 'adj. 可怕的', 9594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'accent', 'n. 腔调； 口音 A；重音', 9595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'passive', 'adj. 被动的， 消极的 <', 9596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'lorry', 'n. 卡车， 运货汽车', 9597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'fragment', 'n. 碎片； 小部分， 片断 <', 9598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'carrier', 'n. 运送者， 载体； 携带者', 9599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'response', 'n. 回答， 回音；反应， 响应', 9600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'category', 'n. 种类', 9601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (9, 'rival', 'adj. 竞争的， 对手的 n. 竞争者， 对手 vt. 竞争， 对抗', 9602);
