INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slum', 'n. 贫民窟', 7501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detection', 'n. 察觉, 侦查', 7502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glider', 'n. 滑行(或物), 滑翔机', 7503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anytime', 'adv. 任何时候, 无论何时', 7504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intuitive', 'adj. 有直觉力的，直觉到的', 7505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undernutrition', 'n. 营养不良', 7506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urgent', 'adj. 急迫的, 紧急的', 7507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hohokam', 'adj. 霍霍坎文化的', 7508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irresponsible', 'adj. 不负责任的, 不可靠的', 7509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrospect', 'n. 回顾', 7510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronic', 'adj. 慢性的, 延续很长的', 7511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'index', 'n. 索引, 指数', 7512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flatfish', 'n. 比目鱼', 7513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attic', 'n. 阁楼', 7514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sundial', 'n. 日昝仪, 日规', 7515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'butte', 'n. 孤立的丘', 7516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lightly', 'adv. 轻轻地, 轻松地', 7517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uneducated', 'adj. 没受教育的；文盲的', 7518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'securely', 'adv. 安全地；无疑地', 7519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncorrupt', 'adv. 不腐败的;廉洁的', 7520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landscapist', 'n. 风景画家', 7521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scenery', 'n. 风景, 景色', 7522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'complimentary', 'adj. 称赞的；免费的', 7523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incorporation', 'n. 合并；组建公司', 7524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sobriquet', 'n. 假名, 绰号', 7525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'socialize', 'v. 使社会化, 使社会主义化', 7526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rename', 'v. 重新命名, 改名', 7527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awaken', 'v. 唤醒, 醒来', 7528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'afflict', 'v. 使痛苦, 折磨', 7529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'governance', 'n. 统治, 管理', 7530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'methodically', 'adv. 有条不紊地, 有方法地', 7531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feverishly', 'adv. 兴奋地, 发热地', 7532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'personnel', 'n. 人员, 职员', 7533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antifungal', 'adj. 抗真菌的, 杀真菌的', 7534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'senior', 'adj. 年长的, 资格较老的', 7535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flashy', 'adj. 浮华的', 7536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dimly', 'adv. 微暗, 朦胧', 7537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'earthward', 'adv. 向地球, 向地面', 7538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'justice', 'n. 正义, 公平', 7539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overwhelmingly', 'adv. 压倒性地, 不可抵抗地', 7540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assembly', 'n. 集会，集合;组装', 7541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stressful', 'adj. 紧张的, 压力重的', 7542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exertion', 'n. 努力, 发挥,运用', 7543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deformity', 'n. 残缺, 畸形', 7544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disruptive', 'adj. 使破裂的, 分裂性的', 7545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'girder', 'n. 梁', 7546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bustle', 'v. 匆匆忙忙', 7547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unforeseen', 'adj. 无法预料的', 7548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conversational', 'adj. 会话的, 对话的', 7549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'governor', 'n. 统治者, 管理者', 7550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abbreviate', 'v. 缩写, 简化', 7551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'restrain', 'v. 抑制, 制止', 7552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'broadcaster', 'n. 播送设备, 广播员', 7553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adviser', 'n. 顾问,', 7554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clarification', 'n. 澄清, 净化', 7555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awful', 'adj. 可怕的, 威严的,', 7556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speechwriter', 'n. 演讲稿撰写人', 7557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'televisual', 'adj. 电视的', 7558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electrify', 'v. 使充电, 使通电', 7559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'legislative', 'adj. 立法的, 立法机关的', 7560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melodic', 'adj. 有旋律的,调子美妙的', 7561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predictably', 'adv. 可预言地, 不出所料地', 7562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'climatically', 'adv. 气候上, 风土上', 7563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lethargic', 'adj. 昏睡的', 7564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chicken', 'n. 小鸡', 7565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compute', 'v. 计算, 估计', 7566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pathology', 'n. 病理学', 7567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'offend', 'v. 犯罪, 冒犯', 7568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disk', 'n. 磁盘,圆盘', 7569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helper', 'n. 帮忙者, 助手', 7570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'triangular', 'adj. 三角形的, 三人间的', 7571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'counsel', 'n. 律师 vt劝告，提议', 7572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'programme', 'n. 程序, 编程', 7573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curvature', 'n. 弯曲, 曲率', 7574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endpoint', 'n. 端点', 7575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vocational', 'adj. 职业的，业务的', 7576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'datebase', 'n. 数据库, 资料库', 7577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compulsory', 'adj. 强制的,  义务的', 7578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shyness', 'n. 羞怯, 胆怯', 7579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lethargy', 'n. 无生气', 7580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hostility', 'n. 敌意, 不友善', 7581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'credential', 'n. 外交使节所递的国书, 信任状', 7582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disorientation', 'n. 迷失方向, 迷惑', 7583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'additionally', 'adv. 另外, 同时', 7584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uninterrupted', 'adj. 不停的, 连续的', 7585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bureaucratization', 'n. 官化', 7586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excursion', 'n. 远足，短途旅行', 7587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dissension', 'n. 意见不同, 纠纷', 7588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embryonic', 'adj. 胚胎的，萌芽期的', 7589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'breakup', 'n. 破裂, 崩溃', 7590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'necklace', 'n. 项链', 7591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bylaw', 'n. 附则, 法规', 7592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'republish', 'v. 再版, 重新发表', 7593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'publicly', 'adv. 公然地, 舆论上', 7594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distantly', 'adj. 疏远的, 遥远的', 7595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oily', 'adj. 油的, 油滑的', 7596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'assault', 'n&v. 攻击, 袭击', 7597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fierce', 'adj. 凶猛的, 猛烈的', 7598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'categorize', 'v. 加以类别, 分类', 7599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'severity', 'n. 严肃, 严格', 7600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'definitively', 'adv. 决定性地, 最后地', 7601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lineage', 'n. 血统, 世系', 7602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slam', 'v. 砰地关上(放下)', 7603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flaming', 'adj. 熊熊燃烧的；热情的', 7604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pique', 'n. 生气, 愤怒', 7605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'internet', 'n. 国际互联网，因特网', 7606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'newscast', 'n. <美>新闻广播', 7607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fateful', 'adj. 重大的；不幸的', 7608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antipathy', 'n. 憎恶, 反感', 7609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hurtle', 'v. 急飞', 7610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glisten', 'v. 闪光', 7611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'predate', 'v. 提早日期, 居先', 7612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Finnish', 'adj. 芬兰的', 7613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cenote', 'n. 天然井', 7614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empathy', 'n. 移情作用, 共鸣', 7615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardwood', 'n. 硬木, 阔叶树', 7616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sash', 'n. 腰带，肩带', 7617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prohibit', 'v. 禁止, 阻止', 7618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foment', 'v. [医]热敷', 7619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gesture', 'n. 姿态, 手势', 7620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretentious', 'adj. 自命不凡的，自负的', 7621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heredity', 'n. 遗传, 形质遗传', 7622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'yean', 'v. 生产, 生育', 7623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dining', 'n. 吃饭', 7624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amenity', 'n. 宜人, 礼仪', 7625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'changeover', 'n. 转换, 大变更', 7626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meander', 'v. 蜿蜒而行', 7627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skylight', 'n. 天窗', 7628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'palatable', 'adj. 味美的', 7629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contender', 'n. 竞争者', 7630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invariable', 'n&a. 不变的, 永恒的', 7631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depreciation', 'n. 贬值, 减价', 7632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unspecified', 'adj. 未详细说明的', 7633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disability', 'n. 无力, 残疾', 7634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helplessness', 'n. 无能为力', 7635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retentive', 'adj. 有记忆力的', 7636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amplifier', 'n. 扩音器, 放大器', 7637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scan', 'n&v. 扫描；浏览', 7638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unfailingly', 'adv. 无穷尽地, 可靠地', 7639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swell', 'v. (使)膨胀, 增大', 7640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'needless', 'adj. 不需要的, 不必要的', 7641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bulge', 'n&v. 膨胀，鼓起', 7642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undiscovered', 'adj. 未被发现的', 7643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helplessly', 'adv. 无能为力地', 7644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overnight', 'ad& a. (在)整夜(的)；突然(的)', 7645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dentist', 'n. 牙科医生', 7646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optometrist', 'n. 验光师, 视力测定者', 7647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'merciless', 'adj. 残忍的；无情的', 7648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'strenuous', 'adj. 奋发的, 费力的, 积极的', 7649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'passion', 'n. 激情，热情', 7650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emancipate', 'v. 释放, 解放', 7651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'protagonist', 'n. 提倡者，支持者', 7652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leo', 'n. [天]狮子座，狮子宫', 7653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cruel', 'adj. 残酷的, 悲惨的', 7654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grimly', 'adv. 严格地,冷酷地', 7655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'apportion', 'v. 分配', 7656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commentator', 'n. 评论员, 解说员', 7657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repay', 'v. 偿还, 报答', 7658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'earning', 'n. 所得,收入', 7659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bankruptcy', 'n. 破产', 7660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subjugation', 'n. 镇压, 平息', 7661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uncontrollably', 'adj. 无法管束的, 控制不住的', 7662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lazily', 'adv. 懒洋洋地', 7663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radioactive', 'adj. 放射性的，有辐射能的', 7664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consortium', 'n. 财团, 联合, 合伙', 7665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preventive', 'adj. 预防性的', 7666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'supplementary', 'adj. 增补的，补充的', 7667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'multidirectional', 'adj. 多方向的', 7668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'booklet', 'n. 小册子', 7669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curio', 'n. 古董, 古玩', 7670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chandler', 'n. 杂货零售商', 7671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speck', 'n. 斑点', 7672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stair', 'n. 楼梯', 7673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'encircle', 'v. 环绕, 围绕', 7674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'surmount', 'v. 克服；置于…顶上', 7675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heading', 'n. 标题', 7676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Californian', 'n. 加利福尼亚州人 a加州的', 7677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reaumur', 'n&a. 列氏温度计(的)', 7678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mycology', 'n. [植]真菌学', 7679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glean', 'v. 拾落穗, 收集', 7680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nevus', 'n. [医]痣', 7681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'watcher', 'n. 监票员, 看守人', 7682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'filament', 'n. 细丝, 灯丝', 7683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thermal', 'adj. 热的, 热量的', 7684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ostrich', 'n. 鸵鸟', 7685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faintly', 'adv. 微弱地, 朦胧地', 7686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dazzlingly', 'adv. 灿烂地, 耀眼地', 7687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tint', 'n. 色彩', 7688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'varve', 'n. [地质]纹泥', 7689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'server', 'n. 服务器', 7690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'benign', 'adj. 仁慈的, 温和的, 良性的', 7691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feathery', 'adj. 生有羽毛的,柔软如羽毛的', 7692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'churn', 'v. 搅拌, 搅动', 7693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'awhile', 'adv. 片刻, 一会儿', 7694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proudly', 'adv. 骄傲地', 7695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pedestrian', 'n. 步行者，行人', 7696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'oilskin', 'n. 油布, 防水布', 7697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'splash', 'n&v. 溅, 飞溅', 7698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unnoticed', 'adj. 不被注意的, 被忽视的', 7699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thunderous', 'adj. 打雷的, 雷鸣般的', 7700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faraway', 'adj. 遥远的', 7701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ploy', 'n. 花招，手段', 7702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noisily', 'adv. 吵闹地', 7703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squeak', 'n. 吱吱声 v. 吱吱叫', 7704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crouch', 'v. 蜷缩, 蹲伏', 7705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'regain', 'v. 收回；恢复', 7706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outcome', 'n. 结果, 成果', 7707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'heroism', 'n. 英雄品质, 英雄主义', 7708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inconspicuously', 'adv. 难以觉察地, 不显著地', 7709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'matron', 'n. 主妇；护士长', 7710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspension', 'n. 暂停, 中止', 7711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stratagem', 'n. 战略, 计谋', 7712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'brood', 'v. 沉思；孵蛋 n一窝', 7713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vole', 'n. 田鼠', 7714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mimic', 'v. 模仿, 模拟', 7715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unmanageable', 'adj. 难处理的, 难控制的', 7716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rivet', 'n. 铆钉  v固定', 7717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hairy', 'adj. 毛发的，多毛的', 7718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reception', 'n. 招待会；接受', 7719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flyway', 'n. 候鸟迁徙所经的路径', 7720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nozzle', 'n. 管口, 喷嘴', 7721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bonanza', 'n. 走运，发财', 7722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electrician', 'n. 电工, 电学家', 7723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overburden', 'v. 装载过多, 负担过多', 7724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lavish', 'adj. 无节制的；浪费的 vt慷慨给予，挥霍', 7725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bravery', 'n. 勇敢', 7726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'creek', 'n. 小溪, 小河,', 7727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waster', 'n. 挥霍者, 废品', 7728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Stamford', 'n. 斯坦福德[美国康涅狄格州西南部城市]', 7729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gallon', 'n. 加仑', 7730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beer', 'n. 啤酒', 7731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tact', 'n. 机智, 手法', 7732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trapper', 'n. 捕兽者, 捕捉器', 7733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'romantically', 'adv. 浪漫地, 空想地', 7734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prosecute', 'v. 起(公)诉，告发', 7735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sonic', 'adj. 音速的', 7736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'enthusiast', 'n. 热心家, 狂热者', 7737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smoothly', 'adv. 平稳地', 7738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gingham', 'n. 条纹棉布', 7739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slipper', 'n. 拖鞋', 7740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'instantaneous', 'adj. 瞬间的，即刻的', 7741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shoeshine', 'n. 鞋油, 擦皮鞋', 7742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'politely', 'adv. 有礼貌地', 7743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modestly', 'adv. 谨慎地, 适当地', 7744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'balcony', 'n. 阳台, 包厢', 7745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'loudspeaker', 'n. 扩音器, 喇叭', 7746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confluence', 'n. 汇合', 7747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crunch', 'vi&n. 嘎吱嘎吱地响(声)', 7748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'juggle', 'v&n. 玩杂耍', 7749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seize', 'v. 抓住,夺取', 7750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mormon', 'n. 摩门教徒, 一夫多妻主义者', 7751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'atheist', 'n. 无神论者', 7752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gallop', 'n. /v疾驰, 飞奔', 7753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trestle', 'n. 架柱, 支架', 7754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ravine', 'n. 沟壑, 峡谷', 7755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spidery', 'adj. 蜘蛛(网)一般的, 细长足的', 7756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wildcatter', 'n. 投机份子', 7757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onlooker', 'n. 旁观者', 7758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'folly', 'n. 愚蠢, 荒唐事', 7759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lubricate', 'v. 润滑 v加润滑油', 7760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trespasser', 'n. 侵入者, 侵犯者', 7761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'waxes', 'n. 蜡，蜂蜡 vt给…上蜡', 7762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grocery', 'n. 食品杂货店', 7763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refiner', 'n. 精炼者, 精炼机', 7764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'richly', 'adv. 富裕地, 丰富地', 7765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'remodel', 'v. 重新塑造, 改造', 7766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kier', 'n. 漂煮锅', 7767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seepage', 'n. 渗流, 渗出的量', 7768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cooperative', 'adj. 合作的, 协力的', 7769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ponytail', 'n. 马尾辫(一种发型)', 7770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disuse', 'n&v. 废弃, 废止', 7771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'adequately', 'adv. 充分地', 7772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wither', 'v. 凋谢,枯萎', 7773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facsimile', 'n. 摹写, 传真', 7774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unproductive', 'adj. 不生产的, 徒劳的', 7775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'methodical', 'adj. 有条理的，井然的', 7776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contest', 'n&v. 论争, 竞赛', 7777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bike', 'n. 脚踏车, 自行车', 7778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indulge', 'v. 纵容', 7779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unnoticeable', 'adj. 不引人注意的(', 7780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'termination', 'n. 终止', 7781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dismay', 'n&v. 沮丧, 绝望', 7782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irreparable', 'adj. 无法修复的，不能挽回的', 7783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'birthright', 'n. 生来就有的权利, 长子继承权', 7784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'negotiation', 'n. 商议, 谈判', 7785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fruitless', 'adj. 不结果实的', 7786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conscription', 'n. 征召', 7787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aloof', 'adj. 冷漠的', 7788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'downtown', 'adv. 在市区 adj. 市区的', 7789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delectable', 'adj. 使人愉快的', 7790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intermittent', 'adj. 间歇的，断断续续的', 7791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hatchery', 'n. 孵卵所', 7792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'doggedly', 'adv. 固执地, 顽强地', 7793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'depot', 'n. 贮藏所, 仓库', 7794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Minnesota', 'n. 明尼苏达州(美国州名)', 7795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erupt', 'v. 喷出 vi爆发', 7796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'truck', 'n. 卡车, 敞棚货车', 7797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'phonetic', 'adj. 语音的,语音学的', 7798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lap', 'n. 膝上；一圈 v. 舔(食)；拍打', 7799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chic', 'adj. 别致的, 时髦的', 7800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'executive', 'n. 主管，行政官a行政的', 7801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slapstick', 'n. 闹剧, 趣剧', 7802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hairdo', 'n. 发型', 7803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maraca', 'n. [音]沙球', 7804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beater', 'n. 搅拌器', 7805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'picnic', 'n. 野餐', 7806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'craze', 'n. 狂热', 7807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'synthesizer', 'n. 综合者, [电子]合成器', 7808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liberation', 'n. 释放, 解放', 7809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thunder', 'n. 雷,雷声', 7810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blip', 'n. （在雷达屏幕显示出的）物体光点, 尖音信号', 7811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'excessively', 'adv. 过分地, 过度地, 极度地', 7812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'indiscernible', 'adj. 看不清的', 7813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lopsided', 'adj. 倾向一方的, 不平衡的', 7814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hippopotamus', 'n. 河马', 7815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'laugh', 'v&n. 笑, 笑声', 7816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'groan', 'n&v. 呻吟, 叹息', 7817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sneeze', 'n. 喷嚏 vi打喷嚏', 7818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tapir', 'n. [动]貘', 7819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scream', 'v. /n尖声叫, 尖叫声', 7820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'horsefly', 'n. 马蝇', 7821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonelectronic', 'adj. 非电子的', 7822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vestige', 'n. 痕迹', 7823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'baseball', 'n. 棒球(运动)', 7824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reverently', 'adv. 恭敬地, 虔诚地', 7825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'homeless', 'adj. 无家的, 无家可归的', 7826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mystify', 'v. 迷惑', 7827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mesmerize', 'v. 施催眠术', 7828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undifferentiated', 'adj. 无差别的, 一致的', 7829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gravitation', 'n. 地心吸力, 引力作用', 7830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'springtime', 'n. 春天, 春季', 7831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sled', 'n. (小)雪撬', 7832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ski', 'n. 滑雪板 vi滑雪', 7833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swampy', 'adj. 沼泽的，似沼泽的', 7834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pickaxe', 'n. 鹤嘴锄, 手镐', 7835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cubic', 'adj. 立方体的, 立方的', 7836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'taint', 'v. 感染 n污点', 7837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pestilential', 'adj. 引起瘟疫的, 有害的', 7838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'miasmic', 'adj. 毒气的, 瘴气的', 7839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onstage', 'adj. 台上的,舞台表演区的', 7840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'holm', 'n. (河，湖中的)小岛', 7841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'anymore', 'adv. 不再, 再也不', 7842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trainload', 'n. 装载量, 列车载重', 7843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ziggurat', 'n. 古代亚述及巴比伦之金字形神塔(顶上有神殿)', 7844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shapeless', 'adj. 不成形的, 无定形的', 7845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'troupe', 'n. 剧团', 7846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postmodern', 'adj. 后现代主义的', 7847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expressionless', 'adj. 无表情的', 7848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clumsy', 'adj. 笨拙的', 7849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foghorn', 'n. [航海]雾角,尖而响的声音', 7850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'majestic', 'adj. 雄伟的，壮丽的', 7851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'viennese', 'n&a. 维也纳人（语）(的)', 7852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commissioner', 'n. 委员, 专员', 7853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plum', 'n. [植] 李子, 洋李', 7854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seaman', 'n. 海员, 水手', 7855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stilt', 'n. 高跷, 支柱', 7856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stele', 'n. 石碑,  匾额', 7857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chronology', 'n. 年代学, 年表', 7858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overt', 'adj. 明显的, 公然的', 7859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'colorfully', 'adj. 华美的, 富有色彩的', 7860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eminence', 'n. 出众, 显赫', 7861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beacon', 'n. 信号灯，闪光灯', 7862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stubbornness', 'n. 倔强, 顽强', 7863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prearrange', 'v. 预先安排', 7864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'persevere', 'v. 坚持', 7865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'softball', 'n. 垒球运动, 垒球', 7866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Shakespeare', 'n. 莎士比亚(1564-1616,英国剧作家,诗人)', 7867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'abuse', 'n&v. 滥用, 虐待,辱骂', 7868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cither', 'n. 齐特拉琴(古希腊一种类似竖琴的古乐器)', 7869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'modernistic', 'adj. 现代的, 现代主义的', 7870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wick', 'n. 蜡烛心, 灯芯', 7871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corp', 'n. 公司', 7872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sturdiness', 'n. 强健, 雄壮, 坚固', 7873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wicker', 'n. 柳条 a柳条制的', 7874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'austere', 'adj. 简朴的, 严厉的', 7875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nationwide', 'adj. 全国性的', 7876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'astrological', 'adj. 占星的, 占星术的', 7877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mirage', 'n. 海市蜃楼,幻想', 7878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'repertory', 'n. 仓库', 7879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rescue', 'v. ／ n营救，救援', 7880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nearness', 'n. 靠近, 接近', 7881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pavlova', 'n. 奶油水果蛋白饼', 7882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nourishment', 'n. 食物, 营养品', 7883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'schoolroom', 'n. 教室', 7884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'helpless', 'adj. 无助的,没用的', 7885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grandparents', 'n. 外祖父母, 祖父母', 7886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fruitfulness', 'n. 多产, 肥沃', 7887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cathedral', 'n. 大教堂', 7888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ignition', 'n. 点火, 点燃', 7889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midwestern', 'adj. 美国中西部的', 7890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interject', 'v. 插嘴, 突然插入', 7891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lightness', 'n. 轻盈, 灵活', 7892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'idyllic', 'adj. 田园短诗的, 牧歌的', 7893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resonance', 'n. 共鸣,  反响', 7894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allegory', 'n. 寓言', 7895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rainbow', 'n. 彩虹', 7896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pretense', 'n. 借口,伪装，自吹', 7897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gratuitous', 'adj. 无缘无故的；免费的', 7898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liveliness', 'n. 活泼', 7899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stench', 'n. 恶臭, 臭气', 7900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slime', 'n. 粘土, 粘液', 7901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tern', 'n. 三个一组, [鸟]燕鸥', 7902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'starlike', 'adj. 星形的, 星般闪烁的', 7903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slimy', 'adj. 黏滑的, 卑劣的', 7904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'germ', 'n. 微生物, 细菌', 7905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'storeroom', 'n. 储藏室, 库房', 7906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Oakland', 'n. 奥克兰(美国加利福尼亚州西部城市)', 7907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'allude', 'v. 暗指，提及', 7908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sunburst', 'n. 从云隙射下的阳光', 7909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lordly', 'adj. 高贵的；高傲的', 7910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ditch', 'n. 沟,  壕沟', 7911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebellious', 'adj. 反抗的，难控制的', 7912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disciple', 'n. 信徒, 弟子', 7913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arctic', 'adj. 北极的 n北极(圈)', 7914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tadpole', 'n. [动]蝌蚪', 7915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'propensity', 'n. 倾向', 7916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wildflower', 'n. 野花', 7917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stifle', 'v. 窒息, 抑制', 7918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whip', 'n. 鞭子 v鞭打', 7919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'debut', 'n. 首次演出，初次露面', 7920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sufficiency', 'n. 充足；充裕', 7921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rebel', 'n. 反叛分子 v. 反叛；反对', 7922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foray', 'v&n. 突袭，偷袭', 7923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pupil', 'n. 小学生', 7924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lacquer', 'n. 漆, 漆器', 7925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gobi', 'n. 戈壁', 7926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maiden', 'n. 少女, 处女', 7927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'academically', 'adv. 学业上', 7928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vaccinate', 'v. 接种疫苗，给…打防疫针', 7929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'summarization', 'n. 摘要, 概要', 7930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flu', 'n. 流感', 7931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'haphazardly', 'adv. 不规则地, 随意地', 7932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'geometrically', 'adv. 成几何级数(图形)地', 7933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solidly', 'adv. 坚硬地, 稳固地', 7934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'timid', 'adj. 胆小的, 羞怯的', 7935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embroider', 'v. 刺绣，修饰', 7936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drugstore', 'n. 药房, 杂货店', 7937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'speckle', 'n. 小斑点  vt点缀', 7938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gentlemanly', 'adj. 绅士派头的', 7939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gamble', 'v& n. (打)赌；投机，冒险', 7940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'override', 'v. 不顾，否决', 7941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'citadel', 'n. 根据地, 大本营', 7942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fresher', 'n. 大学一年级新生, 新鲜人', 7943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outcry', 'n. 大声疾呼', 7944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'edit', 'v. 编辑, 校订', 7945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'postgraduate', 'n. 研究生', 7946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'manifesto', 'n. 宣言, 声明', 7947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'treasurer', 'n. 司库,财务主管', 7948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gnaw', 'v. 啃，咬', 7949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endear', 'v. 使亲密', 7950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industrious', 'adj. 勤劳的, 勤奋的', 7951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'participator', 'n. 参加者', 7952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trespass', 'n&v. 侵犯，擅自进入', 7953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'darn', 'v. 缝补，补缀', 7954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'irony', 'n. 反话, 讽刺', 7955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cheerless', 'adj. 不快活的', 7956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sovereignty', 'n. 君主, 主权', 7957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renunciation', 'n. 放弃，抛弃', 7958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Calvinist', 'n. 加尔文教徒(见Calvin)', 7959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sociability', 'n. 好交际,善于交际', 7960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frivolity', 'n. 轻薄,轻浮', 7961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'womanhood', 'n. 女人,女人气质', 7962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stern', 'adj. 严厉的 n. 船尾', 7963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'patriarchal', 'adj. 家长的, 族长的', 7964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disinterest', 'n. 无兴趣, 不关心', 7965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grip', 'v. 握紧，抓牢', 7966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'luce', 'n. 一种成鱼', 7967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'writhe', 'v. 翻滚，扭动', 7968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overhead', 'ad& a. 在头顶上(的)', 7969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embroidery', 'n. 刺绣(品)', 7970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hobby', 'n. 业余爱好', 7971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radish', 'n. [植]萝卜', 7972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ventilation', 'n. 通风, 流通空气', 7973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'babble', 'v. 说蠢话，牙牙学语', 7974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'belle', 'n. 美女', 7975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fragility', 'n. 脆弱, 虚弱', 7976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'innocence', 'n. 清白', 7977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonconformity', 'n. 不信奉国教', 7978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cardinal', 'adj. 主要的, 最重要的', 7979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'willingly', 'adv. 自动地, 欣然地', 7980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fervor', 'n. 热情, 热烈', 7981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undergraduate', 'n. (尚未取得学位的)大学生', 7982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rosy', 'adj. 蔷薇色的, 玫瑰红色的', 7983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telecommuter', 'n. 远程工作者', 7984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seduce', 'v. 勾引；引诱', 7985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'programmer', 'n. 程序师, 程序规划员', 7986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'paycheck', 'n. 薪水支票, 工资', 7987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disillusion', 'v. 醒悟', 7988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accountant', 'n. 会计(员), 会计师', 7989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tranquil', 'adj. 安静的', 7990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solitude', 'n. 孤独', 7991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chary', 'adj. 小心的，审慎的', 7992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'farmhand', 'n. 农业工人，农场工人', 7993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tardiness', 'n. 缓慢', 7994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'harvester', 'n. 收割机', 7995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reliant', 'adj. 信赖的, 依靠的', 7996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'facet', 'n. 小平面, 方面, 刻面', 7997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transpose', 'v. 调换, 颠倒顺序', 7998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'culturally', 'adv. 人文地, 文化地', 7999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'iconographic', 'adj. 肖像的, 图像材料的', 8000);
