INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'empire', 'n. 帝国；帝王统治，君权', 3501);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worker', 'n. 工人；劳动者；职蚁', 3502);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'weekday', 'n. 平日，普通日；工作日', 3503);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'controversial', 'adj. 有争议的；有争论的', 3504);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'company', 'n. 公司；陪伴，同伴；连队 v. 交往', 3505);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Spanish', 'adj. 西班牙的；西班牙人的；西班牙语的 n. 西班牙语；西班牙人', 3506);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mile', 'n. 英里；一英里赛跑；较大的距离', 3507);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dry', 'adj. 干的；口渴的；枯燥无味的；禁酒的 v. 把…弄干 n. 干涸', 3508);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'skirt', 'n. 裙子 v. 绕过，回避；位于…边缘', 3509);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sign', 'n. 迹象；符号；记号；手势；指示牌 v. 签署；签名', 3510);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'playroom', 'n. 游戏室；娱乐室', 3511);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hole', 'n. 洞，孔；洞穴，穴；突破口 v. 凿洞，穿孔；（高尔夫球等）进洞', 3512);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fingernail', 'n. 手指甲', 3513);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spoon', 'n. 匙，勺子；一杓的量 v. 用匙舀；使成匙状', 3514);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'assess', 'v. 评定；估价；对…征税', 3515);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'middle', 'adj. 中间的，中部的；中级的，中等的 n. 中间，中央；腰部', 3516);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cartoon', 'n. 卡通片，[电影] 动画片；连环漫画 v. 为…画漫画', 3517);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mail', 'n. 邮件；邮政，邮递；盔甲 v. 邮寄；给…穿盔甲', 3518);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cafeteria', 'n. 自助餐厅', 3519);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'violinist', 'n. 小提琴演奏者，小提琴家', 3520);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unpleasant', 'adj. 讨厌的；使人不愉快的', 3521);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'relationship', 'n. 关系；关联', 3522);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'receiver', 'n. 接收器；接受者；收信机；收款员，接待者', 3523);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'health', 'n. 健康；卫生；保健；兴旺', 3524);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pea', 'n. 豌豆', 3525);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grill', 'v. 烧，烤； n. 烤架，铁格子；烤肉', 3526);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'softball', 'n. 垒球；垒球运动', 3527);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'seaweed', 'n. 海藻，海草', 3528);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coral', 'n. 珊瑚；珊瑚虫 adj. 珊瑚的；珊瑚色的', 3529);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rush', 'n. 冲进；匆促；急流；灯心草 adj. 急需的 v. 使冲；突袭；匆忙地做；飞跃', 3530);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'narrow', 'adj. 狭窄的，有限的；勉强的；精密的；度量小的 n. 海峡；狭窄部分，隘路 v. 使变狭窄', 3531);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'boot', 'v. 引导；踢；解雇；使穿靴 n. 靴子；踢；汽车行李箱', 3532);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'claw', 'n. 爪；螯，钳；爪形器具 v. 用爪抓（或挖）', 3533);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'answer', 'v. 回答；符合 n. 回答；答案；答辩', 3534);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'own', 'v. 拥有；承认 adj. 自己的；特有的 n. 自己的', 3535);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rhyme', 'n. 韵律；韵脚；韵文；押韵词 v. 使押韵；用韵诗表达；把…写作诗', 3536);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'likely', 'adj. 很可能的；合适的；有希望的 adv. 很可能；或许', 3537);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plain', 'adj. 平的；简单的；朴素的；清晰的 n. 平原；无格式；朴实无华的东西 adv. 清楚地；平易地', 3538);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Frenchman', 'n. 法国人', 3539);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'socialism', 'n. 社会主义', 3540);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'experience', 'n. 经验；经历；体验 v. 经验；经历；体验', 3541);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'awful', 'adj. 可怕的；极坏的；使人敬畏的', 3542);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'applicant', 'n. 申请人，申请者；请求者', 3543);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'speak', 'v. 说话；演讲；表明；陈述', 3544);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'saleswoman', 'n. [贸易] 女售货员；[贸易] 女店员', 3545);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'twelfth', 'adj. 第十二的，第十二个的；十二分之一的 n. 第十二；月的第十二日', 3546);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'nail', 'v. 钉；使固定；揭露 n. [解剖] 指甲；钉子', 3547);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fancy', 'n. 幻想；想象力；爱好 adj. 想象的；奇特的；昂贵的；精选的 v. 想象；喜爱；设想；自负', 3548);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'disability', 'n. 残疾；无能；无资格；不利条件', 3549);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'besides', 'adv. 此外；而且 prep. 除…之外', 3550);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'beginning', 'n. 开始；起点 v. 开始；创建（begin的ing形式）', 3551);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rock', 'n. 岩石；摇滚乐；暗礁 v. 摇动；使摇晃', 3552);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'betray', 'v. 背叛；出卖；泄露（秘密）；露出…迹象', 3553);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'soil', 'n. 土地；土壤；国家；粪便；务农；温床 v. 弄脏；污辱', 3554);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sunset', 'n. 日落，傍晚', 3555);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'allow', 'v. 允许；给予；认可', 3556);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clerk', 'n. 职员，办事员；店员；书记；记账员；<古>牧师，教士 v. 当销售员，当店员；当职员', 3557);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chant', 'n. 圣歌；赞美诗 v. 唱；诵扬', 3558);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cloudy', 'adj. 多云的；阴天的；愁容满面的', 3559);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'here', 'adv. 在这里；此时 int. 嘿！；喂！ n. 这里', 3560);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'price', 'n. 价格；价值；代价 v. 给……定价；问……的价格', 3561);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bride', 'n. 新娘；姑娘，女朋友', 3562);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'challenge', 'n. 挑战；怀疑 v. 向…挑战；对…质疑', 3563);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'painful', 'adj. 痛苦的；疼痛的；令人不快的', 3564);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cushion', 'n. 垫子；起缓解作用之物；（猪等的）臀肉；银行储蓄 v. 给…安上垫子；把…安置在垫子上；缓和…的冲击', 3565);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'oilfield', 'n. 油田', 3566);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fit', 'v. 安装；使……适应；使……合身；与……相符 adj. 健康的；合适的；恰当的；准备好的 n. 合身；发作；痉挛', 3567);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'value', 'n. 值；价值；价格；重要性；确切涵义 v. 评价；重视；估价', 3568);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'scene', 'n. 场面；情景；景象；事件', 3569);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'freezing', 'adj. 冰冻的；严寒的；冷冻用的', 3570);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wild', 'adj. 野生的；野蛮的；狂热的；荒凉的 n. 荒野 adv. 疯狂地；胡乱地', 3571);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'scenery', 'n. 风景；景色；舞台布景', 3572);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sideway', 'n. 人行道；小巷 adv. 斜地里 adj. 旁边的；向侧面的（等于sideways）', 3573);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'squid', 'n. 鱿鱼；乌贼；枪乌贼', 3574);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'convenient', 'adj. 方便的；[废语]适当的；[口语]近便的；实用的', 3575);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dark', 'adj. 黑暗的，深色的；模糊的；无知的；忧郁的 n. 黑暗；夜；黄昏；模糊', 3576);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'zero', 'n. 零点，零度 num. 零', 3577);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'interesting', 'adj. 有趣的；引起兴趣的，令人关注的', 3578);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chips', 'n. [食品] 炸土豆条；小木片；（作赌注用的）圆形筹码；缺口（chip的复数形式）', 3579);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sugar', 'n. 糖；食糖；甜言蜜语 v. 加糖于；粉饰', 3580);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'silk', 'n. 丝绸；蚕丝；丝织物 adj. 丝的；丝绸的；丝制的 vi. （玉米）处于长须的阶段中', 3581);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'nod', 'n. 点头；打盹；摆动 v. 点头；点头表示', 3582);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'float', 'v. 使漂浮；实行 n. 彩车，花车；漂流物；浮舟；浮萍', 3583);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'believe', 'v. 信任；料想；笃信宗教', 3584);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Mom', 'n. 妈妈', 3585);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'June', 'n. 六月；琼（人名，来源于拉丁语，含义是“年轻气盛的六月”）', 3586);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'treatment', 'n. 治疗，疗法；处理；对待', 3587);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sight', 'n. 视力；景象；眼界；见解 v. 看见；瞄准 adj. 见票即付的；即席的', 3588);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'calm', 'adj. 静的，平静的；沉着的 v. 使平静；使镇定 n. 风平浪静', 3589);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plenty', 'n. 丰富，大量；充足 adj. 足够的，很多的 adv. 足够', 3590);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'missile', 'n. 导弹；投射物 adj. 导弹的；可投掷的；用以发射导弹的', 3591);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'environment', 'n. 环境，外界', 3592);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anyone', 'pron. 任何人；任何一个', 3593);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clearly', 'adv. 清晰地；明显地；无疑地；明净地', 3594);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'climate', 'n. 气候；风气；思潮；风土', 3595);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'behave', 'v. 表现；（机器等）运转；举止端正；（事物）起某种作用', 3596);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'delete', 'v. 删除', 3597);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'call', 'v. 呼叫；拜访；叫牌 n. 电话；呼叫；要求；访问', 3598);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'catastrophe', 'n. 大灾难；大祸；惨败', 3599);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'orbit', 'n. 轨道；眼眶；势力范围；生活常规 v. 盘旋；绕轨道运行', 3600);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'customs', 'n. 海关；风俗（custom的复数）；习惯；关税', 3601);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'snowy', 'adj. 下雪的，多雪的；被雪覆盖的；洁白无瑕的', 3602);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'waste', 'n. 浪费；废物；荒地；损耗；地面风化物 v. 浪费；消耗；使荒芜 adj. 废弃的；多余的；荒芜的', 3603);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'regard', 'n. 注意；尊重；问候；凝视 v. 注重，考虑；看待；尊敬；把…看作；与…有关', 3604);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'communism', 'n. 共产主义', 3605);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'less', 'adv. 较少地；较小地；更小地 adj. 较少的；较小的 prep. 减去 n. 较少；较小', 3606);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'French', 'adj. 法国的；法语的；法国人的 n. 法国人；法语', 3607);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reduce', 'v. 减少；降低；使处于；把…分解', 3608);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'identification', 'n. 鉴定，识别；认同；身份证明', 3609);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alphabet', 'n. 字母表，字母系统；入门，初步', 3610);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lawyer', 'n. 律师；法学家', 3611);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'moon', 'n. 月亮；月球；月光；卫星 v. 闲荡；出神', 3612);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'robot', 'n. 机器人；遥控设备，自动机械；机械般工作的人', 3613);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'nineteen', 'num. 十九', 3614);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sigh', 'v. 叹息，叹气 n. 叹息，叹气', 3615);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'food', 'n. 食物；养料', 3616);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'raise', 'v. 提高；筹集；养育；升起 n. 高地；上升；加薪', 3617);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'strengthen', 'v. 加强；巩固', 3618);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'league', 'n. 联盟；社团；范畴 v. 使…结盟；与…联合', 3619);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'scissors', 'n. 剪刀；剪式跳法 v. 剪开；删除（scissor的第三人称单数）', 3620);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sweat', 'v. 使出汗；流出；使干苦活；剥削；藉出汗减轻；焦急地期待 n. 汗；水珠；焦急；苦差使', 3621);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reflect', 'v. 反映；反射，照出；表达；显示;反省', 3622);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'deep', 'n. 深处；深渊 adj. 深的；低沉的；深奥的 adv. 深入地；深深地；迟', 3623);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tooth', 'n. 牙齿 vt. 给……装齿 vi. 啮合', 3624);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'orange', 'adj. 橙色的；橘色的 n. 橙；橙色；桔子', 3625);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prohibit', 'v. 阻止，禁止', 3626);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'finance', 'n. 财政，财政学；金融 v. 负担经费，供给…经费', 3627);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rule', 'v. 统治；管辖；裁定 n. 统治；规则', 3628);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tank', 'n. 坦克；水槽；池塘 v. 把…贮放在柜内；打败', 3629);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'worthy', 'adj. 值得的；有价值的；配得上的，相称的；可尊敬的；应…的 n. 杰出人物；知名人士', 3630);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'communicate', 'v. 通讯，传达；相通；交流；感染', 3631);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'population', 'n. 人口；[生物] 种群，[生物] 群体；全体居民', 3632);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'influence', 'n. 影响；势力；感化；有影响的人或事 v. 影响；改变', 3633);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Oceania', 'n. 大洋洲', 3634);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'noble', 'adj. 高尚的；贵族的；惰性的；宏伟的 n. 贵族 vt. 抓住；逮捕', 3635);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'knife', 'n. 刀；匕首 v. 用刀切；（口）伤害', 3636);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'grandson', 'n. 孙子；外孙', 3637);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'revolution', 'n. 革命；旋转；运行；循环', 3638);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clone', 'n. 克隆；无性系；无性繁殖；靠营养生殖而由母体分离繁殖的植物 v. 无性繁殖，复制', 3639);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'post', 'n. 岗位；邮件；标杆 v. 张贴；公布；邮递；布置', 3640);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bunch', 'n. 群；串；突出物 v. 隆起；打褶；形成一串', 3641);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'twenty', 'n. 二十；二十年代 num. 二十 adj. 二十的', 3642);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'troop', 'n. 军队；组；群；多数 v. 群集；成群而行；结队', 3643);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'kangaroo', 'n. 袋鼠', 3644);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dear', 'adj. 亲爱的；尊敬的；昂贵的 adv. 高价地；疼爱地 int. 哎呀 n. 亲爱的人', 3645);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'welfare', 'n. 福利；幸福；福利事业；安宁 adj. 福利的；接受社会救济的', 3646);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'roll', 'v. 卷；滚动，转动；辗 n. 卷，卷形物；名单；摇晃', 3647);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'explanation', 'n. 说明，解释；辩解', 3648);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'feel', 'v. 感觉；认为；触摸；试探 n. 感觉；触摸', 3649);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mad', 'adj. 疯狂的；发疯的；愚蠢的；着迷的 n. 狂怒', 3650);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'squirrel', 'n. 松鼠；松鼠毛皮 v. 贮藏', 3651);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'she', 'pron. 她（主格）；它（用来指雌性动物或国家、船舶、地球、月亮等） n. 女人；雌性动物', 3652);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'destination', 'n. 目的地，终点', 3653);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'differ', 'v. 使…相异；使…不同 n. (Differ)人名；(法)迪费', 3654);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pack', 'n. 包装；一群；背包；包裹；一副 v. 包装；压紧；捆扎；挑选；塞满', 3655);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'seaman', 'n. 海员，水手；水兵', 3656);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'terror', 'n. 恐怖；恐怖行动；恐怖时期；可怕的人', 3657);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'force', 'n. 力量；武力；军队；魄力 v. 促使，推动；强迫；强加', 3658);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'discussion', 'n. 讨论，议论', 3659);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'station', 'n. 车站；驻地；地位；身份 v. 配置；安置；驻扎', 3660);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'business', 'n. 商业；[贸易] 生意；[贸易] 交易；事情', 3661);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'granny', 'n. 奶奶；外婆；婆婆妈妈的人', 3662);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Arabic', 'adj. 阿拉伯的；阿拉伯人的 n. 阿拉伯语', 3663);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bone', 'n. 骨；骨骼 v. 剔去的骨；施骨肥于', 3664);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'OK', 'adj. 好的；不错的 adv. 行；很好 int. 好；可以 v. 对…表示同意 n. 同意', 3665);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bishop', 'n. （基督教的）主教；（国际象棋的）象', 3666);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'refusal', 'n. 拒绝；优先取舍权；推却；取舍权', 3667);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'eager', 'adj. 渴望的；热切的；热心的 n. (Eager)人名；(英)伊格', 3668);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cancel', 'vt.  取消', 3669);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prepare', 'v.  准备； 配制', 3670);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'govern', 'v.  统治； 管理', 3671);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'surgeon', 'n.  外科医生', 3672);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'analyse', 'vt.  分析； 研究', 3673);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'abrupt', 'adj.  突然的， 意外的', 3674);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'resemble', 'vt.  像， 类似', 3675);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'discourage', 'vt.  使气馁， 打消', 3676);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hall', 'n.  大厅， 礼堂； 门厅， 过道', 3677);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pollution', 'n.  污染', 3678);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'remote', 'adj.  遥远的', 3679);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'explanation', 'n.  解释， 说明', 3680);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cafeteria', 'n.  自助餐厅', 3681);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'salary', 'n.  工资， 薪水', 3682);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pretend', 'v.  假装， 装作', 3683);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'youth', 'n.  青春； 青年', 3684);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'without', 'prep.  没有， 不', 3685);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'drunk', 'adj.  醉的', 3686);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'would', 'modal verb. 将，将会〔表示想做某事或认为某事会发生〕', 3687);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pick', 'v.  拾起， 采集； 挑选', 3688);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'customs', 'n.  海关； 关税', 3689);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'calculate', 'v.  计算， 核算', 3690);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'energy', 'n.  精力； 能量', 3691);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'audience', 'n.  观众， 听众', 3692);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'solid', 'adj. 结实的，固体的 n.  固体', 3693);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'thus', 'adv.  这样； 因而', 3694);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'meanwhile', 'adv.  同时', 3695);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sniff', 'v.  用力吸； 嗅， 闻', 3696);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'possess', 'vt.  占有， 拥有', 3697);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'require', 'vt.  需求； 要求', 3698);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'optional', 'adj.  可选择的； 随意的', 3699);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'scratch', 'v. 抓，划破；乱涂 n.  乱写； 抓痕', 3700);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'analysis', 'n.  分析； 解析', 3701);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'click', 'v. 点击；发出滴答声 n.  滴答声', 3702);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'apparent', 'adj.  明显的， 清楚的', 3703);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'journalist', 'n.  记者， 新闻工作者', 3704);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'left', 'adv. 向左边，在左边 adj. 左边的 n.  左， 左边', 3705);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dawn', 'n.  黎明， 拂晓', 3706);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sideways', 'adj.  斜向一边的', 3707);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'object', 'v.  反对 n.  物体； 目标； 宾语', 3708);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harbour', 'n.  港口', 3709);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chapter', 'n.  章', 3710);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accessible', 'adj.  可使用的； 可进入的； 易接近的', 3711);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flight', 'n.  飞行； 航班； 楼梯的一段', 3712);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hang', 'v.   悬挂； 装饰； 绞死', 3713);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'role', 'n.  [Ｃ] 角色； 作用', 3714);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'independent', 'adj.  独立的， 有主见的', 3715);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'carriage', 'n.  四轮马车；  客车厢', 3716);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'defence', 'n.  防御； 防护； 辩护', 3717);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'achieve', 'vt.  达到， 取得', 3718);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ahead', 'adv.  在前， 向前', 3719);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anybody', 'pron.  任何人， 无论谁', 3720);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'roll', 'v. 滚动,打滚 n.  面包圈； 卷状物', 3721);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'turn', 'v. 旋转；转变；转弯 n.  轮流', 3722);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'elect', 'vt.   选举', 3723);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'example', 'n.  例子， 范例', 3724);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'result', 'n.  结果， 效果', 3725);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'same', 'adj.  同样的， 同一的 n. 同样的事', 3726);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'selfish', 'adj.  自私的', 3727);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'after', 'prep&conj&adv.  在…之后， 后来', 3728);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'headline', 'n. 标题；', 3729);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'connect', 'vt.  连接， 把…联系起来', 3730);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hand', 'n. 手；指针 vt.  交付； 传递', 3731);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'merciful', 'adj.  仁慈的； 宽大的', 3732);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'rebuild', 'vt.  重建', 3733);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sharpen', 'v.   变锐利， 削尖', 3734);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'committee', 'n.  委员会', 3735);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'address', 'n.  地址', 3736);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'union', 'n.  联合， 联盟', 3737);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'straight', 'adj&adv.  直的', 3738);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wipe', 'vt.  擦； 扫', 3739);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sale', 'n.  卖， 出售', 3740);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'component', 'n.  成分； 零部件', 3741);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'suite', 'n.  套， 组； 套间', 3742);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consultant', 'n.  顾问； 会诊医师', 3743);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'outdoors', 'adv. 户外的，野外的 n.  户外', 3744);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'throw', 'v.   投， 掷， 扔', 3745);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'obvious', 'adj.  明显的， 显而易见的', 3746);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'arch', 'n.  拱门； 拱形', 3747);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'discuss', 'v.  讨论， 议论', 3748);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'standard', 'adj.  标准的 n. 标准，规格', 3749);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'violent', 'adj.  暴力的； 猛烈的', 3750);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harmony', 'n.  协调， 融洽', 3751);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'correct', 'adj.  正确的， 对的； 恰当的 vt. 改正；纠正', 3752);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'empty', 'adj.  空的 vt. 倒空', 3753);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wish', 'n&v.  祝愿； 想要', 3754);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'institution', 'n.  公共机构； 协会', 3755);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tie', 'v. 系，拴，扎 n.  关系； 领带； 绳子， 结', 3756);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wise', 'adj.  聪明的， 明智的', 3757);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ambition', 'n.  雄心， 野心', 3758);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tin', 'n.  罐头', 3759);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'enlarge', 'v.  扩大， 放大', 3760);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'besides', 'adv.  此外； 再说 prep. 除…以外', 3761);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'serious', 'adj.  严肃的， 严重的； 认真的', 3762);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tip', 'vt. 告诫，提示；给小费 n.  顶端； 小费； 提示', 3763);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'export', 'vi.  出口 vt. 输出 n.  出口', 3764);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'conversation', 'n.  谈话， 交谈', 3765);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'laugh', 'vi.  笑， 大笑 n. 笑，大笑，笑声；嘲笑', 3766);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'murder', 'n&v.  谋杀', 3767);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fantasy', 'n.  幻想， 白日梦', 3768);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pay', 'v. 付钱，给…报酬 n.  工资', 3769);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'check', 'v. 核对；检查；批改 n.  检查； 批改', 3770);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'list', 'n. 一览表，清单 vt.  列表', 3771);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'strange', 'adj.  奇怪的， 奇特的； 陌生的', 3772);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lack', 'n&v.  缺乏， 缺少', 3773);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'toast', 'vt. 向…敬酒；烘，烤 n.  烤面包， 吐司； 祝酒， 祝酒词', 3774);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aside', 'adv.  在旁边', 3775);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circumstance', 'n.  环境； 情况', 3776);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'success', 'n.  成功， 成就； 成功的人', 3777);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'brunch', 'n.  早午饭', 3778);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'authority', 'n.  权威； 当局', 3779);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'creature', 'n.  生物； 动物', 3780);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'outgoing', 'adj.  好交际的， 外向的； 即将离职的', 3781);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tasteless', 'adj.  无滋味的', 3782);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harm', 'n&vt.  伤害， 损伤', 3783);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'instrument', 'n.  乐器； 工具， 器械', 3784);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'medium', 'adj. 中间的，中等的 n.   媒介', 3785);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'remove', 'vt.  移动， 拿走； 去除', 3786);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wisdom', 'n.  智慧', 3787);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'starvation', 'n.  饥饿； 饿死', 3788);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'nowhere', 'adv.  任何地方都不； 无处', 3789);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'psychology', 'n.  心理学', 3790);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wrestle', 'v.  摔跤， 格斗； 斟酌', 3791);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'treasure', 'n.  金银财宝， 财富', 3792);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'multiply', 'v.    相乘； 增加', 3793);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'live', 'vi. 生活，居住 adj.  活的； 直播的 vt. 过着，经历', 3794);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'approval', 'n.  赞成； 认可； 批准', 3795);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'victory', 'n.  [C] 胜利', 3796);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mobile', 'adj.  活动的， 可移动的', 3797);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'perform', 'v.  表演， 表现； 履行', 3798);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'evolution', 'n.  进展， 演变， 进化', 3799);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'expose', 'vt.  暴露； 揭露', 3800);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'concentrate', 'v.  集中， 聚集', 3801);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cheer', 'n&v.  欢呼， 喝彩', 3802);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'with', 'prep.  与， 伴随； 有， 以', 3803);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'there', 'adv.  在那里 int. 那！你瞧！', 3804);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'permit', 'v. 许可，允许 n.  许可证， 执照', 3805);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'well', 'adv. 好，充分地 adj. 健康的 int. 好吧 n.  井', 3806);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'suitable', 'adj.  合适的， 适宜的', 3807);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'personnel', 'n.  人员， 职员', 3808);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hopeless', 'adj.  没有希望的； 不可救药的', 3809);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'freeway', 'n.  高速公路', 3810);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fountain', 'n.  喷泉； 源泉', 3811);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pile', 'v. 堆积，积累 n.  堆', 3812);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'channel', 'n.  海峡； 频道； 通道', 3813);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'sunburnt', 'adj.  晒黑的， 晒伤的', 3814);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'focus', 'v. 聚焦，集中 n.  中心， 焦点', 3815);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'entire', 'adj.  整个的， 全部的', 3816);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'approach', 'v.  接近， 靠近 n. 方式，方法', 3817);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wrist', 'n.  手腕， 腕关节', 3818);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'experiment', 'n.  实验', 3819);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fierce', 'adj.  猛烈的， 激烈的', 3820);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reservation', 'n.   预订； 预约', 3821);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'e-mail', 'n. 电子邮件 vt.  给…发电子邮件', 3822);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hate', 'vt. 恨，讨厌，不喜欢 n.  怨恨', 3823);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'block', 'v.  阻塞， 阻挡 n. 大块；街区', 3824);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'write', 'v.   写', 3825);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pet', 'n.  宠物， 爱畜', 3826);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'flow', 'v. 流动 n.  流， 流动', 3827);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'order', 'n. 顺序；命令 vt.  命令； 点菜； 订货', 3828);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wage', 'n.  工资， 报酬', 3829);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'period', 'n.  时期， 时代', 3830);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'musical', 'adj. 音乐的，爱好音乐的 n.  音乐剧', 3831);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'corporation', 'n.  团体； 公司， 企业', 3832);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'distant', 'adj.  远的， 遥远的', 3833);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'understand', 'v.   懂得， 理解', 3834);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dismiss', 'v.  解雇； 解散', 3835);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'intelligence', 'n.  智力， 聪明', 3836);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'reform', 'v.  改革， 革新 n. 改革；改善', 3837);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ever', 'adv.  曾经； 无论何时', 3838);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'even', 'adv. 甚至，更加，还要 adj.  平坦的', 3839);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'restriction', 'n.  限制', 3840);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'crazy', 'adj.  疯狂的', 3841);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'razor', 'n.  剃须刀', 3842);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coach', 'v. 指导，训练 n.  教练； 马车； 长途车', 3843);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'champion', 'n.  冠军， 优胜者', 3844);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wait', 'v. 等待 n.  等待， 等候', 3845);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circuit', 'n.  电路', 3846);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pint', 'n.   品脱； 一品脱啤酒', 3847);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'matter', 'vi.  要紧， 有重大关系 n. 事情，物质；原因', 3848);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'instant', 'adj. 立即的；速食的 n.  瞬间', 3849);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'personalization', 'n.  个性化', 3850);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'shaver', 'n.  电动剃须刀', 3851);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'top', 'n.  顶部； 上面', 3852);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'native', 'adj.  本土的， 本国的', 3853);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'too', 'adv.  也； 又； 太； 很', 3854);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'have', 'v.  帮助构成完成时态 vt. 有，使，令', 3855);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'violence', 'n.  暴力； 强烈', 3856);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'roast', 'v.  烤', 3857);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'energetic', 'adj.  精力旺盛的', 3858);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'consequence', 'n.  结果， 后果', 3859);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'quilt', 'n.  加衬芯床罩', 3860);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'famous', 'adj.  著名的， 出名的', 3861);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'question', 'vt. 询问 n.  问题', 3862);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'vinegar', 'n.  醋', 3863);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spirit', 'n.  精神， 灵魂', 3864);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'premier', 'n.  总理， 首相', 3865);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'produce', 'v.  生产， 制造', 3866);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'allergic', 'adj.  过敏的', 3867);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cheat', 'v. 哄骗，欺骗，骗取 n.  骗子； 诈骗', 3868);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'framework', 'n.  框架， 结构', 3869);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'regard', 'v. 当做，看待 n.  关心， 注意； 致意', 3870);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anecdote', 'n.  轶事； 趣事', 3871);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prohibit', 'vt.  禁止， 阻止', 3872);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'almost', 'adv.  几乎， 差不多', 3873);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'steward', 'n.  男乘务员', 3874);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fuel', 'n.  燃料', 3875);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'manner', 'n. 方式；举止；', 3876);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'upon', 'prep.  在…上面', 3877);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'foresee', 'vt.   预见， 预知', 3878);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'harmful', 'adj.  有害的； 致伤的', 3879);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'associate', 'v.  结合； 结交', 3880);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pray', 'v.  祈祷， 祈求', 3881);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wake', 'v.   醒来， 叫醒', 3882);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pin', 'vt. 钉住，别住 n.  别针； 胸针', 3883);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'academic', 'adj. 学术的；院校的 n.  大学教师； 学者', 3884);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'whether', 'conj.  是否', 3885);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'function', 'vi.  起作用； 行使职责 n. 功能，作用，职责；函数', 3886);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'raise', 'vt.  举起； 提高， 使升高； 饲养， 养育', 3887);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spoon', 'n.  勺， 匙， 调羹', 3888);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'quite', 'adv.  完全， 十分', 3889);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lap', 'n.  大腿；  一圈', 3890);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'mineral', 'n.  矿物质， 矿物', 3891);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'representative', 'n.  代表', 3892);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'terror', 'n.  恐怖； 可怕的人', 3893);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'beneath', 'prep.  在…下方， 在…下面', 3894);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'everyone', 'pron.  每人， 人人', 3895);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lay', 'v.   放， 搁； 产', 3896);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'swap', 'v.   交换', 3897);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'hatch', 'v.   孵蛋', 3898);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pardon', 'vt&n.  原谅， 宽恕； 对不起', 3899);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'plenty', 'n.  充足， 大量， 丰富', 3900);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'tick', 'v.  发出滴答声 n. 钟表的滴答声；记号', 3901);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'basis', 'n.  [C] 基础； 根据； 原则', 3902);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'adventure', 'n.  冒险； 奇遇', 3903);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'condition', 'n.  条件， 状况', 3904);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'improve', 'v.  改进， 更新', 3905);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ceremony', 'n.  典礼， 仪式', 3906);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bingo', 'n.  宾果', 3907);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'try', 'v.   尝试， 试图； 努力', 3908);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'gym', 'n.  体育馆； 健身房', 3909);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'basic', 'adj. 基本的 n.  要素； 基础', 3910);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'twist', 'v. 拧，扭曲 n.  扭曲， 歪曲', 3911);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'unite', 'v.  联合， 团结', 3912);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bush', 'n.  灌木丛， 矮树丛', 3913);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'technique', 'n.  技术， 技巧', 3914);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cause', 'n. 原因，起因 vt.  促使， 引起', 3915);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'dioxide', 'n.  二氧化物', 3916);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'wound', 'vt. 伤，使受伤；伤害 n.  [Ｃ] 创伤； 伤口', 3917);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'catastrophe', 'n.  灾难； 灾祸； 横祸', 3918);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'busy', 'adj.  忙碌的', 3919);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'convey', 'vt.  搬运； 传播， 传达', 3920);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'extra', 'adj.  额外的， 外加的', 3921);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'design', 'v. 设计；制订；筹划 n.  样式', 3922);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'generous', 'adj.  慷慨的， 大方的', 3923);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'land', 'v.  登陆； 降落 n. 陆地', 3924);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'coincidence', 'n.  一致； 巧合', 3925);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'victim', 'n.  受害人， 牺牲品', 3926);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'department', 'n.  部门；  系', 3927);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'possibility', 'n.  可能， 可能性', 3928);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'direction', 'n.  方向； 说明； 说明书； 指导', 3929);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'exhibition', 'n.  展览， 展览会； 展品', 3930);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'burn', 'v. 燃，烧，着火；使烧焦；', 3931);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'garlic', 'n.  大蒜', 3932);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'alcoholic', 'adj. 酒精的；酒精中毒的 n.  饮酒过度的人', 3933);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bachelor', 'n.  学士； 单身汉', 3934);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'countryside', 'n.  乡下， 农村', 3935);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chief', 'adj. 主要的，首要的 n.  领导', 3936);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'automatic', 'adj.  自动的， 机械的', 3937);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lamp', 'n.  灯， 油灯； 光源', 3938);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cry', 'v.  喊叫； 哭 n. 喊；哭声', 3939);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'Antarctic', 'adj. 南极的 n.  南极地区', 3940);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'conduct', 'vt.  引导； 管理', 3941);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bury', 'vt.   埋， 葬', 3942);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'obey', 'v.  服从， 顺从', 3943);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'stable', 'adj.  稳定的', 3944);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lamb', 'n.  羔羊； 羔羊肉', 3945);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'fantastic', 'adj.  极好的， 美妙的， 很棒的', 3946);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'changeable', 'adj.  易变的， 变化无常的', 3947);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'spoken', 'adj.  口语的', 3948);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'respond', 'v.  回答； 做出反应', 3949);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'incident', 'n.  事件', 3950);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'walk', 'v.  走路， 步行 n. 散步', 3951);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'lame', 'adj.  跛的； 残废的', 3952);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'marry', 'v.   和…结婚', 3953);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pity', 'n.  怜悯， 同情； 憾事', 3954);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'absorb', 'vt.  吸收； 吸引', 3955);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'supply', 'v.  供给， 提供 n. 供给；供应品', 3956);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'uncertain', 'adj.  不确定的', 3957);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'concern', 'n. 关系；关心 vt.  涉及， 关系到', 3958);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circulate', 'vt.  使流通； 使运行', 3959);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'liberty', 'n.  自由', 3960);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'recycle', 'v.  再循环， 回收', 3961);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'let', 'vt.   让', 3962);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'state', 'n. 状态；国家；州 vt.  宣称', 3963);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'press', 'vt. 压，按 n.  压， 按； 新闻界， 出版社', 3964);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'welcome', 'n&vt&adj.  欢迎', 3965);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'confidential', 'adj.  极受信任的； 秘密的', 3966);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'chaos', 'n.  混乱', 3967);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'abundant', 'adj.  丰富的， 充裕的', 3968);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'want', 'v.  想要， 需要', 3969);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pace', 'n.  步子， 步速； 节奏', 3970);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ballet', 'n.  芭蕾舞， 芭蕾舞剧', 3971);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'opposite', 'adj.  相反的， 对面的 n. 相反，对面；对立面，对立物', 3972);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'forecast', 'n. 预知 vt.  预告， 预测', 3973);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'recognize', 'vt.  认出； 承认', 3974);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'warehouse', 'n.  仓库； 大商店', 3975);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'pack', 'v.  包装， 整理 n. 包，背包；一群', 3976);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'each', 'adj&pron.  每人， 每个， 每件', 3977);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'abnormal', 'adj.  反常的； 变态的', 3978);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'difference', 'n.  不同', 3979);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'must', 'modal verb. 必须 n. 必须做的事；必不可少的东西', 3980);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'circle', 'v.  围起来， 环绕 n. 圆圈', 3981);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'resign', 'v.  辞去， 辞职', 3982);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'drier', 'n.  烘干机， 吹风机', 3983);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'bathe', 'v.  洗澡， 沐浴， 浸洗', 3984);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'polite', 'adj.  有礼貌的， 有教养的', 3985);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'cut', 'v. 切，剪，削，割；删节 n.  伤口', 3986);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'entertainment', 'n.  娱乐； 娱乐表演', 3987);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'probably', 'adv.  很可能， 大概', 3988);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'document', 'n.  文件， 文献', 3989);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'aluminum', 'n.  铝', 3990);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'ward', 'vt. 保卫，看护 n.  病房， 收容所', 3991);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'starve', 'v.  饿死， 挨饿', 3992);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'prize', 'n.  奖赏， 奖品， 奖金', 3993);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'accident', 'n.  事故， 意外事件', 3994);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'clay', 'n.  黏土； 泥土', 3995);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'moment', 'n.  [C] 片刻， 瞬间， 刹那', 3996);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'anyway', 'adv.  不管怎样', 3997);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'promote', 'vt.  促进； 提升； 推销', 3998);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'routine', 'n.  常规， 日常事务', 3999);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (6, 'found', 'vt.  成立， 建立', 4000);
