INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tenement', 'n. 公寓', 4001);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'daguerreotype', 'n. (早期)银板照相', 4002);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'staple', 'v. 订 a主要的', 4003);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fatty', 'adj. 脂肪的', 4004);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mainland', 'n. 大陆', 4005);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disrupt', 'v. 使中断，扰乱', 4006);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rend', 'v. 撕裂，猛拉', 4007);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maser', 'n. 微波激射器', 4008);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spinal', 'adj. 脊椎骨 n. 脊髓麻醉', 4009);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clockwise', 'adv. ／ a顺时针方向地(的)', 4010);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generic', 'adj. 种类的，类属的', 4011);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resin', 'n. 树脂 vt涂树脂于', 4012);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'backward', 'a&ad. 向后的, 落后的', 4013);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'carving', 'n. 雕刻(品)', 4014);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frown', 'v. ／ n皱眉，蹙额', 4015);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feasible', 'adj. 可行的', 4016);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'distrust', 'n&vt. 不信任，怀疑', 4017);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'incredible', 'adj. 不可信的；不可思议的', 4018);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'smother', 'v. 窒息', 4019);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stain', 'n. 污点v染污', 4020);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cavern', 'n. 洞穴，大山洞', 4021);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'minuscule', 'n&a. 草写小字(的)', 4022);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'envelop', 'v. 包封, 遮盖', 4023);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fortunately', 'adv. 幸运地，幸亏', 4024);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dormant', 'adj. 冬眠的', 4025);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coppersmith', 'n. 铜匠', 4026);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intrinsic', 'adj. 内在的, 固有的', 4027);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'portability', 'n. 可携带, 轻便', 4028);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pest', 'n. 害虫', 4029);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potato', 'n. 马铃薯', 4030);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clarify', 'v. 澄清, 阐明', 4031);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extermination', 'n. 消灭, 根绝', 4032);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suburbanization', 'n. 市郊化', 4033);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'succulent', 'adj. 多汁的', 4034);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'medal', 'n. 奖牌，奖章', 4035);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'micron', 'n. 微米,百万分之一米', 4036);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'publicize', 'v. 宣传', 4037);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spout', 'v. 喷出', 4038);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catastrophic', 'adj. 悲惨的, 灾难的', 4039);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sensory', 'adj. 知觉的, 感觉的', 4040);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fodder', 'n. 饲料, 草料', 4041);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'photoflash', 'n. （照相）闪光灯', 4042);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'substantiated', 'vt. 证实, 实体化', 4043);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cramp', 'n. 痉挛 v. 限制，束缚', 4044);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reversal', 'n. 翻转, 倒转, 反转', 4045);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'psychologically', 'adv. 精神上地, 心理上地', 4046);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'virtuosity', 'n. 艺术鉴别力', 4047);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leafy', 'adj. 叶状的；叶茂的', 4048);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perishable', 'adj. 容易腐烂的', 4049);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retract', 'v. 缩回, 撤销', 4050);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Israel', 'n. [地名] 以色列', 4051);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'retrieval', 'n. 取回，补偿', 4052);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'insist', 'v. 坚持, 强调', 4053);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inject', 'v. 注射, 注入', 4054);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'domelike', 'adj. 穹顶状的', 4055);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'savannah', 'n. (南美)大草原', 4056);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snake', 'n. 蛇', 4057);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pour', 'v. 灌,注,倾泻', 4058);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'navigator', 'n. 航海家', 4059);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vacuum', 'n. 真空', 4060);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elliot', 'n. 埃利奥特(男子名)', 4061);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'perry', 'n. 梨子酒', 4062);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'liter', 'n. 公升', 4063);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arthropod', 'n&a. 节肢动物(的)', 4064);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'airflow', 'n. 气流', 4065);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'departure', 'n. 启程, 出发', 4066);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'momentum', 'n. 动力, 势头', 4067);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spearhead', 'v. 充当先锋', 4068);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unjust', 'adj. 不公平的', 4069);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'industrialism', 'n. 产业主义,工业制度', 4070);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'drug', 'n. 药', 4071);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'environmentally', 'adv. 在环境方面地', 4072);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gem', 'n. 宝石, 珍宝', 4073);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'detract', 'v. 转移', 4074);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'swirl', 'n&v. 旋转，漩涡', 4075);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bluefin', 'n. 金枪鱼', 4076);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'radiant', 'adj. 发光的, 辐射的', 4077);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'potent', 'adj. 强有力的,有效的', 4078);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sociobiology', 'n. 生物社会学', 4079);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ideological', 'adj. 意识形态的', 4080);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'solidarity', 'n. 团结', 4081);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'providence', 'n. 深谋远虑，远见', 4082);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'catharsis', 'n. 宣泄，净化', 4083);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contradictory', 'adj. 相矛盾的', 4084);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chloride', 'n. [化]氯化物', 4085);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'archaic', 'adj. 古代的, 陈旧的', 4086);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aristocrat', 'n. 贵族', 4087);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'consolidate', 'v. 合并,统一,巩固', 4088);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spark', 'n. 火花 v. 触发，引起', 4089);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plug', 'v. 塞 n插头', 4090);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spine', 'n. 脊柱', 4091);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absolute', 'adj. 完全的, 绝对的', 4092);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lade', 'v. 装载,装货', 4093);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Soviet', 'n&a. 苏维埃(的)', 4094);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanity', 'n. 人性', 4095);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'budget', 'n. 预算 v做预算', 4096);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'magnesium', 'n. [化]镁', 4097);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'engulf', 'v. 吞没', 4098);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frigid', 'adj. 寒冷的', 4099);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grandiose', 'adj. 宏伟的,堂皇的', 4100);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'citizenship', 'n. 公民的身份', 4101);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'despondent', 'adj. 失望的, 沮丧的', 4102);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'identifiable', 'adj. 可辨认的', 4103);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cellular', 'adj. 细胞组成的，多孔的', 4104);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'universality', 'n. 普遍性, 一般性', 4105);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'widen', 'v. 加宽,扩展', 4106);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Impressionism', 'n. 印象派, 印象主义', 4107);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'steer', 'v. 操纵, 驾驶', 4108);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'moderately', 'adv. 适度地', 4109);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'writing', 'n. 笔迹, 作品', 4110);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'symbolism', 'n. 象征主义', 4111);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acute', 'adj. 敏锐的, 急性的', 4112);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'romance', 'n. 恋爱关系；浪漫气氛', 4113);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bowl', 'n. 碗', 4114);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unreliable', 'adj. 不可靠的', 4115);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unfortunate', 'adj. 不幸的', 4116);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'weekly', 'adj. 每周的 ad一周一次地 n周报', 4117);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compensation', 'n. 补偿, 赔偿', 4118);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vine', 'n. 葡萄树；藤本植物', 4119);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hardness', 'n. 硬度', 4120);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aerodynamic', 'adj. 空气动力学的', 4121);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'command', 'n&v. 命令；指挥', 4122);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arbitrary', 'adj. 任意的, 武断的', 4123);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pianist', 'n. 钢琴家', 4124);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'slender', 'adj. 苗条的, 微薄的', 4125);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'admit', 'v. 承认,准许', 4126);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alp', 'n. 高山', 4127);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'commonplace', 'n. 寻常的事物', 4128);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vase', 'n. (花)瓶', 4129);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deliberately', 'adv. 故意地', 4130);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recommend', 'v. 推荐,劝告', 4131);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dual', 'adj. 双的, 二重的', 4132);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mouse', 'n. 鼠', 4133);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'craftsmanship', 'n. 技术', 4134);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beast', 'n. 野兽，牲畜', 4135);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'affinity', 'n. 密切关系,类同', 4136);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'diagonal', 'n&a. 对角线(的)', 4137);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'exhaust', 'v. 使筋疲力尽,耗尽', 4138);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'resemblance', 'n. 相似，形似', 4139);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nontraditional', 'adj. 非传统的', 4140);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disprove', 'v. 反驳,证明为误', 4141);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skeptical', 'adj. 怀疑的', 4142);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shirt', 'n. 衬衫', 4143);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plenty', 'n. 丰富, 大量', 4144);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'appropriately', 'adv. 适当地', 4145);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'emotionally', 'adv. 感情上地, 冲动地', 4146);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freshly', 'adv. 新近，刚才', 4147);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unbelievable', 'adj. 难以置信的', 4148);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'simultaneous', 'adj. 同时发生的,同步的', 4149);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'induce', 'v. 促使,引诱', 4150);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'woodworker', 'n. 木工', 4151);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conversation', 'n. 会话', 4152);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'translate', 'v. 翻译', 4153);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'transaction', 'n. 交易，业务', 4154);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eager', 'adj. 热心于, 渴望着', 4155);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'skillful', 'adj. 熟练的, 灵巧的', 4156);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fate', 'n. 天数,命运', 4157);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'possession', 'n. 财产, 所有', 4158);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invariably', 'adv. 不变地，始终如一地', 4159);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Babylonian', 'n. 巴比伦人(的), 巴比伦语（的）', 4160);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'urbanization', 'n. 都市化', 4161);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tram', 'n. 有轨电车', 4162);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sulfur', 'n. [化] 硫磺', 4163);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stripe', 'n. 条纹', 4164);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ought', 'aux. 应当, 应该', 4165);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'volatile', 'adj. 动荡不定的,反复无常的', 4166);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'densely', 'adv. 浓密地', 4167);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biography', 'n. 传记', 4168);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inscribe', 'v. 题写', 4169);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'intercity', 'adj. 城市间的', 4170);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alongside', 'prep&ad. 在旁边', 4171);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'erratic', 'adj. 古怪的，飘忽不定的', 4172);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overly', 'adv. 过度地, 极度地', 4173);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'uplift', 'v. 提高；振奋(精神)', 4174);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'workday', 'n. 工作日', 4175);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'golden', 'adj. 金(黄)色的；金的', 4176);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'officially', 'adv. 职务上, 正式', 4177);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sacrifice', 'n& vt. 牺牲，献祭', 4178);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'trick', 'n. 诡计 v. 欺诈', 4179);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'melody', 'n. 旋律，曲调', 4180);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'array', 'n&v. 展示,排列', 4181);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thunderstorm', 'n. 雷暴雨', 4182);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'frog', 'n. 青蛙', 4183);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deception', 'n. 欺骗, 诡计', 4184);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'snap', 'v. 喀嚓折断,拍快照 n吧嗒声', 4185);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'typify', 'v. 代表', 4186);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gently', 'adv. 轻轻地, 温柔地', 4187);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'astronomical', 'adj. 天文学的, 巨大的', 4188);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quantify', 'v. 用数量表示,量化', 4189);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'startle', 'v. 震惊', 4190);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'peregrine', 'n. 游隼 a外来的,移住的', 4191);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'optimal', 'adj. 最理想的', 4192);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tapestry', 'n. 挂毯', 4193);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'polish', 'v. 磨光，擦亮', 4194);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capability', 'n. 能力，才能', 4195);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mechanization', 'n. 机械化', 4196);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'influx', 'n. 流入', 4197);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sculptural', 'adj. 雕刻的', 4198);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calm', 'adj. 镇定的,平静的 v(使)平静', 4199);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'announce', 'v. 宣布,宣告', 4200);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'leisure', 'n. 闲暇, 休闲', 4201);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'essence', 'n. 本质，实质', 4202);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'landmass', 'n. 大陆', 4203);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shrimp', 'n. 小虾 v捕虾', 4204);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ornamentation', 'n. 装饰', 4205);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'freely', 'adv. 自由地；慷慨地', 4206);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'undesirable', 'adj. 令人不悦的，讨厌的', 4207);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'globe', 'n. 球体,地球仪', 4208);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'grasshopper', 'n. 蚱蜢，蝗虫', 4209);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'elegant', 'adj. 优雅的, 雅致的', 4210);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shiny', 'adj. 发光的；磨光的', 4211);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glassmaker', 'n. 玻璃工人', 4212);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spectacularly', 'adv. 壮观地, 令人吃惊地', 4213);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nss', 'n. 卫星导航系统(供氮系统)', 4214);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submerge', 'v. 浸没，淹没', 4215);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'terminology', 'n. 术语(学)', 4216);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unclear', 'adj. 不清楚的', 4217);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unimportant', 'adj. 不重要的', 4218);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ubiquitous', 'adj. 到处存在的', 4219);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demise', 'n. 死亡,让位', 4220);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'conspicuous', 'adj. 显著的, 显眼的', 4221);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'error', 'n. 错误, 过失', 4222);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deadly', 'adj. 致命的', 4223);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barter', 'v. 交易', 4224);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nomadic', 'adj. 游牧的, 流浪的', 4225);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'merge', 'v. 结合,合并', 4226);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seashore', 'n. 海岸, 海滨', 4227);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nonhuman', 'adj. 非人类的', 4228);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cottage', 'n. 村舍,小别墅', 4229);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fairground', 'n. 游乐场, 集市', 4230);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lengthen', 'v. 变长,延伸', 4231);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'candle', 'n. 蜡烛', 4232);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kilogram', 'n. [物]千克, 公斤', 4233);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'naturalism', 'n. 自然主义', 4234);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'input', 'n. 输入，投入', 4235);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'delight', 'n&v. 高兴,欣喜', 4236);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'telegraph', 'n&v. (打)电报', 4237);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stance', 'n. 站姿，立场', 4238);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kitchen', 'n. 厨房', 4239);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tour', 'n&v. 旅行，游历', 4240);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maple', 'n. 枫树', 4241);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'contraction', 'n. 收缩', 4242);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hinge', 'n. （门、盖等的）铰链', 4243);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biotic', 'adj. 有关生命的,生物的', 4244);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'maturity', 'n. 成熟,(票据)到期', 4245);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'honest', 'adj. 诚实的, 正直的', 4246);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firewood', 'n. 木柴, 柴火', 4247);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'barn', 'n. [农]谷仓, 畜棚, 畜舍, 机器房', 4248);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'joke', 'n. 笑话, 玩笑', 4249);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'granular', 'adj. 由小粒而成的,粒状的', 4250);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'preindustrial', 'adj. 未工业化的, 工业化前的', 4251);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'thaw', 'n. 融化,解冻', 4252);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quarry', 'n. 采石场 v. 挖出', 4253);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ethology', 'n. 动物行动学, 人种学', 4254);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amendment', 'n. 改善, 改正', 4255);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curious', 'adj. 好奇的, 奇特的', 4256);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'faith', 'n. 信仰, 信念', 4257);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'overtake', 'v. 追上，超过', 4258);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'neck', 'n. 脖子, 颈', 4259);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impurity', 'n. 不纯；杂质', 4260);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formidable', 'adj. 可怕的；难以克服的', 4261);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'acceptable', 'adj. 可接受的, 合意的', 4262);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'forager', 'n. 强征(粮食)者', 4263);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'impend', 'v. 迫近，逼近', 4264);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'glasslike', 'adj. 玻璃状的', 4265);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'translucent', 'adj. 半透明的', 4266);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'topsoil', 'n. 表层土', 4267);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'interrelationship', 'n. 相互关系', 4268);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blade', 'n. 刀刃, 刀片', 4269);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pocket', 'n. 衣袋，小袋', 4270);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hillside', 'n. 山腰', 4271);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'beside', 'prep. 在…旁边,和…相比', 4272);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'subscribe', 'v. 订阅, 签名,捐赠', 4273);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'buffer', 'n. 缓冲器', 4274);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'embody', 'v. 使具体化', 4275);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'happy', 'adj. 快乐的，幸福的', 4276);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'net', 'n. 网, 网络', 4277);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'litter', 'n. 垃圾 v乱扔东西', 4278);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'outsider', 'n. 外行, 局外人', 4279);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aragonite', 'n. [矿]霰石, 文石', 4280);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'convenience', 'n. 便利,适宜', 4281);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'promotion', 'n. 提升；促进', 4282);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unaltered', 'adj. 未被改变的', 4283);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bath', 'n. 沐浴, 浴室', 4284);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'directional', 'adj. 方向的', 4285);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'holding', 'n. 保持，固定', 4286);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'romantic', 'adj. 传奇式的, 浪漫的', 4287);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'treeless', 'adj. 没有树木的', 4288);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'recorder', 'n. 记录员, 记录器', 4289);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seller', 'n. 售货者', 4290);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'noticeably', 'adv. 显著地，显然', 4291);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plunge', 'v& n. 投入, 跳进', 4292);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eradicate', 'v. 根除', 4293);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caste', 'n. 印度的世袭阶级', 4294);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inherit', 'v. 继承', 4295);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gosling', 'n. 小鹅，年轻无知的人', 4296);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'formally', 'adv. 正式地, 形式上', 4297);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rattle', 'v. 嘎嘎作响n咯咯声;吵闹声', 4298);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'residence', 'n. 居住, 住处', 4299);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'antecedent', 'adj. 先行的 n. 祖先', 4300);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stake', 'n. 树桩', 4301);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'disloyalty', 'n. 不忠实', 4302);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'certainty', 'n. 确定, 确实的事情', 4303);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'nystatin', 'n. [微]制霉菌素', 4304);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'compile', 'v. 编译, 编辑', 4305);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prodigious', 'adj. 巨大的, 惊人的', 4306);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mural', 'adj. 墙壁的  n壁画', 4307);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fountain', 'n. 喷泉', 4308);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'gatherer', 'n. 收集者, 收集器', 4309);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shoemaking', 'n. 制鞋', 4310);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electrically', 'adv. 用电力;有关电地', 4311);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'generous', 'adj. 慷慨的,丰富的', 4312);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sprawl', 'v. 伸开', 4313);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'petal', 'n. 花瓣', 4314);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'technologically', 'adv. 科技地', 4315);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'proportionately', 'adv. 相称地, 成比例地', 4316);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'germanium', 'n. 锗', 4317);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'likelihood', 'n. 可能(性)', 4318);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'charter', 'v. 租 n宪章', 4319);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'threshold', 'n. 门槛, 开端', 4320);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sparse', 'adj. 稀少的, 稀疏的', 4321);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statuary', 'n. 雕象', 4322);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypha', 'n. [植]菌丝', 4323);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'farsighted', 'adj. 有先见之明的, 远视的', 4324);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fatten', 'v. 养肥；使肥沃', 4325);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spit', 'n. 唾液 v吐(唾沫)', 4326);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crawl', 'vi&n. 爬行, 蠕动', 4327);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cautious', 'adj. 谨慎的, 小心的', 4328);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expanse', 'n. 广阔；宽阔的区域', 4329);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dawn', 'n. 黎明 vi破晓,开始出现', 4330);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pram', 'n. 婴儿车', 4331);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'purify', 'v. 使纯净', 4332);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'wonderful', 'adj. 精彩的, 极好的', 4333);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Sanskrit', 'n& a. 梵语(的)', 4334);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'orbital', 'adj. 轨道的', 4335);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quit', 'v. 离开, 辞职', 4336);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confront', 'v. 面临, 对抗', 4337);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bison', 'n. (美洲)野牛', 4338);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sideways', 'a&ad. 旁的, 横向的', 4339);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hyksos', 'n. 希克索斯王朝(古埃及王朝之一)', 4340);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'arduous', 'adj. 费力的, 辛勤的', 4341);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boulder', 'n. 大石头', 4342);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'saint', 'n. 圣人, 圣徒', 4343);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bathhouse', 'n. 公共浴室, 澡堂,', 4344);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dilute', 'v. 稀释，冲淡', 4345);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'principally', 'adv. 主要地', 4346);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imbalance', 'n. 不平衡,不均衡', 4347);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ionize', 'v. 使离子化 ,电离', 4348);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'immigration', 'n. 移民入境', 4349);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'agitation', 'n. 鼓动，焦虑', 4350);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'vivid', 'adj. 生动的，栩栩如生的', 4351);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'necessitate', 'v. 使成为必需,迫使', 4352);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Hollywood', 'n. 好莱坞', 4353);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'poverty', 'n. 贫穷, 贫困', 4354);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'blossom', 'n. 花 v. 开花', 4355);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'demographic', 'adj. 人口统计学的', 4356);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'accidentally', 'adj. 意外的,偶然(发生)的', 4357);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shipbuilding', 'n. 造船', 4358);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'duct', 'n. 管道, 导管 vt. 用导管输送', 4359);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sweat', 'n. 汗 v(使)出汗', 4360);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'empirical', 'adj. 经验主义的', 4361);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mediate', 'v. 调停, 斡旋', 4362);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'bloodstream', 'n. 血流', 4363);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verify', 'v. 核实, 证明', 4364);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'reelection', 'n. 再选, 改选', 4365);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dwelling', 'n. 住处', 4366);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'foremost', 'adj. 最重要的,最初的', 4367);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'midair', 'n. 半空中', 4368);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'crocodile', 'n. 鳄鱼, 鳄鱼皮', 4369);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'sister', 'n. 姐妹', 4370);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'calve', 'v. 生小牛, (使)冰山崩解', 4371);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'integration', 'n. 综合', 4372);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'usefulness', 'n. 有用, 有效性', 4373);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'olfactory', 'adj. 嗅觉的', 4374);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cranial', 'adj. 头盖(形)的', 4375);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prerequisite', 'n. 先决条件', 4376);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'occupational', 'adj. 职业的', 4377);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'eclipse', 'n. (日、月)食 vt形成(日、月)食', 4378);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'refute', 'v. 驳斥，驳倒', 4379);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'updraft', 'n. 上升气流', 4380);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'deliberation', 'n. 仔细考虑；商量', 4381);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flagpole', 'n. 旗杆', 4382);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'invoke', 'v. 恳求', 4383);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'hypersensitive', 'adj. 过份敏感的', 4384);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unavoidable', 'adj. 不可避免的', 4385);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lucky', 'adj. 幸运的, 吉祥的', 4386);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'upcoming', 'adj. 即将来临的', 4387);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'February', 'n. 二月(略作Feb)', 4388);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lug', 'v. (用力)拖拉', 4389);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'broadly', 'adv. 宽广地, 广泛', 4390);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'friendship', 'n. 友谊, 友好', 4391);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'twain', 'n. 两, 双, 二', 4392);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pathogen', 'n. [微生物]病菌, 病原体', 4393);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'memorable', 'adj. 难忘的,重大的', 4394);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'auditory', 'adj. 耳的, 听觉的', 4395);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'avant', 'adj. 先锋的,激进的', 4396);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tertiary', 'adj. 第三的, 第三位的', 4397);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'submarine', 'n. 潜水艇', 4398);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locality', 'n. 位置, 地点', 4399);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'questionable', 'adj. 可疑的', 4400);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Inuit', 'n. 因纽特人,  因纽特语', 4401);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'alga', 'n. 藻类,海藻', 4402);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dialect', 'n. 方言', 4403);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'respectively', 'adv. 分别地, 各个地', 4404);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'absent', 'adj. 缺席的；缺乏的', 4405);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'feldspar', 'n. [矿]长石', 4406);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biology', 'n. (生物)学', 4407);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fatal', 'adj. 致命的，灾难性的', 4408);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'romanticism', 'n. 浪漫精神, 浪漫主义', 4409);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'needlework', 'n. 刺绣, 缝纫', 4410);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'palace', 'n. 宫, 宫殿', 4411);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ingenious', 'adj. 设计独特的，巧妙的', 4412);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'framework', 'n. 框架, 体系, 结构', 4413);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'imposition', 'n. 强迫接受', 4414);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meantime', 'n&ad. 同时, 其间', 4415);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'caribou', 'n. 北美产驯鹿(=Rangifer)', 4416);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'attentive', 'adj. 注意的, 留意的', 4417);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lifelong', 'adj. 终生的', 4418);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'August', 'n. 八月(略作Aug)', 4419);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'motionless', 'adj. 不动的, 静止的', 4420);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'renewable', 'adj. 可更新的, 可再生的', 4421);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'aural', 'adj. 听觉的', 4422);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'amateur', 'n. 业余爱好者', 4423);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tangle', 'v. (使)乱作一团 n混乱', 4424);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'onset', 'n. 开始；攻击', 4425);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'flank', 'n. 肋，侧边', 4426);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'ornamental', 'adj. 装饰的  n装饰品', 4427);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'connective', 'adj. 连合的, 连接的', 4428);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'meaningless', 'adj. 无意义的', 4429);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'capitalist', 'adj. 资本主义的 n资本家', 4430);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'estate', 'n. 财产, 地产', 4431);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cenotes', 'n. 天然井', 4432);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mesquite', 'n. 豆科灌木', 4433);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'actively', 'adv. 活跃地, 积极地', 4434);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prison', 'n. 监狱', 4435);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'whistle', 'v. 吹口哨，鸣笛 n哨子', 4436);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'seedling', 'n. 幼苗', 4437);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lace', 'n. 花边,系带 vt用系带束紧', 4438);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'constrict', 'v. 压缩', 4439);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'electromagnetic', 'adj. 电磁的', 4440);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Virginian', 'n. 弗吉尼亚州的人', 4441);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'dryness', 'n. 干燥', 4442);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'locale', 'n. 现场, 场所', 4443);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rodeo', 'n. 马术竞技表演会, 将牛、马驱集在一起', 4444);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'endurance', 'n. 忍耐(力), 持久(力)', 4445);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tribute', 'n. 颂词，称赞', 4446);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mussel', 'n. [动]贻贝, 蚌类', 4447);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cyan', 'n. 蓝绿色, 青色', 4448);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'jungle', 'n. (热带)丛林', 4449);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'clam', 'n. 蛤', 4450);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'angry', 'adj. 发怒的，生气的', 4451);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'usher', 'v. 引，领，陪同', 4452);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'fusion', 'n. 熔化,融合', 4453);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'scarcely', 'adv. 几乎不, 简直没有', 4454);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'herald', 'n. 使者 v. 预报, 标志', 4455);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'mismatch', 'n&v. 配错, 不相匹配', 4456);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'stitch', 'v. 缝, 缝合', 4457);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'suspicious', 'adj. 可疑的,多疑的', 4458);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'monarch', 'n. 君主', 4459);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'extol', 'v. 赞美', 4460);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'squat', 'v. 蹲(下)', 4461);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'rope', 'n. 绳, 索', 4462);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'verse', 'n. 诗(句)', 4463);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spoon', 'n. 匙，调羹', 4464);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chaos', 'n. 混乱，紊乱', 4465);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'prizefight', 'n. 职业拳击赛', 4466);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'inactivity', 'n. 不活动, 迟钝', 4467);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'confident', 'adj. 自信的, 确信的', 4468);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'shipment', 'n. 装船, 出货', 4469);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'unprotected', 'adj. 无保护的, 未做防护措施的', 4470);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'spawn', 'v. 产卵 n. 卵', 4471);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lobe', 'n. 耳垂，(肺，肝等的)叶', 4472);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'plummet', 'n. 铅锤 vi垂直落下', 4473);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'biologically', 'adv. 生物学地', 4474);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'firearm', 'n. 火器,枪炮', 4475);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'communal', 'adj. 公共的，集体的', 4476);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'kick', 'v. 踢', 4477);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'boost', 'v. 推进', 4478);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'linguist', 'n. 语言学家', 4479);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'cortex', 'n. 外皮, （大脑）皮层', 4480);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'objectively', 'adv. 客观地', 4481);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'chilly', 'adj. 寒冷的', 4482);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'artifact', 'n. 人造物品', 4483);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'statesman', 'n. 政治家', 4484);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'curator', 'n. 管理者', 4485);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'tally', 'n. 记分  vi符合', 4486);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'corporation', 'n. 公司, 法人', 4487);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'expertise', 'n. 专门知识(或技能等)，专长', 4488);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'coincide', 'v. 一致, 符合', 4489);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'operator', 'n. 操作员, 技工', 4490);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'originator', 'n. 创始人, 发起人', 4491);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pacifier', 'n. 调停者，和解人', 4492);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'Indus', 'n. 印度河（印度西北部的河流）', 4493);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'asymmetrical', 'adj. 不对称的,不均匀的', 4494);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'lady', 'n. 女士,夫人,小姐', 4495);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'quantifiable', 'adj. 可以计量的, 可量化的', 4496);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'pul', 'n. 普尔(阿富汗辅币单位)', 4497);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'temper', 'n. 脾气,韧度 vt调和', 4498);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'humanness', 'n. 为人,人性', 4499);
INSERT INTO word (book_id, word, meaning, sort_order) VALUES (10, 'companion', 'n. 同伴, 共事者', 4500);
